"""
Tier 0 / AI-native — SEMANTIC activity labeling for tcode-based event logs (rsau_audit_history).
The map below was GENERATED BY THE LLM (Claude) from SAP domain knowledge — not a hand-maintained table.
This is the AI-native foundation step: tcode -> {business activity, process, control-risk}, so a raw audit
log of tcode-starts becomes a labeled PROCESS log. Coverage + the long tail get measured; the tail is what
an LLM enriches on demand (no manual upkeep). Reused by any tcode-based event log we build.

Run:  python process_mining/semantic_activity_map.py   # reports coverage on the live audit log

DEFECTO VIVO (A48, marcado 2026-08-26) -- LEER ANTES DE CITAR NINGUNA CIFRA DE ESTE SCRIPT
    La consulta de main() (ver el bloque ">>> A48 - CAUSA RAIZ" justo encima de ella) agrupa
    por SLGTC, que en las filas
    TXSUBCLSID='Transaction Start' es el tcode LANZADOR, no el ARRANCADO: el arrancado vive
    en PARAM1. Medido: coinciden en 8 de 1.235.225 filas. El defecto esta desde el PRIMER
    commit, asi que TODA cobertura semantica emitida por este script (el titular del 97%)
    esta medida sobre la columna equivocada y NO ES VALIDA.
    El arreglo es cambio de LOGICA y no se hizo en la corrida del 2026-08-26.
"""
import sqlite3
from collections import defaultdict

import os as _os, sys as _sys
_sys.path.insert(0, _os.path.dirname(_os.path.abspath(__file__)))
from gold_ref import GOLD  # T5: resolved via golden_manifest.json, not a hardcoded path
try:  # lo que este proyecto ya aprendio de ESTE instrumento; si falta, el minero sigue corriendo
    from metodo import lo_que_ya_aprendimos as _aprendido
except Exception:
    _aprendido = None

# tcode -> (business activity, process, control-risk-class)   [LLM-generated from SAP knowledge]
SEMANTIC = {
    # navigation (NOT business work — filter these out)
    "SESSION_MANAGER": ("Navigate menu", "_nav", "none"), "S000": ("Logon screen", "_nav", "none"),
    "START_REPORT": ("Run report (generic)", "_nav", "none"), "SE16": ("Browse table data", "_admin", "view-sensitive"),
    "SE16N": ("Browse table data", "_admin", "view-sensitive"), "SM37": ("Monitor jobs", "_admin", "none"),
    # P2P
    "ME21N": ("Create PO", "P2P", "commit"), "ME22N": ("Change PO", "P2P", "commit"),
    "ME23N": ("Display PO", "P2P", "view"), "MIGO": ("Goods movement (GR)", "P2P", "receipt"),
    "MIRO": ("Enter invoice", "P2P", "invoice-entry"), "MIR4": ("Display invoice", "P2P", "view"),
    "MIR7": ("Park invoice", "P2P", "invoice-entry"), "MRBR": ("Release blocked invoice", "P2P", "release"),
    # FI / AP
    "FB60": ("Post vendor invoice", "FI-AP", "invoice-entry"), "FB01": ("Post G/L document", "FI", "posting"),
    "FB50": ("Post G/L (enjoy)", "FI", "posting"), "F-43": ("Post vendor invoice", "FI-AP", "invoice-entry"),
    "FBL1N": ("Vendor line items", "FI-AP", "view"), "FBL3N": ("G/L line items", "FI", "view"),
    "FBL5N": ("Customer line items", "FI-AR", "view"), "FB03": ("Display document", "FI", "view"),
    "FB02": ("Change document", "FI", "edit-posted"), "FBRA": ("Reset cleared items", "FI", "clearing-reversal"),
    "F-44": ("Clear vendor", "FI-AP", "clearing"), "F.13": ("Automatic clearing", "FI", "clearing"),
    # Payment
    "F110": ("Payment run", "Payment", "payment-release"), "F-53": ("Post outgoing payment", "Payment", "payment"),
    "F-58": ("Payment with printout", "Payment", "payment"), "FF67": ("Manual bank statement", "Treasury", "bank"),
    "FEB_BSPROC": ("Bank statement postprocess", "Treasury", "bank"), "FF_5": ("Import bank statement", "Treasury", "bank"),
    # master data (SoD-sensitive)
    "XK01": ("Create vendor (central)", "MDM", "master-create"), "XK02": ("Change vendor (central)", "MDM", "master-edit"),
    "FK01": ("Create vendor (FI)", "MDM", "master-create"), "FK02": ("Change vendor (FI)", "MDM", "master-edit"),
    "FS00": ("Edit G/L account", "MDM", "master-edit"), "FI12": ("Change house bank", "MDM", "bank-master"),
    "SU01": ("Maintain user", "BASIS", "user-admin"), "PFCG": ("Maintain role", "BASIS", "role-admin"),
    # PSM / FM (UNESCO-heavy)
    "FMX3": ("Display FM document", "PSM", "view"), "FMRP_RFFMEP1FX": ("FM line-item report", "PSM", "view"),
    "FMRP_RFFMEP1OX": ("FM commitment report", "PSM", "view"), "FMBB": ("Budgeting", "PSM", "budget"),
    # CUSTOM cockpits (resolved via brain d01_tstc -> program 2026-06-21; the comprehension gap closed).
    # These are where UNESCO's real budget/HR-finance work runs — NOT standard tcodes. The LLM/brain
    # moat: no commercial PM tool knows what YFM1_BCS_V3 / Y_KBLP_PBC_OPEN_N / HUNUEDGR_CONSOLE do.
    "YFM1": ("Budget detail (BCS yearly)", "PSM", "view"),          # YFM1_BCS_V3
    "ZICTP_COCKPIT": ("ICTP operations cockpit", "PSM", "operate"),  # ZICTP_COCKPIT
    "YKBLP_N": ("HR open commitments (PBC)", "PSM-HR", "view"),      # Y_KBLP_PBC_OPEN_N
    "YSC1": ("Support-cost allocation", "FI-CO", "posting"),         # YEBUET01
    "HRPADUNEDGR": ("Education Grant console", "HCM", "benefit"),    # HUNUEDGR_CONSOLE
    "PPOME": ("Change org/staffing", "HCM", "master-edit"), "F13E": ("Automatic clearing (currency)", "FI", "clearing"),
    "FBZ2": ("Post outgoing payment", "Payment", "payment"), "ME2L": ("POs by vendor (report)", "P2P", "view"),
    # control-sensitive: arbitrary program execution
    "SA38": ("Run any program", "_admin", "execute-arbitrary"), "SA39": ("Run program (param tcode)", "_admin", "execute-arbitrary"),
    "SE38": ("ABAP editor / run program", "_admin", "execute-arbitrary"),
}


def main():
    # ANTES de minar: lo ya aprendido de este mismo instrumento. La critica aqui es que en
    # TXSUBCLSID='Transaction Start' el tcode ARRANCADO vive en PARAM1, no en SLGTC.
    # ENMENDADO 2026-08-26 (A48): esa critica YA ESTABA ESCRITA aqui y NO ARREGLA NADA.
    # `avisar()` (metodo.py:89-91) solo hace `p = salida or print`: no lanza excepcion y no
    # llama a sys.exit. O sea que el script imprime la advertencia y A CONTINUACION imprime
    # la cobertura falsa, que es la que acaba en un informe. Una advertencia no es una
    # puerta. PENDIENTE (LOGICA, no hecho hoy): (a) leer TRIM(PARAM1) en vez de SLGTC y
    # quitar el filtro sobre SLGTC; (b) imprimir DOS coberturas y LIDERAR con la de NEGOCIO
    # (excluyendo `_nav` y `_admin` de numerador y denominador), porque el numero que se
    # cita es el que se imprime primero; (c) devolver float en vez de `100*labeled//tot` y
    # guardar el caso tot==0; (d) que `avisar()` reciba una salida que HALTE mientras el
    # instrumento este en state=DEFECTO_VIVO: no deberia poder emitir su cifra.
    if _aprendido:
        _aprendido("rsau_audit_history", "slgtc", "param1", "tcode", "cobertura").avisar()
    c = sqlite3.connect(GOLD, timeout=10)
    # ARREGLADO 2026-08-26 (A48). Lo que habia:
    #     SELECT SLGTC ... WHERE TXSUBCLSID='Transaction Start' AND SLGTC<>'' GROUP BY SLGTC
    # y era el defecto entero. En 'Transaction Start' (MSG='AU3', "Transaction &A started")
    # el tcode ARRANCADO vive en PARAM1; SLGTC es el tcode de CONTEXTO desde el que se lanzo.
    # Coincidian en 8 de 1.235.225 filas. Agrupar por SLGTC histograma EL LANZADOR.
    #
    # Y el filtro SLGTC<>'' no era higiene: descartaba 108.375 arranques (8,8%) de los que
    # 108.168 llevan un tcode real en PARAM1 -- XK02 40.661, FB01 34.008, PR01 17.649...
    # Comprobado que no eran arranques fallidos: descartadas y conservadas comparten MSG,
    # SUBID y SUBCLASID.
    #
    # ⛔ Y NO se arregla con COALESCE(NULLIF(SLGTC,''), PARAM1): eso solo toca el 8,8% con
    # SLGTC vacio y sigue histogramando el lanzador en el 91,2% restante -- arreglaria la
    # parte visible y ocultaria la causa, dandolo por cerrado. El canal declarado en
    # capability_U_USAGE_execution_footprint.md:34 y en sap_process_mining/SKILL.md:94 es
    # PARAM1 A SECAS.
    rows = c.execute("SELECT TRIM(PARAM1), COUNT(*) FROM rsau_audit_history "
                     "WHERE TXSUBCLSID='Transaction Start' AND TRIM(PARAM1)<>'' "
                     "GROUP BY 1").fetchall()
    tot = sum(n for _, n in rows)
    labeled = sum(n for tc, n in rows if tc in SEMANTIC)
    distinct_cov = sum(1 for tc, _ in rows if tc in SEMANTIC)
    if not tot:
        print("0 arranques en la ventana: no hay nada que medir (y NO es 0% de cobertura)")
        return 0

    # DOS COBERTURAS, Y LIDERA LA DE NEGOCIO. El titular anterior decia 97% y el 92,7% de lo
    # etiquetado era `_nav` -- SESSION_MANAGER y S000, que es justo el LANZADOR y que este
    # mismo fichero declara arriba que no es trabajo de negocio. El numero que la gente cita
    # es el que se imprime PRIMERO, asi que el primero tiene que ser el honesto.
    RUIDO = ("_nav", "_admin")
    neg = [(tc, n) for tc, n in rows if SEMANTIC.get(tc, ("", "", ""))[1] not in RUIDO]
    neg_tot = sum(n for _, n in neg)
    neg_lab = sum(n for tc, n in neg if tc in SEMANTIC)
    print(f"arranques (PARAM1) en Transaction Start: {tot:,} eventos / "
          f"{len(rows):,} tcodes distintos")
    print(f"cobertura de NEGOCIO: {100.0*neg_lab/neg_tot:.1f}% del volumen "
          f"({neg_lab:,} de {neg_tot:,}) -- excluye _nav y _admin de numerador Y denominador")
    print(f"cobertura total     : {100.0*labeled/tot:.1f}% del volumen, "
          f"{distinct_cov}/{len(rows)} tcodes distintos mapeados")
    print("\n-- volume by PROCESS (labeled) --")
    byproc = defaultdict(int)
    for tc, n in rows:
        if tc in SEMANTIC: byproc[SEMANTIC[tc][1]] += n
    for p, n in sorted(byproc.items(), key=lambda x: -x[1]):
        print(f"  {n:>8,}  {p}")
    print("\n-- top UNLABELED tcodes (the long tail the LLM enriches on demand) --")
    for tc, n in sorted([(tc, n) for tc, n in rows if tc not in SEMANTIC], key=lambda x: -x[1])[:12]:
        print(f"  {n:>7,}  {tc}")


if __name__ == "__main__":
    main()
