"""
Tier 0 / AI-native — SEMANTIC activity labeling for tcode-based event logs (rsau_audit_history).
The map below was GENERATED BY THE LLM (Claude) from SAP domain knowledge — not a hand-maintained table.
This is the AI-native foundation step: tcode -> {business activity, process, control-risk}, so a raw audit
log of tcode-starts becomes a labeled PROCESS log. Coverage + the long tail get measured; the tail is what
an LLM enriches on demand (no manual upkeep). Reused by any tcode-based event log we build.

Run:  python process_mining/semantic_activity_map.py   # reports coverage on the live audit log
"""
import sqlite3
from collections import defaultdict

import os as _os, sys as _sys
_sys.path.insert(0, _os.path.dirname(_os.path.abspath(__file__)))
from gold_ref import GOLD  # T5: resolved via golden_manifest.json, not a hardcoded path

# tcode -> (business activity, process, control-risk-class)   [LLM-generated from SAP knowledge]
SEMANTIC = {
    # navigation (NOT business work — filter these out)
    "SESSION_MANAGER": ("Navigate menu", "_nav", "none"), "S000": ("Logon screen", "_nav", "none"),
    "START_REPORT": ("Run report (generic)", "_nav", "none"), "SE16": ("Browse table data", "_admin", "view-sensitive"),
    "SE16N": ("Browse table data", "_admin", "view-sensitive"), "SM37": ("Monitor jobs", "_admin", "none"),
    # P2P
    "ME21N": ("Create PO", "P2P", "commit"), "ME22N": ("Change PO", "P2P", "commit"),
    "ME23N": ("Display PO", "P2P", "view"), "MIGO": ("Goods movement (GR)", "P2P", "receipt"),
    "MIRO": ("Enter invoice", "P2P", "invoice-entry"), "MIR4": ("Display invoice", "P2P", "view"),
    "MIR7": ("Park invoice", "P2P", "invoice-entry"), "MRBR": ("Release blocked invoice", "P2P", "release"),
    # FI / AP
    "FB60": ("Post vendor invoice", "FI-AP", "invoice-entry"), "FB01": ("Post G/L document", "FI", "posting"),
    "FB50": ("Post G/L (enjoy)", "FI", "posting"), "F-43": ("Post vendor invoice", "FI-AP", "invoice-entry"),
    "FBL1N": ("Vendor line items", "FI-AP", "view"), "FBL3N": ("G/L line items", "FI", "view"),
    "FBL5N": ("Customer line items", "FI-AR", "view"), "FB03": ("Display document", "FI", "view"),
    "FB02": ("Change document", "FI", "edit-posted"), "FBRA": ("Reset cleared items", "FI", "clearing-reversal"),
    "F-44": ("Clear vendor", "FI-AP", "clearing"), "F.13": ("Automatic clearing", "FI", "clearing"),
    # Payment
    "F110": ("Payment run", "Payment", "payment-release"), "F-53": ("Post outgoing payment", "Payment", "payment"),
    "F-58": ("Payment with printout", "Payment", "payment"), "FF67": ("Manual bank statement", "Treasury", "bank"),
    "FEB_BSPROC": ("Bank statement postprocess", "Treasury", "bank"), "FF_5": ("Import bank statement", "Treasury", "bank"),
    # master data (SoD-sensitive)
    "XK01": ("Create vendor (central)", "MDM", "master-create"), "XK02": ("Change vendor (central)", "MDM", "master-edit"),
    "FK01": ("Create vendor (FI)", "MDM", "master-create"), "FK02": ("Change vendor (FI)", "MDM", "master-edit"),
    "FS00": ("Edit G/L account", "MDM", "master-edit"), "FI12": ("Change house bank", "MDM", "bank-master"),
    "SU01": ("Maintain user", "BASIS", "user-admin"), "PFCG": ("Maintain role", "BASIS", "role-admin"),
    # PSM / FM (UNESCO-heavy)
    "FMX3": ("Display FM document", "PSM", "view"), "FMRP_RFFMEP1FX": ("FM line-item report", "PSM", "view"),
    "FMRP_RFFMEP1OX": ("FM commitment report", "PSM", "view"), "FMBB": ("Budgeting", "PSM", "budget"),
    # CUSTOM cockpits (resolved via brain d01_tstc -> program 2026-06-21; the comprehension gap closed).
    # These are where UNESCO's real budget/HR-finance work runs — NOT standard tcodes. The LLM/brain
    # moat: no commercial PM tool knows what YFM1_BCS_V3 / Y_KBLP_PBC_OPEN_N / HUNUEDGR_CONSOLE do.
    "YFM1": ("Budget detail (BCS yearly)", "PSM", "view"),          # YFM1_BCS_V3
    "ZICTP_COCKPIT": ("ICTP operations cockpit", "PSM", "operate"),  # ZICTP_COCKPIT
    "YKBLP_N": ("HR open commitments (PBC)", "PSM-HR", "view"),      # Y_KBLP_PBC_OPEN_N
    "YSC1": ("Support-cost allocation", "FI-CO", "posting"),         # YEBUET01
    "HRPADUNEDGR": ("Education Grant console", "HCM", "benefit"),    # HUNUEDGR_CONSOLE
    "PPOME": ("Change org/staffing", "HCM", "master-edit"), "F13E": ("Automatic clearing (currency)", "FI", "clearing"),
    "FBZ2": ("Post outgoing payment", "Payment", "payment"), "ME2L": ("POs by vendor (report)", "P2P", "view"),
    # control-sensitive: arbitrary program execution
    "SA38": ("Run any program", "_admin", "execute-arbitrary"), "SA39": ("Run program (param tcode)", "_admin", "execute-arbitrary"),
    "SE38": ("ABAP editor / run program", "_admin", "execute-arbitrary"),
}


def main():
    c = sqlite3.connect(GOLD, timeout=10)
    rows = c.execute("SELECT SLGTC, COUNT(*) FROM rsau_audit_history WHERE TXSUBCLSID='Transaction Start' "
                     "AND SLGTC<>'' GROUP BY SLGTC").fetchall()
    tot = sum(n for _, n in rows)
    labeled = sum(n for tc, n in rows if tc in SEMANTIC)
    distinct_cov = sum(1 for tc, _ in rows if tc in SEMANTIC)
    print(f"audit-log tcode-starts: {tot:,} events / {len(rows):,} distinct tcodes")
    print(f"semantic coverage: {100*labeled//tot}% of volume, {distinct_cov}/{len(rows)} distinct tcodes mapped")
    print("\n-- volume by PROCESS (labeled) --")
    byproc = defaultdict(int)
    for tc, n in rows:
        if tc in SEMANTIC: byproc[SEMANTIC[tc][1]] += n
    for p, n in sorted(byproc.items(), key=lambda x: -x[1]):
        print(f"  {n:>8,}  {p}")
    print("\n-- top UNLABELED tcodes (the long tail the LLM enriches on demand) --")
    for tc, n in sorted([(tc, n) for tc, n in rows if tc not in SEMANTIC], key=lambda x: -x[1])[:12]:
        print(f"  {n:>7,}  {tc}")


if __name__ == "__main__":
    main()
