*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZ_WF_FI_GET_CLASSIC_VALIDU01.
                    "Z_WF_FI_PR_WF_ACTOR1_DET