PROGRAM /1PAPA/FEAT350YYCDR.
* Compilation of YYCDR
FORM CALL_549B USING BACK STATUS STRUC STRUCTURE PC205.
SET EXTENDED CHECK OFF.
CASE STRUC-PERSG .
WHEN '1' .
CASE STRUC-GSBER .
WHEN 'GEF ' .
CASE STRUC-WERKS .
WHEN 'BE00' .
BACK = 'Y' .
WHEN 'DE00' .
BACK = 'Y' .
WHEN 'FR00' .
BACK = 'Y' .
WHEN 'IT00' .
BACK = 'Y' .
WHEN 'NL00' .
BACK = 'Y' .
WHEN OTHERS .
BACK = '' .
ENDCASE.
WHEN '*** ' .
BACK = '' .
WHEN OTHERS .
BACK = '' .
ENDCASE.
WHEN '2' .
CASE STRUC-GSBER .
WHEN 'GEF ' .
CASE STRUC-WERKS .
WHEN 'BE00' .
BACK = 'Y' .
WHEN 'DE00' .
BACK = 'Y' .
WHEN 'FR00' .
BACK = 'Y' .
WHEN 'IT00' .
BACK = 'Y' .
WHEN 'NL00' .
BACK = 'Y' .
WHEN OTHERS .
BACK = '' .
ENDCASE.
WHEN '*** ' .
BACK = '' .
WHEN OTHERS .
BACK = '' .
ENDCASE.
WHEN '3' .
CASE STRUC-GSBER .
WHEN 'GEF ' .
CASE STRUC-WERKS .
WHEN 'DE00' .
BACK = 'Y' .
WHEN 'FR00' .
BACK = 'Y' .
WHEN 'IT00' .
BACK = 'Y' .
WHEN 'NL00' .
BACK = 'Y' .
WHEN OTHERS .
BACK = '' .
ENDCASE.
WHEN '*** ' .
BACK = '' .
WHEN OTHERS .
BACK = '' .
ENDCASE.
WHEN 'M' .
CASE STRUC-GSBER .
WHEN 'GEF ' .
CASE STRUC-WERKS .
WHEN 'BE00' .
BACK = '' .
WHEN 'DE00' .
BACK = '' .
WHEN 'FR00' .
BACK = 'Y' .
WHEN 'IT00' .
BACK = '' .
WHEN 'NL00' .
BACK = '' .
WHEN OTHERS .
BACK = '' .
ENDCASE.
WHEN '*** ' .
BACK = '' .
WHEN OTHERS .
BACK = '' .
ENDCASE.
WHEN 'O' .
CASE STRUC-GSBER .
WHEN 'GEF ' .
CASE STRUC-WERKS .
WHEN 'BE00' .
BACK = 'Y' .
WHEN 'DE00' .
BACK = 'Y' .
WHEN 'FR00' .
BACK = 'Y' .
WHEN 'IT00' .
BACK = 'Y' .
WHEN 'NL00' .
BACK = 'Y' .
WHEN OTHERS .
BACK = '' .
ENDCASE.
WHEN '*** ' .
BACK = '' .
WHEN OTHERS .
BACK = '' .
ENDCASE.
WHEN OTHERS .
BACK = '' .
ENDCASE.
SET EXTENDED CHECK ON.
ENDFORM.