REPORT YAM_TDHIST_REP LINE-SIZE 200.

TABLES: ANKT, ANLA, ANLZ, PA0002, PA0003, T499S.

SELECTION-SCREEN BEGIN OF BLOCK BMAIN WITH FRAME.
PARAMETERS: P_BUKRS LIKE ANLA-BUKRS OBLIGATORY DEFAULT 'UNES'.

SELECT-OPTIONS: P_ANLN1 FOR ANLA-ANLN1,
                P_ANLKL FOR ANLA-ANLKL,
                P_GSBER FOR ANLZ-GSBER,
                P_KOSTL FOR ANLZ-KOSTL MATCHCODE OBJECT KOST,
                P_WERKS FOR ANLZ-WERKS OBLIGATORY DEFAULT '0002',
                P_STORT FOR ANLZ-STORT,
                P_PERNR FOR ANLZ-PERNR MATCHCODE OBJECT PREM.

SELECTION-SCREEN SKIP.
SELECTION-SCREEN END OF BLOCK BMAIN.
PARAMETERS: P_DLINE AS CHECKBOX.


DATA: BEGIN OF T_ITAB OCCURS 0,
        BUKRS LIKE ANLA-BUKRS,
        ANLKL LIKE ANLA-ANLKL,
        TXK50 LIKE ANKT-TXK50,
        ANLN1 LIKE ANLA-ANLN1,
        ANLN2 LIKE ANLA-ANLN2,
        INVNR LIKE ANLA-INVNR,
        TXT50 LIKE ANLA-TXT50,
        BDATU LIKE ANLZ-BDATU,
        ADATU LIKE ANLZ-ADATU,
        GSBER LIKE ANLZ-GSBER,
        KOSTL LIKE ANLZ-KOSTL,
        WERKS LIKE ANLZ-WERKS,
        STORT LIKE ANLZ-STORT,
        KTEXT LIKE T499S-KTEXT,
        PERNR LIKE ANLZ-PERNR,
        NACHN LIKE PA0002-NACHN,
        VORNA LIKE PA0002-VORNA,
      END OF T_ITAB.

DATA: W_COLOR,
      W_PNAME(60).


START-OF-SELECTION.

CLEAR ANLZ.
SELECT *
      FROM ANLZ
      WHERE BUKRS = P_BUKRS
        AND ANLN1 IN P_ANLN1.

  CHECK ANLZ-GSBER IN P_GSBER.
  CHECK ANLZ-KOSTL IN P_KOSTL.
  CHECK ANLZ-WERKS IN P_WERKS.
  CHECK ANLZ-STORT IN P_STORT.
  CHECK ANLZ-PERNR IN P_PERNR.

  CLEAR T_ITAB.
  MOVE-CORRESPONDING ANLZ TO T_ITAB.

  CLEAR ANLA.
  SELECT SINGLE *
        FROM ANLA
        WHERE BUKRS = ANLZ-BUKRS
          AND ANLN1 = ANLZ-ANLN1
          AND ANLN2 = ANLZ-ANLN2.
  CHECK ANLA-ANLKL IN P_ANLKL.

  CLEAR ANKT.
  SELECT SINGLE *
        FROM ANKT
        WHERE SPRAS = SY-LANGU
          AND ANLKL = ANLA-ANLKL.

  T_ITAB-ANLKL = ANLA-ANLKL.
  T_ITAB-TXK50 = ANKT-TXK50.
  T_ITAB-INVNR = ANLA-INVNR.
  T_ITAB-TXT50 = ANLA-TXT50.

  CLEAR T499S.
  SELECT SINGLE *
        FROM T499S
        WHERE WERKS = ANLZ-WERKS
          AND STAND = ANLZ-STORT.
  T_ITAB-KTEXT = T499S-KTEXT.

  CLEAR PA0003.
  SELECT SINGLE *
        FROM PA0003
        WHERE PERNR = ANLZ-PERNR.
    CLEAR PA0002.
    SELECT SINGLE *
          FROM PA0002
          WHERE PERNR = PA0003-PERNR
            AND SUBTY = PA0003-SUBTY
            AND OBJPS = PA0003-OBJPS
            AND SPRPS = PA0003-SPRPS
*            and endda = pa0003-endda
*            and begda = pa0003-begda
            AND SEQNR = PA0003-SEQNR.
    T_ITAB-NACHN = PA0002-NACHN.
    T_ITAB-VORNA = PA0002-VORNA.

    APPEND T_ITAB.
ENDSELECT. "anlz

END-OF-SELECTION.


SORT T_ITAB.
CLEAR: T_ITAB, W_COLOR.
LOOP AT T_ITAB.
  AT NEW TXK50.
    FORMAT COLOR 3 INTENSIFIED ON.
    WRITE: /
           'Class',
           T_ITAB-ANLKL,
           '-',
           T_ITAB-TXK50,
           198 '...'.
  ENDAT. "new anlkl
  IF W_COLOR = 1.
    FORMAT COLOR 2 INTENSIFIED ON.
    CLEAR W_COLOR.
   ELSE.
     FORMAT COLOR 2 INTENSIFIED OFF.
     W_COLOR = 1.
  ENDIF. "w_color
  CLEAR W_PNAME.
  CONCATENATE T_ITAB-VORNA T_ITAB-NACHN INTO W_PNAME
             SEPARATED BY SPACE.
  CONDENSE W_PNAME.
  CONDENSE T_ITAB-INVNR.
  WRITE: /
         T_ITAB-ANLN1,
         T_ITAB-INVNR(12),
         T_ITAB-TXT50,
         T_ITAB-ADATU,
         T_ITAB-BDATU,
         T_ITAB-GSBER,
         T_ITAB-KOSTL,
*         t_itab-werks,
         T_ITAB-STORT,
*         t_itab-ktext,
         T_ITAB-PERNR,
         W_PNAME.
  HIDE: T_ITAB-BUKRS, T_ITAB-ANLN1, T_ITAB-ANLN2.
  IF P_DLINE = 'X'.
    AT END OF ANLN1.
      ULINE.
*      skip.
    ENDAT.
  ENDIF. "p_dline
ENDLOOP. "t_itab


AT LINE-SELECTION.
  SET PARAMETER ID 'BUK' FIELD T_ITAB-BUKRS.
  SET PARAMETER ID 'AN1' FIELD T_ITAB-ANLN1.
  SET PARAMETER ID 'AN2' FIELD T_ITAB-ANLN2.
  CALL TRANSACTION 'AS03' AND SKIP FIRST SCREEN.