REPORT YAM_ZUGDT_CLR.

TABLES: ANLA.


PARAMETERS: P_BUKRS LIKE ANLA-BUKRS DEFAULT 'UNES'.
SELECT-OPTIONS: P_ANLN1 FOR ANLA-ANLN1.


DATA: BEGIN OF T_ANLA OCCURS 0.
        INCLUDE STRUCTURE ANLA.
DATA: END OF T_ANLA.

START-OF-SELECTION.

REFRESH T_ANLA.

CLEAR ANLA.
SELECT *
      FROM ANLA
      INTO TABLE T_ANLA
      WHERE BUKRS = P_BUKRS
        AND ANLN1 IN P_ANLN1.


CLEAR T_ANLA.
LOOP AT T_ANLA.
  CLEAR: T_ANLA-ZUGDT,
         T_ANLA-ZUPER,
         T_ANLA-ZUJHR,
         T_ANLA-XAFABCH.
  UPDATE ANLA FROM T_ANLA.
ENDLOOP. "t_anla

END-OF-SELECTION.