*&---------------------------------------------------------------------*
*& Report  YAM_AMOUNTS_REPORT                                          *
*&                                                                     *
*&---------------------------------------------------------------------*
*&                                                                     *
*&                                                                     *
*&---------------------------------------------------------------------*

REPORT  YAM_AMOUNTS_REPORT LINE-SIZE 120 LINE-COUNT 90.

TABLES: ANLA,
        ANKT,
        ANLC,
        YAM_CLGROUP.


PARAMETERS: P_BUKRS LIKE T001-BUKRS OBLIGATORY DEFAULT 'UNES',
            P_YEAR  LIKE ANLC-GJAHR OBLIGATORY DEFAULT SY-DATUM(4),
            P_AFABE LIKE ANLC-AFABE OBLIGATORY DEFAULT '01'.

SELECT-OPTIONS: P_ANLKL FOR ANKT-ANLKL.

SELECTION-SCREEN BEGIN OF BLOCK B_TOTRB WITH FRAME TITLE TEXT-002.
PARAMETERS: P_CLASS RADIOBUTTON GROUP RBG1 DEFAULT 'X',
            P_GROUP RADIOBUTTON GROUP RBG1.
SELECTION-SCREEN END OF BLOCK B_TOTRB.

SELECTION-SCREEN SKIP.

SELECTION-SCREEN BEGIN OF BLOCK B_ATTRACT WITH FRAME TITLE TEXT-001.
SELECT-OPTIONS: P_ATTRCL FOR ANKT-ANLKL NO INTERVALS.
PARAMETERS: P_ATTRAM LIKE ANLC-KANSW.
SELECTION-SCREEN END OF BLOCK B_ATTRACT.


CONSTANTS: C_V01 TYPE I VALUE  1000,
           C_V02 TYPE I VALUE  2500,
           C_V03 TYPE I VALUE  5000,
           C_V04 TYPE I VALUE 10000,
           C_T01(30) VALUE 'Value <= 1000,00',
           C_T02(30) VALUE '1000,00 < Value <= 2500,00',
           C_T03(30) VALUE '2500,00 < Value <= 5000,00',
           C_T04(30) VALUE '5000,00 < Value <= 10000,00',
           C_T05(30) VALUE '10000,00 < Value'.


DATA: BEGIN OF T_AMOUNT_RANGES OCCURS 0,
       LINDX(3),
       LIMIT(30),
       GRTXT  LIKE YAM_CLGROUP-GRTXT,
       GROUP  TYPE N LENGTH 8,
       ANLKL  LIKE ANKT-ANLKL,
       TXK50  LIKE ANKT-TXK50,
       QUANT  TYPE I,
       AMOUNT LIKE ANLC-KANSW,
      END OF T_AMOUNT_RANGES.

DATA: BEGIN OF T_LV_OBJS OCCURS 0,
       ANLKL  LIKE ANKT-ANLKL,
       TXK50  LIKE ANKT-TXK50,
       QUANT  TYPE I,
       AMOUNT LIKE ANLC-KANSW,
      END OF T_LV_OBJS.

DATA: W_LOW_AMOUNT LIKE ANLC-KANSW.

START-OF-SELECTION.

REFRESH: T_AMOUNT_RANGES, T_LV_OBJS.

CLEAR ANLA.
SELECT *
      FROM ANLA
      WHERE BUKRS = P_BUKRS
        AND ANLKL IN P_ANLKL.

  CHECK ANLA-DEAKT IS INITIAL.
  CLEAR ANLC.
  SELECT SINGLE *
        FROM ANLC
        WHERE BUKRS = ANLA-BUKRS
          AND ANLN1 = ANLA-ANLN1
          AND ANLN2 = ANLA-ANLN2
          AND GJAHR = P_YEAR
          AND AFABE = P_AFABE.

  IF ANLC-KANSW > 0.
    CLEAR T_AMOUNT_RANGES.
    T_AMOUNT_RANGES-GROUP = ANLA-ANLKL(3).
    T_AMOUNT_RANGES-ANLKL = ANLA-ANLKL.
    T_AMOUNT_RANGES-QUANT = 1.
    T_AMOUNT_RANGES-AMOUNT = ANLC-KANSW.
    IF ANLC-KANSW <= C_V01.
      T_AMOUNT_RANGES-LINDX = '001'.
      T_AMOUNT_RANGES-LIMIT = C_T01.
     ELSEIF ANLC-KANSW > C_V01 AND ANLC-KANSW <= C_V02.
       T_AMOUNT_RANGES-LINDX = '002'.
       T_AMOUNT_RANGES-LIMIT = C_T02.
      ELSEIF ANLC-KANSW > C_V02 AND ANLC-KANSW <= C_V03.
        T_AMOUNT_RANGES-LINDX = '003'.
        T_AMOUNT_RANGES-LIMIT = C_T03.
       ELSEIF ANLC-KANSW > C_V03 AND ANLC-KANSW <= C_V04.
         T_AMOUNT_RANGES-LINDX = '004'.
         T_AMOUNT_RANGES-LIMIT = C_T04.
        ELSEIF ANLC-KANSW > C_V04.
          T_AMOUNT_RANGES-LINDX = '005'.
          T_AMOUNT_RANGES-LIMIT = C_T05.
    ENDIF. "anlc-kansw
    COLLECT T_AMOUNT_RANGES.
  ENDIF. "anlc-kansw > 0
ENDSELECT. "anla


CLEAR T_AMOUNT_RANGES.
LOOP AT T_AMOUNT_RANGES.
  CLEAR YAM_CLGROUP.
  SELECT SINGLE *
               FROM YAM_CLGROUP
               WHERE SPRAS = SY-LANGU
                 AND CLGRP = T_AMOUNT_RANGES-GROUP.
  T_AMOUNT_RANGES-GRTXT = YAM_CLGROUP-GRTXT.

  CLEAR ANKT.
  SELECT SINGLE *
               FROM ANKT
               WHERE SPRAS = SY-LANGU
                 AND ANLKL = T_AMOUNT_RANGES-ANLKL.
  T_AMOUNT_RANGES-TXK50 = ANKT-TXK50.
  MODIFY T_AMOUNT_RANGES.
ENDLOOP. "t_amount_ranges


CLEAR ANLA.
SELECT *
      FROM ANLA
      WHERE BUKRS = P_BUKRS
        AND ANLKL IN P_ATTRCL.

  CHECK ANLA-DEAKT IS INITIAL.
  CLEAR ANLC.
  SELECT SINGLE *
        FROM ANLC
        WHERE BUKRS = ANLA-BUKRS
          AND ANLN1 = ANLA-ANLN1
          AND ANLN2 = ANLA-ANLN2
          AND GJAHR = P_YEAR
          AND AFABE = P_AFABE.
  IF ANLC-KANSW >= P_ATTRAM.
    CLEAR T_LV_OBJS.
    T_LV_OBJS-ANLKL = ANLA-ANLKL.
    T_LV_OBJS-QUANT = 1.
    T_LV_OBJS-AMOUNT = ANLC-KANSW.
    COLLECT T_LV_OBJS.
  ENDIF. "anlc-kansw
ENDSELECT. "anla

CLEAR T_LV_OBJS.
LOOP AT T_LV_OBJS.
  CLEAR ANKT.
  SELECT SINGLE *
               FROM ANKT
               WHERE SPRAS = SY-LANGU
                 AND ANLKL = T_LV_OBJS-ANLKL.
  T_LV_OBJS-TXK50 = ANKT-TXK50.
  MODIFY T_LV_OBJS.
ENDLOOP. "t_lv_objs

END-OF-SELECTION.

SORT T_AMOUNT_RANGES BY LINDX ANLKL.
LOOP AT T_AMOUNT_RANGES.
  IF P_CLASS = 'X'.
    WRITE: /
           T_AMOUNT_RANGES-LIMIT,
           T_AMOUNT_RANGES-ANLKL,
           T_AMOUNT_RANGES-TXK50,
           T_AMOUNT_RANGES-AMOUNT,
           T_AMOUNT_RANGES-QUANT.
  ENDIF. "p_class

  IF P_GROUP = 'X'.
    AT END OF GROUP.
      SUM.
      WRITE: /
             T_AMOUNT_RANGES-LIMIT,
             T_AMOUNT_RANGES-GROUP+5(3), '   ',
             T_AMOUNT_RANGES-GRTXT,
             T_AMOUNT_RANGES-AMOUNT,
             T_AMOUNT_RANGES-QUANT.
    ENDAT. "group
  ENDIF. "p_group

  AT END OF LIMIT.
    SUM.
    FORMAT COLOR 3.
    WRITE: /
           T_AMOUNT_RANGES-LIMIT,
           T_AMOUNT_RANGES-ANLKL,
           T_AMOUNT_RANGES-TXK50,
           T_AMOUNT_RANGES-AMOUNT,
           T_AMOUNT_RANGES-QUANT.
    FORMAT COLOR OFF.
  ENDAT. "limit

  AT LAST.
    SUM.
    FORMAT COLOR 3 INTENSIFIED OFF.
    WRITE: /
           T_AMOUNT_RANGES-LIMIT,
           T_AMOUNT_RANGES-ANLKL,
           T_AMOUNT_RANGES-TXK50,
           T_AMOUNT_RANGES-AMOUNT,
           T_AMOUNT_RANGES-QUANT.
    WRITE: 4 'Total'.
    FORMAT COLOR OFF.
  ENDAT. "last
ENDLOOP.

SKIP 2.
ULINE.
NEW-PAGE.

FORMAT COLOR 2.
WRITE: / 'Low-value attractive objects:'.
FORMAT COLOR OFF.

SORT T_LV_OBJS.
LOOP AT T_LV_OBJS.
  WRITE: / P_ATTRAM LEFT-JUSTIFIED, 10 '<= Value',
      32 T_LV_OBJS-ANLKL,
         T_LV_OBJS-TXK50,
         T_LV_OBJS-AMOUNT,
         T_LV_OBJS-QUANT.

  AT LAST.
    SUM.
    FORMAT COLOR 3.
    WRITE: / ' ',
        32 T_LV_OBJS-ANLKL,
           T_LV_OBJS-TXK50,
           T_LV_OBJS-AMOUNT,
           T_LV_OBJS-QUANT.
    WRITE: 4 'Total on low-value objects'.
    FORMAT COLOR OFF.
  ENDAT.
ENDLOOP. "endat