* ==== CLASS POOL YCL_FI_RFBIBL00_SHM_AREA ====
CLASS-POOL .
*"* class pool for class YCL_FI_RFBIBL00_SHM_AREA

*"* local type definitions
INCLUDE YCL_FI_RFBIBL00_SHM_AREA======CCDEF.

*"* class YCL_FI_RFBIBL00_SHM_AREA definition
*"* public declarations
  INCLUDE YCL_FI_RFBIBL00_SHM_AREA======CU.
*"* protected declarations
  INCLUDE YCL_FI_RFBIBL00_SHM_AREA======CO.
*"* private declarations
  INCLUDE YCL_FI_RFBIBL00_SHM_AREA======CI.
ENDCLASS. "YCL_FI_RFBIBL00_SHM_AREA definition

*"* macro definitions
INCLUDE YCL_FI_RFBIBL00_SHM_AREA======CCMAC.
*"* local class implementation
INCLUDE YCL_FI_RFBIBL00_SHM_AREA======CCIMP.

CLASS YCL_FI_RFBIBL00_SHM_AREA IMPLEMENTATION.
*"* method's implementations
  INCLUDE METHODS.
ENDCLASS. "YCL_FI_RFBIBL00_SHM_AREA implementation


* ---- YCL_FI_RFBIBL00_SHM_AREA======CI ----
PRIVATE SECTION.

  CONSTANTS _VERSION_ TYPE I VALUE 23 ##NO_TEXT.
  CLASS-DATA _TRACE_SERVICE TYPE REF TO IF_SHM_TRACE .
  CLASS-DATA _TRACE_ACTIVE TYPE ABAP_BOOL VALUE ABAP_FALSE ##NO_TEXT.
  CONSTANTS _TRANSACTIONAL TYPE ABAP_BOOL VALUE ABAP_FALSE ##NO_TEXT.
  CONSTANTS _CLIENT_DEPENDENT TYPE ABAP_BOOL VALUE ABAP_TRUE ##NO_TEXT.
  CONSTANTS _LIFE_CONTEXT TYPE SHM_LIFE_CONTEXT VALUE CL_SHM_AREA=>LIFE_CONTEXT_MEMORY ##NO_TEXT.

* ---- YCL_FI_RFBIBL00_SHM_AREA======CM001 ----
  METHOD SET_ROOT.

  DATA:
    L_CX TYPE REF TO CX_ROOT.

  IF _TRACE_ACTIVE = ABAP_FALSE OR
  _TRACE_SERVICE->VARIANT-SET_ROOT = ABAP_FALSE.

*   >
    _SET_ROOT( ROOT ).
    ME->ROOT = ROOT.
*   <

  ELSE.

    TRY.

*       >
        _SET_ROOT( ROOT ).
        ME->ROOT = ROOT.
*       <
        _TRACE_SERVICE->TRIN_SET_ROOT(
          AREA_NAME         = AREA_NAME
          INST_NAME         = INST_NAME
          ROOT              = ROOT
        ).

      CLEANUP INTO L_CX.
        _TRACE_SERVICE->TRCX_SET_ROOT(
          AREA_NAME         = AREA_NAME
          INST_NAME         = INST_NAME
          ROOT              = ROOT
          CX                = L_CX
        ).
    ENDTRY.

  ENDIF.

  ENDMETHOD.

* ---- YCL_FI_RFBIBL00_SHM_AREA======CM002 ----
  METHOD CLASS_CONSTRUCTOR.

* TRACE { DO NOT REMOVE THIS LINE !
  _TRACE_ACTIVE = ABAP_FALSE.
  TRY.
      _TRACE_SERVICE =
        CL_SHM_SERVICE=>TRACE_GET_SERVICE( AREA_NAME ).
      IF NOT _TRACE_SERVICE IS INITIAL.
        _TRACE_ACTIVE =
          CL_SHM_SERVICE=>TRACE_IS_VARIANT_ACTIVE(
            _TRACE_SERVICE->VARIANT-DEF_NAME
          ).
      ENDIF.
    CATCH CX_ROOT. "#EC NO_HANDLER
                   "#EC CATCH_ALL
  ENDTRY.
* TRACE } DO NOT REMOVE THIS LINE !

  ENDMETHOD.

* ---- YCL_FI_RFBIBL00_SHM_AREA======CM003 ----
  METHOD GET_GENERATOR_VERSION.
  GENERATOR_VERSION = _VERSION_.
  ENDMETHOD.

* ---- YCL_FI_RFBIBL00_SHM_AREA======CM004 ----
  METHOD ATTACH_FOR_READ.

  DATA:
    L_ATTRIBUTES       TYPE SHMA_ATTRIBUTES,
    L_ROOT             TYPE REF TO OBJECT,
    L_CX               TYPE REF TO CX_ROOT,
    L_CLIENT           TYPE SHM_CLIENT,
    L_CLIENT_SUPPLIED  TYPE ABAP_BOOL. "#EC NEEDED

* check if tracing should be activated/de-activated
  IF  ( NOT _TRACE_SERVICE IS INITIAL ).
    TRY.
        _TRACE_ACTIVE =
          CL_SHM_SERVICE=>TRACE_IS_VARIANT_ACTIVE(
            _TRACE_SERVICE->VARIANT-DEF_NAME
          ).
      CATCH CX_ROOT. "#EC NO_HANDLER
                     "#EC CATCH_ALL
    ENDTRY.
  ENDIF.


  IF _TRACE_ACTIVE = ABAP_FALSE OR
  _TRACE_SERVICE->VARIANT-ATTACH_FOR_READ = ABAP_FALSE.

*   >

    CREATE OBJECT HANDLE.

    HANDLE->CLIENT    = L_CLIENT.
    HANDLE->INST_NAME = INST_NAME.

*   try sneak mode first
    HANDLE->_ATTACH_READ71( EXPORTING AREA_NAME    = AREA_NAME
                                      SNEAK_MODE   = ABAP_TRUE
                                      LIFE_CONTEXT = _LIFE_CONTEXT
                            IMPORTING ROOT         = L_ROOT ).

    IF L_ROOT IS INITIAL.
*     no root object returned, sneak mode was not successful.
*     -> read area properties from database and try again.
      CL_SHM_SERVICE=>INITIALIZE(
        EXPORTING AREA_NAME       = HANDLE->AREA_NAME
                  CLIENT          = L_CLIENT
        IMPORTING ATTRIBUTES      = L_ATTRIBUTES
      ).

      HANDLE->PROPERTIES = L_ATTRIBUTES-PROPERTIES.
      HANDLE->_ATTACH_READ71( EXPORTING AREA_NAME    = AREA_NAME
                                        SNEAK_MODE   = ABAP_FALSE
                                        LIFE_CONTEXT = _LIFE_CONTEXT
                              IMPORTING ROOT         = L_ROOT ).

    ENDIF.

    HANDLE->ROOT ?= L_ROOT.
*   <

  ELSE.

    TRY.

*       >

        CREATE OBJECT HANDLE.

        HANDLE->CLIENT    = L_CLIENT.
        HANDLE->INST_NAME = INST_NAME.

        HANDLE->_ATTACH_READ71( EXPORTING AREA_NAME    = AREA_NAME
                                          SNEAK_MODE   = ABAP_TRUE
                                          LIFE_CONTEXT = _LIFE_CONTEXT
                                IMPORTING ROOT         = L_ROOT ).

        IF L_ROOT IS INITIAL.
*         no root object returned, sneak mode was not successful.
*         -> read area properties from database and try again.
          CL_SHM_SERVICE=>INITIALIZE(
            EXPORTING AREA_NAME       = HANDLE->AREA_NAME
                      CLIENT          = L_CLIENT
            IMPORTING ATTRIBUTES      = L_ATTRIBUTES
          ).

          HANDLE->PROPERTIES = L_ATTRIBUTES-PROPERTIES.
          HANDLE->_ATTACH_READ71( EXPORTING AREA_NAME    = AREA_NAME
                                            SNEAK_MODE   = ABAP_FALSE
                                            LIFE_CONTEXT = _LIFE_CONTEXT
                                  IMPORTING ROOT         = L_ROOT ).

        ENDIF.
        HANDLE->ROOT ?= L_ROOT.

*       <
        _TRACE_SERVICE->TRIN_ATTACH_FOR_READ(
          AREA_NAME = AREA_NAME
          INST_NAME = INST_NAME
          CLIENT    = L_CLIENT ).

      CLEANUP INTO L_CX.
        _TRACE_SERVICE->TRCX_ATTACH_FOR_READ(
          AREA_NAME = AREA_NAME
          INST_NAME = INST_NAME
          CLIENT    = L_CLIENT
          CX        = L_CX
        ).
    ENDTRY.

  ENDIF.

  HANDLE->INST_TRACE_SERVICE = _TRACE_SERVICE.
  HANDLE->INST_TRACE_ACTIVE  = _TRACE_ACTIVE.

  ENDMETHOD.

* ---- YCL_FI_RFBIBL00_SHM_AREA======CM005 ----
  METHOD ATTACH_FOR_WRITE.

  DATA:
    L_ATTRIBUTES             TYPE SHMA_ATTRIBUTES,
    L_CX                     TYPE REF TO CX_ROOT,
    L_CLIENT                 TYPE SHM_CLIENT,
    L_CLIENT_SUPPLIED        TYPE ABAP_BOOL, "#EC NEEDED
    L_WAIT_TIME              TYPE I,
    L_WAIT_TIME_PER_LOOP     TYPE I,
    L_WAIT_TIME_PER_LOOP_SEC TYPE F.

  L_WAIT_TIME = WAIT_TIME.

* check if tracing should be activated/de-activated
  IF  ( NOT _TRACE_SERVICE IS INITIAL ).
    TRY.
        _TRACE_ACTIVE =
          CL_SHM_SERVICE=>TRACE_IS_VARIANT_ACTIVE(
            _TRACE_SERVICE->VARIANT-DEF_NAME
          ).
      CATCH CX_ROOT. "#EC NO_HANDLER
                     "#EC CATCH_ALL
    ENDTRY.
  ENDIF.


  IF _TRACE_ACTIVE = ABAP_FALSE OR
  _TRACE_SERVICE->VARIANT-ATTACH_FOR_WRITE = ABAP_FALSE.

*   >

    CREATE OBJECT HANDLE.

    HANDLE->CLIENT    = L_CLIENT.
    HANDLE->INST_NAME = INST_NAME.

    CL_SHM_SERVICE=>INITIALIZE(
      EXPORTING AREA_NAME    = HANDLE->AREA_NAME
                CLIENT       = L_CLIENT
      IMPORTING ATTRIBUTES   = L_ATTRIBUTES
    ).

    HANDLE->PROPERTIES = L_ATTRIBUTES-PROPERTIES.

    HANDLE->_ATTACH_WRITE70(
      EXPORTING
        AREA_NAME = HANDLE->AREA_NAME
        MODE      = ATTACH_MODE
      CHANGING
        WAIT_TIME = L_WAIT_TIME ).

    IF ATTACH_MODE = CL_SHM_AREA=>ATTACH_MODE_WAIT AND
       HANDLE->_LOCK IS INITIAL.

      L_WAIT_TIME_PER_LOOP = L_WAIT_TIME / 10.
* wait_time_per_loop should be at least 2 * SHMATTACHWRITE_MAXACTIVEWAIT
      IF L_WAIT_TIME_PER_LOOP < 2000.
        L_WAIT_TIME_PER_LOOP = 2000.
      ELSEIF L_WAIT_TIME_PER_LOOP > 300000.
        L_WAIT_TIME_PER_LOOP = 300000.
      ENDIF.

      L_WAIT_TIME_PER_LOOP_SEC = L_WAIT_TIME_PER_LOOP / 1000.

      WHILE HANDLE->_LOCK IS INITIAL.

        IF L_WAIT_TIME_PER_LOOP > L_WAIT_TIME.
          L_WAIT_TIME_PER_LOOP = L_WAIT_TIME.
          L_WAIT_TIME_PER_LOOP_SEC = L_WAIT_TIME_PER_LOOP / 1000.
        ENDIF.

        WAIT UP TO L_WAIT_TIME_PER_LOOP_SEC SECONDS.
        L_WAIT_TIME = L_WAIT_TIME - L_WAIT_TIME_PER_LOOP.

        HANDLE->_ATTACH_WRITE70(
          EXPORTING
            AREA_NAME = HANDLE->AREA_NAME
            MODE      = CL_SHM_AREA=>ATTACH_MODE_WAIT_2ND_TRY
          CHANGING
            WAIT_TIME = L_WAIT_TIME ).

      ENDWHILE.

    ENDIF.

*   <

  ELSE.

    TRY.

*     >

        CREATE OBJECT HANDLE.

        HANDLE->CLIENT    = L_CLIENT.
        HANDLE->INST_NAME = INST_NAME.

        CL_SHM_SERVICE=>INITIALIZE(
          EXPORTING AREA_NAME    = HANDLE->AREA_NAME
                    CLIENT       = L_CLIENT
          IMPORTING ATTRIBUTES   = L_ATTRIBUTES
        ).

        HANDLE->PROPERTIES = L_ATTRIBUTES-PROPERTIES.

        HANDLE->_ATTACH_WRITE70(
          EXPORTING
            AREA_NAME = HANDLE->AREA_NAME
            MODE      = ATTACH_MODE
          CHANGING
            WAIT_TIME = L_WAIT_TIME ).

        IF ATTACH_MODE = CL_SHM_AREA=>ATTACH_MODE_WAIT AND
           HANDLE->_LOCK IS INITIAL.

          L_WAIT_TIME_PER_LOOP = L_WAIT_TIME / 10.
* wait_time_per_loop should be at least 2 * SHMATTACHWRITE_MAXACTIVEWAIT
          IF L_WAIT_TIME_PER_LOOP < 2000.
            L_WAIT_TIME_PER_LOOP = 2000.
          ELSEIF L_WAIT_TIME_PER_LOOP > 300000.
            L_WAIT_TIME_PER_LOOP = 300000.
          ENDIF.

          L_WAIT_TIME_PER_LOOP_SEC = L_WAIT_TIME_PER_LOOP / 1000.

          WHILE HANDLE->_LOCK IS INITIAL.

            IF L_WAIT_TIME_PER_LOOP > L_WAIT_TIME.
              L_WAIT_TIME_PER_LOOP = L_WAIT_TIME.
              L_WAIT_TIME_PER_LOOP_SEC = L_WAIT_TIME_PER_LOOP / 1000.
            ENDIF.

            WAIT UP TO L_WAIT_TIME_PER_LOOP_SEC SECONDS.
            L_WAIT_TIME = L_WAIT_TIME - L_WAIT_TIME_PER_LOOP.

            HANDLE->_ATTACH_WRITE70(
              EXPORTING
                AREA_NAME = HANDLE->AREA_NAME
                MODE      = CL_SHM_AREA=>ATTACH_MODE_WAIT_2ND_TRY
              CHANGING
                WAIT_TIME = L_WAIT_TIME ).

          ENDWHILE.

        ENDIF.

*     <

        _TRACE_SERVICE->TRIN_ATTACH_FOR_WRITE(
          AREA_NAME = AREA_NAME
          INST_NAME = INST_NAME
          CLIENT    = L_CLIENT
          MODE      = ATTACH_MODE
          WAIT_TIME = WAIT_TIME
        ).
      CLEANUP INTO L_CX.
        _TRACE_SERVICE->TRCX_ATTACH_FOR_WRITE(
          AREA_NAME = AREA_NAME
          INST_NAME = INST_NAME
          CLIENT    = L_CLIENT
          MODE      = ATTACH_MODE
          WAIT_TIME = WAIT_TIME
          CX        = L_CX
        ).
    ENDTRY.

  ENDIF.

  HANDLE->INST_TRACE_SERVICE = _TRACE_SERVICE.
  HANDLE->INST_TRACE_ACTIVE  = _TRACE_ACTIVE.

  ENDMETHOD.

* ---- YCL_FI_RFBIBL00_SHM_AREA======CM006 ----
  METHOD ATTACH_FOR_UPDATE.

  DATA:
    L_ATTRIBUTES             TYPE SHMA_ATTRIBUTES,
    L_ROOT                   TYPE REF TO OBJECT,
    L_CX                     TYPE REF TO CX_ROOT,
    L_CLIENT                 TYPE SHM_CLIENT,
    L_CLIENT_SUPPLIED        TYPE ABAP_BOOL, "#EC NEEDED
    L_WAIT_TIME              TYPE I,
    L_WAIT_TIME_PER_LOOP     TYPE I,
    L_WAIT_TIME_PER_LOOP_SEC TYPE F.

  L_WAIT_TIME = WAIT_TIME.

* check if tracing should be activated/de-activated
  IF  ( NOT _TRACE_SERVICE IS INITIAL ).
    TRY.
        _TRACE_ACTIVE =
          CL_SHM_SERVICE=>TRACE_IS_VARIANT_ACTIVE(
            _TRACE_SERVICE->VARIANT-DEF_NAME
          ).
      CATCH CX_ROOT. "#EC NO_HANDLER
                     "#EC CATCH_ALL
    ENDTRY.
  ENDIF.


  IF _TRACE_ACTIVE = ABAP_FALSE OR
  _TRACE_SERVICE->VARIANT-ATTACH_FOR_UPD = ABAP_FALSE.

*   >

    CREATE OBJECT HANDLE.

    HANDLE->CLIENT    = L_CLIENT.
    HANDLE->INST_NAME = INST_NAME.

    CL_SHM_SERVICE=>INITIALIZE(
      EXPORTING AREA_NAME    = HANDLE->AREA_NAME
                CLIENT       = L_CLIENT
      IMPORTING ATTRIBUTES   = L_ATTRIBUTES
    ).

    HANDLE->PROPERTIES = L_ATTRIBUTES-PROPERTIES.

    HANDLE->_ATTACH_UPDATE70(
      EXPORTING AREA_NAME = HANDLE->AREA_NAME
                MODE      = ATTACH_MODE
      IMPORTING ROOT      = L_ROOT
      CHANGING  WAIT_TIME = L_WAIT_TIME ).

    IF ABAP_TRUE = L_ATTRIBUTES-PROPERTIES-HAS_VERSIONS AND
       HANDLE->_LOCK IS NOT INITIAL.
* we may need a second try in case of class constructors
      HANDLE->_ATTACH_UPDATE70(
        EXPORTING AREA_NAME = HANDLE->AREA_NAME
                  MODE      = ATTACH_MODE
        IMPORTING ROOT      = L_ROOT
        CHANGING  WAIT_TIME = L_WAIT_TIME ).
    ENDIF.

    IF ATTACH_MODE = CL_SHM_AREA=>ATTACH_MODE_WAIT AND
       HANDLE->_LOCK IS INITIAL.

      L_WAIT_TIME_PER_LOOP = L_WAIT_TIME / 10.
* wait_time_per_loop should be at least 2 * SHMATTACHWRITE_MAXACTIVEWAIT
      IF L_WAIT_TIME_PER_LOOP < 2000.
        L_WAIT_TIME_PER_LOOP = 2000.
      ELSEIF L_WAIT_TIME_PER_LOOP > 300000.
        L_WAIT_TIME_PER_LOOP = 300000.
      ENDIF.

      L_WAIT_TIME_PER_LOOP_SEC = L_WAIT_TIME_PER_LOOP / 1000.

      WHILE HANDLE->_LOCK IS INITIAL.

        IF L_WAIT_TIME_PER_LOOP > L_WAIT_TIME.
          L_WAIT_TIME_PER_LOOP = L_WAIT_TIME.
          L_WAIT_TIME_PER_LOOP_SEC = L_WAIT_TIME_PER_LOOP / 1000.
        ENDIF.

        WAIT UP TO L_WAIT_TIME_PER_LOOP_SEC SECONDS.
        L_WAIT_TIME = L_WAIT_TIME - L_WAIT_TIME_PER_LOOP.

        HANDLE->_ATTACH_UPDATE70(
          EXPORTING AREA_NAME = HANDLE->AREA_NAME
                    MODE      = CL_SHM_AREA=>ATTACH_MODE_WAIT_2ND_TRY
          IMPORTING ROOT      = L_ROOT
          CHANGING  WAIT_TIME = L_WAIT_TIME ).

        IF ABAP_TRUE = L_ATTRIBUTES-PROPERTIES-HAS_VERSIONS AND
           HANDLE->_LOCK IS NOT INITIAL.
* we may need a second try in case of class constructors
          HANDLE->_ATTACH_UPDATE70(
            EXPORTING AREA_NAME = HANDLE->AREA_NAME
                      MODE      = CL_SHM_AREA=>ATTACH_MODE_WAIT_2ND_TRY
            IMPORTING ROOT      = L_ROOT
            CHANGING  WAIT_TIME = L_WAIT_TIME ).
        ENDIF.

      ENDWHILE.

    ENDIF.

    HANDLE->ROOT ?= L_ROOT.

*   <

  ELSE.

    TRY.

*       >

        CREATE OBJECT HANDLE.

        HANDLE->CLIENT    = L_CLIENT.
        HANDLE->INST_NAME = INST_NAME.

        CL_SHM_SERVICE=>INITIALIZE(
          EXPORTING AREA_NAME    = HANDLE->AREA_NAME
                    CLIENT       = L_CLIENT
          IMPORTING ATTRIBUTES   = L_ATTRIBUTES
        ).

        HANDLE->PROPERTIES = L_ATTRIBUTES-PROPERTIES.

        HANDLE->_ATTACH_UPDATE70(
          EXPORTING AREA_NAME = HANDLE->AREA_NAME
                    MODE      = ATTACH_MODE
          IMPORTING ROOT      = L_ROOT
          CHANGING  WAIT_TIME = L_WAIT_TIME ).

        IF ABAP_TRUE = L_ATTRIBUTES-PROPERTIES-HAS_VERSIONS AND
           HANDLE->_LOCK IS NOT INITIAL.
* we may need a second try in case of class constructors
          HANDLE->_ATTACH_UPDATE70(
            EXPORTING AREA_NAME = HANDLE->AREA_NAME
                      MODE      = ATTACH_MODE
            IMPORTING ROOT      = L_ROOT
            CHANGING  WAIT_TIME = L_WAIT_TIME ).
        ENDIF.

        IF ATTACH_MODE = CL_SHM_AREA=>ATTACH_MODE_WAIT AND
           HANDLE->_LOCK IS INITIAL.

          L_WAIT_TIME_PER_LOOP = L_WAIT_TIME / 10.
* wait_time_per_loop should be at least 2 * SHMATTACHWRITE_MAXACTIVEWAIT
          IF L_WAIT_TIME_PER_LOOP < 2000.
            L_WAIT_TIME_PER_LOOP = 2000.
          ELSEIF L_WAIT_TIME_PER_LOOP > 300000.
            L_WAIT_TIME_PER_LOOP = 300000.
          ENDIF.

          L_WAIT_TIME_PER_LOOP_SEC = L_WAIT_TIME_PER_LOOP / 1000.

          WHILE HANDLE->_LOCK IS INITIAL.

            IF L_WAIT_TIME_PER_LOOP > L_WAIT_TIME.
              L_WAIT_TIME_PER_LOOP = L_WAIT_TIME.
              L_WAIT_TIME_PER_LOOP_SEC = L_WAIT_TIME_PER_LOOP / 1000.
            ENDIF.

            WAIT UP TO L_WAIT_TIME_PER_LOOP_SEC SECONDS.
            L_WAIT_TIME = L_WAIT_TIME - L_WAIT_TIME_PER_LOOP.

            HANDLE->_ATTACH_UPDATE70(
              EXPORTING
                AREA_NAME = HANDLE->AREA_NAME
                MODE      = CL_SHM_AREA=>ATTACH_MODE_WAIT_2ND_TRY
              IMPORTING
                ROOT      = L_ROOT
              CHANGING
                WAIT_TIME = L_WAIT_TIME ).

            IF ABAP_TRUE = L_ATTRIBUTES-PROPERTIES-HAS_VERSIONS AND
               HANDLE->_LOCK IS NOT INITIAL.
* we may need a second try in case of class constructors
              HANDLE->_ATTACH_UPDATE70(
                EXPORTING
                  AREA_NAME = HANDLE->AREA_NAME
                  MODE      = CL_SHM_AREA=>ATTACH_MODE_WAIT_2ND_TRY
                IMPORTING
                  ROOT      = L_ROOT
                CHANGING
                  WAIT_TIME = L_WAIT_TIME ).
            ENDIF.

          ENDWHILE.

        ENDIF.

        HANDLE->ROOT ?= L_ROOT.

*       <
        _TRACE_SERVICE->TRIN_ATTACH_FOR_UPDATE(
          AREA_NAME = AREA_NAME
          INST_NAME = INST_NAME
          CLIENT    = L_CLIENT
          MODE      = ATTACH_MODE
          WAIT_TIME = WAIT_TIME
        ).

      CLEANUP INTO L_CX.
        _TRACE_SERVICE->TRCX_ATTACH_FOR_UPDATE(
          AREA_NAME = AREA_NAME
          INST_NAME = INST_NAME
          CLIENT    = L_CLIENT
          MODE      = ATTACH_MODE
          WAIT_TIME = WAIT_TIME
          CX        = L_CX
        ).
    ENDTRY.

  ENDIF.

  HANDLE->INST_TRACE_SERVICE = _TRACE_SERVICE.
  HANDLE->INST_TRACE_ACTIVE  = _TRACE_ACTIVE.

  ENDMETHOD.

* ---- YCL_FI_RFBIBL00_SHM_AREA======CM007 ----
  METHOD DETACH_AREA.

  DATA:
    L_CLIENT TYPE SHM_CLIENT,
    L_CLIENT_SUPPLIED TYPE ABAP_BOOL VALUE ABAP_FALSE.


* >
  RC = _DETACH_AREA71( AREA_NAME        = AREA_NAME
                       CLIENT           = L_CLIENT
                       CLIENT_SUPPLIED  = L_CLIENT_SUPPLIED
                       CLIENT_DEPENDENT = _CLIENT_DEPENDENT
                       LIFE_CONTEXT     = _LIFE_CONTEXT
       ).
* <

  IF _TRACE_ACTIVE = ABAP_TRUE.
    IF _TRACE_SERVICE->VARIANT-DETACH_AREA = ABAP_TRUE.
      _TRACE_SERVICE->TRIN_DETACH_AREA(
        AREA_NAME = AREA_NAME
        CLIENT    = L_CLIENT
        RC        = RC
      ).
    ENDIF.
  ENDIF.

  ENDMETHOD.

* ---- YCL_FI_RFBIBL00_SHM_AREA======CM008 ----
  METHOD INVALIDATE_INSTANCE.

  DATA:
    L_CLIENT TYPE SHM_CLIENT,
    L_CLIENT_SUPPLIED TYPE ABAP_BOOL VALUE ABAP_FALSE.

  CONSTANTS: AFFECT_SERVER TYPE SHM_AFFECT_SERVER
             VALUE CL_SHM_AREA=>AFFECT_LOCAL_SERVER.


* >
  RC = _INVALIDATE_INSTANCE71(
    AREA_NAME         = AREA_NAME
    INST_NAME         = INST_NAME
    CLIENT            = L_CLIENT
    CLIENT_SUPPLIED   = L_CLIENT_SUPPLIED
    CLIENT_DEPENDENT  = _CLIENT_DEPENDENT
    TRANSACTIONAL     = _TRANSACTIONAL
    TERMINATE_CHANGER = TERMINATE_CHANGER
    AFFECT_SERVER     = AFFECT_SERVER
    LIFE_CONTEXT      = _LIFE_CONTEXT
  ).
* <

  IF _TRACE_ACTIVE = ABAP_TRUE.
    IF _TRACE_SERVICE->VARIANT-INVALIDATE_INST = ABAP_TRUE.
      _TRACE_SERVICE->TRIN_INVALIDATE_INSTANCE(
        AREA_NAME         = AREA_NAME
        INST_NAME         = INST_NAME
        CLIENT            = L_CLIENT
        TERMINATE_CHANGER = TERMINATE_CHANGER
        AFFECT_SERVER     = AFFECT_SERVER
        RC                = RC
      ).
    ENDIF.
  ENDIF.

  ENDMETHOD.

* ---- YCL_FI_RFBIBL00_SHM_AREA======CM009 ----
  METHOD INVALIDATE_AREA.

  DATA:
    L_CLIENT TYPE SHM_CLIENT,
    L_CLIENT_SUPPLIED TYPE ABAP_BOOL VALUE ABAP_FALSE.

  CONSTANTS: AFFECT_SERVER TYPE SHM_AFFECT_SERVER
             VALUE CL_SHM_AREA=>AFFECT_LOCAL_SERVER.


* >
  RC = _INVALIDATE_AREA71( AREA_NAME         = AREA_NAME
                           CLIENT            = L_CLIENT
                           CLIENT_SUPPLIED   = L_CLIENT_SUPPLIED
                           CLIENT_DEPENDENT  = _CLIENT_DEPENDENT
                           TRANSACTIONAL     = _TRANSACTIONAL
                           TERMINATE_CHANGER = TERMINATE_CHANGER
                           AFFECT_SERVER     = AFFECT_SERVER
                           LIFE_CONTEXT      = _LIFE_CONTEXT ).
* <

  IF _TRACE_ACTIVE = ABAP_TRUE.
    IF _TRACE_SERVICE->VARIANT-INVALIDATE_AREA = ABAP_TRUE.
      _TRACE_SERVICE->TRIN_INVALIDATE_AREA(
        AREA_NAME         = AREA_NAME
        CLIENT            = L_CLIENT
        TERMINATE_CHANGER = TERMINATE_CHANGER
        AFFECT_SERVER     = AFFECT_SERVER
        RC                = RC
      ).
    ENDIF.
  ENDIF.

  ENDMETHOD.

* ---- YCL_FI_RFBIBL00_SHM_AREA======CM00A ----
  METHOD FREE_INSTANCE.

  DATA:
    L_CLIENT TYPE SHM_CLIENT,
    L_CLIENT_SUPPLIED TYPE ABAP_BOOL VALUE ABAP_FALSE.

  CONSTANTS: AFFECT_SERVER TYPE SHM_AFFECT_SERVER
             VALUE CL_SHM_AREA=>AFFECT_LOCAL_SERVER.


* >
  RC = _FREE_INSTANCE71( AREA_NAME         = AREA_NAME
                         INST_NAME         = INST_NAME
                         CLIENT            = L_CLIENT
                         CLIENT_SUPPLIED   = L_CLIENT_SUPPLIED
                         CLIENT_DEPENDENT  = _CLIENT_DEPENDENT
                         TRANSACTIONAL     = _TRANSACTIONAL
                         TERMINATE_CHANGER = TERMINATE_CHANGER
                         AFFECT_SERVER     = AFFECT_SERVER
                         LIFE_CONTEXT      = _LIFE_CONTEXT ).
* <

  IF _TRACE_ACTIVE = ABAP_TRUE.
    IF _TRACE_SERVICE->VARIANT-FREE_INSTANCE = ABAP_TRUE.
      _TRACE_SERVICE->TRIN_FREE_INSTANCE(
        AREA_NAME         = AREA_NAME
        INST_NAME         = INST_NAME
        CLIENT            = L_CLIENT
        TERMINATE_CHANGER = TERMINATE_CHANGER
        AFFECT_SERVER     = AFFECT_SERVER
        RC                = RC
      ).
    ENDIF.
  ENDIF.

  ENDMETHOD.

* ---- YCL_FI_RFBIBL00_SHM_AREA======CM00B ----
  METHOD FREE_AREA.

  DATA:
    L_CLIENT TYPE SHM_CLIENT,
    L_CLIENT_SUPPLIED TYPE ABAP_BOOL VALUE ABAP_FALSE.

  CONSTANTS: AFFECT_SERVER TYPE SHM_AFFECT_SERVER
             VALUE CL_SHM_AREA=>AFFECT_LOCAL_SERVER.


* >
  RC = _FREE_AREA71( AREA_NAME         = AREA_NAME
                     CLIENT            = L_CLIENT
                     CLIENT_SUPPLIED   = L_CLIENT_SUPPLIED
                     CLIENT_DEPENDENT  = _CLIENT_DEPENDENT
                     TRANSACTIONAL     = _TRANSACTIONAL
                     TERMINATE_CHANGER = TERMINATE_CHANGER
                     AFFECT_SERVER     = AFFECT_SERVER
                     LIFE_CONTEXT      = _LIFE_CONTEXT ).
* <

  IF _TRACE_ACTIVE = ABAP_TRUE.
    IF _TRACE_SERVICE->VARIANT-FREE_AREA = ABAP_TRUE.
      _TRACE_SERVICE->TRIN_FREE_AREA(
      AREA_NAME         = AREA_NAME
      CLIENT            = L_CLIENT
      TERMINATE_CHANGER = TERMINATE_CHANGER
      AFFECT_SERVER     = AFFECT_SERVER
      RC                = RC
    ).
    ENDIF.
  ENDIF.

  ENDMETHOD.

* ---- YCL_FI_RFBIBL00_SHM_AREA======CM00C ----
  METHOD GET_INSTANCE_INFOS.

  DATA:
    L_CLIENT             TYPE SHM_CLIENT,
    L_CLIENT_SUPPLIED    TYPE ABAP_BOOL VALUE ABAP_FALSE,
    L_INST_NAME_SUPPLIED TYPE ABAP_BOOL VALUE ABAP_FALSE.


  IF INST_NAME IS SUPPLIED.
    L_INST_NAME_SUPPLIED = ABAP_TRUE.
  ENDIF.

* >
  TRY.
      CALL METHOD ('_GET_INSTANCE_INFOS804')
        EXPORTING
          AREA_NAME          = AREA_NAME
          CLIENT             = L_CLIENT
          CLIENT_SUPPLIED    = L_CLIENT_SUPPLIED
          CLIENT_DEPENDENT   = _CLIENT_DEPENDENT
          LIFE_CONTEXT       = _LIFE_CONTEXT
          INST_NAME          = INST_NAME
          INST_NAME_SUPPLIED = L_INST_NAME_SUPPLIED
        RECEIVING
          INFOS              = INFOS.
    CATCH CX_SY_DYN_CALL_ILLEGAL_METHOD.
*     New kernel and/or new basis SP missing -> use slow fallback
      INFOS = _GET_INSTANCE_INFOS71(
                AREA_NAME        = AREA_NAME
                CLIENT           = L_CLIENT
                CLIENT_SUPPLIED  = L_CLIENT_SUPPLIED
                CLIENT_DEPENDENT = _CLIENT_DEPENDENT
                LIFE_CONTEXT     = _LIFE_CONTEXT
              ).
      IF ABAP_TRUE = L_INST_NAME_SUPPLIED.
        DELETE INFOS WHERE NAME <> INST_NAME.
      ENDIF.
  ENDTRY.
* <

  IF _TRACE_ACTIVE = ABAP_TRUE.
    IF _TRACE_SERVICE->VARIANT-GET_INSTANCE_INF = ABAP_TRUE.
      _TRACE_SERVICE->TRIN_GET_INSTANCE_INFOS(
        AREA_NAME         = AREA_NAME
        INST_NAME         = INST_NAME
        CLIENT            = L_CLIENT
        INFOS             = INFOS
      ).
    ENDIF.
  ENDIF.

  ENDMETHOD.

* ---- YCL_FI_RFBIBL00_SHM_AREA======CM00D ----
  METHOD BUILD.

  DATA:
    L_CLS_NAME TYPE SHM_AUTO_BUILD_CLASS_NAME,
    L_CX TYPE REF TO CX_ROOT.

  IF _TRACE_ACTIVE = ABAP_FALSE OR
  _TRACE_SERVICE->VARIANT-BUILD = ABAP_FALSE.

*   >
    L_CLS_NAME =
      CL_SHM_SERVICE=>GET_AUTO_BUILD_CLASS_NAME( AREA_NAME ).

    CALL METHOD (L_CLS_NAME)=>IF_SHM_BUILD_INSTANCE~BUILD
      EXPORTING
        INST_NAME = INST_NAME.
*   <

  ELSE.

    TRY.

*       >
        L_CLS_NAME =
          CL_SHM_SERVICE=>GET_AUTO_BUILD_CLASS_NAME( AREA_NAME ).

        CALL METHOD (L_CLS_NAME)=>IF_SHM_BUILD_INSTANCE~BUILD
          EXPORTING
            INST_NAME = INST_NAME.
*       <
        _TRACE_SERVICE->TRIN_BUILD(
          AREA_NAME         = AREA_NAME
          INST_NAME         = INST_NAME
        ).

      CLEANUP INTO L_CX.
        _TRACE_SERVICE->TRCX_BUILD(
          AREA_NAME         = AREA_NAME
          INST_NAME         = INST_NAME
          CX                = L_CX
        ).
    ENDTRY.

  ENDIF.

  ENDMETHOD.

* ---- YCL_FI_RFBIBL00_SHM_AREA======CM00E ----
  METHOD GET_ROOT.

  DATA:
    L_CX        TYPE REF TO CX_ROOT,
    L_AREA_NAME TYPE STRING,
    L_INST_NAME TYPE STRING,
    L_CLIENT    TYPE STRING.

  IF _TRACE_ACTIVE = ABAP_FALSE OR
  _TRACE_SERVICE->VARIANT-GET_ROOT = ABAP_FALSE.

*   >
    IF IS_VALID( ) = ABAP_FALSE.
      L_AREA_NAME = ME->AREA_NAME.
      L_INST_NAME = ME->INST_NAME.
      L_CLIENT    = ME->CLIENT.
      RAISE EXCEPTION TYPE CX_SHM_ALREADY_DETACHED
        EXPORTING
          AREA_NAME = L_AREA_NAME
          INST_NAME = L_INST_NAME
          CLIENT    = L_CLIENT.
    ENDIF.
    ROOT = ME->ROOT.
*   <

  ELSE.

    TRY.

*       >
        IF IS_VALID( ) = ABAP_FALSE.
          L_AREA_NAME = ME->AREA_NAME.
          L_INST_NAME = ME->INST_NAME.
          L_CLIENT    = ME->CLIENT.
          RAISE EXCEPTION TYPE CX_SHM_ALREADY_DETACHED
            EXPORTING
              AREA_NAME = L_AREA_NAME
              INST_NAME = L_INST_NAME
              CLIENT    = L_CLIENT.
        ENDIF.
        ROOT = ME->ROOT.
*       <

        _TRACE_SERVICE->TRIN_GET_ROOT(
          AREA_NAME = AREA_NAME
        ).

      CLEANUP INTO L_CX.
        _TRACE_SERVICE->TRCX_GET_ROOT(
          AREA_NAME = AREA_NAME
          CX        = L_CX
        ).
    ENDTRY.

  ENDIF.

  ENDMETHOD.

* ---- YCL_FI_RFBIBL00_SHM_AREA======CO ----
PROTECTED SECTION.

* ---- YCL_FI_RFBIBL00_SHM_AREA======CU ----
CLASS YCL_FI_RFBIBL00_SHM_AREA DEFINITION
  PUBLIC
  INHERITING FROM CL_SHM_AREA
  FINAL
  CREATE PRIVATE

  GLOBAL FRIENDS CL_SHM_AREA .

PUBLIC SECTION.

  CONSTANTS AREA_NAME TYPE SHM_AREA_NAME VALUE 'YCL_FI_RFBIBL00_SHM_AREA' ##NO_TEXT.
  DATA ROOT TYPE REF TO YCL_FI_RFBIBL00_SHM_ROOT READ-ONLY .

  CLASS-METHODS CLASS_CONSTRUCTOR .
  CLASS-METHODS GET_GENERATOR_VERSION
    RETURNING
      VALUE(GENERATOR_VERSION) TYPE I .
  CLASS-METHODS ATTACH_FOR_READ
    IMPORTING
      !INST_NAME TYPE SHM_INST_NAME DEFAULT CL_SHM_AREA=>DEFAULT_INSTANCE
    PREFERRED PARAMETER INST_NAME
    RETURNING
      VALUE(HANDLE) TYPE REF TO YCL_FI_RFBIBL00_SHM_AREA
    RAISING
      CX_SHM_INCONSISTENT
      CX_SHM_NO_ACTIVE_VERSION
      CX_SHM_READ_LOCK_ACTIVE
      CX_SHM_EXCLUSIVE_LOCK_ACTIVE
      CX_SHM_PARAMETER_ERROR
      CX_SHM_CHANGE_LOCK_ACTIVE .
  CLASS-METHODS ATTACH_FOR_WRITE
    IMPORTING
      !INST_NAME TYPE SHM_INST_NAME DEFAULT CL_SHM_AREA=>DEFAULT_INSTANCE
      !ATTACH_MODE TYPE SHM_ATTACH_MODE DEFAULT CL_SHM_AREA=>ATTACH_MODE_DEFAULT
      !WAIT_TIME TYPE I DEFAULT 0
    PREFERRED PARAMETER INST_NAME
    RETURNING
      VALUE(HANDLE) TYPE REF TO YCL_FI_RFBIBL00_SHM_AREA
    RAISING
      CX_SHM_EXCLUSIVE_LOCK_ACTIVE
      CX_SHM_VERSION_LIMIT_EXCEEDED
      CX_SHM_CHANGE_LOCK_ACTIVE
      CX_SHM_PARAMETER_ERROR
      CX_SHM_PENDING_LOCK_REMOVED .
  CLASS-METHODS ATTACH_FOR_UPDATE
    IMPORTING
      !INST_NAME TYPE SHM_INST_NAME DEFAULT CL_SHM_AREA=>DEFAULT_INSTANCE
      !ATTACH_MODE TYPE SHM_ATTACH_MODE DEFAULT CL_SHM_AREA=>ATTACH_MODE_DEFAULT
      !WAIT_TIME TYPE I DEFAULT 0
    PREFERRED PARAMETER INST_NAME
    RETURNING
      VALUE(HANDLE) TYPE REF TO YCL_FI_RFBIBL00_SHM_AREA
    RAISING
      CX_SHM_INCONSISTENT
      CX_SHM_NO_ACTIVE_VERSION
      CX_SHM_EXCLUSIVE_LOCK_ACTIVE
      CX_SHM_VERSION_LIMIT_EXCEEDED
      CX_SHM_CHANGE_LOCK_ACTIVE
      CX_SHM_PARAMETER_ERROR
      CX_SHM_PENDING_LOCK_REMOVED .
  CLASS-METHODS DETACH_AREA
    RETURNING
      VALUE(RC) TYPE SHM_RC .
  CLASS-METHODS INVALIDATE_INSTANCE
    IMPORTING
      !INST_NAME TYPE SHM_INST_NAME DEFAULT CL_SHM_AREA=>DEFAULT_INSTANCE
      !TERMINATE_CHANGER TYPE ABAP_BOOL DEFAULT ABAP_TRUE
    PREFERRED PARAMETER INST_NAME
    RETURNING
      VALUE(RC) TYPE SHM_RC
    RAISING
      CX_SHM_PARAMETER_ERROR .
  CLASS-METHODS INVALIDATE_AREA
    IMPORTING
      !TERMINATE_CHANGER TYPE ABAP_BOOL DEFAULT ABAP_TRUE
    RETURNING
      VALUE(RC) TYPE SHM_RC
    RAISING
      CX_SHM_PARAMETER_ERROR .
  CLASS-METHODS FREE_INSTANCE
    IMPORTING
      !INST_NAME TYPE SHM_INST_NAME DEFAULT CL_SHM_AREA=>DEFAULT_INSTANCE
      !TERMINATE_CHANGER TYPE ABAP_BOOL DEFAULT ABAP_TRUE
    PREFERRED PARAMETER INST_NAME
    RETURNING
      VALUE(RC) TYPE SHM_RC
    RAISING
      CX_SHM_PARAMETER_ERROR .
  CLASS-METHODS FREE_AREA
    IMPORTING
      !TERMINATE_CHANGER TYPE ABAP_BOOL DEFAULT ABAP_TRUE
    RETURNING
      VALUE(RC) TYPE SHM_RC
    RAISING
      CX_SHM_PARAMETER_ERROR .
  CLASS-METHODS GET_INSTANCE_INFOS
    IMPORTING
      !INST_NAME TYPE SHM_INST_NAME OPTIONAL
    RETURNING
      VALUE(INFOS) TYPE SHM_INST_INFOS .
  CLASS-METHODS BUILD
    IMPORTING
      !INST_NAME TYPE SHM_INST_NAME DEFAULT CL_SHM_AREA=>DEFAULT_INSTANCE
    RAISING
      CX_SHMA_NOT_CONFIGURED
      CX_SHMA_INCONSISTENT
      CX_SHM_BUILD_FAILED .
  METHODS SET_ROOT
    IMPORTING
      !ROOT TYPE REF TO YCL_FI_RFBIBL00_SHM_ROOT
    RAISING
      CX_SHM_INITIAL_REFERENCE
      CX_SHM_WRONG_HANDLE .

  METHODS GET_ROOT
    REDEFINITION .