* ==== CLASS POOL YCL_FI_COUPA_ACCOUNTING_DIS ====
CLASS-POOL .
*"* class pool for class YCL_FI_COUPA_ACCOUNTING_DIS

*"* local type definitions
INCLUDE YCL_FI_COUPA_ACCOUNTING_DIS===CCDEF.

*"* class YCL_FI_COUPA_ACCOUNTING_DIS definition
*"* public declarations
  INCLUDE YCL_FI_COUPA_ACCOUNTING_DIS===CU.
*"* protected declarations
  INCLUDE YCL_FI_COUPA_ACCOUNTING_DIS===CO.
*"* private declarations
  INCLUDE YCL_FI_COUPA_ACCOUNTING_DIS===CI.
ENDCLASS. "YCL_FI_COUPA_ACCOUNTING_DIS definition

*"* macro definitions
INCLUDE YCL_FI_COUPA_ACCOUNTING_DIS===CCMAC.
*"* local class implementation
INCLUDE YCL_FI_COUPA_ACCOUNTING_DIS===CCIMP.

CLASS YCL_FI_COUPA_ACCOUNTING_DIS IMPLEMENTATION.
*"* method's implementations
  INCLUDE METHODS.
ENDCLASS. "YCL_FI_COUPA_ACCOUNTING_DIS implementation


* ---- YCL_FI_COUPA_ACCOUNTING_DIS===CI ----
PRIVATE SECTION.

  DATA MV_REPID TYPE SY-REPID .
  DATA MO_DISPLAY_SETTINGS TYPE REF TO CL_SALV_DISPLAY_SETTINGS .
  DATA MO_SALV_TABLE TYPE REF TO CL_SALV_TABLE .
  DATA MO_LAYOUT TYPE REF TO CL_SALV_LAYOUT .
  DATA MT_STATUS TYPE YCL_CA_UTILITIES=>TTY_DOMAIN_VALUE .

  METHODS GET_BTCI_RESULT
    IMPORTING
      !IV_BDC_QID TYPE APQ_QUID
    CHANGING
      !CV_STATUS TYPE YE_BC_GENERIC_STATUS
      !CV_TRERR TYPE YE_BC_TR_ERROR_NUMBER
      !CV_TREXE TYPE YE_BC_TR_CORRECT_NUMBER .
  METHODS GET_FILE_PATH_FROM_STATUS
    IMPORTING
      !IV_FILE TYPE FILENAME_AL11
      !IV_STATUS TYPE YE_FI_COUPA_STATUS OPTIONAL
    RETURNING
      VALUE(RV_PATH_AND_FILE) TYPE STRING
    RAISING
      YCX_FILE_ACCESS .
  METHODS REFRESH_STATUS
    IMPORTING
      !IV_VIA_JOB TYPE XFELD DEFAULT ABAP_FALSE
    CHANGING
      !CS_LIST TYPE YIF_FI_COUPA_ACCOUNTING~TY_LIST .
  METHODS SET_STATUS_DATA
    IMPORTING
      !IV_STATUS TYPE YE_BC_GENERIC_STATUS
      !IV_TRTOT TYPE YE_BC_TR_NUMBER
      !IV_TRERR TYPE YE_BC_TR_ERROR_NUMBER
    EXPORTING
      !EV_STATUS_TEXT TYPE TEXT40
      !EV_STATUS_ICON TYPE P_99S_STATU .
  METHODS UPDATE_YTBC_APPL_FUP
    IMPORTING
      !IS_LIST TYPE YIF_FI_COUPA_ACCOUNTING~TY_LIST .
  METHODS HANDLE_USER_COMMAND
    FOR EVENT ADDED_FUNCTION OF CL_SALV_EVENTS_TABLE
    IMPORTING
      !E_SALV_FUNCTION .
  METHODS SET_COLUMNS .
  METHODS HANDLE_LINK_CLICK
    FOR EVENT LINK_CLICK OF CL_SALV_EVENTS_TABLE
    IMPORTING
      !ROW
      !COLUMN .
  METHODS GET_FILE_PATH
    IMPORTING
      !IV_LOGICAL_PATH TYPE PATHINTERN
      !IV_PHYSICAL_FILE TYPE FILENAME_AL11
    RETURNING
      VALUE(RV_PHYSICAL_PATH) TYPE STRING
    RAISING
      YCX_FILE_ACCESS .

* ---- YCL_FI_COUPA_ACCOUNTING_DIS===CM001 ----
  METHOD DISPLAY_ALV.

    DATA LO_EVENTS TYPE REF TO CL_SALV_EVENTS_TABLE.

    MV_REPID = IV_REPID.

    "Init ALV
    TRY.
        CALL METHOD CL_SALV_TABLE=>FACTORY
*      EXPORTING
*        list_display   = IF_SALV_C_BOOL_SAP=>FALSE
*        r_container    =
*        container_name =
          IMPORTING
            R_SALV_TABLE = MO_SALV_TABLE
          CHANGING
            T_TABLE      = YIF_FI_COUPA_ACCOUNTING~MT_LIST.
      CATCH CX_SALV_MSG .
    ENDTRY.

    MO_SALV_TABLE->SET_SCREEN_STATUS( PFSTATUS = 'MAIN'
                                      REPORT   = 'YFI_COUPA_PROTOCOL_DISPLAY'
                                      SET_FUNCTIONS = MO_SALV_TABLE->C_FUNCTIONS_ALL ).

    LO_EVENTS = MO_SALV_TABLE->GET_EVENT( ).
    SET HANDLER ME->HANDLE_USER_COMMAND FOR LO_EVENTS.

    "ALV columns
    ME->SET_COLUMNS( ).

    "ALV layout
    DATA LS_LAYOUT_KEY TYPE SALV_S_LAYOUT_KEY.

    MO_LAYOUT = MO_SALV_TABLE->GET_LAYOUT( ).
    LS_LAYOUT_KEY-REPORT = MV_REPID.
    MO_LAYOUT->SET_KEY( LS_LAYOUT_KEY ).
    MO_LAYOUT->SET_SAVE_RESTRICTION( IF_SALV_C_LAYOUT=>RESTRICT_NONE ).

    "ALV display settings
    MO_DISPLAY_SETTINGS = MO_SALV_TABLE->GET_DISPLAY_SETTINGS( ).
    MO_DISPLAY_SETTINGS->SET_STRIPED_PATTERN( ABAP_TRUE ).

    "Display list
    MO_SALV_TABLE->DISPLAY( ).

  ENDMETHOD.

* ---- YCL_FI_COUPA_ACCOUNTING_DIS===CM002 ----
  METHOD SET_COLUMNS.

    DATA LO_COLUMNS TYPE REF TO CL_SALV_COLUMNS_TABLE.
    DATA LO_COLUMN TYPE REF TO CL_SALV_COLUMN_TABLE.

    LO_COLUMNS = MO_SALV_TABLE->GET_COLUMNS( ).
    "Column width optimization
    LO_COLUMNS->SET_OPTIMIZE( ABAP_TRUE ).

    TRY.
        LO_COLUMN ?= LO_COLUMNS->GET_COLUMN( 'STATUS' ).
        LO_COLUMN->SET_TECHNICAL( ABAP_TRUE ).
      CATCH CX_SALV_NOT_FOUND.
    ENDTRY.

    TRY.
        LO_COLUMN ?= LO_COLUMNS->GET_COLUMN( 'STATUS_ICON' ).
        LO_COLUMN->SET_ALIGNMENT( IF_SALV_C_ALIGNMENT=>CENTERED ).
      CATCH CX_SALV_NOT_FOUND.
    ENDTRY.

    TRY.
        LO_COLUMN ?= LO_COLUMNS->GET_COLUMN( 'STATUS_TXT' ).
        LO_COLUMN->SET_LONG_TEXT( 'Status' ).
        LO_COLUMN->SET_MEDIUM_TEXT( 'Status' ).
        LO_COLUMN->SET_FIXED_HEADER_TEXT( 'L' ).
      CATCH CX_SALV_NOT_FOUND.
    ENDTRY.

    TRY.
        LO_COLUMN ?= LO_COLUMNS->GET_COLUMN( 'BDC_GROUP' ).
        LO_COLUMN->SET_LONG_TEXT( 'Batch-input for posting' ).
        LO_COLUMN->SET_MEDIUM_TEXT( 'BTCI for posting' ).
        LO_COLUMN->SET_FIXED_HEADER_TEXT( 'L' ).
      CATCH CX_SALV_NOT_FOUND.
    ENDTRY.

    TRY.
        LO_COLUMN ?= LO_COLUMNS->GET_COLUMN( 'BDC_QID' ).
        LO_COLUMN->SET_VISIBLE( ABAP_FALSE ).
      CATCH CX_SALV_NOT_FOUND.
    ENDTRY.

    TRY.
        LO_COLUMN ?= LO_COLUMNS->GET_COLUMN( 'TRTOT' ).
        LO_COLUMN->SET_FIXED_HEADER_TEXT( 'L' ).
      CATCH CX_SALV_NOT_FOUND.
    ENDTRY.

    TRY.
        LO_COLUMN ?= LO_COLUMNS->GET_COLUMN( 'TRERR' ).
        LO_COLUMN->SET_FIXED_HEADER_TEXT( 'L' ).
      CATCH CX_SALV_NOT_FOUND.
    ENDTRY.

    TRY.
        LO_COLUMN ?= LO_COLUMNS->GET_COLUMN( 'TREXE' ).
        LO_COLUMN->SET_FIXED_HEADER_TEXT( 'L' ).
      CATCH CX_SALV_NOT_FOUND.
    ENDTRY.

  ENDMETHOD.

* ---- YCL_FI_COUPA_ACCOUNTING_DIS===CM003 ----
  METHOD HANDLE_LINK_CLICK.

    CHECK ROW IS NOT INITIAL.
    READ TABLE YIF_FI_COUPA_ACCOUNTING~MT_LIST INTO DATA(LS_LIST) INDEX ROW.
    CHECK SY-SUBRC = 0.

  ENDMETHOD.

* ---- YCL_FI_COUPA_ACCOUNTING_DIS===CM004 ----
  METHOD HANDLE_USER_COMMAND.

    TYPES: BEGIN OF LTY_MESSAGE,
             MSG TYPE SALV_CSQT_LOG_TEXT,
           END OF LTY_MESSAGE.

    DATA LO_SELECTIONS TYPE REF TO CL_SALV_SELECTIONS.
    DATA LT_ROWS       TYPE SALV_T_ROW.
    DATA LV_ROW        TYPE SY-TABIX.
    DATA LT_MESSAGE TYPE TABLE OF LTY_MESSAGE.
    DATA LS_MESSAGE TYPE LTY_MESSAGE.
    DATA LO_POPUP TYPE REF TO YCL_CA_ALV_IN_POPUP.
    DATA LV_TITLE TYPE TEXT50.
    FIELD-SYMBOLS <LS_LIST> TYPE YIF_FI_COUPA_ACCOUNTING~TY_LIST.

    IF E_SALV_FUNCTION = 'YREFRESH'.
      LOOP AT YIF_FI_COUPA_ACCOUNTING~MT_LIST ASSIGNING <LS_LIST> WHERE BDC_GROUP IS NOT INITIAL
                                                                  AND STATUS > 0.
        ME->REFRESH_STATUS( EXPORTING IV_VIA_JOB = ABAP_TRUE
                            CHANGING CS_LIST = <LS_LIST> ).
        ME->SET_STATUS_DATA( EXPORTING IV_STATUS = <LS_LIST>-STATUS
                                       IV_TRTOT = <LS_LIST>-TRTOT
                                       IV_TRERR = <LS_LIST>-TRERR
                             IMPORTING EV_STATUS_TEXT = <LS_LIST>-STATUS_TXT
                                       EV_STATUS_ICON = <LS_LIST>-STATUS_ICON ).
      ENDLOOP.
      TRY.
          MO_SALV_TABLE->SET_DATA( CHANGING T_TABLE = YIF_FI_COUPA_ACCOUNTING~MT_LIST ).
        CATCH CX_SALV_NO_NEW_DATA_ALLOWED.
      ENDTRY.
      MO_SALV_TABLE->REFRESH( ).
      EXIT.
    ENDIF.

    LO_SELECTIONS = MO_SALV_TABLE->GET_SELECTIONS( ).
    LT_ROWS = LO_SELECTIONS->GET_SELECTED_ROWS( ).
    READ TABLE LT_ROWS INTO LV_ROW INDEX 1.
    IF SY-SUBRC <> 0.
      MESSAGE I024(YCOMMON).
      EXIT.
    ENDIF.
    READ TABLE YIF_FI_COUPA_ACCOUNTING~MT_LIST ASSIGNING <LS_LIST> INDEX LV_ROW.
    CHECK SY-SUBRC = 0.

    CASE E_SALV_FUNCTION.
      WHEN 'YPROT'.
        LOOP AT YIF_FI_COUPA_ACCOUNTING~MT_PROTOCOL INTO DATA(LS_PROTOCOL) WHERE APPL_KEY = <LS_LIST>-APPL_KEY.
          MESSAGE ID LS_PROTOCOL-MSGID TYPE LS_PROTOCOL-MSGTY NUMBER LS_PROTOCOL-MSGNO
                WITH LS_PROTOCOL-MSGV1 LS_PROTOCOL-MSGV2 LS_PROTOCOL-MSGV3 LS_PROTOCOL-MSGV4
                INTO LS_MESSAGE-MSG.
          APPEND LS_MESSAGE TO LT_MESSAGE.
        ENDLOOP.
        IF SY-SUBRC = 0.
          "Call ALV popup
          LO_POPUP = NEW YCL_CA_ALV_IN_POPUP( ).
          LV_TITLE = |Protocol for { <LS_LIST>-FILENAME }|.
          LO_POPUP->EXECUTE( EXPORTING IV_TITLE = LV_TITLE
                             CHANGING CT_TABLE = LT_MESSAGE ).
          FREE LO_POPUP.
        ELSE.
          MESSAGE I026(YCOMMON).
        ENDIF.
      WHEN 'YBTCI'.
        CHECK <LS_LIST>-BDC_GROUP IS NOT INITIAL.
        SET PARAMETER ID 'MPN' FIELD <LS_LIST>-BDC_GROUP.
        CALL TRANSACTION 'SM35' AND SKIP FIRST SCREEN.
        CHECK <LS_LIST>-STATUS > 0.
        ME->REFRESH_STATUS( EXPORTING IV_VIA_JOB = ABAP_TRUE
                            CHANGING CS_LIST = <LS_LIST> ).
        ME->SET_STATUS_DATA( EXPORTING IV_STATUS = <LS_LIST>-STATUS
                                       IV_TRTOT = <LS_LIST>-TRTOT
                                       IV_TRERR = <LS_LIST>-TRERR
                             IMPORTING EV_STATUS_TEXT = <LS_LIST>-STATUS_TXT
                                       EV_STATUS_ICON = <LS_LIST>-STATUS_ICON ).
        TRY.
            MO_SALV_TABLE->SET_DATA( CHANGING T_TABLE = YIF_FI_COUPA_ACCOUNTING~MT_LIST ).
          CATCH CX_SALV_NO_NEW_DATA_ALLOWED.
        ENDTRY.
        MO_SALV_TABLE->REFRESH( ).
    ENDCASE.

  ENDMETHOD.

* ---- YCL_FI_COUPA_ACCOUNTING_DIS===CM005 ----
  METHOD GET_DATA.

    DATA LV_STATUS_BTCI TYPE YE_BC_GENERIC_STATUS.
    DATA LV_TRERR_BTCI TYPE YE_BC_TR_ERROR_NUMBER.
    DATA LV_TREXE_BTCI TYPE YE_BC_TR_CORRECT_NUMBER.
    DATA LV_STATUS_BEFORE TYPE YE_FI_COUPA_STATUS.
    DATA LV_STATUS_AFTER TYPE YE_FI_COUPA_STATUS.

    CLEAR: YIF_FI_COUPA_ACCOUNTING~MT_LIST, YIF_FI_COUPA_ACCOUNTING~MT_PROTOCOL.

    SELECT A~APPL_KEY,
           A~ERDAT,
           A~ERTIM,
           A~ERNAM,
           A~FILENAME,
           A~STATUS,
           A~BDC_GROUP,
           A~BDC_QID,
           A~TRTOT,
           A~TRERR,
           A~TREXE
           FROM YTBC_APPL_FUP AS A
           WHERE YAPPL = @IV_APPL
           AND   APPL_KEY IN @IT_APPL_KEY
           AND   ERDAT BETWEEN @IV_BEGDA AND @IV_ENDDA
           AND   STATUS IN @IT_STATUS
      INTO CORRESPONDING FIELDS OF TABLE @YIF_FI_COUPA_ACCOUNTING~MT_LIST.

    CHECK YIF_FI_COUPA_ACCOUNTING~MT_LIST IS NOT INITIAL.

    SELECT APPL_KEY,
           SEQNR,
           MSGID,
           MSGTY,
           MSGNO,
           MSGV1,
           MSGV2,
           MSGV3,
           MSGV4
           FROM YTBC_APPL_PROT
           FOR ALL ENTRIES IN @YIF_FI_COUPA_ACCOUNTING~MT_LIST
           WHERE YAPPL = @IV_APPL
           AND   APPL_KEY = @YIF_FI_COUPA_ACCOUNTING~MT_LIST-APPL_KEY
      INTO TABLE @YIF_FI_COUPA_ACCOUNTING~MT_PROTOCOL.

    "Update BTCI status if necessary
    LOOP AT YIF_FI_COUPA_ACCOUNTING~MT_LIST ASSIGNING FIELD-SYMBOL(<LS_LIST>) WHERE BDC_QID IS NOT INITIAL
                                                                              AND   STATUS > 0.
      ME->REFRESH_STATUS( EXPORTING IV_VIA_JOB = IV_STATUS_VIA_JOB
                          CHANGING CS_LIST = <LS_LIST> ).
    ENDLOOP.

  ENDMETHOD.

* ---- YCL_FI_COUPA_ACCOUNTING_DIS===CM006 ----
  METHOD FILL_GENERIC_STATUS_RANGE.

    DATA LS_GENERIC_STATUS TYPE LINE OF TTY_STATUS_RANGE.
    FIELD-SYMBOLS <LV_FIELD> TYPE ANY.

    LOOP AT IT_STATUS ASSIGNING FIELD-SYMBOL(<LS_STATUS>).
      ASSIGN COMPONENT 1 OF STRUCTURE <LS_STATUS> TO <LV_FIELD>.
      LS_GENERIC_STATUS-SIGN = <LV_FIELD>.
      ASSIGN COMPONENT 2 OF STRUCTURE <LS_STATUS> TO <LV_FIELD>.
      LS_GENERIC_STATUS-OPTION = <LV_FIELD>.
      ASSIGN COMPONENT 3 OF STRUCTURE <LS_STATUS> TO <LV_FIELD>.
      LS_GENERIC_STATUS-LOW = <LV_FIELD>.
      ASSIGN COMPONENT 4 OF STRUCTURE <LS_STATUS> TO <LV_FIELD>.
      LS_GENERIC_STATUS-HIGH = <LV_FIELD>.
      APPEND LS_GENERIC_STATUS TO RT_GENERIC_STATUS.
    ENDLOOP.

  ENDMETHOD.

* ---- YCL_FI_COUPA_ACCOUNTING_DIS===CM007 ----
  METHOD COMPLETE_DATA.

    LOOP AT YIF_FI_COUPA_ACCOUNTING~MT_LIST ASSIGNING FIELD-SYMBOL(<LS_LIST>).
      ME->SET_STATUS_DATA( EXPORTING IV_STATUS = <LS_LIST>-STATUS
                                     IV_TRTOT = <LS_LIST>-TRTOT
                                     IV_TRERR = <LS_LIST>-TRERR
                           IMPORTING EV_STATUS_TEXT = <LS_LIST>-STATUS_TXT
                                     EV_STATUS_ICON = <LS_LIST>-STATUS_ICON ).
    ENDLOOP.

    SORT YIF_FI_COUPA_ACCOUNTING~MT_LIST BY ERDAT DESCENDING ERTIM DESCENDING.

  ENDMETHOD.

* ---- YCL_FI_COUPA_ACCOUNTING_DIS===CM008 ----
  METHOD CONSTRUCTOR.

    "Status list
    MT_STATUS = YCL_CA_UTILITIES=>GET_DOMAIN_VALUES( 'YD_FI_COUPA_STATUS' ).

  ENDMETHOD.

* ---- YCL_FI_COUPA_ACCOUNTING_DIS===CM009 ----
  METHOD SET_STATUS_DATA.

    READ TABLE MT_STATUS INTO DATA(LS_STATUS) WITH KEY DOMNAME = 'YD_FI_COUPA_STATUS'
                                                   VALUE = IV_STATUS.
    IF SY-SUBRC = 0.
      EV_STATUS_TEXT = LS_STATUS-DDTEXT.
    ENDIF.
    CASE IV_STATUS.
      WHEN YIF_FI_COUPA_ACCOUNTING~C_STATUS_OK.
        WRITE ICON_LED_GREEN TO EV_STATUS_ICON AS ICON.
      WHEN YIF_FI_COUPA_ACCOUNTING~C_STATUS_KO_FILE_EXISTS OR YIF_FI_COUPA_ACCOUNTING~C_STATUS_KO_RFBIBL_FILE.
        WRITE ICON_LED_RED TO EV_STATUS_ICON AS ICON.
      WHEN YIF_FI_COUPA_ACCOUNTING~C_STATUS_KO_POSTING OR YIF_FI_COUPA_ACCOUNTING~C_STATUS_KO_OTHERS.
        IF IV_TRERR = IV_TRTOT.
          WRITE ICON_LED_RED TO EV_STATUS_ICON AS ICON.
        ELSE.
          WRITE ICON_LED_YELLOW TO EV_STATUS_ICON AS ICON.
        ENDIF.
      WHEN YIF_FI_COUPA_ACCOUNTING~C_STATUS_IN_PROCESS.
        WRITE ICON_EXECUTE_OBJECT TO EV_STATUS_ICON AS ICON.
      WHEN OTHERS.
        WRITE ICON_SYSTEM_HELP TO EV_STATUS_ICON AS ICON.
    ENDCASE.

  ENDMETHOD.

* ---- YCL_FI_COUPA_ACCOUNTING_DIS===CM00A ----
  METHOD GET_BTCI_RESULT.

    DATA LT_APQI TYPE TABLE OF APQI.

    "Get BTCI result
    SELECT * FROM APQI WHERE DESTSYS = @SPACE
                       AND   DESTAPP = @SPACE
                       AND   DATATYP = 'BDC'
                       AND   MANDANT = @SY-MANDT
                       AND   PROGID = 'RFBIBL01'
                       AND   QID = @IV_BDC_QID
                  INTO TABLE @LT_APQI.
    READ TABLE LT_APQI INTO DATA(LS_APQI) INDEX 1.
    IF SY-SUBRC <> 0.   "No batch-input found: status unknown
      CV_STATUS = YIF_FI_COUPA_ACCOUNTING~C_STATUS_UNKNOWN.
    ELSE.
      CASE LS_APQI-QSTATE.
        WHEN 'F'.   "Finish
          CV_STATUS = YIF_FI_COUPA_ACCOUNTING~C_STATUS_OK.
          CV_TRERR = LS_APQI-TRANSCNTE.
          CV_TREXE = LS_APQI-TRANSCNTF.
        WHEN 'R'.   "Running
          CV_STATUS = YIF_FI_COUPA_ACCOUNTING~C_STATUS_IN_PROCESS.
        WHEN 'E'.
          CV_STATUS = YIF_FI_COUPA_ACCOUNTING~C_STATUS_KO_POSTING.
          CV_TRERR = LS_APQI-TRANSCNTE.
          CV_TREXE = LS_APQI-TRANSCNTF.
        WHEN OTHERS.
          CV_STATUS = YIF_FI_COUPA_ACCOUNTING~C_STATUS_UNKNOWN.
          CV_TRERR = LS_APQI-TRANSCNTE.
          CV_TREXE = LS_APQI-TRANSCNTF.
      ENDCASE.
    ENDIF.

  ENDMETHOD.

* ---- YCL_FI_COUPA_ACCOUNTING_DIS===CM00B ----
  METHOD UPDATE_YTBC_APPL_FUP.

    DATA LS_FUP TYPE YTBC_APPL_FUP.

    SELECT SINGLE * FROM YTBC_APPL_FUP WHERE YAPPL = @YIF_FI_COUPA_ACCOUNTING~C_APPL_COUPA
                                       AND   APPL_KEY = @IS_LIST-APPL_KEY
                                  INTO @LS_FUP.
    CHECK SY-SUBRC = 0.
    IF IS_LIST-STATUS <> LS_FUP-STATUS OR IS_LIST-TRERR <> LS_FUP-TRERR OR IS_LIST-TREXE <> LS_FUP-TREXE.
      UPDATE YTBC_APPL_FUP SET STATUS = IS_LIST-STATUS
                               TRERR = IS_LIST-TRERR
                               TREXE = IS_LIST-TREXE
                           WHERE YAPPL = LS_FUP-YAPPL
                           AND   APPL_KEY = LS_FUP-APPL_KEY.
    ENDIF.

  ENDMETHOD.

* ---- YCL_FI_COUPA_ACCOUNTING_DIS===CM00C ----
  METHOD REFRESH_STATUS.

    DATA LV_STATUS_BTCI TYPE YE_BC_GENERIC_STATUS.
    DATA LV_TRERR_BTCI TYPE YE_BC_TR_ERROR_NUMBER.
    DATA LV_TREXE_BTCI TYPE YE_BC_TR_CORRECT_NUMBER.
    DATA LV_STATUS_BEFORE TYPE YE_FI_COUPA_STATUS.
    DATA LV_STATUS_AFTER TYPE YE_FI_COUPA_STATUS.
    DATA LX_FILE_ACCESS TYPE REF TO YCX_FILE_ACCESS.

    LV_STATUS_BTCI = CS_LIST-STATUS.
    LV_TRERR_BTCI = CS_LIST-TRERR.
    LV_TREXE_BTCI = CS_LIST-TREXE.
    ME->GET_BTCI_RESULT( EXPORTING IV_BDC_QID = CS_LIST-BDC_QID
                         CHANGING  CV_STATUS = LV_STATUS_BTCI
                                   CV_TRERR = LV_TRERR_BTCI
                                   CV_TREXE = LV_TREXE_BTCI ).
    IF LV_STATUS_BTCI <> CS_LIST-STATUS.
      "move file
      LV_STATUS_BEFORE = CS_LIST-STATUS.
      LV_STATUS_AFTER = LV_STATUS_BTCI.
      TRY.
          ME->MOVE_FILE( IV_FILE = CS_LIST-FILENAME
                         IV_STATUS_BEFORE = LV_STATUS_BEFORE
                         IV_STATUS_AFTER = LV_STATUS_AFTER
                         IV_VIA_JOB = IV_VIA_JOB
                         IV_USER = 'JOBBATCH' ).
        CATCH YCX_FILE_ACCESS INTO LX_FILE_ACCESS.
          MESSAGE S040(YCOMMON).
      ENDTRY.
    ENDIF.
    IF LV_STATUS_BTCI <> CS_LIST-STATUS OR LV_TRERR_BTCI <> CS_LIST-TRERR OR LV_TREXE_BTCI <> CS_LIST-TREXE.
      CS_LIST-STATUS = LV_STATUS_BTCI.
      CS_LIST-TRERR = LV_TRERR_BTCI.
      CS_LIST-TREXE = LV_TREXE_BTCI.
      ME->UPDATE_YTBC_APPL_FUP( IS_LIST = CS_LIST ).
    ENDIF.

  ENDMETHOD.

* ---- YCL_FI_COUPA_ACCOUNTING_DIS===CM00D ----
  METHOD MOVE_FILE.

    DATA LV_SOURCE_PATH TYPE STRING.
    DATA LV_TARGET_PATH TYPE STRING.
    DATA LV_JOBNAME TYPE TBTCJOB-JOBNAME.
    DATA LV_JOBCOUNT TYPE TBTCJOB-JOBCOUNT.
    DATA LV_ABORTED TYPE XFELD.
    DATA LV_FINISHED TYPE XFELD.
    DATA LV_PRELIMINARY TYPE XFELD.
    DATA LV_READY TYPE XFELD.
    DATA LV_RUNNING TYPE XFELD.
    DATA LV_SCHEDULED TYPE XFELD.
    DATA LV_SUSPENDED TYPE XFELD.
    DATA LV_OTHER TYPE XFELD.
    DATA LV_ERROR TYPE XFELD.
    DATA LV_COUNT TYPE I.

    IF IV_STATUS_BEFORE IS NOT SUPPLIED.
      LV_SOURCE_PATH = ME->GET_FILE_PATH_FROM_STATUS( IV_FILE = IV_FILE ).
    ELSE.
      "Get source path
      LV_SOURCE_PATH = ME->GET_FILE_PATH_FROM_STATUS( IV_FILE = IV_FILE
                                                      IV_STATUS = IV_STATUS_BEFORE ).
    ENDIF.
    "Get target path
    LV_TARGET_PATH = ME->GET_FILE_PATH_FROM_STATUS( IV_FILE = IV_FILE
                                                    IV_STATUS = IV_STATUS_AFTER ).

    CHECK LV_TARGET_PATH <> LV_SOURCE_PATH.
    "Move file
    IF IV_VIA_JOB = ABAP_FALSE.
      YCL_BC_FILE_UTIL=>MOVE_OR_COPY_FILE( IV_ACTION = 'M'
                                           IV_SOURCE_FILE = LV_SOURCE_PATH
                                           IV_TARGET_FILE = LV_TARGET_PATH ).
    ELSE.
      LV_JOBNAME = |COUPA_MOVE_FILE_{ SY-DATUM }_{ SY-UZEIT }|.
      CALL FUNCTION 'JOB_OPEN'
        EXPORTING
          JOBNAME          = LV_JOBNAME
        IMPORTING
          JOBCOUNT         = LV_JOBCOUNT
        EXCEPTIONS
          CANT_CREATE_JOB  = 1
          INVALID_JOB_DATA = 2
          JOBNAME_MISSING  = 3
          OTHERS           = 4.
      IF SY-SUBRC <> 0.
        RAISE EXCEPTION TYPE YCX_FILE_ACCESS
          EXPORTING
            TEXTID      = YCX_FILE_ACCESS=>FILE_ACTION_ERROR
            FILE_ACTION = 'move'.
      ENDIF.
      SUBMIT YBC_MOVE_OR_COPY_FILE WITH P_FILE_S = LV_SOURCE_PATH
                                   WITH P_FILE_T = LV_TARGET_PATH
                                   WITH P_MOVE = ABAP_TRUE
                                   USER IV_USER VIA JOB LV_JOBNAME NUMBER LV_JOBCOUNT
                                   AND RETURN.
      CALL FUNCTION 'JOB_CLOSE'
        EXPORTING
          JOBCOUNT             = LV_JOBCOUNT
          JOBNAME              = LV_JOBNAME
          STRTIMMED            = ABAP_TRUE
        EXCEPTIONS
          CANT_START_IMMEDIATE = 1
          INVALID_STARTDATE    = 2
          JOBNAME_MISSING      = 3
          JOB_CLOSE_FAILED     = 4
          JOB_NOSTEPS          = 5
          JOB_NOTEX            = 6
          LOCK_FAILED          = 7
          INVALID_TARGET       = 8
          OTHERS               = 9.
      IF SY-SUBRC <> 0.
        RAISE EXCEPTION TYPE YCX_FILE_ACCESS
          EXPORTING
            TEXTID      = YCX_FILE_ACCESS=>FILE_ACTION_ERROR
            FILE_ACTION = 'move'.
      ENDIF.
      "Wait for job result
      DO.
        ADD 1 TO LV_COUNT.
        CALL FUNCTION 'SHOW_JOBSTATE'
          EXPORTING
            JOBCOUNT         = LV_JOBCOUNT
            JOBNAME          = LV_JOBNAME
          IMPORTING
            ABORTED          = LV_ABORTED
            FINISHED         = LV_FINISHED
            PRELIMINARY      = LV_PRELIMINARY
            READY            = LV_READY
            RUNNING          = LV_RUNNING
            SCHEDULED        = LV_SCHEDULED
            SUSPENDED        = LV_SUSPENDED
            OTHER            = LV_OTHER
          EXCEPTIONS
            JOBCOUNT_MISSING = 1
            JOBNAME_MISSING  = 2
            JOB_NOTEX        = 3
            OTHERS           = 4.
        IF SY-SUBRC <> 0.
          EXIT.
        ENDIF.
        IF LV_FINISHED = ABAP_TRUE.
          EXIT.
        ELSEIF LV_READY = ABAP_TRUE OR LV_RUNNING = ABAP_TRUE.
          WAIT UP TO 1 SECONDS.
        ELSE.
          RAISE EXCEPTION TYPE YCX_FILE_ACCESS
            EXPORTING
              TEXTID      = YCX_FILE_ACCESS=>FILE_ACTION_ERROR
              FILE_ACTION = 'move'.
          EXIT.
        ENDIF.
        IF LV_COUNT > 30.
          RAISE EXCEPTION TYPE YCX_FILE_ACCESS
            EXPORTING
              TEXTID      = YCX_FILE_ACCESS=>FILE_ACTION_ERROR
              FILE_ACTION = 'move'.
          EXIT.
        ENDIF.
      ENDDO.
    ENDIF.

  ENDMETHOD.

* ---- YCL_FI_COUPA_ACCOUNTING_DIS===CM00E ----
  METHOD GET_FILE_PATH_FROM_STATUS.

    IF IV_STATUS IS NOT SUPPLIED.   "Initial situation: file in folder data
      RV_PATH_AND_FILE = ME->GET_FILE_PATH( IV_LOGICAL_PATH = YIF_FI_COUPA_ACCOUNTING~C_PATH_DATA
                                           IV_PHYSICAL_FILE = IV_FILE ).
    ELSE.

      CASE IV_STATUS.
        WHEN YIF_FI_COUPA_ACCOUNTING~C_STATUS_OK.   "OK
          "File in archives folder
          RV_PATH_AND_FILE = ME->GET_FILE_PATH( IV_LOGICAL_PATH = YIF_FI_COUPA_ACCOUNTING~C_PATH_ARCHIVE
                                                IV_PHYSICAL_FILE = IV_FILE ).
        WHEN YIF_FI_COUPA_ACCOUNTING~C_STATUS_KO_FILE_EXISTS.     "File already loaded
          "File in data\post\double folder
          RV_PATH_AND_FILE = ME->GET_FILE_PATH( IV_LOGICAL_PATH = YIF_FI_COUPA_ACCOUNTING~C_PATH_DOUBLE
                                                IV_PHYSICAL_FILE = IV_FILE ).
        WHEN YIF_FI_COUPA_ACCOUNTING~C_STATUS_KO_RFBIBL_FILE.     "Error in RFBIBL00 file generation
          "File in error folder
          RV_PATH_AND_FILE = ME->GET_FILE_PATH( IV_LOGICAL_PATH = YIF_FI_COUPA_ACCOUNTING~C_PATH_ERROR
                                                IV_PHYSICAL_FILE = IV_FILE ).
        WHEN YIF_FI_COUPA_ACCOUNTING~C_STATUS_IN_PROCESS.
          "File in process folder
          RV_PATH_AND_FILE = ME->GET_FILE_PATH( IV_LOGICAL_PATH = YIF_FI_COUPA_ACCOUNTING~C_PATH_PROCESS
                                                IV_PHYSICAL_FILE = IV_FILE ).
        WHEN OTHERS.
          "File in error folder
          RV_PATH_AND_FILE = ME->GET_FILE_PATH( IV_LOGICAL_PATH = YIF_FI_COUPA_ACCOUNTING~C_PATH_ERROR
                                                IV_PHYSICAL_FILE = IV_FILE ).
      ENDCASE.
    ENDIF.

  ENDMETHOD.

* ---- YCL_FI_COUPA_ACCOUNTING_DIS===CM00F ----
  METHOD GET_FILE_PATH.

    "Get directory for COUPA files
    CALL FUNCTION 'FILE_GET_NAME_USING_PATH'
      EXPORTING
*       CLIENT                     = SY-MANDT
        LOGICAL_PATH               = IV_LOGICAL_PATH
*       OPERATING_SYSTEM           = SY-OPSYS
        PARAMETER_1                = SY-SYSID
*       PARAMETER_2                = ' '
*       PARAMETER_3                = ' '
*       USE_BUFFER                 = ' '
        FILE_NAME                  = IV_PHYSICAL_FILE
*       USE_PRESENTATION_SERVER    = ' '
        ELEMINATE_BLANKS           = ' '
      IMPORTING
        FILE_NAME_WITH_PATH        = RV_PHYSICAL_PATH
      EXCEPTIONS
        PATH_NOT_FOUND             = 1
        MISSING_PARAMETER          = 2
        OPERATING_SYSTEM_NOT_FOUND = 3
        FILE_SYSTEM_NOT_FOUND      = 4
        OTHERS                     = 5.
    IF SY-SUBRC <> 0.
      RAISE EXCEPTION TYPE YCX_FILE_ACCESS
        EXPORTING
          TEXTID     = YCX_FILE_ACCESS=>PATH_ACCESS_ERROR
          PATH_NAME1 = IV_LOGICAL_PATH(50).
    ENDIF.

  ENDMETHOD.

* ---- YCL_FI_COUPA_ACCOUNTING_DIS===CM00G ----
  METHOD PREPARE_AND_SEND_MAIL.

    DATA LT_BODY TYPE SOLI_TAB.
    DATA LV_EXIST_DATA TYPE XFELD.
    DATA LS_STATUS TYPE LINE OF YCL_CA_UTILITIES=>TTY_DOMAIN_VALUE.
    DATA LV_STRING TYPE STRING.
    DATA LO_MAIL_GENERATOR TYPE REF TO YCL_BC_MAIL_GENERATOR.

    "Prepare body mail
    APPEND 'Dear BFM colleagues,' TO LT_BODY.
    APPEND SPACE TO LT_BODY.
    IF IV_ONLY_ERROR = ABAP_TRUE.
      APPEND 'Some errors occured during G/L posting from COUPA in the following file(s):' TO LT_BODY.
    ELSE.
      APPEND 'Please find below status of G/L posting file(s) from COUPA:' TO LT_BODY.
    ENDIF.

    LOOP AT YIF_FI_COUPA_ACCOUNTING~MT_LIST INTO DATA(LS_LIST).
      IF IV_ONLY_ERROR = ABAP_TRUE.
        CHECK LS_LIST-STATUS > YIF_FI_COUPA_ACCOUNTING~C_STATUS_OK.
      ENDIF.
      LV_EXIST_DATA = ABAP_TRUE.
      CLEAR LS_STATUS.
      READ TABLE MT_STATUS INTO LS_STATUS WITH KEY DOMNAME = 'YD_FI_COUPA_STATUS'
                                                   VALUE = LS_LIST-STATUS.
      LV_STRING = |{ LS_LIST-FILENAME }: { LS_STATUS-DDTEXT }|.
      APPEND LV_STRING TO LT_BODY.
    ENDLOOP.

    CHECK LV_EXIST_DATA = ABAP_TRUE.

    APPEND SPACE TO LT_BODY.
    APPEND 'You can manage the errors by executing transaction YFI_COUPA_DIS in IRIS.' TO LT_BODY.
    APPEND SPACE TO LT_BODY.
    APPEND 'Best regards' TO LT_BODY.
    APPEND 'G/L posting from COUPA interface' TO LT_BODY.

    IF YCL_CA_UTILITIES=>IS_PRODUCTION_SYSTEM( ) = ABAP_FALSE.
      LV_STRING = |TEST { SY-SYSID } - G/L posting from COUPA interface status|.
    ELSE.
      LV_STRING = 'G/L posting from COUPA interface status'.
    ENDIF.

    LO_MAIL_GENERATOR = NEW YCL_BC_MAIL_GENERATOR( YIF_FI_COUPA_ACCOUNTING~C_APPL_COUPA ).
    LO_MAIL_GENERATOR->FILL_MAIL_CONTENT( IV_HEADER = LV_STRING
                                          IT_BODY = LT_BODY
                                          IV_CONVERT_TO_HTML = ABAP_TRUE ).
    LO_MAIL_GENERATOR->SEND_MAIL( IT_MAIL_ADDRESS = IT_MAIL_ADDRESS ).

  ENDMETHOD.

* ---- YCL_FI_COUPA_ACCOUNTING_DIS===CO ----
PROTECTED SECTION.

* ---- YCL_FI_COUPA_ACCOUNTING_DIS===CU ----
CLASS YCL_FI_COUPA_ACCOUNTING_DIS DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

PUBLIC SECTION.

  INTERFACES YIF_FI_COUPA_ACCOUNTING .

  TYPES:
    TTY_STATUS_RANGE TYPE RANGE OF YE_BC_GENERIC_STATUS .
  TYPES:
    TTY_APPL_KEY_RANGE TYPE RANGE OF YE_BC_APPLICATION_KEY .

  METHODS PREPARE_AND_SEND_MAIL
    IMPORTING
      !IT_MAIL_ADDRESS TYPE YCL_BC_MAIL_GENERATOR=>TTY_MAIL_ADDRESS
      !IV_ONLY_ERROR TYPE XFELD DEFAULT ABAP_TRUE .
  METHODS CONSTRUCTOR .
  METHODS MOVE_FILE
    IMPORTING
      !IV_FILE TYPE FILENAME_AL11
      !IV_STATUS_BEFORE TYPE YE_FI_COUPA_STATUS OPTIONAL
      !IV_STATUS_AFTER TYPE YE_FI_COUPA_STATUS
      !IV_VIA_JOB TYPE XFELD DEFAULT ABAP_FALSE
      !IV_USER TYPE SY-UNAME DEFAULT 'JOBBATCH'
    RAISING
      YCX_FILE_ACCESS .
  METHODS COMPLETE_DATA .
  METHODS FILL_GENERIC_STATUS_RANGE
    IMPORTING
      !IT_STATUS TYPE ANY TABLE
    RETURNING
      VALUE(RT_GENERIC_STATUS) TYPE TTY_STATUS_RANGE .
  METHODS GET_DATA
    IMPORTING
      !IV_APPL TYPE YE_APPL
      !IV_BEGDA TYPE BEGDA DEFAULT '19000101'
      !IV_ENDDA TYPE ENDDA DEFAULT '99991231'
      !IT_STATUS TYPE TTY_STATUS_RANGE OPTIONAL
      !IT_APPL_KEY TYPE TTY_APPL_KEY_RANGE OPTIONAL
      !IV_STATUS_VIA_JOB TYPE XFELD DEFAULT ABAP_FALSE .
  METHODS DISPLAY_ALV
    IMPORTING
      !IV_REPID TYPE SY-REPID DEFAULT SY-REPID .