* ==== CLASS POOL YCL_FI_POSTING_LIMIT_BL ====
CLASS-POOL .
*"* class pool for class YCL_FI_POSTING_LIMIT_BL

*"* local type definitions
INCLUDE YCL_FI_POSTING_LIMIT_BL=======CCDEF.

*"* class YCL_FI_POSTING_LIMIT_BL definition
*"* public declarations
  INCLUDE YCL_FI_POSTING_LIMIT_BL=======CU.
*"* protected declarations
  INCLUDE YCL_FI_POSTING_LIMIT_BL=======CO.
*"* private declarations
  INCLUDE YCL_FI_POSTING_LIMIT_BL=======CI.
ENDCLASS. "YCL_FI_POSTING_LIMIT_BL definition

*"* macro definitions
INCLUDE YCL_FI_POSTING_LIMIT_BL=======CCMAC.
*"* local class implementation
INCLUDE YCL_FI_POSTING_LIMIT_BL=======CCIMP.

CLASS YCL_FI_POSTING_LIMIT_BL IMPLEMENTATION.
*"* method's implementations
  INCLUDE METHODS.
ENDCLASS. "YCL_FI_POSTING_LIMIT_BL implementation


* ---- YCL_FI_POSTING_LIMIT_BL=======CI ----
PRIVATE SECTION.

  TYPES:
    BEGIN OF TY_PLACE,
      CODE       TYPE STRING,
      TEXT       TYPE STRING,
      PLACE_TYPE TYPE STRING,
    END OF TY_PLACE .
  TYPES:
    BEGIN OF TY_CERTIF_LIMIT,
      UNAME TYPE USNAM,
      NAME  TYPE AD_NAMTEXT,
      LIMIT TYPE INT4,
      RFPRO TYPE RFPRO,
    END OF TY_CERTIF_LIMIT .
  TYPES:
    BEGIN OF TY_LIST_T043,
      STATUS  TYPE P_99S_STATU.
      INCLUDE TYPE TY_CERTIF_LIMIT.
      TYPES: MESSAGE TYPE BAPI_MSG,
    END OF TY_LIST_T043 .
  TYPES:
    BEGIN OF TY_T043_ACTION,
      ACTION TYPE CHAR1,
      USNAM  TYPE T043-USNAM,
      RFPRO  TYPE T043-RFPRO,
    END OF TY_T043_ACTION .
  TYPES:
    BEGIN OF TY_T043T_UPDATE,
      RFPRO     TYPE T043T-RFPRO,
      BUKRS     TYPE T043T-BUKRS,
      WAERS     TYPE WAERS,
      MAXBT_OLD TYPE T043T-MAXBT,
      MAXBT_NEW TYPE T043T-MAXBT,
      MAXEB_OLD TYPE T043T-MAXEB,
      MAXEB_NEW TYPE T043T-MAXEB,
    END OF TY_T043T_UPDATE .

  DATA MV_REPID TYPE SY-REPID .
  DATA:
    MT_PLACE TYPE TABLE OF TY_PLACE .
  DATA:
    MT_MEMBER TYPE TABLE OF TY_CERTIF_LIMIT .
  DATA:
    MT_CERTIF_LIMIT TYPE TABLE OF TY_CERTIF_LIMIT .
  DATA:
    MT_T043_ACTION TYPE TABLE OF TY_T043_ACTION .
  DATA:
    MT_LIST_T043 TYPE TABLE OF TY_LIST_T043 .
  DATA:
    MT_T043T_UPDATE TYPE TABLE OF TY_T043T_UPDATE .
  DATA MO_ROLE_PROXY TYPE REF TO ZROLE_MGTCO_FACADE .
  DATA MO_DISPLAY_SETTINGS TYPE REF TO CL_SALV_DISPLAY_SETTINGS .
  DATA MO_SALV_TABLE TYPE REF TO CL_SALV_TABLE .
  DATA MO_LAYOUT TYPE REF TO CL_SALV_LAYOUT .

  METHODS INIT_ALV
    CHANGING
      !CT_TABLE TYPE ANY TABLE .
  METHODS GET_CONVERTED_AMOUNT
    IMPORTING
      !IV_RFPRO TYPE RFPRO
      !IV_WAERS TYPE WAERS
    EXPORTING
      !EV_AMOUNT TYPE MAXBT_043T .
  METHODS SET_COLUMNS_FOR_T043T_LIST .
  METHODS SET_COLUMNS_FOR_T043_LIST .
  METHODS FILL_STATUS
    IMPORTING
      !IV_ACTION TYPE CHAR1
    CHANGING
      !CS_LIST TYPE TY_LIST_T043 .
  METHODS COMPARE_DATA .
  METHODS BUILD_GROUP
    IMPORTING
      !IV_LIMIT TYPE INT4
    RETURNING
      VALUE(RV_RFPRO) TYPE RFPRO .
  METHODS PREPARE_DATA .
  METHODS GET_CERTIFYING_OFFICER
    RAISING
      YCX_COMMUNICATION_CHECK .
  METHODS GET_PLACES
    RAISING
      YCX_COMMUNICATION_CHECK .

* ---- YCL_FI_POSTING_LIMIT_BL=======CM001 ----
METHOD GET_CERTIFYING_OFF_WITH_LIMIT.

  "Create connection
  TRY.
      MO_ROLE_PROXY = NEW ZROLE_MGTCO_FACADE( LOGICAL_PORT_NAME = 'LP_ROLE_MGT' ).
    CATCH CX_AI_SYSTEM_FAULT . " Application Integration: Technical Error
      RAISE EXCEPTION TYPE YCX_COMMUNICATION_CHECK
        EXPORTING
          TEXTID       = YCX_COMMUNICATION_CHECK=>PROXY_ERROR
          LOGICAL_PORT = 'LP_ROLE_MGT'.
  ENDTRY.

  "First, get all places
  ME->GET_PLACES( ).

  "Second, get certifying officers from each place
  ME->GET_CERTIFYING_OFFICER( ).

  "Third, fill tables with data
  ME->PREPARE_DATA( ).

  "Then, compare with table T043
  ME->COMPARE_DATA( ).

ENDMETHOD.

* ---- YCL_FI_POSTING_LIMIT_BL=======CM002 ----
  METHOD GET_PLACES.

    DATA LS_INPUT_PLACE TYPE ZFACADE_GET_PLACES_INPUT_MESSA.
    DATA LS_OUTPUT_PLACE TYPE ZFACADE_GET_PLACES_OUTPUT_MESS.
    DATA LS_PLACE TYPE TY_PLACE.

    CLEAR MT_PLACE.

    TRY.
        MO_ROLE_PROXY->GET_PLACES( EXPORTING INPUT = LS_INPUT_PLACE
                                   IMPORTING OUTPUT = LS_OUTPUT_PLACE ).
      CATCH CX_AI_SYSTEM_FAULT . " Application Integration: Technical Error
        RAISE EXCEPTION TYPE YCX_COMMUNICATION_CHECK
          EXPORTING
            TEXTID      = YCX_COMMUNICATION_CHECK=>WEB_SERVICE_ERROR
            WEB_SERVICE = 'GET_PLACES'.
    ENDTRY.

    LOOP AT LS_OUTPUT_PLACE-GET_PLACES_RESULT-RESULT-PLACE_ITEM INTO DATA(LS_PLACE_ITEM).
      LS_PLACE-CODE = LS_PLACE_ITEM-BASE-CODE.
      LS_PLACE-TEXT = LS_PLACE_ITEM-BASE-TEXT.
      LS_PLACE-PLACE_TYPE = LS_PLACE-PLACE_TYPE.
      APPEND LS_PLACE TO MT_PLACE.
    ENDLOOP.

  ENDMETHOD.

* ---- YCL_FI_POSTING_LIMIT_BL=======CM003 ----
  METHOD GET_CERTIFYING_OFFICER.

    DATA LS_INPUT_ROLE TYPE ZFACADE_GET_ROLE_MEMBERS_INPUT.
    DATA LS_OUTPUT_ROLE TYPE ZFACADE_GET_ROLE_MEMBERS_OUTPU.
    DATA LS_CERTIF_LIMIT TYPE TY_CERTIF_LIMIT.

    CLEAR MT_MEMBER.

    LOOP AT MT_PLACE INTO DATA(LS_PLACE).
      LS_INPUT_ROLE-REQUEST-ROLE = 'CERTIFYING'.
      LS_INPUT_ROLE-REQUEST-PLACE = LS_PLACE-CODE.
      TRY.
          MO_ROLE_PROXY->GET_ROLE_MEMBERS( EXPORTING INPUT = LS_INPUT_ROLE
                                           IMPORTING OUTPUT = LS_OUTPUT_ROLE ).
        CATCH CX_AI_SYSTEM_FAULT . " Application Integration: Technical Error
          RAISE EXCEPTION TYPE YCX_COMMUNICATION_CHECK
            EXPORTING
              TEXTID      = YCX_COMMUNICATION_CHECK=>WEB_SERVICE_ERROR
              WEB_SERVICE = 'GET_ROLE_MEMBERS'.
      ENDTRY.
      LOOP AT LS_OUTPUT_ROLE-GET_ROLE_MEMBERS_RESULT-RESULT-ROLE_MEMBER_ITEM INTO DATA(LS_MEMBER).
        LS_CERTIF_LIMIT-UNAME = LS_MEMBER-LOGON_NAME.
        TRANSLATE LS_CERTIF_LIMIT-UNAME TO UPPER CASE.
        LS_CERTIF_LIMIT-NAME = LS_MEMBER-NAME.
        LS_CERTIF_LIMIT-LIMIT = LS_MEMBER-LIMIT.
        APPEND LS_CERTIF_LIMIT TO MT_CERTIF_LIMIT.
      ENDLOOP.
    ENDLOOP.

    SORT MT_CERTIF_LIMIT BY UNAME LIMIT.
    DELETE ADJACENT DUPLICATES FROM MT_CERTIF_LIMIT COMPARING UNAME LIMIT.

  ENDMETHOD.

* ---- YCL_FI_POSTING_LIMIT_BL=======CM004 ----
  METHOD PREPARE_DATA.

    DATA LV_LIMIT TYPE INT4.
    DATA LV_NEW TYPE XFELD.
    DATA LV_END TYPE XFELD.
    DATA LV_SKIP TYPE XFELD.
    DATA LT_CERTIF_LIMIT TYPE TABLE OF TY_CERTIF_LIMIT.

    LT_CERTIF_LIMIT = MT_CERTIF_LIMIT.
    CLEAR MT_CERTIF_LIMIT.

    SORT LT_CERTIF_LIMIT BY UNAME LIMIT.

    LOOP AT LT_CERTIF_LIMIT INTO DATA(LS_CERTIF).
      LV_NEW = ABAP_FALSE.
      LV_END = ABAP_FALSE.
      AT NEW UNAME.
        LV_SKIP = ABAP_FALSE.
        LV_NEW = ABAP_TRUE.
      ENDAT.
      AT END OF UNAME.
        LV_END = ABAP_TRUE.
      ENDAT.
      CHECK LV_SKIP = ABAP_FALSE.
      IF LV_NEW = ABAP_TRUE  AND LS_CERTIF-LIMIT = 0.
        LS_CERTIF-RFPRO =  ME->BUILD_GROUP( LS_CERTIF-LIMIT ).
        APPEND LS_CERTIF TO MT_CERTIF_LIMIT.
        LV_SKIP = ABAP_TRUE.
      ELSEIF LV_END = ABAP_TRUE.
        LS_CERTIF-RFPRO = ME->BUILD_GROUP( LS_CERTIF-LIMIT ).
        APPEND LS_CERTIF TO MT_CERTIF_LIMIT.
      ENDIF.
    ENDLOOP.

  ENDMETHOD.

* ---- YCL_FI_POSTING_LIMIT_BL=======CM005 ----
  METHOD BUILD_GROUP.

    DATA LV_INT4 TYPE INT4.
    DATA LV_NUM4(4) TYPE N.

    IF IV_LIMIT = 0.
      RV_RFPRO = '/NL/'. "No limit
    ELSE.
      LV_INT4 = IV_LIMIT / 1000.
      IF LV_INT4 < 10000.
        LV_NUM4 = LV_INT4.
        RV_RFPRO = LV_NUM4.
      ELSE.
        RV_RFPRO = '/OV/'.   "Overflow
      ENDIF.
    ENDIF.

  ENDMETHOD.

* ---- YCL_FI_POSTING_LIMIT_BL=======CM006 ----
  METHOD COMPARE_DATA.

    DATA LS_LIST TYPE TY_LIST_T043.
    DATA LT_RFPRO TYPE RANGE OF RFPRO.
    DATA LT_T043 TYPE TABLE OF T043.

    "Get current data
    SELECT * FROM T043 INTO TABLE @LT_T043.

    "Get existing groups
    SELECT DISTINCT 'I', 'EQ', RFPRO AS LOW FROM T043T INTO TABLE @LT_RFPRO.
    DELETE LT_RFPRO WHERE LOW IS INITIAL.

    CHECK LT_RFPRO IS NOT INITIAL.

    "Compare
    LOOP AT MT_CERTIF_LIMIT INTO DATA(LS_CERTIF_LIMIT).
      CLEAR LS_LIST.
      MOVE-CORRESPONDING LS_CERTIF_LIMIT TO LS_LIST.
      READ TABLE LT_T043 INTO DATA(LS_T043) WITH KEY USNAM = LS_CERTIF_LIMIT-UNAME.
      IF SY-SUBRC = 0.
        DELETE LT_T043 INDEX SY-TABIX.
        IF LS_CERTIF_LIMIT-RFPRO = LS_T043-RFPRO.
          "No update to do
          ME->FILL_STATUS( EXPORTING IV_ACTION = '=' CHANGING CS_LIST = LS_LIST ).
        ELSE.
          IF LS_CERTIF_LIMIT-RFPRO IN LT_RFPRO.
            "Update group
            ME->FILL_STATUS( EXPORTING IV_ACTION = 'U' CHANGING CS_LIST = LS_LIST ).
          ELSE.
            IF LS_CERTIF_LIMIT-RFPRO = '/NL/'.   "No limit
              "No limit: delete entry from table T043
              ME->FILL_STATUS( EXPORTING IV_ACTION = 'D' CHANGING CS_LIST = LS_LIST ).
              LS_LIST-RFPRO = LS_T043-RFPRO.
            ELSEIF LS_CERTIF_LIMIT-RFPRO = '/OV/'. "Overflow
              ME->FILL_STATUS( EXPORTING IV_ACTION = 'O' CHANGING CS_LIST = LS_LIST ).
            ELSE.
              "Unknown group
              ME->FILL_STATUS( EXPORTING IV_ACTION = 'E' CHANGING CS_LIST = LS_LIST ).
            ENDIF.
          ENDIF.
        ENDIF.
      ELSE.
        IF LS_CERTIF_LIMIT-RFPRO IN LT_RFPRO.
          "New entry
          WRITE ICON_CREATE TO LS_LIST-STATUS AS ICON.
          ME->FILL_STATUS( EXPORTING IV_ACTION = 'I' CHANGING CS_LIST = LS_LIST ).
        ELSEIF LS_CERTIF_LIMIT-RFPRO = '/NL/'.   "No limit
          "Nothing to do
          CONTINUE.
        ELSEIF LS_CERTIF_LIMIT-RFPRO = '/OV/'. "Overflow
          ME->FILL_STATUS( EXPORTING IV_ACTION = 'O' CHANGING CS_LIST = LS_LIST ).
        ELSE.
          "Unknown group
          ME->FILL_STATUS( EXPORTING IV_ACTION = 'E' CHANGING CS_LIST = LS_LIST ).
        ENDIF.
      ENDIF.
      APPEND LS_LIST TO MT_LIST_T043.
    ENDLOOP.

    LOOP AT LT_T043 INTO LS_T043.
      CHECK LS_T043-RFPRO CO '0123456789'.
      CLEAR LS_LIST.
      LS_LIST-UNAME = LS_T043-USNAM.
      LS_LIST-RFPRO = LS_T043-RFPRO.
      ME->FILL_STATUS( EXPORTING IV_ACTION = 'D' CHANGING CS_LIST = LS_LIST ).
      APPEND LS_LIST TO MT_LIST_T043.
    ENDLOOP.

  ENDMETHOD.

* ---- YCL_FI_POSTING_LIMIT_BL=======CM007 ----
  METHOD FILL_STATUS.

    DATA LS_T043_ACTION TYPE TY_T043_ACTION..

    LS_T043_ACTION-ACTION = IV_ACTION.

    CASE IV_ACTION.
      WHEN 'I'. "Insert
        WRITE ICON_CREATE TO CS_LIST-STATUS AS ICON.
        CS_LIST-MESSAGE = 'New entry'.
        LS_T043_ACTION-USNAM = CS_LIST-UNAME.
        LS_T043_ACTION-RFPRO = CS_LIST-RFPRO.
        APPEND LS_T043_ACTION TO MT_T043_ACTION.
      WHEN 'U'. "Update
        WRITE ICON_CHANGE TO CS_LIST-STATUS AS ICON.
        CS_LIST-MESSAGE = 'Group updated'.
        LS_T043_ACTION-USNAM = CS_LIST-UNAME.
        LS_T043_ACTION-RFPRO = CS_LIST-RFPRO.
        APPEND LS_T043_ACTION TO MT_T043_ACTION.
      WHEN 'D'. "Delete
        WRITE ICON_DELETE TO CS_LIST-STATUS AS ICON.
        CS_LIST-MESSAGE = 'User deleted from tolerance table'.
        LS_T043_ACTION-USNAM = CS_LIST-UNAME.
        LS_T043_ACTION-RFPRO = CS_LIST-RFPRO.
        APPEND LS_T043_ACTION TO MT_T043_ACTION .
      WHEN '='. "Nothing to do
        WRITE ICON_EQUAL_GREEN TO CS_LIST-STATUS AS ICON.
        CS_LIST-MESSAGE = 'No change to do'.
      WHEN 'E'. "Error on group
        WRITE ICON_FAILURE TO CS_LIST-STATUS AS ICON.
        CS_LIST-MESSAGE = 'Tolerance group doesn''t exist'.
      WHEN 'O'. "Overflow on group determination
        WRITE ICON_FAILURE TO CS_LIST-STATUS AS ICON.
        CS_LIST-MESSAGE = 'Tolerance group is greater than 9999'.
    ENDCASE.

  ENDMETHOD.

* ---- YCL_FI_POSTING_LIMIT_BL=======CM008 ----
  METHOD GET_AMOUNTS_TO_UPDATE.

    DATA LT_T001 TYPE TABLE OF T001.
    DATA LT_T043T TYPE TABLE OF T043T.
    DATA LV_AMOUNT TYPE MAXBT_043T.
    DATA LS_T043T_UPDATE TYPE TY_T043T_UPDATE.

    "Get company code non USD
    SELECT * FROM T001 WHERE WAERS <> 'USD' INTO TABLE @LT_T001.
    CHECK LT_T001 IS NOT INITIAL.

    SELECT * FROM T043T FOR ALL ENTRIES IN @LT_T001
                        WHERE BUKRS = @LT_T001-BUKRS
                        INTO TABLE @LT_T043T.

    LOOP AT LT_T043T INTO DATA(LS_T043T).
      CHECK LS_T043T-RFPRO CO '0123456789'.
      "Get currency for company code
      READ TABLE LT_T001 INTO DATA(LS_T001) WITH KEY BUKRS = LS_T043T-BUKRS.
      "Get limit amount in company currency
      ME->GET_CONVERTED_AMOUNT( EXPORTING IV_RFPRO = LS_T043T-RFPRO
                                          IV_WAERS = LS_T001-WAERS
                                IMPORTING EV_AMOUNT = LV_AMOUNT ).
      CHECK LS_T043T-MAXBT <> LV_AMOUNT OR LS_T043T-MAXEB <> LV_AMOUNT.
      LS_T043T_UPDATE-RFPRO = LS_T043T-RFPRO.
      LS_T043T_UPDATE-BUKRS = LS_T043T-BUKRS.
      LS_T043T_UPDATE-WAERS = LS_T001-WAERS.
      LS_T043T_UPDATE-MAXBT_OLD = LS_T043T-MAXBT.
      LS_T043T_UPDATE-MAXBT_NEW = LV_AMOUNT.
      LS_T043T_UPDATE-MAXEB_OLD = LS_T043T-MAXEB.
      LS_T043T_UPDATE-MAXEB_NEW = LV_AMOUNT.
      APPEND LS_T043T_UPDATE TO MT_T043T_UPDATE.
    ENDLOOP.

    SORT MT_T043T_UPDATE BY BUKRS RFPRO.

  ENDMETHOD.

* ---- YCL_FI_POSTING_LIMIT_BL=======CM009 ----
  METHOD GET_CONVERTED_AMOUNT.

    DATA LV_AMOUNT TYPE MAXBT_043T.
    DATA LV_INT TYPE INT4.

    LV_INT = IV_RFPRO.
    LV_AMOUNT = LV_INT * 1000.

    "Convert to USD
    CALL FUNCTION 'CONVERT_TO_FOREIGN_CURRENCY'
      EXPORTING
*       CLIENT           = SY-MANDT
        DATE             = SY-DATUM
        FOREIGN_CURRENCY = IV_WAERS
        LOCAL_AMOUNT     = LV_AMOUNT
        LOCAL_CURRENCY   = 'USD'
*       RATE             = 0
*       TYPE_OF_RATE     = 'M'
*       READ_TCURR       = 'X'
      IMPORTING
*       EXCHANGE_RATE    =
        FOREIGN_AMOUNT   = EV_AMOUNT
*       FOREIGN_FACTOR   =
*       LOCAL_FACTOR     =
*       EXCHANGE_RATEX   =
*       DERIVED_RATE_TYPE       =
*       FIXED_RATE       =
      EXCEPTIONS
        NO_RATE_FOUND    = 1
        OVERFLOW         = 2
        NO_FACTORS_FOUND = 3
        NO_SPREAD_FOUND  = 4
        DERIVED_2_TIMES  = 5
        OTHERS           = 6.

    IF SY-SUBRC <> 0.
      CLEAR EV_AMOUNT.
    ENDIF.

  ENDMETHOD.

* ---- YCL_FI_POSTING_LIMIT_BL=======CM00A ----
  METHOD UPDATE_T043.

    DATA LS_T043 TYPE T043.

    LOOP AT MT_T043_ACTION INTO DATA(LS_T043_ACTION).
      MOVE-CORRESPONDING LS_T043_ACTION TO LS_T043.
      CASE LS_T043_ACTION-ACTION.
        WHEN 'I'.
          INSERT T043 FROM LS_T043.
        WHEN 'U'.
          UPDATE T043 FROM LS_T043.
        WHEN 'D'.
          DELETE FROM T043 WHERE USNAM = LS_T043-USNAM.
      ENDCASE.
    ENDLOOP.

    IF IV_UPDATE = ABAP_TRUE.
      COMMIT WORK.
    ELSE.
      ROLLBACK WORK.
    ENDIF.

  ENDMETHOD.

* ---- YCL_FI_POSTING_LIMIT_BL=======CM00B ----
  METHOD DISPLAY_ALV_T043.

    MV_REPID = IV_REPID.

    "Init ALV
    ME->INIT_ALV( CHANGING CT_TABLE = MT_LIST_T043 ).

    ME->SET_COLUMNS_FOR_T043_LIST( ).

    "Display list
    MO_SALV_TABLE->DISPLAY( ).

  ENDMETHOD.

* ---- YCL_FI_POSTING_LIMIT_BL=======CM00C ----
  METHOD INIT_ALV.

    "Init ALV
    TRY.
        CALL METHOD CL_SALV_TABLE=>FACTORY
*      EXPORTING
*        list_display   = IF_SALV_C_BOOL_SAP=>FALSE
*        r_container    =
*        container_name =
          IMPORTING
            R_SALV_TABLE = MO_SALV_TABLE
          CHANGING
            T_TABLE      = CT_TABLE.
      CATCH CX_SALV_MSG .
    ENDTRY.

    MO_SALV_TABLE->SET_SCREEN_STATUS( PFSTATUS = 'SALV_TABLE_1'
                                  REPORT   = 'YCA_ALV_GUI_STATUS'
                                  SET_FUNCTIONS = MO_SALV_TABLE->C_FUNCTIONS_ALL ).

    "ALV layout
    DATA LS_LAYOUT_KEY TYPE SALV_S_LAYOUT_KEY.

    MO_LAYOUT = MO_SALV_TABLE->GET_LAYOUT( ).
    LS_LAYOUT_KEY-REPORT = MV_REPID.
    MO_LAYOUT->SET_KEY( LS_LAYOUT_KEY ).
    MO_LAYOUT->SET_SAVE_RESTRICTION( IF_SALV_C_LAYOUT=>RESTRICT_NONE ).


    "ALV display settings
    MO_DISPLAY_SETTINGS = MO_SALV_TABLE->GET_DISPLAY_SETTINGS( ).
    MO_DISPLAY_SETTINGS->SET_STRIPED_PATTERN( ABAP_TRUE ).

  ENDMETHOD.

* ---- YCL_FI_POSTING_LIMIT_BL=======CM00D ----
  METHOD SET_COLUMNS_FOR_T043_LIST.

    DATA LO_COLUMNS TYPE REF TO CL_SALV_COLUMNS_TABLE.
    DATA LO_COLUMN TYPE REF TO CL_SALV_COLUMN_TABLE.

    LO_COLUMNS = MO_SALV_TABLE->GET_COLUMNS( ).
    "Column width optimization
    LO_COLUMNS->SET_OPTIMIZE( ABAP_TRUE ).

    TRY.
        LO_COLUMN ?= LO_COLUMNS->GET_COLUMN( 'LIMIT' ).
        LO_COLUMN->SET_LONG_TEXT( 'Limit' ).
        LO_COLUMN->SET_MEDIUM_TEXT( 'Limit' ).
        LO_COLUMN->SET_FIXED_HEADER_TEXT( 'L' ).
      CATCH CX_SALV_NOT_FOUND.
    ENDTRY.

  ENDMETHOD.

* ---- YCL_FI_POSTING_LIMIT_BL=======CM00E ----
  METHOD DISPLAY_ALV_T043T.

    MV_REPID = IV_REPID.

    "Init ALV
    ME->INIT_ALV( CHANGING CT_TABLE = MT_T043T_UPDATE ).

    ME->SET_COLUMNS_FOR_T043T_LIST( ).

    "Display list
    MO_SALV_TABLE->DISPLAY( ).

  ENDMETHOD.

* ---- YCL_FI_POSTING_LIMIT_BL=======CM00F ----
  METHOD SET_COLUMNS_FOR_T043T_LIST.

    DATA LO_COLUMNS TYPE REF TO CL_SALV_COLUMNS_TABLE.
    DATA LO_COLUMN TYPE REF TO CL_SALV_COLUMN_TABLE.

    LO_COLUMNS = MO_SALV_TABLE->GET_COLUMNS( ).
    "Column width optimization
    LO_COLUMNS->SET_OPTIMIZE( ABAP_TRUE ).

    TRY.
        LO_COLUMN ?= LO_COLUMNS->GET_COLUMN( 'MAXBT_OLD' ).
        LO_COLUMN->SET_LONG_TEXT( 'Old Maximum Amount Posted per Document' ).
        LO_COLUMN->SET_FIXED_HEADER_TEXT( 'L' ).
      CATCH CX_SALV_NOT_FOUND.
    ENDTRY.

    TRY.
        LO_COLUMN ?= LO_COLUMNS->GET_COLUMN( 'MAXBT_NEW' ).
        LO_COLUMN->SET_LONG_TEXT( 'New Maximum Amount Posted per Document' ).
        LO_COLUMN->SET_FIXED_HEADER_TEXT( 'L' ).
      CATCH CX_SALV_NOT_FOUND.
    ENDTRY.

    TRY.
        LO_COLUMN ?= LO_COLUMNS->GET_COLUMN( 'MAXEB_OLD' ).
        LO_COLUMN->SET_LONG_TEXT( 'Old Maximum Posting Amount per Line Item' ).
        LO_COLUMN->SET_FIXED_HEADER_TEXT( 'L' ).
      CATCH CX_SALV_NOT_FOUND.
    ENDTRY.

    TRY.
        LO_COLUMN ?= LO_COLUMNS->GET_COLUMN( 'MAXEB_NEW' ).
        LO_COLUMN->SET_LONG_TEXT( 'New Maximum Posting Amount per Line Item' ).
        LO_COLUMN->SET_FIXED_HEADER_TEXT( 'L' ).
      CATCH CX_SALV_NOT_FOUND.
    ENDTRY.

  ENDMETHOD.

* ---- YCL_FI_POSTING_LIMIT_BL=======CM00G ----
  METHOD UPDATE_T043T.

    LOOP AT MT_T043T_UPDATE INTO DATA(LS_T043T_UPDATE).
      UPDATE T043T SET MAXBT = LS_T043T_UPDATE-MAXBT_NEW
                       MAXEB = LS_T043T_UPDATE-MAXEB_NEW
                   WHERE RFPRO = LS_T043T_UPDATE-RFPRO
                   AND   BUKRS = LS_T043T_UPDATE-BUKRS.
    ENDLOOP.

    IF IV_UPDATE = ABAP_TRUE.
      COMMIT WORK.
    ELSE.
      ROLLBACK WORK.
    ENDIF.

  ENDMETHOD.

* ---- YCL_FI_POSTING_LIMIT_BL=======CO ----
PROTECTED SECTION.

* ---- YCL_FI_POSTING_LIMIT_BL=======CU ----
CLASS YCL_FI_POSTING_LIMIT_BL DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

PUBLIC SECTION.

  METHODS DISPLAY_ALV_T043
    IMPORTING
      !IV_REPID TYPE SY-REPID .
  METHODS DISPLAY_ALV_T043T
    IMPORTING
      !IV_REPID TYPE SY-REPID .
  METHODS GET_AMOUNTS_TO_UPDATE .
  METHODS GET_CERTIFYING_OFF_WITH_LIMIT
    RAISING
      YCX_COMMUNICATION_CHECK .
  METHODS UPDATE_T043
    IMPORTING
      !IV_UPDATE TYPE XFELD DEFAULT ABAP_FALSE .
  METHODS UPDATE_T043T
    IMPORTING
      !IV_UPDATE TYPE XFELD DEFAULT ABAP_FALSE .