* ==== CLASS POOL YCL_FI_CASH_FORECAST_BL ====
CLASS-POOL .
*"* class pool for class YCL_FI_CASH_FORECAST_BL

*"* local type definitions
INCLUDE YCL_FI_CASH_FORECAST_BL=======CCDEF.

*"* class YCL_FI_CASH_FORECAST_BL definition
*"* public declarations
  INCLUDE YCL_FI_CASH_FORECAST_BL=======CU.
*"* protected declarations
  INCLUDE YCL_FI_CASH_FORECAST_BL=======CO.
*"* private declarations
  INCLUDE YCL_FI_CASH_FORECAST_BL=======CI.
ENDCLASS. "YCL_FI_CASH_FORECAST_BL definition

*"* macro definitions
INCLUDE YCL_FI_CASH_FORECAST_BL=======CCMAC.
*"* local class implementation
INCLUDE YCL_FI_CASH_FORECAST_BL=======CCIMP.

CLASS YCL_FI_CASH_FORECAST_BL IMPLEMENTATION.
*"* method's implementations
  INCLUDE METHODS.
ENDCLASS. "YCL_FI_CASH_FORECAST_BL implementation


* ---- YCL_FI_CASH_FORECAST_BL=======CI ----
PRIVATE SECTION.

  TYPES:
    BEGIN OF TY_GLT0,
      RLDNR TYPE GLT0-RLDNR,
      RRCTY TYPE GLT0-RRCTY,
      RVERS TYPE GLT0-RVERS,
      BUKRS TYPE GLT0-BUKRS,
      RYEAR TYPE GLT0-RYEAR,
      RACCT TYPE GLT0-RACCT,
      RBUSA TYPE GLT0-RBUSA,
      RTCUR TYPE GLT0-RTCUR,
      DRCRK TYPE GLT0-DRCRK,
      RPMAX TYPE GLT0-RPMAX,
      HSLVT TYPE GLT0-HSLVT,
      HSL01 TYPE GLT0-HSL01,
      HSL02 TYPE GLT0-HSL02,
      HSL03 TYPE GLT0-HSL03,
      HSL04 TYPE GLT0-HSL04,
      HSL05 TYPE GLT0-HSL05,
      HSL06 TYPE GLT0-HSL06,
      HSL07 TYPE GLT0-HSL07,
      HSL08 TYPE GLT0-HSL08,
      HSL09 TYPE GLT0-HSL09,
      HSL10 TYPE GLT0-HSL10,
      HSL11 TYPE GLT0-HSL11,
      HSL12 TYPE GLT0-HSL12,
      HSL13 TYPE GLT0-HSL13,
      HSL14 TYPE GLT0-HSL14,
      HSL15 TYPE GLT0-HSL15,
      HSL16 TYPE GLT0-HSL16,
    END OF TY_GLT0 .
  TYPES:
    BEGIN OF TY_FMIFI,
      FMBELNR TYPE V_FMIFI-FMBELNR,
      FIKRS   TYPE V_FMIFI-FIKRS,
      FMBUZEI TYPE V_FMIFI-FMBUZEI,
      BTART   TYPE V_FMIFI-BTART,
      RLDNR   TYPE V_FMIFI-RLDNR,
      GJAHR   TYPE V_FMIFI-GJAHR,
      STUNR   TYPE V_FMIFI-STUNR,
      FISTL   TYPE V_FMIFI-FISTL,
      FONDS   TYPE V_FMIFI-FONDS,
      FIPEX   TYPE V_FMIFI-FIPEX,
      PERIO   TYPE V_FMIFI-PERIO,
      FKBTR   TYPE V_FMIFI-FKBTR,
      WAERS   TYPE WAERS,
    END OF TY_FMIFI .
  TYPES:
    BEGIN OF TY_FUND,
      FIKRS   TYPE FMFINCODE-FIKRS,
      FINCODE TYPE FMFINCODE-FINCODE,
      TYPE    TYPE FMFINCODE-TYPE,
    END OF TY_FUND .
  TYPES:
    TTY_FUND TYPE SORTED TABLE OF TY_FUND WITH NON-UNIQUE KEY FIKRS FINCODE .
  TYPES:
    BEGIN OF TY_PERIOD,
      PERIO6 TYPE YE_PERIOD,
      GJAHR  TYPE GJAHR,
      PERIO3 TYPE CO_PERIO,
      PERIO2 TYPE FMFG_FISCAL_PERIOD,
      BEGDA  TYPE BEGDA,
      ENDDA  TYPE ENDDA,
      LOCKED TYPE BOOLEAN,
      MESSG  TYPE TEXT80,
    END OF TY_PERIOD .
  TYPES:
    BEGIN OF TY_RESULT.
      INCLUDE TYPE YSFI_CASH_FORECAST.
      TYPES: COLFIELD TYPE LVC_T_SCOL,
      CELLTAB  TYPE LVC_T_STYL,
    END OF TY_RESULT .
  TYPES:
    TTY_RESULT TYPE TABLE OF TY_RESULT .
  TYPES:
    BEGIN OF TY_BSXX,
      BUKRS TYPE BSIS-BUKRS,
      HKONT TYPE BSIS-HKONT,
      AUGDT TYPE BSIS-AUGDT,
      AUGBL TYPE BSIS-AUGBL,
      ZUONR TYPE BSIS-ZUONR,
      GJAHR TYPE BSIS-GJAHR,
      BELNR TYPE BSIS-BELNR,
      BUZEI TYPE BSIS-BUZEI,
      BUDAT TYPE BSIS-BUDAT,
      BLART TYPE BSIS-BLART,
      SHKZG TYPE BSIS-SHKZG,
      GSBER TYPE BSIS-GSBER,
      SGTXT TYPE BSIS-SGTXT,
      DMBTR TYPE BSIS-DMBTR,
      WAERS TYPE T001-WAERS,
    END OF TY_BSXX .

  DATA:
    MR_BLART2 TYPE RANGE OF BLART .
  DATA:
    MR_GSBER2 TYPE RANGE OF GSBER .
  DATA:
    MR_SAKNR2 TYPE RANGE OF HKONT .
  DATA:
    MR_SGTXT2 TYPE RANGE OF SGTXT .
  DATA MV_DATA_CHANGED TYPE BOOLEAN .
  DATA MV_WAERS TYPE WAERS .
  DATA MT_EXCLUDE_FCT TYPE UI_FUNCTIONS .
  DATA MT_FIELDCAT TYPE LVC_T_FCAT .
  DATA:
    MT_PERIOD TYPE TABLE OF TY_PERIOD .
  DATA MT_FUND TYPE TTY_FUND .
  DATA:
    MT_FMIFI TYPE TABLE OF TY_FMIFI .
  DATA MV_BEGDA TYPE BEGDA .
  DATA MV_ENDDA TYPE ENDDA .
  DATA MV_FIKRS TYPE FIKRS .
  DATA:
    MT_GLT0 TYPE TABLE OF TY_GLT0 .
  DATA MP_BUKRS TYPE BUKRS .
  DATA:
    MR_FYEAR TYPE RANGE OF GJAHR .
  DATA:
    MR_GSBER1 TYPE RANGE OF GSBER .
  DATA:
    MR_SAKNR1 TYPE RANGE OF SAKNR .
  DATA:
    MR_FUND1 TYPE RANGE OF BP_GEBER .
  DATA:
    MR_TYPE1 TYPE RANGE OF FM_FUNDTYPE .
  DATA:
    MR_FUND2 TYPE RANGE OF BP_GEBER .
  DATA:
    MR_TYPE2 TYPE RANGE OF FM_FUNDTYPE .
  DATA:
    MR_FUND3 TYPE RANGE OF BP_GEBER .
  DATA:
    MR_TYPE3 TYPE RANGE OF FM_FUNDTYPE .
  DATA:
    MR_FUND4 TYPE RANGE OF BP_GEBER .
  DATA:
    MR_TYPE4 TYPE RANGE OF FM_FUNDTYPE .
  DATA:
    MR_FUND5 TYPE RANGE OF BP_GEBER .
  DATA:
    MR_TYPE5 TYPE RANGE OF FM_FUNDTYPE .
  DATA:
    MR_GSBER3 TYPE RANGE OF GSBER .
  DATA:
    MR_SAKNR3 TYPE RANGE OF SAKNR .
  DATA:
    MT_RESULT TYPE TABLE OF TY_RESULT .
  DATA:
    MT_CASH_FOR TYPE SORTED TABLE OF YTFI_CASH_FOR WITH UNIQUE KEY BUKRS PERIOD .
  DATA:
    MT_BSIS TYPE TABLE OF TY_BSXX .
  DATA:
    MT_BSAS TYPE TABLE OF TY_BSXX .
  DATA:
    MT_GLT0_WCF TYPE TABLE OF TY_GLT0 .

  METHODS GET_INTERFUND_TRANSFER
    IMPORTING
      !IV_BEGDA TYPE BEGDA
      !IV_ENDDA TYPE ENDDA
    EXPORTING
      !EV_IFUTR TYPE YE_FI_INTERFUND_TRANSFER .
  METHODS LOCK_CASH_FORECAST
    IMPORTING
      !IV_BUKRS TYPE BUKRS
      !IV_PERIOD TYPE YE_PERIOD
    EXPORTING
      !EV_LOCKED TYPE BOOLEAN
      !EV_MESSAGE TYPE TEXT80 .
  METHODS UNLOCK_CASH_FORECAST
    IMPORTING
      !IV_BUKRS TYPE BUKRS
      !IV_PERIOD TYPE YE_PERIOD .
  METHODS CLEAR_DATA_CHANGED .
  METHODS HANDLE_DATA_CHANGED
    FOR EVENT DATA_CHANGED OF CL_GUI_ALV_GRID
    IMPORTING
      !ER_DATA_CHANGED .
  METHODS CALCULATE_AMOUNTS
    CHANGING
      !CS_RESULT TYPE TY_RESULT .
  METHODS EXCLUDE_ALV_FUNCTIONS
    IMPORTING
      !IV_FUNCTION TYPE UI_FUNC .
  METHODS READ_EXPENDITURE_AMOUNTS
    IMPORTING
      !IV_FYEAR TYPE GJAHR
      !IV_PERIO TYPE CO_PERIO
    CHANGING
      !CV_EXPAB TYPE YE_FI_EXP_APPROVED_BUDGET
      !CV_EXPUL TYPE YE_FI_EXP_ULO
      !CV_EXPRU TYPE YE_FI_EXP_REMAINING_UNSPENT
      !CV_EXPAC_LAST TYPE YE_FI_EXP_AC_LAST
      !CV_EXPAC_CURR TYPE YE_FI_EXP_AC_CURRENT .
  METHODS READ_BALANCE_AMOUNTS
    IMPORTING
      !IV_FYEAR TYPE GJAHR
      !IV_PERIO TYPE FMFG_FISCAL_PERIOD
    EXPORTING
      !EV_OPEBA TYPE YE_FI_OPENING_BALANCE
      !EV_CLOBA TYPE YE_FI_CLOSING_CASH_BAL .
  METHODS READ_WORKING_CAPITAL_FUND
    IMPORTING
      !IV_FYEAR TYPE GJAHR
      !IV_PERIO TYPE FMFG_FISCAL_PERIOD
    EXPORTING
      !EV_WORKCAP TYPE YE_FI_WORKING_CAPITAL_FUND .
  METHODS PREPARE_DATA .
  METHODS GET_FUNDS
    IMPORTING
      !IR_FUND LIKE MR_FUND1
      !IR_TYPE LIKE MR_TYPE1
    RETURNING
      VALUE(RT_FUND) TYPE TTY_FUND .
  METHODS INITIALIZE_DATA .
  METHODS READ_DATA_FROM_DB .

* ---- YCL_FI_CASH_FORECAST_BL=======CM001 ----
  METHOD SET_SELECTION_VALUES.

    FIELD-SYMBOLS <LT_RANGE> TYPE ANY TABLE.
    FIELD-SYMBOLS <LV_PARAM> TYPE ANY.
    DATA LV_SELNAME TYPE FIELDNAME.

    LV_SELNAME = IV_SELNAME.
    CASE IV_KIND.
      WHEN 'S'.   "SELECT-OPTIONS
        REPLACE 'S_' IN LV_SELNAME WITH 'MR_'.
        ASSIGN (LV_SELNAME) TO <LT_RANGE>.
        CHECK <LT_RANGE> IS ASSIGNED.
        <LT_RANGE> = IT_VALUE.
      WHEN 'P'. "PARAMETERS
        REPLACE 'P_' IN LV_SELNAME WITH 'MP_'.
        ASSIGN (LV_SELNAME) TO <LV_PARAM>.
        CHECK <LV_PARAM> IS ASSIGNED.
        <LV_PARAM> = IV_VALUE.
    ENDCASE.

  ENDMETHOD.

* ---- YCL_FI_CASH_FORECAST_BL=======CM002 ----
  METHOD GET_DATA.

    ME->INITIALIZE_DATA( ).
    ME->READ_DATA_FROM_DB( ).
    ME->PREPARE_DATA( ).

  ENDMETHOD.

* ---- YCL_FI_CASH_FORECAST_BL=======CM003 ----
  METHOD READ_DATA_FROM_DB.

    DATA LT_FUND TYPE TTY_FUND.
    DATA LV_NUM(1) TYPE N.
    DATA LV_NAME TYPE FIELDNAME.
    FIELD-SYMBOLS <MR_FUND> TYPE ANY.
    FIELD-SYMBOLS <MR_TYPE> TYPE ANY.

    "Get funds
    DO 5 TIMES.
      ADD 1 TO LV_NUM.
      LV_NAME = |MR_FUND{ LV_NUM }|.
      ASSIGN (LV_NAME) TO <MR_FUND>.
      LV_NAME = |MR_TYPE{ LV_NUM }|.
      ASSIGN (LV_NAME) TO <MR_TYPE>.
      LT_FUND = ME->GET_FUNDS( IR_FUND = <MR_FUND>
                               IR_TYPE = <MR_TYPE> ).
      INSERT LINES OF LT_FUND INTO TABLE MT_FUND.
      CLEAR LT_FUND.
    ENDDO.

    DELETE ADJACENT DUPLICATES FROM MT_FUND.

    "Get data from GLT0 table for balance
    SELECT RLDNR,
           RRCTY,
           RVERS,
           BUKRS,
           RYEAR,
           RACCT,
           RBUSA,
           RTCUR,
           DRCRK,
           RPMAX,
           HSLVT,
           HSL01,
           HSL02,
           HSL03,
           HSL04,
           HSL05,
           HSL06,
           HSL07,
           HSL08,
           HSL09,
           HSL10,
           HSL11,
           HSL12,
           HSL13,
           HSL14,
           HSL15,
           HSL16
      FROM GLT0
      WHERE BUKRS = @MP_BUKRS
      AND   RBUSA IN @MR_GSBER1
      AND   RYEAR IN @MR_FYEAR
      AND   RACCT IN @MR_SAKNR1
      INTO TABLE @MT_GLT0.

    "Get data from GLT0 table for working capital fund
    SELECT RLDNR,
           RRCTY,
           RVERS,
           BUKRS,
           RYEAR,
           RACCT,
           RBUSA,
           RTCUR,
           DRCRK,
           RPMAX,
           HSLVT,
           HSL01,
           HSL02,
           HSL03,
           HSL04,
           HSL05,
           HSL06,
           HSL07,
           HSL08,
           HSL09,
           HSL10,
           HSL11,
           HSL12,
           HSL13,
           HSL14,
           HSL15,
           HSL16
      FROM GLT0
      WHERE BUKRS = @MP_BUKRS
      AND   RBUSA IN @MR_GSBER3
      AND   RYEAR IN @MR_FYEAR
      AND   RACCT IN @MR_SAKNR3
      INTO TABLE @MT_GLT0_WCF.

    "Get data from V_FMIFI
    SELECT A~FMBELNR,
           A~FIKRS,
           A~FMBUZEI,
           A~BTART,
           A~RLDNR,
           A~GJAHR,
           A~STUNR,
           A~FISTL,
           A~FONDS,
           A~FIPEX,
           A~PERIO,
           A~FKBTR,
           B~WAERS
      FROM V_FMIFI AS A
      LEFT OUTER JOIN FM01 AS B ON B~FIKRS = A~FIKRS
      FOR ALL ENTRIES IN @MT_FUND
      WHERE A~FIKRS = @MV_FIKRS
      AND   A~FONDS = @MT_FUND-FINCODE
      AND   A~GJAHR IN @MR_FYEAR
      INTO TABLE @MT_FMIFI.

    "Get data from BSIS
    SELECT A~BUKRS,
           A~HKONT,
           A~AUGDT,
           A~AUGBL,
           A~ZUONR,
           A~GJAHR,
           A~BELNR,
           A~BUZEI,
           A~BUDAT,
           A~BLART,
           A~SHKZG,
           A~GSBER,
           A~SGTXT,
           A~DMBTR,
           B~WAERS
           FROM BSIS AS A
           LEFT OUTER JOIN T001 AS B ON B~BUKRS = A~BUKRS
           WHERE A~BUKRS = @MP_BUKRS
           AND   A~HKONT IN @MR_SAKNR2
           AND   A~BLART IN @MR_BLART2
           AND   A~BUDAT BETWEEN @MV_BEGDA AND @MV_ENDDA
           AND   A~GSBER IN @MR_GSBER2
           AND   A~SGTXT IN @MR_SGTXT2
           INTO TABLE @MT_BSIS.

    "Get data from BSAS
    SELECT A~BUKRS,
           A~HKONT,
           A~AUGDT,
           A~AUGBL,
           A~ZUONR,
           A~GJAHR,
           A~BELNR,
           A~BUZEI,
           A~BUDAT,
           A~BLART,
           A~SHKZG,
           A~GSBER,
           A~SGTXT,
           A~DMBTR,
           B~WAERS
           FROM BSAS AS A
           LEFT OUTER JOIN T001 AS B ON B~BUKRS = A~BUKRS
           WHERE A~BUKRS = @MP_BUKRS
           AND   A~HKONT IN @MR_SAKNR2
           AND   A~BLART IN @MR_BLART2
           AND   A~BUDAT BETWEEN @MV_BEGDA AND @MV_ENDDA
           AND   A~GSBER IN @MR_GSBER2
           AND   A~SGTXT IN @MR_SGTXT2
           INTO TABLE @MT_BSAS.

    "Get manual amounts from YTFI_CASH_FOR
    SELECT * FROM YTFI_CASH_FOR WHERE BUKRS = @MP_BUKRS
                                AND   PERIOD >= @MV_BEGDA(6)
                                AND   PERIOD <= @MV_ENDDA(6)
             INTO TABLE @MT_CASH_FOR.

  ENDMETHOD.

* ---- YCL_FI_CASH_FORECAST_BL=======CM004 ----
  METHOD INITIALIZE_DATA.

    DATA LV_PERIO6 TYPE TY_PERIOD-PERIO6.
    DATA LS_PERIOD TYPE TY_PERIOD.

    READ TABLE MR_FYEAR INTO DATA(LS_FYEAR) INDEX 1.
    IF SY-SUBRC = 0.
      MV_BEGDA = |{ LS_FYEAR-LOW }0101|.
      MV_ENDDA = |{ LS_FYEAR-HIGH }1231|.
    ENDIF.

    "Get FM area
    SELECT SINGLE FIKRS INTO MV_FIKRS FROM T001 WHERE BUKRS = MP_BUKRS.
    "Get currency from fM area
    SELECT SINGLE WAERS INTO MV_WAERS FROM FM01 WHERE FIKRS = MV_FIKRS.

    "initialize period
    LV_PERIO6 = MV_BEGDA(6).
    DO.
      LS_PERIOD-PERIO6 = LV_PERIO6.
      LS_PERIOD-GJAHR = LV_PERIO6(4).
      LS_PERIOD-PERIO3 = |0{ LV_PERIO6+4(2) }|.
      LS_PERIOD-PERIO2 = LV_PERIO6+4(2).
      LS_PERIOD-BEGDA = |{ LV_PERIO6 }01|.:
      CALL FUNCTION 'RP_LAST_DAY_OF_MONTHS'
        EXPORTING
          DAY_IN            = LS_PERIOD-BEGDA
        IMPORTING
          LAST_DAY_OF_MONTH = LS_PERIOD-ENDDA
        EXCEPTIONS
          DAY_IN_NO_DATE    = 1
          OTHERS            = 2.
      APPEND LS_PERIOD TO MT_PERIOD.
      IF LV_PERIO6 = MV_ENDDA(6).
        EXIT.
      ENDIF.
      IF LV_PERIO6+4(2) = '12'.
        ADD 89 TO LV_PERIO6.
      ELSE.
        ADD 1 TO LV_PERIO6.
      ENDIF.
    ENDDO.

    SORT MT_PERIOD.

    "Lock periods for table YTFI_CASH_FOR
    LOOP AT MT_PERIOD ASSIGNING FIELD-SYMBOL(<LS_PERIOD>).
      ME->LOCK_CASH_FORECAST( EXPORTING IV_BUKRS = MP_BUKRS
                                        IV_PERIOD = <LS_PERIOD>-PERIO6
                              IMPORTING EV_LOCKED = <LS_PERIOD>-LOCKED
                                        EV_MESSAGE = <LS_PERIOD>-MESSG ).
    ENDLOOP.

  ENDMETHOD.

* ---- YCL_FI_CASH_FORECAST_BL=======CM005 ----
  METHOD GET_FUNDS.

    SELECT FIKRS, FINCODE, TYPE FROM FMFINCODE
               WHERE FIKRS = @MV_FIKRS
               AND   FINCODE IN @IR_FUND
               AND   TYPE IN @IR_TYPE
               AND   DATAB <= @MV_ENDDA
               AND   DATBIS >= @MV_BEGDA
             INTO TABLE @RT_FUND.

  ENDMETHOD.

* ---- YCL_FI_CASH_FORECAST_BL=======CM006 ----
  METHOD PREPARE_DATA.

    DATA LS_RESULT TYPE TY_RESULT.
    DATA LS_COLOR TYPE LVC_S_SCOL.
    DATA LV_INT TYPE LVC_S_SCOL-COLOR-INT.
    DATA LS_CELLTAB TYPE LVC_S_STYL.

    LV_INT = 1.

    LOOP AT MT_PERIOD INTO DATA(LS_PERIOD).
      IF LS_PERIOD-PERIO2 = 1.
        CLEAR LS_RESULT.
      ENDIF.
      LS_RESULT-PERIOD = LS_PERIOD-PERIO6.
      LS_RESULT-WAERS = MV_WAERS.
      "Get data from GLT0for balance amounts
      ME->READ_BALANCE_AMOUNTS( EXPORTING IV_FYEAR = LS_PERIOD-GJAHR
                                          IV_PERIO = LS_PERIOD-PERIO2
                                IMPORTING EV_OPEBA = LS_RESULT-OPEBA
                                          EV_CLOBA = LS_RESULT-CLOBA ).
      "Get data from V_FMIFI
      ME->READ_EXPENDITURE_AMOUNTS( EXPORTING IV_FYEAR = LS_PERIOD-GJAHR
                                              IV_PERIO = LS_PERIOD-PERIO3
                                    CHANGING  CV_EXPAB = LS_RESULT-EXPAB
                                              CV_EXPUL = LS_RESULT-EXPUL
                                              CV_EXPRU = LS_RESULT-EXPRU
                                              CV_EXPAC_LAST = LS_RESULT-EXPAC_LAST
                                              CV_EXPAC_CURR = LS_RESULT-EXPAC_CURR ).
      "Get data from BSIS / BSAS
      ME->GET_INTERFUND_TRANSFER( EXPORTING IV_BEGDA = LS_PERIOD-BEGDA
                                            IV_ENDDA = LS_PERIOD-ENDDA
                                  IMPORTING EV_IFUTR = LS_RESULT-IFUTR ).
      "Get data from GLT0 for working capital fund
      ME->READ_WORKING_CAPITAL_FUND( EXPORTING IV_FYEAR = LS_PERIOD-GJAHR
                                               IV_PERIO = LS_PERIOD-PERIO2
                                     IMPORTING EV_WORKCAP = LS_RESULT-WORKCAP ).
      "Get data from YTFI_CASH_FOR
      READ TABLE MT_CASH_FOR INTO DATA(LS_CASH_FOR) WITH KEY BUKRS = MP_BUKRS
                                                             PERIOD = LS_PERIOD-PERIO6.
      IF SY-SUBRC = 0.
        MOVE-CORRESPONDING LS_CASH_FOR TO LS_RESULT.
      ENDIF.
      "Calculate amounts
      ME->CALCULATE_AMOUNTS( CHANGING CS_RESULT = LS_RESULT ).

      "Manage ALV editable field regarding locked entries
      CLEAR LS_RESULT-CELLTAB.
      IF LS_PERIOD-LOCKED = ABAP_FALSE.
        LS_RESULT-MESSG = LS_PERIOD-MESSG.
        LS_CELLTAB-FIELDNAME = 'ASSCO'.
        LS_CELLTAB-STYLE = CL_GUI_ALV_GRID=>MC_STYLE_DISABLED.
        INSERT LS_CELLTAB INTO TABLE LS_RESULT-CELLTAB.
        LS_CELLTAB-FIELDNAME = 'RECAR'.
        LS_CELLTAB-STYLE = CL_GUI_ALV_GRID=>MC_STYLE_DISABLED.
        INSERT LS_CELLTAB INTO TABLE LS_RESULT-CELLTAB.
        LS_CELLTAB-FIELDNAME = 'RECPP'.
        LS_CELLTAB-STYLE = CL_GUI_ALV_GRID=>MC_STYLE_DISABLED.
        INSERT LS_CELLTAB INTO TABLE LS_RESULT-CELLTAB.
        LS_CELLTAB-FIELDNAME = 'CONFO'.
        LS_CELLTAB-STYLE = CL_GUI_ALV_GRID=>MC_STYLE_DISABLED.
        INSERT LS_CELLTAB INTO TABLE LS_RESULT-CELLTAB.
      ENDIF.

      "Manage ALV colors
      CLEAR LS_RESULT-COLFIELD.
      "Set color for key
      LS_COLOR-FNAME = 'PERIOD'.
      LS_COLOR-COLOR-COL = COL_KEY.
      LS_COLOR-COLOR-INT = 1.
      APPEND LS_COLOR TO LS_RESULT-COLFIELD.
      "Set color main column
      IF LV_INT = 1.
        LV_INT = 0.
      ELSE.
        LV_INT = 1.
      ENDIF.
      LS_COLOR-FNAME = 'CASHIN'.
      LS_COLOR-COLOR-COL = COL_GROUP.
      LS_COLOR-COLOR-INT = LV_INT.
      APPEND LS_COLOR TO LS_RESULT-COLFIELD.
      LS_COLOR-FNAME = 'CASHOUT'.
      APPEND LS_COLOR TO LS_RESULT-COLFIELD.
      LS_COLOR-FNAME = 'NETBAL'.
      APPEND LS_COLOR TO LS_RESULT-COLFIELD.
      LS_COLOR-FNAME = 'WORKCAP'.
      APPEND LS_COLOR TO LS_RESULT-COLFIELD.
      "set to result table
      APPEND LS_RESULT TO MT_RESULT.
    ENDLOOP.

  ENDMETHOD.

* ---- YCL_FI_CASH_FORECAST_BL=======CM007 ----
  METHOD READ_BALANCE_AMOUNTS.

    DATA LV_PERIO TYPE FMFG_FISCAL_PERIOD.
    DATA LV_FIELDNAME TYPE FIELDNAME.
    DATA LV_OPEBA TYPE YE_FI_OPENING_BALANCE.
    DATA LV_CLOBA TYPE YE_FI_CLOSING_CASH_BAL.
    FIELD-SYMBOLS <HSL> TYPE ANY.

    CLEAR: EV_OPEBA, EV_CLOBA.

    LOOP AT MT_GLT0 INTO DATA(LS_GLT0) WHERE RYEAR = IV_FYEAR.
      CLEAR: LV_OPEBA, LV_CLOBA, LV_PERIO.
      LV_OPEBA = LS_GLT0-HSLVT.
      DO 12 TIMES.
        ADD 1 TO LV_PERIO.
        LV_FIELDNAME = |LS_GLT0-HSL{ LV_PERIO }|.
        ASSIGN (LV_FIELDNAME) TO <HSL>.
        CHECK <HSL> IS ASSIGNED.
        IF LV_PERIO < IV_PERIO.
          ADD <HSL> TO LV_OPEBA.
        ELSE.
          LV_CLOBA = LV_OPEBA.
          ADD <HSL> TO LV_CLOBA.
          IF IV_PERIO = 12.
            ADD LS_GLT0-HSL13 TO LV_CLOBA.
            ADD LS_GLT0-HSL14 TO LV_CLOBA.
            ADD LS_GLT0-HSL15 TO LV_CLOBA.
            ADD LS_GLT0-HSL16 TO LV_CLOBA.
          ENDIF.
          EXIT.
        ENDIF.
      ENDDO.
      ADD LV_OPEBA TO EV_OPEBA.
      ADD LV_CLOBA TO EV_CLOBA.
    ENDLOOP.

  ENDMETHOD.

* ---- YCL_FI_CASH_FORECAST_BL=======CM008 ----
  METHOD READ_EXPENDITURE_AMOUNTS.

    DATA LS_FUND TYPE TY_FUND.

    LOOP AT MT_FMIFI INTO DATA(LS_FMIFI) WHERE GJAHR = IV_FYEAR
                                         AND   PERIO = IV_PERIO.
      "get fund
      READ TABLE MT_FUND INTO LS_FUND WITH KEY FIKRS = LS_FMIFI-FIKRS
                                               FINCODE = LS_FMIFI-FONDS.
      CHECK SY-SUBRC = 0.
      MULTIPLY LS_FMIFI-FKBTR BY -1.
      "Add to expenditure for approved budget
      IF LS_FUND-FINCODE IN MR_FUND1 AND LS_FUND-TYPE IN MR_TYPE1.
        ADD LS_FMIFI-FKBTR TO CV_EXPAB.
      ENDIF.
      "Add to expenditure from ULO
      IF LS_FUND-FINCODE IN MR_FUND2 AND LS_FUND-TYPE IN MR_TYPE2.
        ADD LS_FMIFI-FKBTR TO CV_EXPUL.
      ENDIF.
      "Add to expenditure from remaining unspent budget
      IF LS_FUND-FINCODE IN MR_FUND3 AND LS_FUND-TYPE IN MR_TYPE3.
        ADD LS_FMIFI-FKBTR TO CV_EXPRU.
      ENDIF.
      "Add to expenditure from AC received last biennium
      IF LS_FUND-FINCODE IN MR_FUND4 AND LS_FUND-TYPE IN MR_TYPE4.
        ADD LS_FMIFI-FKBTR TO CV_EXPAC_LAST.
      ENDIF.
      "Add to expenditure from AC received current biennium
      IF LS_FUND-FINCODE IN MR_FUND5 AND LS_FUND-TYPE IN MR_TYPE5.
        ADD LS_FMIFI-FKBTR TO CV_EXPAC_CURR.
      ENDIF.
    ENDLOOP.

  ENDMETHOD.

* ---- YCL_FI_CASH_FORECAST_BL=======CM009 ----
  METHOD CALCULATE_AMOUNTS.

    "Cumulative cashflow in
    CS_RESULT-CASHIN = CS_RESULT-OPEBA + CS_RESULT-ASSCO.
    "Cumulative cashflow out
    CS_RESULT-CASHOUT = CS_RESULT-RECAR + CS_RESULT-RECPP + CS_RESULT-IFUTR
                      - CS_RESULT-EXPAB - CS_RESULT-EXPUL - CS_RESULT-EXPRU
                      - CS_RESULT-EXPAC_LAST - CS_RESULT-EXPAC_CURR.
    "Net balance
    CS_RESULT-NETBAL = CS_RESULT-CLOBA + CS_RESULT-CONFO.

  ENDMETHOD.

* ---- YCL_FI_CASH_FORECAST_BL=======CM00A ----
  METHOD DISPLAY_ALV.

    DATA LS_LAYOUT TYPE LVC_S_LAYO.

    CALL FUNCTION 'LVC_FIELDCATALOG_MERGE'
      EXPORTING
*       I_BUFFER_ACTIVE        =
        I_STRUCTURE_NAME       = 'YSFI_CASH_FORECAST'
*       I_CLIENT_NEVER_DISPLAY = 'X'
        I_BYPASSING_BUFFER     = ABAP_TRUE
*       I_INTERNAL_TABNAME     =
      CHANGING
        CT_FIELDCAT            = MT_FIELDCAT
      EXCEPTIONS
        INCONSISTENT_INTERFACE = 1
        PROGRAM_ERROR          = 2
        OTHERS                 = 3.
    CHECK SY-SUBRC = 0.

    LOOP AT MT_FIELDCAT ASSIGNING FIELD-SYMBOL(<FIELDCAT>).
      CASE <FIELDCAT>-FIELDNAME.
        WHEN 'ASSCO' OR 'RECAR' OR 'RECPP' OR 'CONFO'.
          <FIELDCAT>-EDIT = ABAP_TRUE.
        WHEN 'PERIOD'.
          <FIELDCAT>-KEY = ABAP_TRUE.
      ENDCASE.
    ENDLOOP.

    "Exclude interactive functions
    ME->EXCLUDE_ALV_FUNCTIONS( CL_GUI_ALV_GRID=>MC_FC_LOC_CUT ).
    ME->EXCLUDE_ALV_FUNCTIONS( CL_GUI_ALV_GRID=>MC_FC_LOC_COPY_ROW ).
    ME->EXCLUDE_ALV_FUNCTIONS( CL_GUI_ALV_GRID=>MC_FC_LOC_PASTE ).
    ME->EXCLUDE_ALV_FUNCTIONS( CL_GUI_ALV_GRID=>MC_FC_LOC_INSERT_ROW ).
    ME->EXCLUDE_ALV_FUNCTIONS( CL_GUI_ALV_GRID=>MC_FC_LOC_DELETE_ROW ).
    ME->EXCLUDE_ALV_FUNCTIONS( CL_GUI_ALV_GRID=>MC_FC_LOC_APPEND_ROW ).
    ME->EXCLUDE_ALV_FUNCTIONS( CL_GUI_ALV_GRID=>MC_FC_LOC_COPY ).
    ME->EXCLUDE_ALV_FUNCTIONS( CL_GUI_ALV_GRID=>MC_FC_LOC_PASTE_NEW_ROW ).
    ME->EXCLUDE_ALV_FUNCTIONS( CL_GUI_ALV_GRID=>MC_FC_INFO ).
    ME->EXCLUDE_ALV_FUNCTIONS( CL_GUI_ALV_GRID=>MC_FC_VIEWS ).
    ME->EXCLUDE_ALV_FUNCTIONS( CL_GUI_ALV_GRID=>MC_FC_GRAPH ).

    LS_LAYOUT-ZEBRA = ABAP_TRUE.
    LS_LAYOUT-CTAB_FNAME =  'COLFIELD'.   "to define cell color
    LS_LAYOUT-STYLEFNAME = 'CELLTAB'.     "to define cell style


    MO_GRID->SET_TABLE_FOR_FIRST_DISPLAY( EXPORTING IT_TOOLBAR_EXCLUDING = MT_EXCLUDE_FCT
                                                    IS_LAYOUT = LS_LAYOUT
                                          CHANGING IT_FIELDCATALOG = MT_FIELDCAT
                                                   IT_OUTTAB = MT_RESULT ).

    MO_GRID->SET_READY_FOR_INPUT( EXPORTING I_READY_FOR_INPUT = 1 ).

    "Handle enter event
    MO_GRID->REGISTER_EDIT_EVENT( EXPORTING I_EVENT_ID = CL_GUI_ALV_GRID=>MC_EVT_ENTER ).
    SET HANDLER ME->HANDLE_DATA_CHANGED FOR MO_GRID.

  ENDMETHOD.

* ---- YCL_FI_CASH_FORECAST_BL=======CM00B ----
  METHOD EXCLUDE_ALV_FUNCTIONS.

    APPEND IV_FUNCTION TO MT_EXCLUDE_FCT.

  ENDMETHOD.

* ---- YCL_FI_CASH_FORECAST_BL=======CM00C ----
  METHOD HANDLE_DATA_CHANGED.

    DATA LTY_RESULT TYPE TABLE OF TY_RESULT.
    DATA LS_STABLE TYPE LVC_S_STBL.
    FIELD-SYMBOLS <LT_RESULT_MODIFIED> TYPE TTY_RESULT.

    ASSIGN ER_DATA_CHANGED->MP_MOD_ROWS->* TO <LT_RESULT_MODIFIED>.

    CHECK <LT_RESULT_MODIFIED> IS NOT INITIAL.

    LOOP AT <LT_RESULT_MODIFIED> INTO DATA(LS_RESULT_MODIFIED).
      READ TABLE MT_RESULT ASSIGNING FIELD-SYMBOL(<LS_RESULT>) WITH KEY PERIOD = LS_RESULT_MODIFIED-PERIOD.
      CHECK SY-SUBRC = 0.
      ME->CALCULATE_AMOUNTS( CHANGING CS_RESULT = LS_RESULT_MODIFIED ).
      <LS_RESULT> = LS_RESULT_MODIFIED.
    ENDLOOP.

    "Set flag data changed
    MV_DATA_CHANGED = ABAP_TRUE.

    "Refresh table
    LS_STABLE-COL = ABAP_TRUE.
    LS_STABLE-ROW = ABAP_TRUE.
    MO_GRID->REFRESH_TABLE_DISPLAY( IS_STABLE = LS_STABLE ).

  ENDMETHOD.

* ---- YCL_FI_CASH_FORECAST_BL=======CM00D ----
  METHOD SAVE_DATA.

    DATA LS_CASH_FOR TYPE YTFI_CASH_FOR.
    DATA LS_CASH_FOR_RES TYPE YTFI_CASH_FOR.

    IF ME->CHECK_DATA_CHANGED( ) = ABAP_TRUE.
      LOOP AT MT_RESULT INTO DATA(LS_RESULT).
        MOVE-CORRESPONDING LS_RESULT TO LS_CASH_FOR_RES.
        LS_CASH_FOR_RES-BUKRS = MP_BUKRS.
        LS_CASH_FOR_RES-MANDT = SY-MANDT.
        SELECT SINGLE * INTO LS_CASH_FOR FROM YTFI_CASH_FOR WHERE PERIOD = LS_RESULT-PERIOD.
        IF SY-SUBRC = 0.
          CLEAR: LS_CASH_FOR-UDATE, LS_CASH_FOR-UNAME,
                 LS_CASH_FOR_RES-UDATE, LS_CASH_FOR_RES-UNAME.
          IF LS_CASH_FOR <> LS_CASH_FOR_RES.
            LS_CASH_FOR_RES-UDATE = SY-DATUM.
            LS_CASH_FOR_RES-UNAME = SY-UNAME.
            UPDATE YTFI_CASH_FOR FROM LS_CASH_FOR_RES.
          ENDIF.
        ELSE.
          LS_CASH_FOR_RES-UDATE = SY-DATUM.
          LS_CASH_FOR_RES-UNAME = SY-UNAME.
          INSERT YTFI_CASH_FOR FROM LS_CASH_FOR_RES.
        ENDIF.
      ENDLOOP.
      MESSAGE TEXT-U01 TYPE 'S'.
      ME->CLEAR_DATA_CHANGED( ).
    ELSE.
      MESSAGE TEXT-U02 TYPE 'S'.
    ENDIF.

  ENDMETHOD.

* ---- YCL_FI_CASH_FORECAST_BL=======CM00E ----
  METHOD CHECK_DATA_CHANGED.

    DATA LV_ANSWER TYPE CHAR1.
    DATA LV_VALID TYPE BOOLEAN.

    "Check if data changed (in case of click on save without enter)
    MO_GRID->CHECK_CHANGED_DATA( IMPORTING E_VALID = LV_VALID ).

    IF IV_SET_POPUP = ABAP_TRUE.
      IF MV_DATA_CHANGED = ABAP_FALSE.
        EXIT.
      ELSE.
        LV_ANSWER = YCL_CA_UTILITIES=>POPUP_TO_CONFIRM( IV_TITLE = 'Data has been modified'
                                                        IV_TEXT = 'Do you want to leave without saving ?' ).
        CASE LV_ANSWER.
          WHEN '1'.  "Yes
            RV_CHANGED = ABAP_FALSE.
            MV_DATA_CHANGED = ABAP_FALSE.
          WHEN '2'.
            RV_CHANGED = 'W'.
        ENDCASE.
      ENDIF.
    ELSE.
      RV_CHANGED = MV_DATA_CHANGED.
    ENDIF.

  ENDMETHOD.

* ---- YCL_FI_CASH_FORECAST_BL=======CM00F ----
  METHOD CLEAR_DATA_CHANGED.

    MV_DATA_CHANGED = ABAP_FALSE.

  ENDMETHOD.

* ---- YCL_FI_CASH_FORECAST_BL=======CM00G ----
  METHOD LOCK_CASH_FORECAST.

    CALL FUNCTION 'ENQUEUE_EYCASH_FOR'
      EXPORTING
        MODE_YTFI_CASH_FOR = 'E'
        MANDT              = SY-MANDT
        BUKRS              = IV_BUKRS
        PERIOD             = IV_PERIOD
*       X_BUKRS            = ' '
*       X_PERIOD           = ' '
*       _SCOPE             = '2'
*       _WAIT              = ' '
*       _COLLECT           = ' '
      EXCEPTIONS
        FOREIGN_LOCK       = 1
        SYSTEM_FAILURE     = 2
        OTHERS             = 3.
    IF SY-SUBRC <> 0.
      MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
            WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4 INTO EV_MESSAGE.
    ELSE.
      EV_LOCKED = ABAP_TRUE.
    ENDIF.

  ENDMETHOD.

* ---- YCL_FI_CASH_FORECAST_BL=======CM00H ----
  METHOD UNLOCK_CASH_FORECAST.

    CALL FUNCTION 'DEQUEUE_EYCASH_FOR'
      EXPORTING
        MODE_YTFI_CASH_FOR = 'E'
        MANDT              = SY-MANDT
        BUKRS              = IV_BUKRS
        PERIOD             = IV_PERIOD
*       X_BUKRS            = ' '
*       X_PERIOD           = ' '
*       _SCOPE             = '3'
*       _SYNCHRON          = ' '
*       _COLLECT           = ' '
      .

  ENDMETHOD.

* ---- YCL_FI_CASH_FORECAST_BL=======CM00I ----
  METHOD UNLOCK_PERIODS.

    LOOP AT MT_PERIOD INTO DATA(LS_PERIOD).
      ME->UNLOCK_CASH_FORECAST( IV_BUKRS = MP_BUKRS
                                IV_PERIOD = LS_PERIOD-PERIO6 ).
    ENDLOOP.

  ENDMETHOD.

* ---- YCL_FI_CASH_FORECAST_BL=======CM00J ----
  METHOD GET_INTERFUND_TRANSFER.

    CLEAR EV_IFUTR.

    "Get data from BSIS
    LOOP AT MT_BSIS INTO DATA(LS_BSIS) WHERE BUDAT >= IV_BEGDA
                                       AND   BUDAT <= IV_ENDDA.
      CASE LS_BSIS-SHKZG.
        WHEN 'S'. "Debit
          ADD LS_BSIS-DMBTR TO EV_IFUTR.
        WHEN 'H'. "Credit
          SUBTRACT LS_BSIS-DMBTR FROM EV_IFUTR.
      ENDCASE.
    ENDLOOP.

    "Get data from BSAS
    LOOP AT MT_BSAS INTO DATA(LS_BSAS) WHERE BUDAT >= IV_BEGDA
                                       AND   BUDAT <= IV_ENDDA.
      CASE LS_BSAS-SHKZG.
        WHEN 'S'. "Debit
          ADD LS_BSAS-DMBTR TO EV_IFUTR.
        WHEN 'H'. "Credit
          SUBTRACT LS_BSAS-DMBTR FROM EV_IFUTR.
      ENDCASE.
    ENDLOOP.

  ENDMETHOD.

* ---- YCL_FI_CASH_FORECAST_BL=======CM00K ----
  METHOD READ_WORKING_CAPITAL_FUND.

    DATA LV_PERIO TYPE FMFG_FISCAL_PERIOD.
    DATA LV_FIELDNAME TYPE FIELDNAME.
    DATA LV_WORKCAP TYPE YE_FI_WORKING_CAPITAL_FUND.
    FIELD-SYMBOLS <HSL> TYPE ANY.

    CLEAR: EV_WORKCAP.

    LOOP AT MT_GLT0_WCF INTO DATA(LS_GLT0) WHERE RYEAR = IV_FYEAR.
      CLEAR: LV_WORKCAP, LV_PERIO.
      LV_WORKCAP = LS_GLT0-HSLVT.
      DO 12 TIMES.
        ADD 1 TO LV_PERIO.
        LV_FIELDNAME = |LS_GLT0-HSL{ LV_PERIO }|.
        ASSIGN (LV_FIELDNAME) TO <HSL>.
        CHECK <HSL> IS ASSIGNED.
        IF LV_PERIO < IV_PERIO.
          ADD <HSL> TO LV_WORKCAP.
        ELSE.
          EXIT.
        ENDIF.
      ENDDO.
      ADD LV_WORKCAP TO EV_WORKCAP.
    ENDLOOP.

  ENDMETHOD.

* ---- YCL_FI_CASH_FORECAST_BL=======CO ----
PROTECTED SECTION.

* ---- YCL_FI_CASH_FORECAST_BL=======CU ----
CLASS YCL_FI_CASH_FORECAST_BL DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

PUBLIC SECTION.

  DATA MO_GRID TYPE REF TO CL_GUI_ALV_GRID .

  METHODS CHECK_DATA_CHANGED
    IMPORTING
      !IV_SET_POPUP TYPE BOOLEAN DEFAULT ABAP_FALSE
    RETURNING
      VALUE(RV_CHANGED) TYPE BOOLEAN .
  METHODS DISPLAY_ALV .
  METHODS GET_DATA .
  METHODS SAVE_DATA .
  METHODS UNLOCK_PERIODS .
  METHODS SET_SELECTION_VALUES
    IMPORTING
      !IV_SELNAME TYPE RSSCR_NAME
      !IV_KIND TYPE RSSCR_KIND
      !IV_VALUE TYPE ANY OPTIONAL
      !IT_VALUE TYPE ANY TABLE OPTIONAL .