* ==== CLASS POOL YCL_PS_PROJECT_UTILITIES ====
CLASS-POOL .
*"* class pool for class YCL_PS_PROJECT_UTILITIES

*"* local type definitions
INCLUDE YCL_PS_PROJECT_UTILITIES======CCDEF.

*"* class YCL_PS_PROJECT_UTILITIES definition
*"* public declarations
  INCLUDE YCL_PS_PROJECT_UTILITIES======CU.
*"* protected declarations
  INCLUDE YCL_PS_PROJECT_UTILITIES======CO.
*"* private declarations
  INCLUDE YCL_PS_PROJECT_UTILITIES======CI.
ENDCLASS. "YCL_PS_PROJECT_UTILITIES definition

*"* macro definitions
INCLUDE YCL_PS_PROJECT_UTILITIES======CCMAC.
*"* local class implementation
INCLUDE YCL_PS_PROJECT_UTILITIES======CCIMP.

CLASS YCL_PS_PROJECT_UTILITIES IMPLEMENTATION.
*"* method's implementations
  INCLUDE METHODS.
ENDCLASS. "YCL_PS_PROJECT_UTILITIES implementation


* ---- YCL_PS_PROJECT_UTILITIES======CI ----
PRIVATE SECTION.

* ---- YCL_PS_PROJECT_UTILITIES======CM001 ----
  METHOD SET_PRHI_TO_UP_DOWN.

    DATA LS_WBS_UP_DOWN TYPE TY_WBS_UP_DOWN.

    CLEAR MT_WBS_UP_DOWN.

    LOOP AT MT_PRHI INTO DATA(LS_PRHI) WHERE UP IS NOT INITIAL.
      LS_WBS_UP_DOWN-WBS_UP = LS_PRHI-UP.
      LS_WBS_UP_DOWN-WBS_DOWN = LS_PRHI-POSNR.
      APPEND LS_WBS_UP_DOWN TO MT_WBS_UP_DOWN.
      IF LS_PRHI-DOWN IS INITIAL.
        CLEAR LS_WBS_UP_DOWN-WBS_DOWN.
        LS_WBS_UP_DOWN-WBS_UP = LS_PRHI-POSNR.
        APPEND LS_WBS_UP_DOWN TO MT_WBS_UP_DOWN.
      ENDIF.
    ENDLOOP.

  ENDMETHOD.

* ---- YCL_PS_PROJECT_UTILITIES======CM002 ----
  METHOD CALL_PROJECT_TRANSACTION.

    DATA LV_TCODE TYPE SY-TCODE.
    DATA LV_FIELDNAME TYPE TEXT100.
    DATA LT_WBS_ELEMENT TYPE TABLE OF BAPI_WBS_ELEMENT_EXP.
    DATA LV_OBJ TYPE SWO_OBJTYP.
    FIELD-SYMBOLS <TABLE> TYPE ANY TABLE.
    FIELD-SYMBOLS <STRUCTURE> TYPE ANY.

    "Check if project has WBS element
    CALL FUNCTION 'BAPI_PROJECT_GETINFO'
      EXPORTING
        PROJECT_DEFINITION  = IV_PROJECT
*       WITH_ACTIVITIES     =
*       WITH_MILESTONES     =
*       WITH_SUBTREE        =
*     IMPORTING
*       E_PROJECT_DEFINITION         =
*       RETURN              =
      TABLES
*       I_WBS_ELEMENT_TABLE =
        E_WBS_ELEMENT_TABLE = LT_WBS_ELEMENT
*       E_WBS_MILESTONE_TABLE        =
*       E_WBS_HIERARCHIE_TABLE       =
*       E_ACTIVITY_TABLE    =
*       E_MESSAGE_TABLE     =
      .

    IF LT_WBS_ELEMENT IS INITIAL.
      LV_OBJ = 'BUS2001'.
    ELSE.
      LV_OBJ = 'BUS2054'.
    ENDIF.

    CALL FUNCTION 'PLM_PS_CALL_PROJECT_BUILDER'
      EXPORTING
        I_PAROBTYP         = SPACE
        I_PARKEY1          = SPACE
        I_PARKEY2          = SPACE
        I_ATTR1            = LV_OBJ
        I_ATTR2            = IV_PROJECT
        I_ATTR3            = SPACE
        I_ATTR4            = SPACE
        I_ACTVT            = IV_MODE
      IMPORTING
        E_TRANSACTION_CODE = LV_TCODE.

    IF LV_TCODE IS NOT INITIAL.
      CALL TRANSACTION LV_TCODE.
    ENDIF.

    LV_FIELDNAME = '(SAPLPLM_PS_PORTAL_TRANS_46C)ENTRY_DATA[]'.
    ASSIGN (LV_FIELDNAME) TO <TABLE>.
    CLEAR <TABLE>.
    LV_FIELDNAME = '(SAPLPLM_PS_PORTAL_TRANS_46C)GS_VIEW_STACK'.
    ASSIGN (LV_FIELDNAME) TO <STRUCTURE>.
    CLEAR <STRUCTURE>.

  ENDMETHOD.

* ---- YCL_PS_PROJECT_UTILITIES======CO ----
PROTECTED SECTION.

* ---- YCL_PS_PROJECT_UTILITIES======CU ----
CLASS YCL_PS_PROJECT_UTILITIES DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

PUBLIC SECTION.

  TYPES:
    BEGIN OF TY_WBS_UP_DOWN,
             WBS_UP   TYPE PS_PHIUP,
             WBS_DOWN TYPE PS_PHIDO,
           END OF TY_WBS_UP_DOWN .
  TYPES:
    TTY_WBS_UP_DOWN TYPE TABLE OF TY_WBS_UP_DOWN .

  DATA MT_WBS_UP_DOWN TYPE TTY_WBS_UP_DOWN .
  DATA MT_PRHI TYPE TT_PRHI .

  CLASS-METHODS CALL_PROJECT_TRANSACTION
    IMPORTING
      !IV_PROJECT TYPE PS_PSPID
      !IV_MODE TYPE C DEFAULT 'D' .
  METHODS SET_PRHI_TO_UP_DOWN .