* ==== CLASS POOL YCL_IM__FI_VENDOR_ADD_DATA ====
CLASS-POOL .
*"* class pool for class YCL_IM__FI_VENDOR_ADD_DATA

*"* local classes
INCLUDE YCL_IM__FI_VENDOR_ADD_DATA====CL.

*"* class YCL_IM__FI_VENDOR_ADD_DATA definition
*"* public declarations
  INCLUDE YCL_IM__FI_VENDOR_ADD_DATA====CU.
*"* protected declarations
  INCLUDE YCL_IM__FI_VENDOR_ADD_DATA====CO.
*"* private declarations
  INCLUDE YCL_IM__FI_VENDOR_ADD_DATA====CI.
ENDCLASS. "YCL_IM__FI_VENDOR_ADD_DATA definition

CLASS YCL_IM__FI_VENDOR_ADD_DATA IMPLEMENTATION.
*"* method's implementations
  INCLUDE METHODS.
ENDCLASS. "YCL_IM__FI_VENDOR_ADD_DATA implementation


* ---- YCL_IM__FI_VENDOR_ADD_DATA====CI ----
*"* private components of class YCL_IM__FI_VENDOR_ADD_DATA
*"* do not include other source files here!!!
PRIVATE SECTION.

* ---- YCL_IM__FI_VENDOR_ADD_DATA====CM001 ----
METHOD IF_EX_VENDOR_ADD_DATA~CHECK_ALL_DATA.
ENDMETHOD.

* ---- YCL_IM__FI_VENDOR_ADD_DATA====CM002 ----
METHOD IF_EX_VENDOR_ADD_DATA~SAVE_DATA.
ENDMETHOD.

* ---- YCL_IM__FI_VENDOR_ADD_DATA====CM003 ----
METHOD IF_EX_VENDOR_ADD_DATA~CHECK_DATA_CHANGED.
ENDMETHOD.

* ---- YCL_IM__FI_VENDOR_ADD_DATA====CM004 ----
METHOD IF_EX_VENDOR_ADD_DATA~INITIALIZE_ADD_ON_DATA.
ENDMETHOD.

* ---- YCL_IM__FI_VENDOR_ADD_DATA====CM005 ----
METHOD IF_EX_VENDOR_ADD_DATA~READ_ADD_ON_DATA.
ENDMETHOD.

* ---- YCL_IM__FI_VENDOR_ADD_DATA====CM006 ----
METHOD IF_EX_VENDOR_ADD_DATA~CHECK_ACCOUNT_NUMBER.
ENDMETHOD.

* ---- YCL_IM__FI_VENDOR_ADD_DATA====CM007 ----
METHOD IF_EX_VENDOR_ADD_DATA~MODIFY_ACCOUNT_NUMBER.
ENDMETHOD.

* ---- YCL_IM__FI_VENDOR_ADD_DATA====CM008 ----
METHOD IF_EX_VENDOR_ADD_DATA~PRESET_VALUES_CCODE.
ENDMETHOD.

* ---- YCL_IM__FI_VENDOR_ADD_DATA====CM009 ----
METHOD IF_EX_VENDOR_ADD_DATA~PRESET_VALUES_PORG.
ENDMETHOD.

* ---- YCL_IM__FI_VENDOR_ADD_DATA====CM00A ----
METHOD IF_EX_VENDOR_ADD_DATA~PRESET_VALUES_PORG_ALTERNATIVE.
ENDMETHOD.

* ---- YCL_IM__FI_VENDOR_ADD_DATA====CM00B ----
METHOD IF_EX_VENDOR_ADD_DATA~GET_CHANGEDOCS_FOR_OWN_TABLES.
ENDMETHOD.

* ---- YCL_IM__FI_VENDOR_ADD_DATA====CM00C ----
METHOD IF_EX_VENDOR_ADD_DATA~CHECK_ADD_ON_ACTIVE.
  IF I_SCREEN_GROUP = 'Z1'.
    E_ADD_ON_ACTIVE = 'X'.
  ENDIF.
ENDMETHOD.

* ---- YCL_IM__FI_VENDOR_ADD_DATA====CM00D ----
METHOD IF_EX_VENDOR_ADD_DATA~BUILD_TEXT_FOR_CHANGE_DETAIL.
ENDMETHOD.

* ---- YCL_IM__FI_VENDOR_ADD_DATA====CM00E ----
METHOD IF_EX_VENDOR_ADD_DATA~SET_USER_INPUTS.
ENDMETHOD.

* ---- YCL_IM__FI_VENDOR_ADD_DATA====CO ----
*"* protected components of class YCL_IM__FI_VENDOR_ADD_DATA
*"* do not include other source files here!!!
PROTECTED SECTION.

* ---- YCL_IM__FI_VENDOR_ADD_DATA====CU ----
CLASS YCL_IM__FI_VENDOR_ADD_DATA DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

*"* public components of class YCL_IM__FI_VENDOR_ADD_DATA
*"* do not include other source files here!!!
PUBLIC SECTION.

  INTERFACES IF_BADI_INTERFACE .
  INTERFACES IF_EX_VENDOR_ADD_DATA .