* ==== CLASS POOL YCL_FM_BR_EXCHANGE_RATE_BL ====
CLASS-POOL .
*"* class pool for class YCL_FM_BR_EXCHANGE_RATE_BL

*"* local type definitions
INCLUDE YCL_FM_BR_EXCHANGE_RATE_BL====CCDEF.

*"* class YCL_FM_BR_EXCHANGE_RATE_BL definition
*"* public declarations
  INCLUDE YCL_FM_BR_EXCHANGE_RATE_BL====CU.
*"* protected declarations
  INCLUDE YCL_FM_BR_EXCHANGE_RATE_BL====CO.
*"* private declarations
  INCLUDE YCL_FM_BR_EXCHANGE_RATE_BL====CI.
ENDCLASS. "YCL_FM_BR_EXCHANGE_RATE_BL definition

*"* macro definitions
INCLUDE YCL_FM_BR_EXCHANGE_RATE_BL====CCMAC.
*"* local class implementation
INCLUDE YCL_FM_BR_EXCHANGE_RATE_BL====CCIMP.

CLASS YCL_FM_BR_EXCHANGE_RATE_BL IMPLEMENTATION.
*"* method's implementations
  INCLUDE METHODS.
ENDCLASS. "YCL_FM_BR_EXCHANGE_RATE_BL implementation


* ---- YCL_FM_BR_EXCHANGE_RATE_BL====CI ----
PRIVATE SECTION.

  DATA MV_BUKRS TYPE BUKRS .
  DATA MV_FIKRS TYPE FIKRS .
  DATA MV_START_DATE TYPE BEGDA .
  CLASS-DATA MO_INSTANCE TYPE REF TO YCL_FM_BR_EXCHANGE_RATE_BL .
  DATA:
    MR_RLDNR TYPE RANGE OF RLDNR .
  DATA:
    MR_FIKRS TYPE RANGE OF FIKRS .
  DATA:
    MR_GSBER TYPE RANGE OF GSBER .
  DATA:
    MR_WAERS TYPE RANGE OF WAERS .
  DATA:
    MR_FIPEX TYPE RANGE OF FM_FIPEX .
  DATA:
    MR_VRGNG TYPE RANGE OF CO_VORGANG .
  DATA:
    MR_BUKRS TYPE RANGE OF BUKRS .
  DATA:
    MR_FUND_TYPE TYPE RANGE OF FM_FUNDTYPE .
  DATA:
*Staff
    MR_VRGNG2 TYPE RANGE OF CO_VORGANG .
  DATA:
    MR_WAERS2 TYPE RANGE OF WAERS .
  DATA:
    MR_HKONT TYPE RANGE OF HKONT .
  DATA:
*Revaluation
    MR_FUND_TYPE3 TYPE RANGE OF FM_FUNDTYPE .
  DATA:
    MR_FIPEX3 TYPE RANGE OF FM_FIPEX .
  DATA:
    MR_VRGNG3 TYPE RANGE OF CO_VORGANG .

* ---- YCL_FM_BR_EXCHANGE_RATE_BL====CM001 ----
  METHOD GET_INSTANCE.

    IF MO_INSTANCE IS INITIAL.
      MO_INSTANCE = NEW YCL_FM_BR_EXCHANGE_RATE_BL( ).
    ENDIF.

    RO_INSTANCE = MO_INSTANCE.

  ENDMETHOD.

* ---- YCL_FM_BR_EXCHANGE_RATE_BL====CM002 ----
  METHOD CONSTRUCTOR.

    "Set values for ranges
    APPEND VALUE #( SIGN = 'I' OPTION = 'EQ' LOW = '9A' ) TO MR_RLDNR.
    APPEND VALUE #( SIGN = 'I' OPTION = 'EQ' LOW = 'UNES' ) TO MR_BUKRS.
    APPEND VALUE #( SIGN = 'I' OPTION = 'EQ' LOW = 'UNES' ) TO MR_FIKRS.
    APPEND VALUE #( SIGN = 'I' OPTION = 'EQ' LOW = 'GEF' ) TO MR_GSBER.
    APPEND VALUE #( SIGN = 'I' OPTION = 'EQ' LOW = 'EUR' ) TO MR_WAERS.
    MR_FIPEX = VALUE #( ( SIGN = 'E' OPTION = 'EQ' LOW = 'GAINS' )
                        ( SIGN = 'E' OPTION = 'EQ' LOW = 'REVENUE' ) ).
    MR_VRGNG = VALUE #( ( SIGN = 'E' OPTION = 'EQ' LOW = 'HRM1' )   "PBC pre-commitment
                        ( SIGN = 'E' OPTION = 'EQ' LOW = 'HRM2' )   "PBC commitment
                        ( SIGN = 'E' OPTION = 'EQ' LOW = 'HRP1' ) )."Payroll posting
    "Set fund types perimeters
     "APPEND VALUE #( sign = 'E' option = 'EQ' low = '019' ) TO mr_fund_type.
    SELECT 'I', 'EQ', FUND_TYPE AS LOW FROM FMFUNDTYPE WHERE FM_AREA IN @MR_FIKRS
                                                       AND   ZZFIX_RATE = @ABAP_TRUE
                                       INTO TABLE @MR_FUND_TYPE.
    "For revaluation exclusion
    "APPEND VALUE #( sign = 'I' option = 'EQ' low = '019' ) TO mr_fund_type3.
    SELECT 'E', 'EQ', FUND_TYPE AS LOW FROM FMFUNDTYPE WHERE FM_AREA IN @MR_FIKRS
                                                       AND   ZZFIX_RATE = @ABAP_TRUE
                                       INTO TABLE @MR_FUND_TYPE3.

    MR_FIPEX3 = VALUE #( ( SIGN = 'I' OPTION = 'EQ' LOW = 'GAINS' )
                         ( SIGN = 'I' OPTION = 'EQ' LOW = 'REVENUE' ) ).

    MR_VRGNG3 = VALUE #( ( SIGN = 'I' OPTION = 'EQ' LOW = 'HRM1' )   "PBC pre-commitment
                        ( SIGN = 'I' OPTION = 'EQ' LOW = 'HRM2' )   "PBC commitment
                        ( SIGN = 'I' OPTION = 'EQ' LOW = 'HRP1' ) )."Payroll posting

    "Get start date for fixed rate
    SELECT SINGLE CAST( LOW AS DATS ) INTO @MV_START_DATE FROM TVARVC WHERE NAME = 'Y_FM_FIXED_RATE_START'
                                                                      AND   TYPE = 'P'.
    IF MV_START_DATE IS INITIAL OR MV_START_DATE = SPACE.
      MV_START_DATE = '99991231'.
    ENDIF.

    "staff operations
    MR_VRGNG2 = VALUE #( ( SIGN = 'I' OPTION = 'EQ' LOW = 'HRM1' )   "PBC pre-commitment
                        ( SIGN = 'I' OPTION = 'EQ' LOW = 'HRM2' )   "PBC commitment
                        ( SIGN = 'I' OPTION = 'EQ' LOW = 'HRP1' ) )."Payroll posting

    APPEND VALUE #( SIGN = 'I' OPTION = 'EQ' LOW = 'EUR' ) TO MR_WAERS2.
    APPEND VALUE #( SIGN = 'I' OPTION = 'EQ' LOW = 'USD' ) TO MR_WAERS2.

  ENDMETHOD.

* ---- YCL_FM_BR_EXCHANGE_RATE_BL====CM003 ----
  METHOD CHECK_CONDITIONS.

    RV_IS_OK = ABAP_FALSE.

    IF IV_RLDNR IS NOT INITIAL.
      CHECK IV_RLDNR IN MR_RLDNR.
    ENDIF.

    IF IV_BUKRS IS NOT INITIAL.
      CHECK IV_BUKRS IN MR_BUKRS.
    ENDIF.

    IF IV_FIKRS IS NOT INITIAL.
      CHECK IV_FIKRS IN MR_FIKRS.
    ENDIF.

    IF IV_GSBER IS NOT INITIAL.
      CHECK IV_GSBER IN MR_GSBER.
    ENDIF.

    IF IV_WAERS IS NOT INITIAL.
      CHECK IV_WAERS IN MR_WAERS.
    ENDIF.

    IF IV_FIPEX IS NOT INITIAL.
      CHECK IV_FIPEX IN MR_FIPEX.
    ENDIF.

    IF IV_VRGNG IS NOT INITIAL.
      CHECK IV_VRGNG IN MR_VRGNG.
    ENDIF.

    IF IV_FTYPE IS NOT INITIAL.
      CHECK IV_FTYPE IN MR_FUND_TYPE.
    ENDIF.

    RV_IS_OK = ABAP_TRUE..

  ENDMETHOD.

* ---- YCL_FM_BR_EXCHANGE_RATE_BL====CM004 ----
  METHOD CONVERT_TO_CURRENCY.

    CLEAR EV_LOCAL_AMOUNT.

    CALL FUNCTION 'CONVERT_TO_LOCAL_CURRENCY'
      EXPORTING
*       CLIENT           = SY-MANDT
        DATE             = IV_DATE
        FOREIGN_AMOUNT   = IV_FOREIGN_AMOUNT
        FOREIGN_CURRENCY = IV_FOREIGN_CURRENCY
        LOCAL_CURRENCY   = IV_LOCAL_CURRENCY
*       RATE             = 0
        TYPE_OF_RATE     = IV_TYPE_OF_RATE
*       READ_TCURR       = 'X'
      IMPORTING
*       EXCHANGE_RATE    =
*       FOREIGN_FACTOR   =
        LOCAL_AMOUNT     = EV_LOCAL_AMOUNT
*       LOCAL_FACTOR     =
*       EXCHANGE_RATEX   =
*       FIXED_RATE       =
*       DERIVED_RATE_TYPE       =
      EXCEPTIONS
        NO_RATE_FOUND    = 1
        OVERFLOW         = 2
        NO_FACTORS_FOUND = 3
        NO_SPREAD_FOUND  = 4
        DERIVED_2_TIMES  = 5
        OTHERS           = 6.
    EV_SUBRC = SY-SUBRC.

  ENDMETHOD.

* ---- YCL_FM_BR_EXCHANGE_RATE_BL====CM005 ----
  METHOD GET_EXCHANGE_RATE.

    CALL FUNCTION 'READ_EXCHANGE_RATE'
      EXPORTING
*       CLIENT           = SY-MANDT
        DATE             = IV_DATE
        FOREIGN_CURRENCY = IV_FOREIGN_CURRENCY
        LOCAL_CURRENCY   = IV_LOCAL_CURRENCY
        TYPE_OF_RATE     = 'EURX'
*       EXACT_DATE       = ' '
      IMPORTING
        EXCHANGE_RATE    = EV_EXCHANGE_RATE
*       FOREIGN_FACTOR   =
*       LOCAL_FACTOR     =
*       VALID_FROM_DATE  =
*       DERIVED_RATE_TYPE       =
*       FIXED_RATE       =
*       OLDEST_RATE_FROM =
      EXCEPTIONS
        NO_RATE_FOUND    = 1
        NO_FACTORS_FOUND = 2
        NO_SPREAD_FOUND  = 3
        DERIVED_2_TIMES  = 4
        OVERFLOW         = 5
        ZERO_RATE        = 6
        OTHERS           = 7.

    EV_SUBRC = SY-SUBRC.

  ENDMETHOD.

* ---- YCL_FM_BR_EXCHANGE_RATE_BL====CM006 ----
  METHOD FMAVC_REINIT_ON_EVENT.

    DATA LT_FUND TYPE RANGE OF BP_GEBER.
    DATA LT_ALDNR TYPE RANGE OF BUAVC_ALDNR.

    CHECK KIND = CL_SYSTEM_TRANSACTION_STATE=>COMMIT_WORK.

    APPEND VALUE #( SIGN = 'I' OPTION = 'EQ' LOW = '9H' ) TO LT_ALDNR.

    LOOP AT MT_AVC_FUND INTO DATA(LS_AVC_FUND).
      APPEND VALUE #( SIGN = 'I' OPTION = 'EQ' LOW = LS_AVC_FUND-FONDS ) TO LT_FUND.
      AT END OF FIKRS.
        SET PARAMETER ID 'FIK' FIELD LS_AVC_FUND-FIKRS.
        SUBMIT RFFMAVC_REINIT EXPORTING LIST TO MEMORY
                              WITH P_FIKRS = LS_AVC_FUND-FIKRS
                              WITH P_GJAHR = LS_AVC_FUND-GJAHR
                              WITH S_FUND IN LT_FUND
                              WITH S_ALDNR IN LT_ALDNR
                              AND  RETURN.
        CLEAR LT_FUND.
      ENDAT.
    ENDLOOP.

    CLEAR MT_AVC_FUND.

  ENDMETHOD.

* ---- YCL_FM_BR_EXCHANGE_RATE_BL====CM007 ----
  METHOD GET_FUND_TYPE_FROM_FUND.

    SELECT SINGLE TYPE FROM FMFINCODE WHERE FIKRS = @IV_FIKRS
                                      AND   FINCODE = @IV_FINCODE
                       INTO @RV_FTYPE.
    IF SY-SUBRC <> 0.
      CLEAR RV_FTYPE.
    ENDIF.

  ENDMETHOD.

* ---- YCL_FM_BR_EXCHANGE_RATE_BL====CM008 ----
  METHOD GET_FM_AREA_FROM_COMPANY_CODE.

    IF IV_BUKRS <> MV_BUKRS.
      CLEAR MV_FIKRS.
      SELECT SINGLE FIKRS FROM T001 WHERE BUKRS = @IV_BUKRS INTO @MV_FIKRS.
      MV_BUKRS = IV_BUKRS.
    ENDIF.

    RV_FIKRS = MV_FIKRS.

  ENDMETHOD.

* ---- YCL_FM_BR_EXCHANGE_RATE_BL====CM009 ----
  METHOD CONVERT_TO_CURRENCY_2.

    DATA: EV_LOCAL_AMOUNT_2 TYPE BSEG-DMBTR.


*Step 1 Convert USD UNORE to EUR UNORE
    CALL FUNCTION 'CONVERT_TO_LOCAL_CURRENCY'
      EXPORTING
        DATE             = IV_DATE
        FOREIGN_AMOUNT   = IV_FOREIGN_AMOUNT
        FOREIGN_CURRENCY = 'USD'                 " USD UNORE
        LOCAL_CURRENCY   = 'EUR'                 " EUR UNORE
        TYPE_OF_RATE     = IV_TYPE_OF_RATE_UNORE " M
*       READ_TCURR       = 'X'
      IMPORTING
        LOCAL_AMOUNT     = EV_LOCAL_AMOUNT_2      "USD Unore converted to EUR Unore
      EXCEPTIONS
        NO_RATE_FOUND    = 1
        OVERFLOW         = 2
        NO_FACTORS_FOUND = 3
        NO_SPREAD_FOUND  = 4
        DERIVED_2_TIMES  = 5
        OTHERS           = 6.
    EV_SUBRC = SY-SUBRC.


*Step 2 Convert EUR UNORE to USD BR
    CLEAR EV_LOCAL_AMOUNT.
    CALL FUNCTION 'CONVERT_TO_LOCAL_CURRENCY'
      EXPORTING
        DATE             = IV_DATE
        FOREIGN_AMOUNT   = EV_LOCAL_AMOUNT_2     " Amount converted to EUR unore
        FOREIGN_CURRENCY = 'EUR'                " EUR
        LOCAL_CURRENCY   = 'USD'                " USD
        TYPE_OF_RATE     = IV_TYPE_OF_RATE      "EURX
      IMPORTING
        LOCAL_AMOUNT     = EV_LOCAL_AMOUNT    "EUR Unore converted to USD BR
      EXCEPTIONS
        NO_RATE_FOUND    = 1
        OVERFLOW         = 2
        NO_FACTORS_FOUND = 3
        NO_SPREAD_FOUND  = 4
        DERIVED_2_TIMES  = 5
        OTHERS           = 6.
    EV_SUBRC = SY-SUBRC.

  ENDMETHOD.

* ---- YCL_FM_BR_EXCHANGE_RATE_BL====CM00A ----
  METHOD CHECK_CONDITIONS_2.
* Check Staff Conditions

    RV_IS_OK = ABAP_FALSE.

    IF IV_RLDNR IS NOT INITIAL.
      CHECK IV_RLDNR IN MR_RLDNR.
    ENDIF.

    IF IV_BUKRS IS NOT INITIAL.
      CHECK IV_BUKRS IN MR_BUKRS.
    ENDIF.

    IF IV_FIKRS IS NOT INITIAL.
      CHECK IV_FIKRS IN MR_FIKRS.
    ENDIF.

    IF IV_GSBER IS NOT INITIAL.
      CHECK IV_GSBER IN MR_GSBER.
    ENDIF.
    "staff
    IF IV_WAERS IS NOT INITIAL.
      CHECK IV_WAERS IN MR_WAERS2.
    ENDIF.

    IF IV_FIPEX IS NOT INITIAL.
      CHECK IV_FIPEX IN MR_FIPEX.
    ENDIF.

    IF IV_HKONT IS NOT INITIAL.
       CHECK IV_HKONT IN  MR_HKONT.
    ENDIF.

    "staff
    IF IV_VRGNG IS NOT INITIAL.
      CHECK IV_VRGNG IN MR_VRGNG2.
    ENDIF.

    IF IV_FTYPE IS NOT INITIAL.
      CHECK IV_FTYPE IN MR_FUND_TYPE.
    ENDIF.

    RV_IS_OK = ABAP_TRUE..

  ENDMETHOD.

* ---- YCL_FM_BR_EXCHANGE_RATE_BL====CM00B ----
  METHOD CHECK_CONDITIONS_3.
* Check Reconstruction Conditions for deletion

    RV_IS_OK = ABAP_FALSE.

    IF IV_RLDNR IS NOT INITIAL.
      CHECK IV_RLDNR NOT IN MR_RLDNR.
    ENDIF.

    IF IV_BUKRS IS NOT INITIAL.
      CHECK IV_BUKRS NOT IN MR_BUKRS.
    ENDIF.

    IF IV_FIKRS IS NOT INITIAL.
      CHECK IV_FIKRS NOT IN MR_FIKRS.
    ENDIF.

    IF IV_GSBER IS NOT INITIAL.
      CHECK IV_GSBER NOT IN MR_GSBER.
    ENDIF.

    IF IV_FIPEX IS NOT INITIAL.
      CHECK IV_FIPEX IN MR_FIPEX3.
    ENDIF.

    IF IV_VRGNG IS NOT INITIAL.
      CHECK IV_VRGNG IN MR_VRGNG3.
    ENDIF.

    IF IV_FTYPE IS NOT INITIAL.
      CHECK IV_FTYPE IN MR_FUND_TYPE3.
    ENDIF.

    RV_IS_OK = ABAP_TRUE..

  ENDMETHOD.

* ---- YCL_FM_BR_EXCHANGE_RATE_BL====CM00C ----
  METHOD CHECK_BR_IS_ACTIVE.

    RV_IS_OK = ABAP_FALSE.

    IF SY-DATUM >= MV_START_DATE.
      RV_IS_OK = ABAP_TRUE.
    ENDIF.

  ENDMETHOD.

* ---- YCL_FM_BR_EXCHANGE_RATE_BL====CM00D ----
  METHOD GET_BR_IMPACT.

    IF IV_TRBTRP = 0.
      EV_ZZBRIMPACTED = 'E'.
    ELSE.
      EV_ZZBRIMPACTED = 'X'.
    ENDIF.

    IF IV_WRTTP = '54'.    "Check if from BSEG
      IF IV_BSEG_DMBTR IS NOT INITIAL AND IV_BSEG_SHKZG IS NOT INITIAL.
        EV_ZZAMOUNTBRLC = IV_BSEG_DMBTR.
        IF IV_BSEG_SHKZG = 'H'.
          MULTIPLY EV_ZZAMOUNTBRLC BY -1.
        ENDIF.
      ELSEIF IV_BSEG_BELNR IS NOT INITIAL.
        SELECT SINGLE SHKZG, DMBTR FROM BSEG WHERE BUKRS = @IV_BUKRS
                                             AND   BELNR = @IV_BSEG_BELNR
                                             AND   GJAHR = @IV_BSEG_GJAHR
                                             AND   BUZEI = @IV_BSEG_BUZEI
                                   INTO ( @DATA(LV_SHKZG), @EV_ZZAMOUNTBRLC ).
        IF LV_SHKZG = 'H'.
          MULTIPLY EV_ZZAMOUNTBRLC BY -1.
        ENDIF.
      ENDIF.
      "Check if the value is filled from table EKBE
    ELSEIF IV_WRTTP = '51'    "Purchase Orders    "Check if the value is filled from table EKBE
       AND IV_VRGNG = 'RMBE'
       AND IV_BTART = '0200'.   "Reduction

      "GET amount from ekbe
      YCL_MM_PO_UTILITIES=>GET_EKBE_AMOUNTS_1( EXPORTING IV_EBELN = IV_REFBN
                                                         IV_EBELP = IV_RFPOS
                                                         IV_VGABE = '1'  "GR
                                                         IV_GJAHR = IV_GJAHR
                                                         IV_WAERS = IV_TWAER
                                                         IV_GEBER = IV_FINCODE
                                               IMPORTING EV_DMBTR = EV_ZZAMOUNTBRLC ).
      MULTIPLY EV_ZZAMOUNTBRLC BY -1.  "Because of reduction
    ELSE.
      IF IV_KURSF IS NOT INITIAL.
        IF IV_KURSF < 0.
          EV_ZZAMOUNTBRLC = - IV_TRBTRP / IV_KURSF.
        ELSE.
          EV_ZZAMOUNTBRLC = IV_TRBTRP * IV_KURSF.
        ENDIF.
      ELSE.
*Convert Tramsaction Amount to UNORE
        CALL FUNCTION 'CONVERT_TO_LOCAL_CURRENCY'
          EXPORTING
            DATE             = IV_BUDAT
            FOREIGN_AMOUNT   = IV_TRBTRP
            FOREIGN_CURRENCY = IV_TWAER
            LOCAL_CURRENCY   = 'USD'
            TYPE_OF_RATE     = 'M'
          IMPORTING
            LOCAL_AMOUNT     = EV_ZZAMOUNTBRLC
          EXCEPTIONS
            NO_RATE_FOUND    = 1
            OVERFLOW         = 2
            NO_FACTORS_FOUND = 3
            NO_SPREAD_FOUND  = 4
            DERIVED_2_TIMES  = 5
            OTHERS           = 6.
      ENDIF.
    ENDIF.

    EV_ZZAMOUNTBRDIFF = IV_FKBTRP - EV_ZZAMOUNTBRLC.

  ENDMETHOD.

* ---- YCL_FM_BR_EXCHANGE_RATE_BL====CO ----
PROTECTED SECTION.

* ---- YCL_FM_BR_EXCHANGE_RATE_BL====CU ----
CLASS YCL_FM_BR_EXCHANGE_RATE_BL DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

PUBLIC SECTION.

  TYPES:
    BEGIN OF TY_AVC_FUND,
             GJAHR TYPE GJAHR,
             FIKRS TYPE FIKRS,
             FONDS TYPE BP_GEBER,
           END OF TY_AVC_FUND .

  DATA:
    MT_AVC_FUND TYPE SORTED TABLE OF TY_AVC_FUND WITH UNIQUE KEY GJAHR FIKRS FONDS .

  METHODS CHECK_BR_IS_ACTIVE
    RETURNING
      VALUE(RV_IS_OK) TYPE XFELD .
  METHODS GET_BR_IMPACT
    IMPORTING
      !IV_BUKRS TYPE BUKRS
      !IV_GJAHR TYPE GJAHR
      !IV_FKBTRP TYPE FM_FKBTRPY
      !IV_TRBTRP TYPE FM_TRBTRPY
      !IV_TWAER TYPE TWAER
      !IV_WRTTP TYPE CO_WRTTP
      !IV_VRGNG TYPE CO_VORGANG
      !IV_BTART TYPE FM_BTART
      !IV_BUDAT TYPE BUDAT
      !IV_KURSF TYPE KURSF OPTIONAL
      !IV_BSEG_BELNR TYPE BELNR_D OPTIONAL
      !IV_BSEG_GJAHR TYPE GJAHR OPTIONAL
      !IV_BSEG_BUZEI TYPE BUZEI OPTIONAL
      !IV_BSEG_DMBTR TYPE DMBTR OPTIONAL
      !IV_BSEG_SHKZG TYPE SHKZG OPTIONAL
      !IV_REFBN TYPE CO_REFBN OPTIONAL
      !IV_RFPOS TYPE CC_RFPOS OPTIONAL
      !IV_FINCODE TYPE BP_GEBER
    EXPORTING
      !EV_ZZBRIMPACTED TYPE ZE_BRAFFECTED
      !EV_ZZAMOUNTBRLC TYPE ZE_AMOUNTBR_LC
      !EV_ZZAMOUNTBRDIFF TYPE ZE_AMOUNTBR_DIFF .
  METHODS GET_FM_AREA_FROM_COMPANY_CODE
    IMPORTING
      !IV_BUKRS TYPE BUKRS
    RETURNING
      VALUE(RV_FIKRS) TYPE FIKRS .
  METHODS GET_FUND_TYPE_FROM_FUND
    IMPORTING
      !IV_FIKRS TYPE FIKRS
      !IV_FINCODE TYPE BP_GEBER
    RETURNING
      VALUE(RV_FTYPE) TYPE FM_FUNDTYPE .
  METHODS CHECK_CONDITIONS
    IMPORTING
      !IV_RLDNR TYPE RLDNR OPTIONAL
      !IV_BUKRS TYPE BUKRS OPTIONAL
      !IV_FIKRS TYPE FIKRS OPTIONAL
      !IV_GSBER TYPE GSBER OPTIONAL
      !IV_WAERS TYPE WAERS OPTIONAL
      !IV_FIPEX TYPE FM_FIPEX OPTIONAL
      !IV_VRGNG TYPE CO_VORGANG OPTIONAL
      !IV_FTYPE TYPE FM_FUNDTYPE OPTIONAL
    RETURNING
      VALUE(RV_IS_OK) TYPE XFELD .
  METHODS CHECK_CONDITIONS_2
    IMPORTING
      !IV_RLDNR TYPE RLDNR OPTIONAL
      !IV_BUKRS TYPE BUKRS OPTIONAL
      !IV_FIKRS TYPE FIKRS OPTIONAL
      !IV_GSBER TYPE GSBER OPTIONAL
      !IV_WAERS TYPE WAERS OPTIONAL
      !IV_FIPEX TYPE FM_FIPEX OPTIONAL
      !IV_VRGNG TYPE CO_VORGANG OPTIONAL
      !IV_FTYPE TYPE FM_FUNDTYPE OPTIONAL
      !IV_HKONT TYPE HKONT OPTIONAL
    RETURNING
      VALUE(RV_IS_OK) TYPE XFELD .
  METHODS CONVERT_TO_CURRENCY
    IMPORTING
      !IV_DATE TYPE DATUM
      !IV_TYPE_OF_RATE TYPE KURST_CURR DEFAULT 'EURX'
      !IV_FOREIGN_AMOUNT TYPE ANY
      !IV_FOREIGN_CURRENCY TYPE WAERS
      !IV_LOCAL_CURRENCY TYPE WAERS
    EXPORTING
      !EV_LOCAL_AMOUNT TYPE ANY
      !EV_SUBRC TYPE SY-SUBRC .
  METHODS CONVERT_TO_CURRENCY_2
    IMPORTING
      !IV_DATE TYPE DATUM
      !IV_TYPE_OF_RATE TYPE KURST_CURR DEFAULT 'EURX'
      !IV_FOREIGN_AMOUNT TYPE ANY
      !IV_FOREIGN_CURRENCY TYPE WAERS
      !IV_LOCAL_CURRENCY TYPE WAERS
      !IV_TYPE_OF_RATE_UNORE TYPE KURST_CURR DEFAULT 'M'
    EXPORTING
      !EV_LOCAL_AMOUNT TYPE ANY
      !EV_SUBRC TYPE SY-SUBRC .
  METHODS FMAVC_REINIT_ON_EVENT
    FOR EVENT TRANSACTION_FINISHED OF CL_SYSTEM_TRANSACTION_STATE
    IMPORTING
      !KIND .
  METHODS GET_EXCHANGE_RATE
    IMPORTING
      !IV_DATE TYPE DATUM
      !IV_FOREIGN_CURRENCY TYPE WAERS
      !IV_LOCAL_CURRENCY TYPE WAERS
    EXPORTING
      !EV_EXCHANGE_RATE TYPE ANY
      !EV_SUBRC TYPE SY-SUBRC .
  METHODS CONSTRUCTOR .
  CLASS-METHODS GET_INSTANCE
    RETURNING
      VALUE(RO_INSTANCE) TYPE REF TO YCL_FM_BR_EXCHANGE_RATE_BL .
  METHODS CHECK_CONDITIONS_3
    IMPORTING
      !IV_RLDNR TYPE RLDNR OPTIONAL
      !IV_BUKRS TYPE BUKRS OPTIONAL
      !IV_FIKRS TYPE FIKRS OPTIONAL
      !IV_GSBER TYPE GSBER OPTIONAL
      !IV_WAERS TYPE WAERS OPTIONAL
      !IV_FIPEX TYPE FM_FIPEX OPTIONAL
      !IV_VRGNG TYPE CO_VORGANG OPTIONAL
      !IV_FTYPE TYPE FM_FUNDTYPE OPTIONAL
      !IV_HKONT TYPE HKONT OPTIONAL
    RETURNING
      VALUE(RV_IS_OK) TYPE XFELD .