* ==== CLASS POOL YCL_FI_BR_UPDATE_TABLES ====
CLASS-POOL .
*"* class pool for class YCL_FI_BR_UPDATE_TABLES

*"* local type definitions
INCLUDE YCL_FI_BR_UPDATE_TABLES=======CCDEF.

*"* class YCL_FI_BR_UPDATE_TABLES definition
*"* public declarations
  INCLUDE YCL_FI_BR_UPDATE_TABLES=======CU.
*"* protected declarations
  INCLUDE YCL_FI_BR_UPDATE_TABLES=======CO.
*"* private declarations
  INCLUDE YCL_FI_BR_UPDATE_TABLES=======CI.
ENDCLASS. "YCL_FI_BR_UPDATE_TABLES definition

*"* macro definitions
INCLUDE YCL_FI_BR_UPDATE_TABLES=======CCMAC.
*"* local class implementation
INCLUDE YCL_FI_BR_UPDATE_TABLES=======CCIMP.

CLASS YCL_FI_BR_UPDATE_TABLES IMPLEMENTATION.
*"* method's implementations
  INCLUDE METHODS.
ENDCLASS. "YCL_FI_BR_UPDATE_TABLES implementation


* ---- YCL_FI_BR_UPDATE_TABLES=======CI ----
PRIVATE SECTION.

* ---- YCL_FI_BR_UPDATE_TABLES=======CM001 ----
  METHOD UPDATE_BR_FMIFIIT.

    DATA LS_BR_FMIFIIT TYPE YTFM_BR_FMIFIIT.

    IF IS_FMIFIIT IS INITIAL.
      EV_SUBRC = 8.
      EXIT.
    ENDIF.

    SELECT SINGLE * FROM YTFM_BR_FMIFIIT WHERE FMBELNR = @IS_FMIFIIT-FMBELNR
                                         AND   FIKRS = @IS_FMIFIIT-FIKRS
                                         AND   FMBUZEI = @IS_FMIFIIT-FMBUZEI
                                         AND   BTART = @IS_FMIFIIT-BTART
                                         AND   RLDNR = @IS_FMIFIIT-RLDNR
                                         AND   GJAHR = @IS_FMIFIIT-GJAHR
                                         AND   STUNR = @IS_FMIFIIT-STUNR
                    INTO @LS_BR_FMIFIIT.
    IF SY-SUBRC = 0.
      LS_BR_FMIFIIT-ZFKBTR = IS_FMIFIIT-FKBTR.
      LS_BR_FMIFIIT-ZTRBTR = IS_FMIFIIT-TRBTR.
      LS_BR_FMIFIIT-TWAER = IS_FMIFIIT-TWAER.
      LS_BR_FMIFIIT-CPUDT = SY-DATUM.
      LS_BR_FMIFIIT-CPUTM = SY-UZEIT.
      LS_BR_FMIFIIT-USNAM = SY-UNAME.
      LS_BR_FMIFIIT-TCODE = SY-TCODE.
      UPDATE YTFM_BR_FMIFIIT FROM LS_BR_FMIFIIT.
      EV_SUBRC = SY-SUBRC.
    ELSE.
      MOVE-CORRESPONDING IS_FMIFIIT TO LS_BR_FMIFIIT.
      LS_BR_FMIFIIT-ZFKBTR = IS_FMIFIIT-FKBTR.
      LS_BR_FMIFIIT-ZTRBTR = IS_FMIFIIT-TRBTR.
      LS_BR_FMIFIIT-CPUDT = SY-DATUM.
      LS_BR_FMIFIIT-CPUTM = SY-UZEIT.
      LS_BR_FMIFIIT-USNAM = SY-UNAME.
      LS_BR_FMIFIIT-TCODE = SY-TCODE.
      INSERT YTFM_BR_FMIFIIT FROM LS_BR_FMIFIIT.
      EV_SUBRC = SY-SUBRC.
    ENDIF.

  ENDMETHOD.

* ---- YCL_FI_BR_UPDATE_TABLES=======CM002 ----
  METHOD UPDATE_BR_FMIOI.

    DATA LS_BR_FMIOI TYPE YTFM_BR_FMIOI.

    IF IS_FMIOI IS INITIAL.
      EV_SUBRC = 8.
      EXIT.
    ENDIF.

    SELECT SINGLE * FROM YTFM_BR_FMIOI WHERE REFBN = @IS_FMIOI-REFBN
                                       AND   REFBT = @IS_FMIOI-REFBT
                                       AND   RFORG = @IS_FMIOI-RFORG
                                       AND   RFPOS = @IS_FMIOI-RFPOS
                                       AND   RFKNT = @IS_FMIOI-RFKNT
                                       AND   RFETE = @IS_FMIOI-RFETE
                                       AND   RCOND = @IS_FMIOI-RCOND
                                       AND   RFTYP = @IS_FMIOI-RFTYP
                                       AND   RFSYS = @IS_FMIOI-RFSYS
                                       AND   BTART = @IS_FMIOI-BTART
                                       AND   RLDNR = @IS_FMIOI-RLDNR
                                       AND   GJAHR = @IS_FMIOI-GJAHR
                                       AND   STUNR = @IS_FMIOI-STUNR
                    INTO @LS_BR_FMIOI.
    IF SY-SUBRC = 0.
      LS_BR_FMIOI-WRTTP = IS_FMIOI-WRTTP.
      LS_BR_FMIOI-ZFKBTR = IS_FMIOI-FKBTR.
      LS_BR_FMIOI-ZTRBTR = IS_FMIOI-TRBTR.
      LS_BR_FMIOI-TWAER = IS_FMIOI-TWAER.
      LS_BR_FMIOI-CPUDT = SY-DATUM.
      LS_BR_FMIOI-CPUTM = SY-UZEIT.
      LS_BR_FMIOI-USNAM = SY-UNAME.
      LS_BR_FMIOI-TCODE = SY-TCODE.
      UPDATE YTFM_BR_FMIOI FROM LS_BR_FMIOI.
      EV_SUBRC = SY-SUBRC.
    ELSE.
      MOVE-CORRESPONDING IS_FMIOI TO LS_BR_FMIOI.
      LS_BR_FMIOI-ZFKBTR = IS_FMIOI-FKBTR.
      LS_BR_FMIOI-ZTRBTR = IS_FMIOI-TRBTR.
      LS_BR_FMIOI-CPUDT = SY-DATUM.
      LS_BR_FMIOI-CPUTM = SY-UZEIT.
      LS_BR_FMIOI-USNAM = SY-UNAME.
      LS_BR_FMIOI-TCODE = SY-TCODE.
      INSERT YTFM_BR_FMIOI FROM LS_BR_FMIOI.
      EV_SUBRC = SY-SUBRC.
    ENDIF.

  ENDMETHOD.

* ---- YCL_FI_BR_UPDATE_TABLES=======CM003 ----
  METHOD UPDATE_BR_FM_POS.

    SELECT SINGLE * FROM YTFM_BR_FM_POS WHERE ENC_TYPE = @IV_ENC_TYPE
                                        AND   BELNR = @IV_BELNR
                                        AND   FPM_POSNR = @IV_FPM_POSNR
                    INTO @DATA(LS_FM_POS).
    IF SY-SUBRC = 0.
      LS_FM_POS-BETRG_BEFORE = IV_BETRG_BEFORE.
      LS_FM_POS-BWAER_BEFORE = IV_BWAER_BEFORE.
      LS_FM_POS-BETRG_AFTER = IV_BETRG_AFTER.
      LS_FM_POS-DELTA_BEFORE = IV_DELTA_BEFORE.
      LS_FM_POS-DWAER_BEFORE = IV_DWAER_BEFORE.
      LS_FM_POS-DELTA_AFTER = IV_DELTA_AFTER.
      LS_FM_POS-WAERS_AFTER = IV_WAERS_AFTER.
      LS_FM_POS-CPUDT = SY-DATUM.
      LS_FM_POS-CPUTM = SY-UZEIT.
      LS_FM_POS-USNAM = SY-UNAME.
      LS_FM_POS-TCODE = SY-TCODE.
      UPDATE YTFM_BR_FM_POS FROM LS_FM_POS.
      EV_SUBRC = SY-SUBRC.
    ELSE.
      LS_FM_POS-ENC_TYPE = IV_ENC_TYPE.
      LS_FM_POS-BELNR = IV_BELNR.
      LS_FM_POS-FPM_POSNR = IV_FPM_POSNR.
      LS_FM_POS-BETRG_BEFORE = IV_BETRG_BEFORE.
      LS_FM_POS-BWAER_BEFORE = IV_BWAER_BEFORE.
      LS_FM_POS-BETRG_AFTER = IV_BETRG_AFTER.
      LS_FM_POS-DELTA_BEFORE = IV_DELTA_BEFORE.
      LS_FM_POS-DWAER_BEFORE = IV_DWAER_BEFORE.
      LS_FM_POS-DELTA_AFTER = IV_DELTA_AFTER.
      LS_FM_POS-WAERS_AFTER = IV_WAERS_AFTER.
      LS_FM_POS-CPUDT = SY-DATUM.
      LS_FM_POS-CPUTM = SY-UZEIT.
      LS_FM_POS-USNAM = SY-UNAME.
      LS_FM_POS-TCODE = SY-TCODE.
      INSERT YTFM_BR_FM_POS FROM LS_FM_POS.
      EV_SUBRC = SY-SUBRC.
    ENDIF.

  ENDMETHOD.

* ---- YCL_FI_BR_UPDATE_TABLES=======CO ----
PROTECTED SECTION.

* ---- YCL_FI_BR_UPDATE_TABLES=======CU ----
CLASS YCL_FI_BR_UPDATE_TABLES DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

PUBLIC SECTION.

  CLASS-METHODS UPDATE_BR_FMIFIIT
    IMPORTING
      !IS_FMIFIIT TYPE FMIFIIT
    EXPORTING
      !EV_SUBRC TYPE SY-SUBRC .
  CLASS-METHODS UPDATE_BR_FMIOI
    IMPORTING
      !IS_FMIOI TYPE FMIOI
    EXPORTING
      !EV_SUBRC TYPE SY-SUBRC .
  CLASS-METHODS UPDATE_BR_FM_POS
    IMPORTING
      !IV_ENC_TYPE TYPE HRFPM_ENC_TYPE
      !IV_BELNR TYPE HRFPM_FPM_DOCNR
      !IV_FPM_POSNR TYPE HRFPM_FPM_POSNR
      !IV_BETRG_BEFORE TYPE BPREP_REQ_AMOUNT
      !IV_BWAER_BEFORE TYPE WAERS
      !IV_BETRG_AFTER TYPE BPREP_REQ_AMOUNT
      !IV_DELTA_BEFORE TYPE BPREP_REQUIRED_AMOUNT
      !IV_DWAER_BEFORE TYPE WAERS
      !IV_DELTA_AFTER TYPE BPREP_REQUIRED_AMOUNT
      !IV_WAERS_AFTER TYPE WAERS
    EXPORTING
      !EV_SUBRC TYPE SY-SUBRC .