* ==== CLASS POOL YCL_HRFM_NODES_BL ====
CLASS-POOL .
*"* class pool for class YCL_HRFM_NODES_BL

*"* local type definitions
INCLUDE YCL_HRFM_NODES_BL=============CCDEF.

*"* class YCL_HRFM_NODES_BL definition
*"* public declarations
  INCLUDE YCL_HRFM_NODES_BL=============CU.
*"* protected declarations
  INCLUDE YCL_HRFM_NODES_BL=============CO.
*"* private declarations
  INCLUDE YCL_HRFM_NODES_BL=============CI.
ENDCLASS. "YCL_HRFM_NODES_BL definition

*"* macro definitions
INCLUDE YCL_HRFM_NODES_BL=============CCMAC.
*"* local class implementation
INCLUDE YCL_HRFM_NODES_BL=============CCIMP.

CLASS YCL_HRFM_NODES_BL IMPLEMENTATION.
*"* method's implementations
  INCLUDE METHODS.
ENDCLASS. "YCL_HRFM_NODES_BL implementation


* ---- YCL_HRFM_NODES_BL=============CI ----
PRIVATE SECTION.

  TYPES:
    BEGIN OF TY_NODES_C,
      ORGEH TYPE YTFM_CNODES_C-ORGEH,
      CNODE TYPE YTFM_CNODES_C-CNODE,
    END OF TY_NODES_C .
  TYPES:
    BEGIN OF TY_RULES,
      ORGEH_SOURCE TYPE YTHR_SORG_RULE-ORGEH_SOURCE,
      SHORT_SOURCE TYPE SHORT_D,
      STEXT_SOURCE TYPE STEXT,
      ZZSECT       TYPE YTHR_SORG_RULE-ZZSECT,
      ORGEH_TARGET TYPE YTHR_SORG_RULE-ORGEH_TARGET,
    END OF TY_RULES .

  DATA MT_ORGEH_WITH_NODE TYPE TTY_ORGEH_WITH_NODE .
  DATA MV_DATE_REF TYPE DATUM .
  DATA:
    MT_NODES_DEF TYPE SORTED TABLE OF TY_NODES_DEF WITH UNIQUE KEY CNODE .
  DATA MV_APPLI TYPE YE_FM_APPLICATION .
  DATA:
    MT_NODES_C TYPE SORTED TABLE OF TY_NODES_C WITH UNIQUE KEY ORGEH .
  DATA:
    MT_OBJEC TYPE TABLE OF OBJEC .
  DATA:
    MT_STRUC_ORG TYPE SORTED TABLE OF STRUC WITH UNIQUE KEY OTYPE OBJID .
  DATA:
    MT_STRUC_SEQ TYPE SORTED TABLE OF STRUC WITH UNIQUE KEY SEQNR .
  DATA:
    MT_RULES TYPE TABLE OF TY_RULES .

  METHODS DO_ORGEH_MAPPING .
  METHODS READ_UNESCO_STRUCTURE .
  METHODS READ_NODES_DB .

* ---- YCL_HRFM_NODES_BL=============CM001 ----
  METHOD CONSTRUCTOR.

    MV_APPLI = IV_APPLI.
    MV_DATE_REF = IV_DATE_REF.

    ME->READ_NODES_DB( ).
    ME->READ_UNESCO_STRUCTURE( ).
    ME->DO_ORGEH_MAPPING( ).

  ENDMETHOD.

* ---- YCL_HRFM_NODES_BL=============CM002 ----
  METHOD READ_NODES_DB.

    DATA LT_NODE_RANGE TYPE RANGE OF YE_FM_CNODE.
    DATA LT_NODE_RANGE_UP TYPE RANGE OF YE_FM_CNODE.
    DATA LV_LEVEL TYPE I.

    "Read nodes definition
    SELECT A~CNODE,
           T~CNODS,
           T~CNODT,
           A~DIS_ORDER,
           A~CNODE_UP
           FROM YTFM_CNODES_A AS A
           INNER JOIN YTFM_CNODES AS D ON D~CNODE = A~CNODE
           INNER JOIN YTFM_CNODES_T AS T ON  T~SPRSL = @SY-LANGU
                                         AND T~CNODE = D~CNODE
           WHERE A~APPLI = @MV_APPLI
           AND   A~BEGDA <= @MV_DATE_REF
           AND   A~ENDDA >= @MV_DATE_REF
           AND   D~BEGDA <= @MV_DATE_REF
           AND   D~ENDDA >= @MV_DATE_REF
           INTO TABLE @MT_NODES_DEF.

    "Complete with levels
    LT_NODE_RANGE = VALUE #( ( SIGN = 'I' OPTION = 'EQ' LOW = SPACE ) ).
    DO.
      ADD 1 TO LV_LEVEL.
      LOOP AT MT_NODES_DEF ASSIGNING FIELD-SYMBOL(<LS_NODES_DEF>) WHERE CNODE_UP IN LT_NODE_RANGE.
        <LS_NODES_DEF>-LEVEL = LV_LEVEL.
        APPEND VALUE #( SIGN = 'I' OPTION = 'EQ' LOW = <LS_NODES_DEF>-CNODE ) TO LT_NODE_RANGE_UP.
      ENDLOOP.
      IF SY-SUBRC <> 0.
        EXIT.
      ENDIF.
      LT_NODE_RANGE = LT_NODE_RANGE_UP.
      CLEAR LT_NODE_RANGE_UP.
    ENDDO.

    "Read mapping org unit to node
    SELECT ORGEH,
           CNODE
           FROM YTFM_CNODES_C
           WHERE APPLI = @MV_APPLI
           AND   BEGDA <= @MV_DATE_REF
           AND   ENDDA >= @MV_DATE_REF
           INTO TABLE @MT_NODES_C.

    "Read special rules
    SELECT ORGEH_SOURCE,
           ZZSECT,
           ORGEH_TARGET
           FROM YTHR_SORG_RULE
           WHERE BEGDA <= @MV_DATE_REF
           AND   ENDDA >= @MV_DATE_REF
           INTO CORRESPONDING FIELDS OF TABLE @MT_RULES.


  ENDMETHOD.

* ---- YCL_HRFM_NODES_BL=============CM003 ----
  METHOD READ_UNESCO_STRUCTURE.

    DATA LT_STRUC TYPE TABLE OF STRUC.

    CALL FUNCTION 'RH_STRUC_GET'
      EXPORTING
        ACT_OTYPE      = 'O'
        ACT_OBJID      = '00000001'
        ACT_WEGID      = 'ORGEH'
*       ACT_INT_FLAG   =
        ACT_PLVAR      = '01'
        ACT_BEGDA      = MV_DATE_REF
        ACT_ENDDA      = MV_DATE_REF
*       ACT_TDEPTH     = 0
*       ACT_TFLAG      = 'X'
*       ACT_VFLAG      = 'X'
*       AUTHORITY_CHECK        = 'X'
*       TEXT_BUFFER_FILL       =
*       BUFFER_MODE    =
*     IMPORTING
*       ACT_PLVAR      =
      TABLES
*       RESULT_TAB     =
        RESULT_OBJEC   = MT_OBJEC
        RESULT_STRUC   = LT_STRUC
      EXCEPTIONS
        NO_PLVAR_FOUND = 1
        NO_ENTRY_FOUND = 2
        OTHERS         = 3.

    "Set to sorted tables for performance
    INSERT LINES OF LT_STRUC INTO TABLE MT_STRUC_ORG.
    INSERT LINES OF LT_STRUC INTO TABLE MT_STRUC_SEQ.

  ENDMETHOD.

* ---- YCL_HRFM_NODES_BL=============CM004 ----
  METHOD DO_ORGEH_MAPPING.

    DATA LS_ORGEH_WITH_NODE TYPE TY_ORGEH_WITH_NODE.
    DATA LS_NODES_C TYPE TY_NODES_C.
    DATA LV_ORGEH TYPE ORGEH.
    DATA LT_RULES TYPE TABLE OF TY_RULES.
    DATA LT_NODES_C TYPE SORTED TABLE OF TY_NODES_C WITH NON-UNIQUE KEY ORGEH.

    CLEAR MT_ORGEH_WITH_NODE.

    LOOP AT MT_OBJEC INTO DATA(LS_OBJEC).
      LV_ORGEH = LS_OBJEC-OBJID.
      DO.
        "check if directly assigned to a node
        READ TABLE MT_NODES_C INTO LS_NODES_C WITH KEY ORGEH = LV_ORGEH.
        IF SY-SUBRC = 0.
          LS_ORGEH_WITH_NODE-ORGEH = LS_OBJEC-OBJID.
          LS_ORGEH_WITH_NODE-CNODE = LS_NODES_C-CNODE.
          LS_ORGEH_WITH_NODE-SHORT = LS_OBJEC-SHORT.
          LS_ORGEH_WITH_NODE-STEXT = LS_OBJEC-STEXT.
          INSERT LS_ORGEH_WITH_NODE INTO TABLE MT_ORGEH_WITH_NODE.
          "add special rules
          LOOP AT MT_RULES INTO DATA(LS_RULES) WHERE ORGEH_SOURCE = LV_ORGEH.
            LS_RULES-ORGEH_SOURCE = LS_OBJEC-OBJID.
            LS_RULES-SHORT_SOURCE = LS_OBJEC-SHORT.
            LS_RULES-STEXT_SOURCE = LS_OBJEC-STEXT.
            APPEND LS_RULES TO LT_RULES.
          ENDLOOP.
          EXIT.
        ELSE.
          READ TABLE MT_STRUC_ORG INTO DATA(LS_STRUC_ORG) WITH KEY OTYPE = 'O'
                                                                   OBJID = LV_ORGEH.
          IF SY-SUBRC = 0.
            READ TABLE MT_STRUC_SEQ INTO DATA(LS_STRUC_SEQ) WITH KEY SEQNR = LS_STRUC_ORG-PUP.
            IF SY-SUBRC = 0.
              LV_ORGEH = LS_STRUC_SEQ-OBJID.
            ELSE.
              EXIT.
            ENDIF.
          ELSE.
            EXIT.
          ENDIF.
        ENDIF.
      ENDDO.
    ENDLOOP.

    "Complete nodes for org unit in rules
    LOOP AT MT_RULES INTO LS_RULES.
      LS_NODES_C-ORGEH = LS_RULES-ORGEH_TARGET.
      READ TABLE MT_ORGEH_WITH_NODE INTO LS_ORGEH_WITH_NODE WITH KEY ORGEH = LS_RULES-ORGEH_TARGET
                                                                     ZZSECT = SPACE.
      CHECK SY-SUBRC = 0.
      LS_NODES_C-CNODE = LS_ORGEH_WITH_NODE-CNODE.
      INSERT LS_NODES_C INTO TABLE LT_NODES_C.
    ENDLOOP.

    "Add special rules to result
    LOOP AT LT_RULES INTO LS_RULES.
      LS_ORGEH_WITH_NODE-ORGEH = LS_RULES-ORGEH_SOURCE.
      LS_ORGEH_WITH_NODE-ZZSECT = LS_RULES-ZZSECT.
      LS_ORGEH_WITH_NODE-SHORT = LS_RULES-SHORT_SOURCE.
      LS_ORGEH_WITH_NODE-STEXT = LS_RULES-STEXT_SOURCE.
      READ TABLE LT_NODES_C INTO LS_NODES_C WITH KEY ORGEH = LS_RULES-ORGEH_TARGET.
      CHECK SY-SUBRC = 0.
      LS_ORGEH_WITH_NODE-CNODE = LS_NODES_C-CNODE.
      INSERT LS_ORGEH_WITH_NODE INTO TABLE MT_ORGEH_WITH_NODE.
    ENDLOOP.

  ENDMETHOD.

* ---- YCL_HRFM_NODES_BL=============CM005 ----
  METHOD GET_ORG_UNITS_WITH_NODE.

    ET_ORGEH_WITH_NODE = MT_ORGEH_WITH_NODE.

  ENDMETHOD.

* ---- YCL_HRFM_NODES_BL=============CM006 ----
  METHOD GET_NODE_DEFINITION.

    ET_NODES_DEF = MT_NODES_DEF.

  ENDMETHOD.

* ---- YCL_HRFM_NODES_BL=============CM007 ----
  METHOD GET_NODE_FROM_ORG_UNIT.

    CLEAR ES_DATA.

    READ TABLE MT_ORGEH_WITH_NODE INTO ES_DATA WITH KEY ORGEH = IV_ORGEH
                                                        ZZSECT = IV_ZZSECT.
    IF SY-SUBRC <> 0.
      READ TABLE MT_ORGEH_WITH_NODE INTO ES_DATA WITH KEY ORGEH = IV_ORGEH
                                                          ZZSECT = SPACE.
    ENDIF.

  ENDMETHOD.

* ---- YCL_HRFM_NODES_BL=============CM008 ----
  METHOD GET_NODE_FROM_POSITION.

    DATA LV_ORGEH TYPE ORGEH.

    "Get org unit from position
    SELECT SINGLE CAST( SUBSTRING( SOBID, 1, 8 ) AS NUMC )
                  FROM HRP1001 WHERE PLVAR = '01'
                               AND   OTYPE = 'S'
                               AND   OBJID = @IV_PLANS
                               AND   RSIGN = 'A'
                               AND   RELAT = '003'
                               AND   ISTAT = '1'
                               AND   BEGDA <= @MV_DATE_REF
                               AND   ENDDA >= @MV_DATE_REF
                               AND   SCLAS = 'O'
                  INTO @LV_ORGEH.

    CHECK SY-SUBRC = 0.

    ME->GET_NODE_FROM_ORG_UNIT( EXPORTING IV_ORGEH = LV_ORGEH
                                          IV_ZZSECT = IV_ZZSECT
                                IMPORTING ES_DATA = ES_DATA ).

  ENDMETHOD.

* ---- YCL_HRFM_NODES_BL=============CM009 ----
  METHOD GET_CURRENT_C5_APPLICATION.

    SELECT SINGLE APPLI FROM YTFM_APPLI WHERE BEGDA <= @IV_DATE_REF
                                        AND   ENDDA >= @IV_DATE_REF
                                        AND   APLTY = 'C5'
                        INTO @RV_APPLI.

  ENDMETHOD.

* ---- YCL_HRFM_NODES_BL=============CO ----
PROTECTED SECTION.

* ---- YCL_HRFM_NODES_BL=============CU ----
CLASS YCL_HRFM_NODES_BL DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

PUBLIC SECTION.

  TYPES:
    BEGIN OF TY_NODES_DEF,
        CNODE     TYPE YTFM_CNODES-CNODE,
        CNODS     TYPE YTFM_CNODES_T-CNODS,
        CNODT     TYPE YTFM_CNODES_T-CNODT,
        DIS_ORDER TYPE YTFM_CNODES_A-DIS_ORDER,
        CNODE_UP  TYPE YTFM_CNODES_A-CNODE_UP,
        LEVEL     TYPE I,
      END OF TY_NODES_DEF .
  TYPES:
    TTY_NODES_DEF TYPE SORTED TABLE OF TY_NODES_DEF WITH UNIQUE KEY CNODE .
  TYPES:
    BEGIN OF TY_ORGEH_WITH_NODE,
        ORGEH  TYPE ORGEH,
        ZZSECT TYPE ZHR_SECT,
        CNODE  TYPE YE_FM_CNODE,
        SHORT  TYPE SHORT_D,
        STEXT  TYPE STEXT,
      END OF TY_ORGEH_WITH_NODE .
  TYPES:
    TTY_ORGEH_WITH_NODE TYPE SORTED TABLE OF TY_ORGEH_WITH_NODE WITH UNIQUE KEY ORGEH ZZSECT .

  CLASS-METHODS GET_CURRENT_C5_APPLICATION
    IMPORTING
      !IV_DATE_REF TYPE DATUM
    RETURNING
      VALUE(RV_APPLI) TYPE YE_FM_APPLICATION .
  METHODS GET_NODE_DEFINITION
    EXPORTING
      !ET_NODES_DEF TYPE TTY_NODES_DEF .
  METHODS GET_NODE_FROM_ORG_UNIT
    IMPORTING
      !IV_ORGEH TYPE ORGEH
      !IV_ZZSECT TYPE ZHR_SECT
    EXPORTING
      !ES_DATA TYPE TY_ORGEH_WITH_NODE .
  METHODS GET_NODE_FROM_POSITION
    IMPORTING
      !IV_PLANS TYPE PLANS
      !IV_ZZSECT TYPE ZHR_SECT
    EXPORTING
      !ES_DATA TYPE TY_ORGEH_WITH_NODE .
  METHODS GET_ORG_UNITS_WITH_NODE
    EXPORTING
      !ET_ORGEH_WITH_NODE TYPE TTY_ORGEH_WITH_NODE .
  METHODS CONSTRUCTOR
    IMPORTING
      !IV_APPLI TYPE YE_FM_APPLICATION
      !IV_DATE_REF TYPE DATUM .