* ==== CLASS POOL YCL_FI_COUPA_ACCOUNTING_LOAD ====
CLASS-POOL .
*"* class pool for class YCL_FI_COUPA_ACCOUNTING_LOAD

*"* local type definitions
INCLUDE YCL_FI_COUPA_ACCOUNTING_LOAD==CCDEF.

*"* class YCL_FI_COUPA_ACCOUNTING_LOAD definition
*"* public declarations
  INCLUDE YCL_FI_COUPA_ACCOUNTING_LOAD==CU.
*"* protected declarations
  INCLUDE YCL_FI_COUPA_ACCOUNTING_LOAD==CO.
*"* private declarations
  INCLUDE YCL_FI_COUPA_ACCOUNTING_LOAD==CI.
ENDCLASS. "YCL_FI_COUPA_ACCOUNTING_LOAD definition

*"* macro definitions
INCLUDE YCL_FI_COUPA_ACCOUNTING_LOAD==CCMAC.
*"* local class implementation
INCLUDE YCL_FI_COUPA_ACCOUNTING_LOAD==CCIMP.

CLASS YCL_FI_COUPA_ACCOUNTING_LOAD IMPLEMENTATION.
*"* method's implementations
  INCLUDE METHODS.
ENDCLASS. "YCL_FI_COUPA_ACCOUNTING_LOAD implementation


* ---- YCL_FI_COUPA_ACCOUNTING_LOAD==CI ----
PRIVATE SECTION.

  TYPES:
    BEGIN OF TY_COUPA_DATA,
      DATAFILE TYPE STRING,
      BIBLFILE TYPE STRING,
      STATUS   TYPE YE_FI_COUPA_STATUS,
      DATA     TYPE YTTFI_COUPA_FILE_DATA,
    END OF TY_COUPA_DATA .

  DATA MO_COUPA_DIS TYPE REF TO YCL_FI_COUPA_ACCOUNTING_DIS .
  DATA MV_PATH_AND_FILE_TEMPLATE TYPE STRING .
  DATA MS_BBKPF_NODATA TYPE BBKPF .
  CONSTANTS C_NODATA TYPE CHAR1 VALUE '/' ##NO_TEXT.
  DATA MV_TEST TYPE XFELD .
  CONSTANTS C_FILE_TEMPLATE TYPE TEXT80 VALUE 'COUPA_FILE_NAME' ##NO_TEXT.
  DATA MV_FILE_ORDER TYPE CHAR1 .
  DATA MV_SEPARATOR TYPE CHAR1 .
  DATA MV_WITH_HEADER_LINE TYPE XFELD .
  DATA:
    MT_COUPA_DATA TYPE TABLE OF TY_COUPA_DATA .
  DATA MS_BBSEG_NODATA TYPE BBSEG .

  METHODS EXECUTE_BTCI
    IMPORTING
      !IV_BDC_GROUP TYPE APQ_GRPN .
  METHODS FILE_ALREADY_LOADED
    IMPORTING
      !IV_FILE TYPE STRING
    RETURNING
      VALUE(RV_ALREADY_LOADED) TYPE XFELD .
  METHODS GET_PROCESSID
    RETURNING
      VALUE(RV_ID) TYPE NUM7 .
  METHODS MANAGE_RFBIBL00_PROTOCOL
    IMPORTING
      !IT_MESSAGE TYPE FB_T_FIMSG
      !IV_ERROR_RUN TYPE XFELD
      !IT_BIBL_FILE TYPE YTT_STRING
      !IS_RFBIBL_DATA TYPE YSFI_RFBIBL00_DATA
      !IV_DATAFILE TYPE STRING
    EXPORTING
      !EV_STATUS TYPE YE_FI_COUPA_STATUS .
  METHODS SET_RFBIBL00_FILE_NAME
    IMPORTING
      !IV_DATA_FILE TYPE STRING
    EXPORTING
      !EV_BIBL_FILE TYPE STRING
      !EV_BIBL_PATH_AND_FILE TYPE STRING .
  METHODS EXECUTE_RFBIBL00
    IMPORTING
      !IV_TEST_MODE TYPE XFELD DEFAULT ABAP_TRUE
      !IV_PATH_AND_FILE TYPE STRING .
  METHODS SET_RFBIBL00_SHARED_MEMORY .
  METHODS CONVERT_STRING_TO_DATE
    IMPORTING
      !IV_STRING TYPE STRING
    EXPORTING
      VALUE(EV_DATE_BI) TYPE DATUM_BI
      VALUE(EV_DATE) TYPE DATUM .
  METHODS DOWNLOAD_RFBIBL00_FILE
    IMPORTING
      !IS_RFBIBL00_DATA TYPE YSFI_RFBIBL00_DATA
      !IV_PATH_AND_FILE TYPE STRING
    RAISING
      YCX_FILE_ACCESS .
  METHODS FILL_BBKPF
    IMPORTING
      !IT_COUPA_DATA TYPE YTTFI_COUPA_FILE_DATA
    EXPORTING
      !ET_BBKPF_EXT TYPE YTTFI_BBKPF_EXT .
  METHODS FILL_BBSEG
    IMPORTING
      !IS_COUPA_DATA TYPE YSFI_COUPA_FILE_DATA
    EXPORTING
      !ET_BBSEG TYPE YTTFI_BBSEG .
  METHODS FILL_BGR00
    EXPORTING
      !ES_BGR00 TYPE BGR00
      !EV_PROCESSID TYPE NUM7 .
  METHODS READ_DATA_FROM_COUPA_FILE
    IMPORTING
      !IV_FILENAME TYPE STRING
    RETURNING
      VALUE(RT_DATA) TYPE YTTFI_COUPA_FILE_DATA
    RAISING
      YCX_FILE_ACCESS .
  METHODS GET_FILE_PATH
    IMPORTING
      !IV_LOGICAL_PATH TYPE PATHINTERN
      !IV_PHYSICAL_FILE TYPE TEXT80
    RETURNING
      VALUE(RV_PHYSICAL_PATH) TYPE STRING
    RAISING
      YCX_FILE_ACCESS .

* ---- YCL_FI_COUPA_ACCOUNTING_LOAD==CM001 ----
  METHOD LOAD_FILE.

    DATA LT_FILE_LIST TYPE EPS2FILIS.
    DATA LV_PATH_AND_FILE TYPE STRING.
    DATA LV_PATH TYPE STRING.
    DATA LS_COUPA_DATA TYPE TY_COUPA_DATA.
    DATA LT_FILE_DATA TYPE YTTFI_COUPA_FILE_DATA.

    CLEAR MT_COUPA_DATA.

    "Get directory for COUPA accounting files
    LV_PATH_AND_FILE = ME->GET_FILE_PATH( IV_LOGICAL_PATH = YIF_FI_COUPA_ACCOUNTING~C_PATH_DATA
                                          IV_PHYSICAL_FILE = C_FILE_TEMPLATE ).
    LV_PATH = LV_PATH_AND_FILE.
    REPLACE C_FILE_TEMPLATE IN LV_PATH WITH SPACE.

    "Get all files in the directory
    LT_FILE_LIST = YCL_BC_FILE_UTIL=>GET_DIRECTORY_FILES_LIST( IV_DIRECTORY = LV_PATH ).

    CASE MV_FILE_ORDER.
      WHEN 'D'.  "by date
        SORT LT_FILE_LIST BY MTIM.
      WHEN 'N'.  "by name
        SORT LT_FILE_LIST BY NAME.
    ENDCASE.

    LOOP AT LT_FILE_LIST INTO DATA(LS_FILE_LIST).
      CLEAR LS_COUPA_DATA.
      LV_PATH_AND_FILE = |{ LV_PATH }{ LS_FILE_LIST-NAME }|.
      LT_FILE_DATA = ME->READ_DATA_FROM_COUPA_FILE( IV_FILENAME = LV_PATH_AND_FILE ).
      LS_COUPA_DATA-DATAFILE = LS_FILE_LIST-NAME.
      LS_COUPA_DATA-DATA = LT_FILE_DATA.
      APPEND LS_COUPA_DATA TO MT_COUPA_DATA.
    ENDLOOP.

    DESCRIBE TABLE MT_COUPA_DATA LINES EV_NUMBER.

  ENDMETHOD.

* ---- YCL_FI_COUPA_ACCOUNTING_LOAD==CM002 ----
  METHOD CONSTRUCTOR.

    FIELD-SYMBOLS <LV_FIELD> TYPE ANY.

    MV_WITH_HEADER_LINE = IV_WITH_HEADER_LINE.
    MV_SEPARATOR = IV_SEPARATOR.
    MV_FILE_ORDER = IV_FILE_ORDER.
    MV_TEST = IV_TEST.

    "Init RFBIBL00 structures
    DO.
      ASSIGN COMPONENT SY-INDEX OF STRUCTURE MS_BBKPF_NODATA TO <LV_FIELD>.
      IF SY-SUBRC NE 0.
        EXIT.
      ELSE.
        <LV_FIELD> = C_NODATA.
      ENDIF.
    ENDDO.
    DO.
      ASSIGN COMPONENT SY-INDEX OF STRUCTURE MS_BBSEG_NODATA TO <LV_FIELD>.
      IF SY-SUBRC NE 0.
        EXIT.
      ELSE.
        <LV_FIELD> = C_NODATA.
      ENDIF.
    ENDDO.

    "Instance display class for COUPA
    MO_COUPA_DIS = NEW YCL_FI_COUPA_ACCOUNTING_DIS( ).

  ENDMETHOD.

* ---- YCL_FI_COUPA_ACCOUNTING_LOAD==CM003 ----
  METHOD GET_FILE_PATH.

    "Get directory for COUPA files
    CALL FUNCTION 'FILE_GET_NAME_USING_PATH'
      EXPORTING
*       CLIENT                     = SY-MANDT
        LOGICAL_PATH               = IV_LOGICAL_PATH
*       OPERATING_SYSTEM           = SY-OPSYS
        PARAMETER_1                = SY-SYSID
*       PARAMETER_2                = ' '
*       PARAMETER_3                = ' '
*       USE_BUFFER                 = ' '
        FILE_NAME                  = IV_PHYSICAL_FILE
*       USE_PRESENTATION_SERVER    = ' '
        ELEMINATE_BLANKS           = ' '
      IMPORTING
        FILE_NAME_WITH_PATH        = RV_PHYSICAL_PATH
      EXCEPTIONS
        PATH_NOT_FOUND             = 1
        MISSING_PARAMETER          = 2
        OPERATING_SYSTEM_NOT_FOUND = 3
        FILE_SYSTEM_NOT_FOUND      = 4
        OTHERS                     = 5.
    IF SY-SUBRC <> 0.
      RAISE EXCEPTION TYPE YCX_FILE_ACCESS
        EXPORTING
          TEXTID     = YCX_FILE_ACCESS=>PATH_ACCESS_ERROR
          PATH_NAME1 = IV_LOGICAL_PATH(50).
    ENDIF.

  ENDMETHOD.

* ---- YCL_FI_COUPA_ACCOUNTING_LOAD==CM004 ----
  METHOD READ_DATA_FROM_COUPA_FILE.

    DATA LV_STRING TYPE STRING.
    DATA LS_DATA TYPE LINE OF YTTFI_COUPA_FILE_DATA.
    DATA LV_FILE TYPE FILENAME_AL11.

    CLEAR RT_DATA.
    LV_FILE = IV_FILENAME.

    "Open source file
    OPEN DATASET LV_FILE FOR INPUT IN TEXT MODE ENCODING DEFAULT.
    IF SY-SUBRC <> 0.
      RAISE EXCEPTION TYPE YCX_FILE_ACCESS
        EXPORTING
          TEXTID     = YCX_FILE_ACCESS=>FILE_ACCESS_ERROR
          FILE_NAME1 = LV_FILE(50)
          FILE_NAME2 = LV_FILE+50(50)
          FILE_NAME3 = LV_FILE+100(50)
          FILE_NAME4 = LV_FILE+150(50).
    ENDIF.

    "Load source file
    DO.
      READ DATASET LV_FILE INTO LV_STRING.
      IF SY-SUBRC <> 0.
        EXIT.
      ENDIF.
      IF SY-INDEX = 1 AND MV_WITH_HEADER_LINE = ABAP_TRUE.
        CONTINUE.
      ENDIF.
      SPLIT LV_STRING AT MV_SEPARATOR INTO LS_DATA-VOUCHER_NO
                                           LS_DATA-ENTITY
                                           LS_DATA-COMPANY_CODE
                                           LS_DATA-DATA_TYPE
                                           LS_DATA-DEAL_TYPES
                                           LS_DATA-NUMBERS
                                           LS_DATA-DIRECTION
                                           LS_DATA-FLOW
                                           LS_DATA-TYPES
                                           LS_DATA-AMOUNT
                                           LS_DATA-CURRENCY
                                           LS_DATA-DATE_FROM
                                           LS_DATA-DATE_TO
                                           LS_DATA-VALUE_DATE
                                           LS_DATA-COUNTERPARTY
                                           LS_DATA-ADD_TEXT
                                           LS_DATA-DEBIT_ACCOUNT
                                           LS_DATA-CREDIT_ACCOUNT.
      APPEND LS_DATA TO RT_DATA.
    ENDDO.

    CLOSE DATASET LV_FILE.

  ENDMETHOD.

* ---- YCL_FI_COUPA_ACCOUNTING_LOAD==CM005 ----
  METHOD GENERATE_RFBIBL00_FILE.

    DATA LS_RFBIBL TYPE YSFI_RFBIBL00_DATA.
    DATA LV_PATH_AND_FILE TYPE STRING.

    DATA LO_AREA TYPE REF TO YCL_FI_RFBIBL00_SHM_AREA.
    DATA LO_ROOT TYPE REF TO YCL_FI_RFBIBL00_SHM_ROOT.
    DATA LO_EXC TYPE REF TO CX_SHM_EXTERNAL_REFERENCE.

    DATA LT_MESSAGE TYPE FB_T_FIMSG.
    DATA LV_ERROR_RUN TYPE XFELD.
    DATA LT_BIBL_FILE_ERROR TYPE YTT_STRING.
    DATA LV_FILE TYPE FILENAME_AL11.

    CLEAR: YIF_FI_COUPA_ACCOUNTING~MT_LIST, YIF_FI_COUPA_ACCOUNTING~MT_PROTOCOL.

    CHECK MT_COUPA_DATA IS NOT INITIAL.

    "Get File path for RFBIBL00 files
    MV_PATH_AND_FILE_TEMPLATE = ME->GET_FILE_PATH( IV_LOGICAL_PATH = YIF_FI_COUPA_ACCOUNTING~C_PATH_PROCESS
                                                   IV_PHYSICAL_FILE = C_FILE_TEMPLATE ).

    "Set to shared memory with RFBIBL00
    TRY.
        LO_AREA = YCL_FI_RFBIBL00_SHM_AREA=>ATTACH_FOR_WRITE( ).
        CREATE OBJECT LO_ROOT AREA HANDLE LO_AREA.
        LO_AREA->SET_ROOT( LO_ROOT ).
        LO_ROOT->SET_SHARED_MEMORY( IV_GET_PROTOCOL = ABAP_TRUE ).
        LO_AREA->DETACH_COMMIT( ).
      CATCH CX_ROOT.
        MESSAGE 'Error set shared memory' TYPE 'I'.
    ENDTRY.

    LOOP AT MT_COUPA_DATA ASSIGNING FIELD-SYMBOL(<LS_COUPA_DATA>).
      CHECK ME->FILE_ALREADY_LOADED( IV_FILE = <LS_COUPA_DATA>-DATAFILE ) = ABAP_FALSE.
      "Prepare data for RFBIBL00
      CLEAR: LS_RFBIBL, LV_PATH_AND_FILE, LT_MESSAGE, LV_ERROR_RUN.
      ME->FILL_BGR00( IMPORTING ES_BGR00 = LS_RFBIBL-BGR00
                                EV_PROCESSID = LS_RFBIBL-PROCESSID ).
      ME->FILL_BBKPF( EXPORTING IT_COUPA_DATA = <LS_COUPA_DATA>-DATA
                      IMPORTING ET_BBKPF_EXT = LS_RFBIBL-BBKPF_T ).
      "Set RFBIBL00 file
      ME->SET_RFBIBL00_FILE_NAME( EXPORTING IV_DATA_FILE = <LS_COUPA_DATA>-DATAFILE
                                  IMPORTING EV_BIBL_FILE = <LS_COUPA_DATA>-BIBLFILE
                                            EV_BIBL_PATH_AND_FILE = LV_PATH_AND_FILE ).
      "Download RFBIBL00 file
      ME->DOWNLOAD_RFBIBL00_FILE( EXPORTING IS_RFBIBL00_DATA = LS_RFBIBL
                                            IV_PATH_AND_FILE = LV_PATH_AND_FILE ).
      "Execute RFBIBL00
      ME->EXECUTE_RFBIBL00( EXPORTING IV_TEST_MODE = MV_TEST
                                      IV_PATH_AND_FILE = LV_PATH_AND_FILE ).
      TRY.
          LO_AREA = YCL_FI_RFBIBL00_SHM_AREA=>ATTACH_FOR_READ( ).
        CATCH CX_ROOT.
      ENDTRY.
      LO_AREA->ROOT->GET_SHARED_MEMORY( IMPORTING ET_MESSAGE = LT_MESSAGE
                                                  EV_ERROR_RUN = LV_ERROR_RUN
                                                  ET_BIBL_FILE = LT_BIBL_FILE_ERROR ).
      LO_AREA->DETACH( ).
      "Execute BTCI

      "Manage G/L posting result
      ME->MANAGE_RFBIBL00_PROTOCOL( EXPORTING IT_MESSAGE = LT_MESSAGE
                                              IV_ERROR_RUN = LV_ERROR_RUN
                                              IT_BIBL_FILE = LT_BIBL_FILE_ERROR
                                              IS_RFBIBL_DATA = LS_RFBIBL
                                              IV_DATAFILE = <LS_COUPA_DATA>-DATAFILE
                                    IMPORTING EV_STATUS = <LS_COUPA_DATA>-STATUS ).
      IF MV_TEST = ABAP_FALSE.
        "Execute Batch-input
        ME->EXECUTE_BTCI( IV_BDC_GROUP = LS_RFBIBL-BGR00-GROUP ).
        "Move file to archive or error folder
        TRY.
            LV_FILE = <LS_COUPA_DATA>-DATAFILE.
            MO_COUPA_DIS->MOVE_FILE( IV_FILE = LV_FILE
                                     IV_STATUS_AFTER = <LS_COUPA_DATA>-STATUS ).
          CATCH YCX_FILE_ACCESS.
            MESSAGE S040(YCOMMON).
        ENDTRY.
      ENDIF.
    ENDLOOP.

    "Free shared memory
    YCL_FI_RFBIBL00_SHM_AREA=>FREE_INSTANCE( ).

  ENDMETHOD.

* ---- YCL_FI_COUPA_ACCOUNTING_LOAD==CM006 ----
  METHOD FILL_BGR00.

    DATA LV_NUM TYPE NUM7.

    CLEAR ES_BGR00.
    ES_BGR00-STYPE = '0'.
    ES_BGR00-MANDT = SY-MANDT.
    ES_BGR00-USNAM = SY-UNAME.
    "es_bgr00-start = sy-datum.
    ES_BGR00-NODATA = C_NODATA.
    "Get id for batch-input name
    EV_PROCESSID = ME->GET_PROCESSID( ).

    ES_BGR00-GROUP = |COUPA{ EV_PROCESSID }|.
    ES_BGR00-XKEEP = ABAP_TRUE.

  ENDMETHOD.

* ---- YCL_FI_COUPA_ACCOUNTING_LOAD==CM007 ----
  METHOD FILL_BBKPF.

    DATA LS_BBKPF_EXT TYPE LINE OF YTTFI_BBKPF_EXT.
    DATA LV_BUDAT TYPE DATUM.

    LOOP AT IT_COUPA_DATA INTO DATA(LS_COUPA_DATA).
      CLEAR: LS_BBKPF_EXT, LV_BUDAT.
      "Set nodata values
      LS_BBKPF_EXT-BBKPF = MS_BBKPF_NODATA.
      "Fill header
      LS_BBKPF_EXT-BBKPF-STYPE = '1'.
      LS_BBKPF_EXT-BBKPF-TCODE = 'FB01'.
      ME->CONVERT_STRING_TO_DATE( EXPORTING IV_STRING = LS_COUPA_DATA-VALUE_DATE
                                  IMPORTING EV_DATE_BI = LS_BBKPF_EXT-BBKPF-BUDAT
                                            EV_DATE = LV_BUDAT ).
      LS_BBKPF_EXT-BBKPF-BLDAT = LS_BBKPF_EXT-BBKPF-BUDAT.
      IF LS_COUPA_DATA-DEAL_TYPES = 'FX'.
        LS_BBKPF_EXT-BBKPF-BLART = 'TO'.
      ELSE.
        LS_BBKPF_EXT-BBKPF-BLART = 'TD'.
      ENDIF.
      LS_BBKPF_EXT-BBKPF-BUKRS = LS_COUPA_DATA-COMPANY_CODE.
      LS_BBKPF_EXT-BBKPF-WAERS = LS_COUPA_DATA-CURRENCY.
      LS_BBKPF_EXT-BBKPF-XBLNR = LS_BBKPF_EXT-BBKPF-BKTXT = LS_COUPA_DATA-TYPES.
      "Fill items

***20/22/2025 Change Conversion date for reversal JP_LOPEZ,
      IF LS_COUPA_DATA-TYPES = 'GL Posting Reversal' AND LV_BUDAT IS NOT INITIAL.
        LV_BUDAT = LV_BUDAT - 1.
        LS_BBKPF_EXT-BBKPF-WWERT = |{ LV_BUDAT+6(2) }{ LV_BUDAT+4(2) }{ LV_BUDAT(4) }|.
      ENDIF.
***end change *20/22/2025 JP_LOPEZ

      ME->FILL_BBSEG( EXPORTING IS_COUPA_DATA = LS_COUPA_DATA
                      IMPORTING ET_BBSEG = LS_BBKPF_EXT-BBSEG_T ).
      APPEND LS_BBKPF_EXT TO ET_BBKPF_EXT.
    ENDLOOP.

  ENDMETHOD.

* ---- YCL_FI_COUPA_ACCOUNTING_LOAD==CM008 ----
  METHOD CONVERT_STRING_TO_DATE.

    DATA LV_DATE_IN(10) TYPE C.
    DATA LV_DATE TYPE DATUM.

    CLEAR: EV_DATE_BI, EV_DATE.

    LV_DATE_IN = IV_STRING.
    LV_DATE(4) = LV_DATE_IN+6(4).
    LV_DATE+4(2) = LV_DATE_IN+3(2).
    LV_DATE+6(2) = LV_DATE_IN(2).

    "Check if date is correct
    CALL FUNCTION 'DATE_CHECK_PLAUSIBILITY'
      EXPORTING
        DATE                      = LV_DATE
      EXCEPTIONS
        PLAUSIBILITY_CHECK_FAILED = 1
        OTHERS                    = 2.
    IF SY-SUBRC = 0.
      EV_DATE_BI(2) = LV_DATE+6(2).
      EV_DATE_BI+2(2) = LV_DATE+4(2).
      EV_DATE_BI+4(4) = LV_DATE(4).
      EV_DATE = LV_DATE.
    ENDIF.

  ENDMETHOD.

* ---- YCL_FI_COUPA_ACCOUNTING_LOAD==CM009 ----
  METHOD FILL_BBSEG.

    DATA LS_BBSEG TYPE LINE OF YTTFI_BBSEG.
    DATA LV_AMOUNT TYPE BSEG-WRBTR.

    CLEAR ET_BBSEG.

    "Set nodata values
    LS_BBSEG = MS_BBSEG_NODATA.
    LS_BBSEG-STYPE = '2'.
    LS_BBSEG-TBNAM = 'BBSEG'.
    IF IS_COUPA_DATA-DEAL_TYPES = 'FX'.
      LS_BBSEG-ZUONR = |{ IS_COUPA_DATA-DEAL_TYPES }-{ IS_COUPA_DATA-NUMBERS }|.
    ELSE.
      LS_BBSEG-ZUONR = IS_COUPA_DATA-NUMBERS.
    ENDIF.
    LV_AMOUNT = IS_COUPA_DATA-AMOUNT.
    WRITE LV_AMOUNT TO LS_BBSEG-WRBTR.
    LS_BBSEG-SGTXT = |{ IS_COUPA_DATA-ENTITY } { IS_COUPA_DATA-DEAL_TYPES } { IS_COUPA_DATA-TYPES } { IS_COUPA_DATA-COUNTERPARTY }|.
    "ls_bbseg-valut = me->convert_string_to_date( is_coupa_data-value_date ).
    LS_BBSEG-GSBER = IS_COUPA_DATA-ADD_TEXT.
    "ls_bbseg-hkont = is_coupa_data-debit_account.
    LS_BBSEG-NEWKO = IS_COUPA_DATA-DEBIT_ACCOUNT.
    LS_BBSEG-NEWBS = '40'.
    APPEND LS_BBSEG TO ET_BBSEG.
    LS_BBSEG-NEWKO = IS_COUPA_DATA-CREDIT_ACCOUNT.
    LS_BBSEG-NEWBS = '50'.
    APPEND LS_BBSEG TO ET_BBSEG.

  ENDMETHOD.

* ---- YCL_FI_COUPA_ACCOUNTING_LOAD==CM00A ----
  METHOD DOWNLOAD_RFBIBL00_FILE.

    DATA LV_FILE TYPE FILENAME_AL11.

    LV_FILE = IV_PATH_AND_FILE.

    "Create file
    OPEN DATASET LV_FILE FOR OUTPUT IN TEXT MODE ENCODING DEFAULT.
    IF SY-SUBRC <> 0.
      RAISE EXCEPTION TYPE YCX_FILE_ACCESS
        EXPORTING
          TEXTID     = YCX_FILE_ACCESS=>FILE_CREATE_ERROR
          FILE_NAME1 = LV_FILE(50)
          FILE_NAME2 = LV_FILE+50(50)
          FILE_NAME3 = LV_FILE+100(50)
          FILE_NAME4 = LV_FILE+150(50).
    ENDIF.

    "Transfer data to file
    TRANSFER IS_RFBIBL00_DATA-BGR00 TO LV_FILE.
    LOOP AT IS_RFBIBL00_DATA-BBKPF_T INTO DATA(LS_BBKPF).
      TRANSFER LS_BBKPF-BBKPF TO LV_FILE.
      LOOP AT LS_BBKPF-BBSEG_T INTO DATA(LS_BBSEG).
        TRANSFER LS_BBSEG TO LV_FILE.
      ENDLOOP.
    ENDLOOP.

    CLOSE DATASET LV_FILE.

  ENDMETHOD.

* ---- YCL_FI_COUPA_ACCOUNTING_LOAD==CM00B ----
  METHOD EXECUTE_RFBIBL00.

    SUBMIT RFBIBL00 WITH DS_NAME = IV_PATH_AND_FILE
                    WITH FL_CHECK = IV_TEST_MODE
                    WITH CALLMODE = 'B'
                    WITH PA_XPROT = ABAP_TRUE
                    WITH XLOG = ABAP_TRUE
                    AND RETURN.

  ENDMETHOD.

* ---- YCL_FI_COUPA_ACCOUNTING_LOAD==CM00C ----
  METHOD SET_RFBIBL00_SHARED_MEMORY.

    DATA LO_AREA TYPE REF TO YCL_FI_RFBIBL00_SHM_AREA.
    DATA LO_ROOT TYPE REF TO YCL_FI_RFBIBL00_SHM_ROOT.
    DATA LO_EXC TYPE REF TO CX_SHM_EXTERNAL_REFERENCE.

    TRY.
        LO_AREA = YCL_FI_RFBIBL00_SHM_AREA=>ATTACH_FOR_WRITE( ).
        CREATE OBJECT LO_ROOT AREA HANDLE LO_AREA.
        LO_AREA->SET_ROOT( LO_ROOT ).
        LO_ROOT->SET_SHARED_MEMORY( IV_GET_PROTOCOL = ABAP_TRUE ).
        LO_AREA->DETACH_COMMIT( ).
        "CATCH cx_shm_external_reference INTO lo_exc.
      CATCH CX_ROOT.
        MESSAGE 'Error set shared memory' TYPE 'I'.
    ENDTRY.

  ENDMETHOD.

* ---- YCL_FI_COUPA_ACCOUNTING_LOAD==CM00D ----
  METHOD SET_RFBIBL00_FILE_NAME.

    DATA LV_FILE TYPE FILENAME_AL11.
    DATA LT_RESULT TYPE MATCH_RESULT_TAB.
    DATA LV_PATH_AND_FILE TYPE STRING.

    LV_FILE = IV_DATA_FILE.
    FIND ALL OCCURRENCES OF '.' IN LV_FILE RESULTS LT_RESULT.
    LOOP AT LT_RESULT INTO DATA(LS_RESULT).
    ENDLOOP.
    IF SY-SUBRC = 0.
      CLEAR LV_FILE+LS_RESULT-OFFSET.
    ENDIF.
    EV_BIBL_FILE = |{ LV_FILE }_BIBL.txt|.
    EV_BIBL_PATH_AND_FILE = MV_PATH_AND_FILE_TEMPLATE.
    REPLACE C_FILE_TEMPLATE IN EV_BIBL_PATH_AND_FILE WITH EV_BIBL_FILE.

  ENDMETHOD.

* ---- YCL_FI_COUPA_ACCOUNTING_LOAD==CM00E ----
  METHOD MANAGE_RFBIBL00_PROTOCOL.

    TYPES: BEGIN OF LTY_APQI,
             GROUPID  TYPE APQI-GROUPID,
             QID      TYPE APQI-QID,
             TRANSCNT TYPE APQI-TRANSCNT,
           END OF LTY_APQI.

    DATA LT_APQI TYPE TABLE OF LTY_APQI.
    DATA LS_APPL_FUP TYPE YTBC_APPL_FUP.
    DATA LS_APPL_PROT TYPE YTBC_APPL_PROT.
    DATA LS_LIST TYPE YIF_FI_COUPA_ACCOUNTING~TY_LIST.
    DATA LS_PROTOCOL TYPE YIF_FI_COUPA_ACCOUNTING~TY_PROTOCOL.

    EV_STATUS = YIF_FI_COUPA_ACCOUNTING~C_STATUS_OK.

    "Prepare data to store in DB table YTBC_APPL_FUP
    LS_APPL_FUP-YAPPL = YIF_FI_COUPA_ACCOUNTING~C_APPL_COUPA.
    LS_APPL_FUP-APPL_KEY = |{ SY-DATUM }{ SY-UZEIT }_{ IS_RFBIBL_DATA-PROCESSID }|.
    LS_APPL_FUP-ERDAT = SY-DATUM.
    LS_APPL_FUP-ERTIM = SY-UZEIT.
    LS_APPL_FUP-ERNAM = SY-UNAME.
    LS_APPL_FUP-FILENAME = IV_DATAFILE.

    "First check if error in RFBIBL00 file structure
    READ TABLE IT_MESSAGE TRANSPORTING NO FIELDS WITH KEY MSGID = 'FB'
                                                          MSGNO = '013'.
    IF SY-SUBRC = 0.
      "Error in RFBIBL00 file structure
      EV_STATUS = YIF_FI_COUPA_ACCOUNTING~C_STATUS_KO_RFBIBL_FILE.
    ELSEIF IV_ERROR_RUN = ABAP_TRUE OR IT_BIBL_FILE IS NOT INITIAL.  "Error during posting generation for direct input or call transaction
      EV_STATUS = YIF_FI_COUPA_ACCOUNTING~C_STATUS_KO_POSTING.
    ELSE.
      READ TABLE IT_MESSAGE TRANSPORTING NO FIELDS WITH KEY MSGTY = 'E'.  "Other error
      IF SY-SUBRC = 0.
        EV_STATUS = YIF_FI_COUPA_ACCOUNTING~C_STATUS_KO_OTHERS.
      ELSE.
        IF MV_TEST = ABAP_FALSE.
          EV_STATUS = YIF_FI_COUPA_ACCOUNTING~C_STATUS_IN_PROCESS.
        ENDIF.
      ENDIF.
    ENDIF.

    LS_APPL_FUP-STATUS = EV_STATUS.

    "Check if batch-input with erros has been generated
    SELECT GROUPID, QID, TRANSCNT FROM APQI WHERE DESTSYS = @SPACE
                                            AND   DESTAPP = @SPACE
                                            AND   DATATYP = 'BDC'
                                            AND   MANDANT = @SY-MANDT
                                            AND   GROUPID = @IS_RFBIBL_DATA-BGR00-GROUP
                                            AND   PROGID = 'RFBIBL01'
                                       ORDER BY QID DESCENDING
                                       INTO TABLE @LT_APQI.
    READ TABLE LT_APQI INTO DATA(LS_APQI) INDEX 1.
    IF SY-SUBRC = 0.
      LS_APPL_FUP-BDC_GROUP = LS_APQI-GROUPID.
      LS_APPL_FUP-BDC_QID = LS_APQI-QID.
      LS_APPL_FUP-TRTOT = LS_APQI-TRANSCNT.
    ELSE.
      "Get number of transaction
      DESCRIBE TABLE IS_RFBIBL_DATA-BBKPF_T LINES LS_APPL_FUP-TRTOT.
    ENDIF.

    "Set to list
    MOVE-CORRESPONDING LS_APPL_FUP TO LS_LIST.
    APPEND LS_LIST TO YIF_FI_COUPA_ACCOUNTING~MT_LIST.

    IF MV_TEST = ABAP_FALSE.
      "Insert into follow up table
      INSERT YTBC_APPL_FUP FROM LS_APPL_FUP.
    ENDIF.

    "Insert into protocol table
    LS_APPL_PROT-YAPPL = LS_APPL_FUP-YAPPL.
    LS_APPL_PROT-APPL_KEY = LS_APPL_FUP-APPL_KEY.
    LOOP AT IT_MESSAGE INTO DATA(LS_MESSAGE).
      ADD 1 TO LS_APPL_PROT-SEQNR.
      MOVE-CORRESPONDING LS_MESSAGE TO LS_APPL_PROT.
      MOVE-CORRESPONDING LS_APPL_PROT TO LS_PROTOCOL.
      APPEND LS_PROTOCOL TO YIF_FI_COUPA_ACCOUNTING~MT_PROTOCOL.
      IF MV_TEST = ABAP_FALSE.
        INSERT YTBC_APPL_PROT FROM LS_APPL_PROT.
      ENDIF.
    ENDLOOP.

  ENDMETHOD.

* ---- YCL_FI_COUPA_ACCOUNTING_LOAD==CM00F ----
  METHOD DISPLAY_PROTOCOL.

    MO_COUPA_DIS->YIF_FI_COUPA_ACCOUNTING~MT_LIST = YIF_FI_COUPA_ACCOUNTING~MT_LIST.
    MO_COUPA_DIS->YIF_FI_COUPA_ACCOUNTING~MT_PROTOCOL = YIF_FI_COUPA_ACCOUNTING~MT_PROTOCOL.
    MO_COUPA_DIS->COMPLETE_DATA( ).
    MO_COUPA_DIS->DISPLAY_ALV( IV_REPID = IV_REPID ).

  ENDMETHOD.

* ---- YCL_FI_COUPA_ACCOUNTING_LOAD==CM00G ----
  METHOD SEND_PROTOCOL_BY_MAIL.

    DATA LT_APPL_KEY TYPE RANGE OF YE_BC_APPLICATION_KEY.
    DATA LV_JOBNUMBER TYPE TBTCJOB-JOBCOUNT.
    DATA LV_PRINT_PARAMETERS TYPE PRI_PARAMS.
    DATA LV_JOBNAME TYPE TBTCJOB-JOBNAME VALUE 'YCOUPA_POSTING_MAIL'.
    DATA LV_START_DATE TYPE DATUM.
    DATA LV_START_TIME TYPE UZEIT.
    DATA LV_UZEIT TYPE UZEIT.

    CHECK MV_TEST = ABAP_FALSE AND IT_MAIL_ADDRESS IS NOT INITIAL.

    LOOP AT YIF_FI_COUPA_ACCOUNTING~MT_LIST INTO DATA(LS_LIST).
      IF IV_ONLY_ERROR = ABAP_TRUE.
        CHECK LS_LIST-STATUS > YIF_FI_COUPA_ACCOUNTING~C_STATUS_OK.
      ENDIF.
      APPEND VALUE #( SIGN = 'I' OPTION = 'EQ' LOW = LS_LIST-APPL_KEY ) TO LT_APPL_KEY.
    ENDLOOP.

    CHECK LT_APPL_KEY IS NOT INITIAL.

    "Generate Job for mail
    CALL FUNCTION 'JOB_OPEN'
      EXPORTING
*       DELANFREP        = ' '
*       JOBGROUP         = ' '
        JOBNAME          = LV_JOBNAME
*       SDLSTRTDT        = NO_DATE
*       SDLSTRTTM        = NO_TIME
*       JOBCLASS         =
*       CHECK_JOBCLASS   =
      IMPORTING
        JOBCOUNT         = LV_JOBNUMBER
*       INFO             =
*   CHANGING
*       RET              =
      EXCEPTIONS
        CANT_CREATE_JOB  = 1
        INVALID_JOB_DATA = 2
        JOBNAME_MISSING  = 3
        OTHERS           = 4.
    CHECK SY-SUBRC = 0.

    SUBMIT YFI_COUPA_POSTING_FILE_MAIL WITH S_APKEY IN LT_APPL_KEY
                                       WITH S_MAIL IN IT_MAIL_ADDRESS
                                       WITH P_ERROR = IV_ONLY_ERROR
                       USER 'JOBBATCH' VIA JOB LV_JOBNAME NUMBER LV_JOBNUMBER
                       AND RETURN.

    "Set start date and time
    LV_START_DATE = SY-DATUM.
    LV_UZEIT = SY-UZEIT.
    LV_START_TIME = LV_UZEIT + ( IV_DELAY * 60 ).
    IF LV_START_TIME < LV_UZEIT.
      ADD 1 TO LV_START_DATE.
    ENDIF.

    CALL FUNCTION 'JOB_CLOSE'
      EXPORTING
        JOBCOUNT             = LV_JOBNUMBER
        JOBNAME              = LV_JOBNAME
        SDLSTRTDT            = LV_START_DATE
        SDLSTRTTM            = LV_START_TIME
      EXCEPTIONS
        CANT_START_IMMEDIATE = 1
        INVALID_STARTDATE    = 2
        JOBNAME_MISSING      = 3
        JOB_CLOSE_FAILED     = 4
        JOB_NOSTEPS          = 5
        JOB_NOTEX            = 6
        LOCK_FAILED          = 7
        INVALID_TARGET       = 8
        OTHERS               = 9.

  ENDMETHOD.

* ---- YCL_FI_COUPA_ACCOUNTING_LOAD==CM00H ----
  METHOD FILE_ALREADY_LOADED.

    DATA LS_APPL_FUP TYPE YTBC_APPL_FUP.
    DATA LS_LIST TYPE YIF_FI_COUPA_ACCOUNTING~TY_LIST.
    DATA LV_FILE TYPE FILENAME_AL11.

    RV_ALREADY_LOADED = ABAP_FALSE.
    SELECT SINGLE * FROM YTBC_APPL_FUP WHERE YAPPL = @YIF_FI_COUPA_ACCOUNTING~C_APPL_COUPA
                                       AND   FILENAME = @IV_FILE
                                 INTO @LS_APPL_FUP.
    CHECK SY-SUBRC = 0.
    RV_ALREADY_LOADED = ABAP_TRUE.
    CLEAR LS_APPL_FUP.
    LS_APPL_FUP-YAPPL = YIF_FI_COUPA_ACCOUNTING~C_APPL_COUPA.
    LS_APPL_FUP-APPL_KEY = |{ SY-DATUM }{ SY-UZEIT }_{ ME->GET_PROCESSID( ) }|.
    LS_APPL_FUP-ERDAT = SY-DATUM.
    LS_APPL_FUP-ERTIM = SY-UZEIT.
    LS_APPL_FUP-ERNAM = SY-UNAME.
    LS_APPL_FUP-FILENAME = IV_FILE.
    LS_APPL_FUP-STATUS = YIF_FI_COUPA_ACCOUNTING~C_STATUS_KO_FILE_EXISTS.
    "Set to list
    MOVE-CORRESPONDING LS_APPL_FUP TO LS_LIST.
    APPEND LS_LIST TO YIF_FI_COUPA_ACCOUNTING~MT_LIST.

    IF MV_TEST = ABAP_FALSE.
      "Insert into follow up table
      INSERT YTBC_APPL_FUP FROM LS_APPL_FUP.
      "Move file
      TRY.
          LV_FILE = IV_FILE.
          MO_COUPA_DIS->MOVE_FILE( IV_FILE = LV_FILE
                                   IV_STATUS_AFTER = YIF_FI_COUPA_ACCOUNTING~C_STATUS_KO_FILE_EXISTS ).
        CATCH YCX_FILE_ACCESS.
      ENDTRY.
    ENDIF.

  ENDMETHOD.

* ---- YCL_FI_COUPA_ACCOUNTING_LOAD==CM00I ----
  METHOD GET_PROCESSID.

    IF MV_TEST = ABAP_TRUE.
      RV_ID = 0.
    ELSE.
      CALL FUNCTION 'NUMBER_GET_NEXT'
        EXPORTING
          NR_RANGE_NR             = '01'
          OBJECT                  = 'YCOUPAPOST'
*         QUANTITY                = '1'
*         SUBOBJECT               = ' '
*         TOYEAR                  = '0000'
*         IGNORE_BUFFER           = ' '
        IMPORTING
          NUMBER                  = RV_ID
*         QUANTITY                =
*         RETURNCODE              =
        EXCEPTIONS
          INTERVAL_NOT_FOUND      = 1
          NUMBER_RANGE_NOT_INTERN = 2
          OBJECT_NOT_FOUND        = 3
          QUANTITY_IS_0           = 4
          QUANTITY_IS_NOT_1       = 5
          INTERVAL_OVERFLOW       = 6
          BUFFER_OVERFLOW         = 7
          OTHERS                  = 8.
    ENDIF.

  ENDMETHOD.

* ---- YCL_FI_COUPA_ACCOUNTING_LOAD==CM00J ----
  METHOD EXECUTE_BTCI.

    CHECK IV_BDC_GROUP IS NOT INITIAL.

    SUBMIT RSBDCSUB WITH MAPPE = IV_BDC_GROUP
                    WITH Z_VERARB = ABAP_TRUE
                    WITH FEHLER = ABAP_FALSE
                    WITH LOGALL = ABAP_TRUE
                    EXPORTING LIST TO MEMORY
                    AND RETURN.

    "Clear list in memory
    CALL FUNCTION 'LIST_FREE_MEMORY'.

  ENDMETHOD.

* ---- YCL_FI_COUPA_ACCOUNTING_LOAD==CM00K ----
  METHOD REFRESH_STATUS_AND_MOVE_FILE.

    DATA LT_STATUS TYPE RANGE OF YE_BC_GENERIC_STATUS.

    "Check all enties with non OK status
    LT_STATUS = VALUE #( ( SIGN = 'E' OPTION = 'EQ' LOW = '0' ) ).

    MO_COUPA_DIS->GET_DATA( IV_APPL = 'COUPA_POST'
                            IV_BEGDA = '19000101'
                            IV_ENDDA = '99991231'
                            IT_STATUS = LT_STATUS ).

    CLEAR: MO_COUPA_DIS->YIF_FI_COUPA_ACCOUNTING~MT_LIST, MO_COUPA_DIS->YIF_FI_COUPA_ACCOUNTING~MT_PROTOCOL.

  ENDMETHOD.

* ---- YCL_FI_COUPA_ACCOUNTING_LOAD==CO ----
PROTECTED SECTION.

* ---- YCL_FI_COUPA_ACCOUNTING_LOAD==CU ----
CLASS YCL_FI_COUPA_ACCOUNTING_LOAD DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

PUBLIC SECTION.

  INTERFACES YIF_FI_COUPA_ACCOUNTING .

  METHODS REFRESH_STATUS_AND_MOVE_FILE .
  METHODS SEND_PROTOCOL_BY_MAIL
    IMPORTING
      !IT_MAIL_ADDRESS TYPE YIF_FI_COUPA_ACCOUNTING=>TTY_EMAIL_RANGE
      !IV_ONLY_ERROR TYPE XFELD
      !IV_DELAY TYPE INT1 DEFAULT 60 .
  METHODS DISPLAY_PROTOCOL
    IMPORTING
      !IV_REPID TYPE SY-REPID .
  METHODS GENERATE_RFBIBL00_FILE
    RAISING
      YCX_FILE_ACCESS .
  METHODS CONSTRUCTOR
    IMPORTING
      !IV_WITH_HEADER_LINE TYPE XFELD DEFAULT ABAP_TRUE
      !IV_SEPARATOR TYPE CHAR1 DEFAULT ','
      !IV_FILE_ORDER TYPE CHAR1 DEFAULT 'D'
      !IV_TEST TYPE XFELD DEFAULT ABAP_TRUE .
  METHODS LOAD_FILE
    EXPORTING
      !EV_NUMBER TYPE INT2
    RAISING
      YCX_FILE_ACCESS .