* ==== CLASS POOL YCL_IM__FI_VENDOR_MR ====
CLASS-POOL .
*"* class pool for class YCL_IM__FI_VENDOR_MR

*"* local classes
INCLUDE YCL_IM__FI_VENDOR_MR==========CL.

*"* class YCL_IM__FI_VENDOR_MR definition
*"* public declarations
  INCLUDE YCL_IM__FI_VENDOR_MR==========CU.
*"* protected declarations
  INCLUDE YCL_IM__FI_VENDOR_MR==========CO.
*"* private declarations
  INCLUDE YCL_IM__FI_VENDOR_MR==========CI.
ENDCLASS. "YCL_IM__FI_VENDOR_MR definition

CLASS YCL_IM__FI_VENDOR_MR IMPLEMENTATION.
*"* method's implementations
  INCLUDE METHODS.
ENDCLASS. "YCL_IM__FI_VENDOR_MR implementation


* ---- YCL_IM__FI_VENDOR_MR==========CI ----
*"* private components of class YCL_IM__FI_VENDOR_MR
*"* do not include other source files here!!!
PRIVATE SECTION.

* ---- YCL_IM__FI_VENDOR_MR==========CM001 ----
METHOD IF_EX_VENDOR_ADD_DATA_CS~SET_DATA.

DATA: W_LFBK TYPE FLFBK.

CLEAR W_LFBK.
LOOP AT T_LFBK INTO W_LFBK WHERE BKREF <> SPACE.
ENDLOOP. "T_LFBK

CALL FUNCTION 'Y_FI_VENDOR_EXTZ1_SETDATA'
  EXPORTING
    I_LIFNR = I_LFA1-LIFNR
    I_KTOKK = I_LFA1-KTOKK
    I_UNESDIR = I_LFA1-YYUNESDIR
    I_NATIO = I_LFA1-YYNATIO
    I_FFCRTO = W_LFBK-YYFFCRTO
    I_SDATE = I_LFA1-YYSDATE
    I_EDATE = I_LFA1-YYEDATE
    I_AUFNR = I_LFA1-YYAUFNR.

ENDMETHOD.

* ---- YCL_IM__FI_VENDOR_MR==========CM002 ----
METHOD IF_EX_VENDOR_ADD_DATA_CS~GET_DATA.

DATA: W_LFBK TYPE FLFBK,
      W_FFCRTO TYPE FLFBK-YYFFCRTO.

CALL FUNCTION 'Y_FI_VENDOR_EXTZ1_GETDATA'
  IMPORTING
    E_UNESDIR = S_LFA1-YYUNESDIR
    E_NATIO = S_LFA1-YYNATIO
    E_FFCRTO = W_FFCRTO
    E_SDATE = S_LFA1-YYSDATE
    E_EDATE = S_LFA1-YYEDATE
    E_AUFNR = S_LFA1-YYAUFNR.

CLEAR W_LFBK.
LOOP AT T_LFBK INTO W_LFBK WHERE BKREF <> SPACE.
  W_LFBK-YYFFCRTO = W_FFCRTO.
  MODIFY T_LFBK FROM W_LFBK.
ENDLOOP. "T_LFBK

ENDMETHOD.

* ---- YCL_IM__FI_VENDOR_MR==========CM003 ----
METHOD IF_EX_VENDOR_ADD_DATA_CS~GET_FIELDNAME_FOR_CHANGEDOC.
ENDMETHOD.

* ---- YCL_IM__FI_VENDOR_MR==========CM004 ----
METHOD IF_EX_VENDOR_ADD_DATA_CS~SUPPRESS_TAXI_TABSTRIPS.
ENDMETHOD.

* ---- YCL_IM__FI_VENDOR_MR==========CM005 ----
METHOD IF_EX_VENDOR_ADD_DATA_CS~GET_TAXI_SCREEN.
  CASE I_TAXI_FCODE.
    WHEN 'Z1UN01'.
      IF SY-TCODE = 'XK03' OR SY-TCODE = 'FK03'.
        E_SCREEN  = '0300'.
       ELSE.
         E_SCREEN  = '0100'.
      ENDIF.
      E_PROGRAM = 'SAPLYFI_VENDOR_MR'.
      E_HEADERSCREEN_LAYOUT = ' '.
    WHEN OTHERS.
  ENDCASE.
ENDMETHOD.

* ---- YCL_IM__FI_VENDOR_MR==========CM006 ----
METHOD IF_EX_VENDOR_ADD_DATA_CS~SET_FCODE.
ENDMETHOD.

* ---- YCL_IM__FI_VENDOR_MR==========CO ----
*"* protected components of class YCL_IM__FI_VENDOR_MR
*"* do not include other source files here!!!
PROTECTED SECTION.

* ---- YCL_IM__FI_VENDOR_MR==========CU ----
CLASS YCL_IM__FI_VENDOR_MR DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

*"* public components of class YCL_IM__FI_VENDOR_MR
*"* do not include other source files here!!!
PUBLIC SECTION.

  INTERFACES IF_BADI_INTERFACE .
  INTERFACES IF_EX_VENDOR_ADD_DATA_CS .