* ==== CLASS POOL YCL_FM_BR_POSTING_IN_FM_BL ====
CLASS-POOL .
*"* class pool for class YCL_FM_BR_POSTING_IN_FM_BL

*"* local type definitions
INCLUDE YCL_FM_BR_POSTING_IN_FM_BL====CCDEF.

*"* class YCL_FM_BR_POSTING_IN_FM_BL definition
*"* public declarations
  INCLUDE YCL_FM_BR_POSTING_IN_FM_BL====CU.
*"* protected declarations
  INCLUDE YCL_FM_BR_POSTING_IN_FM_BL====CO.
*"* private declarations
  INCLUDE YCL_FM_BR_POSTING_IN_FM_BL====CI.
ENDCLASS. "YCL_FM_BR_POSTING_IN_FM_BL definition

*"* macro definitions
INCLUDE YCL_FM_BR_POSTING_IN_FM_BL====CCMAC.
*"* local class implementation
INCLUDE YCL_FM_BR_POSTING_IN_FM_BL====CCIMP.

CLASS YCL_FM_BR_POSTING_IN_FM_BL IMPLEMENTATION.
*"* method's implementations
  INCLUDE METHODS.
ENDCLASS. "YCL_FM_BR_POSTING_IN_FM_BL implementation


* ---- YCL_FM_BR_POSTING_IN_FM_BL====CI ----
PRIVATE SECTION.

  TYPES:
    BEGIN OF TY_BSEG_BR,
      PERNR  TYPE BSEG-PERNR,
      AWKEY  TYPE BKPF-AWKEY,
      BUZEI  TYPE BSEG-BUZEI,
      SHKZG  TYPE BSEG-SHKZG,
      DMBTR  TYPE BSEG-DMBTR,
      HWAER  TYPE BKPF-HWAER,
      WRBTR  TYPE BSEG-WRBTR,
      WAERS  TYPE BKPF-WAERS,
      BUKRS  TYPE BKPF-BUKRS,
      BLDAT  TYPE BKPF-BLDAT,
      BUDAT  TYPE BKPF-BUDAT,
      FIPOS  TYPE BSEG-FIPOS,
      FISTL  TYPE BSEG-FISTL,
      GEBER  TYPE BSEG-GEBER,
      GSBER  TYPE BSEG-GSBER,
      HKONT  TYPE BSEG-HKONT,
      KOSTL  TYPE BSEG-KOSTL,
      PROJK  TYPE BSEG-PROJK,
      DOCNUM TYPE PPDIT-DOCNUM,
      DOCLIN TYPE PPDIT-DOCLIN,
    END OF TY_BSEG_BR .
  TYPES:
    BEGIN OF TY_BSEG_DIST,
      BUKRS TYPE BKPF-BUKRS,
      BELNR TYPE BKPF-BELNR,
      GJAHR TYPE BKPF-GJAHR,
      BLDAT TYPE BKPF-BLDAT,
      BUDAT TYPE BKPF-BUDAT,
      AWKEY TYPE BKPF-AWKEY,
      BUZEI TYPE BSEG-BUZEI,
      SHKZG TYPE BSEG-SHKZG,
      DMBTR TYPE BSEG-DMBTR,
      HWAER TYPE BKPF-HWAER,
      WRBTR TYPE BSEG-WRBTR,
      WAERS TYPE BKPF-WAERS,
      KURSF TYPE BKPF-KURSF,
      PERNR TYPE BSEG-PERNR,
      GSBER TYPE BSEG-GSBER,
      HKONT TYPE BSEG-HKONT,
      FIPOS TYPE BSEG-FIPOS,
      FIKRS TYPE BKPF-FIKRS,
      FISTL TYPE BSEG-FISTL,
      GEBER TYPE BSEG-GEBER,
      KOSTL TYPE BSEG-KOSTL,
      PROJK TYPE BSEG-PROJK,
    END OF TY_BSEG_DIST .
  TYPES:
    BEGIN OF TY_DOC_LINES_EXT.
      INCLUDE TYPE YCL_FI_TO_PAYROLL_POSTING_BL=>TY_DOC_LINES.
      TYPES: AWKEY TYPE BKPF-AWKEY,
      BUZEI TYPE BSEG-BUZEI,
    END OF TY_DOC_LINES_EXT .
  TYPES:
    TTY_POST_ITEM TYPE SORTED TABLE OF TY_POST_ITEM WITH UNIQUE KEY FIPOS FISTL GEBER GSBER SAKNR KOSTL PTEXT .
  TYPES:
    BEGIN OF TY_POST,
      HEAD TYPE TY_POST_HEAD,
      ITEM TYPE TTY_POST_ITEM,
    END OF TY_POST .
  TYPES:
    BEGIN OF TY_PERNR_CONSOLIDATION,
      PERNR      TYPE P_PERNR,
      BETRG_999S TYPE WERTV9,
      BETRG_DIST TYPE WERTV9,
    END OF TY_PERNR_CONSOLIDATION .
  TYPES:
    BEGIN OF TY_PERNR_COST,
      PERNR TYPE BSEG-PERNR,
      BUKRS TYPE BKPF-BUKRS,
      GSBER TYPE BSEG-GSBER,
      HKONT TYPE BSEG-HKONT,
      FIKRS TYPE BKPF-FIKRS,
      FISTL TYPE BSEG-FISTL,
      GEBER TYPE BSEG-GEBER,
      KOSTL TYPE BSEG-KOSTL,
      PROJK TYPE BSEG-PROJK,
      HWAER TYPE BKPF-HWAER,
      DMBTR TYPE WERTV9,
    END OF TY_PERNR_COST .
  TYPES:
    BEGIN OF TY_BSEG_FOR_POST,
      BUKRS  TYPE BSEG-BUKRS,
      HWAER  TYPE BKPF-HWAER,
      KTEXT  TYPE FMR_INTERFACE_HEAD-KTEXT,
      FIPOS  TYPE BSEG-FIPOS,
      FISTL  TYPE BSEG-FISTL,
      GEBER  TYPE BSEG-GEBER,
      GSBER  TYPE BSEG-GSBER,
      HKONT  TYPE BSEG-HKONT,
      KOSTL  TYPE BSEG-KOSTL,
      PROJK  TYPE BSEG-PROJK,
      AMOUNT TYPE WERTV9,
    END OF TY_BSEG_FOR_POST .
  TYPES:
    BEGIN OF TY_PERNR_FIPOS,
           PERNR  TYPE BSEG-PERNR,
           FIPOS  TYPE BSEG-FIPOS,
           AMOUNT TYPE WERTV9,
         END OF TY_PERNR_FIPOS .

  CLASS-DATA MV_BLDAT TYPE BLDAT .
  CLASS-DATA MV_BUDAT TYPE BUDAT .
  CLASS-DATA MV_FIKRS TYPE FIKRS .
  CLASS-DATA MT_FIPOS_PC TYPE HRPP_SEL_FIPOS .
  CLASS-DATA:
    MT_DOC_LINES_EXT TYPE TABLE OF TY_DOC_LINES_EXT .
  CLASS-DATA MT_PPDIT_PPDIX TYPE YCL_FI_TO_PAYROLL_POSTING_BL=>TTY_PPDIT_PPDIX .
  CLASS-DATA:
    MT_BSEG_BR TYPE TABLE OF TY_BSEG_BR .
  CLASS-DATA:
    MT_BSEG_DIST TYPE TABLE OF TY_BSEG_DIST .
  CLASS-DATA:
    MT_POST TYPE SORTED TABLE OF TY_POST WITH UNIQUE KEY HEAD-BLART HEAD-BLTYP HEAD-BUKRS HEAD-BLDAT HEAD-BUDAT HEAD-WAERS .
  CLASS-DATA:
    MT_BR_PERNR TYPE TABLE OF YTFM_BR_PAYPER .

  CLASS-METHODS PUT_CUMUL_BY_PERNR
    IMPORTING
      !IV_RUNID TYPE P_EVNUM OPTIONAL .
  CLASS-METHODS PUT_TO_POST_TABLE
    IMPORTING
      !IS_DATA TYPE TY_BSEG_FOR_POST .
  CLASS-METHODS UNLOCK_RUNID
    IMPORTING
      !IV_RUNID TYPE P_EVNUM .
  CLASS-METHODS LOCK_RUNID
    IMPORTING
      !IV_RUNID TYPE P_EVNUM .
  CLASS-METHODS UPDATE_POSTING_STATUS
    IMPORTING
      !IV_RUNID TYPE P_EVNUM .
  CLASS-METHODS CONSOLIDATE_DISTRIBUTION
    CHANGING
      !CS_LIST TYPE YTFM_BR_PAYPER .
  CLASS-METHODS GET_FIPOS_PC
    IMPORTING
      !IV_FIKRS TYPE FIKRS
    RETURNING
      VALUE(RT_FIPOS_PC) TYPE HRPP_SEL_FIPOS .
  CLASS-METHODS GET_DIST_FI_POSTING .
  CLASS-METHODS CHECK_RUNID
    IMPORTING
      !IV_RUNID TYPE P_EVNUM
    RETURNING
      VALUE(RV_IS_OK) TYPE XFELD .
  CLASS-METHODS GET_BR_FI_POSTING
    IMPORTING
      !IV_RUNID TYPE P_EVNUM
      !IT_PERNR TYPE YTTHR_PERNR_RANGE .
  CLASS-METHODS READ_PPDIX
    IMPORTING
      !IV_RUNID TYPE P_EVNUM .

* ---- YCL_FM_BR_POSTING_IN_FM_BL====CM001 ----
  METHOD CHECK_RUNID.

    DATA LV_STATUS TYPE PEVSH-STATUS.
    DATA LV_SIMU TYPE PEVST-SIMU.


    "Check status
    CALL FUNCTION 'HR_EVAL_STATUS_GET'
      EXPORTING
        TYPE          = 'PP'
        RUNID         = IV_RUNID
*       LOCK          = ' '
      IMPORTING
        STATUS        = LV_STATUS
*       NAME          =
        SIMU          = LV_SIMU
*       CREATOR       =
*       CREADATE      =
*       CREATIME      =
      EXCEPTIONS
        RUN_NOT_FOUND = 1
        RUN_LOCKED    = 2
        OTHERS        = 3.
    IF SY-SUBRC <> 0 OR LV_STATUS <> '50' OR LV_SIMU = ABAP_TRUE.
      RV_IS_OK = ABAP_FALSE.
    ELSE.
      RV_IS_OK = ABAP_TRUE.
    ENDIF.

    CHECK RV_IS_OK = ABAP_TRUE.

    "Check FM Br difference posting has not been executed yet
    SELECT SINGLE FM_BR_DIFF INTO @DATA(LV_BR_FM_DIFF) FROM YTHR_PEVST WHERE TYPE = 'PP'
                                                                       AND   RUNID = @IV_RUNID.
    IF SY-SUBRC = 0 AND LV_BR_FM_DIFF IS NOT INITIAL.
      RV_IS_OK = ABAP_FALSE.
    ENDIF.

    "Get posting date and document
    SELECT SINGLE BUDAT, BLDAT FROM PPDHD WHERE EVTYP = 'PP'
                                          AND   RUNID = @IV_RUNID
                               INTO ( @MV_BUDAT, @MV_BLDAT ).

  ENDMETHOD.

* ---- YCL_FM_BR_POSTING_IN_FM_BL====CM002 ----
  METHOD GET_BR_FI_POSTING.

    DATA LV_BKTXT TYPE BKPF-BKTXT.
    DATA LT_CUSD_FIPEX TYPE RANGE OF FM_FIPEX .


    CLEAR MT_BSEG_BR.

    LT_CUSD_FIPEX = VALUE #( ( SIGN = 'I' OPTION = 'EQ' LOW = 'CDCE' )
                             ( SIGN = 'I' OPTION = 'EQ' LOW = 'CDSP' ) ).

    LV_BKTXT = |PP{ IV_RUNID }|.

    SELECT S~PERNR,
           K~AWKEY,
           S~BUZEI,
           S~SHKZG,
           S~DMBTR,
           K~HWAER,
           S~WRBTR,
           K~WAERS,
           K~BUKRS,
           K~BLDAT,
           K~BUDAT,
           S~FIPOS,
           S~FISTL,
           S~GEBER,
           S~GSBER,
           S~HKONT,
           S~KOSTL,
           S~PROJK,
           CAST( K~AWKEY AS NUMC( 10 ) ) AS DOCNUM,
           S~BUZEI AS DOCLIN
           FROM BKPF AS K
           INNER JOIN BSEG AS S ON  S~BUKRS = K~BUKRS
                                AND S~BELNR = K~BELNR
                                AND S~GJAHR = K~GJAHR
           WHERE K~BKTXT = @LV_BKTXT
           AND   K~AWTYP = 'HRPAY'
           AND   S~FIPOS IN @LT_CUSD_FIPEX
           AND   S~PERNR IN @IT_PERNR
           INTO TABLE @MT_BSEG_BR.

  ENDMETHOD.

* ---- YCL_FM_BR_POSTING_IN_FM_BL====CM003 ----
  METHOD READ_PPDIX.

    CLEAR MT_PPDIT_PPDIX.

    SELECT X~DOCNUM,
           X~DOCLIN,
           T~PERNR,
           X~RUNID,
           X~LINUM
           FROM PPDIX AS X LEFT OUTER JOIN PPDIT AS T ON  T~DOCNUM = X~DOCNUM
                                                      AND T~DOCLIN = X~DOCLIN
           FOR ALL ENTRIES IN @MT_BSEG_BR
           WHERE X~EVTYP = 'PP'
           AND   X~RUNID = @IV_RUNID
           AND   X~DOCNUM = @MT_BSEG_BR-DOCNUM
           AND   X~DOCLIN = @MT_BSEG_BR-DOCLIN
           INTO CORRESPONDING FIELDS OF TABLE @MT_PPDIT_PPDIX.

    "Get Commitment item
    LOOP AT MT_PPDIT_PPDIX ASSIGNING FIELD-SYMBOL(<LS_PPDIT_PPDIX>).
      READ TABLE MT_BSEG_BR INTO DATA(LS_BSEG_BR) WITH KEY DOCNUM = <LS_PPDIT_PPDIX>-DOCNUM
                                                           DOCLIN = <LS_PPDIT_PPDIX>-DOCLIN.
      IF SY-SUBRC = 0.
        <LS_PPDIT_PPDIX>-FIPOS = LS_BSEG_BR-FIPOS.
      ENDIF.
    ENDLOOP.

  ENDMETHOD.

* ---- YCL_FM_BR_POSTING_IN_FM_BL====CM004 ----
  METHOD GET_DIST_FI_POSTING.

    CHECK MT_DOC_LINES_EXT IS NOT INITIAL.

    SELECT K~BUKRS,
           K~BELNR,
           K~GJAHR,
           K~BLDAT,
           K~BUDAT,
           K~AWKEY,
           S~BUZEI,
           S~SHKZG,
           S~DMBTR,
           K~HWAER,
           S~WRBTR,
           K~WAERS,
           K~KURSF,
           S~PERNR,
           S~GSBER,
           S~HKONT,
           S~FIPOS,
           K~FIKRS,
           S~FISTL,
           S~GEBER,
           S~KOSTL,
           S~PROJK
           FROM BKPF AS K
           INNER JOIN BSEG AS S ON  S~BUKRS = K~BUKRS
                                AND S~BELNR = K~BELNR
                                AND S~GJAHR = K~GJAHR
           FOR ALL ENTRIES IN @MT_DOC_LINES_EXT
           WHERE K~AWTYP = 'HRPAY'
           AND   K~AWKEY = @MT_DOC_LINES_EXT-AWKEY
           AND   S~BUZEI = @MT_DOC_LINES_EXT-BUZEI
           INTO TABLE @MT_BSEG_DIST.

    "Filter on Personnel cost only
    LOOP AT MT_BSEG_DIST INTO DATA(LS_BSEG_DIST).
      IF LS_BSEG_DIST-FIPOS NOT IN GET_FIPOS_PC( LS_BSEG_DIST-FIKRS ).
        DELETE MT_BSEG_DIST.
      ENDIF.
    ENDLOOP.

  ENDMETHOD.

* ---- YCL_FM_BR_POSTING_IN_FM_BL====CM005 ----
  METHOD PREPARE_DATA_FROM_RUNID.

    DATA LT_DOC_LINES TYPE YCL_FI_TO_PAYROLL_POSTING_BL=>TTY_DOC_LINES.
    DATA LS_DOC_LINES_EXT TYPE TY_DOC_LINES_EXT.

    "Check runid
    IF CHECK_RUNID( IV_RUNID ) = ABAP_FALSE.
      APPEND YCL_CA_UTILITIES=>SET_TO_BAPIRET2( IV_MSGID = 'YFM1'
                                                IV_MSGNO = '025'
                                                IV_MSGTY = 'E'
                                                IV_MSGV1 = |{ IV_RUNID }| ) TO ET_RETURN.
      EXIT.
    ENDIF.

    "Get BR difference posting in FI for the runid
    GET_BR_FI_POSTING( IV_RUNID = IV_RUNID
                       IT_PERNR = IT_PERNR ).
    IF MT_BSEG_BR IS INITIAL.
      APPEND YCL_CA_UTILITIES=>SET_TO_BAPIRET2( IV_MSGID = 'YFM1'
                                                IV_MSGNO = '026'
                                                IV_MSGTY = 'E'
                                                IV_MSGV1 = |{ IV_RUNID }| ) TO ET_RETURN.
      EXIT.
    ENDIF.

    "Get Payroll posting references
    READ_PPDIX( IV_RUNID ).
    IF MT_PPDIT_PPDIX IS INITIAL.
      APPEND YCL_CA_UTILITIES=>SET_TO_BAPIRET2( IV_MSGID = 'YFM1'
                                                IV_MSGNO = '026'
                                                IV_MSGTY = 'E'
                                                IV_MSGV1 = |{ IV_RUNID }| ) TO ET_RETURN.
      EXIT.
    ENDIF.

    "build ditribution of fixed rate impact
    YCL_FI_TO_PAYROLL_POSTING_BL=>BUILD_FX_DISTRIBUTION( EXPORTING IT_PPDIT_PPDIX = MT_PPDIT_PPDIX
                                                         IMPORTING ET_DOC_LINES = LT_DOC_LINES ).

    "Extend doc lines with Fi document numbers
    CLEAR MT_DOC_LINES_EXT.
    LOOP AT LT_DOC_LINES INTO DATA(LS_DOC_LINES).
      MOVE-CORRESPONDING LS_DOC_LINES TO LS_DOC_LINES_EXT.
      LS_DOC_LINES_EXT-AWKEY = LS_DOC_LINES-DOCNUM.
      LS_DOC_LINES_EXT-BUZEI = LS_DOC_LINES-DOCLIN.
      APPEND LS_DOC_LINES_EXT TO MT_DOC_LINES_EXT.
    ENDLOOP.

    "Get FI posting from distribution
    GET_DIST_FI_POSTING( ).

  ENDMETHOD.

* ---- YCL_FM_BR_POSTING_IN_FM_BL====CM006 ----
  METHOD CHECK_DISTRIBUTION.

    DATA LS_LIST TYPE TY_LIST_PERNR.
    DATA LV_ECART TYPE P DECIMALS 2.
    DATA LT_TOL1 TYPE RANGE OF YE_CA_DEC_3_2_S.
    DATA LT_TOL2 TYPE RANGE OF YE_CA_DEC_3_2_S.
    DATA LV_TOLERANCE_N TYPE YE_CA_DEC_3_2_S.

    "Set Tolerance
    LV_TOLERANCE_N = - IV_TOLERANCE.
    APPEND VALUE #( SIGN = 'I' OPTION = 'BT' LOW = LV_TOLERANCE_N HIGH = IV_TOLERANCE ) TO LT_TOL1.
    LV_TOLERANCE_N = LV_TOLERANCE_N * 2.
    IV_TOLERANCE = IV_TOLERANCE * 2.
    APPEND VALUE #( SIGN = 'I' OPTION = 'BT' LOW = LV_TOLERANCE_N HIGH = IV_TOLERANCE ) TO LT_TOL2.

    PUT_CUMUL_BY_PERNR( ).

    LOOP AT MT_BR_PERNR INTO DATA(LS_BR_PERNR).
      MOVE-CORRESPONDING LS_BR_PERNR TO LS_LIST.
      LV_ECART = LS_LIST-DMBTR_9 + LS_LIST-DMBTR_D.
      IF LV_ECART IN LT_TOL1.
        WRITE ICON_GREEN_LIGHT TO LS_LIST-STATUS AS ICON.
      ELSEIF LV_ECART IN LT_TOL2.
        WRITE ICON_YELLOW_LIGHT TO LS_LIST-STATUS AS ICON.
      ELSE.
        WRITE ICON_RED_LIGHT TO LS_LIST-STATUS AS ICON.
      ENDIF.
      APPEND LS_LIST TO MT_LIST_PERNR.
    ENDLOOP.

  ENDMETHOD.

* ---- YCL_FM_BR_POSTING_IN_FM_BL====CM007 ----
  METHOD GET_FIPOS_PC.

    IF IV_FIKRS <> MV_FIKRS.
      MV_FIKRS = IV_FIKRS.
      SELECT 'I', 'EQ', FIPEX AS LOW FROM FMCI WHERE FIKRS = @IV_FIKRS
                                               AND   GJAHR = '0000'
                                               AND   ( FIPEX = 'PC' OR FIPUP = 'PC' )
                                      INTO TABLE @MT_FIPOS_PC.
    ENDIF.

    RT_FIPOS_PC = MT_FIPOS_PC.

  ENDMETHOD.

* ---- YCL_FM_BR_POSTING_IN_FM_BL====CM008 ----
  METHOD CONSOLIDATE_DISTRIBUTION.

    DATA LV_AMOUNT TYPE MAXBT."TYPE p DECIMALS 5.
    DATA LV_AMOUNT_CUMUL TYPE MAXBT. "TYPE p DECIMALS 5.

    LOOP AT MT_BSEG_DIST INTO DATA(LS_BSEG_DIST) WHERE PERNR = CS_LIST-PERNR.
      "Get the corresponding distribution
      READ TABLE MT_DOC_LINES_EXT INTO DATA(LS_DOC_LINES) WITH KEY AWKEY = LS_BSEG_DIST-AWKEY
                                                                   BUZEI = LS_BSEG_DIST-BUZEI.
      IF SY-SUBRC = 0.
        LS_DOC_LINES-BETRG_9 = - LS_DOC_LINES-BETRG_9.
        ADD LS_DOC_LINES-BETRG_9 TO CS_LIST-WRBTR_D.
        CS_LIST-WAERS_D = LS_DOC_LINES-WAERS_9.
        IF LS_DOC_LINES-WAERS_O = LS_BSEG_DIST-HWAER.   "All in USD
          ADD LS_DOC_LINES-BETRG_9 TO LV_AMOUNT_CUMUL.
          CS_LIST-HWAER_D = LS_DOC_LINES-WAERS_9.
        ELSE.  "Distribution in EUR
          IF LS_BSEG_DIST-KURSF < 0.
            LV_AMOUNT = LS_DOC_LINES-BETRG_9 / ( - LS_BSEG_DIST-KURSF ).
          ELSE.
            LV_AMOUNT = LS_DOC_LINES-BETRG_9 * LS_BSEG_DIST-KURSF.
          ENDIF.
          ADD LV_AMOUNT TO LV_AMOUNT_CUMUL.
          CS_LIST-HWAER_D = LS_BSEG_DIST-HWAER.
        ENDIF.
      ENDIF.

    ENDLOOP.

    IF SY-SUBRC = 0.
      CS_LIST-DMBTR_D = LV_AMOUNT_CUMUL.
    ENDIF.

  ENDMETHOD.

* ---- YCL_FM_BR_POSTING_IN_FM_BL====CM009 ----
  METHOD POST.

    DATA LS_FM_HEAD TYPE FMR_INTERFACE_HEAD.
    DATA LT_FM_ITEM TYPE TABLE OF FMR_INTERFACE_DET.
    DATA LS_FM_ITEM TYPE FMR_INTERFACE_DET.
    DATA LV_ERROR TYPE XFELD.
    DATA LS_LIST_POST_EXE TYPE TY_LIST_POST_EXE.
    DATA LV_AMOUNT TYPE WERTV9.
    DATA LS_BR_PAYPH TYPE YTFM_BR_PAYPH.
    DATA LS_BR_PAYPI TYPE YTFM_BR_PAYPI.
    DATA LT_BR_PAYPI TYPE TABLE OF YTFM_BR_PAYPI.
    DATA LV_PITEM TYPE YTFM_BR_PAYPI-PITEM.

    IF IV_MODE_TEST = ABAP_FALSE.
      LOCK_RUNID( IV_RUNID ).
    ENDIF.

    LOOP AT MT_POST INTO DATA(LS_POST).
      CLEAR: LS_FM_HEAD, LS_FM_ITEM, LT_FM_ITEM, LS_LIST_POST_EXE, LV_AMOUNT,
             LS_BR_PAYPH, LS_BR_PAYPI, LT_BR_PAYPI, LV_PITEM.
      "For FM posting
      MOVE-CORRESPONDING LS_POST-HEAD TO LS_FM_HEAD.
      "For BR posting
      MOVE-CORRESPONDING LS_POST-HEAD TO LS_BR_PAYPH.
      LS_BR_PAYPH-RUNID = IV_RUNID.

      LOOP AT LS_POST-ITEM INTO DATA(LS_ITEM).
        CHECK LS_ITEM-WRBTR <> 0.
        "For FM posting
        MOVE-CORRESPONDING LS_ITEM TO LS_FM_ITEM.
        APPEND LS_FM_ITEM TO LT_FM_ITEM.
        "For BR posting
        MOVE-CORRESPONDING LS_POST-HEAD TO LS_BR_PAYPI.
        MOVE-CORRESPONDING LS_ITEM TO LS_BR_PAYPI.
        ADD 1 TO LV_PITEM.
        LS_BR_PAYPI-RUNID = IV_RUNID.
        LS_BR_PAYPI-PITEM = LV_PITEM.
        APPEND LS_BR_PAYPI TO LT_BR_PAYPI.

        ADD LS_FM_ITEM-WRBTR TO LV_AMOUNT.
      ENDLOOP.

      CHECK LT_FM_ITEM IS NOT INITIAL.
      MOVE-CORRESPONDING LS_FM_HEAD TO LS_LIST_POST_EXE.
      LS_LIST_POST_EXE-BETRG = LV_AMOUNT.

      "Post in FM
      IF IV_FM_POST = ABAP_TRUE.
        CALL FUNCTION 'FMFR_CREATE_FROM_DATA'
          EXPORTING
            I_FLG_CHECKONLY     = IV_MODE_TEST
            I_FLG_COMMIT        = ABAP_FALSE
          TABLES
            T_POSDATA           = LT_FM_ITEM
          CHANGING
            C_F_HEADDATA        = LS_FM_HEAD
          EXCEPTIONS
            DOCTYPE_NOT_ALLOWED = 1
            ERROR_OCCURED       = 2
            OTHERS              = 3.
        IF SY-SUBRC = 0.
          WRITE ICON_LED_GREEN TO LS_LIST_POST_EXE-STATUS_FM AS ICON.
          LS_LIST_POST_EXE-BELNR = LS_FM_HEAD-BELNR.
        ELSE.
          WRITE ICON_LED_RED TO LS_LIST_POST_EXE-STATUS_FM AS ICON.
          LV_ERROR = ABAP_TRUE.
        ENDIF.
      ENDIF.

      "Set to BR tables
      IF IV_BR_POST = ABAP_TRUE.
        INSERT YTFM_BR_PAYPH FROM LS_BR_PAYPH.
        IF SY-SUBRC = 0.
          INSERT YTFM_BR_PAYPI FROM TABLE LT_BR_PAYPI.
        ENDIF.
        IF SY-SUBRC = 0.
          WRITE ICON_CHECKED TO LS_LIST_POST_EXE-STATUS_BR AS ICON.
        ELSE.
          LV_ERROR = ABAP_TRUE.
          WRITE ICON_INCOMPLETE TO LS_LIST_POST_EXE-STATUS_BR AS ICON.
        ENDIF.
      ENDIF.

      APPEND LS_LIST_POST_EXE TO MT_LIST_POST_EXE.

    ENDLOOP.

    IF IV_MODE_TEST = ABAP_FALSE.
      IF LV_ERROR = ABAP_FALSE.
        IF IV_BR_POST = ABAP_TRUE.
          PUT_CUMUL_BY_PERNR( IV_RUNID ).
          IF MT_BR_PERNR IS NOT INITIAL.
            INSERT YTFM_BR_PAYPER FROM TABLE MT_BR_PERNR.
          ENDIF.
        ENDIF.
        UPDATE_POSTING_STATUS( IV_RUNID ).
        COMMIT WORK.
      ELSE.
        ROLLBACK WORK.
      ENDIF.
      UNLOCK_RUNID( IV_RUNID ).
    ELSE.
      ROLLBACK WORK.
    ENDIF.

  ENDMETHOD.

* ---- YCL_FM_BR_POSTING_IN_FM_BL====CM00A ----
  METHOD PREPARE_DATA_FOR_POSTING.

    DATA LV_AKPER TYPE PEVAT-VALUE.
    DATA LV_AMOUNT_9 TYPE MAXBT.
    DATA LT_PERNR_CONSOLIDATION TYPE TABLE OF TY_PERNR_CONSOLIDATION.
    DATA LS_PERNR_CONSOLIDATION TYPE TY_PERNR_CONSOLIDATION.
    DATA LT_PERNR_COST TYPE TABLE OF TY_PERNR_COST.
    DATA LS_PERNR_COST TYPE TY_PERNR_COST.
    DATA LS_BSEG_FOR_POST TYPE TY_BSEG_FOR_POST.
    DATA LT_PERNR_FIPOS TYPE TABLE OF TY_PERNR_FIPOS.
    DATA LS_PERNR_FIPOS TYPE TY_PERNR_FIPOS.

    CLEAR: MT_POST.

    "Get runid period
    SELECT SINGLE VALUE FROM PEVAT WHERE TYPE = 'PP'
                                   AND   RUNID = @IV_RUNID
                                   AND   ATTR = 'AKPER'
                        INTO @LV_AKPER.

    """""Set data for adjustment document (i.e. Fixed rate impact in account 999999x)
    SORT MT_BSEG_BR.

    LOOP AT MT_BSEG_BR INTO DATA(LS_BSEG_BR).

      CASE LS_BSEG_BR-SHKZG.
        WHEN 'S'.
          LV_AMOUNT_9 = - LS_BSEG_BR-DMBTR.
        WHEN 'H'.
          LV_AMOUNT_9 = LS_BSEG_BR-DMBTR.
      ENDCASE.

      CLEAR LS_BSEG_FOR_POST.
      MOVE-CORRESPONDING LS_BSEG_BR TO LS_BSEG_FOR_POST.
      LS_BSEG_FOR_POST-AMOUNT = LV_AMOUNT_9.
      LS_BSEG_FOR_POST-KTEXT =  |Payroll posting run { IV_RUNID } { LV_AKPER }|.

      "collect posting
      PUT_TO_POST_TABLE( IS_DATA = LS_BSEG_FOR_POST ).

      "Consolidate by personnel number
      LS_PERNR_CONSOLIDATION-PERNR = LS_BSEG_BR-PERNR.
      LS_PERNR_CONSOLIDATION-BETRG_999S = LV_AMOUNT_9.
      LS_PERNR_CONSOLIDATION-BETRG_DIST = 0.
      COLLECT LS_PERNR_CONSOLIDATION INTO LT_PERNR_CONSOLIDATION.

      LS_PERNR_FIPOS-PERNR = LS_BSEG_BR-PERNR.
      LS_PERNR_FIPOS-FIPOS = LS_BSEG_BR-FIPOS.
      LS_PERNR_FIPOS-AMOUNT = LV_AMOUNT_9.
      COLLECT LS_PERNR_FIPOS INTO LT_PERNR_FIPOS.

    ENDLOOP.

    """"""Set data for distribution document
    LOOP AT MT_BSEG_DIST INTO DATA(LS_BSEG_DIST).
      "Get the corresponding distribution
      READ TABLE MT_DOC_LINES_EXT INTO DATA(LS_DOC_LINES) WITH KEY AWKEY = LS_BSEG_DIST-AWKEY
                                                                   BUZEI = LS_BSEG_DIST-BUZEI.
      IF SY-SUBRC = 0.

        LV_AMOUNT_9 = - LS_DOC_LINES-BETRG_9.

        "Do conversion if necessary
        IF LS_DOC_LINES-WAERS_9 <> LS_BSEG_DIST-HWAER.
          IF LS_BSEG_DIST-KURSF < 0.
            LV_AMOUNT_9 = LV_AMOUNT_9 / ( - LS_BSEG_DIST-KURSF ).
          ELSE.
            LV_AMOUNT_9 = LV_AMOUNT_9 * LS_BSEG_DIST-KURSF.
          ENDIF.
        ENDIF.

        CLEAR LS_BSEG_FOR_POST.
        MOVE-CORRESPONDING LS_BSEG_DIST TO LS_BSEG_FOR_POST.
        LS_BSEG_FOR_POST-FIPOS = LS_DOC_LINES-FIPOS.
        LS_BSEG_FOR_POST-AMOUNT = LV_AMOUNT_9.
        LS_BSEG_FOR_POST-KTEXT =  |Payroll posting run { IV_RUNID } { LV_AKPER }|.

        "collect posting
        PUT_TO_POST_TABLE( IS_DATA = LS_BSEG_FOR_POST ).

        "Consolidate by personnel number
        LS_PERNR_CONSOLIDATION-PERNR = LS_BSEG_DIST-PERNR.
        LS_PERNR_CONSOLIDATION-BETRG_999S = 0.
        LS_PERNR_CONSOLIDATION-BETRG_DIST = LV_AMOUNT_9.
        COLLECT LS_PERNR_CONSOLIDATION INTO LT_PERNR_CONSOLIDATION.

      ENDIF.

      "Collect cost distribution
      MOVE-CORRESPONDING LS_BSEG_DIST TO LS_PERNR_COST.
      COLLECT LS_PERNR_COST INTO LT_PERNR_COST.

    ENDLOOP.

    SORT LT_PERNR_COST BY PERNR ASCENDING DMBTR DESCENDING.

    "Post the potential difference
    LOOP AT LT_PERNR_CONSOLIDATION INTO LS_PERNR_CONSOLIDATION.
      LV_AMOUNT_9 = LS_PERNR_CONSOLIDATION-BETRG_999S + LS_PERNR_CONSOLIDATION-BETRG_DIST.
      CHECK LV_AMOUNT_9 <> 0.
      "Post the difference
      MULTIPLY LV_AMOUNT_9 BY -1.
      "get posting
      CLEAR LS_BSEG_FOR_POST.

      READ TABLE LT_PERNR_COST INTO LS_PERNR_COST WITH KEY PERNR = LS_PERNR_CONSOLIDATION-PERNR.
      IF SY-SUBRC = 0.
        MOVE-CORRESPONDING LS_PERNR_COST TO LS_BSEG_FOR_POST.
        LS_BSEG_FOR_POST-AMOUNT = LV_AMOUNT_9.
        LS_BSEG_FOR_POST-KTEXT =  |Diff for post run { IV_RUNID } { LV_AKPER } { LS_PERNR_CONSOLIDATION-PERNR } |.
        READ TABLE LT_PERNR_FIPOS INTO LS_PERNR_FIPOS WITH KEY PERNR = LS_PERNR_CONSOLIDATION-PERNR.
        IF SY-SUBRC = 0.
          LS_BSEG_FOR_POST-FIPOS = LS_PERNR_FIPOS-FIPOS.
        ENDIF.
        "collect posting
        PUT_TO_POST_TABLE( IS_DATA = LS_BSEG_FOR_POST ).
      ELSE.
        "No 6xxxxxx account lines found: put difference on 99999x account
        READ TABLE MT_BSEG_BR INTO LS_BSEG_BR WITH KEY PERNR = LS_PERNR_CONSOLIDATION-PERNR.
        IF SY-SUBRC = 0.
          MOVE-CORRESPONDING LS_BSEG_BR TO LS_BSEG_FOR_POST.
          LS_BSEG_FOR_POST-AMOUNT = LV_AMOUNT_9.
          LS_BSEG_FOR_POST-KTEXT =  |Diff for post run { IV_RUNID } { LV_AKPER } { LS_PERNR_CONSOLIDATION-PERNR } |.
          "collect posting
          PUT_TO_POST_TABLE( IS_DATA = LS_BSEG_FOR_POST ).
        ENDIF.
      ENDIF.
    ENDLOOP.

  ENDMETHOD.

* ---- YCL_FM_BR_POSTING_IN_FM_BL====CM00B ----
  METHOD SET_POSTING_LIST.

    DATA LS_LIST_POST_CHK TYPE TY_LIST_POST_CHK.

    LOOP AT MT_POST INTO DATA(LS_POST).
      MOVE-CORRESPONDING LS_POST-HEAD TO LS_LIST_POST_CHK.
      LOOP AT LS_POST-ITEM INTO DATA(LS_ITEM).
        MOVE-CORRESPONDING LS_ITEM TO LS_LIST_POST_CHK.
        APPEND LS_LIST_POST_CHK TO MT_LIST_POST_CHK.
      ENDLOOP.
    ENDLOOP.

  ENDMETHOD.

* ---- YCL_FM_BR_POSTING_IN_FM_BL====CM00C ----
  METHOD UPDATE_POSTING_STATUS.

    DATA LS_YTHR_PEVST TYPE YTHR_PEVST.

    SELECT SINGLE * INTO @LS_YTHR_PEVST FROM YTHR_PEVST WHERE TYPE = 'PP'
                                                        AND   RUNID = @IV_RUNID.
    IF SY-SUBRC = 0.
      LS_YTHR_PEVST-FM_BR_DIFF = ABAP_TRUE.
      LS_YTHR_PEVST-CPUDT = SY-DATUM.
      LS_YTHR_PEVST-CPUTM = SY-UZEIT.
      LS_YTHR_PEVST-USNAM = SY-UNAME.
      UPDATE YTHR_PEVST FROM LS_YTHR_PEVST.
    ELSE.
      LS_YTHR_PEVST-TYPE = 'PP'.
      LS_YTHR_PEVST-RUNID = IV_RUNID.
      LS_YTHR_PEVST-FM_BR_DIFF = ABAP_TRUE.
      LS_YTHR_PEVST-CPUDT = SY-DATUM.
      LS_YTHR_PEVST-CPUTM = SY-UZEIT.
      LS_YTHR_PEVST-USNAM = SY-UNAME.
      INSERT YTHR_PEVST FROM LS_YTHR_PEVST.
    ENDIF.

  ENDMETHOD.

* ---- YCL_FM_BR_POSTING_IN_FM_BL====CM00D ----
  METHOD LOCK_RUNID.

    CALL FUNCTION 'ENQUEUE_EPEVST'
      EXPORTING
        MODE_PEVST     = 'X'
        MANDT          = SY-MANDT
        TYPE           = 'PP'
        RUNID          = IV_RUNID
*       X_TYPE         = ' '
*       X_RUNID        = ' '
*       _SCOPE         = '2'
*       _WAIT          = ' '
*       _COLLECT       = ' '
      EXCEPTIONS
        FOREIGN_LOCK   = 1
        SYSTEM_FAILURE = 2
        OTHERS         = 3.
    IF SY-SUBRC <> 0.
      MESSAGE E051(3G) WITH 'PP' IV_RUNID.
    ENDIF.

  ENDMETHOD.

* ---- YCL_FM_BR_POSTING_IN_FM_BL====CM00E ----
  METHOD UNLOCK_RUNID.

    CALL FUNCTION 'DEQUEUE_EPEVST'
      EXPORTING
        TYPE  = 'PP'
        RUNID = IV_RUNID.

  ENDMETHOD.

* ---- YCL_FM_BR_POSTING_IN_FM_BL====CM00F ----
  METHOD PUT_TO_POST_TABLE.

    DATA LS_POST TYPE TY_POST.
    DATA LS_POST_ITEM TYPE TY_POST_ITEM.
    DATA LV_TABIX TYPE SY-TABIX.
    DATA LV_BLART TYPE BLART.

    CLEAR: LV_TABIX, LS_POST, LV_BLART.

    IF IS_DATA-AMOUNT < 0.
      LV_BLART = 'P1'.
    ELSE.
      LV_BLART = 'P2'.
    ENDIF.

    READ TABLE MT_POST INTO LS_POST WITH KEY HEAD-BLART = LV_BLART
                                             HEAD-BLTYP = '50'
                                             HEAD-BUKRS = IS_DATA-BUKRS
                                             HEAD-BLDAT = MV_BLDAT
                                             HEAD-BUDAT = MV_BUDAT
                                             HEAD-WAERS = IS_DATA-HWAER.
    IF SY-SUBRC <> 0.
      LS_POST-HEAD-BLART = LV_BLART.
      LS_POST-HEAD-BLTYP = '50'.
      LS_POST-HEAD-BUKRS = IS_DATA-BUKRS.
      LS_POST-HEAD-BLDAT = MV_BLDAT.
      LS_POST-HEAD-BUDAT = MV_BUDAT.
      LS_POST-HEAD-WAERS = IS_DATA-HWAER.
      LS_POST-HEAD-KTEXT = IS_DATA-KTEXT.
    ELSE.
      LV_TABIX = SY-TABIX.
    ENDIF.

    READ TABLE LS_POST-ITEM ASSIGNING FIELD-SYMBOL(<LS_POST_ITEM>) WITH KEY FIPOS = IS_DATA-FIPOS
                                                                            FISTL = IS_DATA-FISTL
                                                                            GEBER = IS_DATA-GEBER
                                                                            GSBER = IS_DATA-GSBER
                                                                            SAKNR = IS_DATA-HKONT
                                                                            KOSTL = IS_DATA-KOSTL
                                                                            PTEXT = IS_DATA-KTEXT.
    IF SY-SUBRC = 0.
      ADD IS_DATA-AMOUNT TO <LS_POST_ITEM>-WRBTR.
    ELSE.
      CLEAR LS_POST_ITEM.
      LS_POST_ITEM-FIPOS = IS_DATA-FIPOS.
      LS_POST_ITEM-FISTL = IS_DATA-FISTL.
      LS_POST_ITEM-GEBER = IS_DATA-GEBER.
      LS_POST_ITEM-GSBER = IS_DATA-GSBER.
      LS_POST_ITEM-SAKNR = IS_DATA-HKONT.
      LS_POST_ITEM-KOSTL = IS_DATA-KOSTL.
      LS_POST_ITEM-PS_PSP_PNR = IS_DATA-PROJK.
      LS_POST_ITEM-WRBTR = IS_DATA-AMOUNT.
      LS_POST_ITEM-PTEXT = IS_DATA-KTEXT.
      INSERT LS_POST_ITEM INTO TABLE LS_POST-ITEM.
    ENDIF.

    IF LV_TABIX = 0.
      INSERT LS_POST INTO TABLE MT_POST.
    ELSE.
      MODIFY MT_POST FROM LS_POST INDEX LV_TABIX.
    ENDIF.

  ENDMETHOD.

* ---- YCL_FM_BR_POSTING_IN_FM_BL====CM00G ----
  METHOD PUT_CUMUL_BY_PERNR.

    DATA LS_BR_PERNR TYPE YTFM_BR_PAYPER.

    SORT MT_BSEG_BR.

    LOOP AT MT_BSEG_BR INTO DATA(LS_BSEG_BR).

      AT NEW PERNR.
        CLEAR LS_BR_PERNR.
        LS_BR_PERNR-RUNID = IV_RUNID.
        LS_BR_PERNR-PERNR = LS_BSEG_BR-PERNR.
      ENDAT.

      CASE LS_BSEG_BR-SHKZG.
        WHEN 'H'.
          ADD LS_BSEG_BR-DMBTR TO LS_BR_PERNR-DMBTR_9.
          ADD LS_BSEG_BR-WRBTR TO LS_BR_PERNR-WRBTR_9.
        WHEN 'S'.
          SUBTRACT LS_BSEG_BR-DMBTR FROM LS_BR_PERNR-DMBTR_9.
          SUBTRACT LS_BSEG_BR-WRBTR FROM LS_BR_PERNR-WRBTR_9.
      ENDCASE.

      LS_BR_PERNR-HWAER_9 = LS_BSEG_BR-HWAER.
      LS_BR_PERNR-WAERS_9 = LS_BSEG_BR-WAERS.

      AT END OF PERNR.
        CONSOLIDATE_DISTRIBUTION( CHANGING CS_LIST = LS_BR_PERNR ).
        APPEND LS_BR_PERNR TO MT_BR_PERNR.
      ENDAT.

    ENDLOOP.

  ENDMETHOD.

* ---- YCL_FM_BR_POSTING_IN_FM_BL====CO ----
PROTECTED SECTION.

* ---- YCL_FM_BR_POSTING_IN_FM_BL====CU ----
CLASS YCL_FM_BR_POSTING_IN_FM_BL DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

PUBLIC SECTION.

  TYPES:
    BEGIN OF TY_POST_HEAD,
        BLART TYPE FMR_INTERFACE_HEAD-BLART,
        BLTYP TYPE FMR_INTERFACE_HEAD-BLTYP,
        BUKRS TYPE FMR_INTERFACE_HEAD-BUKRS,
        BLDAT TYPE FMR_INTERFACE_HEAD-BLDAT,
        BUDAT TYPE FMR_INTERFACE_HEAD-BUDAT,
        WAERS TYPE FMR_INTERFACE_HEAD-WAERS,
        KTEXT TYPE FMR_INTERFACE_HEAD-KTEXT,
      END OF TY_POST_HEAD .
  TYPES:
    BEGIN OF TY_POST_ITEM,
        FIPOS      TYPE FMR_INTERFACE_DET-FIPOS,
        FISTL      TYPE FMR_INTERFACE_DET-FISTL,
        GEBER      TYPE FMR_INTERFACE_DET-GEBER,
        GSBER      TYPE FMR_INTERFACE_DET-GSBER,
        SAKNR      TYPE FMR_INTERFACE_DET-SAKNR,
        KOSTL      TYPE FMR_INTERFACE_DET-KOSTL,
        PS_PSP_PNR TYPE FMR_INTERFACE_DET-PS_PSP_PNR,
        WRBTR      TYPE FMR_INTERFACE_DET-WRBTR,
        PTEXT      TYPE FMR_INTERFACE_DET-PTEXT,
      END OF TY_POST_ITEM .
  TYPES:
    BEGIN OF TY_LIST_PERNR,
        PERNR   TYPE P_PERNR,
        DMBTR_9 TYPE BSEG-DMBTR,
        HWAER_9 TYPE BKPF-HWAER,
        WRBTR_9 TYPE BSEG-WRBTR,
        WAERS_9 TYPE BKPF-WAERS,
        DMBTR_D TYPE BSEG-DMBTR,
        HWAER_D TYPE BKPF-HWAER,
        WRBTR_D TYPE BSEG-WRBTR,
        WAERS_D TYPE BKPF-WAERS,
        STATUS  TYPE P_99S_STATU,
      END OF TY_LIST_PERNR .
  TYPES:
    BEGIN OF TY_LIST_POST_CHK.
        INCLUDE TYPE TY_POST_HEAD.
        INCLUDE TYPE TY_POST_ITEM.
      TYPES: END OF TY_LIST_POST_CHK .
  TYPES:
    BEGIN OF TY_LIST_POST_EXE.
        INCLUDE TYPE TY_POST_HEAD.
        TYPES: BETRG     TYPE WERTV9,
        STATUS_FM TYPE P_99S_STATU,
        STATUS_BR TYPE P_99S_STATU,
        BELNR     TYPE KBLNR,
      END OF TY_LIST_POST_EXE .

  CLASS-DATA:
    MT_LIST_PERNR TYPE TABLE OF TY_LIST_PERNR .
  CLASS-DATA:
    MT_LIST_POST_CHK TYPE TABLE OF TY_LIST_POST_CHK .
  CLASS-DATA:
    MT_LIST_POST_EXE TYPE TABLE OF TY_LIST_POST_EXE .

  CLASS-METHODS SET_POSTING_LIST .
  CLASS-METHODS POST
    IMPORTING
      !IV_RUNID TYPE P_EVNUM
      !IV_MODE_TEST TYPE XFELD
      !IV_FM_POST TYPE XFELD DEFAULT ABAP_FALSE
      !IV_BR_POST TYPE XFELD DEFAULT ABAP_FALSE .
  CLASS-METHODS PREPARE_DATA_FOR_POSTING
    IMPORTING
      !IV_RUNID TYPE P_EVNUM .
  CLASS-METHODS CHECK_DISTRIBUTION
    IMPORTING
      VALUE(IV_TOLERANCE) TYPE YE_CA_DEC_3_2 OPTIONAL .
  CLASS-METHODS PREPARE_DATA_FROM_RUNID
    IMPORTING
      !IV_RUNID TYPE P_EVNUM
      !IT_PERNR TYPE YTTHR_PERNR_RANGE
    EXPORTING
      !ET_RETURN TYPE BAPIRETTAB .