* ==== CLASS POOL YCL_PS_PROJECT_ALE_EXTENSION ====
CLASS-POOL .
*"* class pool for class YCL_PS_PROJECT_ALE_EXTENSION

*"* local type definitions
INCLUDE YCL_PS_PROJECT_ALE_EXTENSION==CCDEF.

*"* class YCL_PS_PROJECT_ALE_EXTENSION definition
*"* public declarations
  INCLUDE YCL_PS_PROJECT_ALE_EXTENSION==CU.
*"* protected declarations
  INCLUDE YCL_PS_PROJECT_ALE_EXTENSION==CO.
*"* private declarations
  INCLUDE YCL_PS_PROJECT_ALE_EXTENSION==CI.
ENDCLASS. "YCL_PS_PROJECT_ALE_EXTENSION definition

*"* macro definitions
INCLUDE YCL_PS_PROJECT_ALE_EXTENSION==CCMAC.
*"* local class implementation
INCLUDE YCL_PS_PROJECT_ALE_EXTENSION==CCIMP.

CLASS YCL_PS_PROJECT_ALE_EXTENSION IMPLEMENTATION.
*"* method's implementations
  INCLUDE METHODS.
ENDCLASS. "YCL_PS_PROJECT_ALE_EXTENSION implementation


* ---- YCL_PS_PROJECT_ALE_EXTENSION==CI ----
PRIVATE SECTION.

  TYPES:
    BEGIN OF TY_SYSTEM_STATUS,
      OBTYP TYPE TJ04-OBTYP,
      ISTAT TYPE TJ04-ISTAT,
      TXT04 TYPE TJ02T-TXT04,
      TXT30 TYPE TJ02T-TXT30,
    END OF TY_SYSTEM_STATUS .

  DATA:
    MT_SYSTEM_STATUS TYPE SORTED TABLE OF TY_SYSTEM_STATUS WITH UNIQUE KEY OBTYP ISTAT .
  CLASS-DATA MO_INSTANCE TYPE REF TO YCL_PS_PROJECT_ALE_EXTENSION .

* ---- YCL_PS_PROJECT_ALE_EXTENSION==CM001 ----
  METHOD GET_INSTANCE.

    IF MO_INSTANCE IS INITIAL.
      MO_INSTANCE = NEW YCL_PS_PROJECT_ALE_EXTENSION( ).
    ENDIF.

    RO_INSTANCE = MO_INSTANCE.

  ENDMETHOD.

* ---- YCL_PS_PROJECT_ALE_EXTENSION==CM002 ----
  METHOD CONSTRUCTOR.

    DATA LT_OBTYP TYPE RANGE OF J_OBTYP.

    LT_OBTYP = VALUE #( ( SIGN = 'I' OPTION = 'EQ' LOW = 'PDN' )
                        ( SIGN = 'I' OPTION = 'EQ' LOW = 'PRN' ) ).

    "Get system status for project / WBS element
    SELECT A~OBTYP,
           A~ISTAT,
           T~TXT04,
           T~TXT30
           FROM TJ04 AS A LEFT OUTER JOIN TJ02T AS T ON  T~ISTAT = A~ISTAT
                                                     AND T~SPRAS = @SY-LANGU
           WHERE A~OBTYP IN @LT_OBTYP
           INTO TABLE @MT_SYSTEM_STATUS.

  ENDMETHOD.

* ---- YCL_PS_PROJECT_ALE_EXTENSION==CM003 ----
  METHOD FILL_EXT_WITH_SYSTEM_STATUS.

    DATA LS_EXTENSION TYPE LINE OF BAPIPAREXTAB.
    DATA LS_EXTENSION_VALUE TYPE YSPS_PROJECT_SYSTEM_STATUS.
    DATA LS_BDI TYPE LINE OF YTT_BDI_BTABIX.
    FIELD-SYMBOLS <DATA> TYPE C.
    DATA LV_INDEX TYPE SYTABIX.

    "Get last index from extension
    LOOP AT CT_BDI_BTABIX INTO LS_BDI WHERE RECEIVER = IV_RECEIVER
                                      AND   TABNAME = 'EXTENSION'.
      LV_INDEX = LS_BDI-INDEX.
    ENDLOOP.

    "If MuleSOFT as receiver, don't send standard extension
    IF IV_RECEIVER(4) = 'MULE' OR IV_RECEIVER = 'DUMMY'.
      DELETE CT_BDI_BTABIX WHERE RECEIVER = IV_RECEIVER
                           AND   TABNAME = 'EXTENSION'.
    ENDIF.

    LOOP AT IT_OBJECTSTATUS INTO DATA(LS_OBJECTSTATUS) WHERE INACTIVE = ABAP_FALSE.
      "Get status details
      READ TABLE MT_SYSTEM_STATUS INTO DATA(LS_SYSTEM_STATUS) WITH KEY OBTYP = LS_OBJECTSTATUS-OBJECT_TYPE
                                                                       ISTAT = LS_OBJECTSTATUS-STATUS.
      CHECK SY-SUBRC = 0.    "System Status only
      CHECK LS_OBJECTSTATUS-OBJECT_TYPE = 'PDN'.   "Only project status
      CLEAR: LS_EXTENSION_VALUE, LS_EXTENSION, LS_BDI.
      "Set values
      LS_EXTENSION_VALUE-WBS_OBJECTID = LS_OBJECTSTATUS-WBS_OBJECTID.
      LS_EXTENSION_VALUE-OBJECT_TYPE = LS_OBJECTSTATUS-OBJECT_TYPE.
      LS_EXTENSION_VALUE-STATUS = LS_OBJECTSTATUS-STATUS.
      LS_EXTENSION_VALUE-TXT04 = LS_SYSTEM_STATUS-TXT04.
      LS_EXTENSION_VALUE-TXT30 = LS_SYSTEM_STATUS-TXT30.
      "Set to extension
      LS_EXTENSION-STRUCTURE = 'YSPS_PROJECT_SYSTEM_STATUS'.
      ASSIGN LS_EXTENSION_VALUE TO <DATA> CASTING.
      LS_EXTENSION-VALUEPART1 = <DATA>.
      APPEND LS_EXTENSION TO CT_EXTENSION.
      "Set to BDI table
      ADD 1 TO LV_INDEX.
      LS_BDI-RECEIVER = IV_RECEIVER.
      LS_BDI-TABNAME = 'EXTENSION'.
      LS_BDI-INDEX = LV_INDEX.
      APPEND LS_BDI TO CT_BDI_BTABIX.
    ENDLOOP.

    SORT CT_BDI_BTABIX BY RECEIVER TABNAME INDEX.

  ENDMETHOD.

* ---- YCL_PS_PROJECT_ALE_EXTENSION==CO ----
PROTECTED SECTION.

* ---- YCL_PS_PROJECT_ALE_EXTENSION==CU ----
CLASS YCL_PS_PROJECT_ALE_EXTENSION DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

PUBLIC SECTION.

  METHODS FILL_EXT_WITH_SYSTEM_STATUS
    IMPORTING
      !IT_OBJECTSTATUS TYPE YTT_BAPI2054_OBJECTSTATUS_ALE
      !IV_RECEIVER TYPE LOGSYS
    CHANGING
      !CT_EXTENSION TYPE BAPIPAREXTAB
      !CT_BDI_BTABIX TYPE YTT_BDI_BTABIX .
  METHODS CONSTRUCTOR .
  CLASS-METHODS GET_INSTANCE
    RETURNING
      VALUE(RO_INSTANCE) TYPE REF TO YCL_PS_PROJECT_ALE_EXTENSION .