* ==== CLASS POOL YCL_FI_ACCOUNT_SUBST_BL ====
CLASS-POOL .
*"* class pool for class YCL_FI_ACCOUNT_SUBST_BL

*"* local type definitions
INCLUDE YCL_FI_ACCOUNT_SUBST_BL=======CCDEF.

*"* class YCL_FI_ACCOUNT_SUBST_BL definition
*"* public declarations
  INCLUDE YCL_FI_ACCOUNT_SUBST_BL=======CU.
*"* protected declarations
  INCLUDE YCL_FI_ACCOUNT_SUBST_BL=======CO.
*"* private declarations
  INCLUDE YCL_FI_ACCOUNT_SUBST_BL=======CI.
ENDCLASS. "YCL_FI_ACCOUNT_SUBST_BL definition

*"* macro definitions
INCLUDE YCL_FI_ACCOUNT_SUBST_BL=======CCMAC.
*"* local class implementation
INCLUDE YCL_FI_ACCOUNT_SUBST_BL=======CCIMP.

CLASS YCL_FI_ACCOUNT_SUBST_BL IMPLEMENTATION.
*"* method's implementations
  INCLUDE METHODS.
ENDCLASS. "YCL_FI_ACCOUNT_SUBST_BL implementation


* ---- YCL_FI_ACCOUNT_SUBST_BL=======CI ----
PRIVATE SECTION.

  TYPES:
    BEGIN OF TY_LIST,
      BLART TYPE BLART,
      LTEXT TYPE LTEXT_003T,
      GSBER TYPE GSBER,
      GTEXT TYPE GTEXT,
      HKSEL TYPE ICON_D,
      HKDIS TYPE ICON_D,
      HKTAB TYPE RANGE OF HKONT,
    END OF TY_LIST .
  TYPES:
    BEGIN OF TY_ACCT,
      BUKRS TYPE BUKRS,
      BLART TYPE BLART,
      GSBER TYPE GSBER,
      HKONT TYPE HKONT,
      TXT50 TYPE TXT50_SKAT,
    END OF TY_ACCT .
  TYPES:
    BEGIN OF TY_CHECK,
      BUKRS TYPE BUKRS,
      BLART TYPE BLART,
      GSBER TYPE GSBER,
      HKONT TYPE HKONT,
      TXT50 TYPE TXT50_SKAT,
      MESSG TYPE BAPI_MSG,
    END OF TY_CHECK .

  DATA MV_MODE TYPE CHAR1 .
  DATA MV_REPID TYPE SYST-REPID .
  DATA MV_BUKRS TYPE BUKRS .
  DATA:
    MT_LIST TYPE TABLE OF TY_LIST .
  DATA:
    MT_ACCT TYPE TABLE OF TY_ACCT .
  DATA:
    MT_CHECK TYPE TABLE OF TY_CHECK .
  DATA MO_COLUMNS TYPE REF TO CL_SALV_COLUMNS_TABLE .
  DATA MO_DISPLAY_SETTINGS TYPE REF TO CL_SALV_DISPLAY_SETTINGS .
  DATA MO_FUNCTIONS TYPE REF TO CL_SALV_FUNCTIONS_LIST .
  DATA MO_SALV_TABLE TYPE REF TO CL_SALV_TABLE .
  DATA MO_LAYOUT TYPE REF TO CL_SALV_LAYOUT .
  DATA MO_FUNCTIONAL_SETTINGS TYPE REF TO CL_SALV_FUNCTIONAL_SETTINGS .
  DATA MO_ALV_CHECK TYPE REF TO YCL_CA_ALV_IN_POPUP .

  METHODS READ_ACCOUNT_LIST
    IMPORTING
      !IS_LIST TYPE TY_LIST .
  METHODS UPDATE_DATA
    IMPORTING
      !IV_BLART TYPE BLART
      !IV_GSBER TYPE GSBER
      !IT_HKONT TYPE YTTFI_HKONT_RANGE .
  METHODS LOAD_DATA .

* ---- YCL_FI_ACCOUNT_SUBST_BL=======CM001 ----
  METHOD CONSTRUCTOR.

    MV_BUKRS = IV_BUKRS.
    MV_MODE = IV_MODE.
    ME->LOAD_DATA( ).

    MO_ALV_CHECK = NEW YCL_CA_ALV_IN_POPUP( ).

  ENDMETHOD.

* ---- YCL_FI_ACCOUNT_SUBST_BL=======CM002 ----
  METHOD LOAD_DATA.

    SELECT DISTINCT A~BLART,
                    B~LTEXT,
                    A~GSBER,
                    G~GTEXT
      FROM YTFI_BA_SUBST AS A
      LEFT OUTER JOIN T003T AS B ON  B~SPRAS = @SY-LANGU
                                 AND B~BLART = A~BLART
      LEFT OUTER JOIN TGSBT AS G ON  G~SPRAS = @SY-LANGU
                                 AND G~GSBER = A~GSBER
      WHERE A~BUKRS = @MV_BUKRS
      INTO CORRESPONDING FIELDS OF TABLE @MT_LIST.

    LOOP AT MT_LIST ASSIGNING FIELD-SYMBOL(<LS_LIST>).
      <LS_LIST>-HKSEL = ICON_DISPLAY_MORE.  "ICON_ENTER_MORE
      SELECT SIGN,
             OPTI AS OPTION,
             LOW,
             HIGH
        FROM YTFI_BA_SUBST
        WHERE BUKRS = @MV_BUKRS
        AND   BLART = @<LS_LIST>-BLART
        AND   GSBER = @<LS_LIST>-GSBER
        AND   SIGN <> @SPACE
        INTO TABLE @<LS_LIST>-HKTAB.
      IF <LS_LIST>-HKTAB IS INITIAL.
        <LS_LIST>-HKSEL = ICON_ENTER_MORE.
      ELSE.
        <LS_LIST>-HKSEL = ICON_DISPLAY_MORE.
      ENDIF.
      <LS_LIST>-HKDIS = ICON_DISPLAY.
    ENDLOOP.

  ENDMETHOD.

* ---- YCL_FI_ACCOUNT_SUBST_BL=======CM003 ----
  METHOD INIT_ALV.

    MV_REPID = IV_REPID.

    TRY.
        CALL METHOD CL_SALV_TABLE=>FACTORY
*          EXPORTING
*           list_display = IF_SALV_C_BOOL_SAP=>FALSE
*           r_container  = mo_alv_container
*           container_name =
          IMPORTING
            R_SALV_TABLE = MO_SALV_TABLE
          CHANGING
            T_TABLE      = MT_LIST.
      CATCH CX_SALV_MSG .
    ENDTRY.

  ENDMETHOD.

* ---- YCL_FI_ACCOUNT_SUBST_BL=======CM004 ----
  METHOD DISPLAY_ALV.

    DATA LS_LAYOUT_KEY TYPE SALV_S_LAYOUT_KEY.
    DATA LO_COLUMN  TYPE REF TO CL_SALV_COLUMN_TABLE.
    DATA LV_TITLE TYPE LVC_TITLE.
    DATA LV_PFSTATUS TYPE SYPFKEY.

    MO_FUNCTIONS = MO_SALV_TABLE->GET_FUNCTIONS( ).
    MO_COLUMNS = MO_SALV_TABLE->GET_COLUMNS( ).
    MO_LAYOUT = MO_SALV_TABLE->GET_LAYOUT( ).
    MO_DISPLAY_SETTINGS = MO_SALV_TABLE->GET_DISPLAY_SETTINGS( ).
    MO_FUNCTIONAL_SETTINGS = MO_SALV_TABLE->GET_FUNCTIONAL_SETTINGS( ).

    "ALV set status
    IF MV_MODE = 'M'.
      LV_PFSTATUS = 'MAIN_STATUS'.
    ELSE.
      LV_PFSTATUS = 'MAIN_STATUS_DIS'.
    ENDIF.
    MO_SALV_TABLE->SET_SCREEN_STATUS( PFSTATUS      = LV_PFSTATUS
                                      REPORT        = MV_REPID
                                      SET_FUNCTIONS = MO_SALV_TABLE->C_FUNCTIONS_ALL ).

    "ALV layout
    MO_LAYOUT = MO_SALV_TABLE->GET_LAYOUT( ).
    LS_LAYOUT_KEY-REPORT = MV_REPID.
    MO_LAYOUT->SET_KEY( LS_LAYOUT_KEY ).

    "List title
    IF MV_MODE = 'M'.
      LV_TITLE = |Manage { TEXT-T01 } { MV_BUKRS }|.
    ELSE.
      LV_TITLE = |Display { TEXT-T01 } { MV_BUKRS }|.
    ENDIF.
    MO_DISPLAY_SETTINGS->SET_LIST_HEADER( LV_TITLE ).

    "Columns
    TRY.
        LO_COLUMN ?= MO_COLUMNS->GET_COLUMN( 'HKSEL' ).
        LO_COLUMN->SET_CELL_TYPE( IF_SALV_C_CELL_TYPE=>HOTSPOT ).
        LO_COLUMN->SET_ICON( IF_SALV_C_BOOL_SAP=>TRUE ).
        LO_COLUMN->SET_LONG_TEXT( 'G/L Accounts' ).
        LO_COLUMN->SET_FIXED_HEADER_TEXT( 'L' ).
      CATCH CX_SALV_NOT_FOUND.
    ENDTRY.
    TRY.
        LO_COLUMN ?= MO_COLUMNS->GET_COLUMN( 'HKDIS' ).
        LO_COLUMN->SET_CELL_TYPE( IF_SALV_C_CELL_TYPE=>HOTSPOT ).
        LO_COLUMN->SET_ICON( IF_SALV_C_BOOL_SAP=>TRUE ).
        LO_COLUMN->SET_LONG_TEXT( 'List of G/L Accounts' ).
        LO_COLUMN->SET_FIXED_HEADER_TEXT( 'L' ).
      CATCH CX_SALV_NOT_FOUND.
    ENDTRY.

    "Display ALV
    MO_SALV_TABLE->DISPLAY( ).

  ENDMETHOD.

* ---- YCL_FI_ACCOUNT_SUBST_BL=======CM005 ----
  METHOD GET_EVENT.

    RO_EVENT = MO_SALV_TABLE->GET_EVENT( ).

  ENDMETHOD.

* ---- YCL_FI_ACCOUNT_SUBST_BL=======CM006 ----
  METHOD GET_ROW_SELECTED.

    DATA LO_SELECTIONS TYPE REF TO CL_SALV_SELECTIONS.
    DATA LT_ROWS       TYPE SALV_T_ROW.

    CLEAR RV_ROW_INDEX.

    LO_SELECTIONS = MO_SALV_TABLE->GET_SELECTIONS( ).
    LT_ROWS = LO_SELECTIONS->GET_SELECTED_ROWS( ).
    READ TABLE LT_ROWS INTO RV_ROW_INDEX INDEX 1.
    IF SY-SUBRC <> 0.
      MESSAGE TEXT-I01 TYPE 'I'.
    ENDIF.

  ENDMETHOD.

* ---- YCL_FI_ACCOUNT_SUBST_BL=======CM007 ----
  METHOD GET_ACCOUNTS.

    READ TABLE MT_LIST INTO DATA(LS_LIST) INDEX IV_ROW_INDEX.
    CHECK SY-SUBRC = 0.
    RT_HKONT = LS_LIST-HKTAB.

  ENDMETHOD.

* ---- YCL_FI_ACCOUNT_SUBST_BL=======CM008 ----
  METHOD SET_ACCOUNTS.

    READ TABLE MT_LIST ASSIGNING FIELD-SYMBOL(<LS_LIST>) INDEX IV_ROW_INDEX.
    CHECK SY-SUBRC = 0.
    <LS_LIST>-HKTAB = IT_HKONT.

    IF <LS_LIST>-HKTAB IS INITIAL.
      <LS_LIST>-HKSEL = ICON_ENTER_MORE.
    ELSE.
      <LS_LIST>-HKSEL = ICON_DISPLAY_MORE.
    ENDIF.

    "Update data
    ME->UPDATE_DATA( IV_BLART = <LS_LIST>-BLART
                     IV_GSBER = <LS_LIST>-GSBER
                     IT_HKONT = <LS_LIST>-HKTAB ).

  ENDMETHOD.

* ---- YCL_FI_ACCOUNT_SUBST_BL=======CM009 ----
  METHOD INSERT_ROW.

    DATA LS_LIST TYPE TY_LIST.

    READ TABLE MT_LIST TRANSPORTING NO FIELDS WITH KEY BLART = IV_BLART
                                                       GSBER = IV_GSBER.
    IF SY-SUBRC = 0.
      MESSAGE TEXT-E01 TYPE 'E'.
      EXIT.
    ENDIF.

    "Update data
    ME->UPDATE_DATA( IV_BLART = IV_BLART
                     IV_GSBER = IV_GSBER
                     IT_HKONT = IT_HKONT ).

  ENDMETHOD.

* ---- YCL_FI_ACCOUNT_SUBST_BL=======CM00A ----
  METHOD UPDATE_DATA.

    DATA LT_DATA TYPE TABLE OF YTFI_BA_SUBST.
    DATA LS_DATA TYPE YTFI_BA_SUBST.
    DATA LV_NUMB TYPE YTFI_BA_SUBST-NUMB.

    "First delete existing entries
    DELETE FROM YTFI_BA_SUBST WHERE BUKRS = MV_BUKRS
                              AND   BLART = IV_BLART
                              AND   GSBER = IV_GSBER.
    LS_DATA-BUKRS = MV_BUKRS.
    LS_DATA-BLART = IV_BLART.
    LS_DATA-GSBER = IV_GSBER.

    LOOP AT IT_HKONT INTO DATA(LS_HKONT).
      ADD 1 TO LV_NUMB.
      LS_DATA-NUMB = LV_NUMB.
      LS_DATA-SIGN = LS_HKONT-SIGN.
      LS_DATA-OPTI = LS_HKONT-OPTION.
      LS_DATA-LOW = LS_HKONT-LOW.
      LS_DATA-HIGH = LS_HKONT-HIGH.
      APPEND LS_DATA TO LT_DATA.
    ENDLOOP.
    IF SY-SUBRC <> 0.
      APPEND LS_DATA TO LT_DATA.
    ENDIF.

    INSERT YTFI_BA_SUBST FROM TABLE LT_DATA.
    IF SY-SUBRC <> 0.
      MESSAGE TEXT-E02 TYPE 'E'.
      ROLLBACK WORK.
    ELSE.
      COMMIT WORK.
    ENDIF.

  ENDMETHOD.

* ---- YCL_FI_ACCOUNT_SUBST_BL=======CM00B ----
  METHOD REFRESH_ALV.

    CLEAR MT_LIST.
    ME->LOAD_DATA( ).
    TRY.
        MO_SALV_TABLE->SET_DATA( CHANGING T_TABLE = MT_LIST ).
      CATCH CX_SALV_NO_NEW_DATA_ALLOWED.
    ENDTRY.

    MO_SALV_TABLE->REFRESH( ).

  ENDMETHOD.

* ---- YCL_FI_ACCOUNT_SUBST_BL=======CM00C ----
  METHOD DELETE_ROW.

    READ TABLE MT_LIST INTO DATA(LS_LIST) INDEX IV_ROW_INDEX.
    CHECK SY-SUBRC = 0.
    DELETE FROM YTFI_BA_SUBST WHERE BUKRS = MV_BUKRS
                              AND   BLART = LS_LIST-BLART
                              AND   GSBER = LS_LIST-GSBER.
    COMMIT WORK.

  ENDMETHOD.

* ---- YCL_FI_ACCOUNT_SUBST_BL=======CM00D ----
  METHOD GET_DATA_FROM_ROW_INDEX.

    CLEAR: EV_BLART, EV_GSBER, ET_HKONT.
    READ TABLE MT_LIST INTO DATA(LS_LIST) INDEX IV_ROW_INDEX.
    CHECK SY-SUBRC = 0.
    EV_BLART = LS_LIST-BLART.
    EV_GSBER = LS_LIST-GSBER.
    ET_HKONT = LS_LIST-HKTAB.

  ENDMETHOD.

* ---- YCL_FI_ACCOUNT_SUBST_BL=======CM00E ----
  METHOD DISPLAY_ACCOUNT_LIST.

    READ TABLE MT_LIST INTO DATA(LS_LIST) INDEX IV_ROW_INDEX.
    CHECK SY-SUBRC = 0 AND LS_LIST-HKTAB IS NOT INITIAL.

    ME->READ_ACCOUNT_LIST( LS_LIST ).

    MO_ALV_CHECK->EXECUTE( EXPORTING IV_TITLE = 'List of G/L accounts'
                           CHANGING CT_TABLE = MT_ACCT ).

*    SUBMIT yfi_account_substitution_list WITH p_bukrs = mv_bukrs
*                                         WITH p_blart = ls_list-blart
*                                         WITH p_gsber = ls_list-gsber
*                                         AND RETURN.

  ENDMETHOD.

* ---- YCL_FI_ACCOUNT_SUBST_BL=======CM00F ----
  METHOD CHECK_ACCOUNTS.

    DATA LT_ACCT_ALL TYPE TABLE OF TY_ACCT.
    DATA LS_CHECK TYPE TY_CHECK.

    CLEAR MT_CHECK.

    LOOP AT MT_LIST INTO DATA(LS_LIST).
      IF LS_LIST-HKTAB IS INITIAL.
        CLEAR LS_CHECK.
        MOVE-CORRESPONDING LS_LIST TO LS_CHECK.
        LS_CHECK-MESSG = TEXT-M02.
        APPEND LS_CHECK TO MT_CHECK.
      ELSE.
        ME->READ_ACCOUNT_LIST( LS_LIST ).
        APPEND LINES OF MT_ACCT TO LT_ACCT_ALL.
      ENDIF.
    ENDLOOP.

    SORT LT_ACCT_ALL BY BLART HKONT.

    LOOP AT LT_ACCT_ALL INTO DATA(LS_ACCT_ALL) GROUP BY ( BLART = LS_ACCT_ALL-BLART
                                                          SAKNR = LS_ACCT_ALL-HKONT
                                                          SIZE = GROUP SIZE )
                        ASSIGNING FIELD-SYMBOL(<LS_ACCT_GROUP>).
      IF <LS_ACCT_GROUP>-SIZE > 1.
        LOOP AT GROUP <LS_ACCT_GROUP> INTO DATA(LS_ACCT_GROUP).
          CLEAR LS_CHECK.
          MOVE-CORRESPONDING LS_ACCT_GROUP TO LS_CHECK.
          LS_CHECK-MESSG = TEXT-M01.
          APPEND LS_CHECK TO MT_CHECK.
        ENDLOOP.
      ENDIF.
    ENDLOOP.

    MO_ALV_CHECK->EXECUTE( EXPORTING IV_TITLE = 'Inconsistency in G/L Accounts assignment'
                           CHANGING CT_TABLE = MT_CHECK ).

  ENDMETHOD.

* ---- YCL_FI_ACCOUNT_SUBST_BL=======CM00G ----
  METHOD READ_ACCOUNT_LIST.

    CLEAR MT_ACCT.

    SELECT A~BUKRS, @IS_LIST-BLART, @IS_LIST-GSBER, A~SAKNR, T~TXT50
       FROM SKB1 AS A
       INNER JOIN T001 AS B ON B~BUKRS = A~BUKRS
       LEFT OUTER JOIN SKAT AS T ON  T~SPRAS = @SY-LANGU
                                 AND T~KTOPL = B~KTOPL
                                 AND T~SAKNR = A~SAKNR
       WHERE A~BUKRS = @MV_BUKRS
       AND   A~SAKNR IN @IS_LIST-HKTAB
       INTO  TABLE @MT_ACCT.

  ENDMETHOD.

* ---- YCL_FI_ACCOUNT_SUBST_BL=======CO ----
PROTECTED SECTION.

* ---- YCL_FI_ACCOUNT_SUBST_BL=======CU ----
CLASS YCL_FI_ACCOUNT_SUBST_BL DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

PUBLIC SECTION.

  METHODS CHECK_ACCOUNTS .
  METHODS DELETE_ROW
    IMPORTING
      !IV_ROW_INDEX TYPE SY-TABIX .
  METHODS DISPLAY_ACCOUNT_LIST
    IMPORTING
      !IV_ROW_INDEX TYPE SY-TABIX .
  METHODS DISPLAY_ALV .
  METHODS GET_ACCOUNTS
    IMPORTING
      !IV_ROW_INDEX TYPE SY-TABIX
    RETURNING
      VALUE(RT_HKONT) TYPE YTTFI_HKONT_RANGE .
  METHODS GET_DATA_FROM_ROW_INDEX
    IMPORTING
      !IV_ROW_INDEX TYPE SY-TABIX
    EXPORTING
      !EV_BLART TYPE BLART
      !EV_GSBER TYPE GSBER
      !ET_HKONT TYPE YTTFI_HKONT_RANGE .
  METHODS GET_EVENT
    RETURNING
      VALUE(RO_EVENT) TYPE REF TO CL_SALV_EVENTS_TABLE .
  METHODS GET_ROW_SELECTED
    RETURNING
      VALUE(RV_ROW_INDEX) TYPE SY-TABIX .
  METHODS INIT_ALV
    IMPORTING
      !IV_REPID TYPE SYST-REPID .
  METHODS INSERT_ROW
    IMPORTING
      !IV_BLART TYPE BLART
      !IV_GSBER TYPE GSBER
      !IT_HKONT TYPE YTTFI_HKONT_RANGE .
  METHODS REFRESH_ALV .
  METHODS SET_ACCOUNTS
    IMPORTING
      !IV_ROW_INDEX TYPE SY-TABIX
      !IT_HKONT TYPE YTTFI_HKONT_RANGE .
  METHODS CONSTRUCTOR
    IMPORTING
      !IV_BUKRS TYPE BUKRS
      !IV_MODE TYPE CHAR1 .