* ==== CLASS POOL YCL_FM_FUND_CASH_BAL_WITH_PS ====
CLASS-POOL .
*"* class pool for class YCL_FM_FUND_CASH_BAL_WITH_PS

*"* local type definitions
INCLUDE YCL_FM_FUND_CASH_BAL_WITH_PS==CCDEF.

*"* class YCL_FM_FUND_CASH_BAL_WITH_PS definition
*"* public declarations
  INCLUDE YCL_FM_FUND_CASH_BAL_WITH_PS==CU.
*"* protected declarations
  INCLUDE YCL_FM_FUND_CASH_BAL_WITH_PS==CO.
*"* private declarations
  INCLUDE YCL_FM_FUND_CASH_BAL_WITH_PS==CI.
ENDCLASS. "YCL_FM_FUND_CASH_BAL_WITH_PS definition

*"* macro definitions
INCLUDE YCL_FM_FUND_CASH_BAL_WITH_PS==CCMAC.
*"* local class implementation
INCLUDE YCL_FM_FUND_CASH_BAL_WITH_PS==CCIMP.

CLASS YCL_FM_FUND_CASH_BAL_WITH_PS IMPLEMENTATION.
*"* method's implementations
  INCLUDE METHODS.
ENDCLASS. "YCL_FM_FUND_CASH_BAL_WITH_PS implementation


* ---- YCL_FM_FUND_CASH_BAL_WITH_PS==CI ----
PRIVATE SECTION.

  TYPES:
    BEGIN OF TY_FUND_FMIT,
      FIKRS   TYPE FIKRS,
      FINCODE TYPE BP_GEBER,
    END OF TY_FUND_FMIT .
  TYPES:
    BEGIN OF TY_FUND,
      FIKRS      TYPE FIKRS,
      FINCODE    TYPE BP_GEBER,
      TYPE       TYPE FM_FUNDTYPE,
      BESCHR     TYPE FM_BESCHR,
      DATAB      TYPE FM_DATAB,
      DATBIS     TYPE FM_DATBIS,
      FUND_PSPID TYPE PS_PSPID,
    END OF TY_FUND .
  TYPES:
    BEGIN OF TY_FUND_C5,
      FIKRS     TYPE FIKRS,
      FINCODE   TYPE BP_GEBER,
      C5_ID     TYPE YE_FM_C5_ID,
      YEAR_FROM TYPE YE_CA_YEAR_FROM,
      YEAR_TO   TYPE YE_CA_YEAR_FROM,
      C5_SEL    TYPE YE_FM_C5_CONTRIBUTION,
      FM_OUTPUT TYPE YE_FM_OUTPUT,
      OTYPE     TYPE YE_FM_OUTPUT_TYPE,
      ONAME     TYPE YE_FM_OUTPUT_NAME,
      OTEXT     TYPE YE_FM_OUTPUT_TEXT,
    END OF TY_FUND_C5 .
  TYPES:
    BEGIN OF TY_FUND_AMOUNT,
      FINCODE TYPE BP_GEBER,
      WAERS   TYPE WAERS,
      CF      TYPE WERTV9,
      REVENUE TYPE WERTV9,
      GAINS   TYPE WERTV9,
      COST    TYPE WERTV9,
    END OF TY_FUND_AMOUNT .
  TYPES:
    BEGIN OF TY_PROJ_WBS,
      PROJ_PSPNR      TYPE PROJ-PSPNR,
      PSPID           TYPE PROJ-PSPID,
      POSTU           TYPE PROJ-POSTU,
      PWHIE           TYPE PROJ-PWHIE,
      PROFL           TYPE PROJ-PROFL,
      BPROF           TYPE PROJ-BPROF,
      PRPS_PSPNR      TYPE PRPS-PSPNR,
      POSID           TYPE PRPS-POSID,
      PBUKR           TYPE PRPS-PBUKR,
      PGSBR           TYPE PRPS-PGSBR,
      PRART           TYPE PRPS-PRART,
      STUFE           TYPE PRPS-STUFE,
      DESCR           TYPE STRING,
      YYE_DONOR       TYPE PRPS-YYE_DONOR,
      YYE_EXEC_AGENCY TYPE PRPS-YYE_EXEC_AGENCY,
      YYE_IMPL_AGENCY TYPE PRPS-YYE_IMPL_AGENCY,
      YYE_TYP_SOU     TYPE PRPS-YYE_TYP_SOU,
      YYE_EXEC        TYPE PRPS-YYE_EXEC,
      YYE_PRCRT       TYPE PRPS-YYE_PRCRT,
    END OF TY_PROJ_WBS .
  TYPES:
    BEGIN OF TY_LIST.
      INCLUDE TYPE TY_FUND.
      TYPES: C5_ID     TYPE YE_FM_C5_ID,
      FM_OUTPUT TYPE YE_FM_OUTPUT,
      OTYPE     TYPE YE_FM_OUTPUT_TYPE,
      ONAME     TYPE YE_FM_OUTPUT_NAME,
      OTEXT     TYPE YE_FM_OUTPUT_TEXT,
      C5_SEL    TYPE YE_FM_C5_CONTRIBUTION.
      INCLUDE TYPE TY_PROJ_WBS.
      TYPES: CF        TYPE WERTV9,
      REVENUE   TYPE WERTV9,
      GAINS     TYPE WERTV9,
      COST      TYPE WERTV9,
      BALANCE   TYPE WERTV9,
      WAERS     TYPE WAERS,
    END OF TY_LIST .

  DATA MV_FM_WAERS TYPE WAERS .
  DATA MV_FIKRS TYPE FIKRS .
  DATA:
    MT_FIPEX_REVENUE TYPE RANGE OF FM_FIPEX .
  DATA:
    MT_FIPEX_GAINS TYPE RANGE OF FM_FIPEX .
  DATA:
    MT_FMIT TYPE TABLE OF FMIT .
  DATA:
    MT_FUND_FMIT TYPE SORTED TABLE OF TY_FUND_FMIT WITH UNIQUE KEY FIKRS FINCODE .
  DATA:
    MT_FUND_AMOUNT TYPE TABLE OF TY_FUND_AMOUNT .
  DATA:
    MT_FUND TYPE SORTED TABLE OF TY_FUND WITH UNIQUE KEY FIKRS FINCODE .
  DATA:
    MT_FUND_C5 TYPE SORTED TABLE OF TY_FUND_C5 WITH NON-UNIQUE KEY FIKRS FINCODE .
  DATA:
    MT_PROJ_WBS TYPE TABLE OF TY_PROJ_WBS .
  DATA:
    MT_LIST TYPE TABLE OF TY_LIST .

  METHODS GET_DATA_FROM_FMIT .
  METHODS READ_WBS_TEXT
    IMPORTING
      !IV_PSPNR      TYPE PS_POSNR
    RETURNING
      VALUE(RV_TEXT) TYPE STRING .
  METHODS PREPARE_DATA .
  METHODS GET_PS_DATA .
  METHODS GET_FUNDS .
  METHODS INITIALIZE_DATA .

* ---- YCL_FM_FUND_CASH_BAL_WITH_PS==CM001 ----
  METHOD GET_DATA.

    ME->INITIALIZE_DATA( ).
    ME->GET_DATA_FROM_FMIT( ).
    CHECK MT_FUND_FMIT IS NOT INITIAL.
    ME->GET_FUNDS( ).
    CHECK MT_FUND IS NOT INITIAL.
    ME->GET_PS_DATA( ).
    ME->PREPARE_DATA( ).

  ENDMETHOD.

* ---- YCL_FM_FUND_CASH_BAL_WITH_PS==CM002 ----
  METHOD INITIALIZE_DATA.

    "Get FM area from company code
    SELECT SINGLE FIKRS FROM T001 WHERE BUKRS = @MP_BUKRS INTO @MV_FIKRS.

    "Get local currency
    SELECT SINGLE WAERS FROM FM01 WHERE FIKRS = @MV_FIKRS INTO @MV_FM_WAERS.

    "Get commitment item 'REVENUE'
    APPEND VALUE #( SIGN = 'I' OPTION = 'EQ' LOW = 'REVENUE' ) TO MT_FIPEX_REVENUE.
    "Get commitment item 'GAINS'
    APPEND VALUE #( SIGN = 'I' OPTION = 'EQ' LOW = 'GAINS' ) TO MT_FIPEX_GAINS.

  ENDMETHOD.

* ---- YCL_FM_FUND_CASH_BAL_WITH_PS==CM004 ----
  METHOD GET_FUNDS.

    "Get fund from selection
    SELECT DISTINCT A~FIKRS,
                    A~FINCODE,
                    A~TYPE,
                    B~BESCHR,
                    A~DATAB,
                    A~DATBIS,
                    A~FINCODE AS FUND_PSPID
                    FROM FMFINCODE AS A
                    INNER JOIN FMFINT AS B ON  B~SPRAS = @SY-LANGU
                                           AND B~FIKRS = A~FIKRS
                                           AND B~FINCODE = A~FINCODE
                    LEFT OUTER JOIN YTFM_FUND_C5 AS C ON  C~FIKRS = A~FIKRS
                                                      AND C~FINCODE = A~FINCODE
                    FOR ALL ENTRIES IN @MT_FUND_FMIT
                    WHERE A~FIKRS = @MT_FUND_FMIT-FIKRS
                    AND   A~FINCODE = @MT_FUND_FMIT-FINCODE
                    AND   C~C5_ID IN @MR_C5
                    INTO TABLE @MT_FUND.

    CHECK MT_FUND IS NOT INITIAL.

    "Get C5 assignment for fiscal year
    SELECT A~FIKRS, A~FINCODE, A~C5_ID, C~YEAR_FROM, C~YEAR_TO, A~C5_SEL, A~FM_OUTPUT, O~OTYPE, T~ONAME, T~OTEXT
           FROM YTFM_FUND_C5 AS A
           INNER JOIN YTFM_C5 AS C ON C~C5_ID = A~C5_ID
           LEFT OUTER JOIN YTFM_OUTPUT AS O ON O~FM_OUTPUT = A~FM_OUTPUT
           LEFT OUTER JOIN YTFM_OUTPUT_T AS T ON  T~SPRSL = @SY-LANGU
                                              AND T~FM_OUTPUT = A~FM_OUTPUT
           FOR ALL ENTRIES IN @MT_FUND
           WHERE A~FIKRS = @MT_FUND-FIKRS
           AND   A~FINCODE = @MT_FUND-FINCODE
           AND   C~YEAR_FROM <= @MP_ENDPER(4)
           AND   C~YEAR_TO >= @MP_BEGPER(4)
           INTO TABLE @MT_FUND_C5.

  ENDMETHOD.

* ---- YCL_FM_FUND_CASH_BAL_WITH_PS==CM005 ----
  METHOD INIT_ALV.

    SUPER->INIT_ALV( EXPORTING IV_REPID = IV_REPID
                     CHANGING CT_TABLE = MT_LIST ).

  ENDMETHOD.

* ---- YCL_FM_FUND_CASH_BAL_WITH_PS==CM006 ----
  METHOD GET_PS_DATA.

    SELECT P~PSPNR AS PROJ_PSPNR,
           P~PSPID,
           P~POSTU,
           P~PWHIE,
           P~PROFL,
           P~BPROF,
           W~PSPNR AS PRPS_PSPNR,
           W~POSID,
           W~PBUKR,
           W~PGSBR,
           W~PRART,
           W~STUFE,
           W~POST1 AS DESCR,
           W~YYE_DONOR,
           W~YYE_EXEC_AGENCY,
           W~YYE_IMPL_AGENCY,
           W~YYE_TYP_SOU,
           W~YYE_EXEC,
           W~YYE_PRCRT
           FROM PROJ AS P
           LEFT OUTER JOIN PRPS AS W ON W~POSID = P~PSPID
           FOR ALL ENTRIES IN @MT_FUND
           WHERE PSPID = @MT_FUND-FUND_PSPID
           AND   VBUKR = @MP_BUKRS
           INTO TABLE @MT_PROJ_WBS.

  ENDMETHOD.

* ---- YCL_FM_FUND_CASH_BAL_WITH_PS==CM007 ----
  METHOD PREPARE_DATA.

    DATA LS_LIST TYPE TY_LIST.

    LOOP AT MT_FUND INTO DATA(LS_FUND).
      CLEAR LS_LIST.
      "Fund data
      MOVE-CORRESPONDING LS_FUND TO LS_LIST.
      "Fund assignment to C5
      LOOP AT MT_FUND_C5 INTO DATA(LS_FUND_C5) WHERE FIKRS = LS_FUND-FIKRS
                                               AND   FINCODE = LS_FUND-FINCODE
                                               AND   YEAR_FROM <= MP_BEGPER(4)
                                               AND   YEAR_TO >= MP_BEGPER(4).
        EXIT.
      ENDLOOP.
      IF SY-SUBRC = 0.
        LS_LIST-C5_ID = LS_FUND_C5-C5_ID.
        LS_LIST-C5_SEL = LS_FUND_C5-C5_SEL.
        LS_LIST-FM_OUTPUT = LS_FUND_C5-FM_OUTPUT.
        LS_LIST-OTYPE = LS_FUND_C5-OTYPE.
        LS_LIST-ONAME = LS_FUND_C5-ONAME.
        LS_LIST-OTEXT = LS_FUND_C5-OTEXT.
      ENDIF.
      "PS data
      READ TABLE MT_PROJ_WBS INTO DATA(LS_PROJ_WBS) WITH KEY PSPID = LS_FUND-FUND_PSPID.
      IF SY-SUBRC = 0.
        MOVE-CORRESPONDING LS_PROJ_WBS TO LS_LIST.
      ELSEIF MP_PROJ = ABAP_TRUE.
        CONTINUE.
      ENDIF.
      "WBS long text
      LS_LIST-DESCR = ME->READ_WBS_TEXT( LS_LIST-PRPS_PSPNR ).
      "Amounts
      READ TABLE MT_FUND_AMOUNT INTO DATA(LS_FUND_AMOUNT) WITH KEY FINCODE = LS_FUND-FINCODE.
      IF SY-SUBRC = 0.
        MOVE-CORRESPONDING LS_FUND_AMOUNT TO LS_LIST.
      ENDIF.
      "Calculate balance
      LS_LIST-BALANCE = LS_LIST-CF + LS_LIST-REVENUE + LS_LIST-GAINS + LS_LIST-COST.
      "Set to ALV list
      APPEND LS_LIST TO MT_LIST.
    ENDLOOP.

  ENDMETHOD.

* ---- YCL_FM_FUND_CASH_BAL_WITH_PS==CM008 ----
  METHOD SET_DISPLAY_SETTINGS.

    SUPER->SET_DISPLAY_SETTINGS( ).
    MO_DISPLAY_SETTINGS->SET_STRIPED_PATTERN( ABAP_TRUE ).

  ENDMETHOD.

* ---- YCL_FM_FUND_CASH_BAL_WITH_PS==CM009 ----
  METHOD SET_ALV_COLUMNS.

    DATA LO_COLUMN TYPE REF TO CL_SALV_COLUMN_TABLE.

    SUPER->SET_ALV_COLUMNS( ).

    TRY.
        LO_COLUMN ?= MO_SALV_COLUMNS_TABLE->GET_COLUMN( 'BESCHR' ).
        LO_COLUMN->SET_LONG_TEXT( 'Fund description' ).
        LO_COLUMN->SET_FIXED_HEADER_TEXT( 'L' ).
      CATCH CX_SALV_NOT_FOUND.
    ENDTRY.

    TRY.
        LO_COLUMN ?= MO_SALV_COLUMNS_TABLE->GET_COLUMN( 'FM_OUTPUT' ).
        LO_COLUMN->SET_LONG_TEXT( 'Output id' ).
        LO_COLUMN->SET_FIXED_HEADER_TEXT( 'L' ).
      CATCH CX_SALV_NOT_FOUND.
    ENDTRY.

    TRY.
        LO_COLUMN ?= MO_SALV_COLUMNS_TABLE->GET_COLUMN( 'OTYPE' ).
        LO_COLUMN->SET_LONG_TEXT( 'Output type' ).
        LO_COLUMN->SET_FIXED_HEADER_TEXT( 'L' ).
      CATCH CX_SALV_NOT_FOUND.
    ENDTRY.

    TRY.
        LO_COLUMN ?= MO_SALV_COLUMNS_TABLE->GET_COLUMN( 'ONAME' ).
        LO_COLUMN->SET_LONG_TEXT( 'Output name' ).
        LO_COLUMN->SET_FIXED_HEADER_TEXT( 'L' ).
        LO_COLUMN->SET_VISIBLE( ABAP_FALSE ).
      CATCH CX_SALV_NOT_FOUND.
    ENDTRY.

    TRY.
        LO_COLUMN ?= MO_SALV_COLUMNS_TABLE->GET_COLUMN( 'FUND_PSPID' ).
        LO_COLUMN->SET_TECHNICAL( ABAP_TRUE ).
      CATCH CX_SALV_NOT_FOUND.
    ENDTRY.

    TRY.
        LO_COLUMN ?= MO_SALV_COLUMNS_TABLE->GET_COLUMN( 'PROJ_PSPNR' ).
        LO_COLUMN->SET_TECHNICAL( ABAP_TRUE ).
      CATCH CX_SALV_NOT_FOUND.
    ENDTRY.

    TRY.
        LO_COLUMN ?= MO_SALV_COLUMNS_TABLE->GET_COLUMN( 'PSPID' ).
        LO_COLUMN->SET_TECHNICAL( ABAP_TRUE ).
      CATCH CX_SALV_NOT_FOUND.
    ENDTRY.

    TRY.
        LO_COLUMN ?= MO_SALV_COLUMNS_TABLE->GET_COLUMN( 'POSTU' ).
        LO_COLUMN->SET_LONG_TEXT( 'Project description' ).
        LO_COLUMN->SET_FIXED_HEADER_TEXT( 'L' ).
      CATCH CX_SALV_NOT_FOUND.
    ENDTRY.

    TRY.
        LO_COLUMN ?= MO_SALV_COLUMNS_TABLE->GET_COLUMN( 'PROFL' ).
        LO_COLUMN->SET_FIXED_HEADER_TEXT( 'M' ).
      CATCH CX_SALV_NOT_FOUND.
    ENDTRY.

    TRY.
        LO_COLUMN ?= MO_SALV_COLUMNS_TABLE->GET_COLUMN( 'BPROF' ).
        LO_COLUMN->SET_FIXED_HEADER_TEXT( 'M' ).
      CATCH CX_SALV_NOT_FOUND.
    ENDTRY.

    TRY.
        LO_COLUMN ?= MO_SALV_COLUMNS_TABLE->GET_COLUMN( 'PRPS_PSPNR' ).
        LO_COLUMN->SET_TECHNICAL( ABAP_TRUE ).
      CATCH CX_SALV_NOT_FOUND.
    ENDTRY.

    TRY.
        LO_COLUMN ?= MO_SALV_COLUMNS_TABLE->GET_COLUMN( 'POSID' ).
        LO_COLUMN->SET_TECHNICAL( ABAP_TRUE ).
      CATCH CX_SALV_NOT_FOUND.
    ENDTRY.

    TRY.
        LO_COLUMN ?= MO_SALV_COLUMNS_TABLE->GET_COLUMN( 'DESCR' ).
        LO_COLUMN->SET_LONG_TEXT( 'WBS description' ).
        LO_COLUMN->SET_FIXED_HEADER_TEXT( 'L' ).
      CATCH CX_SALV_NOT_FOUND.
    ENDTRY.

    TRY.
        LO_COLUMN ?= MO_SALV_COLUMNS_TABLE->GET_COLUMN( 'CF' ).
        LO_COLUMN->SET_LONG_TEXT( 'Carried forward' ).
        LO_COLUMN->SET_FIXED_HEADER_TEXT( 'L' ).
      CATCH CX_SALV_NOT_FOUND.
    ENDTRY.

    TRY.
        LO_COLUMN ?= MO_SALV_COLUMNS_TABLE->GET_COLUMN( 'REVENUE' ).
        LO_COLUMN->SET_LONG_TEXT( 'Revenue' ).
        LO_COLUMN->SET_FIXED_HEADER_TEXT( 'L' ).
      CATCH CX_SALV_NOT_FOUND.
    ENDTRY.

    TRY.
        LO_COLUMN ?= MO_SALV_COLUMNS_TABLE->GET_COLUMN( 'GAINS' ).
        LO_COLUMN->SET_LONG_TEXT( 'Gains' ).
        LO_COLUMN->SET_FIXED_HEADER_TEXT( 'L' ).
      CATCH CX_SALV_NOT_FOUND.
    ENDTRY.

    TRY.
        LO_COLUMN ?= MO_SALV_COLUMNS_TABLE->GET_COLUMN( 'COST' ).
        LO_COLUMN->SET_LONG_TEXT( 'Cost' ).
        LO_COLUMN->SET_FIXED_HEADER_TEXT( 'L' ).
      CATCH CX_SALV_NOT_FOUND.
    ENDTRY.

    TRY.
        LO_COLUMN ?= MO_SALV_COLUMNS_TABLE->GET_COLUMN( 'BALANCE' ).
        LO_COLUMN->SET_LONG_TEXT( 'Balance' ).
        LO_COLUMN->SET_FIXED_HEADER_TEXT( 'L' ).
      CATCH CX_SALV_NOT_FOUND.
    ENDTRY.

  ENDMETHOD.

* ---- YCL_FM_FUND_CASH_BAL_WITH_PS==CM00A ----
  METHOD READ_WBS_TEXT.

    DATA LT_LINES TYPE TABLE OF TLINE.
    DATA LV_TDNAME TYPE THEAD-TDNAME.
    DATA LT_STRING TYPE STRING_TABLE.

    LV_TDNAME = |E{ IV_PSPNR }|.

    CALL FUNCTION 'READ_TEXT'
      EXPORTING
*       CLIENT                  = SY-MANDT
        ID                      = 'LTXT'
        LANGUAGE                = 'E'
        NAME                    = LV_TDNAME
        OBJECT                  = 'PMS'
*       ARCHIVE_HANDLE          = 0
*       LOCAL_CAT               = ' '
* IMPORTING
*       HEADER                  =
*       OLD_LINE_COUNTER        =
      TABLES
        LINES                   = LT_LINES
      EXCEPTIONS
        ID                      = 1
        LANGUAGE                = 2
        NAME                    = 3
        NOT_FOUND               = 4
        OBJECT                  = 5
        REFERENCE_CHECK         = 6
        WRONG_ACCESS_TO_ARCHIVE = 7
        OTHERS                  = 8.

    CHECK LT_LINES IS NOT INITIAL.

    CALL FUNCTION 'CONVERT_ITF_TO_STREAM_TEXT'
      EXPORTING
        LANGUAGE     = 'E'
        LF           = ABAP_TRUE
      IMPORTING
        STREAM_LINES = LT_STRING
      TABLES
        ITF_TEXT     = LT_LINES.

    LOOP AT LT_STRING INTO DATA(LV_STRING).
      DATA(LV_TABIX) = SY-TABIX.
      REPLACE ALL OCCURRENCES OF '#' IN LV_STRING WITH SPACE.
      IF LV_TABIX = 1.
        RV_TEXT = LV_STRING.
      ELSE.
        IF LV_STRING IS INITIAL.
          CONTINUE.
        ENDIF.
        CONCATENATE RV_TEXT LV_STRING INTO RV_TEXT SEPARATED BY SPACE.
      ENDIF.
    ENDLOOP.

  ENDMETHOD.

* ---- YCL_FM_FUND_CASH_BAL_WITH_PS==CM00B ----
  METHOD GET_DATA_FROM_FMIT.

    DATA LS_FUND_FMIT TYPE TY_FUND_FMIT.
    DATA LV_NUM(2) TYPE N.
    DATA LV_PERIO TYPE YE_PERIOD.
    DATA LV_FIELDNAME TYPE FIELDNAME.
    DATA LS_FUND_AMOUNT TYPE TY_FUND_AMOUNT.
    FIELD-SYMBOLS <AMOUNT> TYPE ANY.

    SELECT * FROM FMIT WHERE RLDNR = '9A'
                       AND   RRCTY = '0'
                       AND   RVERS = '000'
                       AND   RYEAR >= @MP_BEGPER(4)
                       AND   RYEAR <= @MP_ENDPER(4)
                       AND   RBUKRS = @MP_BUKRS
                       AND   RFONDS IN @MR_FUND
                       AND   RBUSA IN @MR_GSBER
                       AND   RWRTTP IN @MR_WRTTP
            INTO TABLE @MT_FMIT.

    LOOP AT MT_FMIT INTO DATA(LS_FMIT).
      "Collect fund
      LS_FUND_FMIT-FIKRS = MV_FIKRS.
      LS_FUND_FMIT-FINCODE = LS_FMIT-RFONDS.
      INSERT LS_FUND_FMIT INTO TABLE MT_FUND_FMIT.
      "Get amounts
      CLEAR: LV_NUM, LV_PERIO, LS_FUND_AMOUNT.
      LS_FUND_AMOUNT-FINCODE = LS_FMIT-RFONDS.
      LS_FUND_AMOUNT-WAERS = MV_FM_WAERS.
      "Carried formward amount
      LS_FUND_AMOUNT-CF = LS_FMIT-HSLVT.
      DO 16 TIMES.
        ADD 1 TO LV_NUM.
        LV_PERIO = |{ LS_FMIT-RYEAR }{ LV_NUM }|.
        CHECK LV_PERIO BETWEEN MP_BEGPER AND MP_ENDPER.
        LV_FIELDNAME = |LS_FMIT-HSL{ LV_NUM }|.
        ASSIGN (LV_FIELDNAME) TO <AMOUNT>.
        IF LS_FMIT-RFIPEX IN MT_FIPEX_REVENUE.
          ADD <AMOUNT> TO LS_FUND_AMOUNT-REVENUE.
        ELSEIF  LS_FMIT-RFIPEX IN MT_FIPEX_GAINS.
          ADD <AMOUNT> TO LS_FUND_AMOUNT-GAINS.
        ELSE.
          ADD <AMOUNT> TO LS_FUND_AMOUNT-COST.
        ENDIF.
      ENDDO.
      COLLECT LS_FUND_AMOUNT INTO MT_FUND_AMOUNT.
    ENDLOOP.

  ENDMETHOD.

* ---- YCL_FM_FUND_CASH_BAL_WITH_PS==CO ----
PROTECTED SECTION.

  METHODS SET_DISPLAY_SETTINGS
    REDEFINITION .
  METHODS SET_ALV_COLUMNS
    REDEFINITION .

* ---- YCL_FM_FUND_CASH_BAL_WITH_PS==CU ----
CLASS YCL_FM_FUND_CASH_BAL_WITH_PS DEFINITION
  PUBLIC
  INHERITING FROM YCL_CA_REPORT_SHARE_STATEMENTS
  FINAL
  CREATE PUBLIC .

PUBLIC SECTION.

  DATA MP_BEGPER TYPE YE_PERIOD .
  DATA MP_ENDPER TYPE YE_PERIOD .
  DATA MP_PROJ TYPE XFELD .
  DATA MP_BUKRS TYPE BUKRS .
  DATA:
    MR_FUND TYPE RANGE OF BP_GEBER .
  DATA:
    MR_GSBER TYPE RANGE OF GSBER .
  DATA:
    MR_WRTTP TYPE RANGE OF FM_WRTTP .
  DATA:
    MR_C5 TYPE RANGE OF YE_FM_C5_ID .

  METHODS GET_DATA .

  METHODS INIT_ALV
    REDEFINITION .