* ==== CLASS POOL YCL_FI_RFBIBL00_SHM_ROOT ====
CLASS-POOL .
*"* class pool for class YCL_FI_RFBIBL00_SHM_ROOT

*"* local type definitions
INCLUDE YCL_FI_RFBIBL00_SHM_ROOT======CCDEF.

*"* class YCL_FI_RFBIBL00_SHM_ROOT definition
*"* public declarations
  INCLUDE YCL_FI_RFBIBL00_SHM_ROOT======CU.
*"* protected declarations
  INCLUDE YCL_FI_RFBIBL00_SHM_ROOT======CO.
*"* private declarations
  INCLUDE YCL_FI_RFBIBL00_SHM_ROOT======CI.
ENDCLASS. "YCL_FI_RFBIBL00_SHM_ROOT definition

*"* macro definitions
INCLUDE YCL_FI_RFBIBL00_SHM_ROOT======CCMAC.
*"* local class implementation
INCLUDE YCL_FI_RFBIBL00_SHM_ROOT======CCIMP.

CLASS YCL_FI_RFBIBL00_SHM_ROOT IMPLEMENTATION.
*"* method's implementations
  INCLUDE METHODS.
ENDCLASS. "YCL_FI_RFBIBL00_SHM_ROOT implementation


* ---- YCL_FI_RFBIBL00_SHM_ROOT======CI ----
PRIVATE SECTION.

  DATA MT_BIBL_FILE TYPE YTT_STRING .
  DATA MT_MESSAGE TYPE FB_T_FIMSG .
  DATA MV_ERROR_RUN TYPE XFELD .
  DATA MV_GET_PROTOCOL TYPE XFELD .

* ---- YCL_FI_RFBIBL00_SHM_ROOT======CM001 ----
  METHOD SET_SHARED_MEMORY.

    MV_GET_PROTOCOL = IV_GET_PROTOCOL.
    MT_MESSAGE = IT_MESSAGE.
    MV_ERROR_RUN = IV_ERROR_RUN.
    MT_BIBL_FILE = IT_BIBL_FILE.

  ENDMETHOD.

* ---- YCL_FI_RFBIBL00_SHM_ROOT======CM002 ----
  METHOD GET_SHARED_MEMORY.

    EV_GET_PROTOCOL = MV_GET_PROTOCOL.
    ET_MESSAGE = MT_MESSAGE.
    EV_ERROR_RUN = MV_ERROR_RUN.
    ET_BIBL_FILE = MT_BIBL_FILE.

  ENDMETHOD.

* ---- YCL_FI_RFBIBL00_SHM_ROOT======CO ----
PROTECTED SECTION.

* ---- YCL_FI_RFBIBL00_SHM_ROOT======CU ----
CLASS YCL_FI_RFBIBL00_SHM_ROOT DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC
  SHARED MEMORY ENABLED .

PUBLIC SECTION.

  METHODS GET_SHARED_MEMORY
    EXPORTING
      !EV_GET_PROTOCOL TYPE XFELD
      !ET_MESSAGE TYPE FB_T_FIMSG
      !EV_ERROR_RUN TYPE XFELD
      !ET_BIBL_FILE TYPE YTT_STRING .
  METHODS SET_SHARED_MEMORY
    IMPORTING
      !IV_GET_PROTOCOL TYPE XFELD OPTIONAL
      !IT_MESSAGE TYPE FB_T_FIMSG OPTIONAL
      !IV_ERROR_RUN TYPE XFELD OPTIONAL
      !IT_BIBL_FILE TYPE YTT_STRING OPTIONAL .