* ==== CLASS POOL YCL_FI_CUSTOMER_BL ====
CLASS-POOL .
*"* class pool for class YCL_FI_CUSTOMER_BL

*"* local type definitions
INCLUDE YCL_FI_CUSTOMER_BL============CCDEF.

*"* class YCL_FI_CUSTOMER_BL definition
*"* public declarations
  INCLUDE YCL_FI_CUSTOMER_BL============CU.
*"* protected declarations
  INCLUDE YCL_FI_CUSTOMER_BL============CO.
*"* private declarations
  INCLUDE YCL_FI_CUSTOMER_BL============CI.
ENDCLASS. "YCL_FI_CUSTOMER_BL definition

*"* macro definitions
INCLUDE YCL_FI_CUSTOMER_BL============CCMAC.
*"* local class implementation
INCLUDE YCL_FI_CUSTOMER_BL============CCIMP.

CLASS YCL_FI_CUSTOMER_BL IMPLEMENTATION.
*"* method's implementations
  INCLUDE METHODS.
ENDCLASS. "YCL_FI_CUSTOMER_BL implementation


* ---- YCL_FI_CUSTOMER_BL============CI ----
PRIVATE SECTION.

  TYPES:
    TTY_WORDS TYPE TABLE OF TEXT40 .

  CLASS-DATA:
    MT_KNA1 TYPE TABLE OF YSFI_CUSTOMER_MAIN_1 .
  CLASS-DATA:
    MT_KUNNR TYPE TABLE OF KUNNR .

  CLASS-METHODS SEARCH_IN_KNA1_ADRC
    IMPORTING
      VALUE(IV_WHERE_CLAUSE) TYPE STRING .
  CLASS-METHODS PREPARE_WORDS
    IMPORTING
      VALUE(IV_NAME) TYPE TEXT80
    EXPORTING
      VALUE(ET_WORDS) TYPE TTY_WORDS .
  CLASS-METHODS PREPARE_WHERE_CLAUSE_FOR_NAME
    IMPORTING
      !IV_WORD TYPE TEXT40
    EXPORTING
      !EV_STRING TYPE STRING .
  CLASS-METHODS READ_KNA1
    IMPORTING
      !IV_MAX_ROW TYPE I
    RETURNING
      VALUE(RT_DATA) TYPE YTTFI_CUSTOMER_DATA_1 .

* ---- YCL_FI_CUSTOMER_BL============CM001 ----
  METHOD GET_ID_FROM_SALESFORCE_ID.

    DATA LT_KUNNR TYPE TABLE OF KUNNR.

    SELECT KUNNR FROM KNA1 WHERE BAHNS = @IV_BAHNS INTO TABLE @LT_KUNNR.

    CASE LINES( LT_KUNNR ).
      WHEN 0.
        RAISE EXCEPTION TYPE YCX_FI_DATA
          EXPORTING
            TEXTID   = YCX_FI_DATA=>NO_CUSTOMER_ID_FOUND
            ID_TYPE  = 'SalesForce id'
            ID_VALUE = IV_BAHNS.
      WHEN 1.
        READ TABLE LT_KUNNR INTO RV_KUNNR INDEX 1.
      WHEN OTHERS.
        RAISE EXCEPTION TYPE YCX_FI_DATA
          EXPORTING
            TEXTID   = YCX_FI_DATA=>MORE_THEN_ONE_ID_FOUND
            ID_TYPE  = 'SalesForce id'
            ID_VALUE = IV_BAHNS.
    ENDCASE.

  ENDMETHOD.

* ---- YCL_FI_CUSTOMER_BL============CM002 ----
  METHOD CREATE_CUSTOMER.

    DATA LS_CUSTOMERS TYPE CMDS_EI_MAIN.
    DATA LS_CUSTOMER TYPE CMDS_EI_EXTERN.
    DATA LS_COMPANY TYPE CMDS_EI_COMPANY.
    DATA LS_DUNNING TYPE CMDS_EI_DUNNING.
    DATA LS_PHONE TYPE CVIS_EI_PHONE_STR.
    DATA LS_EMAIL TYPE CVIS_EI_SMTP_STR.
    DATA LS_MESSAGES TYPE CVIS_MESSAGE.

    EV_IS_OK = ABAP_FALSE.
    CLEAR: ET_MESSAGE, EV_KUNNR.

    "Set header data
    LS_CUSTOMER-HEADER-OBJECT_TASK = CVI_EI_API_MAP_STRUCTURE=>GC_INSERT.

    "Set main data
    MOVE-CORRESPONDING IS_MAIN TO LS_CUSTOMER-CENTRAL_DATA-CENTRAL-DATA.
    MOVE-CORRESPONDING IS_MAIN TO LS_CUSTOMER-CENTRAL_DATA-ADDRESS-POSTAL-DATA.
    LS_CUSTOMER-CENTRAL_DATA-ADDRESS-POSTAL-DATA-FROM_DATE = '00010101'.
    LS_CUSTOMER-CENTRAL_DATA-ADDRESS-POSTAL-DATA-TO_DATE = '99991231'.
    "Main phone number
    IF IS_MAIN-TEL_NUMBER IS NOT INITIAL.
      CLEAR LS_PHONE.
      LS_PHONE-CONTACT-DATA-TELEPHONE = IS_MAIN-TEL_NUMBER.
      LS_PHONE-CONTACT-DATA-STD_NO = 'X'.
      LS_PHONE-CONTACT-DATA-HOME_FLAG = 'X'.
      LS_PHONE-CONTACT-DATA-R_3_USER = '1'.
      APPEND LS_PHONE TO LS_CUSTOMER-CENTRAL_DATA-ADDRESS-COMMUNICATION-PHONE-PHONE.
    ENDIF.
    "Mobile phone
    IF IS_MAIN-MOB_NUMBER IS NOT INITIAL.
      CLEAR LS_PHONE.
      LS_PHONE-CONTACT-DATA-TELEPHONE = IS_MAIN-MOB_NUMBER.
      LS_PHONE-CONTACT-DATA-R_3_USER = '3'.
      APPEND LS_PHONE TO LS_CUSTOMER-CENTRAL_DATA-ADDRESS-COMMUNICATION-PHONE-PHONE.
    ENDIF.
    "E-mails
    IF IS_MAIN-EMAIL1 IS NOT INITIAL.
      CLEAR LS_EMAIL.
      LS_EMAIL-CONTACT-DATA-E_MAIL = IS_MAIN-EMAIL1.
      LS_EMAIL-CONTACT-DATA-STD_NO = 'X'.
      LS_EMAIL-CONTACT-DATA-HOME_FLAG = 'X'.
      APPEND LS_EMAIL TO LS_CUSTOMER-CENTRAL_DATA-ADDRESS-COMMUNICATION-SMTP-SMTP.
    ENDIF.
    IF IS_MAIN-EMAIL2 IS NOT INITIAL.
      CLEAR LS_EMAIL.
      LS_EMAIL-CONTACT-DATA-E_MAIL = IS_MAIN-EMAIL2.
      APPEND LS_EMAIL TO LS_CUSTOMER-CENTRAL_DATA-ADDRESS-COMMUNICATION-SMTP-SMTP.
    ENDIF.

    "Set company data
    IF IS_CCODE IS NOT INITIAL.
      LS_COMPANY-TASK = CVI_EI_API_MAP_STRUCTURE=>GC_INSERT.
      LS_COMPANY-DATA_KEY-BUKRS = IS_CCODE-BUKRS.
      MOVE-CORRESPONDING IS_CCODE TO LS_COMPANY-DATA.
      LS_DUNNING-TASK = CVI_EI_API_MAP_STRUCTURE=>GC_INSERT.
      LS_DUNNING-DATA-MAHNA = IS_CCODE-MAHNA.
      APPEND LS_DUNNING TO LS_COMPANY-DUNNING-DUNNING.
      APPEND LS_COMPANY TO LS_CUSTOMER-COMPANY_DATA-COMPANY.
    ENDIF.

    APPEND LS_CUSTOMER TO LS_CUSTOMERS-CUSTOMERS.

    "Create customer
*    cmd_ei_api=>maintain( EXPORTING iv_test_run    = iv_test
*                                    is_master_data = ls_customers
*                          IMPORTING es_error       = ls_messages ).
    CMD_EI_API=>MAINTAIN_DIRECT_INPUT( EXPORTING IV_TEST_RUN = IV_TEST
                                                 IS_MASTER_DATA = LS_CUSTOMERS
                                       IMPORTING ES_MASTER_DATA_CORRECT = DATA(LS_DATA_CORRECT)
                                                 ES_MESSAGE_CORRECT = DATA(LS_MESSAGE_CORRECT)
                                                 ES_MASTER_DATA_DEFECTIVE = DATA(LS_DATA_DEFECT)
                                                 ES_MESSAGE_DEFECTIVE = DATA(LS_MESSAGE_DEFECT) ).

    IF IV_TEST = ABAP_FALSE AND LS_MESSAGE_DEFECT-IS_ERROR = ABAP_FALSE.
      COMMIT WORK.
    ENDIF.

    APPEND LINES OF LS_MESSAGE_CORRECT-MESSAGES TO ET_MESSAGE.
    APPEND LINES OF LS_MESSAGE_DEFECT-MESSAGES TO ET_MESSAGE.

    IF LS_MESSAGE_DEFECT-IS_ERROR = ABAP_FALSE.
      EV_IS_OK = ABAP_TRUE.
      "Get Customer number
      READ TABLE LS_DATA_CORRECT-CUSTOMERS INTO LS_CUSTOMER INDEX 1.
      IF SY-SUBRC = 0.
        EV_KUNNR = LS_CUSTOMER-HEADER-OBJECT_INSTANCE-KUNNR.
      ENDIF.
    ELSE.
      EV_IS_OK = ABAP_FALSE.
    ENDIF.

  ENDMETHOD.

* ---- YCL_FI_CUSTOMER_BL============CM003 ----
  METHOD PREPARE_WHERE_CLAUSE_FOR_NAME.

    DATA LV_ORIG_UPPER TYPE TEXT40.
    DATA LV_ORIG_LOWER TYPE TEXT40.
    DATA LV_ORIG_MIXED TYPE TEXT40.
    DATA LV_NORM_UPPER TYPE TEXT40.
    DATA LV_NORM_LOWER TYPE TEXT40.
    DATA LV_NORM_MIXED TYPE TEXT40.
    DATA LV_WORD TYPE TEXT40.
    DATA LV_WORD_NORM TYPE TEXT40.

    LV_WORD = IV_WORD.

    CALL FUNCTION 'SCP_REPLACE_STRANGE_CHARS'
      EXPORTING
        INTEXT  = LV_WORD
      IMPORTING
        OUTTEXT = LV_WORD_NORM.

    "Set search words from original word
    TRANSLATE LV_WORD TO UPPER CASE.
    LV_ORIG_UPPER = LV_WORD.
    TRANSLATE LV_WORD TO LOWER CASE.
    LV_ORIG_LOWER = LV_ORIG_MIXED = LV_WORD.
    LV_ORIG_MIXED(1) = LV_ORIG_UPPER(1).

    "Set search word from normalized word
    TRANSLATE LV_WORD_NORM TO UPPER CASE.
    LV_NORM_UPPER = LV_WORD_NORM.
    TRANSLATE LV_WORD_NORM TO LOWER CASE.
    LV_NORM_LOWER = LV_NORM_MIXED = LV_WORD_NORM.
    LV_NORM_MIXED(1) = LV_NORM_UPPER(1).

    "Prepare search clause
    EV_STRING = |( D~NAME1 LIKE '%{ lv_orig_upper }%' OR D~NAME2 LIKE '%{ lv_orig_upper }%' OR D~NAME3 LIKE '%{ lv_orig_upper }%' OR D~NAME4 LIKE '%{ lv_orig_upper }%'|.
    ev_string = |{ EV_STRING } OR D~NAME1 LIKE '%{ lv_orig_lower }%' OR D~NAME2 LIKE '%{ lv_orig_lower }%' OR D~NAME3 LIKE '%{ lv_orig_lower }%' OR D~NAME4 LIKE '%{ lv_orig_lower }%'|.
    ev_string = |{ EV_STRING } OR D~NAME1 LIKE '%{ lv_orig_mixed }%' OR D~NAME2 LIKE '%{ lv_orig_mixed }%' OR D~NAME3 LIKE '%{ lv_orig_mixed }%' OR D~NAME4 LIKE '%{ lv_orig_mixed }%'|.
    ev_string = |{ EV_STRING } OR D~NAME1 LIKE '%{ lv_norm_upper }%' OR D~NAME2 LIKE '%{ lv_norm_upper }%' OR D~NAME3 LIKE '%{ lv_norm_upper }%' OR D~NAME4 LIKE '%{ lv_norm_upper }%'|.
    ev_string = |{ EV_STRING } OR D~NAME1 LIKE '%{ lv_norm_lower }%' OR D~NAME2 LIKE '%{ lv_norm_lower }%' OR D~NAME3 LIKE '%{ lv_norm_lower }%' OR D~NAME4 LIKE '%{ lv_norm_lower }%'|.
    ev_string = |{ EV_STRING } OR D~NAME1 LIKE '%{ lv_norm_mixed }%' OR D~NAME2 LIKE '%{ lv_norm_mixed }%' OR D~NAME3 LIKE '%{ lv_norm_mixed }%' OR D~NAME4 LIKE '%{ lv_norm_mixed }%'|.
    ev_string = |{ EV_STRING } )|.

  ENDMETHOD.

* ---- YCL_FI_CUSTOMER_BL============CM004 ----
  METHOD READ_CUSTOMER.

    DATA LS_CUSTOMERS_IN TYPE CMDS_EI_MAIN.
    DATA LS_CUSTOMER_IN TYPE CMDS_EI_EXTERN.
    DATA LS_CUSTOMERS_OUT TYPE CMDS_EI_MAIN.
    DATA LS_MESSAGES TYPE CVIS_MESSAGE.

    CLEAR: EV_IS_OK, ET_MESSAGE, ES_DATA.

    "Check data first
    IF IV_KUNNR IS INITIAL.
      APPEND YCL_CA_UTILITIES=>SET_TO_BAPIRET2( IV_MSGID = 'YFI1'
                                                IV_MSGNO = '015'
                                                IV_MSGTY = 'E' ) TO ET_MESSAGE.
      EXIT.
    ENDIF.
    "Check customer exists
    SELECT SINGLE * FROM KNA1 WHERE KUNNR = @IV_KUNNR INTO @DATA(LS_KNA1).
    IF SY-SUBRC <> 0.
      APPEND YCL_CA_UTILITIES=>SET_TO_BAPIRET2( IV_MSGID = 'YFI1'
                                                IV_MSGNO = '016'
                                                IV_MSGTY = 'E'
                                                IV_MSGV1 = |{ IV_KUNNR }| ) TO ET_MESSAGE.
      EXIT.
    ENDIF.

    LS_CUSTOMER_IN-HEADER-OBJECT_INSTANCE-KUNNR = IV_KUNNR.
    LS_CUSTOMER_IN-HEADER-OBJECT_TASK = CVI_EI_API_MAP_STRUCTURE=>GC_MODIFY.
    APPEND LS_CUSTOMER_IN TO LS_CUSTOMERS_IN-CUSTOMERS.
* Read complete customer data
    CMD_EI_API_EXTRACT=>GET_DATA( EXPORTING IS_MASTER_DATA = LS_CUSTOMERS_IN
                                  IMPORTING ES_MASTER_DATA = LS_CUSTOMERS_OUT
                                            ES_ERROR       = LS_MESSAGES ).

    IF LS_MESSAGES-IS_ERROR = ABAP_FALSE.
      EV_IS_OK = ABAP_TRUE.
      READ TABLE LS_CUSTOMERS_OUT-CUSTOMERS INTO ES_DATA INDEX 1.
    ENDIF.

    APPEND LINES OF LS_MESSAGES-MESSAGES TO ET_MESSAGE.

  ENDMETHOD.

* ---- YCL_FI_CUSTOMER_BL============CM005 ----
  METHOD READ_KNA1.

    TYPES: BEGIN OF TY_KNA1_TMP.
             INCLUDE TYPE YSFI_CUSTOMER_MAIN_1.
             TYPES: ADRNR TYPE KNA1-ADRNR,
           END OF TY_KNA1_TMP.
    DATA LT_KNA1_TMP TYPE TABLE OF TY_KNA1_TMP.
    DATA LS_KNA1 TYPE YSFI_CUSTOMER_MAIN_1.

    CHECK MT_KUNNR IS NOT INITIAL.

    SELECT A~KUNNR,
           A~KTOKD,
           D~NAME1 AS NAME,
           D~NAME2 AS NAME_2,
           D~NAME3 AS NAME_3,
           D~NAME4 AS NAME_4,
           D~SORT1,
           D~SORT2,
           D~HOUSE_NUM1 AS HOUSE_NO,
           D~STREET,
           D~STR_SUPPL1,
           D~STR_SUPPL2,
           D~STR_SUPPL3,
           D~POST_CODE1 AS POSTL_COD1,
           D~CITY1 AS CITY,
           D~COUNTRY,
           L~LAISO AS LANGU_ISO,
           A~TELF1 AS TEL_NUMBER,
           A~TELF2 AS MOB_NUMBER,
           M~SMTP_ADDR AS EMAIL1,
           A~BAHNS,
           A~DTAMS,
           A~DTAWS,
           A~KONZS,
           A~ADRNR
           FROM KNA1 AS A
           INNER JOIN ADRC AS D ON D~ADDRNUMBER = A~ADRNR
           LEFT OUTER JOIN ADR6 AS M ON  M~ADDRNUMBER = A~ADRNR
                                     AND M~FLGDEFAULT = @ABAP_TRUE
           LEFT OUTER JOIN T002 AS L ON L~SPRAS = D~LANGU
           FOR ALL ENTRIES IN @MT_KUNNR
           WHERE A~KUNNR = @MT_KUNNR-TABLE_LINE
           INTO CORRESPONDING FIELDS OF TABLE @LT_KNA1_TMP
           UP TO @IV_MAX_ROW ROWS.

    LOOP AT LT_KNA1_TMP INTO DATA(LS_KNA1_TMP).
      CLEAR LS_KNA1.
      MOVE-CORRESPONDING LS_KNA1_TMP TO LS_KNA1.
      SELECT SINGLE SMTP_ADDR FROM ADR6 WHERE ADDRNUMBER = @LS_KNA1_TMP-ADRNR
                                        AND   FLGDEFAULT = @ABAP_FALSE
                    INTO @LS_KNA1-EMAIL2.
      APPEND LS_KNA1 TO RT_DATA.
    ENDLOOP.

  ENDMETHOD.

* ---- YCL_FI_CUSTOMER_BL============CM006 ----
  METHOD SEARCH_FOR_CUSTOMER.

    DATA LT_WORDS TYPE TTY_WORDS.
    DATA LV_WORD TYPE TEXT40.
    DATA LV_WHERE_CLAUSE_1 TYPE STRING.
    DATA LV_WHERE_CLAUSE_2 TYPE STRING.
    DATA LV_WHERE_CLAUSE TYPE STRING.
    DATA LV_MAX_ROW TYPE I.
    DATA LV_ROW TYPE I.

    CLEAR: ET_RESULT, MT_KUNNR.

    IF IV_KTOKD IS NOT INITIAL.
      LV_WHERE_CLAUSE_1 = |A~KTOKD = '{ iv_ktokd }'|.
    ENDIF.

    IF IV_LAND1 IS NOT INITIAL.
      lv_where_clause = |A~LAND1 = '{ iv_land1 }'|.
      IF LV_WHERE_CLAUSE_1 IS NOT INITIAL.
        LV_WHERE_CLAUSE_1 = |{ LV_WHERE_CLAUSE_1 } AND { LV_WHERE_CLAUSE }|.
      ELSE.
        LV_WHERE_CLAUSE_1 = LV_WHERE_CLAUSE.
      ENDIF.
    ENDIF.

    IF IV_SORT IS NOT INITIAL.
      LV_WHERE_CLAUSE = |( D~SORT1 LIKE '%{ iv_sort }%' OR D~SORT2 LIKE '%{ iv_sort }%' )|.
      IF LV_WHERE_CLAUSE_1 IS NOT INITIAL.
        LV_WHERE_CLAUSE_1 = |{ LV_WHERE_CLAUSE_1 } AND { LV_WHERE_CLAUSE }|.
      ELSE.
        LV_WHERE_CLAUSE_1 = LV_WHERE_CLAUSE.
      ENDIF.
    ENDIF.

    IF IV_NAME IS NOT INITIAL.
      PREPARE_WORDS( EXPORTING IV_NAME = IV_NAME
                     IMPORTING ET_WORDS = LT_WORDS ).
      LOOP AT LT_WORDS INTO LV_WORD.
        CLEAR: LV_WHERE_CLAUSE, LV_WHERE_CLAUSE_2.
        "Prepare where clause
        PREPARE_WHERE_CLAUSE_FOR_NAME( EXPORTING IV_WORD = LV_WORD
                                       IMPORTING EV_STRING = LV_WHERE_CLAUSE_2 ).
        IF LV_WHERE_CLAUSE_1 IS NOT INITIAL.
          LV_WHERE_CLAUSE = |{ LV_WHERE_CLAUSE_1 } AND { LV_WHERE_CLAUSE_2 }|.
        ELSE.
          LV_WHERE_CLAUSE = LV_WHERE_CLAUSE_2.
        ENDIF.
        "Get customers from database
        SEARCH_IN_KNA1_ADRC( IV_WHERE_CLAUSE = LV_WHERE_CLAUSE ).
        IF MT_KUNNR IS INITIAL.
          EXIT.
        ENDIF.
      ENDLOOP.
    ELSEIF LV_WHERE_CLAUSE_1 IS NOT INITIAL.
      "Get customers from database
      SEARCH_IN_KNA1_ADRC( IV_WHERE_CLAUSE = LV_WHERE_CLAUSE_1 ).
    ENDIF.

    IF MT_KUNNR IS NOT INITIAL.
      ET_RESULT = READ_KNA1( IV_MAX_ROW = IV_MAX_ROW ).
    ENDIF.

  ENDMETHOD.

* ---- YCL_FI_CUSTOMER_BL============CM007 ----
  METHOD UPDATE_CUSTOMER.

    DATA LS_CUSTOMERS TYPE CMDS_EI_MAIN.
    DATA LS_CUSTOMER TYPE CMDS_EI_EXTERN.
    DATA LS_CUSTOMER_BEFORE TYPE CMDS_EI_EXTERN.
    DATA LS_COMPANY TYPE CMDS_EI_COMPANY.
    DATA LS_DUNNING TYPE CMDS_EI_DUNNING.
    DATA LS_PHONE TYPE CVIS_EI_PHONE_STR.
    DATA LS_EMAIL TYPE CVIS_EI_SMTP_STR.
    DATA LS_MESSAGES TYPE CVIS_MESSAGE.
    DATA LT_MESSAGE TYPE BAPIRET2_T.
    FIELD-SYMBOLS <LS_PHONE> TYPE CVIS_EI_PHONE_STR.
    FIELD-SYMBOLS <LS_EMAIL> TYPE CVIS_EI_SMTP_STR.
    FIELD-SYMBOLS <LS_COMPANY> TYPE CMDS_EI_COMPANY.

    EV_IS_OK = ABAP_FALSE.
    CLEAR ET_MESSAGE.

    "Read customer
    READ_CUSTOMER( EXPORTING IV_KUNNR = IS_MAIN-KUNNR
                   IMPORTING ES_DATA = LS_CUSTOMER_BEFORE
                             EV_IS_OK = EV_IS_OK
                             ET_MESSAGE = LT_MESSAGE ).
    IF EV_IS_OK = ABAP_FALSE.
      APPEND LINES OF LT_MESSAGE TO ET_MESSAGE.
      EXIT.
    ENDIF.

    EV_IS_OK = ABAP_FALSE.

    "Set header data
    LS_CUSTOMER-HEADER-OBJECT_INSTANCE-KUNNR = IS_MAIN-KUNNR.
    LS_CUSTOMER-HEADER-OBJECT_TASK = CVI_EI_API_MAP_STRUCTURE=>GC_UPDATE.

    "Set main data
    MOVE-CORRESPONDING IS_MAIN TO LS_CUSTOMER-CENTRAL_DATA-CENTRAL-DATA.
    MOVE-CORRESPONDING IS_MAIN_UPD TO LS_CUSTOMER-CENTRAL_DATA-CENTRAL-DATAX.
    MOVE-CORRESPONDING IS_MAIN TO LS_CUSTOMER-CENTRAL_DATA-ADDRESS-POSTAL-DATA.
    MOVE-CORRESPONDING IS_MAIN_UPD TO LS_CUSTOMER-CENTRAL_DATA-ADDRESS-POSTAL-DATAX.
    "Manage phone number
    IF IS_MAIN_UPD-TEL_NUMBER = ABAP_TRUE OR IS_MAIN_UPD-MOB_NUMBER = ABAP_TRUE.
      APPEND LINES OF LS_CUSTOMER_BEFORE-CENTRAL_DATA-ADDRESS-COMMUNICATION-PHONE-PHONE TO LS_CUSTOMER-CENTRAL_DATA-ADDRESS-COMMUNICATION-PHONE-PHONE.
    ENDIF.
    IF IS_MAIN_UPD-TEL_NUMBER = ABAP_TRUE.
      READ TABLE LS_CUSTOMER-CENTRAL_DATA-ADDRESS-COMMUNICATION-PHONE-PHONE ASSIGNING <LS_PHONE> WITH KEY CONTACT-DATA-R_3_USER = '1'.
      IF SY-SUBRC = 0.
        <LS_PHONE>-CONTACT-TASK = CVI_EI_API_MAP_STRUCTURE=>GC_UPDATE.
        <LS_PHONE>-CONTACT-DATA-TELEPHONE = IS_MAIN-TEL_NUMBER.
      ELSE.
        CLEAR LS_PHONE.
        LS_PHONE-CONTACT-TASK = CVI_EI_API_MAP_STRUCTURE=>GC_UPDATE.
        LS_PHONE-CONTACT-DATA-TELEPHONE = IS_MAIN-TEL_NUMBER.
        LS_PHONE-CONTACT-DATA-STD_NO = 'X'.
        LS_PHONE-CONTACT-DATA-HOME_FLAG = 'X'.
        LS_PHONE-CONTACT-DATA-R_3_USER = '1'.
        APPEND LS_PHONE TO LS_CUSTOMER-CENTRAL_DATA-ADDRESS-COMMUNICATION-PHONE-PHONE.
      ENDIF.
    ENDIF.
    "Mobile phone
    IF IS_MAIN_UPD-MOB_NUMBER = ABAP_TRUE.
      READ TABLE LS_CUSTOMER-CENTRAL_DATA-ADDRESS-COMMUNICATION-PHONE-PHONE ASSIGNING <LS_PHONE> WITH KEY CONTACT-DATA-R_3_USER = '3'.
      IF SY-SUBRC = 0.
        <LS_PHONE>-CONTACT-TASK = CVI_EI_API_MAP_STRUCTURE=>GC_UPDATE.
        <LS_PHONE>-CONTACT-DATA-TELEPHONE = IS_MAIN-MOB_NUMBER.
      ELSE.
        CLEAR LS_PHONE.
        LS_PHONE-CONTACT-TASK = CVI_EI_API_MAP_STRUCTURE=>GC_UPDATE.
        LS_PHONE-CONTACT-DATA-TELEPHONE = IS_MAIN-MOB_NUMBER.
        LS_PHONE-CONTACT-DATA-R_3_USER = '3'.
        APPEND LS_PHONE TO LS_CUSTOMER-CENTRAL_DATA-ADDRESS-COMMUNICATION-PHONE-PHONE.
      ENDIF.
    ENDIF.
    "E-mails
    IF IS_MAIN_UPD-EMAIL1 = ABAP_TRUE OR IS_MAIN_UPD-EMAIL2 = ABAP_TRUE.
      APPEND LINES OF LS_CUSTOMER_BEFORE-CENTRAL_DATA-ADDRESS-COMMUNICATION-SMTP-SMTP TO LS_CUSTOMER-CENTRAL_DATA-ADDRESS-COMMUNICATION-SMTP-SMTP.
    ENDIF.
    IF IS_MAIN_UPD-EMAIL1 = ABAP_TRUE.
      READ TABLE LS_CUSTOMER-CENTRAL_DATA-ADDRESS-COMMUNICATION-SMTP-SMTP ASSIGNING <LS_EMAIL> INDEX 1.
      IF SY-SUBRC = 0.
        <LS_EMAIL>-CONTACT-TASK = CVI_EI_API_MAP_STRUCTURE=>GC_UPDATE.
        <LS_EMAIL>-CONTACT-DATA-E_MAIL = IS_MAIN-EMAIL1.
      ELSE.
        CLEAR LS_EMAIL.
        LS_EMAIL-CONTACT-TASK = CVI_EI_API_MAP_STRUCTURE=>GC_UPDATE.
        LS_EMAIL-CONTACT-DATA-E_MAIL = IS_MAIN-EMAIL1.
        LS_EMAIL-CONTACT-DATA-STD_NO = 'X'.
        LS_EMAIL-CONTACT-DATA-HOME_FLAG = 'X'.
        APPEND LS_EMAIL TO LS_CUSTOMER-CENTRAL_DATA-ADDRESS-COMMUNICATION-SMTP-SMTP.
      ENDIF.
    ENDIF.
    IF IS_MAIN_UPD-EMAIL2 = ABAP_TRUE.
      READ TABLE LS_CUSTOMER-CENTRAL_DATA-ADDRESS-COMMUNICATION-SMTP-SMTP ASSIGNING <LS_EMAIL> INDEX 2.
      IF SY-SUBRC = 0.
        <LS_EMAIL>-CONTACT-TASK = CVI_EI_API_MAP_STRUCTURE=>GC_UPDATE.
        <LS_EMAIL>-CONTACT-DATA-E_MAIL = IS_MAIN-EMAIL2.
      ELSE.
        CLEAR LS_EMAIL.
        LS_EMAIL-CONTACT-TASK = CVI_EI_API_MAP_STRUCTURE=>GC_UPDATE.
        LS_EMAIL-CONTACT-DATA-E_MAIL = IS_MAIN-EMAIL2.
        APPEND LS_EMAIL TO LS_CUSTOMER-CENTRAL_DATA-ADDRESS-COMMUNICATION-SMTP-SMTP.
      ENDIF.
    ENDIF.

    "Set company data
    IF IS_CCODE_UPD IS NOT INITIAL.
      "Check if company code indicated
      IF IS_CCODE-BUKRS IS INITIAL.
        APPEND YCL_CA_UTILITIES=>SET_TO_BAPIRET2( IV_MSGID = 'YFI1'
                                                  IV_MSGNO = '017'
                                                  IV_MSGTY = 'E' ) TO ET_MESSAGE.
        EXIT.
      ENDIF.
      "Check if customer exists in company code
      READ TABLE LS_CUSTOMER_BEFORE-COMPANY_DATA-COMPANY TRANSPORTING NO FIELDS WITH KEY DATA_KEY-BUKRS = IS_CCODE-BUKRS.
      IF SY-SUBRC = 0.
        LS_COMPANY-TASK = CVI_EI_API_MAP_STRUCTURE=>GC_UPDATE.
        LS_COMPANY-DATA_KEY-BUKRS = IS_CCODE-BUKRS.
        MOVE-CORRESPONDING IS_CCODE TO LS_COMPANY-DATA.
        MOVE-CORRESPONDING IS_CCODE_UPD TO LS_COMPANY-DATAX.
        IF IS_CCODE_UPD-MAHNA = ABAP_TRUE.
          LS_DUNNING-TASK = CVI_EI_API_MAP_STRUCTURE=>GC_UPDATE.
          LS_DUNNING-DATA-MAHNA = IS_CCODE-MAHNA.
          LS_DUNNING-DATAX-MAHNA = ABAP_TRUE.
          APPEND LS_DUNNING TO LS_COMPANY-DUNNING-DUNNING.
        ENDIF.
        APPEND LS_COMPANY TO LS_CUSTOMER-COMPANY_DATA-COMPANY.
      ELSE.
        LS_COMPANY-TASK = CVI_EI_API_MAP_STRUCTURE=>GC_INSERT.
        LS_COMPANY-DATA_KEY-BUKRS = IS_CCODE-BUKRS.
        MOVE-CORRESPONDING IS_CCODE TO LS_COMPANY-DATA.
        LS_DUNNING-TASK = CVI_EI_API_MAP_STRUCTURE=>GC_INSERT.
        LS_DUNNING-DATA-MAHNA = IS_CCODE-MAHNA.
        APPEND LS_DUNNING TO LS_COMPANY-DUNNING-DUNNING.
        APPEND LS_COMPANY TO LS_CUSTOMER-COMPANY_DATA-COMPANY.
      ENDIF.
    ENDIF.

    APPEND LS_CUSTOMER TO LS_CUSTOMERS-CUSTOMERS.

    "Create customer
*    cmd_ei_api=>maintain( EXPORTING iv_test_run    = iv_test
*                                    is_master_data = ls_customers
*                          IMPORTING es_error       = ls_messages ).
    CMD_EI_API=>INITIALIZE( ).
    CMD_EI_API=>MAINTAIN_DIRECT_INPUT( EXPORTING IV_TEST_RUN = IV_TEST
                                                 IS_MASTER_DATA = LS_CUSTOMERS
                                       IMPORTING ES_MASTER_DATA_CORRECT = DATA(LS_DATA_CORRECT)
                                                 ES_MESSAGE_CORRECT = DATA(LS_MESSAGE_CORRECT)
                                                 ES_MASTER_DATA_DEFECTIVE = DATA(LS_DATA_DEFECT)
                                                 ES_MESSAGE_DEFECTIVE = DATA(LS_MESSAGE_DEFECT) ).

    IF IV_TEST = ABAP_FALSE AND LS_MESSAGE_DEFECT-IS_ERROR = ABAP_FALSE.
      COMMIT WORK.
    ENDIF.

    APPEND LINES OF LS_MESSAGE_CORRECT-MESSAGES TO ET_MESSAGE.
    APPEND LINES OF LS_MESSAGE_DEFECT-MESSAGES TO ET_MESSAGE.

    IF LS_MESSAGE_DEFECT-IS_ERROR = ABAP_FALSE.
      EV_IS_OK = ABAP_TRUE.
    ELSE.
      EV_IS_OK = ABAP_FALSE.
    ENDIF.

  ENDMETHOD.

* ---- YCL_FI_CUSTOMER_BL============CM008 ----
  METHOD PREPARE_WORDS.

    DATA LV_POS TYPE I.
    DATA LV_C(1) TYPE C.
    DATA LV_NUM(10) TYPE C VALUE '0123456789'.
    DATA LV_CHAR_UP(26) TYPE C.
    DATA LV_CHAR_LO(26) TYPE C.

    LV_CHAR_UP = LV_CHAR_LO = SY-ABCDE.
    TRANSLATE LV_CHAR_UP TO UPPER CASE.
    TRANSLATE LV_CHAR_LO TO LOWER CASE.

    "Replace by space character not alphabetic or numeric
    DO 80 TIMES.
      LV_C = IV_NAME+LV_POS(1).
      IF LV_C <> SPACE.
        IF LV_C NA LV_CHAR_LO AND LV_C NA LV_CHAR_UP AND LV_C NA LV_NUM AND
           LV_C NA YCL_CA_UTILITIES=>C_ACCENT_LOW AND LV_C NA YCL_CA_UTILITIES=>C_ACCENT_UPP.
          "Special character: replace by space
          IV_NAME+LV_POS(1) = SPACE.
        ENDIF.
      ENDIF.
      ADD 1 TO LV_POS.
    ENDDO.

    SPLIT IV_NAME AT SPACE INTO TABLE ET_WORDS.

    "Delete words with only one character
    LOOP AT ET_WORDS INTO DATA(LV_WORD).
      CHECK LV_WORD+1 = SPACE.
      DELETE ET_WORDS.
    ENDLOOP.

  ENDMETHOD.

* ---- YCL_FI_CUSTOMER_BL============CM009 ----
  METHOD SEARCH_IN_KNA1_ADRC.

    DATA LT_KUNNR TYPE TABLE OF KUNNR.

    IF MT_KUNNR IS INITIAL.
      SELECT A~KUNNR
             FROM KNA1 AS A
             INNER JOIN ADRC AS D ON D~ADDRNUMBER = A~ADRNR
             WHERE (IV_WHERE_CLAUSE)
             INTO TABLE @MT_KUNNR.
    ELSE.
      IV_WHERE_CLAUSE = |A~KUNNR = @MT_KUNNR-TABLE_LINE AND { IV_WHERE_CLAUSE }|.
      SELECT A~KUNNR
             FROM KNA1 AS A
             INNER JOIN ADRC AS D ON D~ADDRNUMBER = A~ADRNR
             FOR ALL ENTRIES IN @MT_KUNNR
             WHERE (IV_WHERE_CLAUSE)
             INTO TABLE @LT_KUNNR.
      MT_KUNNR = LT_KUNNR.
    ENDIF.

  ENDMETHOD.

* ---- YCL_FI_CUSTOMER_BL============CO ----
PROTECTED SECTION.

* ---- YCL_FI_CUSTOMER_BL============CU ----
CLASS YCL_FI_CUSTOMER_BL DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

PUBLIC SECTION.

  CLASS-METHODS CREATE_CUSTOMER
    IMPORTING
      !IS_MAIN TYPE YSFI_CUSTOMER_MAIN_1
      !IS_CCODE TYPE YSFI_CUSTOMER_COMP_CODE_1 OPTIONAL
      !IV_TEST TYPE XFELD DEFAULT 'X'
    EXPORTING
      !EV_IS_OK TYPE XFELD
      !ET_MESSAGE TYPE BAPIRET2_T
      !EV_KUNNR TYPE KUNNR .
  CLASS-METHODS READ_CUSTOMER
    IMPORTING
      !IV_KUNNR TYPE KUNNR
    EXPORTING
      !ES_DATA TYPE CMDS_EI_EXTERN
      !EV_IS_OK TYPE XFELD
      !ET_MESSAGE TYPE BAPIRET2_T .
  CLASS-METHODS SEARCH_FOR_CUSTOMER
    IMPORTING
      !IV_NAME TYPE TEXT80 OPTIONAL
      !IV_SORT TYPE AD_SORT1 OPTIONAL
      !IV_KTOKD TYPE KTOKD OPTIONAL
      !IV_LAND1 TYPE LAND1 OPTIONAL
      !IV_MAX_ROW TYPE I DEFAULT 100
    EXPORTING
      !ET_RESULT TYPE YTTFI_CUSTOMER_DATA_1 .
  CLASS-METHODS UPDATE_CUSTOMER
    IMPORTING
      !IS_MAIN TYPE YSFI_CUSTOMER_MAIN_1
      !IS_MAIN_UPD TYPE YSFI_CUSTOMER_MAIN_1_UPD OPTIONAL
      !IS_CCODE TYPE YSFI_CUSTOMER_COMP_CODE_1 OPTIONAL
      !IS_CCODE_UPD TYPE YSFI_CUSTOMER_COMP_CODE_1_UPD OPTIONAL
      !IV_TEST TYPE XFELD DEFAULT 'X'
    EXPORTING
      !EV_IS_OK TYPE XFELD
      !ET_MESSAGE TYPE BAPIRET2_T .
  CLASS-METHODS GET_ID_FROM_SALESFORCE_ID
    IMPORTING
      !IV_BAHNS TYPE BAHNS
    RETURNING
      VALUE(RV_KUNNR) TYPE KUNNR
    RAISING
      YCX_FI_DATA .