* ==== CLASS POOL YCL_FI_ACCOUNT_SUBST_READ ====
CLASS-POOL .
*"* class pool for class YCL_FI_ACCOUNT_SUBST_READ

*"* local type definitions
INCLUDE YCL_FI_ACCOUNT_SUBST_READ=====CCDEF.

*"* class YCL_FI_ACCOUNT_SUBST_READ definition
*"* public declarations
  INCLUDE YCL_FI_ACCOUNT_SUBST_READ=====CU.
*"* protected declarations
  INCLUDE YCL_FI_ACCOUNT_SUBST_READ=====CO.
*"* private declarations
  INCLUDE YCL_FI_ACCOUNT_SUBST_READ=====CI.
ENDCLASS. "YCL_FI_ACCOUNT_SUBST_READ definition

*"* macro definitions
INCLUDE YCL_FI_ACCOUNT_SUBST_READ=====CCMAC.
*"* local class implementation
INCLUDE YCL_FI_ACCOUNT_SUBST_READ=====CCIMP.

CLASS YCL_FI_ACCOUNT_SUBST_READ IMPLEMENTATION.
*"* method's implementations
  INCLUDE METHODS.
ENDCLASS. "YCL_FI_ACCOUNT_SUBST_READ implementation


* ---- YCL_FI_ACCOUNT_SUBST_READ=====CI ----
PRIVATE SECTION.

* ---- YCL_FI_ACCOUNT_SUBST_READ=====CM001 ----
  METHOD READ.

    TYPES: BEGIN OF TY_SUBST,
             BUKRS TYPE BUKRS,
             BLART TYPE BLART,
             GSBER TYPE GSBER,
           END OF TY_SUBST.

    DATA LT_SUBST TYPE TABLE OF TY_SUBST.
    DATA LT_HKONT_RANGE TYPE RANGE OF HKONT.

    CLEAR RV_GSBER.

    SELECT DISTINCT BUKRS, BLART, GSBER
       FROM YTFI_BA_SUBST
       WHERE BUKRS = @IV_BUKRS
       AND   BLART = @IV_BLART
       AND   SIGN <> @SPACE
      INTO TABLE @LT_SUBST.

    LOOP AT LT_SUBST INTO DATA(LS_SUBST).
      SELECT SIGN,
             OPTI AS OPTION,
             LOW,
             HIGH
        FROM YTFI_BA_SUBST
        WHERE BUKRS = @LS_SUBST-BUKRS
        AND   BLART = @LS_SUBST-BLART
        AND   GSBER = @LS_SUBST-GSBER
        AND   SIGN <> @SPACE
        INTO TABLE  @LT_HKONT_RANGE.
      CHECK LT_HKONT_RANGE IS NOT INITIAL.
      IF IV_HKONT IN LT_HKONT_RANGE.
        RV_GSBER = LS_SUBST-GSBER.
        EXIT.
      ENDIF.
    ENDLOOP.

  ENDMETHOD.

* ---- YCL_FI_ACCOUNT_SUBST_READ=====CO ----
PROTECTED SECTION.

* ---- YCL_FI_ACCOUNT_SUBST_READ=====CU ----
CLASS YCL_FI_ACCOUNT_SUBST_READ DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

PUBLIC SECTION.

  CLASS-METHODS READ
    IMPORTING
      !IV_BUKRS TYPE BUKRS
      !IV_BLART TYPE BLART
      !IV_HKONT TYPE HKONT
    RETURNING
      VALUE(RV_GSBER) TYPE GSBER .