* ==== CLASS POOL YCL_IDFI_CGI_DMEE_UTIL ====
CLASS-POOL .
*"* class pool for class YCL_IDFI_CGI_DMEE_UTIL

*"* local type definitions
INCLUDE YCL_IDFI_CGI_DMEE_UTIL========CCDEF.

*"* class YCL_IDFI_CGI_DMEE_UTIL definition
*"* public declarations
  INCLUDE YCL_IDFI_CGI_DMEE_UTIL========CU.
*"* protected declarations
  INCLUDE YCL_IDFI_CGI_DMEE_UTIL========CO.
*"* private declarations
  INCLUDE YCL_IDFI_CGI_DMEE_UTIL========CI.
ENDCLASS. "YCL_IDFI_CGI_DMEE_UTIL definition

*"* macro definitions
INCLUDE YCL_IDFI_CGI_DMEE_UTIL========CCMAC.
*"* local class implementation
INCLUDE YCL_IDFI_CGI_DMEE_UTIL========CCIMP.

CLASS YCL_IDFI_CGI_DMEE_UTIL IMPLEMENTATION.
*"* method's implementations
  INCLUDE METHODS.
ENDCLASS. "YCL_IDFI_CGI_DMEE_UTIL implementation


* ---- YCL_IDFI_CGI_DMEE_UTIL========CI ----
PRIVATE SECTION.

  TYPES:
    BEGIN OF TY_PPC_CUS,
      LAND1     TYPE YTFI_PPC_TAG-LAND1,
      DEB_CRE   TYPE YTFI_PPC_TAG-DEB_CRE,
      PAY_TYPE  TYPE YTFI_PPC_STRUC-PAY_TYPE,
      TAG_FULL  TYPE YTFI_PPC_TAG-TAG_FULL,
      CODE_ORD  TYPE YTFI_PPC_STRUC-CODE_ORD,
      PPC_CODE  TYPE YTFI_PPC_STRUC-PPC_CODE,
      PPC_VALUE TYPE YTFI_PPC_STRUC-PPC_VALUE,
      PAY_STRUC TYPE YTFI_PPC_STRUC-PAY_STRUC,
      PAY_FIELD TYPE YTFI_PPC_STRUC-PAY_FIELD,
    END OF TY_PPC_CUS .

  CLASS-DATA MO_INSTANCE TYPE REF TO YCL_IDFI_CGI_DMEE_UTIL .
  DATA:
    MT_PPC_CUS TYPE SORTED TABLE OF TY_PPC_CUS WITH UNIQUE KEY LAND1 DEB_CRE PAY_TYPE TAG_FULL CODE_ORD .
  DATA:
    MT_T015L TYPE SORTED TABLE OF T015L WITH UNIQUE KEY LZBKZ .

  METHODS BUILD_VALUE
    IMPORTING
      !IV_VALUE_C TYPE ANY
      !IV_VALUE_TO_ADD TYPE ANY
    EXPORTING
      !EV_VALUE_C TYPE ANY .

* ---- YCL_IDFI_CGI_DMEE_UTIL========CM001 ----
  METHOD CONSTRUCTOR.

    "Get PPC customizing
    SELECT A~LAND1,
           A~DEB_CRE,
           B~PAY_TYPE,
           A~TAG_FULL,
           B~CODE_ORD,
           B~PPC_CODE,
           B~PPC_VALUE,
           B~PAY_STRUC,
           B~PAY_FIELD
           FROM YTFI_PPC_TAG AS A INNER JOIN YTFI_PPC_STRUC AS B ON  B~LAND1 = A~LAND1
                                                                 AND B~TAG_ID = A~TAG_ID
           INTO TABLE @MT_PPC_CUS.

    "Get SCB customizing
    SELECT * FROM T015L INTO TABLE @MT_T015L.

  ENDMETHOD.

* ---- YCL_IDFI_CGI_DMEE_UTIL========CM002 ----
  METHOD GET_INSTANCE.

    IF MO_INSTANCE IS INITIAL.
      MO_INSTANCE = NEW YCL_IDFI_CGI_DMEE_UTIL( ).
    ENDIF.

    RO_INSTANCE = MO_INSTANCE.

  ENDMETHOD.

* ---- YCL_IDFI_CGI_DMEE_UTIL========CM003 ----
  METHOD GET_TAG_VALUE_FROM_CUSTO.

    DATA LV_PAY_TYPE TYPE YE_FI_PAY_TYPE.
    DATA LS_T015L TYPE T015L.
    DATA LV_DUMMY TYPE T015L-ZWCK1.
    DATA LV_VALUE TYPE T015L-ZWCK1.
    DATA LV_FIELD TYPE TEXT80.
    DATA LV_FIRST TYPE XFELD VALUE ABAP_TRUE.
    DATA LV_DEB_CRE TYPE FIN_DRCRIND.

    EV_SUBRC = 0.

    "Get pay type
    CASE IS_FPAYH-DORIGIN(2).
      WHEN 'HR'.
        LV_PAY_TYPE = 'P'.
      WHEN 'TR'.
        LV_PAY_TYPE = 'R'.
      WHEN OTHERS.
        LV_PAY_TYPE = 'O'.
    ENDCASE.

    CASE IV_DEB_CRE.
      WHEN 'DEBIT'.
        LV_DEB_CRE = 'D'.
      WHEN 'CREDIT'.
        LV_DEB_CRE = 'C'.
      WHEN OTHERS.
        EV_SUBRC = 8.
        EXIT.
    ENDCASE.

    LOOP AT MT_PPC_CUS INTO DATA(LS_CUS) WHERE LAND1 = IV_LAND1
                                         AND   DEB_CRE = LV_DEB_CRE
                                         AND   ( PAY_TYPE = LV_PAY_TYPE OR PAY_TYPE = SPACE )
                                         AND   TAG_FULL = IV_TAG_FULL.
      IF LV_FIRST = ABAP_TRUE.
        CLEAR CV_VALUE_C.
        LV_FIRST = ABAP_FALSE.
      ENDIF.

      CASE LS_CUS-PPC_CODE.
        WHEN 'SEPARATOR' OR 'FIXED_VAL'.
          ME->BUILD_VALUE( EXPORTING IV_VALUE_C = CV_VALUE_C
                                     IV_VALUE_TO_ADD = LS_CUS-PPC_VALUE
                           IMPORTING EV_VALUE_C = CV_VALUE_C ).
        WHEN 'PPC_VAR'.
          READ TABLE MT_T015L INTO LS_T015L WITH KEY LZBKZ = IS_FPAYP-LZBKZ.
          IF SY-SUBRC = 0.
            SPLIT LS_T015L-ZWCK1 AT SPACE INTO LV_VALUE LV_DUMMY.
            ME->BUILD_VALUE( EXPORTING IV_VALUE_C = CV_VALUE_C
                                       IV_VALUE_TO_ADD = LV_VALUE
                             IMPORTING EV_VALUE_C = CV_VALUE_C ).
          ENDIF.
        WHEN 'PPC_DESCR'.
          READ TABLE MT_T015L INTO LS_T015L WITH KEY LZBKZ = IS_FPAYP-LZBKZ.
          IF SY-SUBRC = 0.
            SPLIT LS_T015L-ZWCK1 AT SPACE INTO LV_DUMMY LV_VALUE.
            ME->BUILD_VALUE( EXPORTING IV_VALUE_C = CV_VALUE_C
                                       IV_VALUE_TO_ADD = LV_VALUE
                             IMPORTING EV_VALUE_C = CV_VALUE_C ).
          ENDIF.
        WHEN 'PAY_FIELD'.
          LV_FIELD = |IS_{ LS_CUS-PAY_STRUC }-{ LS_CUS-PAY_FIELD }|.
          ASSIGN (LV_FIELD) TO FIELD-SYMBOL(<FIELD>).
          IF <FIELD> IS ASSIGNED.
            ME->BUILD_VALUE( EXPORTING IV_VALUE_C = CV_VALUE_C
                                     IV_VALUE_TO_ADD = <FIELD>
                           IMPORTING EV_VALUE_C = CV_VALUE_C ).
          ELSE.
            EV_SUBRC = 8.
          ENDIF.
      ENDCASE.
    ENDLOOP.
    IF SY-SUBRC <> 0.
      EV_SUBRC = 4.
    ENDIF.

  ENDMETHOD.

* ---- YCL_IDFI_CGI_DMEE_UTIL========CM004 ----
  METHOD BUILD_VALUE.

    IF IV_VALUE_C IS INITIAL.
      EV_VALUE_C = IV_VALUE_TO_ADD.
    ELSE.
      EV_VALUE_C = |{ IV_VALUE_C }{ IV_VALUE_TO_ADD }|.
    ENDIF.

  ENDMETHOD.

* ---- YCL_IDFI_CGI_DMEE_UTIL========CO ----
PROTECTED SECTION.

* ---- YCL_IDFI_CGI_DMEE_UTIL========CU ----
CLASS YCL_IDFI_CGI_DMEE_UTIL DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

PUBLIC SECTION.

  CLASS-METHODS GET_INSTANCE
    RETURNING
      VALUE(RO_INSTANCE) TYPE REF TO YCL_IDFI_CGI_DMEE_UTIL .
  METHODS GET_TAG_VALUE_FROM_CUSTO
    IMPORTING
      !IV_LAND1 TYPE LAND1
      !IV_DEB_CRE TYPE ANY
      !IV_TAG_FULL TYPE STRING
      !IS_FPAYH TYPE FPAYH
      !IS_FPAYHX TYPE FPAYHX
      !IS_FPAYP TYPE FPAYP
    EXPORTING
      !EV_SUBRC TYPE SY-SUBRC
    CHANGING
      !CV_VALUE_C TYPE ANY .
  METHODS CONSTRUCTOR .