* ==== CLASS POOL YCL_FI_CLOSING_PERIOD ====
CLASS-POOL .
*"* class pool for class YCL_FI_CLOSING_PERIOD

*"* local type definitions
INCLUDE YCL_FI_CLOSING_PERIOD=========CCDEF.

*"* class YCL_FI_CLOSING_PERIOD definition
*"* public declarations
  INCLUDE YCL_FI_CLOSING_PERIOD=========CU.
*"* protected declarations
  INCLUDE YCL_FI_CLOSING_PERIOD=========CO.
*"* private declarations
  INCLUDE YCL_FI_CLOSING_PERIOD=========CI.
ENDCLASS. "YCL_FI_CLOSING_PERIOD definition

*"* macro definitions
INCLUDE YCL_FI_CLOSING_PERIOD=========CCMAC.
*"* local class implementation
INCLUDE YCL_FI_CLOSING_PERIOD=========CCIMP.

CLASS YCL_FI_CLOSING_PERIOD IMPLEMENTATION.
*"* method's implementations
  INCLUDE METHODS.
ENDCLASS. "YCL_FI_CLOSING_PERIOD implementation


* ---- YCL_FI_CLOSING_PERIOD=========CI ----
PRIVATE SECTION.

  DATA:
    MT_T001B TYPE TABLE OF T001B .
  DATA:
    MT_EVENTS TYPE TABLE OF YTFI_CLOSE_EVT .
  DATA:
    MT_TO_CLOSE TYPE TABLE OF YTFI_CLOSE_EVT .

  METHODS PERIOD_TO_CLOSE
    IMPORTING
      !IV_PERI TYPE POPER
      !IV_YEAR TYPE GJAHR
      !IV_LAST_PERI TYPE POPER
      !IV_LAST_YEAR TYPE GJAHR
    EXPORTING
      VALUE(EV_IS_OK) TYPE XFELD
      VALUE(EV_PERI) TYPE POPER
      VALUE(EV_YEAR) TYPE GJAHR .

* ---- YCL_FI_CLOSING_PERIOD=========CM001 ----
  METHOD CONSTRUCTOR.

    "Get FI closing periods
    SELECT * FROM T001B INTO TABLE MT_T001B WHERE RRCTY = '0'.

    "Get events
    SELECT * FROM YTFI_CLOSE_EVT INTO TABLE MT_EVENTS.

  ENDMETHOD.

* ---- YCL_FI_CLOSING_PERIOD=========CM002 ----
  METHOD GET_CLOSING_DATA.

    DATA LV_IS_OK TYPE XFELD.
    DATA LV_PERI TYPE POPER.
    DATA LV_YEAR TYPE GJAHR.
    DATA LS_TO_CLOSE TYPE YTFI_CLOSE_EVT.

    LOOP AT MT_EVENTS INTO DATA(LS_EVENTS) WHERE BUKRS IN IT_BUKRS.
      CLEAR: LV_IS_OK, LV_PERI, LV_YEAR.
      "Check if closing step
      READ TABLE MT_T001B INTO DATA(LS_T001B) WITH KEY BUKRS = LS_EVENTS-BUKRS
                                                       MKOAR = '+'
                                                       BKONT = SPACE.
      CHECK SY-SUBRC = 0.
      CHECK LS_T001B-FRPE1 IS INITIAL AND LS_T001B-TOPE1 IS INITIAL.
      ME->PERIOD_TO_CLOSE( EXPORTING IV_PERI = LS_T001B-FRPE2
                                     IV_YEAR = LS_T001B-FRYE2
                                     IV_LAST_PERI = LS_EVENTS-LAST_POST_PERI
                                     IV_LAST_YEAR = LS_EVENTS-LAST_POST_YEAR
                           IMPORTING EV_IS_OK = LV_IS_OK
                                     EV_PERI = LV_PERI
                                     EV_YEAR = LV_YEAR ).
      CHECK LV_IS_OK = ABAP_TRUE.
      MOVE-CORRESPONDING LS_EVENTS TO LS_TO_CLOSE.
      LS_TO_CLOSE-LAST_POST_PERI = LV_PERI.
      LS_TO_CLOSE-LAST_POST_YEAR = LV_YEAR.
      APPEND LS_TO_CLOSE TO MT_TO_CLOSE.
    ENDLOOP.

  ENDMETHOD.

* ---- YCL_FI_CLOSING_PERIOD=========CM003 ----
  METHOD PERIOD_TO_CLOSE.

    DATA LV_PERIOD(7) TYPE N.
    DATA LV_LAST_PERIOD(7) TYPE N.

    EV_IS_OK = ABAP_FALSE.
    CHECK IV_PERI IS NOT INITIAL AND IV_YEAR IS NOT INITIAL.

    "Get previous period
    IF IV_PERI = '001'.
      EV_PERI = '012'.
      EV_YEAR = IV_YEAR - 1.
    ELSE.
      EV_PERI = IV_PERI - 1.
      EV_YEAR = IV_YEAR.
    ENDIF.
    LV_PERIOD = |{ EV_YEAR }{ EV_PERI }|.
    LV_LAST_PERIOD = |{ IV_LAST_YEAR }{ IV_LAST_PERI }|.

    IF LV_LAST_PERIOD < LV_PERIOD.
      EV_IS_OK = ABAP_TRUE.
    ENDIF.

  ENDMETHOD.

* ---- YCL_FI_CLOSING_PERIOD=========CM004 ----
  METHOD RAISE_EVENT_AND_CLOSE.

    DATA LS_RETURN TYPE BAPIRETURN1.

    LOOP AT MT_TO_CLOSE INTO DATA(LS_TO_CLOSE).
      "Raise event
      CL_BATCH_EVENT=>RAISE( I_EVENTID = LS_TO_CLOSE-EVENTID
                             I_EVENTPARM = LS_TO_CLOSE-EVENTPARM ).
      IF SY-SUBRC <> 0.
        LS_RETURN-ID = 'YCOMMON'.
        LS_RETURN-NUMBER = '015'.
        LS_RETURN-TYPE = 'E'.
        LS_RETURN-MESSAGE_V1 = 'Closing period'.
        LS_RETURN-MESSAGE_V2 = LS_TO_CLOSE-BUKRS.
        MESSAGE ID LS_RETURN-ID TYPE LS_RETURN-TYPE NUMBER LS_RETURN-NUMBER
              WITH LS_RETURN-MESSAGE_V1 LS_RETURN-MESSAGE_V2 INTO LS_RETURN-MESSAGE.
        APPEND LS_RETURN TO MT_RETURN.
      ELSE.
        UPDATE YTFI_CLOSE_EVT SET LAST_POST_PERI = LS_TO_CLOSE-LAST_POST_PERI
                                  LAST_POST_YEAR = LS_TO_CLOSE-LAST_POST_YEAR
                              WHERE BUKRS = LS_TO_CLOSE-BUKRS.
        LS_RETURN-ID = 'YCOMMON'.
        LS_RETURN-NUMBER = '016'.
        LS_RETURN-TYPE = 'I'.
        LS_RETURN-MESSAGE_V1 = LS_TO_CLOSE-EVENTID.
        LS_RETURN-MESSAGE_V2 = LS_TO_CLOSE-EVENTPARM.
        LS_RETURN-MESSAGE_V3 = 'Closing period'.
        LS_RETURN-MESSAGE_V4 = LS_TO_CLOSE-BUKRS.
        MESSAGE ID LS_RETURN-ID TYPE LS_RETURN-TYPE NUMBER LS_RETURN-NUMBER
              WITH LS_RETURN-MESSAGE_V1 LS_RETURN-MESSAGE_V2 LS_RETURN-MESSAGE_V3 LS_RETURN-MESSAGE_V4
              INTO LS_RETURN-MESSAGE.
        APPEND LS_RETURN TO MT_RETURN.
      ENDIF.
    ENDLOOP.

  ENDMETHOD.

* ---- YCL_FI_CLOSING_PERIOD=========CO ----
PROTECTED SECTION.

* ---- YCL_FI_CLOSING_PERIOD=========CU ----
CLASS YCL_FI_CLOSING_PERIOD DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    DATA MT_RETURN TYPE TABLE OF BAPIRETURN1.

    METHODS GET_CLOSING_DATA
      IMPORTING
        !IT_BUKRS TYPE YTT_BUKRS_RANGE .
    METHODS RAISE_EVENT_AND_CLOSE .
    METHODS CONSTRUCTOR .