* ==== CLASS POOL YCL_FM_BR_PAYROLL_POSTING_BL ====
CLASS-POOL .
*"* class pool for class YCL_FM_BR_PAYROLL_POSTING_BL

*"* local type definitions
INCLUDE YCL_FM_BR_PAYROLL_POSTING_BL==CCDEF.

*"* class YCL_FM_BR_PAYROLL_POSTING_BL definition
*"* public declarations
  INCLUDE YCL_FM_BR_PAYROLL_POSTING_BL==CU.
*"* protected declarations
  INCLUDE YCL_FM_BR_PAYROLL_POSTING_BL==CO.
*"* private declarations
  INCLUDE YCL_FM_BR_PAYROLL_POSTING_BL==CI.
ENDCLASS. "YCL_FM_BR_PAYROLL_POSTING_BL definition

*"* macro definitions
INCLUDE YCL_FM_BR_PAYROLL_POSTING_BL==CCMAC.
*"* local class implementation
INCLUDE YCL_FM_BR_PAYROLL_POSTING_BL==CCIMP.

CLASS YCL_FM_BR_PAYROLL_POSTING_BL IMPLEMENTATION.
*"* method's implementations
  INCLUDE METHODS.
ENDCLASS. "YCL_FM_BR_PAYROLL_POSTING_BL implementation


* ---- YCL_FM_BR_PAYROLL_POSTING_BL==CI ----
PRIVATE SECTION.

  CLASS-DATA MO_INSTANCE TYPE REF TO YCL_FM_BR_PAYROLL_POSTING_BL .
  DATA MT_ACCOUNTAMOUNT TYPE HRPP_T_BAPIACCR04 .
  DATA MT_ACCOUNTGL TYPE HRPP_T_BAPIACGL04 .

* ---- YCL_FM_BR_PAYROLL_POSTING_BL==CM001 ----
  METHOD GET_INSTANCE.

    IF MO_INSTANCE IS INITIAL.
      MO_INSTANCE = NEW YCL_FM_BR_PAYROLL_POSTING_BL( ).
    ENDIF.

    RO_INSTANCE = MO_INSTANCE.

  ENDMETHOD.

* ---- YCL_FM_BR_PAYROLL_POSTING_BL==CM002 ----
  METHOD SET_ACCOUNTGL.

    MT_ACCOUNTGL = IT_ACCOUNTGL.

  ENDMETHOD.

* ---- YCL_FM_BR_PAYROLL_POSTING_BL==CM003 ----
  METHOD GET_ACCOUNTGL_LINE.

    CLEAR RS_ACCOUNTGL.
    READ TABLE MT_ACCOUNTGL INTO RS_ACCOUNTGL WITH KEY ITEMNO_ACC = IV_ITEM.

  ENDMETHOD.

* ---- YCL_FM_BR_PAYROLL_POSTING_BL==CM004 ----
  METHOD GET_ACCOUNT_LINE.

    CLEAR ES_ACCOUNT_GL.
    READ TABLE MT_ACCOUNTGL INTO ES_ACCOUNT_GL WITH KEY ITEMNO_ACC = IV_ITEM.

    CLEAR ES_ACCOUNT_AMOUNT.
    READ TABLE MT_ACCOUNTAMOUNT INTO ES_ACCOUNT_AMOUNT WITH KEY ITEMNO_ACC = IV_ITEM.

  ENDMETHOD.

* ---- YCL_FM_BR_PAYROLL_POSTING_BL==CM005 ----
  METHOD SET_ACCOUNT_DATA.

    MT_ACCOUNTGL = IT_ACCOUNTGL.
    MT_ACCOUNTAMOUNT = IT_ACCOUNTAMOUNT.

  ENDMETHOD.

* ---- YCL_FM_BR_PAYROLL_POSTING_BL==CO ----
PROTECTED SECTION.

* ---- YCL_FM_BR_PAYROLL_POSTING_BL==CU ----
CLASS YCL_FM_BR_PAYROLL_POSTING_BL DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

PUBLIC SECTION.

  METHODS GET_ACCOUNTGL_LINE
    IMPORTING
      !IV_ITEM TYPE ANY
    RETURNING
      VALUE(RS_ACCOUNTGL) TYPE BAPIACGL04 .
  METHODS GET_ACCOUNT_LINE
    IMPORTING
      !IV_ITEM TYPE ANY
    EXPORTING
      VALUE(ES_ACCOUNT_GL) TYPE BAPIACGL04
      VALUE(ES_ACCOUNT_AMOUNT) TYPE BAPIACCR04 .
  CLASS-METHODS GET_INSTANCE
    RETURNING
      VALUE(RO_INSTANCE) TYPE REF TO YCL_FM_BR_PAYROLL_POSTING_BL .
  METHODS SET_ACCOUNTGL
    IMPORTING
      !IT_ACCOUNTGL TYPE HRPP_T_BAPIACGL04 .
  METHODS SET_ACCOUNT_DATA
    IMPORTING
      !IT_ACCOUNTGL TYPE HRPP_T_BAPIACGL04
      !IT_ACCOUNTAMOUNT TYPE HRPP_T_BAPIACCR04 .