* ==== CLASS POOL YCL_FI_JCU_MANAGEMENT_BL ====
CLASS-POOL .
*"* class pool for class YCL_FI_JCU_MANAGEMENT_BL

*"* local type definitions
INCLUDE YCL_FI_JCU_MANAGEMENT_BL======CCDEF.

*"* class YCL_FI_JCU_MANAGEMENT_BL definition
*"* public declarations
  INCLUDE YCL_FI_JCU_MANAGEMENT_BL======CU.
*"* protected declarations
  INCLUDE YCL_FI_JCU_MANAGEMENT_BL======CO.
*"* private declarations
  INCLUDE YCL_FI_JCU_MANAGEMENT_BL======CI.
ENDCLASS. "YCL_FI_JCU_MANAGEMENT_BL definition

*"* macro definitions
INCLUDE YCL_FI_JCU_MANAGEMENT_BL======CCMAC.
*"* local class implementation
INCLUDE YCL_FI_JCU_MANAGEMENT_BL======CCIMP.

CLASS YCL_FI_JCU_MANAGEMENT_BL IMPLEMENTATION.
*"* method's implementations
  INCLUDE METHODS.
ENDCLASS. "YCL_FI_JCU_MANAGEMENT_BL implementation


* ---- YCL_FI_JCU_MANAGEMENT_BL======CI ----
PRIVATE SECTION.

  TYPES:
    TTY_LIST TYPE TABLE OF YSFI_CASH_BALANCE_LIST .
  TYPES:
    TTY_JCU TYPE TABLE OF YTFI_JCU .

  DATA MV_BUKRS TYPE BUKRS .
  DATA MV_GJAHR TYPE GJAHR .
  DATA MT_JCU_BEFORE TYPE TTY_JCU .
  DATA MT_LIST TYPE TTY_LIST .
  DATA MT_EXCLUDE_FCT TYPE UI_FUNCTIONS .
  DATA MT_LIST_SAVED TYPE TTY_LIST .

  METHODS HANDLE_USER_COMMAND
    FOR EVENT USER_COMMAND OF CL_GUI_ALV_GRID
    IMPORTING
      !E_UCOMM .
  METHODS SET_JCU_TO_LIST
    IMPORTING
      !IT_JCU TYPE TTY_JCU
    EXPORTING
      !ET_LIST TYPE TTY_LIST .
  METHODS SET_LIST_TO_JCU
    IMPORTING
      !IT_LIST TYPE TTY_LIST
    EXPORTING
      !ET_JCU TYPE TTY_JCU .
  METHODS HANDLE_DATA_CHANGED
    FOR EVENT DATA_CHANGED OF CL_GUI_ALV_GRID
    IMPORTING
      !ER_DATA_CHANGED .
  METHODS HANDLE_LIST_UPDATED
    FOR EVENT DATA_CHANGED_FINISHED OF CL_GUI_ALV_GRID
    IMPORTING
      !ET_GOOD_CELLS
      !E_MODIFIED .
  METHODS EXCLUDE_ALV_FUNCTIONS
    IMPORTING
      !IV_FUNCTION TYPE UI_FUNC .

* ---- YCL_FI_JCU_MANAGEMENT_BL======CM001 ----
  METHOD GET_DATA.

    MV_BUKRS = IV_BUKRS.
    MV_GJAHR = IV_GJAHR.

    "Get initial data
    SELECT * FROM YTFI_JCU WHERE BUKRS = @IV_BUKRS
                           AND   GJAHR = @IV_GJAHR
             INTO TABLE @MT_JCU_BEFORE.

    "Prepare data for ALV table
    ME->SET_JCU_TO_LIST( EXPORTING IT_JCU = MT_JCU_BEFORE
                         IMPORTING ET_LIST = MT_LIST ).

    "Save initial list
    MT_LIST_SAVED = MT_LIST.

  ENDMETHOD.

* ---- YCL_FI_JCU_MANAGEMENT_BL======CM002 ----
  METHOD SET_JCU_TO_LIST.

    DATA LS_LIST TYPE LINE OF TTY_LIST.
    DATA LV_FIELDNAME TYPE FIELDNAME.

    LOOP AT IT_JCU INTO DATA(LS_JCU).
      AT NEW GSBER.
        CLEAR LS_LIST.
        LS_LIST-GSBER = LS_JCU-GSBER.
      ENDAT.
      LS_LIST-WAERS = LS_JCU-WAERS.
      LV_FIELDNAME = |LS_LIST-AMT{ LS_JCU-PERIO+1(2) }|.
      ASSIGN (LV_FIELDNAME) TO FIELD-SYMBOL(<FIELD>).
      <FIELD> = LS_JCU-AMOUNT.
      AT END OF GSBER.
        APPEND LS_LIST TO ET_LIST.
      ENDAT.
    ENDLOOP.

  ENDMETHOD.

* ---- YCL_FI_JCU_MANAGEMENT_BL======CM003 ----
  METHOD SET_LIST_TO_JCU.

    DATA LS_JCU TYPE LINE OF TTY_JCU.
    DATA LV_FIELDNAME TYPE FIELDNAME.
    DATA LV_PERIO TYPE PERIODE.

    LOOP AT IT_LIST INTO DATA(LS_LIST).
      CLEAR: LS_JCU, LV_PERIO.
      LS_JCU-BUKRS = MV_BUKRS.
      LS_JCU-GJAHR = MV_GJAHR.
      LS_JCU-GSBER = LS_LIST-GSBER.
      LS_JCU-WAERS = LS_LIST-WAERS.
      DO 15 TIMES.
        LV_FIELDNAME = |LS_LIST-AMT{ LV_PERIO+1(2) }|.
        ASSIGN (LV_FIELDNAME) TO FIELD-SYMBOL(<FIELD>).
        IF <FIELD> IS INITIAL.
          ADD 1 TO LV_PERIO.
          CONTINUE.
        ENDIF.
        LS_JCU-PERIO = LV_PERIO.
        LS_JCU-AMOUNT = <FIELD>.
        APPEND LS_JCU TO ET_JCU.
        ADD 1 TO LV_PERIO.
      ENDDO.
    ENDLOOP.

  ENDMETHOD.

* ---- YCL_FI_JCU_MANAGEMENT_BL======CM004 ----
  METHOD DISPLAY_ALV.

    DATA LS_LAYOUT TYPE LVC_S_LAYO.
    DATA LT_FIELDCAT TYPE LVC_T_FCAT.

    CALL FUNCTION 'LVC_FIELDCATALOG_MERGE'
      EXPORTING
*       I_BUFFER_ACTIVE        =
        I_STRUCTURE_NAME       = 'YSFI_CASH_BALANCE_LIST'
*       I_CLIENT_NEVER_DISPLAY = 'X'
        I_BYPASSING_BUFFER     = ABAP_TRUE
*       I_INTERNAL_TABNAME     =
      CHANGING
        CT_FIELDCAT            = LT_FIELDCAT
      EXCEPTIONS
        INCONSISTENT_INTERFACE = 1
        PROGRAM_ERROR          = 2
        OTHERS                 = 3.
    CHECK SY-SUBRC = 0.

    LOOP AT LT_FIELDCAT ASSIGNING FIELD-SYMBOL(<FIELDCAT>).
      IF MV_DISPLAY_ONLY = ABAP_FALSE.
        <FIELDCAT>-EDIT = ABAP_TRUE.
      ENDIF.
      CASE <FIELDCAT>-FIELDNAME.
        WHEN 'GSBER' OR 'WAERS'.
          <FIELDCAT>-F4AVAILABL = ABAP_TRUE.
        WHEN 'AMT00'.
          <FIELDCAT>-SCRTEXT_L = 'Balance carry forward'.
          <FIELDCAT>-SCRTEXT_M = 'Balance CF'.
        WHEN OTHERS.
          IF <FIELDCAT>-FIELDNAME(3) = 'AMT'.
            <FIELDCAT>-SCRTEXT_L = |Amount period { <FIELDCAT>-FIELDNAME+3(2) }|.
            <FIELDCAT>-SCRTEXT_M = |Amount period { <FIELDCAT>-FIELDNAME+3(2) }|.
          ENDIF.
      ENDCASE.
    ENDLOOP.

    "Exclude interactive functions
    ME->EXCLUDE_ALV_FUNCTIONS( CL_GUI_ALV_GRID=>MC_FC_INFO ).
    ME->EXCLUDE_ALV_FUNCTIONS( CL_GUI_ALV_GRID=>MC_FC_VIEWS ).
    ME->EXCLUDE_ALV_FUNCTIONS( CL_GUI_ALV_GRID=>MC_FC_GRAPH ).
    IF MV_DISPLAY_ONLY = ABAP_TRUE.
      ME->EXCLUDE_ALV_FUNCTIONS( CL_GUI_ALV_GRID=>MC_FC_LOC_CUT ).
      ME->EXCLUDE_ALV_FUNCTIONS( CL_GUI_ALV_GRID=>MC_FC_LOC_COPY_ROW ).
      ME->EXCLUDE_ALV_FUNCTIONS( CL_GUI_ALV_GRID=>MC_FC_LOC_PASTE ).
      ME->EXCLUDE_ALV_FUNCTIONS( CL_GUI_ALV_GRID=>MC_FC_LOC_INSERT_ROW ).
      ME->EXCLUDE_ALV_FUNCTIONS( CL_GUI_ALV_GRID=>MC_FC_LOC_DELETE_ROW ).
      ME->EXCLUDE_ALV_FUNCTIONS( CL_GUI_ALV_GRID=>MC_FC_LOC_APPEND_ROW ).
      ME->EXCLUDE_ALV_FUNCTIONS( CL_GUI_ALV_GRID=>MC_FC_LOC_COPY ).
      ME->EXCLUDE_ALV_FUNCTIONS( CL_GUI_ALV_GRID=>MC_FC_LOC_PASTE_NEW_ROW ).
    ENDIF.

    MO_GRID->SET_TABLE_FOR_FIRST_DISPLAY( EXPORTING IT_TOOLBAR_EXCLUDING = MT_EXCLUDE_FCT
                                                    IS_LAYOUT = LS_LAYOUT
                                          CHANGING IT_FIELDCATALOG = LT_FIELDCAT
                                                   IT_OUTTAB = MT_LIST ).

    MO_GRID->SET_READY_FOR_INPUT( EXPORTING I_READY_FOR_INPUT = 1 ).

    "Handle enter event
    MO_GRID->REGISTER_EDIT_EVENT( EXPORTING I_EVENT_ID = CL_GUI_ALV_GRID=>MC_EVT_ENTER ).
    SET HANDLER ME->HANDLE_DATA_CHANGED FOR MO_GRID.
    SET HANDLER ME->HANDLE_LIST_UPDATED FOR MO_GRID.

  ENDMETHOD.

* ---- YCL_FI_JCU_MANAGEMENT_BL======CM005 ----
  METHOD CHECK_DATA_CHANGED.

    DATA LV_ANSWER TYPE CHAR1.
    DATA LV_VALID TYPE BOOLEAN.
    DATA LT_LIST TYPE TTY_LIST.

    RV_CHANGED = ABAP_FALSE.

    "Check if data changed (in case of click on save without enter)
    MO_GRID->CHECK_CHANGED_DATA( IMPORTING E_VALID = LV_VALID ).

    IF LV_VALID = ABAP_FALSE.
      RV_CHANGED = 'I'.
      EXIT.
    ENDIF.

    "Check list changed
    LT_LIST = MT_LIST.
    SORT LT_LIST.
    IF LT_LIST <> MT_LIST_SAVED.
      RV_CHANGED = ABAP_TRUE.
    ENDIF.

    IF RV_CHANGED = ABAP_TRUE AND IV_SET_POPUP = ABAP_TRUE.
      LV_ANSWER = YCL_CA_UTILITIES=>POPUP_TO_CONFIRM( IV_TITLE = 'Data has been modified'
                                                      IV_TEXT = 'Do you want to leave without saving ?' ).
      CASE LV_ANSWER.
        WHEN '1'.  "Yes
          RV_CHANGED = ABAP_FALSE.
          "mv_data_changed = abap_false.
*        WHEN '2'.
*          rv_changed = abap_true.
      ENDCASE.
    ENDIF.

  ENDMETHOD.

* ---- YCL_FI_JCU_MANAGEMENT_BL======CM006 ----
  METHOD EXCLUDE_ALV_FUNCTIONS.

    APPEND IV_FUNCTION TO MT_EXCLUDE_FCT.

  ENDMETHOD.

* ---- YCL_FI_JCU_MANAGEMENT_BL======CM007 ----
  METHOD SAVE_DATA.

    DATA LT_JCU TYPE TTY_JCU.
    DATA LV_DATA_CHANGED TYPE CHAR1.

    LV_DATA_CHANGED =  ME->CHECK_DATA_CHANGED( ).

    IF LV_DATA_CHANGED = ABAP_TRUE.
      "Set to JCU format
      ME->SET_LIST_TO_JCU( EXPORTING IT_LIST = MT_LIST
                           IMPORTING ET_JCU = LT_JCU ).
      "Delete old values
      DELETE FROM YTFI_JCU WHERE BUKRS = MV_BUKRS
                           AND   GJAHR = MV_GJAHR.
      "Insert new valus
      INSERT YTFI_JCU FROM TABLE LT_JCU.
      IF SY-SUBRC = 0.
        COMMIT WORK.
      ELSE.
        ROLLBACK WORK.
      ENDIF.
      MESSAGE TEXT-U01 TYPE 'S'.
      MT_LIST_SAVED = MT_LIST.
      SORT MT_LIST_SAVED.
      "mv_data_changed = abap_false.
    ELSEIF LV_DATA_CHANGED = ABAP_FALSE.
      MESSAGE TEXT-U02 TYPE 'S'.
    ENDIF.

  ENDMETHOD.

* ---- YCL_FI_JCU_MANAGEMENT_BL======CM008 ----
  METHOD HANDLE_DATA_CHANGED.

    TYPES: BEGIN OF LTY_DATA.
             INCLUDE TYPE YSFI_CASH_BALANCE_LIST.
             TYPES:     ROW_ID TYPE INT4,
           END OF LTY_DATA.

    DATA LT_DATA TYPE TABLE OF LTY_DATA.
    DATA LS_DATA TYPE LTY_DATA.
    DATA LS_STABLE TYPE LVC_S_STBL.
    DATA LT_ROW_ID TYPE TABLE OF INT4.
    FIELD-SYMBOLS <LT_LIST_MODIFIED> TYPE TTY_LIST.

    ASSIGN ER_DATA_CHANGED->MP_MOD_ROWS->* TO <LT_LIST_MODIFIED>.

    CHECK <LT_LIST_MODIFIED> IS NOT INITIAL.

*    "Set flag data changed
*    mv_data_changed = abap_true.

    LOOP AT MT_LIST INTO DATA(LS_LIST).
      LS_DATA-ROW_ID = SY-TABIX.
      MOVE-CORRESPONDING LS_LIST TO LS_DATA.
      APPEND LS_DATA TO LT_DATA.
    ENDLOOP.

    LOOP AT ER_DATA_CHANGED->MT_DELETED_ROWS INTO DATA(LS_DELETED_ROW).
      DELETE LT_DATA WHERE ROW_ID = LS_DELETED_ROW-ROW_ID.
    ENDLOOP.

    LOOP AT ER_DATA_CHANGED->MT_GOOD_CELLS INTO DATA(LS_GOOD_CELLS) WHERE FIELDNAME = 'GSBER'.
      "Determine if it's an insertion, a deletion or a modification
      READ TABLE ER_DATA_CHANGED->MT_DELETED_ROWS TRANSPORTING NO FIELDS WITH KEY ROW_ID = LS_GOOD_CELLS-ROW_ID.
      IF SY-SUBRC = 0.
        "Deleted row
        CONTINUE.
      ENDIF.
      READ TABLE ER_DATA_CHANGED->MT_INSERTED_ROWS INTO DATA(LS_INSERTED_ROW) WITH KEY ROW_ID = LS_GOOD_CELLS-ROW_ID.
      IF SY-SUBRC = 0.
        "New row
        LS_DATA-ROW_ID = LS_INSERTED_ROW-ROW_ID.
        LS_DATA-GSBER = LS_GOOD_CELLS-VALUE.
        APPEND LS_DATA TO LT_DATA.
      ELSE.
        "Existing row modified
        READ TABLE LT_DATA ASSIGNING FIELD-SYMBOL(<LS_DATA>) WITH KEY ROW_ID = LS_GOOD_CELLS-ROW_ID.
        IF SY-SUBRC = 0.
          <LS_DATA>-GSBER = LS_GOOD_CELLS-VALUE.
        ENDIF.
      ENDIF.
    ENDLOOP.

    "Check Business area is only once
    SORT LT_DATA BY GSBER.
    LOOP AT LT_DATA INTO LS_DATA.
      AT NEW GSBER.
        CLEAR LT_ROW_ID.
      ENDAT.
      APPEND LS_DATA-ROW_ID TO LT_ROW_ID.
      AT END OF GSBER.
        IF LINES( LT_ROW_ID ) > 1.
          LOOP AT LT_ROW_ID INTO DATA(LV_ROW_ID).
            ER_DATA_CHANGED->ADD_PROTOCOL_ENTRY( I_MSGID = 'YFI1'
                                                 I_MSGTY = 'E'
                                                 I_MSGNO = '011'
                                                 I_MSGV1 = LS_DATA-GSBER
                                                 I_FIELDNAME = 'GSBER'
                                                 I_ROW_ID = LV_ROW_ID ).
          ENDLOOP.
        ENDIF.
      ENDAT.
    ENDLOOP.

    "Refresh table
*    ls_stable-col = abap_true.
*    ls_stable-row = abap_true.
*    mo_grid->refresh_table_display( is_stable = ls_stable ).

  ENDMETHOD.

* ---- YCL_FI_JCU_MANAGEMENT_BL======CM009 ----
  METHOD HANDLE_LIST_UPDATED.



  ENDMETHOD.

* ---- YCL_FI_JCU_MANAGEMENT_BL======CM00A ----
  METHOD HANDLE_USER_COMMAND.
  ENDMETHOD.

* ---- YCL_FI_JCU_MANAGEMENT_BL======CM00B ----
  METHOD LOCK_JCU_TABLE.

    CALL FUNCTION 'ENQUEUE_EYFI_JCU'
      EXPORTING
        MODE_YTFI_JCU  = 'E'
        MANDT          = SY-MANDT
        BUKRS          = IV_BUKRS
        GJAHR          = IV_GJAHR
*       X_BUKRS        = ' '
*       X_GJAHR        = ' '
*       _SCOPE         = '2'
*       _WAIT          = ' '
*       _COLLECT       = ' '
      EXCEPTIONS
        FOREIGN_LOCK   = 1
        SYSTEM_FAILURE = 2
        OTHERS         = 3.

    IF SY-SUBRC <> 0.
      MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
            WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4 INTO EV_MESSAGE.
    ELSE.
      EV_LOCKED = ABAP_TRUE.
    ENDIF.

  ENDMETHOD.

* ---- YCL_FI_JCU_MANAGEMENT_BL======CM00C ----
  METHOD UNLOCK_JCU_TABLE.

    CALL FUNCTION 'DEQUEUE_EYFI_JCU'
      EXPORTING
        MODE_YTFI_JCU = 'E'
        MANDT         = SY-MANDT
        BUKRS         = IV_BUKRS
        GJAHR         = IV_GJAHR.

  ENDMETHOD.

* ---- YCL_FI_JCU_MANAGEMENT_BL======CO ----
PROTECTED SECTION.

* ---- YCL_FI_JCU_MANAGEMENT_BL======CU ----
CLASS YCL_FI_JCU_MANAGEMENT_BL DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

PUBLIC SECTION.

  DATA MV_DISPLAY_ONLY TYPE XFELD .
  DATA MO_GRID TYPE REF TO CL_GUI_ALV_GRID .

  METHODS CHECK_DATA_CHANGED
    IMPORTING
      !IV_SET_POPUP TYPE BOOLEAN DEFAULT ABAP_FALSE
    RETURNING
      VALUE(RV_CHANGED) TYPE CHAR1 .
  METHODS DISPLAY_ALV .
  METHODS GET_DATA
    IMPORTING
      !IV_BUKRS TYPE BUKRS
      !IV_GJAHR TYPE GJAHR .
  METHODS LOCK_JCU_TABLE
    IMPORTING
      !IV_BUKRS TYPE BUKRS
      !IV_GJAHR TYPE GJAHR
    EXPORTING
      !EV_LOCKED TYPE XFELD
      !EV_MESSAGE TYPE TEXT100 .
  METHODS SAVE_DATA .
  METHODS UNLOCK_JCU_TABLE
    IMPORTING
      !IV_BUKRS TYPE BUKRS
      !IV_GJAHR TYPE GJAHR .