* ==== CLASS POOL YCL_CA_CURRENCY_OP ====
CLASS-POOL .
*"* class pool for class YCL_CA_CURRENCY_OP

*"* local type definitions
INCLUDE YCL_CA_CURRENCY_OP============CCDEF.

*"* class YCL_CA_CURRENCY_OP definition
*"* public declarations
  INCLUDE YCL_CA_CURRENCY_OP============CU.
*"* protected declarations
  INCLUDE YCL_CA_CURRENCY_OP============CO.
*"* private declarations
  INCLUDE YCL_CA_CURRENCY_OP============CI.
ENDCLASS. "YCL_CA_CURRENCY_OP definition

*"* macro definitions
INCLUDE YCL_CA_CURRENCY_OP============CCMAC.
*"* local class implementation
INCLUDE YCL_CA_CURRENCY_OP============CCIMP.

CLASS YCL_CA_CURRENCY_OP IMPLEMENTATION.
*"* method's implementations
  INCLUDE METHODS.
ENDCLASS. "YCL_CA_CURRENCY_OP implementation


* ---- YCL_CA_CURRENCY_OP============CI ----
PRIVATE SECTION.

  TYPES:
    BEGIN OF TY_DECIMAL_FACTOR,
      WAERS  TYPE WAERS,
      FACTOR TYPE YE_CA_DECIMAL_FACTOR,
    END OF TY_DECIMAL_FACTOR .
  TYPES:
    BEGIN OF TY_FOREIGN_FACTOR,
      WAERS_S  TYPE WAERS,
      WAERS_T  TYPE WAERS,
      DATE     TYPE DATUM,
      FACTOR TYPE YE_CA_DECIMAL_FACTOR,
    END OF TY_FOREIGN_FACTOR .

  DATA MV_VADR_CORRECTION TYPE DATUM .
  DATA:
    MT_DECIMAL_FACTORS TYPE SORTED TABLE OF TY_DECIMAL_FACTOR WITH UNIQUE KEY WAERS .
  DATA:
    MT_FOREIGN_FACTORS TYPE SORTED TABLE OF TY_FOREIGN_FACTOR WITH UNIQUE KEY WAERS_S WAERS_T DATE .

* ---- YCL_CA_CURRENCY_OP============CM001 ----
  METHOD GET_DECIMAL_FACTOR.

    DATA LS_FACTOR TYPE TY_DECIMAL_FACTOR.
    DATA LV_CURRDEC TYPE CURRDEC.

    READ TABLE MT_DECIMAL_FACTORS INTO LS_FACTOR WITH KEY WAERS = IV_CURRENCY.
    IF SY-SUBRC <> 0.
      LS_FACTOR-WAERS = IV_CURRENCY.
      SELECT SINGLE CURRDEC INTO LV_CURRDEC FROM TCURX WHERE CURRKEY = IV_CURRENCY.
      IF SY-SUBRC <> 0.
        LS_FACTOR-FACTOR = 1.
      ELSE.
        LS_FACTOR-FACTOR = 10 ** ( 2 - LV_CURRDEC ).
      ENDIF.
      INSERT LS_FACTOR INTO TABLE MT_DECIMAL_FACTORS.
    ENDIF.

    RV_FACTOR = LS_FACTOR-FACTOR.

  ENDMETHOD.

* ---- YCL_CA_CURRENCY_OP============CM002 ----
  METHOD CONSTRUCTOR.

    DATA LV_LOW TYPE TVARVC-LOW.

    SELECT SINGLE LOW INTO LV_LOW FROM TVARVC WHERE NAME = 'Y_PE04_VADR_CORRECTION'.
    IF SY-SUBRC = 0.
      MV_VADR_CORRECTION = LV_LOW(8).
    ENDIF.

  ENDMETHOD.

* ---- YCL_CA_CURRENCY_OP============CM003 ----
  METHOD GET_CORRECTION_DATE.

    RV_DATE = MV_VADR_CORRECTION.

  ENDMETHOD.

* ---- YCL_CA_CURRENCY_OP============CM004 ----
  METHOD GET_FOREIGN_FACTOR.

    DATA LS_FACTOR TYPE TY_FOREIGN_FACTOR.
    DATA LV_DATE TYPE DATUM.
    DATA LT_TCURF TYPE TABLE OF TCURF.

    READ TABLE MT_FOREIGN_FACTORS INTO LS_FACTOR WITH KEY WAERS_S = IV_SOURCE_CURRENCY
                                                          WAERS_T = IV_TARGET_CURRENCY
                                                          DATE    = IV_DATE.
    IF SY-SUBRC <> 0.
      LS_FACTOR-WAERS_S = IV_SOURCE_CURRENCY.
      LS_FACTOR-WAERS_T = IV_TARGET_CURRENCY.
      LS_FACTOR-DATE    = IV_DATE.

      "Convert date to 'currency' date format
      LV_DATE = IV_DATE.
      TRANSLATE LV_DATE USING '09182736455463728190'.

      SELECT * FROM TCURF WHERE KURST = 'M'
                          AND   FCURR = @IV_SOURCE_CURRENCY
                          AND   TCURR = @IV_TARGET_CURRENCY
              INTO TABLE @LT_TCURF.

      SORT LT_TCURF.
      LOOP AT LT_TCURF INTO DATA(LS_TCURF).
        IF LS_TCURF-GDATU >= LV_DATE.
          LS_FACTOR-FACTOR = LS_TCURF-TFACT / LS_TCURF-FFACT.
          EXIT.
        ENDIF.
      ENDLOOP.

      IF LS_FACTOR-FACTOR = 0.
        LS_FACTOR-FACTOR = 1.
      ENDIF.

      INSERT LS_FACTOR INTO TABLE MT_FOREIGN_FACTORS.
    ENDIF.

    RV_FACTOR = LS_FACTOR-FACTOR.

  ENDMETHOD.

* ---- YCL_CA_CURRENCY_OP============CO ----
PROTECTED SECTION.

* ---- YCL_CA_CURRENCY_OP============CU ----
CLASS YCL_CA_CURRENCY_OP DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

PUBLIC SECTION.

  METHODS GET_CORRECTION_DATE
    RETURNING
      VALUE(RV_DATE) TYPE DATUM .
  METHODS CONSTRUCTOR .
  METHODS GET_FOREIGN_FACTOR
    IMPORTING
      !IV_SOURCE_CURRENCY TYPE SYCURR
      !IV_TARGET_CURRENCY TYPE SYCURR
      !IV_DATE TYPE SY-DATUM OPTIONAL
    RETURNING
      VALUE(RV_FACTOR) TYPE YE_CA_DECIMAL_FACTOR .
  METHODS GET_DECIMAL_FACTOR
    IMPORTING
      !IV_CURRENCY TYPE SYCURR
    RETURNING
      VALUE(RV_FACTOR) TYPE YE_CA_DECIMAL_FACTOR .