* ==== CLASS POOL YCL_FM_RFFMEPGAX_EXTENSION ====
CLASS-POOL .
*"* class pool for class YCL_FM_RFFMEPGAX_EXTENSION

*"* local type definitions
INCLUDE YCL_FM_RFFMEPGAX_EXTENSION====CCDEF.

*"* class YCL_FM_RFFMEPGAX_EXTENSION definition
*"* public declarations
  INCLUDE YCL_FM_RFFMEPGAX_EXTENSION====CU.
*"* protected declarations
  INCLUDE YCL_FM_RFFMEPGAX_EXTENSION====CO.
*"* private declarations
  INCLUDE YCL_FM_RFFMEPGAX_EXTENSION====CI.
ENDCLASS. "YCL_FM_RFFMEPGAX_EXTENSION definition

*"* macro definitions
INCLUDE YCL_FM_RFFMEPGAX_EXTENSION====CCMAC.
*"* local class implementation
INCLUDE YCL_FM_RFFMEPGAX_EXTENSION====CCIMP.

CLASS YCL_FM_RFFMEPGAX_EXTENSION IMPLEMENTATION.
*"* method's implementations
  INCLUDE METHODS.
ENDCLASS. "YCL_FM_RFFMEPGAX_EXTENSION implementation


* ---- YCL_FM_RFFMEPGAX_EXTENSION====CI ----
PRIVATE SECTION.

  TYPES:
    BEGIN OF TY_FM01,
      FIKRS TYPE FM01-FIKRS,
      WAERS TYPE FM01-WAERS,
    END OF TY_FM01 .

  CLASS-DATA MV_WAERS TYPE WAERS .
  CLASS-DATA MV_FIKRS TYPE FIKRS .
  CLASS-DATA:
    MT_CUSD_FIPEX TYPE RANGE OF FM_FIPEX .
  CLASS-DATA:
    MT_FM01 TYPE TABLE OF TY_FM01 .

  CLASS-METHODS GET_FM_AREA_CURRENCY
    IMPORTING
      !IV_FIKRS TYPE FIKRS
    RETURNING
      VALUE(RV_WAERS) TYPE WAERS .
  CLASS-METHODS READ_PPDIT
    IMPORTING
      !IV_DOCNUM TYPE HRPP_DOCNUM
      !IV_DOCLIN TYPE HRPP_DOCLIN
    RETURNING
      VALUE(LS_PPDIT) TYPE PPDIT .
  CLASS-METHODS READ_PPDIX
    IMPORTING
      !IS_PPDIT_PPDIX TYPE YCL_FI_TO_PAYROLL_POSTING_BL=>TY_PPDIT_PPDIX
    CHANGING
      !CT_PPDIT_PPDIX TYPE YCL_FI_TO_PAYROLL_POSTING_BL=>TTY_PPDIT_PPDIX .

* ---- YCL_FM_RFFMEPGAX_EXTENSION====CM001 ----
  METHOD SET_BR_FOR_PAYROLL_LINES.

    DATA LS_LINE_ITEM TYPE LINE OF FM_T_IFMREPGAX.
    DATA LT_PPDIT_PPDIX TYPE YCL_FI_TO_PAYROLL_POSTING_BL=>TTY_PPDIT_PPDIX.
    DATA LS_PPDIT_PPDIX TYPE YCL_FI_TO_PAYROLL_POSTING_BL=>TY_PPDIT_PPDIX.
    DATA LT_DOC_LINES TYPE YCL_FI_TO_PAYROLL_POSTING_BL=>TTY_DOC_LINES.
    DATA LV_AMOUNT TYPE MAXBT.

    "Get lines type CDSE / CDSP
    LOOP AT CT_LINE_ITEM INTO LS_LINE_ITEM WHERE FIPEX IN MT_CUSD_FIPEX
                                           AND   AWTYP = 'HRPAY'.
      CLEAR LS_PPDIT_PPDIX.
      LS_PPDIT_PPDIX-CT_INDEX = SY-TABIX.
      LS_PPDIT_PPDIX-DOCNUM = LS_LINE_ITEM-AWREF.
      LS_PPDIT_PPDIX-DOCLIN = LS_LINE_ITEM-RFPOS.
      DATA(LS_PPDIT) = READ_PPDIT( IV_DOCNUM = LS_PPDIT_PPDIX-DOCNUM
                                   IV_DOCLIN = LS_PPDIT_PPDIX-DOCLIN ).
      LS_PPDIT_PPDIX-PERNR = LS_PPDIT-PERNR.
      READ_PPDIX( EXPORTING IS_PPDIT_PPDIX = LS_PPDIT_PPDIX
                  CHANGING CT_PPDIT_PPDIX = LT_PPDIT_PPDIX ).
    ENDLOOP.

    CHECK LT_PPDIT_PPDIX IS NOT INITIAL.

    "build ditribution of fixed rate impact
    YCL_FI_TO_PAYROLL_POSTING_BL=>BUILD_FX_DISTRIBUTION( EXPORTING IT_PPDIT_PPDIX = LT_PPDIT_PPDIX
                                                         IMPORTING ET_DOC_LINES = LT_DOC_LINES ).

    "Update input table with BR amounts
    LOOP AT LT_DOC_LINES INTO DATA(LS_DOC_LINES).

      LOOP AT CT_LINE_ITEM ASSIGNING FIELD-SYMBOL(<LS_LINE_ITEM>) WHERE AWTYP = 'HRPAY'
                                                                 AND   AWREF = LS_DOC_LINES-DOCNUM
                                                                 AND   RFPOS = LS_DOC_LINES-DOCLIN.
        <LS_LINE_ITEM>-ZZBRIMPACTED = 'P'.
        IF ( LS_DOC_LINES-BETRG_O < 0 AND <LS_LINE_ITEM>-TRBTRP >= 0 ) OR
           ( LS_DOC_LINES-BETRG_O >= 0 AND <LS_LINE_ITEM>-TRBTRP < 0 ).
          IF LS_DOC_LINES-REDUC = 'R'.
            LV_AMOUNT = LS_DOC_LINES-BETRG_9.
          ELSE.
            LV_AMOUNT = - LS_DOC_LINES-BETRG_9.
          ENDIF.
        ELSE.
          LV_AMOUNT = LS_DOC_LINES-BETRG_9.
        ENDIF.
        "Convert Amount if necessary
        IF LS_DOC_LINES-WAERS_9 <> GET_FM_AREA_CURRENCY( <LS_LINE_ITEM>-FIKRS ).
          IF <LS_LINE_ITEM>-KURSF < 0.
            LV_AMOUNT = LV_AMOUNT / ( - <LS_LINE_ITEM>-KURSF ).
          ELSE.
            LV_AMOUNT = LV_AMOUNT * <LS_LINE_ITEM>-KURSF.
          ENDIF.
        ENDIF.
        ADD LV_AMOUNT TO <LS_LINE_ITEM>-ZZAMOUNTBRDIFF.
        <LS_LINE_ITEM>-ZZAMOUNTBRLC = <LS_LINE_ITEM>-FKBTRP + <LS_LINE_ITEM>-ZZAMOUNTBRDIFF.
      ENDLOOP.

    ENDLOOP.

    "Set amount for CDSE / CDSP
    LOOP AT LT_PPDIT_PPDIX INTO LS_PPDIT_PPDIX.
      READ TABLE CT_LINE_ITEM ASSIGNING <LS_LINE_ITEM> INDEX LS_PPDIT_PPDIX-CT_INDEX.
      CHECK SY-SUBRC = 0.
      <LS_LINE_ITEM>-ZZBRIMPACTED = 'P'.
      <LS_LINE_ITEM>-ZZAMOUNTBRDIFF = <LS_LINE_ITEM>-TRBTRP.
      IF <LS_LINE_ITEM>-TWAER <> GET_FM_AREA_CURRENCY( <LS_LINE_ITEM>-FIKRS ).
        IF <LS_LINE_ITEM>-KURSF < 0.
          <LS_LINE_ITEM>-ZZAMOUNTBRDIFF = <LS_LINE_ITEM>-ZZAMOUNTBRDIFF / ( - <LS_LINE_ITEM>-KURSF ).
        ELSE.
          <LS_LINE_ITEM>-ZZAMOUNTBRDIFF = <LS_LINE_ITEM>-ZZAMOUNTBRDIFF * <LS_LINE_ITEM>-KURSF.
        ENDIF.
      ENDIF.
    ENDLOOP.

  ENDMETHOD.

* ---- YCL_FM_RFFMEPGAX_EXTENSION====CM002 ----
  METHOD CLASS_CONSTRUCTOR.

    MT_CUSD_FIPEX = VALUE #( ( SIGN = 'I' OPTION = 'EQ' LOW = 'CDCE' )
                             ( SIGN = 'I' OPTION = 'EQ' LOW = 'CDSP' ) ).

    SELECT FIKRS, WAERS FROM FM01 INTO TABLE @MT_FM01.

  ENDMETHOD.

* ---- YCL_FM_RFFMEPGAX_EXTENSION====CM003 ----
  METHOD READ_PPDIT.

    CLEAR LS_PPDIT.
    SELECT SINGLE * FROM PPDIT WHERE DOCNUM = @IV_DOCNUM
                               AND   DOCLIN = @IV_DOCLIN
                    INTO @LS_PPDIT.

  ENDMETHOD.

* ---- YCL_FM_RFFMEPGAX_EXTENSION====CM004 ----
  METHOD READ_PPDIX.

    SELECT @IS_PPDIT_PPDIX-CT_INDEX,
           DOCNUM,
           DOCLIN,
           @IS_PPDIT_PPDIX-PERNR,
           RUNID,
           LINUM
           FROM PPDIX WHERE EVTYP = 'PP'
                      AND   DOCNUM = @IS_PPDIT_PPDIX-DOCNUM
                      AND   DOCLIN = @IS_PPDIT_PPDIX-DOCLIN
          APPENDING TABLE @CT_PPDIT_PPDIX.

  ENDMETHOD.

* ---- YCL_FM_RFFMEPGAX_EXTENSION====CM005 ----
  METHOD GET_FM_AREA_CURRENCY.

    IF IV_FIKRS <> MV_FIKRS.
      READ TABLE MT_FM01 INTO DATA(LS_FM01) WITH KEY FIKRS = IV_FIKRS.
      IF SY-SUBRC = 0.
        MV_WAERS = LS_FM01-WAERS.
      ENDIF.
      MV_FIKRS = IV_FIKRS.
    ENDIF.

    RV_WAERS = MV_WAERS.

  ENDMETHOD.

* ---- YCL_FM_RFFMEPGAX_EXTENSION====CM006 ----
  METHOD SET_BR_FOR_PAYROLL_LINES_V2.

    "Get lines type CDSE / CDSP
    LOOP AT CT_LINE_ITEM ASSIGNING FIELD-SYMBOL(<LS_LINE_ITEM>) WHERE FIPEX IN MT_CUSD_FIPEX
                                                                AND   AWTYP = 'HRPAY'.
      "Put flag 'P'
      <LS_LINE_ITEM>-ZZBRIMPACTED = 'P'.
      "Set payment budget amount into BR finance and BR differ.
      <LS_LINE_ITEM>-ZZAMOUNTBRDIFF = <LS_LINE_ITEM>-ZZAMOUNTBRLC = <LS_LINE_ITEM>-FKBTRP.
    ENDLOOP.

  ENDMETHOD.

* ---- YCL_FM_RFFMEPGAX_EXTENSION====CO ----
PROTECTED SECTION.

* ---- YCL_FM_RFFMEPGAX_EXTENSION====CU ----
CLASS YCL_FM_RFFMEPGAX_EXTENSION DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

PUBLIC SECTION.

  CLASS-METHODS CLASS_CONSTRUCTOR .
  CLASS-METHODS SET_BR_FOR_PAYROLL_LINES
    CHANGING
      !CT_LINE_ITEM TYPE FM_T_IFMREPGAX .
  CLASS-METHODS SET_BR_FOR_PAYROLL_LINES_V2
    CHANGING
      !CT_LINE_ITEM TYPE FM_T_IFMREPGAX .