* ==== CLASS POOL YCX_FI_DATA ====
CLASS-POOL .
*"* class pool for class YCX_FI_DATA

*"* local type definitions
INCLUDE YCX_FI_DATA===================CCDEF.

*"* class YCX_FI_DATA definition
*"* public declarations
  INCLUDE YCX_FI_DATA===================CU.
*"* protected declarations
  INCLUDE YCX_FI_DATA===================CO.
*"* private declarations
  INCLUDE YCX_FI_DATA===================CI.
ENDCLASS. "YCX_FI_DATA definition

*"* macro definitions
INCLUDE YCX_FI_DATA===================CCMAC.
*"* local class implementation
INCLUDE YCX_FI_DATA===================CCIMP.

CLASS YCX_FI_DATA IMPLEMENTATION.
*"* method's implementations
  INCLUDE METHODS.
ENDCLASS. "YCX_FI_DATA implementation


* ---- YCX_FI_DATA===================CI ----
PRIVATE SECTION.

* ---- YCX_FI_DATA===================CM001 ----
  METHOD CONSTRUCTOR.
CALL METHOD SUPER->CONSTRUCTOR
EXPORTING
PREVIOUS = PREVIOUS
.
ME->ID_TYPE = ID_TYPE .
ME->ID_VALUE = ID_VALUE .
CLEAR ME->TEXTID.
IF TEXTID IS INITIAL.
  IF_T100_MESSAGE~T100KEY = IF_T100_MESSAGE=>DEFAULT_TEXTID.
ELSE.
  IF_T100_MESSAGE~T100KEY = TEXTID.
ENDIF.
  ENDMETHOD.

* ---- YCX_FI_DATA===================CO ----
PROTECTED SECTION.

* ---- YCX_FI_DATA===================CU ----
CLASS YCX_FI_DATA DEFINITION
  PUBLIC
  INHERITING FROM CX_STATIC_CHECK
  CREATE PUBLIC .

PUBLIC SECTION.

  INTERFACES IF_T100_MESSAGE .
  INTERFACES IF_T100_DYN_MSG .

  CONSTANTS:
    BEGIN OF NO_CUSTOMER_ID_FOUND,
        MSGID TYPE SYMSGID VALUE 'YFI1',
        MSGNO TYPE SYMSGNO VALUE '008',
        ATTR1 TYPE SCX_ATTRNAME VALUE 'ID_TYPE',
        ATTR2 TYPE SCX_ATTRNAME VALUE 'ID_VALUE',
        ATTR3 TYPE SCX_ATTRNAME VALUE '',
        ATTR4 TYPE SCX_ATTRNAME VALUE '',
      END OF NO_CUSTOMER_ID_FOUND .
    CONSTANTS:
    BEGIN OF MORE_THEN_ONE_ID_FOUND,
        MSGID TYPE SYMSGID VALUE 'YFI1',
        MSGNO TYPE SYMSGNO VALUE '009',
        ATTR1 TYPE SCX_ATTRNAME VALUE 'ID_TYPE',
        ATTR2 TYPE SCX_ATTRNAME VALUE 'ID_VALUE',
        ATTR3 TYPE SCX_ATTRNAME VALUE '',
        ATTR4 TYPE SCX_ATTRNAME VALUE '',
      END OF MORE_THEN_ONE_ID_FOUND .

  DATA ID_TYPE TYPE TEXT30 .
  DATA ID_VALUE TYPE BAHNS .

  METHODS CONSTRUCTOR
    IMPORTING
      !TEXTID LIKE IF_T100_MESSAGE=>T100KEY OPTIONAL
      !PREVIOUS LIKE PREVIOUS OPTIONAL
      !ID_TYPE TYPE TEXT30 OPTIONAL
      !ID_VALUE TYPE BAHNS OPTIONAL .