* ==== CLASS POOL YCX_COMMUNICATION_CHECK ====
CLASS-POOL .
*"* class pool for class YCX_COMMUNICATION_CHECK

*"* local type definitions
INCLUDE YCX_COMMUNICATION_CHECK=======CCDEF.

*"* class YCX_COMMUNICATION_CHECK definition
*"* public declarations
  INCLUDE YCX_COMMUNICATION_CHECK=======CU.
*"* protected declarations
  INCLUDE YCX_COMMUNICATION_CHECK=======CO.
*"* private declarations
  INCLUDE YCX_COMMUNICATION_CHECK=======CI.
ENDCLASS. "YCX_COMMUNICATION_CHECK definition

*"* macro definitions
INCLUDE YCX_COMMUNICATION_CHECK=======CCMAC.
*"* local class implementation
INCLUDE YCX_COMMUNICATION_CHECK=======CCIMP.

CLASS YCX_COMMUNICATION_CHECK IMPLEMENTATION.
*"* method's implementations
  INCLUDE METHODS.
ENDCLASS. "YCX_COMMUNICATION_CHECK implementation


* ---- YCX_COMMUNICATION_CHECK=======CI ----
PRIVATE SECTION.

* ---- YCX_COMMUNICATION_CHECK=======CM001 ----
  METHOD CONSTRUCTOR.
CALL METHOD SUPER->CONSTRUCTOR
EXPORTING
PREVIOUS = PREVIOUS
.
ME->ACTION = ACTION .
ME->ATTR1 = ATTR1 .
ME->ATTR2 = ATTR2 .
ME->ATTR3 = ATTR3 .
ME->URL = URL .
ME->WEB_SERVICE = WEB_SERVICE .
ME->LOGICAL_PORT = LOGICAL_PORT .
ME->SYSTEM_NAME = SYSTEM_NAME .
CLEAR ME->TEXTID.
IF TEXTID IS INITIAL.
  IF_T100_MESSAGE~T100KEY = IF_T100_MESSAGE=>DEFAULT_TEXTID.
ELSE.
  IF_T100_MESSAGE~T100KEY = TEXTID.
ENDIF.
  ENDMETHOD.

* ---- YCX_COMMUNICATION_CHECK=======CO ----
PROTECTED SECTION.

* ---- YCX_COMMUNICATION_CHECK=======CU ----
CLASS YCX_COMMUNICATION_CHECK DEFINITION
  PUBLIC
  INHERITING FROM CX_STATIC_CHECK
  CREATE PUBLIC .

PUBLIC SECTION.

  INTERFACES IF_T100_MESSAGE .
  INTERFACES IF_T100_DYN_MSG .

  CONSTANTS:
    BEGIN OF PROXY_ERROR,
        MSGID TYPE SYMSGID VALUE 'YCOMMON',
        MSGNO TYPE SYMSGNO VALUE '013',
        ATTR1 TYPE SCX_ATTRNAME VALUE 'LOGICAL_PORT',
        ATTR2 TYPE SCX_ATTRNAME VALUE '',
        ATTR3 TYPE SCX_ATTRNAME VALUE '',
        ATTR4 TYPE SCX_ATTRNAME VALUE '',
      END OF PROXY_ERROR .
  CONSTANTS:
    BEGIN OF WEB_SERVICE_ERROR,
        MSGID TYPE SYMSGID VALUE 'YCOMMON',
        MSGNO TYPE SYMSGNO VALUE '014',
        ATTR1 TYPE SCX_ATTRNAME VALUE 'WEB_SERVICE',
        ATTR2 TYPE SCX_ATTRNAME VALUE '',
        ATTR3 TYPE SCX_ATTRNAME VALUE '',
        ATTR4 TYPE SCX_ATTRNAME VALUE '',
      END OF WEB_SERVICE_ERROR .
  CONSTANTS:
    BEGIN OF URL_ERROR,
        MSGID TYPE SYMSGID VALUE 'YCOMMON',
        MSGNO TYPE SYMSGNO VALUE '027',
        ATTR1 TYPE SCX_ATTRNAME VALUE 'URL',
        ATTR2 TYPE SCX_ATTRNAME VALUE '',
        ATTR3 TYPE SCX_ATTRNAME VALUE '',
        ATTR4 TYPE SCX_ATTRNAME VALUE '',
      END OF URL_ERROR .
  CONSTANTS:
    BEGIN OF COMMUNICATION_ERROR,
        MSGID TYPE SYMSGID VALUE 'YCOMMON',
        MSGNO TYPE SYMSGNO VALUE '028',
        ATTR1 TYPE SCX_ATTRNAME VALUE 'ACTION',
        ATTR2 TYPE SCX_ATTRNAME VALUE 'ATTR1',
        ATTR3 TYPE SCX_ATTRNAME VALUE 'ATTR2',
        ATTR4 TYPE SCX_ATTRNAME VALUE 'ATTR3',
      END OF COMMUNICATION_ERROR .
  CONSTANTS:
    BEGIN OF NO_CONNECTION,
        MSGID TYPE SYMSGID VALUE 'YCOMMON',
        MSGNO TYPE SYMSGNO VALUE '042',
        ATTR1 TYPE SCX_ATTRNAME VALUE 'SYSTEM_NAME',
        ATTR2 TYPE SCX_ATTRNAME VALUE 'ATTR1',
        ATTR3 TYPE SCX_ATTRNAME VALUE 'ATTR2',
        ATTR4 TYPE SCX_ATTRNAME VALUE 'ATTR3',
      END OF NO_CONNECTION .
  DATA ACTION TYPE STRING .
  DATA ATTR1 TYPE STRING .
  DATA ATTR2 TYPE STRING .
  DATA ATTR3 TYPE STRING .
  DATA URL TYPE STRING .
  DATA WEB_SERVICE TYPE SEOCPDNAME .
  DATA LOGICAL_PORT TYPE PRX_LOGICAL_PORT_NAME .
  DATA SYSTEM_NAME TYPE STRING .

  METHODS CONSTRUCTOR
    IMPORTING
      !TEXTID LIKE IF_T100_MESSAGE=>T100KEY OPTIONAL
      !PREVIOUS LIKE PREVIOUS OPTIONAL
      !ACTION TYPE STRING OPTIONAL
      !ATTR1 TYPE STRING OPTIONAL
      !ATTR2 TYPE STRING OPTIONAL
      !ATTR3 TYPE STRING OPTIONAL
      !URL TYPE STRING OPTIONAL
      !WEB_SERVICE TYPE SEOCPDNAME OPTIONAL
      !LOGICAL_PORT TYPE PRX_LOGICAL_PORT_NAME OPTIONAL
      !SYSTEM_NAME TYPE STRING OPTIONAL .