*&---------------------------------------------------------------------*
*& Report YFI_CASH_FORECAST
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT YFI_CASH_FORECAST.

INCLUDE YFI_CASH_FORECAST_DATA.
INCLUDE YFI_CASH_FORECAST_SEL.
INCLUDE YFI_CASH_FORECAST_PBO.
INCLUDE YFI_CASH_FORECAST_PAI.

START-OF-SELECTION.

  "Initialize Business logic class
  GO_CASH_FORECAST = NEW YCL_FI_CASH_FORECAST_BL( ).
  "Set selection data to class
  GO_CASH_FORECAST->SET_SELECTION_VALUES( IV_SELNAME = 'P_BUKRS' IV_KIND = 'P' IV_VALUE = P_BUKRS ).
  GO_CASH_FORECAST->SET_SELECTION_VALUES( IV_SELNAME = 'S_FYEAR' IV_KIND = 'S' IT_VALUE = S_FYEAR[] ).
  GO_CASH_FORECAST->SET_SELECTION_VALUES( IV_SELNAME = 'S_GSBER1' IV_KIND = 'S' IT_VALUE = S_GSBER1[] ).
  GO_CASH_FORECAST->SET_SELECTION_VALUES( IV_SELNAME = 'S_SAKNR1' IV_KIND = 'S' IT_VALUE = S_SAKNR1[] ).
  GO_CASH_FORECAST->SET_SELECTION_VALUES( IV_SELNAME = 'S_FUND1' IV_KIND = 'S' IT_VALUE = S_FUND1[] ).
  GO_CASH_FORECAST->SET_SELECTION_VALUES( IV_SELNAME = 'S_TYPE1' IV_KIND = 'S' IT_VALUE = S_TYPE1[] ).
  GO_CASH_FORECAST->SET_SELECTION_VALUES( IV_SELNAME = 'S_FUND2' IV_KIND = 'S' IT_VALUE = S_FUND2[] ).
  GO_CASH_FORECAST->SET_SELECTION_VALUES( IV_SELNAME = 'S_TYPE2' IV_KIND = 'S' IT_VALUE = S_TYPE2[] ).
  GO_CASH_FORECAST->SET_SELECTION_VALUES( IV_SELNAME = 'S_FUND3' IV_KIND = 'S' IT_VALUE = S_FUND3[] ).
  GO_CASH_FORECAST->SET_SELECTION_VALUES( IV_SELNAME = 'S_TYPE3' IV_KIND = 'S' IT_VALUE = S_TYPE3[] ).
  GO_CASH_FORECAST->SET_SELECTION_VALUES( IV_SELNAME = 'S_FUND4' IV_KIND = 'S' IT_VALUE = S_FUND4[] ).
  GO_CASH_FORECAST->SET_SELECTION_VALUES( IV_SELNAME = 'S_TYPE4' IV_KIND = 'S' IT_VALUE = S_TYPE4[] ).
  GO_CASH_FORECAST->SET_SELECTION_VALUES( IV_SELNAME = 'S_FUND5' IV_KIND = 'S' IT_VALUE = S_FUND5[] ).
  GO_CASH_FORECAST->SET_SELECTION_VALUES( IV_SELNAME = 'S_TYPE5' IV_KIND = 'S' IT_VALUE = S_TYPE5[] ).
  GO_CASH_FORECAST->SET_SELECTION_VALUES( IV_SELNAME = 'S_GSBER2' IV_KIND = 'S' IT_VALUE = S_GSBER2[] ).
  GO_CASH_FORECAST->SET_SELECTION_VALUES( IV_SELNAME = 'S_SAKNR2' IV_KIND = 'S' IT_VALUE = S_SAKNR2[] ).
  GO_CASH_FORECAST->SET_SELECTION_VALUES( IV_SELNAME = 'S_BLART2' IV_KIND = 'S' IT_VALUE = S_BLART2[] ).
  GO_CASH_FORECAST->SET_SELECTION_VALUES( IV_SELNAME = 'S_SGTXT2' IV_KIND = 'S' IT_VALUE = S_SGTXT2[] ).
  GO_CASH_FORECAST->SET_SELECTION_VALUES( IV_SELNAME = 'S_GSBER3' IV_KIND = 'S' IT_VALUE = S_GSBER3[] ).
  GO_CASH_FORECAST->SET_SELECTION_VALUES( IV_SELNAME = 'S_SAKNR3' IV_KIND = 'S' IT_VALUE = S_SAKNR3[] ).
  "Extract data
  GO_CASH_FORECAST->GET_DATA( ).
  "Display data
  CALL SCREEN 0100.

  INCLUDE YFI_CASH_FORECAST_FORM.