*&---------------------------------------------------------------------*
*& Report YFI_CUSTOMER_EXTRACT_SF_DATA
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT YFI_CUSTOMER_EXTRACT_SF_DATA.

TYPES: BEGIN OF TY_RESULT,
         KUNNR     TYPE KUNNR,
         MESS_TYPE TYPE SY-MSGTY,
         MESSAGE   TYPE STRING,
       END OF TY_RESULT.

DATA GS_KNA1 TYPE KNA1.
DATA GT_KUNNR TYPE TABLE OF KUNNR.
DATA GT_RESULT TYPE TABLE OF TY_RESULT.
DATA GS_RESULT TYPE TY_RESULT.
DATA GT_FIELDCAT TYPE LVC_T_FCAT.
DATA GO_ALV TYPE REF TO YCL_ALV.
FIELD-SYMBOLS <GT_FILE_DATA> TYPE STANDARD TABLE.
FIELD-SYMBOLS <GS_FILE_DATA> TYPE ANY.


SELECTION-SCREEN BEGIN OF BLOCK B01 WITH FRAME TITLE TEXT-B01.
SELECT-OPTIONS S_KUNNR FOR GS_KNA1-KUNNR.
SELECT-OPTIONS S_KTOKD FOR GS_KNA1-KTOKD NO INTERVALS.
SELECT-OPTIONS S_BAHNS FOR GS_KNA1-BAHNS.
SELECTION-SCREEN END OF BLOCK B01.
SELECTION-SCREEN BEGIN OF BLOCK B02 WITH FRAME TITLE TEXT-B02.
PARAMETERS P_FILE TYPE STRING LOWER CASE.
PARAMETERS P_SEP(1) TYPE C DEFAULT ';' OBLIGATORY.
SELECTION-SCREEN END OF BLOCK B02.


AT SELECTION-SCREEN ON VALUE-REQUEST FOR P_FILE.
  DATA: LT_FILE TYPE FILETABLE, LV_RC TYPE I.
  CL_GUI_FRONTEND_SERVICES=>FILE_OPEN_DIALOG( CHANGING FILE_TABLE =  LT_FILE
                                                       RC = LV_RC
                                              EXCEPTIONS FILE_OPEN_DIALOG_FAILED = 1
                                                         CNTL_ERROR              = 2
                                                         ERROR_NO_GUI            = 3
                                                         NOT_SUPPORTED_BY_GUI    = 4
                                                         OTHERS                  = 5 ).
  IF SY-SUBRC = 0 AND LV_RC = 1.
    READ TABLE LT_FILE INTO P_FILE INDEX 1.
  ENDIF.

START-OF-SELECTION.

  PERFORM F_SELECT_CUSTOMER.

  PERFORM F_PREPARE_TABLE.

  PERFORM F_PREPARE_DATA.

  PERFORM F_DOWNLOAD_FILE.

  "Display messages
  GO_ALV = NEW YCL_ALV( ).
  GO_ALV->YIF_ALV_DISPLAY~INIT_ALV( CHANGING IT_TABLE = GT_RESULT ).
  GO_ALV->YIF_ALV_DISPLAY~SET_MAIN_FUNCTIONS( IV_REPORT = SY-REPID ).
  GO_ALV->YIF_ALV_DISPLAY~SET_COL_TEXT( IV_FIELD = 'KUNNR_C' IV_TEXT = 'Customer id' ).
  GO_ALV->YIF_ALV_DISPLAY~SET_COL_TEXT( IV_FIELD = 'MESSAGE' IV_TEXT = 'Message' ).
  GO_ALV->YIF_ALV_DISPLAY~DISPLAY_ALV( ).


*&---------------------------------------------------------------------*
*&      Form  F_SELECT_CUSTOMER
*&---------------------------------------------------------------------*
FORM F_SELECT_CUSTOMER .

  CLEAR GT_KUNNR.

  "Get customers from selection
  SELECT KUNNR FROM KNA1 WHERE KUNNR IN @S_KUNNR
                         AND   KTOKD IN @S_KTOKD
                         AND   BAHNS IN @S_BAHNS
               INTO TABLE @GT_KUNNR.

ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  F_PREPARE_DATA
*&---------------------------------------------------------------------*
FORM F_PREPARE_DATA .

  DATA LS_CUS_DATA TYPE CMDS_EI_EXTERN.
  DATA LV_IS_OK TYPE XFELD.
  DATA LT_MESSAGE TYPE BAPIRET2_T.
  DATA LS_MAIN_DATA TYPE YSFI_CUSTOMER_MAIN_1.
  DATA LS_COMP_DATA TYPE YSFI_CUSTOMER_COMP_CODE_1.

  LOOP AT GT_KUNNR INTO DATA(LV_KUNNR).
    "Read customer data
    YCL_FI_CUSTOMER_BL=>READ_CUSTOMER( EXPORTING IV_KUNNR = LV_KUNNR
                                       IMPORTING ES_DATA = LS_CUS_DATA
                                                 EV_IS_OK = LV_IS_OK
                                                 ET_MESSAGE = LT_MESSAGE ).
    IF LV_IS_OK = ABAP_FALSE.
      LOOP AT LT_MESSAGE INTO DATA(LS_MESSAGE).
        GS_RESULT-KUNNR = LV_KUNNR.
        GS_RESULT-MESS_TYPE = LS_MESSAGE-TYPE.
        GS_RESULT-MESSAGE = LS_MESSAGE-MESSAGE.
        APPEND GS_RESULT TO GT_RESULT.
      ENDLOOP.
      CONTINUE.
    ENDIF.

    "Prepare data for SalesForce
    CLEAR: LS_MAIN_DATA, LS_COMP_DATA.
    LS_MAIN_DATA-KUNNR = LS_CUS_DATA-HEADER-OBJECT_INSTANCE-KUNNR.
    MOVE-CORRESPONDING LS_CUS_DATA-CENTRAL_DATA-CENTRAL-DATA TO LS_MAIN_DATA.
    MOVE-CORRESPONDING LS_CUS_DATA-CENTRAL_DATA-ADDRESS-POSTAL-DATA TO LS_MAIN_DATA.
    "Remove separator in text
    PERFORM F_REMOVE_SEPARATOR CHANGING LS_MAIN_DATA-NAME.
    PERFORM F_REMOVE_SEPARATOR CHANGING LS_MAIN_DATA-NAME_2.
    PERFORM F_REMOVE_SEPARATOR CHANGING LS_MAIN_DATA-NAME_3.
    PERFORM F_REMOVE_SEPARATOR CHANGING LS_MAIN_DATA-NAME_4.
    PERFORM F_REMOVE_SEPARATOR CHANGING LS_MAIN_DATA-STREET.
    PERFORM F_REMOVE_SEPARATOR CHANGING LS_MAIN_DATA-STR_SUPPL1.
    PERFORM F_REMOVE_SEPARATOR CHANGING LS_MAIN_DATA-STR_SUPPL2.
    PERFORM F_REMOVE_SEPARATOR CHANGING LS_MAIN_DATA-STR_SUPPL3.
    PERFORM F_REMOVE_SEPARATOR CHANGING LS_MAIN_DATA-CITY.

    "Get phone number
    READ TABLE LS_CUS_DATA-CENTRAL_DATA-ADDRESS-COMMUNICATION-PHONE-PHONE INTO DATA(LS_PHONE) WITH KEY CONTACT-DATA-R_3_USER = '1'.
    IF SY-SUBRC = 0.
      LS_MAIN_DATA-TEL_NUMBER = LS_PHONE-CONTACT-DATA-TELEPHONE.
    ENDIF.
    "Get mobile numbers
    READ TABLE LS_CUS_DATA-CENTRAL_DATA-ADDRESS-COMMUNICATION-PHONE-PHONE INTO LS_PHONE WITH KEY CONTACT-DATA-R_3_USER = '3'.
    IF SY-SUBRC = 0.
      LS_MAIN_DATA-MOB_NUMBER = LS_PHONE-CONTACT-DATA-TELEPHONE.
    ENDIF.
    "Get main e-mail
    READ TABLE LS_CUS_DATA-CENTRAL_DATA-ADDRESS-COMMUNICATION-SMTP-SMTP INTO DATA(LS_SMTP) WITH KEY CONTACT-DATA-STD_NO = ABAP_TRUE.
    IF SY-SUBRC = 0.
      LS_MAIN_DATA-EMAIL1 = LS_SMTP-CONTACT-DATA-E_MAIL.
    ENDIF.
    "Get second e-mail
    READ TABLE LS_CUS_DATA-CENTRAL_DATA-ADDRESS-COMMUNICATION-SMTP-SMTP INTO LS_SMTP WITH KEY CONTACT-DATA-STD_NO = ABAP_FALSE.
    IF SY-SUBRC = 0.
      LS_MAIN_DATA-EMAIL2 = LS_SMTP-CONTACT-DATA-E_MAIL.
    ENDIF.

    "Company code data
    LOOP AT LS_CUS_DATA-COMPANY_DATA-COMPANY INTO DATA(LS_COMPANY).
      CLEAR LS_COMP_DATA.
      LS_COMP_DATA-BUKRS = LS_COMPANY-DATA_KEY-BUKRS.
      MOVE-CORRESPONDING LS_COMPANY-DATA TO LS_COMP_DATA.
      READ TABLE LS_COMPANY-DUNNING-DUNNING INTO DATA(LS_DUNNING) INDEX 1.
      IF SY-SUBRC = 0.
        LS_COMP_DATA-MAHNA = LS_DUNNING-DATA-MAHNA.
      ENDIF.
      PERFORM F_INSERT_INTO_FILE_DATA USING LS_MAIN_DATA LS_COMP_DATA.
    ENDLOOP.
    IF SY-SUBRC <> 0.  "No company data
      PERFORM F_INSERT_INTO_FILE_DATA USING LS_MAIN_DATA LS_COMP_DATA.
    ENDIF.

  ENDLOOP.

ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  F_DOWNLOAD_FILE
*&---------------------------------------------------------------------*
FORM F_DOWNLOAD_FILE .

  DATA LT_STRING TYPE TABLE OF STRING.
  DATA LV_STRING TYPE STRING.
  DATA LV_POS TYPE I.
  FIELD-SYMBOLS <LV_FIELD> TYPE ANY.

  "Generate file header
  LOOP AT GT_FIELDCAT INTO DATA(LS_FIELDCAT).
    IF SY-TABIX = 1.
      LV_STRING = LS_FIELDCAT-FIELDNAME.
    ELSE.
      LV_STRING = |{ LV_STRING }{ P_SEP }{ LS_FIELDCAT-FIELDNAME }|.
    ENDIF.
  ENDLOOP.
  APPEND LV_STRING TO LT_STRING.

  "Generate data into file
  LOOP AT <GT_FILE_DATA> ASSIGNING <GS_FILE_DATA>.
    CLEAR: LV_STRING, LV_POS.
    DO.
      ADD 1 TO LV_POS.
      ASSIGN COMPONENT LV_POS OF STRUCTURE <GS_FILE_DATA> TO <LV_FIELD>.
      IF SY-SUBRC <> 0.
        EXIT.
      ENDIF.
      IF LV_POS = 1.
        LV_STRING = <LV_FIELD>.
      ELSE.
        LV_STRING = |{ LV_STRING }{ P_SEP }{ <LV_FIELD> }|.
      ENDIF.
    ENDDO.
    APPEND LV_STRING TO LT_STRING.
  ENDLOOP.

  "download file
  CL_GUI_FRONTEND_SERVICES=>GUI_DOWNLOAD( EXPORTING FILENAME = P_FILE
                                                    FILETYPE = 'ASC'
                                          CHANGING DATA_TAB = LT_STRING
                                          EXCEPTIONS OTHERS = 1 ).
  IF SY-SUBRC = 0.
    MESSAGE 'File downloaded' TYPE 'S'.
  ELSE.
    MESSAGE 'Error download file' TYPE 'I'.
  ENDIF.

ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  F_PREPARE_TABLE
*&---------------------------------------------------------------------*
FORM F_PREPARE_TABLE .

  DATA LR_TABLE TYPE REF TO DATA.
  DATA LR_LINE TYPE REF TO DATA.

  "Build dynamically table to avoid having KUNNR twice

  CALL FUNCTION 'LVC_FIELDCATALOG_MERGE'
    EXPORTING
*     I_BUFFER_ACTIVE        =
      I_STRUCTURE_NAME       = 'YSFI_CUSTOMER_MAIN_1'
*     I_CLIENT_NEVER_DISPLAY = 'X'
*     I_BYPASSING_BUFFER     =
*     I_INTERNAL_TABNAME     =
    CHANGING
      CT_FIELDCAT            = GT_FIELDCAT
    EXCEPTIONS
      INCONSISTENT_INTERFACE = 1
      PROGRAM_ERROR          = 2
      OTHERS                 = 3.

  CALL FUNCTION 'LVC_FIELDCATALOG_MERGE'
    EXPORTING
*     I_BUFFER_ACTIVE        =
      I_STRUCTURE_NAME       = 'YSFI_CUSTOMER_COMP_CODE_1'
*     I_CLIENT_NEVER_DISPLAY = 'X'
*     I_BYPASSING_BUFFER     =
*     I_INTERNAL_TABNAME     =
    CHANGING
      CT_FIELDCAT            = GT_FIELDCAT
    EXCEPTIONS
      INCONSISTENT_INTERFACE = 1
      PROGRAM_ERROR          = 2
      OTHERS                 = 3.

  CL_ALV_TABLE_CREATE=>CREATE_DYNAMIC_TABLE( EXPORTING IT_FIELDCATALOG = GT_FIELDCAT
                                             IMPORTING EP_TABLE        = LR_TABLE ) .
  ASSIGN LR_TABLE->* TO <GT_FILE_DATA>.
  CREATE DATA LR_LINE LIKE LINE OF <GT_FILE_DATA>.
  ASSIGN LR_LINE->* TO <GS_FILE_DATA>.

ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  F_INSERT_INTO_FILE_DATA
*&---------------------------------------------------------------------*
FORM F_INSERT_INTO_FILE_DATA  USING PS_MAIN_DATA TYPE YSFI_CUSTOMER_MAIN_1
                                    PS_COMP_DATA TYPE YSFI_CUSTOMER_COMP_CODE_1.

  DATA LV_POS_SOURCE TYPE I.
  DATA LV_POS_TARGET TYPE I.
  FIELD-SYMBOLS <FIELD_SOURCE> TYPE ANY.
  FIELD-SYMBOLS <FIELD_TARGET> TYPE ANY.

  DO.
    ADD 1 TO LV_POS_SOURCE.
    ASSIGN COMPONENT LV_POS_SOURCE OF STRUCTURE PS_MAIN_DATA TO <FIELD_SOURCE>.
    IF SY-SUBRC <> 0.
      EXIT.
    ENDIF.
    ADD 1 TO LV_POS_TARGET.
    ASSIGN COMPONENT LV_POS_TARGET OF STRUCTURE <GS_FILE_DATA> TO <FIELD_TARGET>.
    IF SY-SUBRC <> 0.
      EXIT.
    ENDIF.
    <FIELD_TARGET> = <FIELD_SOURCE>.
  ENDDO.

  IF PS_COMP_DATA IS NOT INITIAL.
    CLEAR LV_POS_SOURCE.
    ADD 1 TO LV_POS_SOURCE.   "To skip field KUNNR
    DO.
      ADD 1 TO LV_POS_SOURCE.
      ASSIGN COMPONENT LV_POS_SOURCE OF STRUCTURE PS_COMP_DATA TO <FIELD_SOURCE>.
      IF SY-SUBRC <> 0.
        EXIT.
      ENDIF.
      ADD 1 TO LV_POS_TARGET.
      ASSIGN COMPONENT LV_POS_TARGET OF STRUCTURE <GS_FILE_DATA> TO <FIELD_TARGET>.
      IF SY-SUBRC <> 0.
        EXIT.
      ENDIF.
      <FIELD_TARGET> = <FIELD_SOURCE>.
    ENDDO.
  ENDIF.

  APPEND <GS_FILE_DATA> TO <GT_FILE_DATA>.

ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  F_remove_separator
*&---------------------------------------------------------------------*
FORM F_REMOVE_SEPARATOR CHANGING F_TEXT.

  CHECK P_SEP IS NOT INITIAL.

  IF F_TEXT CS P_SEP.
    REPLACE ALL OCCURRENCES OF P_SEP IN F_TEXT WITH ' '.
  ENDIF.

ENDFORM.