*&---------------------------------------------------------------------*
*& Report YFI_VAT_BALANCE
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT YFI_VAT_BALANCE.

DATA GS_BSIS TYPE BSIS.
DATA GO_VAT_BALANCE_BL TYPE REF TO YCL_FI_VAT_BALANCE_BL.

SELECTION-SCREEN BEGIN OF BLOCK B01 WITH FRAME TITLE TEXT-B01.
PARAMETERS P_BUKRS TYPE BUKRS OBLIGATORY.
SELECT-OPTIONS S_HKONT FOR GS_BSIS-HKONT.
SELECTION-SCREEN END OF BLOCK B01.
SELECTION-SCREEN BEGIN OF BLOCK B02 WITH FRAME TITLE TEXT-B02.
PARAMETERS P_BUDAT TYPE BSIS-BUDAT OBLIGATORY DEFAULT SY-DATUM.
SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS P_CLEAR AS CHECKBOX DEFAULT 'X'.
SELECTION-SCREEN COMMENT 2(70) TEXT-C00 FOR FIELD P_CLEAR.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK B02.


INITIALIZATION.
  GET PARAMETER ID 'BUK' FIELD P_BUKRS.

START-OF-SELECTION.

  GO_VAT_BALANCE_BL = NEW YCL_FI_VAT_BALANCE_BL( ).
  "Transfert selection screen
  GO_VAT_BALANCE_BL->SET_SELECTION_VALUES( IV_SELNAME = 'P_BUKRS' IV_KIND = 'P' IV_VALUE = P_BUKRS ).
  GO_VAT_BALANCE_BL->SET_SELECTION_VALUES( IV_SELNAME = 'S_HKONT' IV_KIND = 'S' IT_VALUE = S_HKONT[] ).
  "Get data
  GO_VAT_BALANCE_BL->GET_DATA( IV_OPEN_DATE = P_BUDAT
                               IV_EXCLUDE_CLEAR_ITEMS = P_CLEAR ).
  "Display ALV
  GO_VAT_BALANCE_BL->INIT_ALV( IV_REPID = SY-REPID ).
  GO_VAT_BALANCE_BL->DISPLAY_ALV( ).