*&---------------------------------------------------------------------*
*& Report YFI_UPDATE_T043_FROM_RM
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT YFI_UPDATE_T043_FROM_RM.

DATA MO_POSTING_LIMIT TYPE REF TO YCL_FI_POSTING_LIMIT_BL.
DATA GX_ERROR TYPE REF TO YCX_COMMUNICATION_CHECK.
DATA GV_MESSAGE TYPE STRING.

SELECTION-SCREEN BEGIN OF BLOCK B01 WITH FRAME TITLE TEXT-B01.
PARAMETERS P_USER RADIOBUTTON GROUP R001 DEFAULT 'X'.
PARAMETERS P_AMOUNT RADIOBUTTON GROUP R001.
SELECTION-SCREEN END OF BLOCK B01.
PARAMETERS P_UPDATE AS CHECKBOX.

START-OF-SELECTION.
  MO_POSTING_LIMIT = NEW YCL_FI_POSTING_LIMIT_BL( ).
  IF P_USER = ABAP_TRUE.
    "Check certifying officers
    TRY.
        MO_POSTING_LIMIT->GET_CERTIFYING_OFF_WITH_LIMIT( ).
      CATCH YCX_COMMUNICATION_CHECK INTO GX_ERROR.
        GV_MESSAGE = GX_ERROR->GET_TEXT( ).
        MESSAGE GV_MESSAGE TYPE 'E'.
    ENDTRY.
    MO_POSTING_LIMIT->UPDATE_T043( P_UPDATE ).
    MO_POSTING_LIMIT->DISPLAY_ALV_T043( SY-REPID ).
  ENDIF.

  IF P_AMOUNT = ABAP_TRUE.
    "Check amounts
    MO_POSTING_LIMIT->GET_AMOUNTS_TO_UPDATE( ).
    MO_POSTING_LIMIT->UPDATE_T043T( P_UPDATE ).
    MO_POSTING_LIMIT->DISPLAY_ALV_T043T( SY-REPID ).
  ENDIF.