*&---------------------------------------------------------------------*
*&  Include           YFI_ACCOUNT_SUBSTITUTION_SEL
*&---------------------------------------------------------------------*
PARAMETERS P_BUKRS TYPE YTFI_BA_SUBST-BUKRS OBLIGATORY.
PARAMETERS P_MODE TYPE CHAR1 NO-DISPLAY DEFAULT 'D'.   "D: display, M: Modify

SELECTION-SCREEN BEGIN OF SCREEN 9000 AS WINDOW TITLE TEXT-T90.
SELECT-OPTIONS S_HKONT FOR GS_SKB1-SAKNR MODIF ID MOD.
SELECTION-SCREEN END OF SCREEN 9000.

SELECTION-SCREEN BEGIN OF SCREEN 9001 AS WINDOW TITLE TEXT-T91.
PARAMETERS P_BLART1 TYPE YTFI_BA_SUBST-BLART.
PARAMETERS P_GSBER1 TYPE YTFI_BA_SUBST-GSBER OBLIGATORY.
SELECT-OPTIONS S_HKONT1 FOR GS_SKB1-SAKNR.
SELECTION-SCREEN END OF SCREEN 9001.

SELECTION-SCREEN BEGIN OF SCREEN 9002 AS WINDOW TITLE TEXT-T92.
SELECTION-SCREEN BEGIN OF BLOCK B21 WITH FRAME TITLE TEXT-B21.
PARAMETERS P_BLART2 TYPE YTFI_BA_SUBST-BLART MODIF ID DIS.
PARAMETERS P_GSBER2 TYPE YTFI_BA_SUBST-GSBER MODIF ID DIS.
SELECTION-SCREEN END OF BLOCK B21.
SELECTION-SCREEN BEGIN OF BLOCK B22 WITH FRAME TITLE TEXT-B22.
PARAMETERS P_BLART3 TYPE YTFI_BA_SUBST-BLART.
PARAMETERS P_GSBER3 TYPE YTFI_BA_SUBST-GSBER OBLIGATORY.
SELECT-OPTIONS S_HKONT3 FOR GS_SKB1-SAKNR.
SELECTION-SCREEN END OF BLOCK B22.
SELECTION-SCREEN END OF SCREEN 9002.

INITIALIZATION.
  IF SY-DYNNR(1) <> '9'.
    GET PARAMETER ID 'BUK' FIELD P_BUKRS.
  ENDIF.

AT SELECTION-SCREEN OUTPUT.
  IF SY-DYNNR = '9002'.
    LOOP AT SCREEN.
      IF SCREEN-GROUP1 = 'DIS'.
        SCREEN-INPUT = 0.
        MODIFY SCREEN.
      ENDIF.
    ENDLOOP.
  ENDIF.
  IF P_MODE = 'D'.
    IF SY-DYNNR = '9000'.
      LOOP AT SCREEN.
        IF SCREEN-NAME(7) = 'S_HKONT'.
          SCREEN-INPUT = 0.
          MODIFY SCREEN.
        ENDIF.
      ENDLOOP.
    ENDIF.
  ENDIF.