*&---------------------------------------------------------------------*
*& Report YFI_COUPA_POSTING_FILE
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT YFI_COUPA_POSTING_FILE.

DATA GO_COUPA_ACCOUNTING_LOAD TYPE REF TO YCL_FI_COUPA_ACCOUNTING_LOAD.
DATA GV_FILE_ORDER(1) TYPE C.
DATA GX_ERROR TYPE REF TO YCX_FILE_ACCESS.
DATA GV_MESSAGE TYPE STRING.
DATA GV_EMAIL TYPE YE_EMAIL.
DATA GV_NUMBER TYPE INT2.

SELECTION-SCREEN BEGIN OF BLOCK B01 WITH FRAME TITLE TEXT-B01.
PARAMETERS P_HEADER AS CHECKBOX DEFAULT 'X'.
PARAMETERS P_SEP TYPE CHAR1 DEFAULT ',' OBLIGATORY.
SELECTION-SCREEN END OF BLOCK B01.
SELECTION-SCREEN BEGIN OF BLOCK B02 WITH FRAME TITLE TEXT-B02.
PARAMETERS P_SORTD RADIOBUTTON GROUP R001 DEFAULT 'X'.
PARAMETERS P_SORTN RADIOBUTTON GROUP R001.
SELECTION-SCREEN END OF BLOCK B02.
SELECTION-SCREEN BEGIN OF BLOCK B03 WITH FRAME TITLE TEXT-B03.
PARAMETERS P_TEST AS CHECKBOX DEFAULT 'X'.
SELECTION-SCREEN END OF BLOCK B03.
SELECTION-SCREEN BEGIN OF BLOCK B04 WITH FRAME TITLE TEXT-B04.
SELECT-OPTIONS S_MAIL FOR GV_EMAIL NO INTERVALS.
PARAMETERS P_DELAY TYPE INT1 DEFAULT 60 OBLIGATORY.
SELECTION-SCREEN END OF BLOCK B04.


START-OF-SELECTION.

  IF P_SORTD = ABAP_TRUE.
    GV_FILE_ORDER = 'D'.
  ELSE.
    GV_FILE_ORDER = 'N'.
  ENDIF.

  GO_COUPA_ACCOUNTING_LOAD = NEW YCL_FI_COUPA_ACCOUNTING_LOAD( IV_WITH_HEADER_LINE = P_HEADER
                                                               IV_SEPARATOR = P_SEP
                                                               IV_FILE_ORDER = GV_FILE_ORDER
                                                               IV_TEST = P_TEST ).
  TRY.
      "Check existing entries end move files if necessary
      GO_COUPA_ACCOUNTING_LOAD->REFRESH_STATUS_AND_MOVE_FILE( ).
      "Manage files in data directory
      GO_COUPA_ACCOUNTING_LOAD->LOAD_FILE( IMPORTING EV_NUMBER = GV_NUMBER ).
      IF GV_NUMBER > 0.
        GO_COUPA_ACCOUNTING_LOAD->GENERATE_RFBIBL00_FILE( ).
        IF SY-BATCH = ABAP_TRUE.
          GO_COUPA_ACCOUNTING_LOAD->SEND_PROTOCOL_BY_MAIL( IT_MAIL_ADDRESS = S_MAIL[]
                                                           IV_ONLY_ERROR = ABAP_TRUE
                                                           IV_DELAY = P_DELAY ).
        ENDIF.
        GO_COUPA_ACCOUNTING_LOAD->DISPLAY_PROTOCOL( SY-REPID ).
      ELSE.
        MESSAGE S025(YCOMMON) WITH 'COUPA'.
      ENDIF.
    CATCH YCX_FILE_ACCESS INTO GX_ERROR.
      GV_MESSAGE = GX_ERROR->GET_TEXT( ).
      MESSAGE GV_MESSAGE TYPE 'E'.
  ENDTRY.