*&---------------------------------------------------------------------*
*& Report YFI_CASH_TRANSCATION_1
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT YFI_CASH_TRANSCATION_1.

DATA GS_BSEG TYPE BSEG.
DATA GS_BKPF TYPE BKPF.
DATA GO_BL TYPE REF TO YCL_FI_CASH_TRANSACTION_1.

SELECTION-SCREEN BEGIN OF BLOCK B01 WITH FRAME TITLE TEXT-B01.
PARAMETERS P_BUKRS TYPE BKPF-BUKRS OBLIGATORY.
SELECT-OPTIONS S_HKONT FOR GS_BSEG-HKONT.
SELECT-OPTIONS S_BUDAT FOR GS_BKPF-BUDAT NO-EXTENSION.
SELECT-OPTIONS S_WAERS FOR GS_BKPF-WAERS NO INTERVALS DEFAULT 'EUR'.
SELECTION-SCREEN END OF BLOCK B01.

INITIALIZATION.
  GET PARAMETER ID 'BUK' FIELD P_BUKRS.

START-OF-SELECTION.

  GO_BL = NEW YCL_FI_CASH_TRANSACTION_1( ).
  GO_BL->EXTRACT_DATA( IV_BUKRS = P_BUKRS
                       IT_HKONT_RANGE = S_HKONT[]
                       IT_BUDAT_RANGE = S_BUDAT[]
                       IT_WAERS_RANGE = S_WAERS[] ).
  GO_BL->DISPLAY_ALV( SY-REPID ).