*&---------------------------------------------------------------------*
*&  Include           YFI_CASH_FORECAST_SEL
*&---------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF BLOCK B01 WITH FRAME TITLE TEXT-B01.
PARAMETERS P_BUKRS TYPE GLT0-BUKRS OBLIGATORY MEMORY ID BUK.
SELECTION-SCREEN END OF BLOCK B01.
SELECTION-SCREEN BEGIN OF BLOCK B02 WITH FRAME TITLE TEXT-B02.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN PUSHBUTTON 1(42) PB_SEL USER-COMMAND OSEL VISIBLE LENGTH 20.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK B02.
SELECTION-SCREEN BEGIN OF BLOCK B03 WITH FRAME TITLE TEXT-B03.
SELECT-OPTIONS S_FYEAR FOR GS_GLT0-RYEAR NO-EXTENSION.
SELECTION-SCREEN END OF BLOCK B03.

SELECTION-SCREEN BEGIN OF SCREEN 9000 AS WINDOW TITLE TEXT-BCR.
SELECTION-SCREEN BEGIN OF BLOCK B90 WITH FRAME TITLE TEXT-B90.
SELECT-OPTIONS S_GSBER1 FOR GS_BSEG-GSBER.
SELECT-OPTIONS S_SAKNR1 FOR GS_BSEG-SAKNR.
SELECTION-SCREEN END OF BLOCK B90.
SELECTION-SCREEN BEGIN OF BLOCK B91 WITH FRAME TITLE TEXT-B91.
SELECT-OPTIONS S_FUND1 FOR GS_FMFINCODE-FINCODE.
SELECT-OPTIONS S_TYPE1 FOR GS_FMFINCODE-TYPE.
SELECTION-SCREEN END OF BLOCK B91.
SELECTION-SCREEN BEGIN OF BLOCK B92 WITH FRAME TITLE TEXT-B92.
SELECT-OPTIONS S_FUND2 FOR GS_FMFINCODE-FINCODE.
SELECT-OPTIONS S_TYPE2 FOR GS_FMFINCODE-TYPE.
SELECTION-SCREEN END OF BLOCK B92.
SELECTION-SCREEN BEGIN OF BLOCK B93 WITH FRAME TITLE TEXT-B93.
SELECT-OPTIONS S_FUND3 FOR GS_FMFINCODE-FINCODE.
SELECT-OPTIONS S_TYPE3 FOR GS_FMFINCODE-TYPE.
SELECTION-SCREEN END OF BLOCK B93.
SELECTION-SCREEN BEGIN OF BLOCK B94 WITH FRAME TITLE TEXT-B94.
SELECT-OPTIONS S_FUND4 FOR GS_FMFINCODE-FINCODE.
SELECT-OPTIONS S_TYPE4 FOR GS_FMFINCODE-TYPE.
SELECTION-SCREEN END OF BLOCK B94.
SELECTION-SCREEN BEGIN OF BLOCK B95 WITH FRAME TITLE TEXT-B95.
SELECT-OPTIONS S_FUND5 FOR GS_FMFINCODE-FINCODE.
SELECT-OPTIONS S_TYPE5 FOR GS_FMFINCODE-TYPE.
SELECTION-SCREEN END OF BLOCK B95.
SELECTION-SCREEN BEGIN OF BLOCK B96 WITH FRAME TITLE TEXT-B96.
SELECT-OPTIONS S_GSBER2 FOR GS_BSIS-GSBER.
SELECT-OPTIONS S_SAKNR2 FOR GS_BSIS-HKONT.
SELECT-OPTIONS S_BLART2 FOR GS_BSIS-BLART.
SELECT-OPTIONS S_SGTXT2 FOR GS_BSIS-SGTXT.
SELECTION-SCREEN END OF BLOCK B96.
SELECTION-SCREEN BEGIN OF BLOCK B97 WITH FRAME TITLE TEXT-B97.
SELECT-OPTIONS S_GSBER3 FOR GS_BSEG-GSBER.
SELECT-OPTIONS S_SAKNR3 FOR GS_BSEG-SAKNR.
SELECTION-SCREEN END OF BLOCK B97.
SELECTION-SCREEN END OF SCREEN 9000.

INITIALIZATION.

  CALL FUNCTION 'RS_SUPPORT_SELECTIONS'
    EXPORTING
      REPORT               = SY-REPID
      VARIANT              = 'STD_CRITERIA'
    EXCEPTIONS
      VARIANT_NOT_EXISTENT = 1
      VARIANT_OBSOLETE     = 2
      OTHERS               = 3.

  "set current biennium
  S_FYEAR-SIGN = 'I'.
  S_FYEAR-OPTION = 'BT'.
  IF SY-DATUM+3(1) CA '02468'.
    S_FYEAR-LOW = SY-DATUM(4).
  ELSE.
    S_FYEAR-LOW = SY-DATUM(4) - 1.
  ENDIF.
  S_FYEAR-HIGH = S_FYEAR-LOW + 1.
  APPEND S_FYEAR.




AT SELECTION-SCREEN OUTPUT.
  DATA LV_ICON TYPE STRING.
  DATA LV_EMPTY TYPE BOOLEAN.
  PERFORM F_SEL_9000_EMPTY USING LV_EMPTY.
  IF LV_EMPTY = ABAP_TRUE.
    LV_ICON = 'ICON_ENTER_MORE'.
  ELSE.
    LV_ICON = 'ICON_DISPLAY_MORE'.
  ENDIF.
  CALL FUNCTION 'ICON_CREATE'
    EXPORTING
      NAME                  = LV_ICON
      TEXT                  = 'Criteria'
      INFO                  = 'Criteria'
*     ADD_STDINF            = 'X'
    IMPORTING
      RESULT                = PB_SEL
    EXCEPTIONS
      ICON_NOT_FOUND        = 1
      OUTPUTFIELD_TOO_SHORT = 2
      OTHERS                = 3.

AT SELECTION-SCREEN.
  IF SY-UCOMM = 'OSEL'.
    CALL SELECTION-SCREEN 9000 STARTING AT 10 05.
  ENDIF.