*&---------------------------------------------------------------------*
*& Report YFI_CASH_POOL_BALANCE
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT YFI_CASH_POOL_BALANCE.

DATA GS_GLT0 TYPE GLT0.
DATA GV_PERIO TYPE FM_MONTH_CLOSING.
DATA GO_CASH_POOL_BALANCE_BL TYPE REF TO YCL_FI_CASH_POOL_BALANCE_BL.

INCLUDE YFI_CASH_POOL_BALANCE_SEL.

START-OF-SELECTION.

  GO_CASH_POOL_BALANCE_BL = NEW YCL_FI_CASH_POOL_BALANCE_BL( ).
  "Set selection-screen data to business class
  GO_CASH_POOL_BALANCE_BL->SET_SELECTION_VALUES( IV_SELNAME = 'P_GJAHR' IV_KIND = 'P' IV_VALUE = P_GJAHR ).
  GO_CASH_POOL_BALANCE_BL->SET_SELECTION_VALUES( IV_SELNAME = 'S_PERIO' IV_KIND = 'S' IT_VALUE = S_PERIO[] ).
  "Criteria: cash pool unes
  GO_CASH_POOL_BALANCE_BL->SET_SELECTION_VALUES( IV_SELNAME = 'P_BUKRS1' IV_KIND = 'P' IV_VALUE = P_BUKRS1 ).
  GO_CASH_POOL_BALANCE_BL->SET_SELECTION_VALUES( IV_SELNAME = 'S_RACCT1' IV_KIND = 'S' IT_VALUE = S_RACCT1[] ).
  "Cash pool UBO
  GO_CASH_POOL_BALANCE_BL->SET_SELECTION_VALUES( IV_SELNAME = 'P_BUKRS2' IV_KIND = 'P' IV_VALUE = P_BUKRS2 ).
  GO_CASH_POOL_BALANCE_BL->SET_SELECTION_VALUES( IV_SELNAME = 'S_RACCT2' IV_KIND = 'S' IT_VALUE = S_RACCT2[] ).
  "ASHI fund
  GO_CASH_POOL_BALANCE_BL->SET_SELECTION_VALUES( IV_SELNAME = 'P_BUKRS3' IV_KIND = 'P' IV_VALUE = P_BUKRS3 ).
  GO_CASH_POOL_BALANCE_BL->SET_SELECTION_VALUES( IV_SELNAME = 'S_RACCT3' IV_KIND = 'S' IT_VALUE = S_RACCT3[] ).
  "Nazim Habif
  GO_CASH_POOL_BALANCE_BL->SET_SELECTION_VALUES( IV_SELNAME = 'P_BUKRS4' IV_KIND = 'P' IV_VALUE = P_BUKRS4 ).
  GO_CASH_POOL_BALANCE_BL->SET_SELECTION_VALUES( IV_SELNAME = 'S_RACCT4' IV_KIND = 'S' IT_VALUE = S_RACCT4[] ).
  "Total cash pool balance UNES by MBF
  GO_CASH_POOL_BALANCE_BL->SET_SELECTION_VALUES( IV_SELNAME = 'P_BUKRS5' IV_KIND = 'P' IV_VALUE = P_BUKRS5 ).
  GO_CASH_POOL_BALANCE_BL->SET_SELECTION_VALUES( IV_SELNAME = 'S_RACCT5' IV_KIND = 'S' IT_VALUE = S_RACCT5[] ).
  GO_CASH_POOL_BALANCE_BL->SET_SELECTION_VALUES( IV_SELNAME = 'S_RBUSA5' IV_KIND = 'S' IT_VALUE = S_RBUSA5[] ).
  "Total cash pool balance UNES by OPF
  GO_CASH_POOL_BALANCE_BL->SET_SELECTION_VALUES( IV_SELNAME = 'P_BUKRS6' IV_KIND = 'P' IV_VALUE = P_BUKRS6 ).
  GO_CASH_POOL_BALANCE_BL->SET_SELECTION_VALUES( IV_SELNAME = 'S_RACCT6' IV_KIND = 'S' IT_VALUE = S_RACCT6[] ).
  GO_CASH_POOL_BALANCE_BL->SET_SELECTION_VALUES( IV_SELNAME = 'S_RBUSA6' IV_KIND = 'S' IT_VALUE = S_RBUSA6[] ).
  "Total cash pool balance UNES by PFF
  GO_CASH_POOL_BALANCE_BL->SET_SELECTION_VALUES( IV_SELNAME = 'P_BUKRS7' IV_KIND = 'P' IV_VALUE = P_BUKRS7 ).
  GO_CASH_POOL_BALANCE_BL->SET_SELECTION_VALUES( IV_SELNAME = 'S_RACCT7' IV_KIND = 'S' IT_VALUE = S_RACCT7[] ).
  GO_CASH_POOL_BALANCE_BL->SET_SELECTION_VALUES( IV_SELNAME = 'S_RBUSA7' IV_KIND = 'S' IT_VALUE = S_RBUSA7[] ).
  "Institutes' cash held at UNESCO
  GO_CASH_POOL_BALANCE_BL->SET_SELECTION_VALUES( IV_SELNAME = 'P_BUKRS9' IV_KIND = 'P' IV_VALUE = P_BUKRS9 ).
  GO_CASH_POOL_BALANCE_BL->SET_SELECTION_VALUES( IV_SELNAME = 'S_RACCTA' IV_KIND = 'S' IT_VALUE = S_RACCTA[] ).
  GO_CASH_POOL_BALANCE_BL->SET_SELECTION_VALUES( IV_SELNAME = 'S_RACCTB' IV_KIND = 'S' IT_VALUE = S_RACCTB[] ).
  GO_CASH_POOL_BALANCE_BL->SET_SELECTION_VALUES( IV_SELNAME = 'S_RACCTC' IV_KIND = 'S' IT_VALUE = S_RACCTC[] ).
  GO_CASH_POOL_BALANCE_BL->SET_SELECTION_VALUES( IV_SELNAME = 'S_RACCTD' IV_KIND = 'S' IT_VALUE = S_RACCTD[] ).
  GO_CASH_POOL_BALANCE_BL->SET_SELECTION_VALUES( IV_SELNAME = 'S_RACCTE' IV_KIND = 'S' IT_VALUE = S_RACCTE[] ).
  GO_CASH_POOL_BALANCE_BL->SET_SELECTION_VALUES( IV_SELNAME = 'S_RACCTF' IV_KIND = 'S' IT_VALUE = S_RACCTF[] ).
  GO_CASH_POOL_BALANCE_BL->SET_SELECTION_VALUES( IV_SELNAME = 'S_RACCTG' IV_KIND = 'S' IT_VALUE = S_RACCTG[] ).
  "Institutes' cash
  GO_CASH_POOL_BALANCE_BL->SET_SELECTION_VALUES( IV_SELNAME = 'S_RACCTH' IV_KIND = 'S' IT_VALUE = S_RACCTH[] ).
  GO_CASH_POOL_BALANCE_BL->SET_SELECTION_VALUES( IV_SELNAME = 'S_RACCTI' IV_KIND = 'S' IT_VALUE = S_RACCTI[] ).
  GO_CASH_POOL_BALANCE_BL->SET_SELECTION_VALUES( IV_SELNAME = 'S_RACCTJ' IV_KIND = 'S' IT_VALUE = S_RACCTJ[] ).
  GO_CASH_POOL_BALANCE_BL->SET_SELECTION_VALUES( IV_SELNAME = 'S_RACCTK' IV_KIND = 'S' IT_VALUE = S_RACCTK[] ).
  GO_CASH_POOL_BALANCE_BL->SET_SELECTION_VALUES( IV_SELNAME = 'S_RACCTL' IV_KIND = 'S' IT_VALUE = S_RACCTL[] ).
  GO_CASH_POOL_BALANCE_BL->SET_SELECTION_VALUES( IV_SELNAME = 'S_RACCTM' IV_KIND = 'S' IT_VALUE = S_RACCTM[] ).
  GO_CASH_POOL_BALANCE_BL->SET_SELECTION_VALUES( IV_SELNAME = 'S_RACCTN' IV_KIND = 'S' IT_VALUE = S_RACCTN[] ).

  "Get data for report
  GO_CASH_POOL_BALANCE_BL->GET_DATA( ).

  "Display list
  GO_CASH_POOL_BALANCE_BL->DISPLAY_ALV( SY-REPID ).