*&---------------------------------------------------------------------*
*& Report YFI_RPRAPA00_COMPL
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT YFI_RPRAPA00_COMPL.

TABLES PERNR.

DATA LO_PRAA_BL TYPE REF TO YCL_FI_PRAA_BL.
DATA LT_PERNR TYPE TABLE OF P_PERNR.
DATA LV_TITLE TYPE LVC_TITLE.

PARAMETERS P_BANK RADIOBUTTON GROUP R001 DEFAULT 'X' USER-COMMAND R01.
SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS P_CCODE RADIOBUTTON GROUP R001.
SELECTION-SCREEN COMMENT 3(31) TEXT-C01 FOR FIELD P_CCODE.
PARAMETERS P_BUKRS TYPE BUKRS MODIF ID BUK OBLIGATORY DEFAULT 'UNES'.
SELECTION-SCREEN END OF LINE.
PARAMETERS P_DATE TYPE DATUM OBLIGATORY.
PARAMETERS P_NOMOD AS CHECKBOX.
PARAMETERS P_FILE TYPE RFBIFILE OBLIGATORY.
PARAMETERS P_GROUP TYPE APQ_GRPN DEFAULT 'PRAA_BANK' OBLIGATORY.
PARAMETERS P_UPDATE AS CHECKBOX.

INITIALIZATION.
  PNPTIMED = 'D'.
  P_DATE = SY-DATUM - 1.
  P_FILE = '\\hq-sapitf\itf\<FOLDER>\PRAA\myfile'.
  IF SY-SYSID <> 'P01'.
    REPLACE '<FOLDER>' IN P_FILE WITH '_OTHERS'.
  ELSE.
    REPLACE '<FOLDER>' IN P_FILE WITH '_PROD'.
  ENDIF.

AT SELECTION-SCREEN ON P_DATE.
  IF P_DATE > SY-DATUM.
    MESSAGE TEXT-E01 TYPE 'E'.
  ENDIF.

AT SELECTION-SCREEN OUTPUT.
  LOOP AT SCREEN.
    IF SCREEN-GROUP1 = 'BUK'.
      IF P_CCODE = ABAP_TRUE.
        SCREEN-INPUT = 1.
      ELSE.
        SCREEN-INPUT = 0.
      ENDIF.
      MODIFY SCREEN.
    ENDIF.
  ENDLOOP.

START-OF-SELECTION.

  LO_PRAA_BL = YCL_FI_PRAA_BL=>GET_INSTANCE( ).

GET PERNR.
  IF LO_PRAA_BL->IS_EXCLUDED_PERNR( PERNR-PERNR ) = ABAP_FALSE.
    APPEND PERNR-PERNR TO LT_PERNR.
  ENDIF.

END-OF-SELECTION.

  LO_PRAA_BL->MT_PERNR = LT_PERNR.
  LO_PRAA_BL->MV_NO_MODIF_SCAN = P_NOMOD.
  LO_PRAA_BL->MV_UPDATE = P_UPDATE.

  CASE ABAP_TRUE.
    WHEN P_BANK.
      LO_PRAA_BL->GET_VENDOR_TO_MODIFY_BANK( IT_BUKRS_RANGE = PNPBUKRS[]
                                             IV_DATE_REF = PN-BEGDA
                                             IV_DATE_FROM = P_DATE ).
      LO_PRAA_BL->UPDATE_VENDOR( IV_GROUP = P_GROUP
                                 IV_FILE = P_FILE ).
      LV_TITLE = TEXT-T01.
    WHEN P_CCODE.



      LV_TITLE = TEXT-T02.
  ENDCASE.

  LO_PRAA_BL->DISPLAY_ALV( IV_TABNAME = 'MT_LIFNR_PERNR'
                           IV_TITLE = LV_TITLE
                           IV_LABEL_TEST = TEXT-L01
                           IV_LABEL_UPD = TEXT-L02
                           IV_SORT_FIELD = 'LIFNR' ).