*&---------------------------------------------------------------------*
*&  Include           YFI_OPEN_VENDORS_SEL
*&---------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK B01 WITH FRAME TITLE TEXT-B01.
PARAMETERS P_BUKRS TYPE LFB1-BUKRS OBLIGATORY.
SELECT-OPTIONS S_LIFNR FOR GS_LFA1-LIFNR.
SELECTION-SCREEN END OF BLOCK B01.
SELECTION-SCREEN BEGIN OF BLOCK B02 WITH FRAME TITLE TEXT-B02.
PARAMETERS P_DATE TYPE DATUM OBLIGATORY DEFAULT SY-DATUM.
SELECTION-SCREEN END OF BLOCK B02.
SELECTION-SCREEN BEGIN OF BLOCK B03 WITH FRAME TITLE TEXT-B03.
PARAMETERS P_ALL RADIOBUTTON GROUP R001 DEFAULT 'X'.
PARAMETERS P_ONLY_0 RADIOBUTTON GROUP R001.
PARAMETERS P_NON_0 RADIOBUTTON GROUP R001.
SELECTION-SCREEN END OF BLOCK B03.
SELECTION-SCREEN BEGIN OF BLOCK B04 WITH FRAME TITLE TEXT-B04.
PARAMETERS P_NOTOT RADIOBUTTON GROUP R002 DEFAULT 'X'.
PARAMETERS P_TOTAL RADIOBUTTON GROUP R002.
SELECTION-SCREEN END OF BLOCK B04.

INITIALIZATION.
  GET PARAMETER ID 'BUK' FIELD P_BUKRS.
  "Exclude vendors type personnel numbers
  S_LIFNR-SIGN = 'E'.
  S_LIFNR-OPTION = 'BT'.
  S_LIFNR-LOW = '0010000000'.
  S_LIFNR-HIGH = '0010199999'.
  APPEND S_LIFNR.