*&---------------------------------------------------------------------*
*&  Include           YFI_CASH_POOL_BALANCE_SEL
*&---------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK B01 WITH FRAME TITLE TEXT-B01.
PARAMETERS P_GJAHR TYPE GLT0-RYEAR OBLIGATORY.
SELECT-OPTIONS S_PERIO FOR GV_PERIO NO-EXTENSION.
SELECTION-SCREEN END OF BLOCK B01.
SELECTION-SCREEN BEGIN OF BLOCK B02 WITH FRAME TITLE TEXT-B02.
SELECTION-SCREEN PUSHBUTTON 1(42) PB_SEL USER-COMMAND OSEL VISIBLE LENGTH 20.
SELECTION-SCREEN END OF BLOCK B02.

SELECTION-SCREEN BEGIN OF SCREEN 9000 AS WINDOW TITLE TEXT-BCR.
"Cash pool UNES
SELECTION-SCREEN BEGIN OF BLOCK B91 WITH FRAME TITLE TEXT-B91.
PARAMETERS P_BUKRS1 TYPE GLT0-BUKRS.
SELECT-OPTIONS S_RACCT1 FOR GS_GLT0-RACCT.
SELECTION-SCREEN END OF BLOCK B91.
"Cash pool UBO
SELECTION-SCREEN BEGIN OF BLOCK B92 WITH FRAME TITLE TEXT-B92.
PARAMETERS P_BUKRS2 TYPE GLT0-BUKRS.
SELECT-OPTIONS S_RACCT2 FOR GS_GLT0-RACCT.
SELECTION-SCREEN END OF BLOCK B92.
"ASHI fund
SELECTION-SCREEN BEGIN OF BLOCK B93 WITH FRAME TITLE TEXT-B93.
PARAMETERS P_BUKRS3 TYPE GLT0-BUKRS.
SELECT-OPTIONS S_RACCT3 FOR GS_GLT0-RACCT.
SELECTION-SCREEN END OF BLOCK B93.
"Nasim Habif
SELECTION-SCREEN BEGIN OF BLOCK B94 WITH FRAME TITLE TEXT-B94.
PARAMETERS P_BUKRS4 TYPE GLT0-BUKRS.
SELECT-OPTIONS S_RACCT4 FOR GS_GLT0-RACCT.
SELECTION-SCREEN END OF BLOCK B94.
"Total cash pool balance UNES by MBF
SELECTION-SCREEN BEGIN OF BLOCK B95 WITH FRAME TITLE TEXT-B95.
PARAMETERS P_BUKRS5 TYPE GLT0-BUKRS.
SELECT-OPTIONS S_RACCT5 FOR GS_GLT0-RACCT.
SELECT-OPTIONS S_RBUSA5 FOR GS_GLT0-RBUSA NO INTERVALS.
SELECTION-SCREEN END OF BLOCK B95.
"Total cash pool balance UNES by OPF
SELECTION-SCREEN BEGIN OF BLOCK B96 WITH FRAME TITLE TEXT-B96.
PARAMETERS P_BUKRS6 TYPE GLT0-BUKRS.
SELECT-OPTIONS S_RACCT6 FOR GS_GLT0-RACCT.
SELECT-OPTIONS S_RBUSA6 FOR GS_GLT0-RBUSA NO INTERVALS.
SELECTION-SCREEN END OF BLOCK B96.
"Total cash pool balance UNES by PFF
SELECTION-SCREEN BEGIN OF BLOCK B97 WITH FRAME TITLE TEXT-B97.
PARAMETERS P_BUKRS7 TYPE GLT0-BUKRS.
SELECT-OPTIONS S_RACCT7 FOR GS_GLT0-RACCT.
SELECT-OPTIONS S_RBUSA7 FOR GS_GLT0-RBUSA NO INTERVALS.
SELECTION-SCREEN END OF BLOCK B97.
"Institute's cach held at UNESCO
SELECTION-SCREEN BEGIN OF BLOCK B98 WITH FRAME TITLE TEXT-B98.
PARAMETERS P_BUKRS9 TYPE GLT0-BUKRS.
SELECT-OPTIONS S_RACCTA FOR GS_GLT0-RACCT.  "IBE
SELECT-OPTIONS S_RACCTB FOR GS_GLT0-RACCT.  "ICTP
SELECT-OPTIONS S_RACCTC FOR GS_GLT0-RACCT.  "IICBA
SELECT-OPTIONS S_RACCTD FOR GS_GLT0-RACCT.  "IIEP
SELECT-OPTIONS S_RACCTE FOR GS_GLT0-RACCT.  "MGIEP
SELECT-OPTIONS S_RACCTF FOR GS_GLT0-RACCT.  "UIL
SELECT-OPTIONS S_RACCTG FOR GS_GLT0-RACCT.  "UIS
SELECTION-SCREEN END OF BLOCK B98.
"Institutes' cash
SELECTION-SCREEN BEGIN OF BLOCK B99 WITH FRAME TITLE TEXT-B99.
SELECT-OPTIONS S_RACCTH FOR GS_GLT0-RACCT.  "IBE
SELECT-OPTIONS S_RACCTI FOR GS_GLT0-RACCT.  "ICTP
SELECT-OPTIONS S_RACCTJ FOR GS_GLT0-RACCT.  "IICBA
SELECT-OPTIONS S_RACCTK FOR GS_GLT0-RACCT.  "IIEP
SELECT-OPTIONS S_RACCTL FOR GS_GLT0-RACCT.  "MGIEP
SELECT-OPTIONS S_RACCTM FOR GS_GLT0-RACCT.  "UIL
SELECT-OPTIONS S_RACCTN FOR GS_GLT0-RACCT.  "UIS
SELECTION-SCREEN END OF BLOCK B99.
SELECTION-SCREEN END OF SCREEN 9000.

INITIALIZATION.
  "Set variant for 'Criteria' default value
  CALL FUNCTION 'RS_SUPPORT_SELECTIONS'
    EXPORTING
      REPORT               = SY-REPID
      VARIANT              = 'STD_CRITERIA'
    EXCEPTIONS
      VARIANT_NOT_EXISTENT = 1
      VARIANT_OBSOLETE     = 2
      OTHERS               = 3.

  DATA LV_PERIO TYPE GLT0-RPMAX.
  LV_PERIO = SY-DATUM+4(2).
  IF LV_PERIO = 1.
    P_GJAHR = SY-DATUM(4) - 1.
    S_PERIO[] = VALUE #( ( SIGN = 'I' OPTION = 'BT' LOW = 1 HIGH = 12 ) ).
  ELSE.
    P_GJAHR = SY-DATUM(4).
    LV_PERIO = LV_PERIO - 1.
    S_PERIO[] = VALUE #( ( SIGN = 'I' OPTION = 'BT' LOW = 1 HIGH = LV_PERIO ) ).
  ENDIF.


AT SELECTION-SCREEN OUTPUT.
  CALL FUNCTION 'ICON_CREATE'
    EXPORTING
      NAME                  = 'ICON_DISPLAY_MORE'
      TEXT                  = 'Criteria'
      INFO                  = 'Criteria'
*     ADD_STDINF            = 'X'
    IMPORTING
      RESULT                = PB_SEL
    EXCEPTIONS
      ICON_NOT_FOUND        = 1
      OUTPUTFIELD_TOO_SHORT = 2
      OTHERS                = 3.

AT SELECTION-SCREEN.
  IF SY-UCOMM = 'OSEL'.
    CALL SELECTION-SCREEN 9000 STARTING AT 10 05.
  ENDIF.