*&---------------------------------------------------------------------*
*& Report YFM_FI_COMPARE_FOR_TEST
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT YFM_FI_COMPARE_FOR_TEST.

TYPES:
  BEGIN OF TY_FUND,
    FIKRS   TYPE FMFINCODE-FIKRS,
    FINCODE TYPE FMFINCODE-FINCODE,
  END OF TY_FUND .
TYPES:
  BEGIN OF TY_FMID,
    FMBELNR TYPE FMIFIHD-FMBELNR,
    FIKRS   TYPE FMIFIHD-FIKRS,
    FMBUZEI TYPE FMIFIIT-FMBUZEI,
    BTART   TYPE FMIFIIT-BTART,
    RLDNR   TYPE FMIFIIT-RLDNR,
    GJAHR   TYPE FMIFIIT-GJAHR,
    STUNR   TYPE FMIFIIT-STUNR,
    BUDAT   TYPE FMIFIHD-BUDAT,
    FKBTR   TYPE FMIFIIT-FKBTR,
    WAERS   TYPE FM01-WAERS,
    FONDS   TYPE FMIFIIT-FONDS,
    FISTL   TYPE FMIFIIT-FISTL,
    FIPEX   TYPE FMIFIIT-FIPEX,
    KNGJAHR TYPE FMIFIIT-KNGJAHR,
    KNBELNR TYPE FMIFIIT-KNBELNR,
    KNBUZEI TYPE FMIFIIT-KNBUZEI,
  END OF TY_FMID .
TYPES: BEGIN OF TY_RESULT,
         FMBELNR TYPE FMIFIHD-FMBELNR,
         FIKRS   TYPE FMIFIHD-FIKRS,
         FMBUZEI TYPE FMIFIIT-FMBUZEI,
         BTART   TYPE FMIFIIT-BTART,
         RLDNR   TYPE FMIFIIT-RLDNR,
         STUNR   TYPE FMIFIIT-STUNR,
         FKBTR   TYPE FMIFIIT-FKBTR,
         WAERS   TYPE FM01-WAERS,
         KNGJAHR TYPE FMIFIIT-KNGJAHR,
         KNBELNR TYPE FMIFIIT-KNBELNR,
         KNBUZEI TYPE FMIFIIT-KNBUZEI.
         INCLUDE TYPE BSEG.
       TYPES: END OF TY_RESULT.

DATA GS_BUDT TYPE BUDT.
DATA GS_FMFINCODE TYPE FMFINCODE.
DATA GS_YTFM_OUTPUT TYPE YTFM_OUTPUT.
DATA GS_P0001 TYPE P0001.
DATA GS_RETURN TYPE BAPIRETURN1.
DATA GS_FUND_C5 TYPE YTFM_FUND_C5.

DATA MT_FUND TYPE TABLE OF TY_FUND.
DATA LV_BEGDA TYPE BEGDA.
DATA LV_ENDDA TYPE ENDDA.
DATA MT_FMID TYPE TABLE OF TY_FMID.
DATA MT_BSEG TYPE TABLE OF BSEG.
DATA LV_BUKRS TYPE BUKRS.
DATA LS_RESULT TYPE TY_RESULT.
DATA LT_RESULT TYPE TABLE OF TY_RESULT.
DATA LV_BSEG_AMOUNT TYPE WERTV9.
DATA LV_TABIX TYPE SY-TABIX.
DATA LO_ALV TYPE REF TO YCL_ALV.
DATA LT_C5_SEL TYPE RANGE OF YE_FM_C5_CONTRIBUTION.

INCLUDE YFM_STAFF_COST_DISTRIBUT_SEL.

INITIALIZATION.
  PERFORM F_INITIALIZATION.



START-OF-SELECTION.

  LV_BEGDA = |{ S_GJAHR-LOW }0101|.
  LV_ENDDA = |{ S_GJAHR-HIGH }1231|.
  SELECT SINGLE BUKRS FROM T001 WHERE FIKRS = @P_FIKRS INTO @LV_BUKRS.

  IF P_C5_SEL = ABAP_TRUE.
    APPEND VALUE #( SIGN = 'I' OPTION = 'EQ' LOW = 'X' ) TO LT_C5_SEL.
  ENDIF.

  "Extract funds from selection criteria
  SELECT DISTINCT A~FIKRS AS FIKRS,
                  A~FINCODE AS FINCODE
         FROM FMFINCODE AS A
         LEFT OUTER JOIN YTFM_FUND_C5 AS C ON  C~FIKRS = A~FIKRS
                                           AND C~FINCODE = A~FINCODE
         LEFT OUTER JOIN YTFM_OUTPUT AS O ON O~FM_OUTPUT = C~FM_OUTPUT
         WHERE A~FIKRS = @P_FIKRS
         AND   A~FINCODE IN @S_FUND
         AND   A~DATAB <= @LV_ENDDA
         AND   A~DATBIS >= @LV_BEGDA
         AND   A~TYPE IN @S_TYPE
         AND   O~OTYPE = 'OFFICE4'    "NME 20241218
         AND   O~ZZSECT IN @S_SECTOR
         AND   C~C5_ID IN @S_C5_ID
         AND   C~FM_OUTPUT IN @S_OUTPUT
         AND   C~C5_SEL IN @LT_C5_SEL
         INTO TABLE @MT_FUND.

  CHECK MT_FUND IS NOT INITIAL.

  "Get data for incurred expenditure from posting
  SELECT H~FMBELNR,
         H~FIKRS,
         I~FMBUZEI,
         I~BTART,
         I~RLDNR,
         I~GJAHR,
         I~STUNR,
         H~BUDAT,
         I~FKBTR,
         F~WAERS,
         I~FONDS,
         I~FISTL,
         I~FIPEX,
         I~KNGJAHR,
         I~KNBELNR,
         I~KNBUZEI
         FROM FMIFIHD AS H
         INNER JOIN FMIFIIT AS I ON  I~FMBELNR = H~FMBELNR
                                 AND I~FIKRS = H~FIKRS
         LEFT OUTER JOIN FM01 AS F ON F~FIKRS = H~FIKRS
         FOR ALL ENTRIES IN @MT_FUND
         WHERE H~FIKRS = @MT_FUND-FIKRS
         AND   I~FONDS = @MT_FUND-FINCODE
         AND   I~GJAHR IN @S_GJAHR
         AND   I~FIPEX IN @S_FIPEX
         AND   H~BUDAT <= @P_BLDAT  "Posting date
         INTO TABLE @MT_FMID.

  "Get data from bseg
  SELECT S~*
         FROM BSEG AS S
         INNER JOIN BKPF AS K ON  K~BUKRS = S~BUKRS
                              AND K~BELNR = S~BELNR
                              AND K~GJAHR = S~GJAHR
         LEFT OUTER JOIN T001 AS B ON B~BUKRS = S~BUKRS
         FOR ALL ENTRIES IN @MT_FUND
         WHERE S~BUKRS = @LV_BUKRS
         AND   S~GJAHR IN @S_GJAHR
         AND   S~AUGDT = '00000000'   "Don't take cleared items
         AND   S~GEBER = @MT_FUND-FINCODE
         AND   S~FIPOS IN @S_FIPEX
         AND   K~BUDAT <= @P_BLDAT  "Posting date
         INTO TABLE @MT_BSEG.

  "Compare
  LOOP AT MT_FMID INTO DATA(LS_FMID).
    CLEAR LS_RESULT.
    READ TABLE MT_BSEG INTO DATA(LS_BSEG) WITH KEY BUKRS = LV_BUKRS
                                                   BELNR = LS_FMID-KNBELNR
                                                   GJAHR = LS_FMID-KNGJAHR
                                                   BUZEI = LS_FMID-KNBUZEI.
    IF SY-SUBRC <> 0.
      MOVE-CORRESPONDING LS_FMID TO LS_RESULT.
      APPEND LS_RESULT TO LT_RESULT.
    ELSE.
      LV_TABIX = SY-TABIX.
      LV_BSEG_AMOUNT = LS_BSEG-DMBTR.
      IF LS_BSEG-SHKZG = 'S'.
        MULTIPLY LV_BSEG_AMOUNT BY -1.
      ENDIF.
      IF LS_FMID-FKBTR <> LV_BSEG_AMOUNT.
        MOVE-CORRESPONDING LS_FMID TO LS_RESULT.
        MOVE-CORRESPONDING LS_BSEG TO LS_RESULT.
        APPEND LS_RESULT TO LT_RESULT.
      ENDIF.
      DELETE MT_BSEG INDEX LV_TABIX.
    ENDIF.
  ENDLOOP.

  LOOP AT MT_BSEG INTO LS_BSEG.
    CLEAR LS_RESULT.
    MOVE-CORRESPONDING LS_BSEG TO LS_RESULT.
    APPEND LS_RESULT TO LT_RESULT.
  ENDLOOP.

  "Display ALV
  LO_ALV = NEW YCL_ALV( ).
  LO_ALV->YIF_ALV_DISPLAY~INIT_ALV( CHANGING IT_TABLE = LT_RESULT ).
  LO_ALV->YIF_ALV_DISPLAY~SET_MAIN_FUNCTIONS( IV_REPORT = SY-REPID ).
  LO_ALV->YIF_ALV_DISPLAY~DISPLAY_ALV( ).

  INCLUDE YFM_STAFF_COST_DISTRIBUT_FORM.