*&---------------------------------------------------------------------*
*& Report YFM_CONSTANT_DOLLAR
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT YFM_CONSTANT_DOLLAR_V2.

DATA GS_FMDERIVE TYPE FMDERIVE.
DATA GS_FUND_C5 TYPE YTFM_FUND_C5.
DATA GV_BEGBI TYPE DATUM.
DATA GV_ENDBI TYPE DATUM.
DATA GT_STORED_DATES TYPE YCL_FM_CONSTANT_DOLLAR_BL_V2=>TTY_STORED_LIST.
DATA GO_CONSTANT_DOLLAR_BL TYPE REF TO YCL_FM_CONSTANT_DOLLAR_BL_V2.
DATA GS_RETURN TYPE BAPIRETURN1.
DATA GV_LIST_TYPE(1) TYPE C.
DATA GV_MESSAGE TYPE STRING.
DATA GV_CHECK TYPE XFELD.

SELECTION-SCREEN BEGIN OF BLOCK B00 WITH FRAME TITLE TEXT-B00.
PARAMETERS P_FIKRS TYPE FM01-FIKRS OBLIGATORY.
SELECTION-SCREEN END OF BLOCK B00.
SELECTION-SCREEN BEGIN OF BLOCK B01 WITH FRAME TITLE TEXT-B01.
SELECT-OPTIONS S_TYPE FOR GS_FMDERIVE-FUND_TYP.
SELECT-OPTIONS S_FUND FOR GS_FMDERIVE-FUND.
SELECT-OPTIONS S_FICTR FOR GS_FMDERIVE-FUND_CENTER.
SELECT-OPTIONS S_C5_ID FOR GS_FUND_C5-C5_ID NO INTERVALS.
SELECTION-SCREEN END OF BLOCK B01.
SELECTION-SCREEN BEGIN OF BLOCK B02 WITH FRAME TITLE TEXT-B02.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(31) TEXT-C01 FOR FIELD P_BEGFY.
PARAMETERS P_BEGFY TYPE BUDT-RYEAR.
SELECTION-SCREEN COMMENT 52(5) TEXT-C02 FOR FIELD P_ENDFY.
PARAMETERS P_ENDFY TYPE BUDT-RYEAR.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK B02.
SELECTION-SCREEN BEGIN OF BLOCK B03 WITH FRAME TITLE TEXT-B03.
SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS P_FILTER AS CHECKBOX.
SELECTION-SCREEN COMMENT 2(40) TEXT-C03 FOR FIELD P_FILTER.
SELECTION-SCREEN COMMENT 43(1) TEXT-C00.
PARAMETERS P_PCT TYPE NUM2 DEFAULT '05'.
SELECTION-SCREEN COMMENT 49(1) TEXT-C04.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS P_EUREXP AS CHECKBOX.
SELECTION-SCREEN COMMENT 2(50) TEXT-C05 FOR FIELD P_EUREXP.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK B03.
SELECTION-SCREEN BEGIN OF BLOCK B04 WITH FRAME TITLE TEXT-B04.
SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS P_MAIN RADIOBUTTON GROUP R001 DEFAULT 'X'.
SELECTION-SCREEN COMMENT 2(70) TEXT-C06 FOR FIELD P_MAIN.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS P_DETA RADIOBUTTON GROUP R001.
SELECTION-SCREEN COMMENT 2(70) TEXT-C07 FOR FIELD P_DETA.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK B04.
SELECTION-SCREEN BEGIN OF BLOCK B05 WITH FRAME TITLE TEXT-B05.
PARAMETERS P_CURR RADIOBUTTON GROUP R002 DEFAULT 'X' USER-COMMAND STO.
SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS P_STOR RADIOBUTTON GROUP R002.
SELECTION-SCREEN COMMENT 2(25) TEXT-C08 FOR FIELD P_STOR.
SELECTION-SCREEN POSITION 30.
PARAMETERS P_CDATE TYPE DATUM MODIF ID SDA.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK B05.

INITIALIZATION.
  "Set FM area to UNES
  P_FIKRS = 'UNES'.
  "Set fiscal year period to current biennium
  YCL_CA_UTILITIES=>GET_BIENNIUM_FOR_DATE( IMPORTING EV_BEGBI = GV_BEGBI
                                                     EV_ENDBI = GV_ENDBI ).
  P_BEGFY = GV_BEGBI(4).
  P_ENDFY = GV_ENDBI(4).
  "Set fund type for GEF
  APPEND VALUE #( SIGN = 'I' OPTION = 'EQ' LOW = '001' HIGH = '099' ) TO S_TYPE.
  SET CURSOR FIELD 'S_FUND-LOW'.

AT SELECTION-SCREEN.
  GS_RETURN = YCL_FM_CONSTANT_DOLLAR_BL=>PRELIMINARY_CHECKS( IV_FIKRS = P_FIKRS
                                                             IV_BEGFY = P_BEGFY
                                                             IV_ENDFY = P_ENDFY ).
  IF GS_RETURN IS NOT INITIAL.
    MESSAGE ID GS_RETURN-ID TYPE GS_RETURN-TYPE NUMBER GS_RETURN-NUMBER
          WITH GS_RETURN-MESSAGE_V1 GS_RETURN-MESSAGE_V2 GS_RETURN-MESSAGE_V3 GS_RETURN-MESSAGE_V4.
  ENDIF.
  IF P_STOR = ABAP_TRUE.
    IF P_CDATE IS NOT INITIAL.
      YCL_FM_CONSTANT_DOLLAR_BL_V2=>GET_LIST_OF_STORED_DATES( IMPORTING ET_STORED_DATES = GT_STORED_DATES ).
      READ TABLE GT_STORED_DATES TRANSPORTING NO FIELDS WITH KEY REF_DATE = P_CDATE.
      IF SY-SUBRC <> 0.
        GV_MESSAGE = |{ TEXT-M01 } { P_CDATE }|.
        MESSAGE GV_MESSAGE TYPE 'E' .
      ENDIF.
    ELSE.
      IF GV_CHECK = ABAP_TRUE.
        MESSAGE TEXT-M02 TYPE 'E' .
      ELSE.
        GV_CHECK = ABAP_TRUE.
      ENDIF.
    ENDIF.
  ELSE.
    CLEAR P_CDATE.
    GV_CHECK = ABAP_FALSE.
  ENDIF.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR P_CDATE.
  YCL_FM_CONSTANT_DOLLAR_BL_V2=>GET_LIST_OF_STORED_DATES( IMPORTING ET_STORED_DATES = GT_STORED_DATES ).
  YCL_CA_UTILITIES=>VALUE_REQUEST_POPUP( EXPORTING IV_RETFIELD = 'REF_DATE'
                                                   IV_REPID = SY-REPID
                                                   IV_DYNPRO = SY-DYNNR
                                                   IV_DYNPROFIELD = 'P_CDATE'
                                                   IT_VALUE_TAB = GT_STORED_DATES ).

AT SELECTION-SCREEN OUTPUT.
  LOOP AT SCREEN.
    IF SCREEN-NAME = 'P_FIKRS'.
      SCREEN-INPUT = 0.
      MODIFY SCREEN.
    ENDIF.
    IF SCREEN-GROUP1 = 'SDA'.
      IF P_STOR = ABAP_TRUE.
        SCREEN-INPUT = 1.
      ELSE.
        SCREEN-INPUT = 0.
      ENDIF.
      MODIFY SCREEN.
    ENDIF.
  ENDLOOP.


START-OF-SELECTION.

  GO_CONSTANT_DOLLAR_BL = NEW YCL_FM_CONSTANT_DOLLAR_BL_V2( ).
  GO_CONSTANT_DOLLAR_BL->SET_SELECTION_VALUES( IV_SELNAME = 'P_FIKRS' IV_KIND = 'P' IV_VALUE = P_FIKRS ).
  GO_CONSTANT_DOLLAR_BL->SET_SELECTION_VALUES( IV_SELNAME = 'S_TYPE' IV_KIND = 'S' IT_VALUE = S_TYPE[] ).
  GO_CONSTANT_DOLLAR_BL->SET_SELECTION_VALUES( IV_SELNAME = 'S_FUND' IV_KIND = 'S' IT_VALUE = S_FUND[] ).
  GO_CONSTANT_DOLLAR_BL->SET_SELECTION_VALUES( IV_SELNAME = 'S_FICTR' IV_KIND = 'S' IT_VALUE = S_FICTR[] ).
  GO_CONSTANT_DOLLAR_BL->SET_SELECTION_VALUES( IV_SELNAME = 'P_BEGFY' IV_KIND = 'P' IV_VALUE = P_BEGFY ).
  GO_CONSTANT_DOLLAR_BL->SET_SELECTION_VALUES( IV_SELNAME = 'P_ENDFY' IV_KIND = 'P' IV_VALUE = P_ENDFY ).
  GO_CONSTANT_DOLLAR_BL->SET_SELECTION_VALUES( IV_SELNAME = 'P_FILTER' IV_KIND = 'P' IV_VALUE = P_FILTER ).
  GO_CONSTANT_DOLLAR_BL->SET_SELECTION_VALUES( IV_SELNAME = 'P_PCT' IV_KIND = 'P' IV_VALUE = P_PCT ).
  GO_CONSTANT_DOLLAR_BL->SET_SELECTION_VALUES( IV_SELNAME = 'P_EUREXP' IV_KIND = 'P' IV_VALUE = P_EUREXP ).
  GO_CONSTANT_DOLLAR_BL->SET_SELECTION_VALUES( IV_SELNAME = 'S_C5_ID' IV_KIND = 'S' IT_VALUE = S_C5_ID[] ).
  GO_CONSTANT_DOLLAR_BL->SET_SELECTION_VALUES( IV_SELNAME = 'P_CDATE' IV_KIND = 'P' IV_VALUE = P_CDATE ).

  CASE ABAP_TRUE.
    WHEN P_MAIN.
      GV_LIST_TYPE = 'M'.
    WHEN P_DETA.
      GV_LIST_TYPE = 'D'.
  ENDCASE.

  "Get data
  CASE ABAP_TRUE.
    WHEN P_CURR.
      GO_CONSTANT_DOLLAR_BL->GET_DATA( ).
      "Prepare data for ALV
      GO_CONSTANT_DOLLAR_BL->PREPARE_DATA_FOR_ALV_LIST( IV_LIST_TYPE = GV_LIST_TYPE ).
    WHEN P_STOR.
      GO_CONSTANT_DOLLAR_BL->GET_DATA_FROM_HIST( ).
      "Prepare data for ALV
      GO_CONSTANT_DOLLAR_BL->PREPARE_DATA_FOR_ALV_HIST( IV_LIST_TYPE = GV_LIST_TYPE ).
  ENDCASE.

  "Display alv
  GO_CONSTANT_DOLLAR_BL->DISPLAY_ALV( SY-REPID ).