*&---------------------------------------------------------------------*
*& Report YFM_BR_POSTING_IN_FM
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT YFM_BR_POSTING_IN_FM.

DATA GV_PERNR TYPE P_PERNR.
DATA GT_RETURN TYPE BAPIRETTAB.
DATA GO_ALV TYPE REF TO YCL_ALV.


SELECTION-SCREEN BEGIN OF BLOCK B01 WITH FRAME TITLE TEXT-B01.
PARAMETERS P_RUNID TYPE PPOIX-RUNID OBLIGATORY.
SELECT-OPTIONS S_PERNR FOR GV_PERNR MATCHCODE OBJECT PREM.
SELECTION-SCREEN END OF BLOCK B01.
SELECTION-SCREEN BEGIN OF BLOCK B02 WITH FRAME TITLE TEXT-B02.
PARAMETERS P_CHECK RADIOBUTTON GROUP R001 DEFAULT 'X' USER-COMMAND R01.
SELECTION-SCREEN BEGIN OF BLOCK B21 WITH FRAME TITLE TEXT-B21.
PARAMETERS P_CHKPO RADIOBUTTON GROUP R002 DEFAULT 'X' USER-COMMAND R02 MODIF ID CHK.
PARAMETERS P_CHKPE RADIOBUTTON GROUP R002 MODIF ID CHK.
PARAMETERS P_TOLE TYPE YE_CA_DEC_3_2 DEFAULT '0.05' MODIF ID CHK.
SELECTION-SCREEN END OF BLOCK B21.
PARAMETERS P_POST RADIOBUTTON GROUP R001.
SELECTION-SCREEN BEGIN OF BLOCK B22 WITH FRAME TITLE TEXT-B22.
PARAMETERS P_FMPOST AS CHECKBOX DEFAULT 'X' MODIF ID PST.
PARAMETERS P_BRPOST AS CHECKBOX DEFAULT 'X' MODIF ID PST.
PARAMETERS P_TEST AS CHECKBOX DEFAULT 'X' MODIF ID PST.
SELECTION-SCREEN END OF BLOCK B22.
SELECTION-SCREEN END OF BLOCK B02.

AT SELECTION-SCREEN.
  IF P_POST = ABAP_TRUE AND P_TEST = ABAP_FALSE AND S_PERNR IS NOT INITIAL.
    MESSAGE TEXT-E01 TYPE 'E'.
  ENDIF.

AT SELECTION-SCREEN OUTPUT.
  LOOP AT SCREEN.
    CASE SCREEN-GROUP1.
      WHEN 'CHK'.
        IF P_CHECK = ABAP_TRUE.
          SCREEN-ACTIVE = 1.
        ELSE.
          SCREEN-ACTIVE = 0.
        ENDIF.
      WHEN 'PST'.
        IF P_POST = ABAP_TRUE.
          SCREEN-ACTIVE = 1.
        ELSE.
          SCREEN-ACTIVE = 0.
        ENDIF.
    ENDCASE.
    MODIFY SCREEN.
  ENDLOOP.

START-OF-SELECTION.

  GO_ALV = NEW YCL_ALV( ).

  YCL_FM_BR_POSTING_IN_FM_BL=>PREPARE_DATA_FROM_RUNID( EXPORTING IV_RUNID = P_RUNID
                                                                 IT_PERNR = S_PERNR[]
                                                       IMPORTING ET_RETURN = GT_RETURN ).

  READ TABLE GT_RETURN TRANSPORTING NO FIELDS WITH KEY TYPE = 'E'.
  IF SY-SUBRC = 0.
    GO_ALV->YIF_ALV_DISPLAY~INIT_ALV( CHANGING IT_TABLE = GT_RETURN ).
  ELSE.
    CASE ABAP_TRUE.
      WHEN P_CHECK.
        CASE ABAP_TRUE.
          WHEN P_CHKPE.
            YCL_FM_BR_POSTING_IN_FM_BL=>CHECK_DISTRIBUTION( IV_TOLERANCE = P_TOLE ).
            GO_ALV->YIF_ALV_DISPLAY~INIT_ALV( CHANGING IT_TABLE = YCL_FM_BR_POSTING_IN_FM_BL=>MT_LIST_PERNR ).
            GO_ALV->YIF_ALV_DISPLAY~SET_COL_TEXT( IV_FIELD = 'DMBTR_9' IV_TEXT = '999999x Local amount' ).
            GO_ALV->YIF_ALV_DISPLAY~SET_COL_TEXT( IV_FIELD = 'WRBTR_9' IV_TEXT = '999999x trans amount' ).
            GO_ALV->YIF_ALV_DISPLAY~SET_COL_TEXT( IV_FIELD = 'DMBTR_D' IV_TEXT = '6xxxxxx Local amount' ).
            GO_ALV->YIF_ALV_DISPLAY~SET_COL_TEXT( IV_FIELD = 'WRBTR_D' IV_TEXT = '6xxxxxx trans amount' ).
          WHEN P_CHKPO.
            YCL_FM_BR_POSTING_IN_FM_BL=>PREPARE_DATA_FOR_POSTING( IV_RUNID = P_RUNID ).
            YCL_FM_BR_POSTING_IN_FM_BL=>SET_POSTING_LIST( ).
            GO_ALV->YIF_ALV_DISPLAY~INIT_ALV( CHANGING IT_TABLE = YCL_FM_BR_POSTING_IN_FM_BL=>MT_LIST_POST_CHK ).
        ENDCASE.
      WHEN P_POST.
        YCL_FM_BR_POSTING_IN_FM_BL=>PREPARE_DATA_FOR_POSTING( IV_RUNID = P_RUNID ).
        YCL_FM_BR_POSTING_IN_FM_BL=>POST( IV_RUNID = P_RUNID
                                          IV_MODE_TEST = P_TEST
                                          IV_FM_POST = P_FMPOST
                                          IV_BR_POST = P_BRPOST ).
        GO_ALV->YIF_ALV_DISPLAY~INIT_ALV( CHANGING IT_TABLE = YCL_FM_BR_POSTING_IN_FM_BL=>MT_LIST_POST_EXE ).
        GO_ALV->YIF_ALV_DISPLAY~SET_COL_TEXT( IV_FIELD = 'BETRG' IV_TEXT = 'Amount' ).
        GO_ALV->YIF_ALV_DISPLAY~SET_COL_TEXT( IV_FIELD = 'STATUS_FM' IV_TEXT = 'Post in FM' ).
        GO_ALV->YIF_ALV_DISPLAY~SET_COL_TEXT( IV_FIELD = 'STATUS_BR' IV_TEXT = 'Post in BR tables' ).
    ENDCASE.
  ENDIF.

  GO_ALV->YIF_ALV_DISPLAY~SET_MAIN_FUNCTIONS( IV_REPORT = SY-REPID ).
  GO_ALV->YIF_ALV_DISPLAY~DISPLAY_ALV( ).