*&---------------------------------------------------------------------*
*& Report YFM_BR_POSTING_REPORT
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT YFM_BR_POSTING_REPORT.

DATA GV_DATUM TYPE DATUM.
DATA GS_SKB1 TYPE SKB1.
DATA GS_BKPF TYPE BKPF.
DATA GV_PERNR TYPE P_PERNR.
DATA GO_FM_BR_POSTING_REPORT TYPE REF TO YCL_FM_BR_POSTING_REPORT.
DATA GO_ALV TYPE REF TO YCL_ALV.

SELECTION-SCREEN BEGIN OF BLOCK B01 WITH FRAME TITLE TEXT-B01.
SELECT-OPTIONS S_DATE FOR GV_DATUM NO-EXTENSION.
SELECTION-SCREEN END OF BLOCK B01.
SELECTION-SCREEN BEGIN OF BLOCK B02 WITH FRAME TITLE TEXT-B02.
PARAMETERS P_POST RADIOBUTTON GROUP R001 DEFAULT 'X' USER-COMMAND RAD.
PARAMETERS P_PER RADIOBUTTON GROUP R001.
SELECTION-SCREEN END OF BLOCK B02.
SELECTION-SCREEN BEGIN OF BLOCK B03 WITH FRAME TITLE TEXT-B03.
PARAMETERS P_BUKRS TYPE BUKRS OBLIGATORY MODIF ID POS.
SELECT-OPTIONS S_BLART FOR GS_BKPF-BLART NO INTERVALS MODIF ID POS.
SELECT-OPTIONS S_SAKNR FOR GS_SKB1-SAKNR MODIF ID POS.
SELECTION-SCREEN END OF BLOCK B03.
SELECTION-SCREEN BEGIN OF BLOCK B04 WITH FRAME TITLE TEXT-B04.
SELECT-OPTIONS S_PERNR FOR GV_PERNR MATCHCODE OBJECT PREM MODIF ID PER.
SELECTION-SCREEN END OF BLOCK B04.


INITIALIZATION.
  "Get current commpany code
  GET PARAMETER ID 'BUK' FIELD P_BUKRS.
  "Get current biennium
  YCL_CA_UTILITIES=>GET_BIENNIUM_FOR_DATE( IMPORTING EV_BEGBI = S_DATE-LOW
                                                     EV_ENDBI = S_DATE-HIGH ).
  S_DATE-SIGN = 'I'.
  S_DATE-OPTION = 'BT'.
  APPEND S_DATE.

AT SELECTION-SCREEN OUTPUT.
  LOOP AT SCREEN.
    CASE SCREEN-GROUP1.
      WHEN 'POS'.
        IF P_POST = ABAP_TRUE.
          SCREEN-ACTIVE = 1.
        ELSE.
          SCREEN-ACTIVE = 0.
        ENDIF.
      WHEN 'PER'.
        IF P_PER = ABAP_TRUE.
          SCREEN-ACTIVE = 1.
        ELSE.
          SCREEN-ACTIVE = 0.
        ENDIF.
    ENDCASE.
    MODIFY SCREEN.
  ENDLOOP.


START-OF-SELECTION.

  GO_FM_BR_POSTING_REPORT = NEW YCL_FM_BR_POSTING_REPORT( ).
  GO_FM_BR_POSTING_REPORT->SET_SELECTION_VALUES( IV_SELNAME = 'S_DATE' IV_KIND = 'S' IT_VALUE = S_DATE[] ).
  GO_FM_BR_POSTING_REPORT->SET_SELECTION_VALUES( IV_SELNAME = 'P_BUKRS' IV_KIND = 'P' IV_VALUE = P_BUKRS ).
  GO_FM_BR_POSTING_REPORT->SET_SELECTION_VALUES( IV_SELNAME = 'S_BLART' IV_KIND = 'S' IT_VALUE = S_BLART[] ).
  GO_FM_BR_POSTING_REPORT->SET_SELECTION_VALUES( IV_SELNAME = 'S_SAKNR' IV_KIND = 'S' IT_VALUE = S_SAKNR[] ).
  GO_FM_BR_POSTING_REPORT->SET_SELECTION_VALUES( IV_SELNAME = 'S_PERNR' IV_KIND = 'S' IT_VALUE = S_PERNR[] ).

  GO_ALV = NEW YCL_ALV( ).

  CASE ABAP_TRUE.
    WHEN P_POST.
      GO_FM_BR_POSTING_REPORT->READ_DATA_FROM_BR_PAYP( ).
      GO_ALV->YIF_ALV_DISPLAY~INIT_ALV( CHANGING IT_TABLE = GO_FM_BR_POSTING_REPORT->MT_BR_POST ).
    WHEN P_PER.
      GO_FM_BR_POSTING_REPORT->READ_DATA_FROM_BR_PAYPER( ).
      GO_ALV->YIF_ALV_DISPLAY~INIT_ALV( CHANGING IT_TABLE = GO_FM_BR_POSTING_REPORT->MT_LIST_PERNR ).
      GO_ALV->YIF_ALV_DISPLAY~SET_COL_TEXT( IV_FIELD = 'DMBTR_9' IV_TEXT = '999999x Local amount' ).
      GO_ALV->YIF_ALV_DISPLAY~SET_COL_TEXT( IV_FIELD = 'WRBTR_9' IV_TEXT = '999999x trans amount' ).
      GO_ALV->YIF_ALV_DISPLAY~SET_COL_TEXT( IV_FIELD = 'DMBTR_D' IV_TEXT = '6xxxxxx Local amount' ).
      GO_ALV->YIF_ALV_DISPLAY~SET_COL_TEXT( IV_FIELD = 'WRBTR_D' IV_TEXT = '6xxxxxx trans amount' ).
      GO_ALV->YIF_ALV_DISPLAY~SET_COL_TEXT( IV_FIELD = 'PERIOD' IV_TEXT = 'Period' ).
  ENDCASE.

  GO_ALV->YIF_ALV_DISPLAY~SET_MAIN_FUNCTIONS( IV_REPORT = SY-REPID ).
  GO_ALV->YIF_ALV_DISPLAY~DISPLAY_ALV( ).