*&---------------------------------------------------------------------*
*& Report YFM_FI_COMPARE_INCLUDING_BR
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT YFM_FI_COMPARE_INCLUDING_BR.

DATA GS_BSEG TYPE BSEG.
DATA GS_BKPF TYPE BKPF.
DATA GO_COMPARE_BL TYPE REF TO YCL_FM_FI_COMPARE_BL.
DATA GV_DISPLAY_RESTRICTION TYPE CHAR1.

SELECTION-SCREEN BEGIN OF BLOCK B01 WITH FRAME TITLE TEXT-B01.
PARAMETERS P_BUKRS TYPE BUKRS OBLIGATORY.
SELECT-OPTIONS S_HKONT FOR GS_BSEG-HKONT.
PARAMETERS P_30ONLY TYPE FM30ONLY DEFAULT ABAP_TRUE.
SELECTION-SCREEN END OF BLOCK B01.
SELECTION-SCREEN BEGIN OF BLOCK B02 WITH FRAME TITLE TEXT-B02.
PARAMETERS P_GJAHR TYPE GJAHR OBLIGATORY.
SELECT-OPTIONS S_PERIO FOR GS_BKPF-MONAT NO-EXTENSION OBLIGATORY.
SELECTION-SCREEN END OF BLOCK B02.
SELECTION-SCREEN BEGIN OF BLOCK B03 WITH FRAME TITLE TEXT-B03.
SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS P_DIFF1 RADIOBUTTON GROUP R001 DEFAULT 'X'.
SELECTION-SCREEN COMMENT 2(70) TEXT-C01 FOR FIELD P_DIFF1.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS P_DIFF2 RADIOBUTTON GROUP R001.
SELECTION-SCREEN COMMENT 2(70) TEXT-C02 FOR FIELD P_DIFF2.
SELECTION-SCREEN END OF LINE.
PARAMETERS P_ALL RADIOBUTTON GROUP R001.
SELECTION-SCREEN END OF BLOCK B03.

INITIALIZATION.
  GET PARAMETER ID 'BUK' FIELD P_BUKRS.
  "Put the last period
  IF SY-DATUM+4(2) = '01'.
    P_GJAHR = SY-DATUM(4) - 1.
    APPEND VALUE #( SIGN = 'I' OPTION = 'BT' LOW = '01' HIGH = '16' ) TO S_PERIO.
  ELSE.
    P_GJAHR = SY-DATUM(4).
    GS_BKPF-MONAT = SY-DATUM+4(2) - 1.
    APPEND VALUE #( SIGN = 'I' OPTION = 'BT' LOW = '01' HIGH = GS_BKPF-MONAT ) TO S_PERIO.
  ENDIF.

START-OF-SELECTION.

  "Set display restriction
  CASE ABAP_TRUE.
    WHEN P_DIFF1.
      GV_DISPLAY_RESTRICTION = YCL_FM_FI_COMPARE_BL=>C_DIFF_DATABASE.
    WHEN P_DIFF2.
      GV_DISPLAY_RESTRICTION = YCL_FM_FI_COMPARE_BL=>C_DIFF_BR.
    WHEN P_ALL.
      GV_DISPLAY_RESTRICTION = YCL_FM_FI_COMPARE_BL=>C_NO_RESTRICTION.
  ENDCASE.

  GO_COMPARE_BL = NEW YCL_FM_FI_COMPARE_BL( IV_BUKRS = P_BUKRS
                                            IV_GJAHR = P_GJAHR
                                            IT_MONAT = S_PERIO[]
                                            IT_HKONT = S_HKONT[] ).
  GO_COMPARE_BL->GET_TOTAL_DATA( IV_30_ONLY = P_30ONLY
                                 IV_DISPLAY_RESTRICTION = GV_DISPLAY_RESTRICTION ).
  GO_COMPARE_BL->DISPLAY_TOTAL( SY-REPID ).