*&---------------------------------------------------------------------*
*& Report YFM_CONSTANT_DOLLAR
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT YFM_CONSTANT_DOLLAR_DB_V2.

DATA GS_FMDERIVE TYPE FMDERIVE.
DATA GS_FUND_C5 TYPE YTFM_FUND_C5.
DATA GV_BEGBI TYPE DATUM.
DATA GV_ENDBI TYPE DATUM.
DATA GO_CONSTANT_DOLLAR_BL TYPE REF TO YCL_FM_CONSTANT_DOLLAR_BL_V2.
DATA GS_RETURN TYPE BAPIRETURN1.

SELECTION-SCREEN BEGIN OF BLOCK B00 WITH FRAME TITLE TEXT-B00.
PARAMETERS P_FIKRS TYPE FM01-FIKRS OBLIGATORY.
SELECTION-SCREEN END OF BLOCK B00.
SELECTION-SCREEN BEGIN OF BLOCK B01 WITH FRAME TITLE TEXT-B01.
SELECT-OPTIONS S_TYPE FOR GS_FMDERIVE-FUND_TYP.
SELECT-OPTIONS S_FUND FOR GS_FMDERIVE-FUND.
SELECT-OPTIONS S_FICTR FOR GS_FMDERIVE-FUND_CENTER.
SELECT-OPTIONS S_C5_ID FOR GS_FUND_C5-C5_ID NO INTERVALS.
SELECTION-SCREEN END OF BLOCK B01.
SELECTION-SCREEN BEGIN OF BLOCK B02 WITH FRAME TITLE TEXT-B02.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(31) TEXT-C01 FOR FIELD P_BEGFY.
PARAMETERS P_BEGFY TYPE BUDT-RYEAR.
SELECTION-SCREEN COMMENT 52(5) TEXT-C02 FOR FIELD P_ENDFY.
PARAMETERS P_ENDFY TYPE BUDT-RYEAR.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK B02.
SELECTION-SCREEN BEGIN OF BLOCK B03 WITH FRAME TITLE TEXT-B03.
PARAMETERS P_TEST AS CHECKBOX DEFAULT 'X'.
PARAMETERS P_CDATE TYPE DATUM OBLIGATORY.
SELECTION-SCREEN END OF BLOCK B03.


INITIALIZATION.
  "Set FM area to UNES
  P_FIKRS = 'UNES'.
  "Set fiscal year period to current biennium
  YCL_CA_UTILITIES=>GET_BIENNIUM_FOR_DATE( IMPORTING EV_BEGBI = GV_BEGBI
                                                     EV_ENDBI = GV_ENDBI ).
  P_BEGFY = GV_BEGBI(4).
  P_ENDFY = GV_ENDBI(4).
  "Set cutoff date the previous day
  P_CDATE = SY-DATUM - 1.
  "Set fund type for GEF
  APPEND VALUE #( SIGN = 'I' OPTION = 'EQ' LOW = '001' HIGH = '099' ) TO S_TYPE.
  SET CURSOR FIELD 'S_FUND-LOW'.

AT SELECTION-SCREEN.
  GS_RETURN = YCL_FM_CONSTANT_DOLLAR_BL=>PRELIMINARY_CHECKS( IV_FIKRS = P_FIKRS
                                                             IV_BEGFY = P_BEGFY
                                                             IV_ENDFY = P_ENDFY ).
  IF GS_RETURN IS NOT INITIAL.
    MESSAGE ID GS_RETURN-ID TYPE GS_RETURN-TYPE NUMBER GS_RETURN-NUMBER
          WITH GS_RETURN-MESSAGE_V1 GS_RETURN-MESSAGE_V2 GS_RETURN-MESSAGE_V3 GS_RETURN-MESSAGE_V4.
  ENDIF.

AT SELECTION-SCREEN OUTPUT.
  LOOP AT SCREEN.
    IF SCREEN-NAME = 'P_FIKRS'.
      SCREEN-INPUT = 0.
      MODIFY SCREEN.
    ENDIF.
  ENDLOOP.


START-OF-SELECTION.

  GO_CONSTANT_DOLLAR_BL = NEW YCL_FM_CONSTANT_DOLLAR_BL_V2( ).
  GO_CONSTANT_DOLLAR_BL->SET_SELECTION_VALUES( IV_SELNAME = 'P_FIKRS' IV_KIND = 'P' IV_VALUE = P_FIKRS ).
  GO_CONSTANT_DOLLAR_BL->SET_SELECTION_VALUES( IV_SELNAME = 'S_TYPE' IV_KIND = 'S' IT_VALUE = S_TYPE[] ).
  GO_CONSTANT_DOLLAR_BL->SET_SELECTION_VALUES( IV_SELNAME = 'S_FUND' IV_KIND = 'S' IT_VALUE = S_FUND[] ).
  GO_CONSTANT_DOLLAR_BL->SET_SELECTION_VALUES( IV_SELNAME = 'S_FICTR' IV_KIND = 'S' IT_VALUE = S_FICTR[] ).
  GO_CONSTANT_DOLLAR_BL->SET_SELECTION_VALUES( IV_SELNAME = 'P_BEGFY' IV_KIND = 'P' IV_VALUE = P_BEGFY ).
  GO_CONSTANT_DOLLAR_BL->SET_SELECTION_VALUES( IV_SELNAME = 'P_ENDFY' IV_KIND = 'P' IV_VALUE = P_ENDFY ).
  GO_CONSTANT_DOLLAR_BL->SET_SELECTION_VALUES( IV_SELNAME = 'S_C5_ID' IV_KIND = 'S' IT_VALUE = S_C5_ID[] ).
  GO_CONSTANT_DOLLAR_BL->SET_SELECTION_VALUES( IV_SELNAME = 'P_CDATE' IV_KIND = 'P' IV_VALUE = P_CDATE ).

  "Get data
  GO_CONSTANT_DOLLAR_BL->GET_DATA( ).
  "Prepare data for ALV
  GO_CONSTANT_DOLLAR_BL->INSERT_INTO_DATABASE( ).

  IF P_TEST = ABAP_TRUE.
    ROLLBACK WORK.
  ELSE.
    COMMIT WORK.
  ENDIF.

  GO_CONSTANT_DOLLAR_BL->DISPLAY_MESSAGE( SY-REPID ).