*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZ_WF_FI_EVENT_PAYMENT_METHU01.
                    "Z_WF_FI_BSEG_EVENT_PAYM_METHOD