CLASS CL_IDFI_CGI_DMEE_FALLBACK DEFINITION
  PUBLIC
  CREATE PUBLIC .

PUBLIC SECTION.
  TYPE-POOLS ABAP .

  INTERFACES IF_BADI_INTERFACE .
  INTERFACES IF_IDFI_CGI_DMEE_COUNTRIES .

  CONSTANTS GC_BANK TYPE STRING VALUE 'BANK' ##NO_TEXT.
  CONSTANTS GC_BBAN TYPE STRING VALUE 'BBAN' ##NO_TEXT.
  CONSTANTS GC_BGNR TYPE STRING VALUE 'BGNR' ##NO_TEXT.
  CONSTANTS GC_CDTDBTIND_CRDT TYPE STRING VALUE 'CRDT' ##NO_TEXT.
  CONSTANTS GC_CDTDBTIND_DBIT TYPE STRING VALUE 'DBIT' ##NO_TEXT.
  CONSTANTS GC_CHK TYPE STRING VALUE 'CHK' ##NO_TEXT.
  CONSTANTS GC_CHQTP_BCHQ TYPE STRING VALUE 'BCHQ' ##NO_TEXT.
  CONSTANTS GC_CHQTP_CCHQ TYPE STRING VALUE 'CCHQ' ##NO_TEXT.
  CONSTANTS GC_CHQTP_DRFT TYPE STRING VALUE 'DRFT' ##NO_TEXT.
  CONSTANTS GC_CHQTP_ELDR TYPE STRING VALUE 'ELDR' ##NO_TEXT.
  CONSTANTS GC_CHRGBR_CRED TYPE STRING VALUE 'CRED' ##NO_TEXT.
  CONSTANTS GC_CHRGBR_DEBT TYPE STRING VALUE 'DEBT' ##NO_TEXT.
  CONSTANTS GC_CHRGBR_SHAR TYPE STRING VALUE 'SHAR' ##NO_TEXT.
  CONSTANTS GC_CINV TYPE STRING VALUE 'CINV' ##NO_TEXT.
  CONSTANTS GC_CREN TYPE STRING VALUE 'CREN' ##NO_TEXT.
  CONSTANTS GC_CTGYPURP_CD_CASH TYPE STRING VALUE 'CASH' ##NO_TEXT.
  CONSTANTS GC_CTGYPURP_CD_DIVI TYPE STRING VALUE 'DIVI' ##NO_TEXT.
  CONSTANTS GC_CTGYPURP_CD_INTC TYPE STRING VALUE 'INTC' ##NO_TEXT.
  CONSTANTS GC_CTGYPURP_CD_PENS TYPE STRING VALUE 'PENS' ##NO_TEXT.
  CONSTANTS GC_CTGYPURP_CD_SALA TYPE STRING VALUE 'SALA' ##NO_TEXT.
  CONSTANTS GC_CTGYPURP_CD_SUPP TYPE STRING VALUE 'SUPP' ##NO_TEXT.
  CONSTANTS GC_CTGYPURP_CD_TREA TYPE STRING VALUE 'TREA' ##NO_TEXT.
  CONSTANTS GC_CUST TYPE STRING VALUE 'CUST' ##NO_TEXT.
  CONSTANTS GC_DLVRYMTD_MLCD TYPE STRING VALUE 'MLCD' ##NO_TEXT.
  CONSTANTS GC_DLVRYMTD_MLDB TYPE STRING VALUE 'MLDB' ##NO_TEXT.
  CONSTANTS GC_DR TYPE STRING VALUE 'DR' ##NO_TEXT.
  CONSTANTS GC_TR_CM_BT TYPE STRING VALUE 'TR-CM-BT' ##NO_TEXT.
  CONSTANTS GC_HR_PY TYPE STRING VALUE 'HR-PY' ##NO_TEXT.
  CONSTANTS GC_INSTRPRTY_HIGH TYPE STRING VALUE 'HIGH' ##NO_TEXT.
  CONSTANTS GC_INSTRPRTY_NORM TYPE STRING VALUE 'NORM' ##NO_TEXT.
  CONSTANTS GC_ISOCD TYPE STRING VALUE 'ISOCD' ##NO_TEXT.
  CONSTANTS GC_KR TYPE STRING VALUE 'KR' ##NO_TEXT.
  CONSTANTS GC_NOTPROVIDED TYPE STRING VALUE 'NOTPROVIDED' ##NO_TEXT.
  CONSTANTS GC_ONE_TIME_VENDOR TYPE STRING VALUE '14' ##NO_TEXT.
  CONSTANTS GC_SEPA TYPE STRING VALUE 'SEPA' ##NO_TEXT.
  CONSTANTS GC_SLEV TYPE STRING VALUE 'SLEV' ##NO_TEXT.
  CONSTANTS GC_SVCLVL_CD_BKTR TYPE STRING VALUE 'BKTR' ##NO_TEXT.
  CONSTANTS GC_SVCLVL_CD_NUGP TYPE STRING VALUE 'NUGP' ##NO_TEXT.
  CONSTANTS GC_SVCLVL_CD_NURG TYPE STRING VALUE 'NURG' ##NO_TEXT.
  CONSTANTS GC_SVCLVL_CD_PRPT TYPE STRING VALUE 'PRPT' ##NO_TEXT.
  CONSTANTS GC_SVCLVL_CD_SDVA TYPE STRING VALUE 'SDVA' ##NO_TEXT.
  CONSTANTS GC_SVCLVL_CD_URGP TYPE STRING VALUE 'URGP' ##NO_TEXT.
  CONSTANTS GC_SVCLVL_CD_URNS TYPE STRING VALUE 'URNS' ##NO_TEXT.
  CONSTANTS GC_SWIFT TYPE STRING VALUE 'SWIFT' ##NO_TEXT.
  CONSTANTS GC_SMNDA TYPE STRING VALUE 'SMNDA' ##NO_TEXT.
  CONSTANTS GC_TRF TYPE STRING VALUE 'TRF' ##NO_TEXT.
  CONSTANTS GC_ACCTTP_CACC TYPE STRING VALUE 'CACC' ##NO_TEXT.
  CONSTANTS GC_ACCTTP_CASH TYPE STRING VALUE 'CASH' ##NO_TEXT.
  CONSTANTS GC_ACCTTP_SVGS TYPE STRING VALUE 'SVGS' ##NO_TEXT.
  CONSTANTS GC_ACCTTP_LOAN TYPE STRING VALUE 'LOAN' ##NO_TEXT.
  CONSTANTS GC_CHID TYPE STRING VALUE 'CHID' ##NO_TEXT.
  CONSTANTS GC_OCR TYPE STRING VALUE 'OCR' ##NO_TEXT.
  CONSTANTS GC_DEBT TYPE STRING VALUE 'DEBT' ##NO_TEXT.
  CONSTANTS GC_SEPA_FLG TYPE STRING VALUE 'S' ##NO_TEXT.
  CONSTANTS GC_IN TYPE STRING VALUE 'IN' ##NO_TEXT.
  CONSTANTS GC_CREDIT TYPE STRING VALUE 'CREDIT' ##NO_TEXT.
  CONSTANTS GC_DEBIT TYPE STRING VALUE 'DEBIT' ##NO_TEXT.
  CONSTANTS GC_ISO TYPE STRING VALUE 'ISO' ##NO_TEXT.
  CONSTANTS GC_HRREF TYPE STRING VALUE 'HR Ref' ##NO_TEXT.
  CONSTANTS GC_HR TYPE STRING VALUE 'HR' ##NO_TEXT.
  CONSTANTS GC_55 TYPE STRING VALUE '55' ##NO_TEXT.
  CONSTANTS GC_OTHR TYPE STRING VALUE 'OTHR' ##NO_TEXT.
  CONSTANTS GC_SCOR TYPE STRING VALUE 'SCOR' ##NO_TEXT.
  CONSTANTS GC_QRR TYPE STRING VALUE 'QRR' ##NO_TEXT.
  CONSTANTS GC_NON TYPE STRING VALUE 'NON' ##NO_TEXT.
  CONSTANTS GC_01 TYPE STRING VALUE '01' ##NO_TEXT.
  CONSTANTS GC_99 TYPE STRING VALUE '99' ##NO_TEXT.