
************************************************************************
******** Data-definition TS-Cluster *Stand 3.0A ************************
************************************************************************

DATA: BEGIN OF TS-KEY,                 "Schlüssel TS-Cluster
*       INCLUDE STRUCTURE PTK40.
        PERNR LIKE PTK40-PERNR,
      END OF TS-KEY.

DATA: BEGIN OF OTS-VERSION,            "Version TS-Cluster
*       INCLUDE STRUCTURE PTK41.
        SAPRL LIKE PTK41-SAPRL,
        NUMBR LIKE PTK41-NUMBR,
      END OF OTS-VERSION.

DATA: BEGIN OF TS-VERSION,
        SAPRL LIKE OTS-VERSION-SAPRL,
        NUMBR LIKE OTS-VERSION-NUMBR VALUE '02',
      END OF TS-VERSION.

DATA: BEGIN OF REISEN OCCURS 100,      "Tabelle Reisen
*       INCLUDE STRUCTURE PTK42.
        ABRJ1 LIKE PTK42-ABRJ1,
        ABRP1 LIKE PTK42-ABRP1,
        ABRJ2 LIKE PTK42-ABRJ2,
        ABRP2 LIKE PTK42-ABRP2,
        REINR LIKE PTK42-REINR,
        LFDNR LIKE PTK42-LFDNR,
        DRUCK LIKE PTK42-DRUCK,
        ANTRG LIKE PTK42-ANTRG,
        ABREC LIKE PTK42-ABREC,
        UEBLG LIKE PTK42-UEBLG,
        UEBRF LIKE PTK42-UEBRF,
        UEBDT LIKE PTK42-UEBDT,
        DATV1 LIKE PTK42-DATV1,
        UHRV1 LIKE PTK42-UHRV1,
        DATB1 LIKE PTK42-DATB1,
        UHRB1 LIKE PTK42-UHRB1,
        ZLAND LIKE PTK42-ZLAND,
        ZORT1 LIKE PTK42-ZORT1,
        KUNDE LIKE PTK42-KUNDE,
        SCHEM LIKE PTK42-SCHEM,
        HRGIO LIKE PTK42-HRGIO,
      END OF REISEN.

DATA: BEGIN OF KMSUM OCCURS 3,         "Tabelle Kumulierte Kilometer
*       INCLUDE STRUCTURE PTK43.
        PERNA LIKE  PTK43-PERNA,
        KMSUM LIKE  PTK43-KMSUM,
      END OF KMSUM.

***** Zusatzdefinition  (nicht im TS-Cluster) **********************

DATA: BEGIN OF TS-SCHLUESSEL,
        PERNR LIKE TS-KEY-PERNR,
        FUELLER(14) VALUE '%             ',
      END OF TS-SCHLUESSEL.

************************************************************************
******** Data-Definition TE-Cluster PCL1 *Stand 3.0A********************
************************************************************************

DATA: BEGIN OF TE-KEY,                 "Schlüssel TE-Cluster
*       INCLUDE STRUCTURE PTK00.
        PERNR LIKE PTK00-PERNR,
        REINR LIKE PTK00-REINR,
        LFDNR LIKE PTK00-LFDNR,
      END OF TE-KEY.

DATA: BEGIN OF OTE-VERSION,            "TE-Version auf PCL1
*       INCLUDE STRUCTURE PTK01.
        SAPRL LIKE PTK01-SAPRL,
        NUMBR LIKE PTK01-NUMBR,
      END OF OTE-VERSION.

DATA: BEGIN OF TE-VERSION,             "TE-Version Datenbeschreibung
        SAPRL LIKE OTE-VERSION-SAPRL,
        NUMBR LIKE OTE-VERSION-NUMBR VALUE '02',
      END OF TE-VERSION.

DATA: BEGIN OF KOPF,                   "Kopfdaten Einzelreise
*       INCLUDE STRUCTURE PTK02.
        ABRJ1 LIKE PTK02-ABRJ1,
        ABRP1 LIKE PTK02-ABRP1,
        ABRJ2 LIKE PTK02-ABRJ2,
        ABRP2 LIKE PTK02-ABRP2,
        MOLGA LIKE PTK02-MOLGA,
        MOREI LIKE PTK02-MOREI,
        SCHEM LIKE PTK02-SCHEM,
        BEREI LIKE PTK02-BEREI,
        ZORT1 LIKE PTK02-ZORT1,
        ZLAND LIKE PTK02-ZLAND,
        KUNDE LIKE PTK02-KUNDE,
        DATV1 LIKE PTK02-DATV1,
        UHRV1 LIKE PTK02-UHRV1,
        DATB1 LIKE PTK02-DATB1,
        UHRB1 LIKE PTK02-UHRB1,
        DATAN LIKE PTK02-DATAN,
        UHRAN LIKE PTK02-UHRAN,
        DATAB LIKE PTK02-DATAB,
        UHRAB LIKE PTK02-UHRAB,
        DATH1 LIKE PTK02-DATH1,
        UHRH1 LIKE PTK02-UHRH1,
        DATR1 LIKE PTK02-DATR1,
        UHRR1 LIKE PTK02-UHRR1,
        AGRZ1 LIKE PTK02-AGRZ1,
        AUFNR LIKE PTK02-AUFNR,
        KOSTL LIKE PTK02-KOSTL,
        KZREA LIKE PTK02-KZREA,
        KZTKT LIKE PTK02-KZTKT,
        KZPMF LIKE PTK02-KZPMF,
        PKWKL LIKE PTK02-PKWKL,
        AZMIT LIKE PTK02-AZMIT,
        KMGES LIKE PTK02-KMGES,
        KMINL LIKE PTK02-KMINL,
        BETPA LIKE PTK02-BETPA,
        KGGEP LIKE PTK02-KGGEP,
        VERPA LIKE PTK02-VERPA,
        UEBKZ LIKE PTK02-UEBKZ,
        ANUEP LIKE PTK02-ANUEP,
        GRBER LIKE PTK02-GRBER,
        PKWRG LIKE PTK02-PKWRG,
        ERKLA LIKE PTK02-ERKLA,
        ERGRU LIKE PTK02-ERGRU,
        POSNR LIKE PTK02-POSNR,
        NPLNR LIKE PTK02-NPLNR,
        VORNR LIKE PTK02-VORNR,
        HRGIO LIKE PTK02-HRGIO,
        GRGIO LIKE PTK02-GRGIO,
      END OF KOPF.

DATA: BEGIN OF BELEG OCCURS 20,        "Tabelle Einzelbelege
*       INCLUDE STRUCTURE PTK03.
        BELNR LIKE PTK03-BELNR,
        SPKZL LIKE PTK03-SPKZL,
        BEART LIKE PTK03-BEART,
        MWSKZ LIKE PTK03-MWSKZ,
        BETRG LIKE PTK03-BETRG,
        BLDAT LIKE PTK03-BLDAT,
        BTEXT LIKE PTK03-BTEXT,
        WAERS LIKE PTK03-WAERS,
        KURSB LIKE PTK03-KURSB,
        FFACT LIKE PTK03-FFACT,
        TFACT LIKE PTK03-TFACT,
        ANZFR LIKE PTK03-ANZFR,
        LNDFR LIKE PTK03-LNDFR,
        BERFR LIKE PTK03-BERFR,
        RGION LIKE PTK03-RGION,
      END OF BELEG.

DATA: BEGIN OF ABZUG OCCURS 20,        "Tabelle Abzüge
*       INCLUDE STRUCTURE PTK04.
        ABDAT LIKE PTK04-ABDAT,
        FRSTK LIKE PTK04-FRSTK,
        MITAG LIKE PTK04-MITAG,
        ABEND LIKE PTK04-ABEND,
        ESBON LIKE PTK04-ESBON,
        ZIKEY LIKE PTK04-ZIKEY,
      END OF ABZUG.

DATA: BEGIN OF ZIEL OCCURS 10,         "Tabelle Ziele
*       INCLUDE STRUCTURE PTK05.
        ZIKEY LIKE PTK05-ZIKEY,
        KZREA LIKE PTK05-KZREA,
        KZTKT LIKE PTK05-KZTKT,
        ZLAND LIKE PTK05-ZLAND,
        BEREI LIKE PTK05-BEREI,
        ZORT1 LIKE PTK05-ZORT1,
        KUNDE LIKE PTK05-KUNDE,
        RVDAT LIKE PTK05-RVDAT,
        RVUHR LIKE PTK05-RVUHR,
        RBDAT LIKE PTK05-RBDAT,
        RBUHR LIKE PTK05-RBUHR,
        RADAT LIKE PTK05-RADAT,
        RAUHR LIKE PTK05-RAUHR,
        UEBPA LIKE PTK05-UEBPA,
        KZPRI LIKE PTK05-KZPRI,
        RGION LIKE PTK05-RGION,
      END OF ZIEL.

DATA: BEGIN OF KONTI OCCURS 10,        "Tabelle Kontierung
        KOKEY(2),
*       INCLUDE STRUCTURE PSREF.
        BUKRS LIKE PSREF-BUKRS,
        GSBER LIKE PSREF-GSBER,
        KOKRS LIKE PSREF-KOKRS,
        KOSTL LIKE PSREF-KOSTL,
        AUFNR LIKE PSREF-AUFNR,
        KSTRG LIKE PSREF-KSTRG,
        POSNR LIKE PSREF-POSNR,
        NPLNR LIKE PSREF-NPLNR,
        VORNR LIKE PSREF-VORNR,
        KDAUF LIKE PSREF-KDAUF,
        KDPOS LIKE PSREF-KDPOS,
        PAOBJNR LIKE PSREF-PAOBJNR,
        PRZNR LIKE PSREF-PRZNR,
        FISTL LIKE PSREF-FISTL,
        FIPOS LIKE PSREF-FIPOS,
        GEBER LIKE PSREF-GEBER,
        EBELN LIKE PSREF-EBELN,
        EBELP LIKE PSREF-EBELP,
        LSTNR LIKE PSREF-LSTNR,
        LTLST LIKE PSREF-LTLST,
        SBUKR LIKE PSREF-SBUKR,
        SGSBR LIKE PSREF-SGSBR,
        SKOST LIKE PSREF-SKOST,
        LSTAR LIKE PSREF-LSTAR,
        EXBEL LIKE PSREF-EXBEL,
        MWSKZ LIKE PSREF-MWSKZ,
        OTYPE LIKE PSREF-OTYPE,
        STELL LIKE PSREF-STELL,
        POHRS LIKE PSREF-POHRS,
      END OF KONTI.

DATA: BEGIN OF VSCH OCCURS 5,          "Tabelle Vorschüsse
*       INCLUDE STRUCTURE PTK08.
        VORSC LIKE PTK08-VORSC,
        WAERS LIKE PTK08-WAERS,
        KURSV LIKE PTK08-KURSV,
        FFACT LIKE PTK08-FFACT,
        TFACT LIKE PTK08-TFACT,
        VORHW LIKE PTK08-VORHW,
        KASSA LIKE PTK08-KASSA,
        DATVS LIKE PTK08-DATVS,
      END OF VSCH.

DATA: BEGIN OF ZWECK OCCURS 5,         "Tabelle Reisetext
*       INCLUDE STRUCTURE PTK09.
        ZEILE LIKE PTK09-ZEILE,
      END OF ZWECK.

DATA: BEGIN OF KMVER OCCURS 5,         "Tabelle Kilometeraufteilung
*       INCLUDE STRUCTURE PTK10.
        DATUM LIKE PTK10-DATUM,
        KMGES LIKE PTK10-KMGES,
        KMINL LIKE PTK10-KMINL,
        KFZKZ LIKE PTK10-KFZKZ,
        KFZMA LIKE PTK10-KFZMA,
        AZMIT LIKE PTK10-AZMIT,
        KGGEP LIKE PTK10-KGGEP,
        BETPA LIKE PTK10-BETPA,
        KZPMF LIKE PTK10-KZPMF,
        BEREI LIKE PTK10-BEREI,
        LAND1 LIKE PTK10-LAND1,
        PKWKL LIKE PTK10-PKWKL,
       END OF KMVER.

DATA: BEGIN OF AEND OCCURS 10,         "Tabelle Status/Änderer
*       INCLUDE STRUCTURE PTK11.
        DATUM LIKE PTK11-DATUM,
        UZEIT LIKE PTK11-UZEIT,
        UNAME LIKE PTK11-UNAME,
        REPID LIKE PTK11-REPID,
        DRUCK LIKE PTK11-DRUCK,
        ANTRG LIKE PTK11-ANTRG,
        ABREC LIKE PTK11-ABREC,
        UEBLG LIKE PTK11-UEBLG,
        UEBRF LIKE PTK11-UEBRF,
        UEBDT LIKE PTK11-UEBDT,
      END OF AEND.

DATA: BEGIN OF STATU,                  "Status der Reise
*       INCLUDE STRUCTURE PTK12.
        DRUCK LIKE PTK12-DRUCK,
        ANTRG LIKE PTK12-ANTRG,
        ABREC LIKE PTK12-ABREC,
        UEBLG LIKE PTK12-UEBLG,
        UEBRF LIKE PTK12-UEBRF,
        UEBDT LIKE PTK12-UEBDT,
      END OF STATU.

******* Results **************************

DATA: BEGIN OF BELER OCCURS 20,        "BELegERgebnisse
*       INCLUDE STRUCTURE PTK20.
        BELNR LIKE PTK20-BELNR,
        ABZUG LIKE PTK20-ABZUG,
        BETRG LIKE PTK20-BETRG,
        FIRMA LIKE PTK20-FIRMA,
      END OF BELER.

DATA: BEGIN OF PAUFA OCCURS 10,        "Ergebnis Fahrtkosten
*       INCLUDE STRUCTURE PTK21.
        KMKEY LIKE PTK21-KMKEY,
        ZIKEY LIKE PTK21-ZIKEY,
        DATUM LIKE PTK21-DATUM,
        KZPMF LIKE PTK21-KZPMF,
        KZNZA LIKE PTK21-KZNZA,
        WAERS LIKE PTK21-WAERS,
        BETFZ LIKE PTK21-BETFZ,
        BETFA LIKE PTK21-BETFA,
        BETKU LIKE PTK21-BETKU,
        ANZHL LIKE PTK21-ANZHL,
        GBTFZ LIKE PTK21-GBTFZ,
        GBTFA LIKE PTK21-GBTFA,
        GBTKU LIKE PTK21-GBTKU,
      END OF PAUFA.

DATA: BEGIN OF VPFPS OCCURS 10,   "Erstattungssätze fuer Verpflegung
*       INCLUDE STRUCTURE PTK22.
        DATV1 LIKE PTK22-DATV1,
        UHRV1 LIKE PTK22-UHRV1,
        DATB1 LIKE PTK22-DATB1,
        UHRB1 LIKE PTK22-UHRB1,
        VPFPH LIKE PTK22-VPFPH,
        VPFKZ LIKE PTK22-VPFKZ,
        ZIKEY LIKE PTK22-ZIKEY,
        WAERS LIKE PTK22-WAERS,
        ANZAL LIKE PTK22-ANZAL,
        BETFZ LIKE PTK22-BETFZ,
        BETFA LIKE PTK22-BETFA,
        BETKU LIKE PTK22-BETKU,
      END OF VPFPS.

DATA: BEGIN OF VPFPA OCCURS 10,        "Verpflegungsabzüge
*       INCLUDE STRUCTURE PTK23.
        DATV1 LIKE PTK23-DATV1,
        UHRV1 LIKE PTK23-UHRV1,
        DATB1 LIKE PTK23-DATB1,
        UHRB1 LIKE PTK23-UHRB1,
        VPFPH LIKE PTK23-VPFPH,
        VPFKZ LIKE PTK23-VPFKZ,
        ZIKEY LIKE PTK23-ZIKEY,
        WAERS LIKE PTK23-WAERS,
        BETFZ LIKE PTK23-BETFZ,
        BETFA LIKE PTK23-BETFA,
        BETKU LIKE PTK23-BETKU,
        ABBFZ LIKE PTK23-ABBFZ,
        ABBFA LIKE PTK23-ABBFA,
        ABBKU LIKE PTK23-ABBKU,
      END OF VPFPA.

DATA: BEGIN OF UEBPA OCCURS 10,        "Ergebnisse Übernachtungen
*       INCLUDE STRUCTURE PTK25.
        DATV1 LIKE PTK25-DATV1,
        DATB1 LIKE PTK25-DATB1,
        ZIKEY LIKE PTK25-ZIKEY,
        REDUZ LIKE PTK25-REDUZ,
        ANZAL LIKE PTK25-ANZAL,
        WAERS LIKE PTK25-WAERS,
        GBTFZ LIKE PTK25-GBTFZ,
        GBTFA LIKE PTK25-GBTFA,
        GBTKU LIKE PTK25-GBTKU,
      END OF UEBPA.

*ata: begin of rpriv,                  "Bukrs/Werk Änderung
*       INCLUDE STRUCTURE PTK26.
* PTK26 in 4.0 nicht mehr vorhandenn
*        bukrs like ptk26-bukrs,
*        werks like ptk26-werks,
*        gsber like ptk26-gsber,
*     end of rpriv.

DATA: BEGIN OF KOSTR OCCURS 25,        "Kostenaufteilung der Gesamtreise
*       INCLUDE STRUCTURE PTK14.
        KOKEY LIKE PTK14-KOKEY,
        AUFTL LIKE PTK14-AUFTL,
      END OF KOSTR.

DATA: BEGIN OF KOSTZ OCCURS 25,        "Kostenaufteilung pro Ziel
*       INCLUDE STRUCTURE PTK16.
        ZIKEY LIKE PTK16-ZIKEY,
        KOKEY LIKE PTK16-KOKEY,
        AUFTL LIKE PTK16-AUFTL,
      END OF KOSTZ.

DATA: BEGIN OF KOSTB OCCURS 25,        "Kostenaufteilung pro Beleg
*       INCLUDE STRUCTURE PTK07.
        BELNR LIKE PTK07-BELNR,
        SPKUE LIKE PTK07-SPKUE,
        ZIKEY LIKE PTK07-ZIKEY,
        KOKEY LIKE PTK07-KOKEY,
        WAERS LIKE PTK07-WAERS,
        AUFTL LIKE PTK07-AUFTL,
        BETPR LIKE PTK07-BETPR,
        BEART LIKE PTK07-BEART,
      END OF KOSTB.

DATA: BEGIN OF RUW OCCURS 10,          "Überweisung
*       INCLUDE STRUCTURE PTK27.
        UWZNR LIKE PTK27-UWZNR,
        LGART LIKE PTK27-LGART,
        BETRG LIKE PTK27-BETRG,
        WAERS LIKE PTK27-WAERS,
        ZLSCH LIKE PTK27-ZLSCH,
        EMFTX LIKE PTK27-EMFTX,
        BKPLZ LIKE PTK27-BKPLZ,
        BKORT LIKE PTK27-BKORT,
        BANKS LIKE PTK27-BANKS,
        BANKL LIKE PTK27-BANKL,
        BANKN LIKE PTK27-BANKN,
        EMFSL LIKE PTK27-EMFSL,
        ZWECK LIKE PTK27-ZWECK,
        VBAFM LIKE PTK27-VBAFM,
        DTANR LIKE PTK27-DTANR,
      END OF RUW.

******* Interface to RF / HR-Payroll calculation ********************
*** C1 PC20B ***
*** OT PC207 ***
DATA: BEGIN OF ROT OCCURS 10,          "Tabelle Überleitung HR, FI
*       INCLUDE STRUCTURE PTK30.
        ABART LIKE PTK30-ABART,
        LGART LIKE PTK30-LGART,
        APZNR LIKE PTK30-APZNR,
        CNTR1 LIKE PTK30-CNTR1,
        CNTR2 LIKE PTK30-CNTR2,
        CNTR3 LIKE PTK30-CNTR3,
        ALZNR LIKE PTK30-ALZNR,
        C1ZNR LIKE PTK30-C1ZNR,
        BTZNR LIKE PTK30-BTZNR,
        ABZNR LIKE PTK30-ABZNR,
        V0TYP LIKE PTK30-V0TYP,
        V0ZNR LIKE PTK30-V0ZNR,
        ZEINH LIKE PTK30-ZEINH,
        BETPE LIKE PTK30-BETPE,
        ANZHL LIKE PTK30-ANZHL,
        BETRG LIKE PTK30-BETRG,
        MWSKZ LIKE PTK30-MWSKZ,
      END OF ROT.

***** Zusatzdefinition  (nicht im TE-Cluster) **********************

DATA: BEGIN OF TE-SCHLUESSEL,
        PERNR LIKE TE-KEY-PERNR,
        REINR LIKE TE-KEY-REINR,
        LFDNR LIKE TE-KEY-LFDNR,
        FUELLER(2) VALUE '% ',                              "QDOK087771
      END OF TE-SCHLUESSEL.

DATA: BEGIN OF DEZI OCCURS 30,
*       INCLUDE STRUCTURE TCURX.
        CURRKEY LIKE TCURX-CURRKEY,
        CURRDEC LIKE TCURX-CURRDEC,
      END OF DEZI.

* Tabelle aus T549B
DATA: BEGIN OF VARIATION OCCURS 7,
        VARIA(21),
      END OF VARIATION.