REPORT RPRTRV01.

DATA: MODIF(1)    VALUE 'X',
      PRINT_E(1)  VALUE ' ',
      PRINT_T(1)  VALUE 'X',
      GET_TIME(1) VALUE 'X',
      T0 TYPE T,
      T1 TYPE T,
      T2 TYPE P,
      LI TYPE P.

DATA: BEGIN OF MESS_TAB OCCURS 100.
        INCLUDE STRUCTURE SPROT_U.
DATA: END OF MESS_TAB.

DATA: BEGIN OF LANGUS OCCURS 10,
        SPRAS LIKE SY-LANGU,
      END   OF LANGUS.

TABLES: DD04T,
               T706D,
               T706B,
               T706F,
        T702H, T706H,
               T706U,
        T702V, T706V,
        T702P, T702Q,                  "KZNZA
        T702E, T706E,                  "KZPMF
        T702G, T706G,                  "KZREA
        T702I, T706I,                  "ERKLA
        T702J, T706J,                  "ERGRU
        T702N, T706N,                  "MOREI
        T702O, T706O,                  "RGION
        T702R, T706R,                  "KZTKT
        T702W, T706W,                  "PKWKL
        T702X, T706X,                  "BEREI
        T702Y, T706Y,                  "PTZUO
        T000, T005T, T706T.

DATA: BEGIN OF I000 OCCURS 20.
        INCLUDE STRUCTURE T000.
DATA: END OF I000.

DATA: BEGIN OF 706D OCCURS 10.
        INCLUDE STRUCTURE T706D.
DATA: END OF 706D.

DATA: BEGIN OF 702P OCCURS 10.
        INCLUDE STRUCTURE T702P.
DATA: END OF 702P.
DATA: BEGIN OF 702Q OCCURS 10.
        INCLUDE STRUCTURE T702Q.
DATA: END OF 702Q.

DATA: BEGIN OF 702E OCCURS 10.
        INCLUDE STRUCTURE T702E.
DATA: END OF 702E.
DATA: BEGIN OF 706E OCCURS 10.
        INCLUDE STRUCTURE T706E.
DATA: END OF 706E.

DATA: BEGIN OF 702G OCCURS 10.
        INCLUDE STRUCTURE T702G.
DATA: END OF 702G.
DATA: BEGIN OF 706G OCCURS 10.
        INCLUDE STRUCTURE T706G.
DATA: END OF 706G.

DATA: BEGIN OF 702I OCCURS 10.
        INCLUDE STRUCTURE T702I.
DATA: END OF 702I.
DATA: BEGIN OF 706I OCCURS 10.
        INCLUDE STRUCTURE T706I.
DATA: END OF 706I.

DATA: BEGIN OF 702J OCCURS 10.
        INCLUDE STRUCTURE T702J.
DATA: END OF 702J.
DATA: BEGIN OF 706J OCCURS 10.
        INCLUDE STRUCTURE T706J.
DATA: END OF 706J.

DATA: BEGIN OF 702N OCCURS 10.
        INCLUDE STRUCTURE T702N.
DATA: END OF 702N.
DATA: BEGIN OF 706N OCCURS 10.
        INCLUDE STRUCTURE T706N.
DATA: END OF 706N.

DATA: BEGIN OF 702O OCCURS 10.
        INCLUDE STRUCTURE T702O.
DATA: END OF 702O.
DATA: BEGIN OF 706O OCCURS 10.
        INCLUDE STRUCTURE T706O.
DATA: END OF 706O.

DATA: BEGIN OF 702R OCCURS 10.
        INCLUDE STRUCTURE T702R.
DATA: END OF 702R.
DATA: BEGIN OF 706R OCCURS 10.
        INCLUDE STRUCTURE T706R.
DATA: END OF 706R.

DATA: BEGIN OF 702W OCCURS 10.
        INCLUDE STRUCTURE T702W.
DATA: END OF 702W.
DATA: BEGIN OF 706W OCCURS 10.
        INCLUDE STRUCTURE T706W.
DATA: END OF 706W.

DATA: BEGIN OF 702X OCCURS 10.
        INCLUDE STRUCTURE T702X.
DATA: END OF 702X.
DATA: BEGIN OF 706X OCCURS 10.
        INCLUDE STRUCTURE T706X.
DATA: END OF 706X.

DATA: BEGIN OF 702Y OCCURS 10.
        INCLUDE STRUCTURE T702Y.
DATA: END OF 702Y.
DATA: BEGIN OF 706Y OCCURS 10.
        INCLUDE STRUCTURE T706Y.
DATA: END OF 706Y.

DATA: BEGIN OF 702H OCCURS 100.
        INCLUDE STRUCTURE T702H.
DATA: END OF 702H.

DATA: BEGIN OF 702V OCCURS 100.
        INCLUDE STRUCTURE T702V.
DATA: END OF 702V.

REFRESH MESS_TAB.

SELECT * FROM T000 INTO TABLE I000.

LOOP AT I000 WHERE MANDT <> '000'.

  PERFORM APPEND_MESS_TAB
  USING   '3' ' '
          'E' '56' '666'
          'X'
          I000-MANDT SPACE SPACE SPACE.

  IF GET_TIME = 'X'.
    GET TIME. T0 = SY-UZEIT.
  ENDIF.

  T000 = I000.
  REFRESH: LANGUS,
           706D,
           702P, 702Q,
           702E, 702G, 702I, 702J, 702N,
           702O, 702R, 702W, 702X, 702Y,
           706E, 706G, 706I, 706J, 706N,
           706O, 706R, 706W, 706X, 706Y,
           702H, 702V.

************************************************************************
* Die im Mandanten benutzten Sprachschlüssel bestimmen
************************************************************************
  SELECT * FROM T706T CLIENT SPECIFIED
                      WHERE MANDT = T000-MANDT.
    MOVE-CORRESPONDING T706T TO LANGUS.
    COLLECT LANGUS.
  ENDSELECT.
  DESCRIBE TABLE LANGUS LINES LI.
  PERFORM DRUCK_T USING 'LANGUS' LI.

************************************************************************
* Die, die schon da sind
************************************************************************
  SELECT * FROM T706E CLIENT SPECIFIED
                      WHERE MANDT = T000-MANDT.
    MOVE-CORRESPONDING T706E TO 702E.
    APPEND 702E.
  ENDSELECT.
  PERFORM DRUCK_T USING 'T706E' SY-DBCNT.

  SELECT * FROM T706G CLIENT SPECIFIED
                      WHERE MANDT = T000-MANDT.
    MOVE-CORRESPONDING T706G TO 702G.
    APPEND 702G.
  ENDSELECT.
  PERFORM DRUCK_T USING 'T706G' SY-DBCNT.

  SELECT * FROM T706R CLIENT SPECIFIED
                      WHERE MANDT = T000-MANDT.
    MOVE-CORRESPONDING T706R TO 702R.
    APPEND 702R.
  ENDSELECT.
  PERFORM DRUCK_T USING 'T706R' SY-DBCNT.

************************************************************************
* Die, die noch nicht da sind
************************************************************************
* T706N, T706G, T706R, T706O, T706X, T706I, T706J aus T706B
  SELECT * FROM T706B CLIENT SPECIFIED WHERE MANDT = T000-MANDT.
      MOVE-CORRESPONDING T706B TO 702N. COLLECT 702N.
      MOVE-CORRESPONDING T706B TO 702G. COLLECT 702G.
      MOVE-CORRESPONDING T706B TO 702R. COLLECT 702R.
      702O-LAND1 = T706B-LNDGR.
      MOVE-CORRESPONDING T706B TO 702O. COLLECT 702O.
      MOVE-CORRESPONDING T706B TO 702X. COLLECT 702X.
      MOVE-CORRESPONDING T706B TO 702I. COLLECT 702I.
      MOVE-CORRESPONDING T706B TO 702J. COLLECT 702J.
    ENDSELECT.
  PERFORM DRUCK_T USING 'T706B' SY-DBCNT.

* T706N, T706G, T706R, T706O, T706X, T706E, T706W, T702Q aus T706F
  SELECT * FROM T706F CLIENT SPECIFIED WHERE MANDT = T000-MANDT.
    MOVE-CORRESPONDING T706F TO 702N. COLLECT 702N.
    MOVE-CORRESPONDING T706F TO 702G. COLLECT 702G.
    MOVE-CORRESPONDING T706F TO 702R. COLLECT 702R.
    MOVE-CORRESPONDING T706F TO 702O. COLLECT 702O.
    MOVE-CORRESPONDING T706F TO 702X. COLLECT 702X.
    MOVE-CORRESPONDING T706F TO 702E. COLLECT 702E.
    MOVE-CORRESPONDING T706F TO 702W. COLLECT 702W.
    MOVE-CORRESPONDING T706F TO 702P. COLLECT 702P.
  ENDSELECT.
  PERFORM DRUCK_T USING 'T706F' SY-DBCNT.

* T706N, T706G, T706R, T706O, T706X, T706I, T706J aus T706H
  SELECT * FROM T706H CLIENT SPECIFIED WHERE MANDT = T000-MANDT
                                       AND   MOREI <> '00'
                                       AND   MOREI <> '99'.
    MOVE-CORRESPONDING T706H TO 702N. COLLECT 702N.
    MOVE-CORRESPONDING T706H TO 702G. COLLECT 702G.
    MOVE-CORRESPONDING T706H TO 702R. COLLECT 702R.
    702O-LAND1 = T706H-LNDGR.
    MOVE-CORRESPONDING T706H TO 702O. COLLECT 702O.
    MOVE-CORRESPONDING T706H TO 702X. COLLECT 702X.
    MOVE-CORRESPONDING T706H TO 702I. COLLECT 702I.
    MOVE-CORRESPONDING T706H TO 702J. COLLECT 702J.
  ENDSELECT.
  PERFORM DRUCK_T USING 'T706H' SY-DBCNT.

* T706N, T706G, T706R, T706O, T706X, T706I, T706J aus T706U
  SELECT * FROM T706U CLIENT SPECIFIED WHERE MANDT = T000-MANDT.
    MOVE-CORRESPONDING T706U TO 702N. COLLECT 702N.
    MOVE-CORRESPONDING T706U TO 702G. COLLECT 702G.
    MOVE-CORRESPONDING T706U TO 702R. COLLECT 702R.
    702O-LAND1 = T706U-LNDGR.
    MOVE-CORRESPONDING T706U TO 702O. COLLECT 702O.
    MOVE-CORRESPONDING T706U TO 702X. COLLECT 702X.
    MOVE-CORRESPONDING T706U TO 702I. COLLECT 702I.
    MOVE-CORRESPONDING T706U TO 702J. COLLECT 702J.
  ENDSELECT.
  PERFORM DRUCK_T USING 'T706U' SY-DBCNT.

* T706N, T706G, T706R, T706O, T706X, T706I, T706J aus T706V
  SELECT * FROM T706V CLIENT SPECIFIED WHERE MANDT = T000-MANDT AND
                                       MOREI <> '99'.
    MOVE-CORRESPONDING T706V TO 702N. COLLECT 702N.
    MOVE-CORRESPONDING T706V TO 702G. COLLECT 702G.
    MOVE-CORRESPONDING T706V TO 702R. COLLECT 702R.
    702O-LAND1 = T706V-LNDGR.
    MOVE-CORRESPONDING T706V TO 702O. COLLECT 702O.
    MOVE-CORRESPONDING T706V TO 702X. COLLECT 702X.
    MOVE-CORRESPONDING T706V TO 702I. COLLECT 702I.
    MOVE-CORRESPONDING T706V TO 702J. COLLECT 702J.
  ENDSELECT.
  PERFORM DRUCK_T USING 'T706V' SY-DBCNT.

************************************************************************
* Jetzt kommen die schönen Füllroutinen
************************************************************************
* T702E, T706E füllen
  LOOP AT LANGUS.
    706E-SPRAS = LANGUS-SPRAS.
    PERFORM REDD04T USING 706E-SPRAS 'KZPMF' 706E-FZTXT.
    LOOP AT 702E.
      MOVE-CORRESPONDING 702E TO 706E.
      706E-FZTXT+21(4) = 706E-KZPMF.
      PERFORM DRUCK_E USING 702E.
      PERFORM DRUCK_E USING 706E.
      APPEND 706E.
    ENDLOOP.
  ENDLOOP.

  DESCRIBE TABLE 702E LINES LI.
  PERFORM DRUCK_T USING '702E' LI.
  DESCRIBE TABLE 706E LINES LI.
  PERFORM DRUCK_T USING '706E' LI.

  IF MODIF = 'X'.
    INSERT T702E CLIENT SPECIFIED FROM TABLE 702E
                 ACCEPTING DUPLICATE KEYS.
    PERFORM DRUCK_T USING 'T702E' SY-DBCNT.

    INSERT T706E CLIENT SPECIFIED FROM TABLE 706E
                 ACCEPTING DUPLICATE KEYS.
    PERFORM DRUCK_T USING 'T706E' SY-DBCNT.
  ENDIF.

* T702G, T706G füllen
  LOOP AT LANGUS.
    706G-SPRAS = LANGUS-SPRAS.
    PERFORM REDD04T USING 706G-SPRAS 'KZREA' 706G-RETXT.
    LOOP AT 702G.
      MOVE-CORRESPONDING 702G TO 706G.
      706G-RETXT+21(4) = 706G-KZREA.
      PERFORM DRUCK_E USING 702G.
      PERFORM DRUCK_E USING 706G.
      APPEND 706G.
    ENDLOOP.
  ENDLOOP.

  DESCRIBE TABLE 702G LINES LI.
  PERFORM DRUCK_T USING '702G' LI.
  DESCRIBE TABLE 706G LINES LI.
  PERFORM DRUCK_T USING '706G' LI.

  IF MODIF = 'X'.
    INSERT T702G CLIENT SPECIFIED FROM TABLE 702G
                 ACCEPTING DUPLICATE KEYS.
    PERFORM DRUCK_T USING 'T702G' SY-DBCNT.

    INSERT T706G CLIENT SPECIFIED FROM TABLE 706G
                 ACCEPTING DUPLICATE KEYS.
    PERFORM DRUCK_T USING 'T706G' SY-DBCNT.
  ENDIF.

* T702R, T706R füllen
  LOOP AT LANGUS.
    706R-SPRAS = LANGUS-SPRAS.
    PERFORM REDD04T USING 706R-SPRAS 'KZTKT' 706R-TKTXT.
    LOOP AT 702R.
      MOVE-CORRESPONDING 702R TO 706R.
      706R-TKTXT+21(4) = 706R-KZTKT.
      PERFORM DRUCK_E USING 702R.
      PERFORM DRUCK_E USING 706R.
      APPEND 706R.
    ENDLOOP.
  ENDLOOP.

  DESCRIBE TABLE 702R LINES LI.
  PERFORM DRUCK_T USING '702R' LI.
  DESCRIBE TABLE 706R LINES LI.
  PERFORM DRUCK_T USING '706R' LI.

  IF MODIF = 'X'.
    INSERT T702R CLIENT SPECIFIED FROM TABLE 702R
                 ACCEPTING DUPLICATE KEYS.
    PERFORM DRUCK_T USING 'T702R' SY-DBCNT.

    INSERT T706R CLIENT SPECIFIED FROM TABLE 706R
                 ACCEPTING DUPLICATE KEYS.
    PERFORM DRUCK_T USING 'T706R' SY-DBCNT.
  ENDIF.

* T702P, T702Q füllen
  LOOP AT LANGUS.
    702Q-SPRAS = LANGUS-SPRAS.
    PERFORM REDD04T USING 702Q-SPRAS 'KZNZA' 702Q-TEXT25.
    LOOP AT 702P.
      MOVE-CORRESPONDING 702P TO 702Q.
      702Q-TEXT25+21(4) = 702Q-KZNZA.
      PERFORM DRUCK_E USING 702P.
      PERFORM DRUCK_E USING 702Q.
      APPEND 702Q.
    ENDLOOP.
  ENDLOOP.

  DESCRIBE TABLE 702P LINES LI.
  PERFORM DRUCK_T USING '702P' LI.
  DESCRIBE TABLE 702Q LINES LI.
  PERFORM DRUCK_T USING '702Q' LI.

  IF MODIF = 'X'.
    INSERT T702P CLIENT SPECIFIED FROM TABLE 702P
                 ACCEPTING DUPLICATE KEYS.
    PERFORM DRUCK_T USING 'T702P' SY-DBCNT.

    INSERT T702Q CLIENT SPECIFIED FROM TABLE 702Q
                 ACCEPTING DUPLICATE KEYS.
    PERFORM DRUCK_T USING 'T702Q' SY-DBCNT.
  ENDIF.

* T702I, T706I füllen
  LOOP AT LANGUS.
    706I-SPRAS = LANGUS-SPRAS.
    PERFORM REDD04T USING 706I-SPRAS 'ERKLA' 706I-TEXT25.
    LOOP AT 702I.
      MOVE-CORRESPONDING 702I TO 706I.
      706I-TEXT25+21(4) = 706I-ERKLA.
      PERFORM DRUCK_E USING 702I.
      PERFORM DRUCK_E USING 706I.
      APPEND 706I.
    ENDLOOP.
  ENDLOOP.

  DESCRIBE TABLE 702I LINES LI.
  PERFORM DRUCK_T USING '702I' LI.
  DESCRIBE TABLE 706I LINES LI.
  PERFORM DRUCK_T USING '706I' LI.

  IF MODIF = 'X'.
    INSERT T702I CLIENT SPECIFIED FROM TABLE 702I
                 ACCEPTING DUPLICATE KEYS.
    PERFORM DRUCK_T USING 'T702I' SY-DBCNT.

    INSERT T706I CLIENT SPECIFIED FROM TABLE 706I
                 ACCEPTING DUPLICATE KEYS.
    PERFORM DRUCK_T USING 'T706I' SY-DBCNT.
  ENDIF.

* T702J, T706J füllen
  LOOP AT LANGUS.
    706J-SPRAS = LANGUS-SPRAS.
    PERFORM REDD04T USING 706J-SPRAS 'ERGRU' 706J-TEXT25.
    LOOP AT 702J.
      MOVE-CORRESPONDING 702J TO 706J.
      706J-TEXT25+21(4) = 706J-ERGRU.
      PERFORM DRUCK_E USING 702J.
      PERFORM DRUCK_E USING 706J.
      APPEND 706J.
    ENDLOOP.
  ENDLOOP.

  DESCRIBE TABLE 702J LINES LI.
  PERFORM DRUCK_T USING '702J' LI.
  DESCRIBE TABLE 706J LINES LI.
  PERFORM DRUCK_T USING '706J' LI.

  IF MODIF = 'X'.
    INSERT T702J CLIENT SPECIFIED FROM TABLE 702J
                 ACCEPTING DUPLICATE KEYS.
    PERFORM DRUCK_T USING 'T702J' SY-DBCNT.

    INSERT T706J CLIENT SPECIFIED FROM TABLE 706J
                 ACCEPTING DUPLICATE KEYS.
    PERFORM DRUCK_T USING 'T706J' SY-DBCNT.
  ENDIF.

* T702N, T706N füllen,
  LOOP AT LANGUS.
    706N-SPRAS = LANGUS-SPRAS.
    PERFORM REDD04T USING 706N-SPRAS 'MOREI' 706N-TEXT25.
    LOOP AT 702N.
      MOVE-CORRESPONDING 702N TO 706N.
      706N-TEXT25+21(4) = 706N-MOREI.
      PERFORM DRUCK_E USING 702N.
      PERFORM DRUCK_E USING 706N.
      APPEND 706N.
    ENDLOOP.
  ENDLOOP.

  DESCRIBE TABLE 702N LINES LI.
  PERFORM DRUCK_T USING '702N' LI.
  DESCRIBE TABLE 706N LINES LI.
  PERFORM DRUCK_T USING '706N' LI.

  IF MODIF = 'X'.
    INSERT T702N CLIENT SPECIFIED FROM TABLE 702N
                 ACCEPTING DUPLICATE KEYS.
    PERFORM DRUCK_T USING 'T702N' SY-DBCNT.

    INSERT T706N CLIENT SPECIFIED FROM TABLE 706N
                 ACCEPTING DUPLICATE KEYS.
    PERFORM DRUCK_T USING 'T706N' SY-DBCNT.
  ENDIF.

* T702Y, T706Y füllen
  LOOP AT LANGUS.
    706Y-SPRAS = LANGUS-SPRAS.
    PERFORM REDD04T USING 706Y-SPRAS 'PTZUO' 706Y-TEXT25.
    LOOP AT 702N.
      MOVE-CORRESPONDING 702N TO 702Y. MOVE-CORRESPONDING 702N TO 706Y.
      706Y-TEXT25+21(4) = 706Y-PTZUO.
      PERFORM DRUCK_E USING 702Y.
      PERFORM DRUCK_E USING 706Y.
      APPEND 702Y. APPEND 706Y.
    ENDLOOP.
  ENDLOOP.

  DESCRIBE TABLE 702Y LINES LI.
  PERFORM DRUCK_T USING '702Y' LI.
  DESCRIBE TABLE 706Y LINES LI.
  PERFORM DRUCK_T USING '706Y' LI.

  IF MODIF = 'X'.
    INSERT T702Y CLIENT SPECIFIED FROM TABLE 702Y
                 ACCEPTING DUPLICATE KEYS.
    PERFORM DRUCK_T USING 'T702Y' SY-DBCNT.

    INSERT T706Y CLIENT SPECIFIED FROM TABLE 706Y
                 ACCEPTING DUPLICATE KEYS.
    PERFORM DRUCK_T USING 'T706Y' SY-DBCNT.

  ENDIF.

* T702O, T706O füllen
  LOOP AT LANGUS.
    706O-SPRAS = LANGUS-SPRAS.
    LOOP AT 702O.
      MOVE-CORRESPONDING 702O TO 706O.
      PERFORM RE005T USING 706O-LAND1 706O-TEXT25.
      IF 706O-TEXT25 IS INITIAL.
        PERFORM REDD04T USING 706O-SPRAS 'LNDGR' 706O-TEXT25.
        706O-TEXT25+21(4) = 706O-LAND1.
      ENDIF.
      PERFORM DRUCK_E USING 702O.
      PERFORM DRUCK_E USING 706O.
      APPEND 706O.
    ENDLOOP.
  ENDLOOP.

  DESCRIBE TABLE 702O LINES LI.
  PERFORM DRUCK_T USING '702O' LI.
  DESCRIBE TABLE 706O LINES LI.
  PERFORM DRUCK_T USING '706O' LI.

  IF MODIF = 'X'.
    INSERT T702O CLIENT SPECIFIED FROM TABLE 702O
                 ACCEPTING DUPLICATE KEYS.
    PERFORM DRUCK_T USING 'T702O' SY-DBCNT.

    INSERT T706O CLIENT SPECIFIED FROM TABLE 706O
                 ACCEPTING DUPLICATE KEYS.
    PERFORM DRUCK_T USING 'T706O' SY-DBCNT.
  ENDIF.

* T702W, T706W füllen
  LOOP AT LANGUS.
    706W-SPRAS = LANGUS-SPRAS.
    PERFORM REDD04T USING 706W-SPRAS 'PKWKL' 706W-TEXT25.
    LOOP AT 702W.
      MOVE-CORRESPONDING 702W TO 706W.
      706W-TEXT25+21(4) = 706W-PKWKL.
      PERFORM DRUCK_E USING 702W.
      PERFORM DRUCK_E USING 706W.
      APPEND 706W.
    ENDLOOP.
  ENDLOOP.

  DESCRIBE TABLE 702W LINES LI.
  PERFORM DRUCK_T USING '702W' LI.
  DESCRIBE TABLE 706W LINES LI.
  PERFORM DRUCK_T USING '706W' LI.

  IF MODIF = 'X'.
    INSERT T702W CLIENT SPECIFIED FROM TABLE 702W
                 ACCEPTING DUPLICATE KEYS.
    PERFORM DRUCK_T USING 'T702W' SY-DBCNT.

    INSERT T706W CLIENT SPECIFIED FROM TABLE 706W
                 ACCEPTING DUPLICATE KEYS.
    PERFORM DRUCK_T USING 'T706W' SY-DBCNT.
  ENDIF.

* T702X, T706X füllen
  LOOP AT LANGUS.
    706X-SPRAS = LANGUS-SPRAS.
    PERFORM REDD04T USING 706X-SPRAS 'BEREI' 706X-TEXT25.
    LOOP AT 702X.
      MOVE-CORRESPONDING 702X TO 706X.
      706X-TEXT25+21(4) = 706X-BEREI.
      PERFORM DRUCK_E USING 702X.
      PERFORM DRUCK_E USING 706X.
      APPEND 706X.
    ENDLOOP.
  ENDLOOP.

  DESCRIBE TABLE 702X LINES LI.
  PERFORM DRUCK_T USING '702X' LI.
  DESCRIBE TABLE 706X LINES LI.
  PERFORM DRUCK_T USING '706X' LI.

  IF MODIF = 'X'.
    INSERT T702X CLIENT SPECIFIED FROM TABLE 702X
                 ACCEPTING DUPLICATE KEYS.
    PERFORM DRUCK_T USING 'T702X' SY-DBCNT.

    INSERT T706X CLIENT SPECIFIED FROM TABLE 706X
                 ACCEPTING DUPLICATE KEYS.
    PERFORM DRUCK_T USING 'T706X' SY-DBCNT.
  ENDIF.

* Füllen der Kürzungsregeln
* T702H füllen
  SELECT * FROM T706H CLIENT SPECIFIED WHERE MANDT = T000-MANDT
                                       AND   MOREI = '99'.
    PERFORM DRUCK_E USING T706H.
    MOVE-CORRESPONDING T706H TO 702H.
    702H-MOREI = T706H-ERGRU.
    702H-ERKLA = '0'.
    702H-ERGRU = '00'.
    IF 702H-LNDGR = 'DOM'.
      702H-LNDGR = 'AT '.
    ENDIF.
    IF 702H-LNDGR = 'ABR'.
      702H-LNDGR = '   '.
    ENDIF.
    702H-NUMFZ = T706H-BETFZ.
    702H-NUMFA = T706H-BETFA.
    702H-DENTR = T706H-BETKU.
    APPEND 702H.
  ENDSELECT.

  DESCRIBE TABLE 702H LINES LI.
  PERFORM DRUCK_T USING '702H' LI.

  IF MODIF = 'X'.
    INSERT T702H CLIENT SPECIFIED FROM TABLE 702H
                 ACCEPTING DUPLICATE KEYS.
    PERFORM DRUCK_T USING 'T702H' SY-DBCNT.
  ENDIF.

* T702V füllen
  SELECT * FROM T706V CLIENT SPECIFIED WHERE MANDT = T000-MANDT
                                       AND   MOREI = '99'.
    PERFORM DRUCK_E USING T706V.
    MOVE-CORRESPONDING T706V TO 702V.
    702V-MOREI = T706V-ERGRU.
    702V-ERKLA = '0'.
    702V-ERGRU = '00'.
    IF 702V-LNDGR = 'DOM'.
      702V-LNDGR = 'AT '.
    ENDIF.
    IF 702V-LNDGR = 'ABR'.
      702V-LNDGR = '   '.
    ENDIF.
    702V-NUMFZ = T706V-BETFZ.
    702V-NUMFA = T706V-BETFA.
    702V-DENTR = T706V-BETKU.
    APPEND 702V.
  ENDSELECT.

  DESCRIBE TABLE 702V LINES LI.
  PERFORM DRUCK_T USING '702V' LI.

  IF MODIF = 'X'.
    INSERT T702V CLIENT SPECIFIED FROM TABLE 702V
                 ACCEPTING DUPLICATE KEYS.
    PERFORM DRUCK_T USING 'T702V' SY-DBCNT.
  ENDIF.

* T706D Initialwerte füllen
  SELECT * FROM T706D CLIENT SPECIFIED
                      INTO 706D
                      WHERE MANDT = T000-MANDT.
    706D-MOLGA = 706D-MOREI.
    CASE 706D-MOLGA.
      WHEN '01'. 706D-LAND1 = 'DE '.
      WHEN '02'. 706D-LAND1 = 'CH '.
      WHEN '03'. 706D-LAND1 = 'AT '.
      WHEN '04'. 706D-LAND1 = 'ES '.
      WHEN '05'. 706D-LAND1 = 'NL '.
      WHEN '06'. 706D-LAND1 = 'FR '.
      WHEN '07'. 706D-LAND1 = 'CA '.
      WHEN '08'. 706D-LAND1 = 'GB '.
      WHEN '09'. 706D-LAND1 = 'DK '.
      WHEN '10'. 706D-LAND1 = 'US '.
      WHEN '12'. 706D-LAND1 = 'BE '.
      WHEN '15'. 706D-LAND1 = 'IT '.
      WHEN '20'. 706D-LAND1 = 'NO '.
      WHEN '22'. 706D-LAND1 = 'JP '.
      WHEN '23'. 706D-LAND1 = 'SE '.
      WHEN OTHERS.
    ENDCASE.
    706D-KURST = 'M   '.
    APPEND 706D.
  ENDSELECT.

  DESCRIBE TABLE 706D LINES LI.
  PERFORM DRUCK_T USING '706D' LI.

  IF MODIF = 'X'.
    MODIFY T706D CLIENT SPECIFIED FROM TABLE 706D.
    PERFORM DRUCK_T USING 'T706D' SY-DBCNT.
  ENDIF.

  PERFORM DRUCK_ZEIT.

ENDLOOP.

CALL FUNCTION 'APPEND_PROTOCOL'
     EXPORTING
          ACCEPT_NOT_INIT      = 'X'
     TABLES
          XMSG                 = MESS_TAB
     EXCEPTIONS
*         table_empty          = 1
          PROT_NOT_INITIALIZED = 4.

*---------------------------------------------------------------------*
*       FORM RE005T                                                   *
*---------------------------------------------------------------------*
FORM  RE005T
USING VALUE(LAND1)
      LANDX.

  SELECT SINGLE * FROM T005T CLIENT SPECIFIED
                             WHERE MANDT = T000-MANDT
                             AND   SPRAS = SY-LANGU
                             AND   LAND1 = LAND1.
  IF SY-SUBRC = 0.
    LANDX = T005T-LANDX.
  ELSE.
    CLEAR LANDX.
  ENDIF.

ENDFORM.

*---------------------------------------------------------------------*
*     FORM DRUCK_E                                                    *
*---------------------------------------------------------------------*
FORM DRUCK_E USING VALUE(TABL).
  IF PRINT_E = 'X'.
    WRITE: / TABL.
  ENDIF.
ENDFORM.

*---------------------------------------------------------------------*
*     FORM DRUCK_T                                                    *
*---------------------------------------------------------------------*
FORM DRUCK_T USING VALUE(TABL) VALUE(ZAEHLER).
  IF PRINT_T = 'X'.
    PERFORM APPEND_MESS_TAB
    USING   '4' ' '
            'E' '56' '667'
            ' '
            TABL ZAEHLER SPACE SPACE.
  ENDIF.
ENDFORM.

*---------------------------------------------------------------------*
*       FORM DRUCK_ZEIT                                               *
*---------------------------------------------------------------------*
FORM DRUCK_ZEIT.
  DATA: TIME_FR(8),
        TIME_TO(8).
  IF GET_TIME = 'X'.
    GET TIME. T1 = SY-UZEIT.
    T2 = T1 - T0.
    WRITE T0 USING EDIT MASK '__:__:__' TO TIME_FR.
    WRITE T1 USING EDIT MASK '__:__:__' TO TIME_TO.

    PERFORM APPEND_MESS_TAB
    USING   '4' ' '
            'E' '56' '668'
            ' '
            T2 TIME_FR TIME_TO SPACE.

  ENDIF.
ENDFORM.

*---------------------------------------------------------------------*
*       FORM APPEND_MESS_TAB                                          *
*---------------------------------------------------------------------*
FORM  APPEND_MESS_TAB
USING VALUE(LEVEL)
      VALUE(SEVERITY)
      VALUE(LANGU)
      VALUE(AG)
      VALUE(MSGNR)
      VALUE(NEWOBJ)
      VALUE(VAR1)
      VALUE(VAR2)
      VALUE(VAR3)
      VALUE(VAR4).

  CLEAR MESS_TAB.
  MESS_TAB-LEVEL    = LEVEL.
  MESS_TAB-SEVERITY = SEVERITY.
  MESS_TAB-LANGU    = LANGU.
  MESS_TAB-AG       = AG.
  MESS_TAB-MSGNR    = MSGNR.
  MESS_TAB-NEWOBJ   = NEWOBJ.
  MESS_TAB-VAR1     = VAR1.
  MESS_TAB-VAR2     = VAR2.
  MESS_TAB-VAR3     = VAR3.
  MESS_TAB-VAR4     = VAR4.
  APPEND MESS_TAB.

ENDFORM.

*---------------------------------------------------------------------*
*       FORM REDD04T                                                  *
*---------------------------------------------------------------------*
FORM  REDD04T
USING VALUE(LANGU) VALUE(ROLLNAME)
      SCRTEXT_L.

  IF DD04T-ROLLNAME   = ROLLNAME AND
     DD04T-DDLANGUAGE = LANGU AND
     DD04T-AS4LOCAL   = 'A'.
    SCRTEXT_L = DD04T-SCRTEXT_L.
  ELSE.
    CLEAR SCRTEXT_L.
    SELECT * FROM DD04T WHERE ROLLNAME   = ROLLNAME
                        AND   DDLANGUAGE = LANGU
                        AND   AS4LOCAL   = 'A'.
      SCRTEXT_L = DD04T-SCRTEXT_L.
      EXIT.
    ENDSELECT.
    IF SY-SUBRC <> 0.
      SELECT * FROM DD04T WHERE ROLLNAME   = ROLLNAME
                          AND   DDLANGUAGE = 'E'
                          AND   AS4LOCAL   = 'A'.
        SCRTEXT_L = DD04T-SCRTEXT_L.
        EXIT.
      ENDSELECT.
    ENDIF.
  ENDIF.
ENDFORM.