CLASS YCL_SAP_TO_WORD DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

PUBLIC SECTION.

  DATA MV_RAISE_MESSAGE TYPE XFELD .
  DATA MO_CONTROL TYPE REF TO I_OI_CONTAINER_CONTROL .
  DATA MO_DOCUMENT TYPE REF TO I_OI_DOCUMENT_PROXY .
  DATA MO_ERROR TYPE REF TO I_OI_ERROR .
  DATA MO_LINK_SERVER TYPE REF TO I_OI_LINK_SERVER .
  DATA MO_WP TYPE REF TO I_OI_WORD_PROCESSOR_DOCUMENT .
  DATA MO_MAIL_MERGE TYPE REF TO I_OI_MAIL_MERGE .
  DATA MO_CONTAINER TYPE REF TO CL_GUI_CUSTOM_CONTAINER .

  CLASS-METHODS GET_URL
    IMPORTING
      !IV_CLASSNAME TYPE BDS_CLSNAM
      !IV_CLASSTYPE TYPE BDS_CLSTYP
      !IV_OBJKEY TYPE BDS_TYPEID
      !IV_FILENAME TYPE BDS_COMPID
    EXPORTING
      !ET_COMP TYPE RSZW_T_BAPICOMPON
      !ET_SIGNAT TYPE RSZW_T_BAPISIGNAT
      !ET_URI TYPE SBDST_URI
    RETURNING
      VALUE(RV_URI) TYPE BDS_URI .
  METHODS PREPARE_WORD
    IMPORTING
      !IV_CONTAINER TYPE REF TO CL_GUI_CONTAINER OPTIONAL .
  METHODS OPEN_DOCUMENT
    IMPORTING
      !I_URL TYPE C
      !I_INPLACE TYPE C .
  METHODS REOPEN_DOCUMENT
    IMPORTING
      !I_INPLACE TYPE C .
  METHODS INSERT_TABLE
    IMPORTING
      !IT_DATA_TABLE TYPE TABLE
      !IT_INFO_TABLE TYPE SOI_COLS_TABLE
      !I_LOWERBOUND TYPE I
      !I_UPPERBOUND TYPE I
      !I_DOCTABLE_NUMBER TYPE I
      !I_CLEAROPTION TYPE I
      !I_STARTROW TYPE I
      !I_VARSIZE TYPE C .
  METHODS MERGE
    IMPORTING
      !I_MERGE_ONE TYPE BOOLE_D DEFAULT 'X'
      !I_DDIC_NAME TYPE TABNAME OPTIONAL
    CHANGING
      !CT_DATA_TABLE TYPE TABLE
      !CT_FIELD_TABLE TYPE SOI_FIELDS_TABLE OPTIONAL .
  METHODS SAVE
    IMPORTING
      !I_FILENAME TYPE C .
  METHODS GET_AND_START_LINK_SERVER .
  METHODS CLOSE_DOCUMENT .
  METHODS RELEASE_DOCUMENT .
  METHODS CLEAR_TABLE
    IMPORTING
      !I_DOCTABLE_NUMBER TYPE I .
  METHODS CUT_SELECTION .
  METHODS INSTALL_TEMPLATE
    IMPORTING
      !IV_URI TYPE BDS_URI
      !IV_TEMPLATE_NAME TYPE C .
  METHODS SET_TEMPLATE
    IMPORTING
      !IV_DOTM TYPE C
      !IV_ATTACH_STYLE TYPE C DEFAULT ' ' .
  METHODS REMOVE_TEMPLATE
    IMPORTING
      !IV_TEMPLATE_NAME TYPE C .
  METHODS EXECUTE_MACRO
    IMPORTING
      !IV_MACRO_NAME TYPE C
      !IV_PARAM1 TYPE ANY DEFAULT '' .
  METHODS SAVE_IN_BDS
    IMPORTING
      !I_URL TYPE C
      !IV_CLOSE TYPE BOOLEAN DEFAULT ABAP_FALSE .
  METHODS GET_MERGEFIELDS
    RETURNING
      VALUE(RT_MERGEFIELDS) TYPE SOI_FIELDS_NAME_TABLE .