*&---------------------------------------------------------------------*
*&  Include           YFI_BANK_RECONCILIATION_SEL
*&---------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK B01 WITH FRAME TITLE TEXT-B01.
PARAMETERS P_BUKRS TYPE LFB1-BUKRS OBLIGATORY.
SELECT-OPTIONS S_HKONT FOR GS_BSIS-HKONT.
SELECTION-SCREEN END OF BLOCK B01.
SELECTION-SCREEN BEGIN OF BLOCK B02 WITH FRAME TITLE TEXT-B02.
PARAMETERS P_DATE_Z TYPE DATUM OBLIGATORY DEFAULT SY-DATUM.
PARAMETERS P_DATE_O TYPE DATUM OBLIGATORY DEFAULT SY-DATUM.
SELECTION-SCREEN END OF BLOCK B02.
SELECTION-SCREEN BEGIN OF BLOCK B03 WITH FRAME TITLE TEXT-B03.
PARAMETERS P_DETAIL RADIOBUTTON GROUP R001 DEFAULT 'X'.
PARAMETERS P_DASH RADIOBUTTON GROUP R001.
SELECTION-SCREEN END OF BLOCK B03.

INITIALIZATION.
  GET PARAMETER ID 'BUK' FIELD P_BUKRS.
  "Set Bank account range
  S_HKONT[] = YCL_FI_BANK_RECONCILIATION_BL=>INITIALIZE_HKONT( ).
  "Set last day of previous month for key date for Z* document types
  P_DATE_Z = SY-DATUM.
  P_DATE_Z+6(2) = '01'.
  P_DATE_Z = P_DATE_Z - 1.
  "Set last day of two month ago
  P_DATE_O = P_DATE_Z.
  P_DATE_O+6(2) = '01'.
  P_DATE_O = P_DATE_O - 1.
  DO.
    CALL FUNCTION 'DATE_CHECK_PLAUSIBILITY'
      EXPORTING
        DATE                      = P_DATE_O
      EXCEPTIONS
        PLAUSIBILITY_CHECK_FAILED = 1
        OTHERS                    = 2.
    IF SY-SUBRC <> 0.
      P_DATE_O+6(2) = P_DATE_O+6(2) - 1.
    ELSE.
      EXIT.
    ENDIF.
  ENDDO.

AT SELECTION-SCREEN ON BLOCK B02.
  IF P_DATE_O > P_DATE_Z.
    MESSAGE E007(YFI1).
  ENDIF.