*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZFI_PAYREL_EMAILU01.
                    "TABLEFRAME_ZFI_PAYREL_EMAIL
INCLUDE LZFI_PAYREL_EMAILU02.
                    "TABLEPROC_ZFI_PAYREL_EMAIL