* ==== CLASS POOL ZCL_IM_HRFPM_ENHLG_GRP_AVC ====
CLASS-POOL .
*"* class pool for class ZCL_IM_HRFPM_ENHLG_GRP_AVC

*"* local type definitions
INCLUDE ZCL_IM_HRFPM_ENHLG_GRP_AVC====CCDEF.

*"* class ZCL_IM_HRFPM_ENHLG_GRP_AVC definition
*"* public declarations
  INCLUDE ZCL_IM_HRFPM_ENHLG_GRP_AVC====CU.
*"* protected declarations
  INCLUDE ZCL_IM_HRFPM_ENHLG_GRP_AVC====CO.
*"* private declarations
  INCLUDE ZCL_IM_HRFPM_ENHLG_GRP_AVC====CI.
ENDCLASS. "ZCL_IM_HRFPM_ENHLG_GRP_AVC definition

*"* macro definitions
INCLUDE ZCL_IM_HRFPM_ENHLG_GRP_AVC====CCMAC.
*"* local class implementation
INCLUDE ZCL_IM_HRFPM_ENHLG_GRP_AVC====CCIMP.

CLASS ZCL_IM_HRFPM_ENHLG_GRP_AVC IMPLEMENTATION.
*"* method's implementations
  INCLUDE METHODS.
ENDCLASS. "ZCL_IM_HRFPM_ENHLG_GRP_AVC implementation


* ---- ZCL_IM_HRFPM_ENHLG_GRP_AVC====CI ----
PRIVATE SECTION.
*"* private components of class ZCL_HRFPM_IM_ENHLOG_GRP_STD
*"* do not include other source files here!!!

* ---- ZCL_IM_HRFPM_ENHLG_GRP_AVC====CM001 ----
METHOD FILL_AVC_AMOUNT_FIELDS.
  DATA LS_AGGREGATE TYPE TYS_AGGREGATE_RETURN.
  DATA LS_AVC_AMOUNTS TYPE HRFPM_APPL_LOG_AVC_AMOUNTS .

  IF DET_AGGREGATE_FROM_DATA( CD_OUTPUT_LINE )-NO_AGGREGEE = ABAP_FALSE.
    MOVE-CORRESPONDING CD_OUTPUT_LINE TO LS_AVC_AMOUNTS.

    IF CHECK_IF_USABLE( CD_OUTPUT_LINE ) = ABAP_TRUE.
      LS_AVC_AMOUNTS-MISSING_AMOUNT = 0.
    ELSE.

      LS_AGGREGATE = DET_AGGREGATE_FROM_DATA(
         IV_LINE = CD_OUTPUT_LINE
         IV_REGISTER = ABAP_TRUE
         "because we need to update the aggregate
         IV_AS_REFERENCE = ABAP_TRUE  ).

      MOVE-CORRESPONDING
        FIGURE_OUT_MISSING_AMOUNT(
            IV_AGGREGATE = LS_AGGREGATE
            IV_AMOUNTS   = LS_AVC_AMOUNTS ) TO LS_AVC_AMOUNTS.

      "subtotals with respect to carrier
      "(perhaps this is needed later)
      LS_AGGREGATE-AGGREGATE->AMOUNTS->MISSING_AMOUNT =
          LS_AGGREGATE-AGGREGATE->AMOUNTS->MISSING_AMOUNT
            + LS_AVC_AMOUNTS-MISSING_AMOUNT.

*      ls_aggregate-aggregate->amounts->avail_bdgt_hist =
*         "ls_aggregate-aggregate->amounts->avail_bdgt_hist +
*           ls_avc_amounts-avail_bdgt_hist.

      LS_AGGREGATE-AGGREGATE->AMOUNTS->REQUESTED_AMOUNT =
        LS_AGGREGATE-AGGREGATE->AMOUNTS->REQUESTED_AMOUNT
          + LS_AVC_AMOUNTS-REQUESTED_AMOUNT.

      LS_AGGREGATE-AGGREGATE->AMOUNTS->POSTED_AMOUNT =
         LS_AGGREGATE-AGGREGATE->AMOUNTS->POSTED_AMOUNT
            + LS_AVC_AMOUNTS-POSTED_AMOUNT.

    ENDIF.
    MOVE-CORRESPONDING LS_AVC_AMOUNTS TO CD_OUTPUT_LINE.
  ENDIF.

ENDMETHOD.

* ---- ZCL_IM_HRFPM_ENHLG_GRP_AVC====CM002 ----
  METHOD ZIF_HRFPM_LG_AVC_AGGREG_HNDL~DET_AGGREGATE_FROM_DATA.

    FIELD-SYMBOLS <AGGREGATE_KEY> TYPE ANY .
    FIELD-SYMBOLS <AGGREGATE> LIKE LINE OF MT_AGGREGATE.
    FIELD-SYMBOLS <ID2KEY> LIKE LINE OF MT_AGGREGATE_ID2KEY.
    DATA LRD_AGGREGATE LIKE REF TO <AGGREGATE>.
    DATA LS_ID2KEY LIKE <ID2KEY>.


    CREATE DATA RS_AGGREGATE-AGGREGATE.

    CREATE DATA RS_AGGREGATE-AGGREGATE->AGGREGATE_ID-AGGREGATE_DATA
       TYPE HANDLE MO_AGGREG_TYPE.
    ASSIGN RS_AGGREGATE-AGGREGATE->AGGREGATE_ID-AGGREGATE_DATA->* TO <AGGREGATE_KEY>.

    RS_AGGREGATE-AGGREGATE->AGGREGATE_ID-AGGREGATE_DATA =
        FILL_AGGREGATE_KEY( IV_LINE ).

    ASSIGN RS_AGGREGATE-AGGREGATE->AGGREGATE_ID-AGGREGATE_DATA->* TO <AGGREGATE_KEY>.

    IF CHECK_IF_AGGREGEE( <AGGREGATE_KEY> ) = ABAP_FALSE .
      RS_AGGREGATE-NO_AGGREGEE = ABAP_TRUE.
    ELSE.
      IF IV_REGISTER = ABAP_TRUE.
        CREATE DATA LS_ID2KEY-AGGREGATE_DATA TYPE HANDLE MO_AGGREG_TYPE.
        LS_ID2KEY-AGGREGATE_DATA =
           RS_AGGREGATE-AGGREGATE->AGGREGATE_ID-AGGREGATE_DATA.
        "(1)register
        LS_ID2KEY-AGGREGATE_VAL = <AGGREGATE_KEY>.
        READ TABLE MT_AGGREGATE_ID2KEY ASSIGNING <ID2KEY>
          WITH KEY VALUE COMPONENTS AGGREGATE_VAL = LS_ID2KEY-AGGREGATE_VAL.

        IF SY-SUBRC <> 0.
          RS_AGGREGATE-IS_NEW = ABAP_TRUE.
          "CREATE DATA ls_id2key-aggregate_data TYPE HANDLE mo_aggreg_type.
          "ASSIGN ls_id2key-aggregate_data->* TO <aggregate_key2>.
          "<aggregate_key2> = <aggreg_val>.
          "ls_id2key-aggregate_val = lv_aggreg_val.
          LS_ID2KEY-ID = MV_CURRENT_AGGREG_ID = MV_CURRENT_AGGREG_ID + 1.
          INSERT LS_ID2KEY INTO TABLE MT_AGGREGATE_ID2KEY ASSIGNING <ID2KEY>.
        ENDIF.

        RS_AGGREGATE-AGGREGATE->AGGREGATE_ID = <ID2KEY>.

        "(2) return the aggregate values
        IF RS_AGGREGATE-IS_NEW = ABAP_TRUE.
          CREATE DATA:
             LRD_AGGREGATE,
             LRD_AGGREGATE->AMOUNTS.
          LRD_AGGREGATE->AGGREGATE_ID = RS_AGGREGATE-AGGREGATE->AGGREGATE_ID.
          INSERT LRD_AGGREGATE->* INTO TABLE MT_AGGREGATE REFERENCE INTO LRD_AGGREGATE.
        ELSE.
          READ TABLE MT_AGGREGATE REFERENCE INTO LRD_AGGREGATE
            WITH KEY ID COMPONENTS
               AGGREGATE_ID-ID = RS_AGGREGATE-AGGREGATE->AGGREGATE_ID-ID.
        ENDIF.

        IF IV_AS_REFERENCE = ABAP_TRUE.
          RS_AGGREGATE-AGGREGATE->AMOUNTS = LRD_AGGREGATE->AMOUNTS.
        ELSE.
          CREATE DATA LRD_AGGREGATE->AMOUNTS.
          LRD_AGGREGATE->AMOUNTS->* = LRD_AGGREGATE->AMOUNTS->*.
        ENDIF.
      ENDIF.
    ENDIF.
  ENDMETHOD.                    "det_aggregate_id_from_data

* ---- ZCL_IM_HRFPM_ENHLG_GRP_AVC====CM003 ----
METHOD ZIF_HRFPM_LG_AVC_AGGREG_HNDL~GET_AFFECTED_OBJECTS.
  DATA LS_FM_POS TYPE HRFPM_FM_POS.
  FIELD-SYMBOLS <HROBJ> LIKE IO_ACC_EXC->HROBJECTS.
  FIELD-SYMBOLS <RUNID> TYPE HRFPM_RUNID.

  TRY .
      CREATE DATA RT_HROBJECT.
      IF NOT IO_ACC_EXC IS BOUND .
        IO_ACC_EXC ?= CL_HRFPM_LG_UTILS=>GET_LOG_HANDLER(
             EXTRACT_BAL_MSG_FROM_LINE( ID_OUTLINE ) ).
      ENDIF.

      ASSIGN COMPONENT 'RUNID' OF STRUCTURE ID_OUTLINE TO <RUNID>.

      ASSIGN IO_ACC_EXC->('HROBJECTS') TO <HROBJ>.

      IF <HROBJ> IS ASSIGNED.
        RT_HROBJECT->* = <HROBJ>.
        "add person-related:
        "
        IF <RUNID> IS ASSIGNED AND NOT
           RT_HROBJECT->* IS INITIAL AND
           IV_WITH_DEPENDING = ABAP_TRUE.

          TRY .

              REPLACE '$' IN IO_ACC_EXC->ACC_DOC_POS-BELNR WITH ''.

              CL_HRFPM_DB_INTERFACE=>GET_SINGLE_FM_DOC(
                EXPORTING
                  IS_FM_DOC_KEY_POS        = IO_ACC_EXC->ACC_DOC_POS
                  IP_BUFFERED              = 'X'
                 IMPORTING
                  ES_FM_DOC_POS            = LS_FM_POS ).

              SELECT
                "depending objects
                 FPM_POS~PLVAR    FPM_POS~OTYPE    FPM_POS~OBJID
                 FPM_POS~PLVAR_DP FPM_POS~OTYPE_DP FPM_POS~OBJID_DP
                 INTO TABLE RT_HROBJECT->*
                FROM HRFPM_FPM_POS AS FPM_POS
                INNER JOIN HRFPM_OBJECTS AS RUN_OBJECT
                  ON  FPM_POS~PLVAR = RUN_OBJECT~PLVAR
                  AND FPM_POS~OTYPE = RUN_OBJECT~OTYPE
                  AND FPM_POS~OBJID = RUN_OBJECT~OBJID
                FOR ALL ENTRIES IN <HROBJ>
                WHERE RUN_OBJECT~RUNID = <RUNID>
                  AND FPM_POS~PLVAR = <HROBJ>-PLVAR
                  AND FPM_POS~OTYPE = <HROBJ>-OTYPE
                  AND FPM_POS~OBJID = <HROBJ>-OBJID
                  AND FPM_POS~ERLKZ     = LS_FM_POS-ERLKZ
                  AND FPM_POS~STATUS    = LS_FM_POS-STATUS
                  AND FPM_POS~DUE_DATE  = LS_FM_POS-DUE_DATE
                  AND FPM_POS~BUKRS     = LS_FM_POS-ACC_ASS-BUKRS
                  AND FPM_POS~KOKRS     = LS_FM_POS-ACC_ASS-KOKRS
                  AND FPM_POS~SAKNR     = LS_FM_POS-ACC_ASS-SAKNR
                  AND FPM_POS~GEBER     = LS_FM_POS-ACC_ASS-GEBER
                  AND FPM_POS~KOSTL     = LS_FM_POS-ACC_ASS-KOSTL
                  AND FPM_POS~FISTL     = LS_FM_POS-ACC_ASS-FISTL
                  AND FPM_POS~AUFNR     = LS_FM_POS-ACC_ASS-AUFNR
                  AND FPM_POS~POSNR     = LS_FM_POS-ACC_ASS-POSNR
                  AND FPM_POS~NPLNR     = LS_FM_POS-ACC_ASS-NPLNR
                  AND FPM_POS~VORNR     = LS_FM_POS-ACC_ASS-VORNR
                  AND FPM_POS~FIPEX     = LS_FM_POS-ACC_ASS-FIPEX
                  AND FPM_POS~FKBER     = LS_FM_POS-ACC_ASS-FKBER
                  AND FPM_POS~GRANT_NBR = LS_FM_POS-ACC_ASS-GRANT_NBR.

              SORT RT_HROBJECT->*.
              DELETE ADJACENT DUPLICATES FROM RT_HROBJECT->*.
            CATCH CX_HRFPM_DB_OPERATION.

          ENDTRY.
        ENDIF.
      ENDIF.
    CATCH CX_SY_MOVE_CAST_ERROR.
  ENDTRY.
ENDMETHOD.

* ---- ZCL_IM_HRFPM_ENHLG_GRP_AVC====CM004 ----
  METHOD IF_HRFPM_LG_ENHANCEMENT_GRP~CHANGE_FIELD_CAT.
    FIELD-SYMBOLS <FCAT> LIKE LINE OF CT_FIELD_CATALOGUE.
    SUPER->IF_HRFPM_LG_ENHANCEMENT_GRP~CHANGE_FIELD_CAT(
      EXPORTING
        IO_OUTPUT_STRUC_HANDLE = IO_OUTPUT_STRUC_HANDLE
      CHANGING
        CT_FIELD_CATALOGUE     = CT_FIELD_CATALOGUE ).


    LOOP AT CT_FIELD_CATALOGUE ASSIGNING <FCAT>
      WHERE FIELDNAME = 'AVAIL_BDGT_HIST'
         OR FIELDNAME = 'FIPEX'
         OR FIELDNAME = 'FISTL'.
      <FCAT>-TECH = SPACE.
    ENDLOOP.
*
*    cl_hrfpm_ui_functions=>modify_dimensions_of_fc_reuse(
*     CHANGING c_t_fieldcat = ct_field_catalogue   ).

  ENDMETHOD.                    "IF_HRFPM_LG_ENHANCEMENT_GRP~CHANGE_FIELD_CAT

* ---- ZCL_IM_HRFPM_ENHLG_GRP_AVC====CM005 ----
  METHOD IF_HRFPM_LG_ENHANCEMENT_GRP~CHANGE_LINE.
    DATA LX TYPE REF TO CX_HRFPM.
    "0 check if this method is applicable to the data of the line at all

    CHECK IV_ENH_GRP_ID IN MTR_ADMISSIBLE_ENH_ID.

    IF NOT IV_LINE_HANDLER IS BOUND.
      IV_LINE_HANDLER ?= CL_HRFPM_LG_UTILS=>GET_LOG_HANDLER(
             EXTRACT_BAL_MSG_FROM_LINE( CD_OUTPUT_LINE ) ).
    ENDIF.

    "1 fill avc amounts
    FILL_AVC_AMOUNT_FIELDS(
        EXPORTING IO_LINE_HANDLER = IV_LINE_HANDLER
        CHANGING CD_OUTPUT_LINE = CD_OUTPUT_LINE ).

    "2 add info about the objects
    FILL_OBJECT_INFO(
        EXPORTING IO_LINE_HANDLER = IV_LINE_HANDLER
        CHANGING CD_OUTPUT_LINE = CD_OUTPUT_LINE ).

*    "3 add info about person responsible for processing an exception
*       ==> moved to the standard enhancement RESPPERS
*    fill_resp_person_info(
*         EXPORTING io_line_handler = lx
*         CHANGING cd_output_line = cd_output_line ).

    DO_AFTER_CHANGE_LINE(
       IO_LINE_HANDLER = IV_LINE_HANDLER
       IS_OUTPUT_LINE  = CD_OUTPUT_LINE
       IV_LINE_INDEX   = IV_LINE_INDEX ).

  ENDMETHOD.                    "if_hrfpm_lg_enhancement_grp~change_line

* ---- ZCL_IM_HRFPM_ENHLG_GRP_AVC====CM006 ----
METHOD DO_AFTER_CHANGE_LINE.
  RETURN.
ENDMETHOD.

* ---- ZCL_IM_HRFPM_ENHLG_GRP_AVC====CM007 ----
  METHOD IF_HRFPM_LG_ENHANCEMENT_GRP~GET_APPLICABLE_TOOLS_FOR_LIST.
    RETURN.
  ENDMETHOD.

* ---- ZCL_IM_HRFPM_ENHLG_GRP_AVC====CM008 ----
  METHOD IF_HRFPM_LG_ENHANCEMENT_GRP~CALL_TOOL_FOR_LIST.
    RETURN.
  ENDMETHOD.

* ---- ZCL_IM_HRFPM_ENHLG_GRP_AVC====CO ----
PROTECTED SECTION.

  ALIASES CHANGE_FIELD_CAT
    FOR IF_HRFPM_LG_ENHANCEMENT_GRP~CHANGE_FIELD_CAT .
  ALIASES CHANGE_LINE
    FOR IF_HRFPM_LG_ENHANCEMENT_GRP~CHANGE_LINE .
  ALIASES CHECK_IF_AGGREGEE
    FOR ZIF_HRFPM_LG_AVC_AGGREG_HNDL~CHECK_IF_AGGREGEE .
  ALIASES CHECK_IF_USABLE
    FOR ZIF_HRFPM_LG_AVC_AGGREG_HNDL~CHECK_IF_USABLE .
  ALIASES DET_AGGREGATE_FROM_DATA
    FOR ZIF_HRFPM_LG_AVC_AGGREG_HNDL~DET_AGGREGATE_FROM_DATA .
  ALIASES FILL_AGGREGATE_KEY
    FOR ZIF_HRFPM_LG_AVC_AGGREG_HNDL~FILL_AGGREGATE_KEY .
  ALIASES GET_AFFECTED_OBJECTS
    FOR ZIF_HRFPM_LG_AVC_AGGREG_HNDL~GET_AFFECTED_OBJECTS .
  ALIASES TYS_AGGREGATE
    FOR ZIF_HRFPM_LG_AVC_AGGREG_HNDL~TYS_AGGREGATE .
  ALIASES TYS_AGGREGATE_ID2KEY
    FOR ZIF_HRFPM_LG_AVC_AGGREG_HNDL~TYS_AGGREGATE_ID2KEY .
  ALIASES TYS_AGGREGATE_RETURN
    FOR ZIF_HRFPM_LG_AVC_AGGREG_HNDL~TYS_AGGREGATE_RETURN .
  ALIASES TYS_HROBJECT_DEP
    FOR ZIF_HRFPM_LG_AVC_AGGREG_HNDL~TYS_HROBJECT_DEP .
  ALIASES TYT_AGGREGATE
    FOR ZIF_HRFPM_LG_AVC_AGGREG_HNDL~TYT_AGGREGATE .
  ALIASES TYT_AGGREGATE_ID2KEY
    FOR ZIF_HRFPM_LG_AVC_AGGREG_HNDL~TYT_AGGREGATE_ID2KEY .
  ALIASES TYT_HROBJECT_DEP
    FOR ZIF_HRFPM_LG_AVC_AGGREG_HNDL~TYT_HROBJECT_DEP .
  ALIASES TYV_AGGREGATE_ID
    FOR ZIF_HRFPM_LG_AVC_AGGREG_HNDL~TYV_AGGREGATE_ID .
  ALIASES TYV_AGGREGATE_VAL
    FOR ZIF_HRFPM_LG_AVC_AGGREG_HNDL~TYV_AGGREGATE_VAL .

  DATA MV_RESP_PERS_ENH_NOT_ACTIVE TYPE BOOLE_D .
  DATA MT_AGGREGATE_ID2KEY TYPE TYT_AGGREGATE_ID2KEY .
  DATA MT_AGGREGATE TYPE TYT_AGGREGATE .
  DATA MO_AGGREG_TYPE TYPE REF TO CL_ABAP_STRUCTDESCR .
  DATA MV_CURRENT_AGGREG_ID TYPE TYV_AGGREGATE_ID .
  DATA:
    MTR_ADMISSIBLE_ENH_ID TYPE RANGE OF HRFPM_APPL_LOG_ENHNC_GRP_ID .

  METHODS DO_AFTER_CHANGE_LINE
    IMPORTING
      !IS_OUTPUT_LINE TYPE DATA
      VALUE(IO_LINE_HANDLER) TYPE REF TO CX_HRFPM OPTIONAL
      !IV_LINE_INDEX TYPE SYTABIX .
  METHODS FILL_AVC_AMOUNT_FIELDS
    IMPORTING
      VALUE(IO_LINE_HANDLER) TYPE REF TO CX_HRFPM OPTIONAL
    CHANGING
      !CD_OUTPUT_LINE TYPE DATA .
  METHODS FIGURE_OUT_MISSING_AMOUNT
  ABSTRACT
    IMPORTING
      !IV_AGGREGATE TYPE TYS_AGGREGATE_RETURN
      !IV_AMOUNTS TYPE HRFPM_APPL_LOG_AVC_AMOUNTS
    RETURNING
      VALUE(RV_MISSING_AMOUNT) TYPE HRFPM_APPL_LOG_AVC_AMOUNTS .

* ---- ZCL_IM_HRFPM_ENHLG_GRP_AVC====CU ----
CLASS ZCL_IM_HRFPM_ENHLG_GRP_AVC DEFINITION
  PUBLIC
  INHERITING FROM ZCL_IM_HRFPM_ENHLG_GRP
  ABSTRACT
  CREATE PUBLIC .

PUBLIC SECTION.

  INTERFACES ZIF_HRFPM_LG_AVC_AGGREG_HNDL
      ABSTRACT METHODS CHECK_IF_AGGREGEE
                       CHECK_IF_USABLE
                       FILL_AGGREGATE_KEY .

  METHODS IF_HRFPM_LG_ENHANCEMENT_GRP~CHANGE_FIELD_CAT
    REDEFINITION .
  METHODS IF_HRFPM_LG_ENHANCEMENT_GRP~CHANGE_LINE
    REDEFINITION .
  METHODS IF_HRFPM_LG_ENHANCEMENT_GRP~GET_APPLICABLE_TOOLS_FOR_LIST
    REDEFINITION .
  METHODS IF_HRFPM_LG_ENHANCEMENT_GRP~CALL_TOOL_FOR_LIST
    REDEFINITION .