* ==== CLASS POOL ZCL_HRFPM_UNES_TRANSFER_BLOCK ====
CLASS-POOL .
*"* class pool for class ZCL_HRFPM_UNES_TRANSFER_BLOCK

*"* local type definitions
INCLUDE ZCL_HRFPM_UNES_TRANSFER_BLOCK=CCDEF.

*"* class ZCL_HRFPM_UNES_TRANSFER_BLOCK definition
*"* public declarations
  INCLUDE ZCL_HRFPM_UNES_TRANSFER_BLOCK=CU.
*"* protected declarations
  INCLUDE ZCL_HRFPM_UNES_TRANSFER_BLOCK=CO.
*"* private declarations
  INCLUDE ZCL_HRFPM_UNES_TRANSFER_BLOCK=CI.
ENDCLASS. "ZCL_HRFPM_UNES_TRANSFER_BLOCK definition

*"* macro definitions
INCLUDE ZCL_HRFPM_UNES_TRANSFER_BLOCK=CCMAC.
*"* local class implementation
INCLUDE ZCL_HRFPM_UNES_TRANSFER_BLOCK=CCIMP.

CLASS ZCL_HRFPM_UNES_TRANSFER_BLOCK IMPLEMENTATION.
*"* method's implementations
  INCLUDE METHODS.
ENDCLASS. "ZCL_HRFPM_UNES_TRANSFER_BLOCK implementation


* ---- ZCL_HRFPM_UNES_TRANSFER_BLOCK=CI ----
PRIVATE SECTION.
*"* private components of class ZCL_HRFPM_UNES_TRANSFER_BLOCK
*"* do not include other source files here!!!

* ---- ZCL_HRFPM_UNES_TRANSFER_BLOCK=CM001 ----
METHOD S_GET_INSTANCE.
  DATA LV_FOUND TYPE BOOLE_D.

  LOOP AT ST_INSTANCE INTO RO_INSTANCE.
    CHECK RO_INSTANCE->FM_DOC_POS = IS_FM_DOC_POS
      AND RO_INSTANCE->PBC_DOC_UPDATE = IR_PBC_UPDATE.
    LV_FOUND = ABAP_TRUE.
    RETURN.
  ENDLOOP.

  IF LV_FOUND = ABAP_FALSE.
    CREATE OBJECT RO_INSTANCE
      EXPORTING
        IS_FM_DOC_POS = IS_FM_DOC_POS
        IR_PBC_DOC_UDPATE = IR_PBC_UPDATE.
    INSERT RO_INSTANCE INTO TABLE ST_INSTANCE.
  ENDIF.
ENDMETHOD.

* ---- ZCL_HRFPM_UNES_TRANSFER_BLOCK=CM002 ----
METHOD CHECK_BLOCKING_ACTIVE.
  BREAK TODO. "evaluate some config table
  DATA LV_DATE TYPE DATUM.

  IF GET_BLOCKING_DATE( GET_BUDGET_CODE( ) ) LE
      PBC_DOC_UPDATE->GET_FM_DOC_POS_DATA( FM_DOC_POS )-DUE_DATE
       "reduction of the budget however are NEVER to be blocked from beeing posted
       AND PBC_DOC_UPDATE->DET_REQ_AMOUNT_OF_FM_POS( FM_DOC_POS ) GT 0.
    RV_BLOCKED = ABAP_TRUE.
  ENDIF.

ENDMETHOD.

* ---- ZCL_HRFPM_UNES_TRANSFER_BLOCK=CM003 ----
METHOD WRITE_BLOCKING_MESSAGE.

  DATA LS_BDGT_CODE TYPE TS_BUDGET_CODE.
  DATA LV_MSG TYPE STRING.
  DATA LV_DUE_DATE TYPE HRFPM_FM_POS-DUE_DATE.

  LS_BDGT_CODE = GET_BUDGET_CODE( ).

  CONCATENATE:

     LS_BDGT_CODE-BUSINESS_AREA
     LS_BDGT_CODE-FUNDING_SOURCE
     INTO LV_MSG SEPARATED BY '/'.

  LV_DUE_DATE = PBC_DOC_UPDATE->GET_FM_DOC_POS_DATA( FM_DOC_POS )-DUE_DATE.
  MESSAGE E899(HRFPM) WITH
   'NO TRANSFERS TO FM AT '
   LV_DUE_DATE
   ' FOR BUDGET CODE '
    LV_MSG INTO LV_MSG.

  MOVE-CORRESPONDING SY TO RS_SY_MESSAGE.
ENDMETHOD.

* ---- ZCL_HRFPM_UNES_TRANSFER_BLOCK=CM004 ----
METHOD CONSTRUCTOR.
  FM_DOC_POS = IS_FM_DOC_POS.
  PBC_DOC_UPDATE = IR_PBC_DOC_UDPATE.
ENDMETHOD.

* ---- ZCL_HRFPM_UNES_TRANSFER_BLOCK=CM005 ----
METHOD GET_BUDGET_CODE.
  RS_BUDGET_CODE-BUSINESS_AREA  =
    PBC_DOC_UPDATE->GET_FM_DOC_POS_DATA( FM_DOC_POS )-GSBER.
  RS_BUDGET_CODE-FUNDING_SOURCE =
   PBC_DOC_UPDATE->GET_FM_DOC_POS_DATA( FM_DOC_POS )-GEBER.
ENDMETHOD.

* ---- ZCL_HRFPM_UNES_TRANSFER_BLOCK=CM006 ----
METHOD GET_BLOCKING_DATE.

  DATA LR_DATE TYPE REF TO TS_BLOCKING_DATE.

  READ TABLE MT_BLOCKING_DATE_BFR REFERENCE INTO LR_DATE
     WITH KEY BUDGET_CODE = IS_BUDGET_CODE.

  IF SY-SUBRC = 0.
    RV_BLOCKING_DATE = LR_DATE->BLOCKING_DATE.
  ELSE.
    CREATE DATA LR_DATE.
    LR_DATE->BUDGET_CODE = IS_BUDGET_CODE.
    LR_DATE->BLOCKING_DATE = RV_BLOCKING_DATE
          = GET_BLOCKING_DATE_EVAL_DB( IS_BUDGET_CODE ).

    INSERT LR_DATE->* INTO TABLE MT_BLOCKING_DATE_BFR.
  ENDIF.


ENDMETHOD.

* ---- ZCL_HRFPM_UNES_TRANSFER_BLOCK=CM007 ----
METHOD GET_BLOCKING_DATE_EVAL_DB.


  BREAK TODO. "evaluate some config table
  DATA LS_TRANSF_BLOCK_BAREA TYPE ZPBC_TRANSF_BLCK.
  DATA LS_TRANSF_BLOCK_FUND TYPE ZPBC_TRANSF_BLCK.
  DATA LS_FM_DOC_POS TYPE HRFPM_FM_DOC_POS.

  LS_FM_DOC_POS = PBC_DOC_UPDATE->GET_FM_DOC_POS_DATA( FM_DOC_POS ).

  SELECT SINGLE BLOCKING_DATE INTO RV_BLOCKING_DATE
      FROM ZPBC_TRANSF_BLCK
      WHERE BUSINESS_AREA = LS_FM_DOC_POS-GSBER
        AND FUNDING_SOURCE = LS_FM_DOC_POS-GEBER
        AND BLOCKING_DATE LE LS_FM_DOC_POS-DUE_DATE.

  IF SY-SUBRC <> 0.

    SELECT SINGLE * INTO LS_TRANSF_BLOCK_BAREA
        FROM ZPBC_TRANSF_BLCK
        WHERE BUSINESS_AREA = LS_FM_DOC_POS-GSBER
          AND FUNDING_SOURCE = SPACE.


    SELECT SINGLE * INTO LS_TRANSF_BLOCK_FUND
        FROM ZPBC_TRANSF_BLCK
        WHERE BUSINESS_AREA = SPACE
          AND FUNDING_SOURCE = LS_FM_DOC_POS-GEBER.

    IF LS_TRANSF_BLOCK_BAREA IS INITIAL
         AND NOT LS_TRANSF_BLOCK_FUND IS INITIAL.
      RV_BLOCKING_DATE = LS_TRANSF_BLOCK_FUND-BLOCKING_DATE.
    ELSEIF  LS_TRANSF_BLOCK_FUND IS INITIAL
         AND NOT LS_TRANSF_BLOCK_BAREA IS INITIAL.
      RV_BLOCKING_DATE = LS_TRANSF_BLOCK_BAREA-BLOCKING_DATE.
    ELSEIF NOT LS_TRANSF_BLOCK_FUND IS INITIAL
         AND NOT LS_TRANSF_BLOCK_BAREA IS INITIAL.

      "evaluate weights
      IF LS_TRANSF_BLOCK_FUND-WEIGHT LT LS_TRANSF_BLOCK_BAREA-WEIGHT.
        RV_BLOCKING_DATE = LS_TRANSF_BLOCK_BAREA-BLOCKING_DATE.
      ELSEIF LS_TRANSF_BLOCK_FUND-WEIGHT GT LS_TRANSF_BLOCK_BAREA-WEIGHT.
        RV_BLOCKING_DATE = LS_TRANSF_BLOCK_FUND-BLOCKING_DATE.
      ELSE.
        "built-in rule of precedence: FUND wins
        RV_BLOCKING_DATE = LS_TRANSF_BLOCK_FUND-BLOCKING_DATE.
      ENDIF.
    ENDIF.
  ENDIF.

  IF RV_BLOCKING_DATE IS INITIAL .
    RV_BLOCKING_DATE = '99991231'.
  ENDIF.


ENDMETHOD.

* ---- ZCL_HRFPM_UNES_TRANSFER_BLOCK=CO ----
PROTECTED SECTION.
*"* protected components of class ZCL_HRFPM_UNES_TRANSFER_BLOCK
*"* do not include other source files here!!!

  TYPES:
    BEGIN OF TS_BLOCKING_DATE,
        BUDGET_CODE TYPE TS_BUDGET_CODE,
        BLOCKING_DATE TYPE DATUM,
     END OF TS_BLOCKING_DATE .
  TYPES:
    TT_BLOCKING_DATE TYPE HASHED TABLE OF TS_BLOCKING_DATE
        WITH UNIQUE KEY BUDGET_CODE .

  CLASS-DATA MT_BLOCKING_DATE_BFR TYPE TT_BLOCKING_DATE .
  DATA FM_DOC_POS TYPE HRFPM_FM_DOC_POS-KEY_POS .
  CLASS-DATA:
    ST_INSTANCE TYPE TABLE OF REF TO ZCL_HRFPM_UNES_TRANSFER_BLOCK .
  DATA PBC_DOC_UPDATE TYPE REF TO ZCL_HRFPM_UNES_CD_PBC_UPDATE .

  METHODS GET_BLOCKING_DATE_EVAL_DB
    IMPORTING
      !IS_BUDGET_CODE TYPE TS_BUDGET_CODE
    RETURNING
      VALUE(RV_BLOCKING_DATE) TYPE DATUM .
  METHODS CONSTRUCTOR
    IMPORTING
      !IS_FM_DOC_POS TYPE HRFPM_FM_DOC_POS-KEY_POS
      !IR_PBC_DOC_UDPATE TYPE REF TO ZCL_HRFPM_UNES_CD_PBC_UPDATE .

* ---- ZCL_HRFPM_UNES_TRANSFER_BLOCK=CU ----
CLASS ZCL_HRFPM_UNES_TRANSFER_BLOCK DEFINITION
  PUBLIC
  CREATE PROTECTED .

PUBLIC SECTION.
*"* public components of class ZCL_HRFPM_UNES_TRANSFER_BLOCK
*"* do not include other source files here!!!

  TYPES:
    BEGIN OF TS_BUDGET_CODE,
              BUSINESS_AREA TYPE GSBER,
              FUNDING_SOURCE TYPE HRFPM_FM_POS-GEBER ,
          END OF TS_BUDGET_CODE .

  CLASS-METHODS S_GET_INSTANCE
    IMPORTING
      !IS_FM_DOC_POS TYPE HRFPM_FM_DOC_POS-KEY_POS
      !IR_PBC_UPDATE TYPE REF TO ZCL_HRFPM_UNES_CD_PBC_UPDATE
    RETURNING
      VALUE(RO_INSTANCE) TYPE REF TO ZCL_HRFPM_UNES_TRANSFER_BLOCK .
  METHODS CHECK_BLOCKING_ACTIVE
    RETURNING
      VALUE(RV_BLOCKED) TYPE BOOLE_D .
  TYPE-POOLS ABAP .
  METHODS WRITE_BLOCKING_MESSAGE
    IMPORTING
      !IV_TO_SY TYPE BOOLE_D DEFAULT ABAP_TRUE
    RETURNING
      VALUE(RS_SY_MESSAGE) TYPE SYMSG .
  METHODS GET_BUDGET_CODE
    RETURNING
      VALUE(RS_BUDGET_CODE) TYPE TS_BUDGET_CODE .
  METHODS GET_BLOCKING_DATE
    IMPORTING
      !IS_BUDGET_CODE TYPE TS_BUDGET_CODE
    RETURNING
      VALUE(RV_BLOCKING_DATE) TYPE DATUM .