* ==== CLASS POOL ZCL_HRFPM_REQUIREMENT_SERVICES ====
CLASS-POOL .
*"* class pool for class ZCL_HRFPM_REQUIREMENT_SERVICES

*"* local type definitions
INCLUDE ZCL_HRFPM_REQUIREMENT_SERVICESCCDEF.

*"* class ZCL_HRFPM_REQUIREMENT_SERVICES definition
*"* public declarations
  INCLUDE ZCL_HRFPM_REQUIREMENT_SERVICESCU.
*"* protected declarations
  INCLUDE ZCL_HRFPM_REQUIREMENT_SERVICESCO.
*"* private declarations
  INCLUDE ZCL_HRFPM_REQUIREMENT_SERVICESCI.
ENDCLASS. "ZCL_HRFPM_REQUIREMENT_SERVICES definition

*"* macro definitions
INCLUDE ZCL_HRFPM_REQUIREMENT_SERVICESCCMAC.
*"* local class implementation
INCLUDE ZCL_HRFPM_REQUIREMENT_SERVICESCCIMP.

CLASS ZCL_HRFPM_REQUIREMENT_SERVICES IMPLEMENTATION.
*"* method's implementations
  INCLUDE METHODS.
ENDCLASS. "ZCL_HRFPM_REQUIREMENT_SERVICES implementation


* ---- ZCL_HRFPM_REQUIREMENT_SERVICESCI ----
PRIVATE SECTION.
*"* private components of class ZCL_HRFPM_REQUIREMENT_SERVICES
*"* do not include other source files here!!!

* ---- ZCL_HRFPM_REQUIREMENT_SERVICESCM001 ----
METHOD ADJUST_COST_DIST_AMOUNT.

*----- New intervall must be in the old one
  IF IS_NEW_VALIDITY-BEGDA < CS_REQUIREMENT-BEGDA
  OR IS_NEW_VALIDITY-BEGDA > CS_REQUIREMENT-ENDDA
  OR IS_NEW_VALIDITY-ENDDA < CS_REQUIREMENT-BEGDA
  OR IS_NEW_VALIDITY-ENDDA > CS_REQUIREMENT-ENDDA
  OR IS_NEW_VALIDITY-ENDDA < IS_NEW_VALIDITY-BEGDA.

    CREATE OBJECT EXC_ADMIN " cx_hrfpm_administrator
      EXPORTING
        TEXTID         = CX_HRFPM_DC_CUSTOMIZING=>WRONG_INTERVAL
        HROBJECT       = CS_REQUIREMENT-HROBJECT.

    MESSAGE E188(HRFPM) INTO MSG_DUMMY.
    EXC_ADMIN->SET_SY_MESSAGE( ).
    RAISE EXCEPTION EXC_ADMIN.

  ELSE.

    CALL FUNCTION 'HR_HCP_CONVERT_PERIODS'
      EXPORTING
        IM_AMOUNT        = CS_REQUIREMENT-BETRG
        IM_NUMBER        = 1
        IM_BEGDA_FROM    = CS_REQUIREMENT-BEGDA
        IM_ENDDA_FROM    = CS_REQUIREMENT-ENDDA
        IM_BEGDA_TO      = IS_NEW_VALIDITY-BEGDA
        IM_ENDDA_TO      = IS_NEW_VALIDITY-ENDDA
      IMPORTING
        EX_AMOUNT        = CS_REQUIREMENT-BETRG
      EXCEPTIONS
        CONVERSION_ERROR = 1
        OTHERS           = 2.

  ENDIF.
ENDMETHOD.

* ---- ZCL_HRFPM_REQUIREMENT_SERVICESCO ----
PROTECTED SECTION.
*"* protected components of class ZCL_HRFPM_REQUIREMENT_SERVICES
*"* do not include other source files here!!!

  CLASS-DATA MSG_DUMMY TYPE STRING .
  CLASS-DATA EXC_ADMIN TYPE REF TO CX_HRFPM_ADMINISTRATOR .

* ---- ZCL_HRFPM_REQUIREMENT_SERVICESCU ----
CLASS ZCL_HRFPM_REQUIREMENT_SERVICES DEFINITION
  PUBLIC
  CREATE PUBLIC .

PUBLIC SECTION.
*"* public components of class CL_HRFPM_REQUIREMENT_SERVICES
*"* do not include other source files here!!!

  CLASS-METHODS ADJUST_COST_DIST_AMOUNT
    IMPORTING
      !IS_NEW_VALIDITY TYPE HRFPM_OBJECT_VALIDITY_IV
    CHANGING
      !CS_REQUIREMENT TYPE HRBPREP_REQUIREMENT_ACC_ASS
    RAISING
      CX_HRFPM_ADMINISTRATOR .