* ==== CLASS POOL ZCL_INFTY_SERVICE ====
CLASS-POOL .
*"* class pool for class ZCL_INFTY_SERVICE

*"* local type definitions
INCLUDE ZCL_INFTY_SERVICE=============CCDEF.

*"* class ZCL_INFTY_SERVICE definition
*"* public declarations
  INCLUDE ZCL_INFTY_SERVICE=============CU.
*"* protected declarations
  INCLUDE ZCL_INFTY_SERVICE=============CO.
*"* private declarations
  INCLUDE ZCL_INFTY_SERVICE=============CI.
ENDCLASS. "ZCL_INFTY_SERVICE definition

*"* macro definitions
INCLUDE ZCL_INFTY_SERVICE=============CCMAC.
*"* local class implementation
INCLUDE ZCL_INFTY_SERVICE=============CCIMP.

CLASS ZCL_INFTY_SERVICE IMPLEMENTATION.
*"* method's implementations
  INCLUDE METHODS.
ENDCLASS. "ZCL_INFTY_SERVICE implementation


* ---- ZCL_INFTY_SERVICE=============CI ----
PRIVATE SECTION.
*"* private components of class ZCL_INFTY_SERVICE
*"* do not include other source files here!!!

* ---- ZCL_INFTY_SERVICE=============CM001 ----
METHOD CONSTRUCTOR.
  DATA LV_TYPE TYPE STRING.
  ZIF_INFTY_SERVICES~MV_INFTY = IV_INFTY.
  ZIF_INFTY_SERVICES~MV_ISTAT = IV_ISTAT.
  ZIF_INFTY_SERVICES~MV_SUBTY = IV_SUBTY.
  ZIF_INFTY_SERVICES~MV_READ_BUFFERED = IV_BUFFERED.

  CONCATENATE 'P' IV_INFTY INTO LV_TYPE.
  MO_INFTY_TYPE ?=
      CL_ABAP_TYPEDESCR=>DESCRIBE_BY_NAME( LV_TYPE ).

  MO_INFTY_TAB_TYPE =
        CL_ABAP_TABLEDESCR=>CREATE( MO_INFTY_TYPE ).

  CLEAR LV_TYPE.
  CASE MV_INFTY(1).
    WHEN '1'.
      CONCATENATE 'HRI' IV_INFTY INTO LV_TYPE.
    WHEN OTHERS.
      CONCATENATE 'PS' IV_INFTY INTO LV_TYPE.
  ENDCASE.

  MO_INFTY_DAT_TYPE ?=
          CL_ABAP_TYPEDESCR=>DESCRIBE_BY_NAME( LV_TYPE ).
ENDMETHOD.

* ---- ZCL_INFTY_SERVICE=============CM002 ----
METHOD GET_SPECIFIED_IN_PERIOD.

  DATA LT_TC1 TYPE CL_HRFPM_GLOBAL_SERVICES=>TT_PERIOD_SPLIT.
  DATA LRT_PNNNN TYPE REF TO DATA .
  FIELD-SYMBOLS <TPNNN> TYPE STANDARD TABLE .
  FIELD-SYMBOLS <TC1> LIKE LINE OF LT_TC1.
  FIELD-SYMBOLS <REF> LIKE LINE OF <TC1>-TAB_REF.
  FIELD-SYMBOLS <LINE> TYPE ANY.

  IF IT_PNNNN IS SUPPLIED.
    ASSERT MO_INFTY_TAB_TYPE->APPLIES_TO_DATA( IT_PNNNN )
       = ABAP_TRUE .
    ASSIGN IT_PNNNN TO <TPNNN>.
  ELSE.
    ASSERT NOT IS_HROBJECT IS INITIAL.

    LRT_PNNNN = ZIF_INFTY_SERVICES~CREATE_TAB_INSTANCE( ).
    ASSIGN LRT_PNNNN->* TO <TPNNN>.

    ZIF_INFTY_SERVICES~READ_INFTY_IN_PERIOD(
       EXPORTING
         IS_HROBJECT   = IS_HROBJECT
         IS_SEL_PERIOD = IS_SEL_PERIOD
       IMPORTING
          ET_PNNNN = <TPNNN> ).

  ENDIF.

  CL_HRFPM_GLOBAL_SERVICES=>CONVERT_TO_TIME_CONSTRAINT_1(
    EXPORTING
      IT_DATA_TAB         = <TPNNN>
      IV_BEGDA            = IS_SEL_PERIOD-BEGDA
      IV_ENDDA            = IS_SEL_PERIOD-ENDDA
    IMPORTING
      ET_PERIOD_SPLIT     = LT_TC1  ).

  IF IV_SPEC = C_LATEST.
    READ TABLE LT_TC1 INDEX LINES( LT_TC1 ) ASSIGNING <TC1>.
  ELSEIF IV_SPEC = C_EARLIEST.
    READ TABLE LT_TC1 INDEX 1 ASSIGNING <TC1>.
  ENDIF.

  IF SY-SUBRC = 0.
    LOOP AT <TC1>-TAB_REF ASSIGNING <REF>.
      READ TABLE <TPNNN> INDEX <REF> ASSIGNING <LINE>.
      INSERT <LINE> INTO TABLE ET_PNNNN_SPECIFIED.
    ENDLOOP.
  ENDIF.
ENDMETHOD.

* ---- ZCL_INFTY_SERVICE=============CM003 ----
METHOD ZIF_INFTY_SERVICES~CREATE_TAB_INSTANCE.
  CREATE DATA RO_TAB_REF TYPE HANDLE MO_INFTY_TAB_TYPE.
ENDMETHOD.

* ---- ZCL_INFTY_SERVICE=============CM004 ----
METHOD ZIF_INFTY_SERVICES~GET_EARLIEST_IN_PERIOD.

  GET_SPECIFIED_IN_PERIOD(
     EXPORTING
       IS_SEL_PERIOD      = IS_SEL_PERIOD
       IT_PNNNN          = IT_PNNNN
       IS_HROBJECT        = IS_HROBJECT
       IV_SPEC            = C_EARLIEST
     IMPORTING
       ET_PNNNN_SPECIFIED = ET_PNNNN_EARLIEST
     EXCEPTIONS
       NONE_FOUND         = 1
       OTHERS             = 2  ).

ENDMETHOD.

* ---- ZCL_INFTY_SERVICE=============CM005 ----
METHOD ZIF_INFTY_SERVICES~GET_LATEST_IN_PERIOD.

  GET_SPECIFIED_IN_PERIOD(
     EXPORTING
       IS_SEL_PERIOD      = IS_SEL_PERIOD
       IT_PNNNN          = IT_PNNNN
       IS_HROBJECT        = IS_HROBJECT
       IV_SPEC            = C_LATEST
     IMPORTING
       ET_PNNNN_SPECIFIED = ET_PNNNN_LATEST
     EXCEPTIONS
       NONE_FOUND         = 1
       OTHERS             = 2  ).


ENDMETHOD.

* ---- ZCL_INFTY_SERVICE=============CM006 ----
METHOD ZIF_INFTY_SERVICES~READ_INFTY_IN_PERIOD.

  READ_INFTY_FROM_BUFFER(
    EXPORTING
      IS_HROBJECT   = IS_HROBJECT
      IS_SEL_PERIOD = IS_SEL_PERIOD
    IMPORTING
      ET_PNNNN      = ET_PNNNN ).

  IF ET_PNNNN IS INITIAL.
    READ_INFTY_FROM_DB(
      EXPORTING
        IS_HROBJECT   = IS_HROBJECT
        IS_SEL_PERIOD = IS_SEL_PERIOD
      IMPORTING
        ET_PNNNN      = ET_PNNNN     ).
  ENDIF.

  PUT_INTO_BUFFER(
   IS_SEL_PERIOD = IS_SEL_PERIOD
   IS_HROBJECT   = IS_HROBJECT
   IT_PNNNN      = ET_PNNNN ).

ENDMETHOD.

* ---- ZCL_INFTY_SERVICE=============CM007 ----
METHOD ZIF_INFTY_SERVICES~S_GET_INSTANCE.
  DATA LV_FOUND TYPE BOOLE_D VALUE ABAP_FALSE.

  LOOP AT ZIF_INFTY_SERVICES~GT_INSTANCES INTO RO_SERVICE.
    CHECK IV_BUFFERED  = RO_SERVICE->MV_READ_BUFFERED
      AND IV_ISTAT     = RO_SERVICE->MV_ISTAT
      AND IV_INFTY     = RO_SERVICE->MV_INFTY
      AND IV_SUBTY     = RO_SERVICE->MV_SUBTY
      AND IV_PATHID    = RO_SERVICE->MV_PATHID.
    LV_FOUND = ABAP_TRUE.
    EXIT.
  ENDLOOP.

  IF LV_FOUND = ABAP_FALSE.
    IF NOT IV_INFTY(1) = '1'.
      CREATE OBJECT RO_SERVICE TYPE ZCL_INFTY_SERVICE
        EXPORTING
          IV_BUFFERED = IV_BUFFERED
          IV_ISTAT    = IV_ISTAT
          IV_INFTY    = IV_INFTY
          IV_SUBTY    = IV_SUBTY.
    ELSE.
      IF IV_INFTY = '1008'.
        CREATE OBJECT RO_SERVICE TYPE ZCL_INFTY_SERVICE_1008
          EXPORTING
            IV_BUFFERED = IV_BUFFERED
            IV_ISTAT    = IV_ISTAT
            IV_INFTY    = '1008'.
      ELSEIF IV_INFTY = '1018'.
        CREATE OBJECT RO_SERVICE TYPE ZCL_INFTY_SERVICE_1008
          EXPORTING
            IV_BUFFERED = IV_BUFFERED
            IV_ISTAT    = IV_ISTAT
            IV_INFTY    = '1018'.
      ELSE.
        CREATE OBJECT RO_SERVICE TYPE ZCL_INFTY_SERVICE_PD
          EXPORTING
            IV_BUFFERED = IV_BUFFERED
            IV_ISTAT    = IV_ISTAT
            IV_INFTY    = IV_INFTY
            IV_SUBTY    = IV_SUBTY.
      ENDIF.
    ENDIF.
    INSERT RO_SERVICE INTO TABLE ZIF_INFTY_SERVICES~GT_INSTANCES.
  ENDIF.
ENDMETHOD.

* ---- ZCL_INFTY_SERVICE=============CM008 ----
METHOD PUT_INTO_BUFFER.
  RETURN.
ENDMETHOD.

* ---- ZCL_INFTY_SERVICE=============CM009 ----
METHOD READ_INFTY_FROM_BUFFER.
  BREAK TODO.
  RETURN.
ENDMETHOD.

* ---- ZCL_INFTY_SERVICE=============CM00A ----
METHOD READ_INFTY_FROM_DB.

  IF MV_SUBTY IS INITIAL.
    CALL FUNCTION 'RH_READ_INFTY'
      EXPORTING
*       AUTHORITY            = 'DISP'
        WITH_STRU_AUTH       = ' '
        PLVAR                = IS_HROBJECT-PLVAR
        OTYPE                = IS_HROBJECT-OTYPE
        OBJID                = IS_HROBJECT-OBJID
        INFTY                = MV_INFTY
        ISTAT                = MV_ISTAT
*       EXTEND               = 'X'
*       SUBTY                = ' '
        BEGDA                = IS_SEL_PERIOD-BEGDA
        ENDDA                = IS_SEL_PERIOD-ENDDA
*       CONDITION            = '00000'
*       INFTB                = '1'
*       SORT                 = 'X'
*       VIA_T777D            = ' '
      TABLES
        INNNN                = ET_PNNNN
*       OBJECTS              = OBJECTS
      EXCEPTIONS
        ALL_INFTY_WITH_SUBTY = 1
        NOTHING_FOUND        = 2
        NO_OBJECTS           = 3
        WRONG_CONDITION      = 4
        WRONG_PARAMETERS     = 5
        OTHERS               = 6.
    IF SY-SUBRC <> 0.
* Implement suitable error handling here
    ENDIF.
  ELSE.
    CALL FUNCTION 'RH_READ_INFTY'
      EXPORTING
*       AUTHORITY            = 'DISP'
        WITH_STRU_AUTH       = ' '
        PLVAR                = IS_HROBJECT-PLVAR
        OTYPE                = IS_HROBJECT-OTYPE
        OBJID                = IS_HROBJECT-OBJID
        INFTY                = MV_INFTY
        ISTAT                = MV_ISTAT
*       EXTEND               = 'X'
        SUBTY                = MV_SUBTY
        BEGDA                = IS_SEL_PERIOD-BEGDA
        ENDDA                = IS_SEL_PERIOD-ENDDA
*       CONDITION            = '00000'
*       INFTB                = '1'
*       SORT                 = 'X'
*       VIA_T777D            = ' '
      TABLES
        INNNN                = ET_PNNNN
*       OBJECTS              = OBJECTS
      EXCEPTIONS
        ALL_INFTY_WITH_SUBTY = 1
        NOTHING_FOUND        = 2
        NO_OBJECTS           = 3
        WRONG_CONDITION      = 4
        WRONG_PARAMETERS     = 5
        OTHERS               = 6.
    IF SY-SUBRC <> 0.
* Implement suitable error handling here
    ENDIF.
  ENDIF.

ENDMETHOD.

* ---- ZCL_INFTY_SERVICE=============CM00B ----
METHOD ZIF_INFTY_SERVICES~GET_AS_TC1_IN_PERIOD.

  DATA LT_TC1 TYPE CL_HRFPM_GLOBAL_SERVICES=>TT_PERIOD_SPLIT.
  DATA LRT_PNNNN TYPE REF TO DATA .
  DATA LRS_PNNNN TYPE REF TO DATA.
  FIELD-SYMBOLS <TPNNN> TYPE STANDARD TABLE .
  FIELD-SYMBOLS <TC1> LIKE LINE OF LT_TC1.
  FIELD-SYMBOLS <REF> LIKE LINE OF <TC1>-TAB_REF.
  FIELD-SYMBOLS <PNNNN> TYPE ANY.
  FIELD-SYMBOLS <LPNNNN> TYPE ANY.

  LRT_PNNNN = ZIF_INFTY_SERVICES~CREATE_TAB_INSTANCE( ).
  ASSIGN LRT_PNNNN->* TO <TPNNN>.

  IF IT_PNNNN IS SUPPLIED .
    ASSERT MO_INFTY_TAB_TYPE->APPLIES_TO_DATA( IT_PNNNN )
       = ABAP_TRUE .
    <TPNNN> = IT_PNNNN.
  ELSE.
    ASSERT NOT IS_HROBJECT IS INITIAL.
    ZIF_INFTY_SERVICES~READ_INFTY_IN_PERIOD(
       EXPORTING
         IS_HROBJECT   = IS_HROBJECT
         IS_SEL_PERIOD = IS_SEL_PERIOD
       IMPORTING
          ET_PNNNN = <TPNNN> ).
  ENDIF.


  CL_HRFPM_GLOBAL_SERVICES=>CONVERT_TO_TIME_CONSTRAINT_1(
    EXPORTING
      IT_DATA_TAB         = <TPNNN>
      IV_BEGDA            = IS_SEL_PERIOD-BEGDA
      IV_ENDDA            = IS_SEL_PERIOD-ENDDA
    IMPORTING
      ET_PERIOD_SPLIT     = LT_TC1  ).

  LOOP AT LT_TC1 ASSIGNING <TC1>.
    IF <TC1>-TAB_REF IS INITIAL.
      INSERT <TC1>-PERIOD INTO TABLE ET_GAPS.
    ELSE.
      LOOP AT <TC1>-TAB_REF ASSIGNING <REF>.
        READ TABLE <TPNNN> INDEX <REF> ASSIGNING <PNNNN>.
        CREATE DATA LRS_PNNNN TYPE HANDLE MO_INFTY_TYPE.
        ASSIGN LRS_PNNNN->* TO <LPNNNN>.
        MOVE-CORRESPONDING <TC1>-PERIOD TO <LPNNNN>.
        INSERT <LPNNNN> INTO TABLE ET_PNNNN_TC1.
      ENDLOOP.
    ENDIF.
  ENDLOOP.


ENDMETHOD.

* ---- ZCL_INFTY_SERVICE=============CO ----
PROTECTED SECTION.
*"* protected components of class ZCL_INFTY_SERVICE
*"* do not include other source files here!!!

  ALIASES MV_INFTY
    FOR ZIF_INFTY_SERVICES~MV_INFTY .
  ALIASES MV_ISTAT
    FOR ZIF_INFTY_SERVICES~MV_ISTAT .
  ALIASES MV_READ_BUFFERED
    FOR ZIF_INFTY_SERVICES~MV_READ_BUFFERED .
  ALIASES MV_SUBTY
    FOR ZIF_INFTY_SERVICES~MV_SUBTY .

  DATA MO_INFTY_TYPE TYPE REF TO CL_ABAP_STRUCTDESCR .
  DATA MO_INFTY_TAB_TYPE TYPE REF TO CL_ABAP_TABLEDESCR .
  CONSTANTS C_EARLIEST TYPE FLAG VALUE 'E'. "#EC NOTEXT
  CONSTANTS C_LATEST TYPE FLAG VALUE 'L'. "#EC NOTEXT
  DATA MO_INFTY_DAT_TYPE TYPE REF TO CL_ABAP_STRUCTDESCR .

  METHODS CONSTRUCTOR
    IMPORTING
      !IV_BUFFERED TYPE FLAG
      !IV_ISTAT TYPE ISTAT_D
      !IV_INFTY TYPE INFTY
      !IV_SUBTY TYPE SUBTY OPTIONAL .
  METHODS GET_SPECIFIED_IN_PERIOD
    IMPORTING
      !IS_SEL_PERIOD TYPE HRFPM_TIME
      !IT_PNNNN TYPE TABLE OPTIONAL
      !IS_HROBJECT TYPE HROBJECT OPTIONAL
      !IV_SPEC TYPE FLAG OPTIONAL
    EXPORTING
      !ET_PNNNN_SPECIFIED TYPE TABLE
    EXCEPTIONS
      NONE_FOUND .
  METHODS READ_INFTY_FROM_BUFFER
    IMPORTING
      !IS_HROBJECT TYPE HROBJECT
      !IS_SEL_PERIOD TYPE HRFPM_TIME
    EXPORTING
      !ET_PNNNN TYPE TABLE .
  METHODS READ_INFTY_FROM_DB
    IMPORTING
      !IS_HROBJECT TYPE HROBJECT
      !IS_SEL_PERIOD TYPE HRFPM_TIME
    EXPORTING
      !ET_PNNNN TYPE TABLE .
  METHODS PUT_INTO_BUFFER
    IMPORTING
      !IS_SEL_PERIOD TYPE HRFPM_TIME
      !IS_HROBJECT TYPE HROBJECT
      !IT_PNNNN TYPE TABLE .

* ---- ZCL_INFTY_SERVICE=============CU ----
CLASS ZCL_INFTY_SERVICE DEFINITION
  PUBLIC
  CREATE PROTECTED .

PUBLIC SECTION.
*"* public components of class ZCL_INFTY_SERVICE
*"* do not include other source files here!!!

  INTERFACES ZIF_INFTY_SERVICES .

  ALIASES S_GET_INSTANCE
    FOR ZIF_INFTY_SERVICES~S_GET_INSTANCE .