* ==== CLASS POOL ZCL_IM_HRFPM_CREATE_DOCS ====
CLASS-POOL .
*"* class pool for class ZCL_IM_HRFPM_CREATE_DOCS

*"* local type definitions
INCLUDE ZCL_IM_HRFPM_CREATE_DOCS======CCDEF.

*"* class ZCL_IM_HRFPM_CREATE_DOCS definition
*"* public declarations
  INCLUDE ZCL_IM_HRFPM_CREATE_DOCS======CU.
*"* protected declarations
  INCLUDE ZCL_IM_HRFPM_CREATE_DOCS======CO.
*"* private declarations
  INCLUDE ZCL_IM_HRFPM_CREATE_DOCS======CI.
ENDCLASS. "ZCL_IM_HRFPM_CREATE_DOCS definition

*"* macro definitions
INCLUDE ZCL_IM_HRFPM_CREATE_DOCS======CCMAC.
*"* local class implementation
INCLUDE ZCL_IM_HRFPM_CREATE_DOCS======CCIMP.

CLASS ZCL_IM_HRFPM_CREATE_DOCS IMPLEMENTATION.
*"* method's implementations
  INCLUDE METHODS.
ENDCLASS. "ZCL_IM_HRFPM_CREATE_DOCS implementation


* ---- ZCL_IM_HRFPM_CREATE_DOCS======CI ----
PRIVATE SECTION.

* ---- ZCL_IM_HRFPM_CREATE_DOCS======CM001 ----
  METHOD CREATE_UPDATE_LOGIC.
    DATA LV_FLT_VAL LIKE FLT_VAL.
    IF NOT INT_FILT_VAL = 'ZSTANDARD_2_NO_AVC_CHECK'.
      RP_UPDATE_LOGIC = SUPER->CREATE_UPDATE_LOGIC( ).
    ELSE.
      CREATE OBJECT RP_UPDATE_LOGIC TYPE ZCL_HRFPM_UNES_CD_UPDATE_LOGIC
        EXPORTING
          IP_RUNID         = RUNID
          IP_ENC_TYPE      = ENC_TYPE
          IP_FLT_VAL       = CL_HRFPM_CONST=>NEW_DOC_CREATION_AVC_CHECK_OFF
          IP_CREATION_MODE = CREATION_MODE.
    ENDIF.
  ENDMETHOD.

* ---- ZCL_IM_HRFPM_CREATE_DOCS======CM002 ----
  METHOD SET_GLOBAL_PARAMETERS.
    IF NOT IP_FLT_VAL = 'ZSTANDARD_2_NO_AVC_CHECK'.
      SUPER->SET_GLOBAL_PARAMETERS(
          IP_FLT_VAL      = IP_FLT_VAL
          IP_FPM_VARIANT  = IP_FPM_VARIANT
          IS_GLOBAL_ATTR  = IS_GLOBAL_ATTR
          I_ENC_DATE_IV   = I_ENC_DATE_IV
          IP_OTYPE        = IP_OTYPE
          IP_FLG_DELETION = IP_FLG_DELETION
          IT_OBJECTS      = IT_OBJECTS ).
    ELSE.
      SUPER->SET_GLOBAL_PARAMETERS(
          IP_FLT_VAL      = CL_HRFPM_CONST=>NEW_DOC_CREATION_AVC_CHECK_OFF
          IP_FPM_VARIANT  = IP_FPM_VARIANT
          IS_GLOBAL_ATTR  = IS_GLOBAL_ATTR
          I_ENC_DATE_IV   = I_ENC_DATE_IV
          IP_OTYPE        = IP_OTYPE
          IP_FLG_DELETION = IP_FLG_DELETION
          IT_OBJECTS      = IT_OBJECTS ).
      INT_FILT_VAL = IP_FLT_VAL.
    ENDIF.
  ENDMETHOD.

* ---- ZCL_IM_HRFPM_CREATE_DOCS======CO ----
PROTECTED SECTION.

  DATA INT_FILT_VAL LIKE FLT_VAL .

  METHODS CREATE_UPDATE_LOGIC
    REDEFINITION .
  METHODS SET_GLOBAL_PARAMETERS
    REDEFINITION .

* ---- ZCL_IM_HRFPM_CREATE_DOCS======CU ----
CLASS ZCL_IM_HRFPM_CREATE_DOCS DEFINITION
  PUBLIC
  INHERITING FROM CL_IM_HRFPM_CD_STANDARD_2
  FINAL
  CREATE PUBLIC .

PUBLIC SECTION.