* ==== CLASS POOL ZCL_IM__UNESCO_ENCUMB_VACANCY ====
CLASS-POOL .
*"* class pool for class ZCL_IM__UNESCO_ENCUMB_VACANCY

*"* local type definitions
INCLUDE ZCL_IM__UNESCO_ENCUMB_VACANCY=CCDEF.

*"* class ZCL_IM__UNESCO_ENCUMB_VACANCY definition
*"* public declarations
  INCLUDE ZCL_IM__UNESCO_ENCUMB_VACANCY=CU.
*"* protected declarations
  INCLUDE ZCL_IM__UNESCO_ENCUMB_VACANCY=CO.
*"* private declarations
  INCLUDE ZCL_IM__UNESCO_ENCUMB_VACANCY=CI.
ENDCLASS. "ZCL_IM__UNESCO_ENCUMB_VACANCY definition

*"* macro definitions
INCLUDE ZCL_IM__UNESCO_ENCUMB_VACANCY=CCMAC.
*"* local class implementation
INCLUDE ZCL_IM__UNESCO_ENCUMB_VACANCY=CCIMP.

CLASS ZCL_IM__UNESCO_ENCUMB_VACANCY IMPLEMENTATION.
*"* method's implementations
  INCLUDE METHODS.
ENDCLASS. "ZCL_IM__UNESCO_ENCUMB_VACANCY implementation


* ---- ZCL_IM__UNESCO_ENCUMB_VACANCY=CI ----
PRIVATE SECTION.
*"* private components of class ZCL_IM__UNESCO_ENCUMB_VACANCY
*"* do not include other source files here!!!

* ---- ZCL_IM__UNESCO_ENCUMB_VACANCY=CM001 ----
METHOD ZIF_REQUIREMENT_FILTER~DO_REQUIREMENT_FILTRATION.
  "1. restriction of vacancy
  "For positions keep only those requirements arising directly
  "from vacancy

  "CHECK sy-uname = 'SAP'.

  DO_HANDLE_VACANCY(
   EXPORTING
     IS_FILTRATION_PERIOD = IS_FILTRATION_PERIOD
   CHANGING
     CT_REQUIREMENT       = CT_REQUIREMENT ).


ENDMETHOD.

* ---- ZCL_IM__UNESCO_ENCUMB_VACANCY=CM002 ----
METHOD DO_HANDLE_VACANCY.
  SUPER->DO_HANDLE_VACANCY(
    EXPORTING
      IS_FILTRATION_PERIOD = IS_FILTRATION_PERIOD
    CHANGING
      CT_REQUIREMENT       = CT_REQUIREMENT ).
ENDMETHOD.

* ---- ZCL_IM__UNESCO_ENCUMB_VACANCY=CM003 ----
METHOD DO_HANDLE_COMMITMENT_PERIOD.
  "No filtering over period ==>
  "in this scenario this is done in ZCL_IM__'UNESCO_ENCUMB_ENCPER
  "acting as implementation ZEI_HRFPM_DC_PERIOD_UNESCO
  ASSERT 1 = 2.
ENDMETHOD.

* ---- ZCL_IM__UNESCO_ENCUMB_VACANCY=CO ----
PROTECTED SECTION.
*"* protected components of class ZCL_IM__UNESCO_ENCUMB_VACANCY
*"* do not include other source files here!!!

* ---- ZCL_IM__UNESCO_ENCUMB_VACANCY=CU ----
CLASS ZCL_IM__UNESCO_ENCUMB_VACANCY DEFINITION
  PUBLIC
  INHERITING FROM ZCL_IM__UNESCO_ENCUMB
  FINAL
  CREATE PUBLIC .

PUBLIC SECTION.
*"* public components of class ZCL_IM__UNESCO_ENCUMB_VACANCY
*"* do not include other source files here!!!

  METHODS DO_HANDLE_COMMITMENT_PERIOD
    REDEFINITION .
  METHODS ZIF_REQUIREMENT_FILTER~DO_REQUIREMENT_FILTRATION
    REDEFINITION .
  METHODS DO_HANDLE_VACANCY
    REDEFINITION .