************************************************************************
* Include FPAYM_TOP                                                    *
* Global Data Declarations                                             *
************************************************************************

REPORT SAPFPAYM
       LINE-SIZE 132
       MESSAGE-ID BFIBL02
       NO STANDARD PAGE HEADING.


*- Function module name variable for illegal calls --------------------*
INCLUDE IFPAYM_MODULE_NAME.


*- Include for general data declarations ------------------------------*
INCLUDE <ICON>.


*- Type Pools ---------------------------------------------------------*
TYPE-POOLS RSDS.


*- Tables -------------------------------------------------------------*
TABLES:
  FPAYH,
  FPAYP,


*- Structures ---------------------------------------------------------*
  SSCRFIELDS.


*- Selection screen decalaration --------------------------------------*

*- Format ---
SELECTION-SCREEN SKIP.
SELECTION-SCREEN BEGIN OF BLOCK 1 WITH FRAME TITLE TEXT-002.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN:
  COMMENT 1(30) TEXT-007 FOR FIELD PAR_FORM,
  POSITION POS_LOW.
PARAMETERS:
  PAR_FORM LIKE TFPM042F-FORMI OBLIGATORY,
  PAR_FORP LIKE FPM_SELPAR-PARAM NO-DISPLAY,
  PAR_FOPC LIKE FPM_SELPAR-PARAM NO-DISPLAY.
SELECTION-SCREEN
  PUSHBUTTON 76(04) IBUTTON USER-COMMAND INFO MODIF ID I.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN
  PUSHBUTTON 33(30) FBUTTON USER-COMMAND FORM MODIF ID F.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK 1.

*- Payment mediums and Lists ---
SELECTION-SCREEN BEGIN OF BLOCK 2 WITH FRAME TITLE TEXT-001.

* Payment medium 1 (Paper)
SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS:
  PAR_XPY1 LIKE TFPM042F-XPRI1 MODIF ID PY1,
  PAR_PRI1 TYPE FPM_PARCON NO-DISPLAY.
SELECTION-SCREEN:
  COMMENT 3(28) TEXT_PY1 FOR FIELD PAR_XPY1 MODIF ID PY1,
  PUSHBUTTON 33(30) P1BUTTON USER-COMMAND PRI1 MODIF ID PY1.
SELECTION-SCREEN END OF LINE.

* Payment medium 3 (File)
SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS:
  PAR_XPY3 LIKE TFPM042F-XDME1 MODIF ID PY3,
  PAR_PRI3 TYPE FPM_PARCON NO-DISPLAY.
SELECTION-SCREEN:
  COMMENT 3(28) TEXT_PY3 FOR FIELD PAR_XPY3 MODIF ID PY3,
  PUSHBUTTON 33(30) P3BUTTON USER-COMMAND PRI3 MODIF ID PY2.
SELECTION-SCREEN END OF LINE.

* Payment medium 5 (List)
SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS:
  PAR_XPY5 LIKE TFPM042F-XLST1 MODIF ID PY5,
  PAR_PRI5 LIKE FPM_PARCON NO-DISPLAY,
  PAR_ARC5 LIKE FPM_PARCON NO-DISPLAY.
SELECTION-SCREEN:
  COMMENT 3(28) TEXT_PY5 FOR FIELD PAR_XPY5 MODIF ID PY5,
  PUSHBUTTON 33(30) P5BUTTON USER-COMMAND PRI5 MODIF ID PY5.
SELECTION-SCREEN END OF LINE.

* Accompanying list
SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS:
  PAR_XLST LIKE FPM_SELPAR-XPLST MODIF ID LST,
  PAR_PRIL LIKE FPM_PARCON NO-DISPLAY MODIF ID LST,
  PAR_ARCL LIKE FPM_PARCON NO-DISPLAY MODIF ID LST.
SELECTION-SCREEN:
  COMMENT 3(28) TEXT-012 FOR FIELD PAR_XLST MODIF ID LST,
  PUSHBUTTON 33(30) LBUTTON USER-COMMAND PRIL MODIF ID LST.
SELECTION-SCREEN END OF LINE.

* Error log
SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS:
  PAR_XERR LIKE FPM_SELPAR-XPERR,
  PAR_PRIE LIKE FPM_PARCON NO-DISPLAY,
  PAR_ARCE LIKE FPM_PARCON NO-DISPLAY.
SELECTION-SCREEN:
  COMMENT 03(28) TEXT-013 FOR FIELD PAR_XERR,
  PUSHBUTTON 33(30) EBUTTON USER-COMMAND PRIE.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK 2.

*- Further file and form parameters ---
SELECTION-SCREEN BEGIN OF BLOCK 3 WITH FRAME TITLE TEXT-003.

* File name
PARAMETERS:
  PAR_BELP LIKE FPM_SELPAR-XBELP DEFAULT 'X',                  "n2783609
  P_BCMRSD TYPE XFELD NO-DISPLAY,    "Resend payment batch     "n2927769
  PAR_F11S TYPE XFELD NO-DISPLAY,    "wait if PAR_BELP = X     "n1922823
  PAR_XFIL LIKE FPM_SELPAR-XPFIL MODIF ID PY4,
  PAR_BOTH TYPE XTEMSE_AND_FILE_FPM NO-DISPLAY MODIF ID PY4,"nte1428908
  PAR_FILE LIKE FPM_SELPAR-PFILE MODIF ID PY4.

* Layout sets
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN:
  COMMENT 1(30) TEXT_FP1 FOR FIELD PAR_FPY1 MODIF ID PY1,
  POSITION POS_LOW.
PARAMETERS:
  PAR_FPY1 LIKE FPM_SELPAR-ALTFORM MODIF ID PY1.
SELECTION-SCREEN:
  PUSHBUTTON 58(20) F1BUTTON USER-COMMAND SCR1 MODIF ID PY1.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN:
  COMMENT 1(30) TXT_PDF1 FOR FIELD PAR_PDF1 MODIF ID PY1,
  POSITION POS_LOW.
PARAMETERS:
  PAR_PDF1 TYPE FPWBFORMNAME MODIF ID PY1.
SELECTION-SCREEN END OF LINE.

* filler
PARAMETERS:
  PAR_FILL TYPE FILLER_FPM MODIF ID PY1.

*accompanying sheet
PARAMETERS:
  PAR_FTYP TYPE FPM_FORMTYPE
    AS LISTBOX VISIBLE LENGTH 12 USER-COMMAND FORM_TYPE_CHANGED MODIF ID PY2,
  PAR_FPY3 LIKE FPM_SELPAR-ALTFORM MODIF ID PY2.
SELECTION-SCREEN:
  PUSHBUTTON 58(20) F3BUTTON USER-COMMAND SCR3 MODIF ID PY2.
PARAMETERS:
  PAR_PDF3 TYPE FPWBFORMNAME MODIF ID PY2.

* accompanying list
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN:
  COMMENT 1(30) TEXT-017 FOR FIELD PAR_VARI,
  POSITION POS_LOW.
PARAMETERS:
  PAR_VARI LIKE DISVARIANT-VARIANT.
SELECTION-SCREEN POSITION 58.
PARAMETERS:
  PAR_SCRN LIKE FPM_SELPAR-XSCRN.
SELECTION-SCREEN:
  COMMENT 60(20) TEXT-018 FOR FIELD PAR_SCRN.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK 3.


*- Internal tables ----------------------------------------------------*
DATA:
  GT_FPAYP        LIKE FPAYP      OCCURS 0 WITH HEADER LINE,
  GT_TFPM042FM    LIKE TFPM042FM  OCCURS 0 WITH HEADER LINE,
  GT_TFPM042FMC   LIKE TFPM042FMC OCCURS 0 WITH HEADER LINE,
  GT_FREESEL      TYPE RSDS_TWHERE,


*- Internal structures ------------------------------------------------*
  GS_PRIE         LIKE PRI_PARAMS,                          "Error list
  GS_ARCE         LIKE ARC_PARAMS,
  GS_PRIL         LIKE PRI_PARAMS,     "Accompanying list
  GS_ARCL         LIKE ARC_PARAMS,
  GS_PRI1         LIKE ITCPO,          "Payment medium (1-5)
  GS_PRI3         LIKE ITCPO,
  GS_PRI5         LIKE PRI_PARAMS,
  GS_ARC5         LIKE ARC_PARAMS,
  GS_FPAYH        LIKE FPAYH,
  GS_DFPAYG       LIKE DFPAYG,
  GS_TFPM042F     LIKE TFPM042F,
  GS_TFPM042F_2   LIKE TFPM042F,
  GS_TFPM042FT    LIKE TFPM042FT,
  GS_TFPM042FF    LIKE TFPM042FF,
  GS_TFPM042FFC   LIKE TFPM042FFC,
  GS_TFPM042FD    LIKE TFPM042FD,
  GS_TFPM042FDC   LIKE TFPM042FDC,
  GS_VARIANT      LIKE DISVARIANT,

*- Help fields --------------------------------------------------------*
  GC_ANSWER(1)    TYPE C,              "Answer of popups
  GC_TEXT_PY3     LIKE ITCPO-TDTITLE,
  GC_FILESYSTEM   TYPE DFILESYST,
  GC_EXTNUMBER    TYPE BALNREXT,
  GC_MESSAGE_TEXT1 LIKE SY-MSGV1,
  GC_MESSAGE_TEXT2 LIKE SY-MSGV2,
  GC_MESSAGE_TEXT3 LIKE SY-MSGV3,
  GC_MESSAGE_TYPE  LIKE SY-MSGTY,
  GC_TOO_MANY_FILES TYPE BOOLE-BOOLE,

*- Flags --------------------------------------------------------------*
  GC_DD_PRENOTIF  TYPE X_DD_PRENOTIF,  "X direct debit prenotification
  GC_XFILE        LIKE BOOLE-BOOLE,    "X file creation (DTTYP = 01)
  GC_XFORMF       LIKE BOOLE-BOOLE,    "Format popup button?
  GC_XFORP        LIKE BOOLE-BOOLE,    "Format params maint?
  GC_XSELECT      LIKE BOOLE-BOOLE,    "Paym. data selected?
  GC_XPRESRV      LIKE BOOLE-BOOLE,    "Pre-service called?


*- Constants without initial value ------------------------------------*
  GC_ICON_FORM_OK(50) TYPE C,          "Format parameters
  GC_ICON_FORM_NO(50) TYPE C,
  GC_ICON_PRIN_OK(50) TYPE C,          "Print parameters
  GC_ICON_PRIN_NO(50) TYPE C.