*&---------------------------------------------------------------------*
*& Include          ZRHR_PRINT_LOG_ALV_SEL
*&---------------------------------------------------------------------*
select-options: pt_in    for gt_output-line NO-DISPLAY.
PARAMETERS : p_titre(50) no-display.
SELECTION-SCREEN BEGIN OF BLOCK FIELDS WITH FRAME TITLE TEXT-b01.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(6) TEXT-B02.
    PARAMETERS : p_f1(25) LOWER CASE.
    SELECTION-SCREEN COMMENT 34(6) TEXT-B03.
    PARAMETERS : p_l1 TYPE I.
    SELECTION-SCREEN COMMENT 56(13) TEXT-B21.
    PARAMETERS : p_reft1(20).
    PARAMETERS : p_reff1(20).
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(6) TEXT-B04.
    PARAMETERS : p_f2(25) LOWER CASE.
    SELECTION-SCREEN COMMENT 34(6) TEXT-B03.
    PARAMETERS : p_l2 TYPE I.
    SELECTION-SCREEN COMMENT 56(13) TEXT-B21.
    PARAMETERS : p_reft2(20).
    PARAMETERS : p_reff2(20).
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(6) TEXT-B05.
    PARAMETERS : p_f3(25) LOWER CASE.
    SELECTION-SCREEN COMMENT 34(6) TEXT-B03.
    PARAMETERS : p_l3 TYPE I.
    SELECTION-SCREEN COMMENT 56(13) TEXT-B21.
    PARAMETERS : p_reft3(20).
    PARAMETERS : p_reff3(20).
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(6) TEXT-B06.
    PARAMETERS : p_f4(25) LOWER CASE.
    SELECTION-SCREEN COMMENT 34(6) TEXT-B03.
    PARAMETERS : p_l4 TYPE I.
    SELECTION-SCREEN COMMENT 56(13) TEXT-B21.
    PARAMETERS : p_reft4(20).
    PARAMETERS : p_reff4(20).
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(6) TEXT-B07.
    PARAMETERS : p_f5(25) LOWER CASE.
    SELECTION-SCREEN COMMENT 34(6) TEXT-B03.
    PARAMETERS : p_l5 TYPE I.
    SELECTION-SCREEN COMMENT 56(13) TEXT-B21.
    PARAMETERS : p_reft5(20).
    PARAMETERS : p_reff5(20).
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(6) TEXT-B08.
    PARAMETERS : p_f6(25) LOWER CASE.
    SELECTION-SCREEN COMMENT 34(6) TEXT-B03.
    PARAMETERS : p_l6 TYPE I.
    SELECTION-SCREEN COMMENT 56(13) TEXT-B21.
    PARAMETERS : p_reft6(20).
    PARAMETERS : p_reff6(20).
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(6) TEXT-B09.
    PARAMETERS : p_f7(25) LOWER CASE.
    SELECTION-SCREEN COMMENT 34(6) TEXT-B03.
    PARAMETERS : p_l7 TYPE I.
    SELECTION-SCREEN COMMENT 56(13) TEXT-B21.
    PARAMETERS : p_reft7(20).
    PARAMETERS : p_reff7(20).
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(6) TEXT-B10.
    PARAMETERS : p_f8(25) LOWER CASE.
    SELECTION-SCREEN COMMENT 34(6) TEXT-B03.
    PARAMETERS : p_l8 TYPE I.
    SELECTION-SCREEN COMMENT 56(13) TEXT-B21.
    PARAMETERS : p_reft8(20).
    PARAMETERS : p_reff8(20).
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(6) TEXT-B11.
    PARAMETERS : p_f9(25) LOWER CASE.
    SELECTION-SCREEN COMMENT 34(6) TEXT-B03.
    PARAMETERS : p_l9 TYPE I.
    SELECTION-SCREEN COMMENT 56(13) TEXT-B21.
    PARAMETERS : p_reft9(20).
    PARAMETERS : p_reff9(20).
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(6) TEXT-B12.
    PARAMETERS : p_f10(25) LOWER CASE.
    SELECTION-SCREEN COMMENT 34(6) TEXT-B03.
    PARAMETERS : p_l10 TYPE I.
    SELECTION-SCREEN COMMENT 56(13) TEXT-B21.
    PARAMETERS : p_reft10(20).
    PARAMETERS : p_reff10(20).
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(6) TEXT-B13.
    PARAMETERS : p_f11(25) LOWER CASE.
    SELECTION-SCREEN COMMENT 34(6) TEXT-B03.
    PARAMETERS : p_l11 TYPE I.
    SELECTION-SCREEN COMMENT 56(13) TEXT-B21.
    PARAMETERS : p_reft11(20).
    PARAMETERS : p_reff11(20).
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(6) TEXT-B14.
    PARAMETERS : p_f12(25) LOWER CASE.
    SELECTION-SCREEN COMMENT 34(6) TEXT-B03.
    PARAMETERS : p_l12 TYPE I.
    SELECTION-SCREEN COMMENT 56(13) TEXT-B21.
    PARAMETERS : p_reft12(20).
    PARAMETERS : p_reff12(20).
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(6) TEXT-B15.
    PARAMETERS : p_f13(25) LOWER CASE.
    SELECTION-SCREEN COMMENT 34(6) TEXT-B03.
    PARAMETERS : p_l13 TYPE I.
    SELECTION-SCREEN COMMENT 56(13) TEXT-B21.
    PARAMETERS : p_reft13(20).
    PARAMETERS : p_reff13(20).
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(6) TEXT-B16.
    PARAMETERS : p_f14(25) LOWER CASE.
    SELECTION-SCREEN COMMENT 34(6) TEXT-B03.
    PARAMETERS : p_l14 TYPE I.
    SELECTION-SCREEN COMMENT 56(13) TEXT-B21.
    PARAMETERS : p_reft14(20).
    PARAMETERS : p_reff14(20).
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(6) TEXT-B17.
    PARAMETERS : p_f15(25) LOWER CASE.
    SELECTION-SCREEN COMMENT 34(6) TEXT-B03.
    PARAMETERS : p_l15 TYPE I.
    SELECTION-SCREEN COMMENT 56(13) TEXT-B21.
    PARAMETERS : p_reft15(20).
    PARAMETERS : p_reff15(20).
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(10) TEXT-B23.
    parameters : p_separ(1).
  SELECTION-SCREEN END OF LINE.
*Column is a checkbox
 PARAMETERS : p_chck1(1) no-display,
              p_chck2(1) no-display,
              p_chck3(1) no-display,
              p_chck4(1) no-display,
              p_chck5(1) no-display,
              p_chck6(1) no-display,
              p_chck7(1) no-display,
              p_chck8(1) no-display,
              p_chck9(1) no-display,
              p_chck10(1) no-display,
              p_chck11(1) no-display,
              p_chck12(1) no-display,
              p_chck13(1) no-display,
              p_chck14(1) no-display,
              p_chck15(1) no-display.
SELECTION-SCREEN END OF BLOCK FIELDS.
SELECTION-SCREEN BEGIN OF BLOCK ZONESTEST WITH FRAME TITLE text-b20.
parameters :  p_line1(100),
              P_line2(100),
              P_line3(100),
              p_Line4(100).
SELECTION-SCREEN END OF BLOCK ZONESTEST.