*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZWF_GET_CERTIFYING_OFFICERU01.
                    "Z_WF_GET_CERTIFYING_OFFICER
INCLUDE LZWF_GET_CERTIFYING_OFFICERU02.
                    "Z_GET_CERTIF_OFFICER_UNESDIR
INCLUDE LZWF_GET_CERTIFYING_OFFICERU03.
                    "Z_UBC_USER_GET_BY_EMAIL