ENHANCEMENT 1  .

  IF SY-TCODE =  'FMZZ'.
    TESTLAUF = 'X'.
    TYPES: BEGIN OF LTY_KBLP,
             GEBER TYPE KBLP-GEBER,
             GSBER TYPE KBLP-GSBER,
           END OF LTY_KBLP.
    DATA YYLS_KBLP TYPE LTY_KBLP.
    DATA YYLO_BR_EXCHANGE_RATE TYPE REF TO YCL_FM_BR_EXCHANGE_RATE_BL.
    YYLO_BR_EXCHANGE_RATE = YCL_FM_BR_EXCHANGE_RATE_BL=>GET_INSTANCE( ).
    IF YYLO_BR_EXCHANGE_RATE->CHECK_BR_IS_ACTIVE( ) = ABAP_TRUE.
      LOOP AT XREVALUATE  ASSIGNING FIELD-SYMBOL(<YYLS_XREVALUATE>).
        SELECT SINGLE GEBER, GSBER FROM KBLP WHERE BELNR = @<YYLS_XREVALUATE>-BELNR
                                             AND   BLPOS = @<YYLS_XREVALUATE>-BLPOS
                 INTO CORRESPONDING FIELDS OF @YYLS_KBLP.

        IF <YYLS_XREVALUATE>-BUKRS = 'UNES' AND <YYLS_XREVALUATE>-WAERS  NE 'EUR'.
          DELETE   XREVALUATE.
        ELSEIF YYLS_KBLP-GSBER NE 'GEF'.
          DELETE   XREVALUATE.
        ELSEIF YYLO_BR_EXCHANGE_RATE->CHECK_CONDITIONS_3( IV_FTYPE = YYLO_BR_EXCHANGE_RATE->GET_FUND_TYPE_FROM_FUND(
                                                          IV_FIKRS = <YYLS_XREVALUATE>-BUKRS
                                                          IV_FINCODE = YYLS_KBLP-GEBER ) ) = ABAP_TRUE.
          DELETE XREVALUATE.
        ENDIF.
      ENDLOOP.
    ENDIF.
  ENDIF.

ENDENHANCEMENT.