ENHANCEMENT 1  .
  DATA YYLO_BR_PAYROLL_POSTING_BL TYPE REF TO YCL_FM_BR_PAYROLL_POSTING_BL.
  YYLO_BR_PAYROLL_POSTING_BL = YCL_FM_BR_PAYROLL_POSTING_BL=>GET_INSTANCE( ).
  YYLO_BR_PAYROLL_POSTING_BL->SET_ACCOUNT_DATA( IT_ACCOUNTGL = ACCOUNTGL[]
                                                IT_ACCOUNTAMOUNT = CURRENCYAMOUNT[] ).
ENDENHANCEMENT.