*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZ_WF_FI_EXCLUDE_NOTIFU01.
                    "Z_WF_FI_EXCLUDE_NOTIF_EMAIL