class ZCL_ZHCMFAB_MYFAMILYME_MPC definition
  public
  inheriting from /IWBEP/CL_MGW_PUSH_ABS_MODEL
  create public .
public section.
  types:
    begin of OTHERADDRESSEDITABILITY,
        IS_EDITABLE type FLAG,
        FIELD_NAME type string,
    end of OTHERADDRESSEDITABILITY .
  types:
   begin of ts_text_element,
      artifact_name  type c length 40,       " technical name
      artifact_type  type c length 4,
      parent_artifact_name type c length 40, " technical name
      parent_artifact_type type c length 4,
      text_symbol    type textpoolky,
   end of ts_text_element .
  types:
         tt_text_elements type standard table of ts_text_element with key text_symbo
  types:
    begin of TAIWAN42MINGUO,
        PTW_MINGUO1 type /IWBEP/SB_ODATA_TY_INT2,
        GBMON type /IWBEP/SB_ODATA_TY_INT2,
        GBTAG type /IWBEP/SB_ODATA_TY_INT2,
    end of TAIWAN42MINGUO .
  types:
    begin of TERYTATTRIBUTES,
        TERY0 type string,
        TERY1 type string,
    end of TERYTATTRIBUTES .
  types:
    begin of TS_FI46_CALCULATETERYT,
        COUNC type string,
        STATE type string,
        TERY2 type string,
    end of TS_FI46_CALCULATETERYT .
  types:
    begin of TS_FI46_EDITOTHERADDRESS,
        CNADR type string,
    end of TS_FI46_EDITOTHERADDRESS .
  types:
    begin of TS_FI42_CALCULATEMINGUO,
        BEGDA type TIMESTAMPL,
    end of TS_FI42_CALCULATEMINGUO .
  types:
     TS_FAMILYMEMBERUN type HCMFAB_S_PERS_FAMILYMEMBER_UN .
  types:
TT_FAMILYMEMBERUN type standard table of TS_FAMILYMEMBERUN .
  types:
     TS_FAMILYMEMBERUNDEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_UN .
  types:
TT_FAMILYMEMBERUNDEFAULT type standard table of TS_FAMILYMEMBERUNDEFAULT .
  types:
     TS_FAMILYMEMBER type HCMFAB_S_PERS_FAMILYMEMBER .
  types:
TT_FAMILYMEMBER type standard table of TS_FAMILYMEMBER .
  types:
     TS_FAMILYMEMBER01 type HCMFAB_S_PERS_FAMILYMEMBER_01 .
  types:
TT_FAMILYMEMBER01 type standard table of TS_FAMILYMEMBER01 .
  types:
     TS_FAMILYMEMBER01DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_01 .
  types:
TT_FAMILYMEMBER01DEFAULT type standard table of TS_FAMILYMEMBER01DEFAULT .
  types:
     TS_FAMILYMEMBER02 type HCMFAB_S_PERS_FAMILYMEMBER_02 .
  types:
TT_FAMILYMEMBER02 type standard table of TS_FAMILYMEMBER02 .
  types:
     TS_FAMILYMEMBER02DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_02 .
  types:
TT_FAMILYMEMBER02DEFAULT type standard table of TS_FAMILYMEMBER02DEFAULT .
  types:
     TS_FAMILYMEMBER03 type HCMFAB_S_PERS_FAMILYMEMBER_03 .
  types:
TT_FAMILYMEMBER03 type standard table of TS_FAMILYMEMBER03 .
  types:
     TS_FAMILYMEMBER03DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_03 .
  types:
TT_FAMILYMEMBER03DEFAULT type standard table of TS_FAMILYMEMBER03DEFAULT .
  types:
     TS_FAMILYMEMBER04 type HCMFAB_S_PERS_FAMILYMEMBER_04 .
  types:
TT_FAMILYMEMBER04 type standard table of TS_FAMILYMEMBER04 .
  types:
     TS_FAMILYMEMBER04DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_04 .
  types:
TT_FAMILYMEMBER04DEFAULT type standard table of TS_FAMILYMEMBER04DEFAULT .
  types:
     TS_FAMILYMEMBER05 type HCMFAB_S_PERS_FAMILYMEMBER_05 .
  types:
TT_FAMILYMEMBER05 type standard table of TS_FAMILYMEMBER05 .
  types:
     TS_FAMILYMEMBER05DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_05 .
  types:
TT_FAMILYMEMBER05DEFAULT type standard table of TS_FAMILYMEMBER05DEFAULT .
  types:
     TS_FAMILYMEMBER06 type HCMFAB_S_PERS_FAMILYMEMBER_06 .
  types:
TT_FAMILYMEMBER06 type standard table of TS_FAMILYMEMBER06 .
  types:
     TS_FAMILYMEMBER06DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_06 .
  types:
TT_FAMILYMEMBER06DEFAULT type standard table of TS_FAMILYMEMBER06DEFAULT .
  types:
     TS_FAMILYMEMBER07 type HCMFAB_S_PERS_FAMILYMEMBER_07 .
  types:
TT_FAMILYMEMBER07 type standard table of TS_FAMILYMEMBER07 .
  types:
     TS_FAMILYMEMBER07DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_07 .
  types:
TT_FAMILYMEMBER07DEFAULT type standard table of TS_FAMILYMEMBER07DEFAULT .
  types:
     TS_FAMILYMEMBER08 type HCMFAB_S_PERS_FAMILYMEMBER_08 .
  types:
TT_FAMILYMEMBER08 type standard table of TS_FAMILYMEMBER08 .
  types:
     TS_FAMILYMEMBER08DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_08 .
  types:
TT_FAMILYMEMBER08DEFAULT type standard table of TS_FAMILYMEMBER08DEFAULT .
  types:
     TS_FAMILYMEMBER09 type HCMFAB_S_PERS_FAMILYMEMBER .
  types:
TT_FAMILYMEMBER09 type standard table of TS_FAMILYMEMBER09 .
  types:
     TS_FAMILYMEMBER09DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER .
  types:
TT_FAMILYMEMBER09DEFAULT type standard table of TS_FAMILYMEMBER09DEFAULT .
  types:
     TS_FAMILYMEMBER10 type HCMFAB_S_PERS_FAMILYMEMBER_10 .
  types:
TT_FAMILYMEMBER10 type standard table of TS_FAMILYMEMBER10 .
  types:
     TS_FAMILYMEMBER10DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_10 .
  types:
TT_FAMILYMEMBER10DEFAULT type standard table of TS_FAMILYMEMBER10DEFAULT .
  types:
     TS_FAMILYMEMBER11 type HCMFAB_S_PERS_FAMILYMEMBER .
  types:
TT_FAMILYMEMBER11 type standard table of TS_FAMILYMEMBER11 .
  types:
     TS_FAMILYMEMBER11DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER .
  types:
TT_FAMILYMEMBER11DEFAULT type standard table of TS_FAMILYMEMBER11DEFAULT .
  types:
     TS_FAMILYMEMBER12 type HCMFAB_S_PERS_FAMILYMEMBER_12 .
  types:
TT_FAMILYMEMBER12 type standard table of TS_FAMILYMEMBER12 .
  types:
     TS_FAMILYMEMBER12DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_12 .
  types:
TT_FAMILYMEMBER12DEFAULT type standard table of TS_FAMILYMEMBER12DEFAULT .
  types:
     TS_FAMILYMEMBER13 type HCMFAB_S_PERS_FAMILYMEMBER_13 .
  types:
TT_FAMILYMEMBER13 type standard table of TS_FAMILYMEMBER13 .
  types:
     TS_FAMILYMEMBER13DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_13 .
  types:
TT_FAMILYMEMBER13DEFAULT type standard table of TS_FAMILYMEMBER13DEFAULT .
  types:
     TS_FAMILYMEMBER14 type HCMFAB_S_PERS_FAMILYMEMBER_14 .
  types:
TT_FAMILYMEMBER14 type standard table of TS_FAMILYMEMBER14 .
  types:
     TS_FAMILYMEMBER14DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_14 .
  types:
TT_FAMILYMEMBER14DEFAULT type standard table of TS_FAMILYMEMBER14DEFAULT .
  types:
     TS_FAMILYMEMBER15 type HCMFAB_S_PERS_FAMILYMEMBER_15 .
  types:
TT_FAMILYMEMBER15 type standard table of TS_FAMILYMEMBER15 .
  types:
     TS_FAMILYMEMBER15DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_15 .
  types:
TT_FAMILYMEMBER15DEFAULT type standard table of TS_FAMILYMEMBER15DEFAULT .
  types:
     TS_FAMILYMEMBER16 type HCMFAB_S_PERS_FAMILYMEMBER .
  types:
TT_FAMILYMEMBER16 type standard table of TS_FAMILYMEMBER16 .
  types:
     TS_FAMILYMEMBER16DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER .
  types:
TT_FAMILYMEMBER16DEFAULT type standard table of TS_FAMILYMEMBER16DEFAULT .
  types:
     TS_FAMILYMEMBER17 type HCMFAB_S_PERS_FAMILYMEMBER_17 .
  types:
TT_FAMILYMEMBER17 type standard table of TS_FAMILYMEMBER17 .
  types:
     TS_FAMILYMEMBER17DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_17 .
  types:
TT_FAMILYMEMBER17DEFAULT type standard table of TS_FAMILYMEMBER17DEFAULT .
  types:
     TS_FAMILYMEMBER18 type HCMFAB_S_PERS_FAMILYMEMBER_18 .
  types:
TT_FAMILYMEMBER18 type standard table of TS_FAMILYMEMBER18 .
  types:
     TS_FAMILYMEMBER18DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_18 .
  types:
TT_FAMILYMEMBER18DEFAULT type standard table of TS_FAMILYMEMBER18DEFAULT .
  types:
     TS_FAMILYMEMBER19 type HCMFAB_S_PERS_FAMILYMEMBER_19 .
  types:
TT_FAMILYMEMBER19 type standard table of TS_FAMILYMEMBER19 .
  types:
     TS_FAMILYMEMBER19DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_19 .
  types:
TT_FAMILYMEMBER19DEFAULT type standard table of TS_FAMILYMEMBER19DEFAULT .
  types:
     TS_FAMILYMEMBER21 type HCMFAB_S_PERS_FAMILYMEMBER_21 .
  types:
TT_FAMILYMEMBER21 type standard table of TS_FAMILYMEMBER21 .
  types:
     TS_FAMILYMEMBER21DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_21 .
  types:
TT_FAMILYMEMBER21DEFAULT type standard table of TS_FAMILYMEMBER21DEFAULT .
  types:
     TS_FAMILYMEMBER22 type HCMFAB_S_PERS_FAMILYMEMBER_22 .
  types:
TT_FAMILYMEMBER22 type standard table of TS_FAMILYMEMBER22 .
  types:
     TS_FAMILYMEMBER22DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_22 .
  types:
TT_FAMILYMEMBER22DEFAULT type standard table of TS_FAMILYMEMBER22DEFAULT .
  types:
     TS_FAMILYMEMBER23 type HCMFAB_S_PERS_FAMILYMEMBER .
  types:
TT_FAMILYMEMBER23 type standard table of TS_FAMILYMEMBER23 .
  types:
     TS_FAMILYMEMBER23DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER .
  types:
TT_FAMILYMEMBER23DEFAULT type standard table of TS_FAMILYMEMBER23DEFAULT .
  types:
     TS_FAMILYMEMBER24 type HCMFAB_S_PERS_FAMILYMEMBER_24 .
  types:
TT_FAMILYMEMBER24 type standard table of TS_FAMILYMEMBER24 .
  types:
     TS_FAMILYMEMBER24DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_24 .
  types:
TT_FAMILYMEMBER24DEFAULT type standard table of TS_FAMILYMEMBER24DEFAULT .
  types:
     TS_FAMILYMEMBER25 type HCMFAB_S_PERS_FAMILYMEMBER_25 .
  types:
TT_FAMILYMEMBER25 type standard table of TS_FAMILYMEMBER25 .
  types:
     TS_FAMILYMEMBER25DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_25 .
  types:
TT_FAMILYMEMBER25DEFAULT type standard table of TS_FAMILYMEMBER25DEFAULT .
  types:
     TS_FAMILYMEMBER26 type HCMFAB_S_PERS_FAMILYMEMBER_26 .
  types:
TT_FAMILYMEMBER26 type standard table of TS_FAMILYMEMBER26 .
  types:
     TS_FAMILYMEMBER26DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_26 .
  types:
TT_FAMILYMEMBER26DEFAULT type standard table of TS_FAMILYMEMBER26DEFAULT .
  types:
     TS_FAMILYMEMBER27 type HCMFAB_S_PERS_FAMILYMEMBER_27 .
  types:
TT_FAMILYMEMBER27 type standard table of TS_FAMILYMEMBER27 .
  types:
     TS_FAMILYMEMBER27DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_27 .
  types:
TT_FAMILYMEMBER27DEFAULT type standard table of TS_FAMILYMEMBER27DEFAULT .
  types:
     TS_FAMILYMEMBER28 type HCMFAB_S_PERS_FAMILYMEMBER_28 .
  types:
TT_FAMILYMEMBER28 type standard table of TS_FAMILYMEMBER28 .
  types:
     TS_FAMILYMEMBER28DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_28 .
  types:
TT_FAMILYMEMBER28DEFAULT type standard table of TS_FAMILYMEMBER28DEFAULT .
  types:
     TS_FAMILYMEMBER29 type HCMFAB_S_PERS_FAMILYMEMBER_29 .
  types:
TT_FAMILYMEMBER29 type standard table of TS_FAMILYMEMBER29 .
  types:
     TS_FAMILYMEMBER29DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_29 .
  types:
TT_FAMILYMEMBER29DEFAULT type standard table of TS_FAMILYMEMBER29DEFAULT .
  types:
     TS_FAMILYMEMBER31 type HCMFAB_S_PERS_FAMILYMEMBER_31 .
  types:
TT_FAMILYMEMBER31 type standard table of TS_FAMILYMEMBER31 .
  types:
     TS_FAMILYMEMBER31DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_31 .
  types:
TT_FAMILYMEMBER31DEFAULT type standard table of TS_FAMILYMEMBER31DEFAULT .
  types:
     TS_FAMILYMEMBER32 type HCMFAB_S_PERS_FAMILYMEMBER_32 .
  types:
TT_FAMILYMEMBER32 type standard table of TS_FAMILYMEMBER32 .
  types:
     TS_FAMILYMEMBER32DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_32 .
  types:
TT_FAMILYMEMBER32DEFAULT type standard table of TS_FAMILYMEMBER32DEFAULT .
  types:
     TS_FAMILYMEMBER33 type HCMFAB_S_PERS_FAMILYMEMBER_33 .
  types:
TT_FAMILYMEMBER33 type standard table of TS_FAMILYMEMBER33 .
  types:
     TS_FAMILYMEMBER33DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_33 .
  types:
TT_FAMILYMEMBER33DEFAULT type standard table of TS_FAMILYMEMBER33DEFAULT .
  types:
     TS_FAMILYMEMBER34 type HCMFAB_S_PERS_FAMILYMEMBER_34 .
  types:
TT_FAMILYMEMBER34 type standard table of TS_FAMILYMEMBER34 .
  types:
     TS_FAMILYMEMBER34DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_34 .
  types:
TT_FAMILYMEMBER34DEFAULT type standard table of TS_FAMILYMEMBER34DEFAULT .
  types:
     TS_FAMILYMEMBER36 type HCMFAB_S_PERS_FAMILYMEMBER_36 .
  types:
TT_FAMILYMEMBER36 type standard table of TS_FAMILYMEMBER36 .
  types:
     TS_FAMILYMEMBER36DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_36 .
  types:
TT_FAMILYMEMBER36DEFAULT type standard table of TS_FAMILYMEMBER36DEFAULT .
  types:
     TS_FAMILYMEMBER37 type HCMFAB_S_PERS_FAMILYMEMBERS_37 .
  types:
TT_FAMILYMEMBER37 type standard table of TS_FAMILYMEMBER37 .
  types:
     TS_FAMILYMEMBER37DEFAULT type HCMFAB_S_PERS_FAMILYMEMBERS_37 .
  types:
TT_FAMILYMEMBER37DEFAULT type standard table of TS_FAMILYMEMBER37DEFAULT .
  types:
     TS_FAMILYMEMBER38 type HCMFAB_S_PERS_FAMILYMEMBER_38 .
  types:
TT_FAMILYMEMBER38 type standard table of TS_FAMILYMEMBER38 .
  types:
     TS_FAMILYMEMBER38DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_38 .
  types:
TT_FAMILYMEMBER38DEFAULT type standard table of TS_FAMILYMEMBER38DEFAULT .
  types:
     TS_FAMILYMEMBER39 type HCMFAB_S_PERS_FAMILYMEMBER_39 .
  types:
TT_FAMILYMEMBER39 type standard table of TS_FAMILYMEMBER39 .
  types:
     TS_FAMILYMEMBER39DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_39 .
  types:
TT_FAMILYMEMBER39DEFAULT type standard table of TS_FAMILYMEMBER39DEFAULT .
  types:
     TS_FAMILYMEMBER40 type HCMFAB_S_PERS_FAMILYMEMBERS_40 .
  types:
TT_FAMILYMEMBER40 type standard table of TS_FAMILYMEMBER40 .
  types:
     TS_FAMILYMEMBER40DEFAULT type HCMFAB_S_PERS_FAMILYMEMBERS_40 .
  types:
TT_FAMILYMEMBER40DEFAULT type standard table of TS_FAMILYMEMBER40DEFAULT .
  types:
     TS_FAMILYMEMBER41 type HCMFAB_S_PERS_FAMILYMEMBER_41 .
  types:
TT_FAMILYMEMBER41 type standard table of TS_FAMILYMEMBER41 .
  types:
     TS_FAMILYMEMBER41DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_41 .
  types:
TT_FAMILYMEMBER41DEFAULT type standard table of TS_FAMILYMEMBER41DEFAULT .
  types:
     TS_FAMILYMEMBER42 type HCMFAB_S_PERS_FAMILYMEMBER_42 .
  types:
TT_FAMILYMEMBER42 type standard table of TS_FAMILYMEMBER42 .
  types:
     TS_FAMILYMEMBER42DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_42 .
  types:
TT_FAMILYMEMBER42DEFAULT type standard table of TS_FAMILYMEMBER42DEFAULT .
  types:
     TS_FAMILYMEMBER43 type HCMFAB_S_PERS_FAMILYMEMBER .
  types:
TT_FAMILYMEMBER43 type standard table of TS_FAMILYMEMBER43 .
  types:
     TS_FAMILYMEMBER43DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER .
  types:
TT_FAMILYMEMBER43DEFAULT type standard table of TS_FAMILYMEMBER43DEFAULT .
  types:
     TS_FAMILYMEMBER44 type HCMFAB_S_PERS_FAMILYMEMBER .
  types:
TT_FAMILYMEMBER44 type standard table of TS_FAMILYMEMBER44 .
  types:
     TS_FAMILYMEMBER44DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER .
  types:
TT_FAMILYMEMBER44DEFAULT type standard table of TS_FAMILYMEMBER44DEFAULT .
  types:
     TS_FAMILYMEMBER45 type HCMFAB_S_PERS_FAMILYMEMBER_45 .
  types:
TT_FAMILYMEMBER45 type standard table of TS_FAMILYMEMBER45 .
  types:
     TS_FAMILYMEMBER45DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_45 .
  types:
TT_FAMILYMEMBER45DEFAULT type standard table of TS_FAMILYMEMBER45DEFAULT .
  types:
     TS_FAMILYMEMBER46 type HCMFAB_S_PERS_FAMILYMEMBER_46 .
  types:
TT_FAMILYMEMBER46 type standard table of TS_FAMILYMEMBER46 .
  types:
     TS_FAMILYMEMBER46DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_46 .
  types:
TT_FAMILYMEMBER46DEFAULT type standard table of TS_FAMILYMEMBER46DEFAULT .
  types:
     TS_FAMILYMEMBER47 type HCMFAB_S_PERS_FAMILYMEMBER_47 .
  types:
TT_FAMILYMEMBER47 type standard table of TS_FAMILYMEMBER47 .
  types:
     TS_FAMILYMEMBER47DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_47 .
  types:
TT_FAMILYMEMBER47DEFAULT type standard table of TS_FAMILYMEMBER47DEFAULT .
  types:
     TS_FAMILYMEMBER48 type HCMFAB_S_PERS_FAMILYMEMBER_48 .
  types:
TT_FAMILYMEMBER48 type standard table of TS_FAMILYMEMBER48 .
  types:
     TS_FAMILYMEMBER48DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_48 .
  types:
TT_FAMILYMEMBER48DEFAULT type standard table of TS_FAMILYMEMBER48DEFAULT .
  types:
     TS_FAMILYMEMBER58 type HCMFAB_S_PERS_FAMILYMEMBER .
  types:
TT_FAMILYMEMBER58 type standard table of TS_FAMILYMEMBER58 .
  types:
     TS_FAMILYMEMBER58DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER .
  types:
TT_FAMILYMEMBER58DEFAULT type standard table of TS_FAMILYMEMBER58DEFAULT .
  types:
     TS_FAMILYMEMBER61 type HCMFAB_S_PERS_FAMILYMEMBER_61 .
  types:
TT_FAMILYMEMBER61 type standard table of TS_FAMILYMEMBER61 .
  types:
     TS_FAMILYMEMBER61DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_61 .
  types:
TT_FAMILYMEMBER61DEFAULT type standard table of TS_FAMILYMEMBER61DEFAULT .
  types:
     TS_FAMILYMEMBER62 type HCMFAB_S_PERS_FAMILYMEMBER_62 .
  types:
TT_FAMILYMEMBER62 type standard table of TS_FAMILYMEMBER62 .
  types:
     TS_FAMILYMEMBER62DEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_62 .
  types:
TT_FAMILYMEMBER62DEFAULT type standard table of TS_FAMILYMEMBER62DEFAULT .
  types:
     TS_FAMILYMEMBERAE type HCMFAB_S_PERS_FAMILYMEMBER_AE .
  types:
TT_FAMILYMEMBERAE type standard table of TS_FAMILYMEMBERAE .
  types:
     TS_FAMILYMEMBERAEDEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_AE .
  types:
TT_FAMILYMEMBERAEDEFAULT type standard table of TS_FAMILYMEMBERAEDEFAULT .
  types:
     TS_FAMILYMEMBERBG type HCMFAB_S_PERS_FAMILYMEMBER_BG .
  types:
TT_FAMILYMEMBERBG type standard table of TS_FAMILYMEMBERBG .
  types:
     TS_FAMILYMEMBERBGDEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_BG .
  types:
TT_FAMILYMEMBERBGDEFAULT type standard table of TS_FAMILYMEMBERBGDEFAULT .
  types:
     TS_FAMILYMEMBERDEFAULT type HCMFAB_S_PERS_FAMILYMEMBER .
  types:
TT_FAMILYMEMBERDEFAULT type standard table of TS_FAMILYMEMBERDEFAULT .
  types:
     TS_FAMILYMEMBERKW type HCMFAB_S_PERS_FAMILYMEMBER_KW .
  types:
TT_FAMILYMEMBERKW type standard table of TS_FAMILYMEMBERKW .
  types:
     TS_FAMILYMEMBERKWDEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_KW .
  types:
TT_FAMILYMEMBERKWDEFAULT type standard table of TS_FAMILYMEMBERKWDEFAULT .
  types:
     TS_FAMILYMEMBEROM type HCMFAB_S_PERS_FAMILYMEMBER_OM .
  types:
TT_FAMILYMEMBEROM type standard table of TS_FAMILYMEMBEROM .
  types:
     TS_FAMILYMEMBEROMDEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_OM .
  types:
TT_FAMILYMEMBEROMDEFAULT type standard table of TS_FAMILYMEMBEROMDEFAULT .
  types:
     TS_FAMILYMEMBERQA type HCMFAB_S_PERS_FAMILYMEMBER_QA .
  types:
TT_FAMILYMEMBERQA type standard table of TS_FAMILYMEMBERQA .
  types:
     TS_FAMILYMEMBERQADEFAULT type HCMFAB_S_PERS_FAMILYMEMBER_QA .
  types:
TT_FAMILYMEMBERQADEFAULT type standard table of TS_FAMILYMEMBERQADEFAULT .
  types:
     TS_FIELDMETADATA type HCMFAB_S_PERS_FIELDMETADATA .
  types:
TT_FIELDMETADATA type standard table of TS_FIELDMETADATA .
  types:
     TS_MAPPEDVERSIONID type HCMFAB_S_PERS_CUSTZ_VI .
  types:
TT_MAPPEDVERSIONID type standard table of TS_MAPPEDVERSIONID .
  types:
  begin of TS_SEARCHHELPDEPENDENTLIVING,
     FAVSV type C length 4,
     OBVBV type C length 2,
     SUBTY type C length 4,
     STEXT type C length 40,
     OBJPS type C length 2,
     FORMATTED_NAME type C length 40,
     FGBDT type TIMESTAMPL,
  end of TS_SEARCHHELPDEPENDENTLIVING .
  types:
TT_SEARCHHELPDEPENDENTLIVING type standard table of TS_SEARCHHELPDEPENDENTLIVING .
  types:
  begin of TS_SEARCHHELPHIGROUP,
     ZKVGP type C length 2,
     PKLAS type C length 2,
     TXPK2 type C length 20,
  end of TS_SEARCHHELPHIGROUP .
  types:
TT_SEARCHHELPHIGROUP type standard table of TS_SEARCHHELPHIGROUP .
  types:
     TS_SUBTYPEATTRIBUTES type HCMFAB_S_PERS_SUBTYPEATTRIBS .
  types:
TT_SUBTYPEATTRIBUTES type standard table of TS_SUBTYPEATTRIBUTES .
  types:
     TS_VALIDITYINFO type HCMFAB_S_PERS_VALIDITY .
  types:
TT_VALIDITYINFO type standard table of TS_VALIDITYINFO .
  types:
     TS_VALUEHELPACADEMICDEGREE type HCMFAB_S_PERS_VH_ACADEMICGRAD .
  types:
TT_VALUEHELPACADEMICDEGREE type standard table of TS_VALUEHELPACADEMICDEGREE .
  types:
     TS_VALUEHELPADDITIONALTITLE type HCMFAB_S_PERS_VH_ADD_TITLE .
  types:
TT_VALUEHELPADDITIONALTITLE type standard table of TS_VALUEHELPADDITIONALTITLE .
  types:
     TS_VALUEHELPADDRESSTYPE type HCMFAB_S_PERS_VH_ADDRTYPEPETE .
  types:
TT_VALUEHELPADDRESSTYPE type standard table of TS_VALUEHELPADDRESSTYPE .
  types:
     TS_VALUEHELPBLOODGROUP type HCMFAB_S_PERS_VH_BLOODGROUP .
  types:
TT_VALUEHELPBLOODGROUP type standard table of TS_VALUEHELPBLOODGROUP .
  types:
     TS_VALUEHELPCHALLENGE type HCMFAB_S_PERS_VH_CHALLENGE .
  types:
TT_VALUEHELPCHALLENGE type standard table of TS_VALUEHELPCHALLENGE .
  types:
     TS_VALUEHELPCHILDTYPE type HCMFAB_S_PERS_VH_CHILDTYPE .
  types:
TT_VALUEHELPCHILDTYPE type standard table of TS_VALUEHELPCHILDTYPE .
  types:
     TS_VALUEHELPCOHABITATION type HCMFAB_S_PERS_VH_COHABITATION .
  types:
TT_VALUEHELPCOHABITATION type standard table of TS_VALUEHELPCOHABITATION .
  types:
     TS_VALUEHELPCOMMUNICATIONMODE type HCMFAB_S_PERS_VH_COMMMODE .
  types:
TT_VALUEHELPCOMMUNICATIONMODE type standard table of TS_VALUEHELPCOMMUNICATIONMODE .
  types:
     TS_VALUEHELPCOMMUNICATIONTYPE type HCMFAB_S_PERS_VH_COMMTYPE .
  types:
TT_VALUEHELPCOMMUNICATIONTYPE type standard table of TS_VALUEHELPCOMMUNICATIONTYPE .
  types:
     TS_VALUEHELPCOMPANY type HCMFAB_S_PERS_VH_COMPANY .
  types:
TT_VALUEHELPCOMPANY type standard table of TS_VALUEHELPCOMPANY .
  types:
     TS_VALUEHELPCOUNTRY type HCMFAB_S_PERS_VH_COUNTRY .
  types:
TT_VALUEHELPCOUNTRY type standard table of TS_VALUEHELPCOUNTRY .
  types:
     TS_VALUEHELPCOUNTY type HCMFAB_S_PERS_VH_COUNTY .
  types:
TT_VALUEHELPCOUNTY type standard table of TS_VALUEHELPCOUNTY .
  types:
     TS_VALUEHELPCURRENCY type HCMFAB_S_PERS_VH_CURRENCY .
  types:
TT_VALUEHELPCURRENCY type standard table of TS_VALUEHELPCURRENCY .
  types:
     TS_VALUEHELPDEDUCTIONDEPENDENT type HCMFAB_S_PERS_VH_DEDUCTDEPEND .
  types:
TT_VALUEHELPDEDUCTIONDEPENDENT type standard table of TS_VALUEHELPDEDUCTIONDEPENDENT
  types:
     TS_VALUEHELPDEDUCTIONDISABILIT type HCMFAB_S_PERS_VH_DEDUCTDISABL .
  types:
TT_VALUEHELPDEDUCTIONDISABILIT type standard table of TS_VALUEHELPDEDUCTIONDISABILIT
  types:
     TS_VALUEHELPDEDUCTIONELDERLY type HCMFAB_S_PERS_VH_DEDUCTELDERLY .
  types:
TT_VALUEHELPDEDUCTIONELDERLY type standard table of TS_VALUEHELPDEDUCTIONELDERLY .
  types:
     TS_VALUEHELPDEDUCTIONHEALTH type HCMFAB_S_PERS_VH_DEDUCTHEALTH .
  types:
TT_VALUEHELPDEDUCTIONHEALTH type standard table of TS_VALUEHELPDEDUCTIONHEALTH .
  types:
     TS_VALUEHELPDEGREEBR type HCMFAB_S_PERS_VH_DEGREE_37 .
  types:
TT_VALUEHELPDEGREEBR type standard table of TS_VALUEHELPDEGREEBR .
  types:
     TS_VALUEHELPDEGREEOFCHALLENGEE type HCMFAB_S_PERS_VH_CHALLENGE_04 .
  types:
TT_VALUEHELPDEGREEOFCHALLENGEE type standard table of TS_VALUEHELPDEGREEOFCHALLENGEE
  types:
     TS_VALUEHELPDEPENDANTTYPE type HCMFAB_S_PERS_VH_KRDEPENDTYPE .
  types:
TT_VALUEHELPDEPENDANTTYPE type standard table of TS_VALUEHELPDEPENDANTTYPE .
  types:
     TS_VALUEHELPDEPENDENTLIVINGCL type HCMFAB_S_PERS_VH_DEPENDENT_LIV .
  types:
TT_VALUEHELPDEPENDENTLIVINGCL type standard table of TS_VALUEHELPDEPENDENTLIVINGCL .
  types:
     TS_VALUEHELPDISABILITYGRADE type HCMFAB_S_PERS_VH_DISABGRADE .
  types:
TT_VALUEHELPDISABILITYGRADE type standard table of TS_VALUEHELPDISABILITYGRADE .
  types:
     TS_VALUEHELPDISABILITYLEVEL type HCMFAB_S_PERS_VH_DISABILITYLEV .
  types:
TT_VALUEHELPDISABILITYLEVEL type standard table of TS_VALUEHELPDISABILITYLEVEL .
  types:
     TS_VALUEHELPDOCTYPE type HCMFAB_S_PERS_VH_DOCUMENTTYPE .
  types:
TT_VALUEHELPDOCTYPE type standard table of TS_VALUEHELPDOCTYPE .
  types:
     TS_VALUEHELPDOCUMENTTYPE type HCMFAB_S_PERS_VH_DOC_TYPE .
  types:
TT_VALUEHELPDOCUMENTTYPE type standard table of TS_VALUEHELPDOCUMENTTYPE .
  types:
     TS_VALUEHELPDUTYSTATION type HCMFAB_S_PERS_VH_DUTY_STATION .
  types:
TT_VALUEHELPDUTYSTATION type standard table of TS_VALUEHELPDUTYSTATION .
  types:
     TS_VALUEHELPEDUCATION type HCMFAB_S_PERS_VH_EDUCATION .
  types:
TT_VALUEHELPEDUCATION type standard table of TS_VALUEHELPEDUCATION .
  types:
     TS_VALUEHELPEDUCATIONALSPECIFI type HCMFAB_S_PERS_VH_EDUC_SPEC_37 .
  types:
TT_VALUEHELPEDUCATIONALSPECIFI type standard table of TS_VALUEHELPEDUCATIONALSPECIFI
  types:
     TS_VALUEHELPEMPLADDRESSCN type HCMFAB_S_PERS_VH_EMPLADDRESSCN .
  types:
TT_VALUEHELPEMPLADDRESSCN type standard table of TS_VALUEHELPEMPLADDRESSCN .
  types:
     TS_VALUEHELPEMPLOYERTYPE type HCMFAB_S_PERS_VH_EMPLOYER_TYPE .
  types:
TT_VALUEHELPEMPLOYERTYPE type standard table of TS_VALUEHELPEMPLOYERTYPE .
  types:
     TS_VALUEHELPEMPLOYMENTSTATUS type HCMFAB_S_PERS_VH_EMPLOYMENTSTA .
  types:
TT_VALUEHELPEMPLOYMENTSTATUS type standard table of TS_VALUEHELPEMPLOYMENTSTATUS .
  types:
     TS_VALUEHELPEMPLOYMENTTAXES type HCMFAB_S_PERS_VH_EMPL_TAX_04 .
  types:
TT_VALUEHELPEMPLOYMENTTAXES type standard table of TS_VALUEHELPEMPLOYMENTTAXES .
  types:
     TS_VALUEHELPETHNICORIGIN type HCMFAB_S_PERS_VH_ETHNICORIGIN .
  types:
TT_VALUEHELPETHNICORIGIN type standard table of TS_VALUEHELPETHNICORIGIN .
  types:
     TS_VALUEHELPFAMALLOWANCE type HCMFAB_S_PERS_VH_FAMILYALLOWAN .
  types:
TT_VALUEHELPFAMALLOWANCE type standard table of TS_VALUEHELPFAMALLOWANCE .
  types:
     TS_VALUEHELPFAMILYCHARIN type HCMFAB_S_PERS_VH_FAM_CHAR_40 .
  types:
TT_VALUEHELPFAMILYCHARIN type standard table of TS_VALUEHELPFAMILYCHARIN .
  types:
     TS_VALUEHELPFAMILYCHARACTERIST type HCMFAB_S_PERS_VH_FAMILY_CHAR .
  types:
TT_VALUEHELPFAMILYCHARACTERIST type standard table of TS_VALUEHELPFAMILYCHARACTERIST
  types:
     TS_VALUEHELPFAMILYCHARACTERIS type HCMFAB_S_PERS_VH_FLDVAL_TEXT .
  types:
TT_VALUEHELPFAMILYCHARACTERIS type standard table of TS_VALUEHELPFAMILYCHARACTERIS .
  types:
     TS_VALUEHELPFORMOFADDRESS type HCMFAB_S_PERS_VH_F_O_ADDRESS .
  types:
TT_VALUEHELPFORMOFADDRESS type standard table of TS_VALUEHELPFORMOFADDRESS .
  types:
     TS_VALUEHELPFORMOFADDRESSATEXT type HCMFAB_S_PERS_VH_FORMADDRATEXT .
  types:
TT_VALUEHELPFORMOFADDRESSATEXT type standard table of TS_VALUEHELPFORMOFADDRESSATEXT
  types:
     TS_VALUEHELPGENDER type HCMFAB_S_PERS_VH_GENDER .
  types:
TT_VALUEHELPGENDER type standard table of TS_VALUEHELPGENDER .
  types:
     TS_VALUEHELPGENDERDIVERSE type HCMFAB_S_PERS_VH_GENDERDIVERSE .
  types:
TT_VALUEHELPGENDERDIVERSE type standard table of TS_VALUEHELPGENDERDIVERSE .
  types:
     TS_VALUEHELPGRADEBR type HCMFAB_S_PERS_VH_GRADE_37 .
  types:
TT_VALUEHELPGRADEBR type standard table of TS_VALUEHELPGRADEBR .
  types:
     TS_VALUEHELPHANDICAPCODE type HCMFAB_S_PERS_VH_KRHANDICODE .
  types:
TT_VALUEHELPHANDICAPCODE type standard table of TS_VALUEHELPHANDICAPCODE .
  types:
     TS_VALUEHELPHEALTHINSURANCEPAI type HCMFAB_S_PERS_VH_HI_PAID_BY .
  types:
TT_VALUEHELPHEALTHINSURANCEPAI type standard table of TS_VALUEHELPHEALTHINSURANCEPAI
  types:
     TS_VALUEHELPHEALTHSTATUS type HCMFAB_S_PERS_VH_HEALTHSTATUS .
  types:
TT_VALUEHELPHEALTHSTATUS type standard table of TS_VALUEHELPHEALTHSTATUS .
  types:
     TS_VALUEHELPICTYPECN type HCMFAB_S_PERS_VH_ICTYPECN .
  types:
TT_VALUEHELPICTYPECN type standard table of TS_VALUEHELPICTYPECN .
  types:
     TS_VALUEHELPIDCHECK type HCMFAB_S_PERS_VH_IDCHECKTW .
  types:
TT_VALUEHELPIDCHECK type standard table of TS_VALUEHELPIDCHECK .
  types:
     TS_VALUEHELPILLNESSCODE type HCMFAB_S_PERS_VH_ILLNESSCODE .
  types:
TT_VALUEHELPILLNESSCODE type standard table of TS_VALUEHELPILLNESSCODE .
  types:
     TS_VALUEHELPINSTITUTE type HCMFAB_S_PERS_VH_INSTITUTE .
  types:
TT_VALUEHELPINSTITUTE type standard table of TS_VALUEHELPINSTITUTE .
  types:
     TS_VALUEHELPJOBSTATUSCN type HCMFAB_S_PERS_VH_JOBSTATUSCN .
  types:
TT_VALUEHELPJOBSTATUSCN type standard table of TS_VALUEHELPJOBSTATUSCN .
  types:
     TS_VALUEHELPLEGALNOMINEE type HCMFAB_S_PERS_VH_LEGAL_NOMINEE .
  types:
TT_VALUEHELPLEGALNOMINEE type standard table of TS_VALUEHELPLEGALNOMINEE .
  types:
     TS_VALUEHELPMARISTATFATXT type HCMFAB_S_PERS_VH_MARISTATFATXT .
  types:
TT_VALUEHELPMARISTATFATXT type standard table of TS_VALUEHELPMARISTATFATXT .
  types:
     TS_VALUEHELPMARITALSTATUS type HCMFAB_S_PERS_VH_MARITALSTATUS .
  types:
TT_VALUEHELPMARITALSTATUS type standard table of TS_VALUEHELPMARITALSTATUS .
  types:
     TS_VALUEHELPNHIEXREASON type HCMFAB_S_PERS_VH_NHIEXEMPTREAS .
  types:
TT_VALUEHELPNHIEXREASON type standard table of TS_VALUEHELPNHIEXREASON .
  types:
     TS_VALUEHELPNHIREASON type HCMFAB_S_PERS_VH_NHISTATREASON .
  types:
TT_VALUEHELPNHIREASON type standard table of TS_VALUEHELPNHIREASON .
  types:
     TS_VALUEHELPNHISTATUS type HCMFAB_S_PERS_VH_NHISTATUSTW .
  types:
TT_VALUEHELPNHISTATUS type standard table of TS_VALUEHELPNHISTATUS .
  types:
     TS_VALUEHELPNAMEFORMAT type HCMFAB_S_PERS_VH_NAMEFORMAT .
  types:
TT_VALUEHELPNAMEFORMAT type standard table of TS_VALUEHELPNAMEFORMAT .
  types:
     TS_VALUEHELPNAMEFORMATFKNZM type HCMFAB_S_PERS_VH_FKNZM .
  types:
TT_VALUEHELPNAMEFORMATFKNZM type standard table of TS_VALUEHELPNAMEFORMATFKNZM .
  types:
     TS_VALUEHELPNAMEPREFIX type HCMFAB_S_PERS_VH_TITLE .
  types:
TT_VALUEHELPNAMEPREFIX type standard table of TS_VALUEHELPNAMEPREFIX .
  types:
     TS_VALUEHELPNATION type HCMFAB_S_PERS_VH_NATION .
  types:
TT_VALUEHELPNATION type standard table of TS_VALUEHELPNATION .
  types:
     TS_VALUEHELPNATIONBR type HCMFAB_S_PERS_VH_NATION_37 .
  types:
TT_VALUEHELPNATIONBR type standard table of TS_VALUEHELPNATIONBR .
  types:
     TS_VALUEHELPNATIONFANAT type HCMFAB_S_PERS_VH_FANATLANDX .
  types:
TT_VALUEHELPNATIONFANAT type standard table of TS_VALUEHELPNATIONFANAT .
  types:
     TS_VALUEHELPNATIONFANAX type HCMFAB_S_PERS_VH_FANATFANAX .
  types:
TT_VALUEHELPNATIONFANAX type standard table of TS_VALUEHELPNATIONFANAX .
  types:
     TS_VALUEHELPOCCUPATION type HCMFAB_S_PERS_VH_OCCUPATION .
  types:
TT_VALUEHELPOCCUPATION type standard table of TS_VALUEHELPOCCUPATION .
  types:
     TS_VALUEHELPOCCUPATIONCN type HCMFAB_S_PERS_VH_OCCUPATIONCN .
  types:
TT_VALUEHELPOCCUPATIONCN type standard table of TS_VALUEHELPOCCUPATIONCN .
  types:
     TS_VALUEHELPORGANIZATION type HCMFAB_S_PERS_VH_ORG_KEY .
  types:
TT_VALUEHELPORGANIZATION type standard table of TS_VALUEHELPORGANIZATION .
  types:
     TS_VALUEHELPPARTNERINCOME type HCMFAB_S_PERS_VH_PARTNERINCOME .
  types:
TT_VALUEHELPPARTNERINCOME type standard table of TS_VALUEHELPPARTNERINCOME .
  types:
     TS_VALUEHELPPARTNERPROFESSION type HCMFAB_S_PERS_VH_PARTNERPROF .
  types:
TT_VALUEHELPPARTNERPROFESSION type standard table of TS_VALUEHELPPARTNERPROFESSION .
  types:
     TS_VALUEHELPPERSIDENTTYPE type HCMFAB_S_PERS_VH_PERSIDENTTYPE .
  types:
TT_VALUEHELPPERSIDENTTYPE type standard table of TS_VALUEHELPPERSIDENTTYPE .
  types:
     TS_VALUEHELPPOLITICALSTATUSCN type HCMFAB_S_PERS_VH_POLITSTATUSCN .
  types:
TT_VALUEHELPPOLITICALSTATUSCN type standard table of TS_VALUEHELPPOLITICALSTATUSCN .
  types:
     TS_VALUEHELPQUOTATYPE type HCMFAB_S_PERS_VH_QUOTA_TYPE_KW .
  types:
TT_VALUEHELPQUOTATYPE type standard table of TS_VALUEHELPQUOTATYPE .
  types:
     TS_VALUEHELPQUOTATYPEKW type HCMFAB_S_PERS_VH_QUOTA_TYPE_KW .
  types:
TT_VALUEHELPQUOTATYPEKW type standard table of TS_VALUEHELPQUOTATYPEKW .
  types:
     TS_VALUEHELPRELATTOEE type HCMFAB_S_PERS_VH_RELATIONTW .
  types:
TT_VALUEHELPRELATTOEE type standard table of TS_VALUEHELPRELATTOEE .
  types:
     TS_VALUEHELPRELATION type HCMFAB_S_PERS_VH_RELATION .
  types:
TT_VALUEHELPRELATION type standard table of TS_VALUEHELPRELATION .
  types:
     TS_VALUEHELPRELATIONKDBSL type HCMFAB_S_PERS_VH_RELATIONKDBSL .
  types:
TT_VALUEHELPRELATIONKDBSL type standard table of TS_VALUEHELPRELATIONKDBSL .
  types:
     TS_VALUEHELPRELATIONKDSVH type HCMFAB_S_PERS_VH_RELATIONKDSVH .
  types:
TT_VALUEHELPRELATIONKDSVH type standard table of TS_VALUEHELPRELATIONKDSVH .
  types:
     TS_VALUEHELPRESIDENCYTYPE type HCMFAB_S_PERS_VH_RESIDENCYTYPE .
  types:
TT_VALUEHELPRESIDENCYTYPE type standard table of TS_VALUEHELPRESIDENCYTYPE .
  types:
     TS_VALUEHELPSOCIALSECINST type HCMFAB_S_PERS_VH_SOCSECINSTIT .
  types:
TT_VALUEHELPSOCIALSECINST type standard table of TS_VALUEHELPSOCIALSECINST .
  types:
     TS_VALUEHELPSPOUSEINCOME type HCMFAB_S_PERS_VH_EMPLOYMENTSTA .
  types:
TT_VALUEHELPSPOUSEINCOME type standard table of TS_VALUEHELPSPOUSEINCOME .
  types:
     TS_VALUEHELPSPOUSETAXOFFICE type HCMFAB_S_PERS_VH_SPOUSETAXOFFI .
  types:
TT_VALUEHELPSPOUSETAXOFFICE type standard table of TS_VALUEHELPSPOUSETAXOFFICE .
  types:
     TS_VALUEHELPSTATE type HCMFAB_S_PERS_VH_STATE .
  types:
TT_VALUEHELPSTATE type standard table of TS_VALUEHELPSTATE .
  types:
     TS_VALUEHELPSTATUSHU type HCMFAB_S_PERS_VH_RELATION .
  types:
TT_VALUEHELPSTATUSHU type standard table of TS_VALUEHELPSTATUSHU .
  types:
     TS_VALUEHELPTTOUT type HCMFAB_S_PERS_VH_TITLE .
  types:
TT_VALUEHELPTTOUT type standard table of TS_VALUEHELPTTOUT .
  types:
     TS_VALUEHELPTAXSETTLEMENT type HCMFAB_S_PERS_VH_TAXSETTLEMENT .
  types:
TT_VALUEHELPTAXSETTLEMENT type standard table of TS_VALUEHELPTAXSETTLEMENT .
  types:
     TS_VALUEHELPTERYTMUNICIPALITY type HCMFAB_S_PERS_VH_TERYTMUNI .
  types:
TT_VALUEHELPTERYTMUNICIPALITY type standard table of TS_VALUEHELPTERYTMUNICIPALITY .
  types:
     TS_VALUEHELPTIPCA type HCMFAB_S_PERS_VH_TIPCA .
  types:
TT_VALUEHELPTIPCA type standard table of TS_VALUEHELPTIPCA .
  types:
     TS_VALUEHELPTITLE type HCMFAB_S_PERS_VH_TITLE .
  types:
TT_VALUEHELPTITLE type standard table of TS_VALUEHELPTITLE .
  types:
     TS_VALUEHELPTITLEFNMZU type HCMFAB_S_PERS_VH_TITLEFNMZU .
  types:
TT_VALUEHELPTITLEFNMZU type standard table of TS_VALUEHELPTITLEFNMZU .
  types:
     TS_VALUEHELPTITLETEXT type HCMFAB_S_PERS_VH_TITLE .
  types:
TT_VALUEHELPTITLETEXT type standard table of TS_VALUEHELPTITLETEXT .
  types:
     TS_VALUEHELPVALIDFROM type HCMFAB_S_PERS_VH_IDCHECKTW .
  types:
TT_VALUEHELPVALIDFROM type standard table of TS_VALUEHELPVALIDFROM .
  types:
     TS_VALUEHELPYEARENDADJUST type HCMFAB_S_PERS_VH_YEARENDADJUST .
  types:
TT_VALUEHELPYEARENDADJUST type standard table of TS_VALUEHELPYEARENDADJUST .
  types:
     TS_VALUEHELP_15COUNTRYOFBIRTH type HCMFAB_S_PERS_VH_15COUNTRY .
  types:
TT_VALUEHELP_15COUNTRYOFBIRTH type standard table of TS_VALUEHELP_15COUNTRYOFBIRTH .
  types:
     TS_VALUEHELP_21CHILDSTATUS type HCMFAB_S_PERS_VH_CHILDSTATUS .
  types:
TT_VALUEHELP_21CHILDSTATUS type standard table of TS_VALUEHELP_21CHILDSTATUS .
  types:
     TS_VALUEHELP_21EVENT type HCMFAB_S_PERS_VH_EVENT .
  types:
TT_VALUEHELP_21EVENT type standard table of TS_VALUEHELP_21EVENT .
  types:
     TS_VALUEHELP_21ILLNESSCODE type HCMFAB_S_PERS_VH_ILLNESSCODE .
  types:
TT_VALUEHELP_21ILLNESSCODE type standard table of TS_VALUEHELP_21ILLNESSCODE .
  types:
     TS_VALUEHELP_28NAMEFORMATID type HCMFAB_S_PERS_VH_NAMEFORMATCN .
  types:
TT_VALUEHELP_28NAMEFORMATID type standard table of TS_VALUEHELP_28NAMEFORMATID .
  types:
     TS_VALUEHELP_37CITYOFBIRTH type HCMFAB_S_PERS_VH_CITY_37 .
  types:
TT_VALUEHELP_37CITYOFBIRTH type standard table of TS_VALUEHELP_37CITYOFBIRTH .
  types:
     TS_VALUEHELP_39DEPLIVINGCODE type HCMFAB_S_PERS_VH_DEPLIVCODE_39 .
  types:
TT_VALUEHELP_39DEPLIVINGCODE type standard table of TS_VALUEHELP_39DEPLIVINGCODE .
  types:
     TS_VALUEHELP_42POSTALCODE type HCMFAB_S_PERS_VH_POSTALCODETW .
  types:
TT_VALUEHELP_42POSTALCODE type standard table of TS_VALUEHELP_42POSTALCODE .
  types:
     TS_VALUEHELP_QASCHOOL type HCMFAB_S_PERS_VH_SCHOOL .
  types:
TT_VALUEHELP_QASCHOOL type standard table of TS_VALUEHELP_QASCHOOL .
  constants GC_VALUEHELPDEGREEOFCHALLENGEE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_
  constants GC_VALUEHELPDEPENDANTTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_E
  constants GC_VALUEHELPDEPENDENTLIVINGCL type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_M
  constants GC_VALUEHELPDISABILITYGRADE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED
  constants GC_VALUEHELPDISABILITYLEVEL type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED
  constants GC_VALUEHELPDOCTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_
  constants GC_VALUEHELPDOCUMENTTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_VALUEHELPDUTYSTATION type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENT
  constants GC_VALUEHELPEDUCATION type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTIT
  constants GC_VALUEHELPEDUCATIONALSPECIFI type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_
  constants GC_VALUEHELPEMPLADDRESSCN type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_E
  constants GC_VALUEHELPEMPLOYERTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_VALUEHELPEMPLOYMENTSTATUS type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_ME
  constants GC_VALUEHELPEMPLOYMENTTAXES type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED
  constants GC_VALUEHELPETHNICORIGIN type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_VALUEHELPFAMALLOWANCE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_VALUEHELPFAMILYCHARACTERIS type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_M
  constants GC_VALUEHELPFAMILYCHARACTERIST type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_
  constants GC_VALUEHELPFAMILYCHARIN type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_VALUEHELPFORMOFADDRESS type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_E
  constants GC_VALUEHELPFORMOFADDRESSATEXT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_
  constants GC_VALUEHELPGENDER type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_N
  constants GC_VALUEHELPGENDERDIVERSE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_E
  constants GC_VALUEHELPGRADEBR type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_
  constants GC_VALUEHELPHANDICAPCODE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_VALUEHELPHEALTHINSURANCEPAI type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_
  constants GC_VALUEHELPHEALTHSTATUS type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FIELDMETADATA type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAM
  constants GC_MAPPEDVERSIONID type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_N
  constants GC_OTHERADDRESSEDITABILITY type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_
  constants GC_SEARCHHELPDEPENDENTLIVING type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_ME
  constants GC_SEARCHHELPHIGROUP type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY
  constants GC_SUBTYPEATTRIBUTES type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY
  constants GC_TAIWAN42MINGUO type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_TERYTATTRIBUTES type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_N
  constants GC_VALIDITYINFO type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME
  constants GC_VALUEHELPACADEMICDEGREE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_
  constants GC_VALUEHELPADDITIONALTITLE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED
  constants GC_VALUEHELPADDRESSTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENT
  constants GC_VALUEHELPBLOODGROUP type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTI
  constants GC_VALUEHELPCHALLENGE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTIT
  constants GC_VALUEHELPCHILDTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTIT
  constants GC_VALUEHELPCOHABITATION type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_VALUEHELPCOMMUNICATIONMODE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_M
  constants GC_VALUEHELPCOMMUNICATIONTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_M
  constants GC_VALUEHELPCOMPANY type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_
  constants GC_VALUEHELPCOUNTRY type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_
  constants GC_VALUEHELPCOUNTY type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_N
  constants GC_VALUEHELPCURRENCY type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY
  constants GC_VALUEHELPDEDUCTIONDEPENDENT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_
  constants GC_VALUEHELPDEDUCTIONDISABILIT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_
  constants GC_VALUEHELPDEDUCTIONELDERLY type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_ME
  constants GC_VALUEHELPDEDUCTIONHEALTH type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED
  constants GC_VALUEHELPDEGREEBR type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY
  constants GC_VALUEHELPICTYPECN type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY
  constants GC_VALUEHELPRELATIONKDBSL type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_E
  constants GC_VALUEHELPRELATIONKDSVH type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_E
  constants GC_VALUEHELPRELATTOEE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTIT
  constants GC_VALUEHELPRESIDENCYTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_E
  constants GC_VALUEHELPSOCIALSECINST type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_E
  constants GC_VALUEHELPSPOUSEINCOME type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_VALUEHELPSPOUSETAXOFFICE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED
  constants GC_VALUEHELPSTATE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_VALUEHELPSTATUSHU type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY
  constants GC_VALUEHELPTAXSETTLEMENT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_E
  constants GC_VALUEHELPTERYTMUNICIPALITY type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_M
  constants GC_VALUEHELPTIPCA type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_VALUEHELPTITLE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_VALUEHELPTITLEFNMZU type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTI
  constants GC_VALUEHELPTITLETEXT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTIT
  constants GC_VALUEHELPTTOUT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_VALUEHELPVALIDFROM type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTIT
  constants GC_VALUEHELPYEARENDADJUST type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_E
  constants GC_VALUEHELP_15COUNTRYOFBIRTH type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_M
  constants GC_VALUEHELP_21CHILDSTATUS type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_
  constants GC_VALUEHELP_21EVENT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY
  constants GC_VALUEHELP_21ILLNESSCODE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_
  constants GC_VALUEHELP_28NAMEFORMATID type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED
  constants GC_VALUEHELP_37CITYOFBIRTH type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_
  constants GC_VALUEHELP_39DEPLIVINGCODE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_ME
  constants GC_VALUEHELP_42POSTALCODE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_E
  constants GC_VALUEHELP_QASCHOOL type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTIT
  constants GC_VALUEHELPIDCHECK type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_
  constants GC_VALUEHELPILLNESSCODE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENT
  constants GC_VALUEHELPINSTITUTE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTIT
  constants GC_VALUEHELPJOBSTATUSCN type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENT
  constants GC_VALUEHELPLEGALNOMINEE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_VALUEHELPMARISTATFATXT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_E
  constants GC_VALUEHELPMARITALSTATUS type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_E
  constants GC_VALUEHELPNAMEFORMAT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTI
  constants GC_VALUEHELPNAMEFORMATFKNZM type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED
  constants GC_VALUEHELPNAMEPREFIX type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTI
  constants GC_VALUEHELPNATION type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_N
  constants GC_VALUEHELPNATIONBR type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY
  constants GC_VALUEHELPNATIONFANAT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENT
  constants GC_VALUEHELPNATIONFANAX type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENT
  constants GC_VALUEHELPNHIEXREASON type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENT
  constants GC_VALUEHELPNHIREASON type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTIT
  constants GC_VALUEHELPNHISTATUS type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTIT
  constants GC_VALUEHELPOCCUPATION type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTI
  constants GC_VALUEHELPOCCUPATIONCN type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_VALUEHELPORGANIZATION type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_VALUEHELPPARTNERINCOME type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_E
  constants GC_VALUEHELPPARTNERPROFESSION type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_M
  constants GC_VALUEHELPPERSIDENTTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_E
  constants GC_VALUEHELPPOLITICALSTATUSCN type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_M
  constants GC_VALUEHELPQUOTATYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTIT
  constants GC_VALUEHELPQUOTATYPEKW type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENT
  constants GC_VALUEHELPRELATION type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY
  constants GC_FAMILYMEMBERUNDEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER14DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER15 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER15DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER16 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER16DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER17 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER17DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER18 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER18DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER19 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER19DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER21 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER21DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER22 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER22DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER23 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER23DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER24 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER24DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER25 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER25DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER26 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER26DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER27 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER27DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER28 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER28DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER14 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME
  constants GC_FAMILYMEMBER01 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER01DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER02 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER02DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER03 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER03DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER04 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER04DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER05 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER05DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER06 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER06DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER07 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER07DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER08 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER08DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER09 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER09DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER10 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER10DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER11 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER11DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER12 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER12DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER13 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER13DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER44DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER45 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER45DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER46 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER46DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER47 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER47DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER48 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER48DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER58 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER58DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER61 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER61DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER62 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER62DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBERAE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBERAEDEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBERBG type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBERBGDEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBERDEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTI
  constants GC_FAMILYMEMBERKW type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBERKWDEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBEROM type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBEROMDEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBERQA type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBERQADEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBERUN type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER29 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER29DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER31 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER31DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER32 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER32DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER33 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER33DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER34 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER34DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER36 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER36DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER37 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER37DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER38 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER38DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER39 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER39DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER40 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER40DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER41 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER41DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER42 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER42DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER43 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  constants GC_FAMILYMEMBER43DEFAULT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_EN
  constants GC_FAMILYMEMBER44 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NA
  methods GET_EXTENDED_MODEL
  final
    exporting
      !EV_EXTENDED_SERVICE type /IWBEP/MED_GRP_TECHNICAL_NAME
      !EV_EXT_SERVICE_VERSION type /IWBEP/MED_GRP_VERSION
      !EV_EXTENDED_MODEL type /IWBEP/MED_MDL_TECHNICAL_NAME
      !EV_EXT_MODEL_VERSION type /IWBEP/MED_MDL_VERSION
    raising
      /IWBEP/CX_MGW_MED_EXCEPTION .
  methods LOAD_TEXT_ELEMENTS
  final
    returning
      value(RT_TEXT_ELEMENTS) type TT_TEXT_ELEMENTS
    raising
      /IWBEP/CX_MGW_MED_EXCEPTION .
  methods DEFINE
    redefinition .
  methods GET_LAST_MODIFIED
    redefinition .