  method IF_HCMFAB_ASR_PROCESS_CONFG~TABLE_BUTTON_HANDLING.
    LOOP AT IT_FIELD_METADATA into DATA(ls_metadata).

    ENDLOOP.

    LOOP AT ET_FIELD_METADATA_TT into DATA(ls_meta_tt).

    ENDLOOP.

  endmethod.
