REPORT Z_DMEE_EXIT_TAX_NUMBER========FT.
* 2.0
*
DATA: TIME1 TYPE P, TIME2 TYPE P, RUNTIME(30), DEBUG, ATRA.
DATA: RC LIKE SY-SUBRC , V_RC LIKE SY-SUBRC.
DATA: DESTI LIKE RFCDES-RFCDEST.
DATA: FIELDNAME LIKE SY-REPID.
DATA: G_UPPER TYPE C.         "Gross/Kleinschreibung
*
TABLES : EUFUNC.
DATA: BEGIN OF UNTERSCHIED,            " Unterschiede bei Testdur
        PARAMETER(30),
        ALT(200),
        NEU(200),                      " laufen
      END OF UNTERSCHIED.
*
DATA : D102N_EXPORTKEY LIKE FUNCTDIR.
*
DATA : BEGIN OF EXPORTKEY,
         DATAID LIKE EUFUNC-NUMMER,
         SEQID  LIKE EUFUNC-SEQID,
       END OF EXPORTKEY.
DATA : BEGIN OF EXCEPTIONS OCCURS 10,
         NAME(30),
       END OF EXCEPTIONS.
DATA : VEXCEPTION(30).
DATA : OEXCEPTION(30).
DATA : NR2(250) TYPE C.
DATA : TABLEN TYPE I.
DATA : EX TYPE REF TO CX_ROOT.
DATA : DESCR_REF TYPE REF TO CL_ABAP_TYPEDESCR.
DATA : RESULTAT(30) TYPE C.
DATA : REST(30)     TYPE C.
*
DATA: %_II_TREE_TYPE TYPE DMEE_TREETYPE_ABA.
DATA: %_II_TREE_ID TYPE DMEE_TREEID_ABA.
DATA: %_II_ITEM(200).
DATA: %_II_PARAM(200).
DATA: %_II_UPARAM(200).
DATA: %_II_EXTENSION TYPE DMEE_EXIT_INTERFACE_ABA.
DATA: %_OO_VALUE(200),
      %_VO_VALUE(200).
DATA: %_OC_VALUE(200),
      %_VC_VALUE(200).
DATA: %_ON_VALUE(200),
      %_VN_VALUE(200).
DATA: %_OP_VALUE(200),
      %_VP_VALUE(200).
DATA: BEGIN OF %_II_TAB OCCURS 1,
        DEFAULT(200),
      END OF %_II_TAB.
*
DATA: BEGIN OF %_OI_TAB OCCURS 1,
        DEFAULT(200),
      END OF %_OI_TAB.
*
DATA: BEGIN OF %_VI_TAB OCCURS 1,
        DEFAULT(200),
      END OF %_VI_TAB.
*
FORM EXISTENCE_CHECK CHANGING VARIA.
  VARIA = 1.
ENDFORM.
FORM FUNCTION_CALL.
  CLEAR %_OO_VALUE.
  CLEAR %_OC_VALUE.
  CLEAR %_ON_VALUE.
  CLEAR %_OP_VALUE.
CLEAR %_OI_TAB.
REFRESH %_OI_TAB.
LOOP AT %_II_TAB.
  %_OI_TAB = %_II_TAB.
  APPEND %_OI_TAB.
ENDLOOP.
*  TRANSAKTION = 'Repo', PROGRAM = REPORT
  IF ATRA = '1'.
    SET RUN TIME ANALYZER ON %_INTERNAL.
  ENDIF.
IF DESTI IS INITIAL.
IF DEBUG = '1'. BREAK-POINT AT NEXT APPLICATION STATEMENT.
ENDIF.
DEBUG = SPACE.
GET RUN TIME FIELD TIME1.
CALL FUNCTION 'Z_DMEE_EXIT_TAX_NUMBER'
EXPORTING
I_TREE_TYPE = %_II_TREE_TYPE
I_TREE_ID = %_II_TREE_ID
I_ITEM = %_II_ITEM
I_PARAM = %_II_PARAM
I_UPARAM = %_II_UPARAM
I_EXTENSION = %_II_EXTENSION
IMPORTING
O_VALUE = %_OO_VALUE
C_VALUE = %_OC_VALUE
N_VALUE = %_ON_VALUE
P_VALUE = %_OP_VALUE
TABLES
I_TAB = %_OI_TAB.
  IF ATRA = '1'.
    SET RUN TIME ANALYZER OFF %_INTERNAL.
  ENDIF.
ELSE.
GET RUN TIME FIELD TIME1.
*  TRANSAKTION = 'Repo', PROGRAM = REPORT
  IF ATRA = '1'.
    SET RUN TIME ANALYZER ON %_INTERNAL.
  ENDIF.
IF DESTI = 'SPACE'.
  DESTI = ' '.
ENDIF.
CALL FUNCTION 'Z_DMEE_EXIT_TAX_NUMBER' DESTINATION DESTI
EXPORTING
I_TREE_TYPE = %_II_TREE_TYPE
I_TREE_ID = %_II_TREE_ID
I_ITEM = %_II_ITEM
I_PARAM = %_II_PARAM
I_UPARAM = %_II_UPARAM
I_EXTENSION = %_II_EXTENSION
IMPORTING
O_VALUE = %_OO_VALUE
C_VALUE = %_OC_VALUE
N_VALUE = %_ON_VALUE
P_VALUE = %_OP_VALUE
TABLES
I_TAB = %_OI_TAB.
  IF ATRA = '1'.
    SET RUN TIME ANALYZER OFF %_INTERNAL.
  ENDIF.
  ENDIF.
  GET RUN TIME FIELD TIME2.
  RC = SY-SUBRC.
  CLEAR EXCEPTIONS.
  READ TABLE EXCEPTIONS INDEX RC.
  IF SY-SUBRC = 0.
  OEXCEPTION = EXCEPTIONS-NAME.
  ELSE.
  OEXCEPTION = RESULTAT.
  ENDIF.
  TIME1 = TIME2 - TIME1.
  WRITE TIME1 TO RUNTIME.
  CONDENSE RUNTIME.
ENDFORM.

FORM CLEAR_DATA.
  CLEAR %_II_TREE_TYPE.
  CLEAR %_II_TREE_ID.
  CLEAR %_II_ITEM.
  CLEAR %_II_PARAM.
  CLEAR %_II_UPARAM.
  CLEAR %_II_EXTENSION.
  CLEAR %_VO_VALUE.
  CLEAR %_OO_VALUE.
  CLEAR %_VC_VALUE.
  CLEAR %_OC_VALUE.
  CLEAR %_VN_VALUE.
  CLEAR %_ON_VALUE.
  CLEAR %_VP_VALUE.
  CLEAR %_OP_VALUE.
ENDFORM.
FORM CLEAR_TABLE.
CLEAR %_II_TAB.
REFRESH %_II_TAB.
ENDFORM.
FORM DELETE_LINE USING KEY INDEX.
CASE KEY.
WHEN 'I_TAB'.
READ TABLE %_II_TAB INDEX INDEX.
IF SY-SUBRC = 0.
DELETE %_II_TAB INDEX INDEX.
ENDIF.
ENDCASE.
ENDFORM.
FORM INIT_EXCEPTIONS USING NAME.
  CLEAR EXCEPTIONS.
  MOVE NAME TO EXCEPTIONS-NAME.
  APPEND EXCEPTIONS.
ENDFORM.
FORM PARAM_ACCESS_TYPES USING KEY DEST P_MODE P_UPPER.
DATA : INTKEY(31).
  P_UPPER = G_UPPER.
  INTKEY = DEST.
  INTKEY+1 = KEY.
  CONDENSE INTKEY.
  CASE INTKEY.
    WHEN 'II_TREE_TYPE'.
    CALL FUNCTION 'RS_COMPLEX_OBJECT_EDIT'
         EXPORTING
OBJECT_NAME = 'I_TREE_TYPE'
MODE = P_MODE
INSERT_TAB = 'X'
UPPER_CASE = P_UPPER
         CHANGING
OBJECT = %_II_TREE_TYPE.
    WHEN 'II_TREE_ID'.
    CALL FUNCTION 'RS_COMPLEX_OBJECT_EDIT'
         EXPORTING
OBJECT_NAME = 'I_TREE_ID'
MODE = P_MODE
INSERT_TAB = 'X'
UPPER_CASE = P_UPPER
         CHANGING
OBJECT = %_II_TREE_ID.
    WHEN 'II_ITEM'.
    CALL FUNCTION 'RS_COMPLEX_OBJECT_EDIT'
         EXPORTING
OBJECT_NAME = 'I_ITEM'
MODE = P_MODE
INSERT_TAB = 'X'
UPPER_CASE = P_UPPER
         CHANGING
OBJECT = %_II_ITEM.
    WHEN 'II_PARAM'.
    CALL FUNCTION 'RS_COMPLEX_OBJECT_EDIT'
         EXPORTING
OBJECT_NAME = 'I_PARAM'
MODE = P_MODE
INSERT_TAB = 'X'
UPPER_CASE = P_UPPER
         CHANGING
OBJECT = %_II_PARAM.
    WHEN 'II_UPARAM'.
    CALL FUNCTION 'RS_COMPLEX_OBJECT_EDIT'
         EXPORTING
OBJECT_NAME = 'I_UPARAM'
MODE = P_MODE
INSERT_TAB = 'X'
UPPER_CASE = P_UPPER
         CHANGING
OBJECT = %_II_UPARAM.
    WHEN 'II_EXTENSION'.
    CALL FUNCTION 'RS_COMPLEX_OBJECT_EDIT'
         EXPORTING
OBJECT_NAME = 'I_EXTENSION'
MODE = P_MODE
INSERT_TAB = 'X'
UPPER_CASE = P_UPPER
         CHANGING
OBJECT = %_II_EXTENSION.
    WHEN 'OO_VALUE'.
    CALL FUNCTION 'RS_COMPLEX_OBJECT_EDIT'
         EXPORTING
OBJECT_NAME = 'O_VALUE'
MODE = P_MODE
INSERT_TAB = 'X'
UPPER_CASE = P_UPPER
         CHANGING
OBJECT = %_OO_VALUE.
    WHEN 'VO_VALUE'.
    CALL FUNCTION 'RS_COMPLEX_OBJECT_EDIT'
         EXPORTING
OBJECT_NAME = 'O_VALUE'
MODE = P_MODE
INSERT_TAB = 'X'
UPPER_CASE = P_UPPER
         CHANGING
OBJECT = %_VO_VALUE.
    WHEN 'OC_VALUE'.
    CALL FUNCTION 'RS_COMPLEX_OBJECT_EDIT'
         EXPORTING
OBJECT_NAME = 'C_VALUE'
MODE = P_MODE
INSERT_TAB = 'X'
UPPER_CASE = P_UPPER
         CHANGING
OBJECT = %_OC_VALUE.
    WHEN 'VC_VALUE'.
    CALL FUNCTION 'RS_COMPLEX_OBJECT_EDIT'
         EXPORTING
OBJECT_NAME = 'C_VALUE'
MODE = P_MODE
INSERT_TAB = 'X'
UPPER_CASE = P_UPPER
         CHANGING
OBJECT = %_VC_VALUE.
    WHEN 'ON_VALUE'.
    CALL FUNCTION 'RS_COMPLEX_OBJECT_EDIT'
         EXPORTING
OBJECT_NAME = 'N_VALUE'
MODE = P_MODE
INSERT_TAB = 'X'
UPPER_CASE = P_UPPER
         CHANGING
OBJECT = %_ON_VALUE.
    WHEN 'VN_VALUE'.
    CALL FUNCTION 'RS_COMPLEX_OBJECT_EDIT'
         EXPORTING
OBJECT_NAME = 'N_VALUE'
MODE = P_MODE
INSERT_TAB = 'X'
UPPER_CASE = P_UPPER
         CHANGING
OBJECT = %_VN_VALUE.
    WHEN 'OP_VALUE'.
    CALL FUNCTION 'RS_COMPLEX_OBJECT_EDIT'
         EXPORTING
OBJECT_NAME = 'P_VALUE'
MODE = P_MODE
INSERT_TAB = 'X'
UPPER_CASE = P_UPPER
         CHANGING
OBJECT = %_OP_VALUE.
    WHEN 'VP_VALUE'.
    CALL FUNCTION 'RS_COMPLEX_OBJECT_EDIT'
         EXPORTING
OBJECT_NAME = 'P_VALUE'
MODE = P_MODE
INSERT_TAB = 'X'
UPPER_CASE = P_UPPER
         CHANGING
OBJECT = %_VP_VALUE.
    WHEN 'II_TAB'.
    CALL FUNCTION 'RS_COMPLEX_OBJECT_EDIT'
         EXPORTING
OBJECT_NAME = 'I_TAB'
MODE = P_MODE
INSERT_TAB = 'X'
UPPER_CASE = P_UPPER
         CHANGING
OBJECT = %_II_TAB[].
    WHEN 'OI_TAB'.
    CALL FUNCTION 'RS_COMPLEX_OBJECT_EDIT'
         EXPORTING
OBJECT_NAME = 'I_TAB'
MODE = P_MODE
INSERT_TAB = 'X'
UPPER_CASE = P_UPPER
         CHANGING
OBJECT = %_OI_TAB[].
    WHEN 'VI_TAB'.
    CALL FUNCTION 'RS_COMPLEX_OBJECT_EDIT'
         EXPORTING
OBJECT_NAME = 'I_TAB'
MODE = P_MODE
INSERT_TAB = 'X'
UPPER_CASE = P_UPPER
         CHANGING
OBJECT = %_VI_TAB[].
  ENDCASE.
ENDFORM.
FORM PARAMETER_SET USING NAME DIRECTION VALUE.
 DATA: L_NAME(31).
 CONCATENATE DIRECTION NAME INTO L_NAME.
CASE L_NAME.
WHEN 'II_TREE_TYPE'.
  PERFORM CB_CALLBACK_VALUE_SET(SAPLSEUJ)
   USING VALUE
   CHANGING %_II_TREE_TYPE.
WHEN 'II_TREE_ID'.
  PERFORM CB_CALLBACK_VALUE_SET(SAPLSEUJ)
   USING VALUE
   CHANGING %_II_TREE_ID.
WHEN 'II_ITEM'.
  PERFORM CB_CALLBACK_VALUE_SET(SAPLSEUJ)
   USING VALUE
   CHANGING %_II_ITEM.
WHEN 'II_PARAM'.
  PERFORM CB_CALLBACK_VALUE_SET(SAPLSEUJ)
   USING VALUE
   CHANGING %_II_PARAM.
WHEN 'II_UPARAM'.
  PERFORM CB_CALLBACK_VALUE_SET(SAPLSEUJ)
   USING VALUE
   CHANGING %_II_UPARAM.
WHEN 'II_EXTENSION'.
  PERFORM CB_CALLBACK_VALUE_SET(SAPLSEUJ)
   USING VALUE
   CHANGING %_II_EXTENSION.
WHEN 'OO_VALUE'.
  PERFORM CB_CALLBACK_VALUE_SET(SAPLSEUJ)
   USING VALUE
   CHANGING %_OO_VALUE.
WHEN 'OC_VALUE'.
  PERFORM CB_CALLBACK_VALUE_SET(SAPLSEUJ)
   USING VALUE
   CHANGING %_OC_VALUE.
WHEN 'ON_VALUE'.
  PERFORM CB_CALLBACK_VALUE_SET(SAPLSEUJ)
   USING VALUE
   CHANGING %_ON_VALUE.
WHEN 'OP_VALUE'.
  PERFORM CB_CALLBACK_VALUE_SET(SAPLSEUJ)
   USING VALUE
   CHANGING %_OP_VALUE.
ENDCASE.
ENDFORM.
FORM PARAMETER_GET USING NAME DIRECTION
                   CHANGING   VALUE
                            OLD_VALUE.
 DATA: L_NAME(31).
 CONCATENATE DIRECTION NAME INTO L_NAME.
CASE L_NAME.
WHEN 'II_TREE_TYPE'.
  PERFORM CB_CALLBACK_VALUE_GET(SAPLSEUJ)
   USING %_II_TREE_TYPE
   CHANGING VALUE.
  PERFORM CB_CALLBACK_VALUE_GET(SAPLSEUJ)
   USING %_II_TREE_TYPE
   CHANGING OLD_VALUE.
WHEN 'II_TREE_ID'.
  PERFORM CB_CALLBACK_VALUE_GET(SAPLSEUJ)
   USING %_II_TREE_ID
   CHANGING VALUE.
  PERFORM CB_CALLBACK_VALUE_GET(SAPLSEUJ)
   USING %_II_TREE_ID
   CHANGING OLD_VALUE.
WHEN 'II_ITEM'.
  PERFORM CB_CALLBACK_VALUE_GET(SAPLSEUJ)
   USING %_II_ITEM
   CHANGING VALUE.
  PERFORM CB_CALLBACK_VALUE_GET(SAPLSEUJ)
   USING %_II_ITEM
   CHANGING OLD_VALUE.
WHEN 'II_PARAM'.
  PERFORM CB_CALLBACK_VALUE_GET(SAPLSEUJ)
   USING %_II_PARAM
   CHANGING VALUE.
  PERFORM CB_CALLBACK_VALUE_GET(SAPLSEUJ)
   USING %_II_PARAM
   CHANGING OLD_VALUE.
WHEN 'II_UPARAM'.
  PERFORM CB_CALLBACK_VALUE_GET(SAPLSEUJ)
   USING %_II_UPARAM
   CHANGING VALUE.
  PERFORM CB_CALLBACK_VALUE_GET(SAPLSEUJ)
   USING %_II_UPARAM
   CHANGING OLD_VALUE.
WHEN 'II_EXTENSION'.
  PERFORM CB_CALLBACK_VALUE_GET(SAPLSEUJ)
   USING %_II_EXTENSION
   CHANGING VALUE.
  PERFORM CB_CALLBACK_VALUE_GET(SAPLSEUJ)
   USING %_II_EXTENSION
   CHANGING OLD_VALUE.
WHEN 'OO_VALUE'.
  PERFORM CB_CALLBACK_VALUE_GET(SAPLSEUJ)
   USING %_OO_VALUE
   CHANGING VALUE.
  PERFORM CB_CALLBACK_VALUE_GET(SAPLSEUJ)
   USING %_OO_VALUE
   CHANGING OLD_VALUE.
WHEN 'OC_VALUE'.
  PERFORM CB_CALLBACK_VALUE_GET(SAPLSEUJ)
   USING %_OC_VALUE
   CHANGING VALUE.
  PERFORM CB_CALLBACK_VALUE_GET(SAPLSEUJ)
   USING %_OC_VALUE
   CHANGING OLD_VALUE.
WHEN 'ON_VALUE'.
  PERFORM CB_CALLBACK_VALUE_GET(SAPLSEUJ)
   USING %_ON_VALUE
   CHANGING VALUE.
  PERFORM CB_CALLBACK_VALUE_GET(SAPLSEUJ)
   USING %_ON_VALUE
   CHANGING OLD_VALUE.
WHEN 'OP_VALUE'.
  PERFORM CB_CALLBACK_VALUE_GET(SAPLSEUJ)
   USING %_OP_VALUE
   CHANGING VALUE.
  PERFORM CB_CALLBACK_VALUE_GET(SAPLSEUJ)
   USING %_OP_VALUE
   CHANGING OLD_VALUE.
WHEN 'OI_TAB'.
  PERFORM CB_CALLBACK_VALUE_GET(SAPLSEUJ)
   USING %_OI_TAB[]
   CHANGING VALUE.
  PERFORM CB_CALLBACK_VALUE_GET(SAPLSEUJ)
   USING %_II_TAB[]
   CHANGING OLD_VALUE.
ENDCASE.
ENDFORM.
FORM PARAMETER_TABLE_SET USING NAME VALUE.
CASE NAME.
WHEN 'I_TAB'.
  %_OI_TAB[] = VALUE.
ENDCASE.
ENDFORM.
FORM PARAMETER_TABLE_GET USING NAME
                   CHANGING   VALUE.
CASE NAME.
WHEN 'I_TAB'.
  VALUE = %_OI_TAB[].
ENDCASE.
ENDFORM.
FORM PARAMETER_DESCRIBE USING CBPROG
                              NAME.
CASE NAME.
WHEN 'I_TREE_TYPE'.
  PERFORM CB_CALLBACK_DESCRIBE IN PROGRAM (CBPROG)
   USING %_II_TREE_TYPE
         NAME.
WHEN 'I_TREE_ID'.
  PERFORM CB_CALLBACK_DESCRIBE IN PROGRAM (CBPROG)
   USING %_II_TREE_ID
         NAME.
WHEN 'I_ITEM'.
  PERFORM CB_CALLBACK_DESCRIBE IN PROGRAM (CBPROG)
   USING %_II_ITEM
         NAME.
WHEN 'I_PARAM'.
  PERFORM CB_CALLBACK_DESCRIBE IN PROGRAM (CBPROG)
   USING %_II_PARAM
         NAME.
WHEN 'I_UPARAM'.
  PERFORM CB_CALLBACK_DESCRIBE IN PROGRAM (CBPROG)
   USING %_II_UPARAM
         NAME.
WHEN 'I_EXTENSION'.
  PERFORM CB_CALLBACK_DESCRIBE IN PROGRAM (CBPROG)
   USING %_II_EXTENSION
         NAME.
WHEN 'O_VALUE'.
  PERFORM CB_CALLBACK_DESCRIBE IN PROGRAM (CBPROG)
   USING %_OO_VALUE
         NAME.
WHEN 'C_VALUE'.
  PERFORM CB_CALLBACK_DESCRIBE IN PROGRAM (CBPROG)
   USING %_OC_VALUE
         NAME.
WHEN 'N_VALUE'.
  PERFORM CB_CALLBACK_DESCRIBE IN PROGRAM (CBPROG)
   USING %_ON_VALUE
         NAME.
WHEN 'P_VALUE'.
  PERFORM CB_CALLBACK_DESCRIBE IN PROGRAM (CBPROG)
   USING %_OP_VALUE
         NAME.
WHEN 'I_TAB'.
  PERFORM CB_CALLBACK_DESCRIBE IN PROGRAM (CBPROG)
   USING %_OI_TAB
         NAME.
ENDCASE.
ENDFORM.
FORM PARAMETER_CONTAINER TABLES LCONT STRUCTURE SWCONT
                         USING NAME
                               DIRECTION .
CASE NAME.
WHEN 'II_TREE_TYPE'.
IF DIRECTION = 'O'.
  CALL FUNCTION 'SWC_ELEMENT_SET'
EXPORTING
ELEMENT = NAME
FIELD   = %_II_TREE_TYPE
TABLES
CONTAINER = LCONT.
ELSE.
  CALL FUNCTION 'SWC_ELEMENT_GET'
EXPORTING
ELEMENT = NAME
IMPORTING
FIELD   = %_II_TREE_TYPE
TABLES
CONTAINER = LCONT.
ENDIF.
WHEN 'II_TREE_ID'.
IF DIRECTION = 'O'.
  CALL FUNCTION 'SWC_ELEMENT_SET'
EXPORTING
ELEMENT = NAME
FIELD   = %_II_TREE_ID
TABLES
CONTAINER = LCONT.
ELSE.
  CALL FUNCTION 'SWC_ELEMENT_GET'
EXPORTING
ELEMENT = NAME
IMPORTING
FIELD   = %_II_TREE_ID
TABLES
CONTAINER = LCONT.
ENDIF.
WHEN 'II_ITEM'.
IF DIRECTION = 'O'.
  CALL FUNCTION 'SWC_ELEMENT_SET'
EXPORTING
ELEMENT = NAME
FIELD   = %_II_ITEM
TABLES
CONTAINER = LCONT.
ELSE.
  CALL FUNCTION 'SWC_ELEMENT_GET'
EXPORTING
ELEMENT = NAME
IMPORTING
FIELD   = %_II_ITEM
TABLES
CONTAINER = LCONT.
ENDIF.
WHEN 'II_PARAM'.
IF DIRECTION = 'O'.
  CALL FUNCTION 'SWC_ELEMENT_SET'
EXPORTING
ELEMENT = NAME
FIELD   = %_II_PARAM
TABLES
CONTAINER = LCONT.
ELSE.
  CALL FUNCTION 'SWC_ELEMENT_GET'
EXPORTING
ELEMENT = NAME
IMPORTING
FIELD   = %_II_PARAM
TABLES
CONTAINER = LCONT.
ENDIF.
WHEN 'II_UPARAM'.
IF DIRECTION = 'O'.
  CALL FUNCTION 'SWC_ELEMENT_SET'
EXPORTING
ELEMENT = NAME
FIELD   = %_II_UPARAM
TABLES
CONTAINER = LCONT.
ELSE.
  CALL FUNCTION 'SWC_ELEMENT_GET'
EXPORTING
ELEMENT = NAME
IMPORTING
FIELD   = %_II_UPARAM
TABLES
CONTAINER = LCONT.
ENDIF.
WHEN 'II_EXTENSION'.
IF DIRECTION = 'O'.
  CALL FUNCTION 'SWC_ELEMENT_SET'
EXPORTING
ELEMENT = NAME
FIELD   = %_II_EXTENSION
TABLES
CONTAINER = LCONT.
ELSE.
  CALL FUNCTION 'SWC_ELEMENT_GET'
EXPORTING
ELEMENT = NAME
IMPORTING
FIELD   = %_II_EXTENSION
TABLES
CONTAINER = LCONT.
ENDIF.
WHEN 'OO_VALUE'.
IF DIRECTION = 'O'.
  CALL FUNCTION 'SWC_ELEMENT_SET'
EXPORTING
ELEMENT = NAME
FIELD   = %_OO_VALUE
TABLES
CONTAINER = LCONT.
ELSE.
  CALL FUNCTION 'SWC_ELEMENT_GET'
EXPORTING
ELEMENT = NAME
IMPORTING
FIELD   = %_OO_VALUE
TABLES
CONTAINER = LCONT.
ENDIF.
WHEN 'OC_VALUE'.
IF DIRECTION = 'O'.
  CALL FUNCTION 'SWC_ELEMENT_SET'
EXPORTING
ELEMENT = NAME
FIELD   = %_OC_VALUE
TABLES
CONTAINER = LCONT.
ELSE.
  CALL FUNCTION 'SWC_ELEMENT_GET'
EXPORTING
ELEMENT = NAME
IMPORTING
FIELD   = %_OC_VALUE
TABLES
CONTAINER = LCONT.
ENDIF.
WHEN 'ON_VALUE'.
IF DIRECTION = 'O'.
  CALL FUNCTION 'SWC_ELEMENT_SET'
EXPORTING
ELEMENT = NAME
FIELD   = %_ON_VALUE
TABLES
CONTAINER = LCONT.
ELSE.
  CALL FUNCTION 'SWC_ELEMENT_GET'
EXPORTING
ELEMENT = NAME
IMPORTING
FIELD   = %_ON_VALUE
TABLES
CONTAINER = LCONT.
ENDIF.
WHEN 'OP_VALUE'.
IF DIRECTION = 'O'.
  CALL FUNCTION 'SWC_ELEMENT_SET'
EXPORTING
ELEMENT = NAME
FIELD   = %_OP_VALUE
TABLES
CONTAINER = LCONT.
ELSE.
  CALL FUNCTION 'SWC_ELEMENT_GET'
EXPORTING
ELEMENT = NAME
IMPORTING
FIELD   = %_OP_VALUE
TABLES
CONTAINER = LCONT.
ENDIF.
ENDCASE.
ENDFORM.
FORM TABLES_CONTAINER TABLES LCONT STRUCTURE SWCONT
                      USING NAME
                            DIRECTION.
CASE NAME.
WHEN 'II_TAB'.
IF DIRECTION = 'O'.
  CALL FUNCTION 'SWC_TABLE_SET'
EXPORTING
ELEMENT = NAME
TABLES
TABLE   = %_II_TAB
CONTAINER = LCONT.
ELSE.
  CALL FUNCTION 'SWC_TABLE_GET'
EXPORTING
ELEMENT = NAME
TABLES
TABLE   = %_II_TAB
CONTAINER = LCONT.
ENDIF.
WHEN 'OI_TAB'.
IF DIRECTION = 'O'.
  CALL FUNCTION 'SWC_TABLE_SET'
EXPORTING
ELEMENT = NAME
TABLES
TABLE   = %_OI_TAB
CONTAINER = LCONT.
ELSE.
  CALL FUNCTION 'SWC_TABLE_GET'
EXPORTING
ELEMENT = NAME
TABLES
TABLE   = %_OI_TAB
CONTAINER = LCONT.
ENDIF.
ENDCASE.
ENDFORM.
FORM SET_VARIABLES USING KEY VALUE.
  CASE KEY.
    WHEN '%%DEBUGON'.
      DEBUG = 1.
    WHEN '%%DEBUGOFF'.
      DEBUG = 0.
    WHEN '%%DESTI'.
      DESTI = VALUE.
    WHEN '%%ATRAON'.
      ATRA = 1.
    WHEN '%%ATRAOFF'.
      ATRA = 0.
    WHEN '%%UPPER'.
      G_UPPER = VALUE.
  ENDCASE.
ENDFORM.
FORM GET_VARIABLES USING    KEY
                   CHANGING VALUE.
  CASE KEY.
    WHEN '%%DEBUG'.
      VALUE = DEBUG.
    WHEN '%%DESTI'.
      VALUE = DESTI.
    WHEN '%%ATRA'.
      VALUE = ATRA.
    WHEN '%%SUBRC'.
      VALUE = RC.
    WHEN 'V%%SUBRC'.
      VALUE = V_RC.
    WHEN '%%TIME'.
      VALUE = RUNTIME.
    WHEN '%%UPPER'.
      VALUE = G_UPPER.
    WHEN '%%EXCCL'.
      VALUE = RESULTAT.
  ENDCASE.
ENDFORM.
FORM GET_EXC_CL CHANGING P_EXC_CL.
   IF EX IS BOUND.
       P_EXC_CL = EX.
     ELSE.
       CLEAR P_EXC_CL.
   ENDIF.
ENDFORM.
FORM PARAMETER_READ_INPUT USING NAME
                                KEY
                       CHANGING VALUE.
  CASE NAME.
    WHEN 'I_TREE_TYPE'.
 CATCH SYSTEM-EXCEPTIONS CONNE_IMPORT_WRONG_COMP_TYPE = 1
                         CONNE_IMPORT_WRONG_OBJECT_TYPE = 2
                         CONNE_IMPORT_WRONG_COMP_LENG = 3
                         CONNE_IMPORT_WRONG_FIELD_LENG = 6
                         CONNE_IMPORT_WRONG_STRUCTURE  = 7
                         CONNE_IMPORT_WRONG_FIELD_TYPE = 4
                         IMPORT_WRONG_END_POS = 8
                         IMPORT_ALIGNMENT_MISMATCH = 5.
      IMPORT %_II_TREE_TYPE
             FROM DATABASE EUFUNC(FL) ID KEY.
 ENDCATCH.
  VALUE = %_II_TREE_TYPE.
    WHEN 'I_TREE_ID'.
 CATCH SYSTEM-EXCEPTIONS CONNE_IMPORT_WRONG_COMP_TYPE = 1
                         CONNE_IMPORT_WRONG_OBJECT_TYPE = 2
                         CONNE_IMPORT_WRONG_COMP_LENG = 3
                         CONNE_IMPORT_WRONG_FIELD_LENG = 6
                         CONNE_IMPORT_WRONG_STRUCTURE  = 7
                         CONNE_IMPORT_WRONG_FIELD_TYPE = 4
                         IMPORT_WRONG_END_POS = 8
                         IMPORT_ALIGNMENT_MISMATCH = 5.
      IMPORT %_II_TREE_ID
             FROM DATABASE EUFUNC(FL) ID KEY.
 ENDCATCH.
  VALUE = %_II_TREE_ID.
    WHEN 'I_ITEM'.
 CATCH SYSTEM-EXCEPTIONS CONNE_IMPORT_WRONG_COMP_TYPE = 1
                         CONNE_IMPORT_WRONG_OBJECT_TYPE = 2
                         CONNE_IMPORT_WRONG_COMP_LENG = 3
                         CONNE_IMPORT_WRONG_FIELD_LENG = 6
                         CONNE_IMPORT_WRONG_STRUCTURE  = 7
                         CONNE_IMPORT_WRONG_FIELD_TYPE = 4
                         IMPORT_WRONG_END_POS = 8
                         IMPORT_ALIGNMENT_MISMATCH = 5.
      IMPORT %_II_ITEM
             FROM DATABASE EUFUNC(FL) ID KEY.
 ENDCATCH.
  VALUE = %_II_ITEM.
    WHEN 'I_PARAM'.
 CATCH SYSTEM-EXCEPTIONS CONNE_IMPORT_WRONG_COMP_TYPE = 1
                         CONNE_IMPORT_WRONG_OBJECT_TYPE = 2
                         CONNE_IMPORT_WRONG_COMP_LENG = 3
                         CONNE_IMPORT_WRONG_FIELD_LENG = 6
                         CONNE_IMPORT_WRONG_STRUCTURE  = 7
                         CONNE_IMPORT_WRONG_FIELD_TYPE = 4
                         IMPORT_WRONG_END_POS = 8
                         IMPORT_ALIGNMENT_MISMATCH = 5.
      IMPORT %_II_PARAM
             FROM DATABASE EUFUNC(FL) ID KEY.
 ENDCATCH.
  VALUE = %_II_PARAM.
    WHEN 'I_UPARAM'.
 CATCH SYSTEM-EXCEPTIONS CONNE_IMPORT_WRONG_COMP_TYPE = 1
                         CONNE_IMPORT_WRONG_OBJECT_TYPE = 2
                         CONNE_IMPORT_WRONG_COMP_LENG = 3
                         CONNE_IMPORT_WRONG_FIELD_LENG = 6
                         CONNE_IMPORT_WRONG_STRUCTURE  = 7
                         CONNE_IMPORT_WRONG_FIELD_TYPE = 4
                         IMPORT_WRONG_END_POS = 8
                         IMPORT_ALIGNMENT_MISMATCH = 5.
      IMPORT %_II_UPARAM
             FROM DATABASE EUFUNC(FL) ID KEY.
 ENDCATCH.
  VALUE = %_II_UPARAM.
    WHEN 'I_EXTENSION'.
 CATCH SYSTEM-EXCEPTIONS CONNE_IMPORT_WRONG_COMP_TYPE = 1
                         CONNE_IMPORT_WRONG_OBJECT_TYPE = 2
                         CONNE_IMPORT_WRONG_COMP_LENG = 3
                         CONNE_IMPORT_WRONG_FIELD_LENG = 6
                         CONNE_IMPORT_WRONG_STRUCTURE  = 7
                         CONNE_IMPORT_WRONG_FIELD_TYPE = 4
                         IMPORT_WRONG_END_POS = 8
                         IMPORT_ALIGNMENT_MISMATCH = 5.
      IMPORT %_II_EXTENSION
             FROM DATABASE EUFUNC(FL) ID KEY.
 ENDCATCH.
  VALUE = %_II_EXTENSION.
  ENDCASE.
ENDFORM.
FORM PARAMETER_READ_OUTPUT USING NAME
                                 KEY
                        CHANGING VALUE.
  CASE NAME.
    WHEN 'I_TREE_TYPE'.
 CATCH SYSTEM-EXCEPTIONS CONNE_IMPORT_WRONG_COMP_TYPE = 1
                         CONNE_IMPORT_WRONG_OBJECT_TYPE = 2
                         CONNE_IMPORT_WRONG_COMP_LENG = 3
                         CONNE_IMPORT_WRONG_FIELD_TYPE = 4
                         CONNE_IMPORT_WRONG_FIELD_LENG = 6
                         CONNE_IMPORT_WRONG_STRUCTURE  = 7
                         IMPORT_WRONG_END_POS = 8
                         IMPORT_ALIGNMENT_MISMATCH = 5.
      IMPORT %_II_TREE_TYPE
             FROM DATABASE EUFUNC(FL) ID KEY.
 ENDCATCH.
    WHEN 'I_TREE_ID'.
 CATCH SYSTEM-EXCEPTIONS CONNE_IMPORT_WRONG_COMP_TYPE = 1
                         CONNE_IMPORT_WRONG_OBJECT_TYPE = 2
                         CONNE_IMPORT_WRONG_COMP_LENG = 3
                         CONNE_IMPORT_WRONG_FIELD_TYPE = 4
                         CONNE_IMPORT_WRONG_FIELD_LENG = 6
                         CONNE_IMPORT_WRONG_STRUCTURE  = 7
                         IMPORT_WRONG_END_POS = 8
                         IMPORT_ALIGNMENT_MISMATCH = 5.
      IMPORT %_II_TREE_ID
             FROM DATABASE EUFUNC(FL) ID KEY.
 ENDCATCH.
    WHEN 'I_ITEM'.
 CATCH SYSTEM-EXCEPTIONS CONNE_IMPORT_WRONG_COMP_TYPE = 1
                         CONNE_IMPORT_WRONG_OBJECT_TYPE = 2
                         CONNE_IMPORT_WRONG_COMP_LENG = 3
                         CONNE_IMPORT_WRONG_FIELD_TYPE = 4
                         CONNE_IMPORT_WRONG_FIELD_LENG = 6
                         CONNE_IMPORT_WRONG_STRUCTURE  = 7
                         IMPORT_WRONG_END_POS = 8
                         IMPORT_ALIGNMENT_MISMATCH = 5.
      IMPORT %_II_ITEM
             FROM DATABASE EUFUNC(FL) ID KEY.
 ENDCATCH.
    WHEN 'I_PARAM'.
 CATCH SYSTEM-EXCEPTIONS CONNE_IMPORT_WRONG_COMP_TYPE = 1
                         CONNE_IMPORT_WRONG_OBJECT_TYPE = 2
                         CONNE_IMPORT_WRONG_COMP_LENG = 3
                         CONNE_IMPORT_WRONG_FIELD_TYPE = 4
                         CONNE_IMPORT_WRONG_FIELD_LENG = 6
                         CONNE_IMPORT_WRONG_STRUCTURE  = 7
                         IMPORT_WRONG_END_POS = 8
                         IMPORT_ALIGNMENT_MISMATCH = 5.
      IMPORT %_II_PARAM
             FROM DATABASE EUFUNC(FL) ID KEY.
 ENDCATCH.
    WHEN 'I_UPARAM'.
 CATCH SYSTEM-EXCEPTIONS CONNE_IMPORT_WRONG_COMP_TYPE = 1
                         CONNE_IMPORT_WRONG_OBJECT_TYPE = 2
                         CONNE_IMPORT_WRONG_COMP_LENG = 3
                         CONNE_IMPORT_WRONG_FIELD_TYPE = 4
                         CONNE_IMPORT_WRONG_FIELD_LENG = 6
                         CONNE_IMPORT_WRONG_STRUCTURE  = 7
                         IMPORT_WRONG_END_POS = 8
                         IMPORT_ALIGNMENT_MISMATCH = 5.
      IMPORT %_II_UPARAM
             FROM DATABASE EUFUNC(FL) ID KEY.
 ENDCATCH.
    WHEN 'I_EXTENSION'.
 CATCH SYSTEM-EXCEPTIONS CONNE_IMPORT_WRONG_COMP_TYPE = 1
                         CONNE_IMPORT_WRONG_OBJECT_TYPE = 2
                         CONNE_IMPORT_WRONG_COMP_LENG = 3
                         CONNE_IMPORT_WRONG_FIELD_TYPE = 4
                         CONNE_IMPORT_WRONG_FIELD_LENG = 6
                         CONNE_IMPORT_WRONG_STRUCTURE  = 7
                         IMPORT_WRONG_END_POS = 8
                         IMPORT_ALIGNMENT_MISMATCH = 5.
      IMPORT %_II_EXTENSION
             FROM DATABASE EUFUNC(FL) ID KEY.
 ENDCATCH.
    WHEN 'O_VALUE'.
 CATCH SYSTEM-EXCEPTIONS CONNE_IMPORT_WRONG_COMP_TYPE = 1
                         CONNE_IMPORT_WRONG_OBJECT_TYPE = 2
                         CONNE_IMPORT_WRONG_COMP_LENG = 3
                         CONNE_IMPORT_WRONG_FIELD_TYPE = 4
                         CONNE_IMPORT_WRONG_FIELD_LENG = 6
                         CONNE_IMPORT_WRONG_STRUCTURE  = 7
                         IMPORT_WRONG_END_POS = 8
                         IMPORT_ALIGNMENT_MISMATCH = 5.
      IMPORT %_VO_VALUE
             FROM DATABASE EUFUNC(FL) ID KEY.
 ENDCATCH.
    WHEN 'C_VALUE'.
 CATCH SYSTEM-EXCEPTIONS CONNE_IMPORT_WRONG_COMP_TYPE = 1
                         CONNE_IMPORT_WRONG_OBJECT_TYPE = 2
                         CONNE_IMPORT_WRONG_COMP_LENG = 3
                         CONNE_IMPORT_WRONG_FIELD_TYPE = 4
                         CONNE_IMPORT_WRONG_FIELD_LENG = 6
                         CONNE_IMPORT_WRONG_STRUCTURE  = 7
                         IMPORT_WRONG_END_POS = 8
                         IMPORT_ALIGNMENT_MISMATCH = 5.
      IMPORT %_VC_VALUE
             FROM DATABASE EUFUNC(FL) ID KEY.
 ENDCATCH.
    WHEN 'N_VALUE'.
 CATCH SYSTEM-EXCEPTIONS CONNE_IMPORT_WRONG_COMP_TYPE = 1
                         CONNE_IMPORT_WRONG_OBJECT_TYPE = 2
                         CONNE_IMPORT_WRONG_COMP_LENG = 3
                         CONNE_IMPORT_WRONG_FIELD_TYPE = 4
                         CONNE_IMPORT_WRONG_FIELD_LENG = 6
                         CONNE_IMPORT_WRONG_STRUCTURE  = 7
                         IMPORT_WRONG_END_POS = 8
                         IMPORT_ALIGNMENT_MISMATCH = 5.
      IMPORT %_VN_VALUE
             FROM DATABASE EUFUNC(FL) ID KEY.
 ENDCATCH.
    WHEN 'P_VALUE'.
 CATCH SYSTEM-EXCEPTIONS CONNE_IMPORT_WRONG_COMP_TYPE = 1
                         CONNE_IMPORT_WRONG_OBJECT_TYPE = 2
                         CONNE_IMPORT_WRONG_COMP_LENG = 3
                         CONNE_IMPORT_WRONG_FIELD_TYPE = 4
                         CONNE_IMPORT_WRONG_FIELD_LENG = 6
                         CONNE_IMPORT_WRONG_STRUCTURE  = 7
                         IMPORT_WRONG_END_POS = 8
                         IMPORT_ALIGNMENT_MISMATCH = 5.
      IMPORT %_VP_VALUE
             FROM DATABASE EUFUNC(FL) ID KEY.
 ENDCATCH.
  ENDCASE.
ENDFORM.
FORM PARAMETER_COMPARE USING NAME
                       CHANGING VALUE.
  CASE NAME.
    WHEN 'O_VALUE'.
      IF %_OO_VALUE <> %_VO_VALUE.
        VALUE = 'X'.
      ELSE.
        CLEAR VALUE.
      ENDIF.
    WHEN 'C_VALUE'.
      IF %_OC_VALUE <> %_VC_VALUE.
        VALUE = 'X'.
      ELSE.
        CLEAR VALUE.
      ENDIF.
    WHEN 'N_VALUE'.
      IF %_ON_VALUE <> %_VN_VALUE.
        VALUE = 'X'.
      ELSE.
        CLEAR VALUE.
      ENDIF.
    WHEN 'P_VALUE'.
      IF %_OP_VALUE <> %_VP_VALUE.
        VALUE = 'X'.
      ELSE.
        CLEAR VALUE.
      ENDIF.
    WHEN 'I_TAB'.
      IF %_OI_TAB[] <> %_VI_TAB[].
        VALUE = 'X'.
      ELSE.
        CLEAR VALUE.
      ENDIF.
  ENDCASE.
ENDFORM.
FORM EXPORT_IMPORT_MEMORY USING SEL KEY STRUCTURE EXPORTKEY.
 CASE SEL.
WHEN 'II'.
 CATCH SYSTEM-EXCEPTIONS CONNE_IMPORT_WRONG_COMP_TYPE = 1
                         CONNE_IMPORT_WRONG_OBJECT_TYPE = 2
                         CONNE_IMPORT_WRONG_COMP_LENG = 3
                         CONNE_IMPORT_WRONG_FIELD_LENG = 6
                         CONNE_IMPORT_WRONG_STRUCTURE  = 7
                         CONNE_IMPORT_WRONG_FIELD_TYPE = 4
                         IMPORT_WRONG_END_POS = 8
                         IMPORT_ALIGNMENT_MISMATCH = 5.
  IMPORT
%_II_TREE_TYPE
%_II_TREE_ID
%_II_ITEM
%_II_PARAM
%_II_UPARAM
%_II_EXTENSION
%_II_TAB
G_UPPER
FROM MEMORY ID KEY.
 ENDCATCH.
WHEN 'IO'.
V_RC = RC.
%_VO_VALUE = %_OO_VALUE.
%_VC_VALUE = %_OC_VALUE.
%_VN_VALUE = %_ON_VALUE.
%_VP_VALUE = %_OP_VALUE.
CLEAR %_VI_TAB.
REFRESH %_VI_TAB.
LOOP AT %_OI_TAB.
  %_VI_TAB = %_OI_TAB.
  APPEND %_VI_TAB.
ENDLOOP.
VEXCEPTION = OEXCEPTION.
  EXPORT
%_II_TREE_TYPE
%_II_TREE_ID
%_II_ITEM
%_II_PARAM
%_II_UPARAM
%_II_EXTENSION
%_II_TAB
%_VO_VALUE
%_VC_VALUE
%_VN_VALUE
%_VP_VALUE
%_VI_TAB
TIME1
V_RC
VEXCEPTION
G_UPPER
TO MEMORY ID KEY.
WHEN 'VI'.
 CATCH SYSTEM-EXCEPTIONS CONNE_IMPORT_WRONG_COMP_TYPE = 1
                         CONNE_IMPORT_WRONG_OBJECT_TYPE = 2
                         CONNE_IMPORT_WRONG_COMP_LENG = 3
                         CONNE_IMPORT_WRONG_FIELD_LENG = 6
                         CONNE_IMPORT_WRONG_STRUCTURE  = 7
                         CONNE_IMPORT_WRONG_FIELD_TYPE = 4
                         IMPORT_WRONG_END_POS = 8
                         IMPORT_ALIGNMENT_MISMATCH = 5.
  IMPORT
%_VO_VALUE
%_VC_VALUE
%_VN_VALUE
%_VP_VALUE
%_VI_TAB
TIME1
V_RC
VEXCEPTION
G_UPPER
FROM MEMORY ID KEY.
 ENDCATCH.
WHEN 'VO'.
V_RC = RC.
%_VO_VALUE = %_OO_VALUE.
%_VC_VALUE = %_OC_VALUE.
%_VN_VALUE = %_ON_VALUE.
%_VP_VALUE = %_OP_VALUE.
CLEAR %_VI_TAB.
REFRESH %_VI_TAB.
LOOP AT %_OI_TAB.
  %_VI_TAB = %_OI_TAB.
  APPEND %_VI_TAB.
ENDLOOP.
VEXCEPTION = OEXCEPTION.
  EXPORT
%_VO_VALUE
%_VC_VALUE
%_VN_VALUE
%_VP_VALUE
%_VI_TAB
TIME1
V_RC
VEXCEPTION
G_UPPER
TO MEMORY ID KEY.
WHEN 'IV'.
 CATCH SYSTEM-EXCEPTIONS CONNE_IMPORT_WRONG_COMP_TYPE = 1
                         CONNE_IMPORT_WRONG_OBJECT_TYPE = 2
                         CONNE_IMPORT_WRONG_COMP_LENG = 3
                         CONNE_IMPORT_WRONG_FIELD_LENG = 6
                         CONNE_IMPORT_WRONG_STRUCTURE  = 7
                         CONNE_IMPORT_WRONG_FIELD_TYPE = 4
                         IMPORT_WRONG_END_POS = 8
                         IMPORT_ALIGNMENT_MISMATCH = 5.
  IMPORT
%_VO_VALUE
%_VC_VALUE
%_VN_VALUE
%_VP_VALUE
%_VI_TAB
TIME1
V_RC
VEXCEPTION
G_UPPER
FROM MEMORY ID KEY.
 ENDCATCH.
RC = V_RC.
%_OO_VALUE = %_VO_VALUE.
%_OC_VALUE = %_VC_VALUE.
%_ON_VALUE = %_VN_VALUE.
%_OP_VALUE = %_VP_VALUE.
CLEAR %_OI_TAB.
REFRESH %_OI_TAB.
LOOP AT %_VI_TAB.
  %_OI_TAB = %_VI_TAB.
  APPEND %_OI_TAB.
ENDLOOP.
  ENDCASE.
ENDFORM.
FORM EXPORT_IMPORT USING SEL KEY STRUCTURE D102N_EXPORTKEY.
 CASE SEL.
WHEN 'II'.
 CATCH SYSTEM-EXCEPTIONS CONNE_IMPORT_WRONG_COMP_TYPE = 1
                         CONNE_IMPORT_WRONG_OBJECT_TYPE = 2
                         CONNE_IMPORT_WRONG_COMP_LENG = 3
                         CONNE_IMPORT_WRONG_FIELD_LENG = 6
                         CONNE_IMPORT_WRONG_STRUCTURE  = 7
                         CONNE_IMPORT_WRONG_FIELD_TYPE = 4
                         IMPORT_WRONG_END_POS = 8
                         IMPORT_ALIGNMENT_MISMATCH = 5.
  IMPORT
%_II_TREE_TYPE
%_II_TREE_ID
%_II_ITEM
%_II_PARAM
%_II_UPARAM
%_II_EXTENSION
%_II_TAB
G_UPPER
FROM DATABASE EUFUNC(FL) ID KEY ACCEPTING PADDING
                         IGNORING CONVERSION ERRORS.
 ENDCATCH.
WHEN 'IO'.
V_RC = RC.
%_VO_VALUE = %_OO_VALUE.
%_VC_VALUE = %_OC_VALUE.
%_VN_VALUE = %_ON_VALUE.
%_VP_VALUE = %_OP_VALUE.
CLEAR %_VI_TAB.
REFRESH %_VI_TAB.
LOOP AT %_OI_TAB.
  %_VI_TAB = %_OI_TAB.
  APPEND %_VI_TAB.
ENDLOOP.
VEXCEPTION = OEXCEPTION.
  EXPORT
%_II_TREE_TYPE
%_II_TREE_ID
%_II_ITEM
%_II_PARAM
%_II_UPARAM
%_II_EXTENSION
%_II_TAB
%_VO_VALUE
%_VC_VALUE
%_VN_VALUE
%_VP_VALUE
%_VI_TAB
TIME1
V_RC
VEXCEPTION
G_UPPER
TO DATABASE EUFUNC(FL) ID KEY.
WHEN 'VI'.
 CATCH SYSTEM-EXCEPTIONS CONNE_IMPORT_WRONG_COMP_TYPE = 1
                         CONNE_IMPORT_WRONG_OBJECT_TYPE = 2
                         CONNE_IMPORT_WRONG_COMP_LENG = 3
                         CONNE_IMPORT_WRONG_FIELD_LENG = 6
                         CONNE_IMPORT_WRONG_STRUCTURE  = 7
                         CONNE_IMPORT_WRONG_FIELD_TYPE = 4
                         IMPORT_WRONG_END_POS = 8
                         IMPORT_ALIGNMENT_MISMATCH = 5.
  IMPORT
%_VO_VALUE
%_VC_VALUE
%_VN_VALUE
%_VP_VALUE
%_VI_TAB
TIME1
V_RC
VEXCEPTION
G_UPPER
FROM DATABASE EUFUNC(FL) ID KEY ACCEPTING PADDING
                         IGNORING CONVERSION ERRORS.
 ENDCATCH.
WHEN 'VO'.
V_RC = RC.
%_VO_VALUE = %_OO_VALUE.
%_VC_VALUE = %_OC_VALUE.
%_VN_VALUE = %_ON_VALUE.
%_VP_VALUE = %_OP_VALUE.
CLEAR %_VI_TAB.
REFRESH %_VI_TAB.
LOOP AT %_OI_TAB.
  %_VI_TAB = %_OI_TAB.
  APPEND %_VI_TAB.
ENDLOOP.
VEXCEPTION = OEXCEPTION.
  EXPORT
%_VO_VALUE
%_VC_VALUE
%_VN_VALUE
%_VP_VALUE
%_VI_TAB
TIME1
V_RC
VEXCEPTION
G_UPPER
TO DATABASE EUFUNC(FL) ID KEY.
WHEN 'IV'.
 CATCH SYSTEM-EXCEPTIONS CONNE_IMPORT_WRONG_COMP_TYPE = 1
                         CONNE_IMPORT_WRONG_OBJECT_TYPE = 2
                         CONNE_IMPORT_WRONG_COMP_LENG = 3
                         CONNE_IMPORT_WRONG_FIELD_LENG = 6
                         CONNE_IMPORT_WRONG_STRUCTURE  = 7
                         CONNE_IMPORT_WRONG_FIELD_TYPE = 4
                         IMPORT_WRONG_END_POS = 8
                         IMPORT_ALIGNMENT_MISMATCH = 5.
  IMPORT
%_VO_VALUE
%_VC_VALUE
%_VN_VALUE
%_VP_VALUE
%_VI_TAB
TIME1
V_RC
VEXCEPTION
G_UPPER
FROM DATABASE EUFUNC(FL) ID KEY ACCEPTING PADDING
                         IGNORING CONVERSION ERRORS.
 ENDCATCH.
RC = V_RC.
%_OO_VALUE = %_VO_VALUE.
%_OC_VALUE = %_VC_VALUE.
%_ON_VALUE = %_VN_VALUE.
%_OP_VALUE = %_VP_VALUE.
CLEAR %_OI_TAB.
REFRESH %_OI_TAB.
LOOP AT %_VI_TAB.
  %_OI_TAB = %_VI_TAB.
  APPEND %_OI_TAB.
ENDLOOP.
  ENDCASE.
ENDFORM.
FORM GET_EXCEPTION_DIFFERENCE
 TABLES DIFFERENCES STRUCTURE UNTERSCHIED.
 IF VEXCEPTION NE OEXCEPTION.
   MOVE 'EXCEPTION' TO DIFFERENCES-PARAMETER.
   IF VEXCEPTION = SPACE.
     MOVE '-' TO DIFFERENCES-ALT.
   ELSE.
     MOVE VEXCEPTION TO DIFFERENCES-ALT.
   ENDIF.
   IF OEXCEPTION = SPACE.
     MOVE '-' TO DIFFERENCES-NEU.
   ELSE.
     MOVE OEXCEPTION TO DIFFERENCES-NEU.
   ENDIF.
   APPEND DIFFERENCES.
  ENDIF.
ENDFORM.
FORM COMPARE_DATA
                  TABLES DIFFERENCES STRUCTURE UNTERSCHIED
                  USING FIELD
                  CHANGING RETCODE.
 DATA : SUBRC LIKE SY-SUBRC.
 field-symbols: <l_f1> type x.
 field-symbols: <l_f2> type x.
 RETCODE = '='.
 CLEAR DIFFERENCES.
 CASE FIELD.
 WHEN 'O_VALUE'.
IF %_OO_VALUE
NE %_VO_VALUE.
RETCODE = SPACE.
MOVE FIELD TO DIFFERENCES-PARAMETER.
assign %_VO_VALUE to <l_f1> casting.
assign differences-alt to <l_f2> casting.
<l_f2> = <l_f1>.
assign %_OO_VALUE to <l_f1> casting.
assign differences-neu to <l_f2> casting.
<l_f2> = <l_f1>.
APPEND DIFFERENCES.
ENDIF.
 WHEN 'C_VALUE'.
IF %_OC_VALUE
NE %_VC_VALUE.
RETCODE = SPACE.
MOVE FIELD TO DIFFERENCES-PARAMETER.
assign %_VC_VALUE to <l_f1> casting.
assign differences-alt to <l_f2> casting.
<l_f2> = <l_f1>.
assign %_OC_VALUE to <l_f1> casting.
assign differences-neu to <l_f2> casting.
<l_f2> = <l_f1>.
APPEND DIFFERENCES.
ENDIF.
 WHEN 'N_VALUE'.
IF %_ON_VALUE
NE %_VN_VALUE.
RETCODE = SPACE.
MOVE FIELD TO DIFFERENCES-PARAMETER.
assign %_VN_VALUE to <l_f1> casting.
assign differences-alt to <l_f2> casting.
<l_f2> = <l_f1>.
assign %_ON_VALUE to <l_f1> casting.
assign differences-neu to <l_f2> casting.
<l_f2> = <l_f1>.
APPEND DIFFERENCES.
ENDIF.
 WHEN 'P_VALUE'.
IF %_OP_VALUE
NE %_VP_VALUE.
RETCODE = SPACE.
MOVE FIELD TO DIFFERENCES-PARAMETER.
assign %_VP_VALUE to <l_f1> casting.
assign differences-alt to <l_f2> casting.
<l_f2> = <l_f1>.
assign %_OP_VALUE to <l_f1> casting.
assign differences-neu to <l_f2> casting.
<l_f2> = <l_f1>.
APPEND DIFFERENCES.
ENDIF.
WHEN 'I_TAB'.
DO.
READ TABLE %_OI_TAB INDEX SY-INDEX.
SUBRC = SY-SUBRC.
READ TABLE %_VI_TAB INDEX SY-INDEX.
IF SY-SUBRC NE 0 AND SUBRC NE 0.
EXIT.
ELSEIF SY-SUBRC NE 0.
RETCODE = SPACE.
MOVE FIELD TO DIFFERENCES-PARAMETER.
assign %_OI_TAB to <l_f1> casting.
assign differences-neu to <l_f2> casting.
<l_f2> = <l_f1>.
APPEND DIFFERENCES.
EXIT.
ELSEIF SUBRC NE 0.
RETCODE = SPACE.
MOVE FIELD TO DIFFERENCES-PARAMETER.
assign %_VI_TAB to <l_f1> casting.
assign differences-alt to <l_f2> casting.
<l_f2> = <l_f1>.
APPEND DIFFERENCES.
EXIT.
ELSEIF %_VI_TAB
NE %_OI_TAB.
RETCODE = SPACE.
MOVE FIELD TO DIFFERENCES-PARAMETER.
assign %_VI_TAB to <l_f1> casting.
assign differences-alt to <l_f2> casting.
<l_f2> = <l_f1>.
assign %_OI_TAB to <l_f1> casting.
assign differences-neu to <l_f2> casting.
<l_f2> = <l_f1>.
APPEND DIFFERENCES.
EXIT.
ENDIF.
ENDDO.
WHEN 'EXCEPTION'.
IF VEXCEPTION NE OEXCEPTION.
RETCODE = SPACE.
MOVE FIELD      TO DIFFERENCES-PARAMETER.
MOVE VEXCEPTION TO DIFFERENCES-ALT.
MOVE OEXCEPTION TO DIFFERENCES-NEU.
APPEND DIFFERENCES.
ENDIF.
  ENDCASE.
ENDFORM.