  METHOD READ_DATA_FROM_DB.

    ME->READ_FMFINCODE( ).
    CHECK MT_FUND IS NOT INITIAL.
    ME->READ_FMBDT( ).
    ME->FILTER_FUND( ).
    CHECK MT_FUND IS NOT INITIAL.
    ME->READ_FMIT( ).
    ME->READ_PROJECT( ).
    ME->READ_AVC( ).
    CHECK MT_PROJECT IS NOT INITIAL.
    ME->READ_COOI_BPEJ( ).

  ENDMETHOD.