CLASS YCL_YPS8_BCS_BL DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

PUBLIC SECTION.

  DATA MT_RESULT TYPE YTTFM_DATA_REP_2 .

  METHODS CONSTRUCTOR .
  METHODS DISPLAY_ALV
    IMPORTING
      !IV_REPID TYPE SY-REPID DEFAULT SY-REPID .
  METHODS GET_DATA .
  METHODS SET_SELECTION_VALUES
    IMPORTING
      !IV_SELNAME TYPE RSSCR_NAME
      !IV_KIND TYPE RSSCR_KIND
      !IV_VALUE TYPE ANY OPTIONAL
      !IT_VALUE TYPE ANY TABLE OPTIONAL .