* === IMPORT_PARAMETER ===
PARAMETER=I_TREE_TYPE | TYP=DMEE_TREETYPE_ABA
PARAMETER=I_TREE_ID | TYP=DMEE_TREEID_ABA
PARAMETER=I_ITEM
PARAMETER=I_PARAM
PARAMETER=I_UPARAM
PARAMETER=I_EXTENSION | REFERENCE=X | TYP=DMEE_EXIT_INTERFACE_ABA
* === EXPORT_PARAMETER ===
PARAMETER=O_VALUE | REFERENCE=X
PARAMETER=C_VALUE | REFERENCE=X
PARAMETER=N_VALUE | REFERENCE=X
PARAMETER=P_VALUE | REFERENCE=X
* === TABLES_PARAMETER ===
PARAMETER=I_TAB